### ISSUE TITLE
Test case does not appear

### ISSUE THREAD

**Issue by sharwell** [nunit/nunit#3203] opened 2019-04-04 22:23 UTC
The following test case does not appear in Test Explorer (NUnit 3.11.0):

```csharp
        [TestCaseSource(nameof(GetHasDiagnosticCases))]
        public async Task HasDiagnosticCases(string code)
        {
        }

        public static IEnumerable<string> GetHasDiagnosticCases()
        {
            yield return @"
struct S {
    private readonly long l1,l2; 
}
public class C {
    private readonly S _s;
    private ref readonly S GetS() => ref _s;
    private static void Test() {
       string s = {|CS0120:GetS|}().ToString(){|CS1002:|}
    }
}";
        }
```

However, the test does appear if it is changed as follows:

```diff
         public static IEnumerable<string> GetHasDiagnosticCases()
         {
             yield return @"
 struct S {
     private readonly long l1,l2; 
 }
 public class C {
     private readonly S _s;
     private ref readonly S GetS() => ref _s;
     private static void Test() {
-       string s = {|CS0120:GetS|}().ToString(){|CS1002:|}
+       string s = {|CS0120:GetS()|}.ToString(){|CS1002:|}
     }
 }";
         }
```

**Comment by CharliePoole** [comment] 2019-04-05 08:09
If this is a problem only in Test Explorer, we should move the issue to the NUnit3 VS Test Adapter.

But let's first see if that's the case. What happens if you use the NUnit3 console to explore the test?

```
nunit3-console <path to your test assembly> --explore
```

That will give you a console dump of all the tests found. Alternatively, send the output to a file or use `--explore:filename` to save the output as XML.

If your test shows up in the above experiment, then it's a problem for the adapter. Otherwise, we can continue here.

And here's a second experiment to try, using Test Explorer this time...

Comment out all test cases except the one in question. Does it appear? If it does, that means that truncation of the test name (specifically the string argument) was causing it to look like a duplicate of some other test. If so, we can talk about how to deal with that.

**Comment by jnm2** [comment] 2019-04-05 12:31
My gut says this is either the VSTest adapter *or* VSTest's source-based discovery which doesn't involve any of our code and which was designed without our knowledge or invitation for review as far as I know. (This disappoints me, because I'd really like the chance to sink my teeth into it.) Source-based discovery is a low-fidelity approximation of what our VSTest adapter does and it's been a generous source of bugs.

So I'd be interested to know if you see the same thing with source-based discovery disabled.

![image](https://user-images.githubusercontent.com/8040367/55627901-4617bc80-577d-11e9-822d-0c0787c8e3d5.png)

**Comment by CharliePoole** [comment] 2019-04-05 13:14
Good point! I'd forgotten about source-based discovery!

**Comment by Igneous01** [comment] 2019-04-19 00:30
I am running into a similar issue. However the mechanics that trigger it are a little different. 

You can see that here: https://github.com/nunit/nunit3-vs-adapter/issues/515#issuecomment-484729416

I've commented out all my tests except for the one using TestCaseSource and checked using both nunit3-console and nunit3-testadapter. Neither appears to detect any test cases.
![image](https://user-images.githubusercontent.com/5571589/56398782-76993500-6218-11e9-852b-7e94380ceed0.png)

I was looking for the Test Options based on the screenshot above but I was unable to find it. Is this under Visual Studio Options?

**Comment by CharliePoole** [comment] 2019-04-19 08:42
Are you saying that the console runner simply hangs at this point and displays nothing further?

**Comment by mikkelbu** [comment] 2019-04-19 20:44
@Igneous01 I've commented in the other issue in more detail. The reason for why no test cases are generated is that you are extracting all the properties of a class that only contain fields.

**Comment by Igneous01** [comment] 2019-04-19 23:45
@CharliePoole the console terminated successfully. Definitely no hangs.

@mikkelbu thank you for pointing this out. Definitely a slip up on my part that I missed.

**Comment by CharliePoole** [comment] 2019-04-20 02:06
@Igneous01 I asked because your screen shot shows no output after listing the file name.

**Comment by mikkelbu** [comment] 2019-08-30 22:08
@sharwell I've just tested this using VS ver 16.3.0 preview, NUnit ver 3.12, and the test adapter ver 3.15.1, and on my machine the testcase appears - although with a bit long test name 😄 (perhaps return instances of `TestCaseData` with appropriate names).

I'm closing this issue, as I don't think that there is anything left to do, please comment and/or reopen the issue if you disagree.

![image](https://user-images.githubusercontent.com/1007631/64053325-21840d00-cb82-11e9-9365-739f041dd5b9.png)

**Closed by mikkelbu** 2019-08-30 22:08 UTC
Labels: confirm
