### ISSUE TITLE
TestCaseSource using multiple arguments

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit#3771] opened 2021-02-16 19:44 UTC
I have the below code, Can you see or let me know if it is possible to only declare couple of parameters which are required for my test, I don't want to pass all the parameters as I am almost returning 40 from my excel

```csharp
public static IEnumerable<TestCaseData> TestData()
{
    return Framework.ExcelDataReader.ReadExcel(Excelfilename,Excelfiletab);
    //here my excel returns 40 values for the test cases and i cannot mention 40 values  in the below test, i want to use whatever required for me when i use Array or List object it is giving the below Error.
}
```

Test

```csharp
[TestCaseSource(nameof(TestData))]
public void Test(List<object> data)
{
}
```

Error: if I use the above code it is saying  Too many arguments provided, provide at most 1 argument

Please help

**Comment by rprouse** [comment] 2021-02-16 19:56
I assume you are using https://github.com/ExcelDataReader/ExcelDataReader?

As far as I know, it doesn't return a collection of `TestCaseData` objects. You need to capture the return from `Framework.ExcelDataReader.ReadExcel(Excelfilename,Excelfiletab);` and pull out the columns you want. I don't know the library, so I can't really help, but the code might look something like,

```csharp
public static IEnumerable<TestCaseData> TestData()
{
    return Framework.ExcelDataReader
          .ReadExcel(Excelfilename,Excelfiletab)
          .Select(c => new TestCaseData(c[0], c[3], c[6], c[12]))
}

[TestCaseSource(nameof(TestData))]
public void Test(object column0, object column3, object column6, object column12)
{
}
```

I'm just guessing at the API for the Excel Reader, but what I'm trying ot show is pulling out the various columns that you want from each row in the spreadsheet.

**Comment by gnaneswarreddy** [comment] 2021-02-16 21:09
> I assume you are using https://github.com/ExcelDataReader/ExcelDataReader?
> 
> As far as I know, it doesn't return a collection of `TestCaseData` objects. You need to capture the return from `Framework.ExcelDataReader.ReadExcel(Excelfilename,Excelfiletab);` and pull out the columns you want. I don't know the library, so I can't really help, but the code might look something like,
> 
> ```cs
> public static IEnumerable<TestCaseData> TestData()
> {
>     return Framework.ExcelDataReader
>           .ReadExcel(Excelfilename,Excelfiletab)
>           .Select(c => new TestCaseData(c[0], c[3], c[6], c[12]))
> }
> 
> [TestCaseSource(nameof(TestData))]
> public void Test(object column0, object column3, object column6, object column12)
> {
> }
> ```
> 
> I'm just guessing at the API for the Excel Reader, but what I'm trying ot show is pulling out the various columns that you want from each row in the spreadsheet.

Thankyou @rprouse I am using this https://github.com/asmaafawzy/NUnit-DataDriven-tests-from-Excel-files
 ExcelDataReader i am using this code in the Framework project, but when i tried your code it is giving error at TestCaseData(c[0], c[3], c[6], c[12]) (Cannot apply indexing[] to an expression of type TestCaseData)

**Comment by rprouse** [comment] 2021-02-16 21:11
As I said, I don't know the API to that project. You will need to figure that out yourself 😉

**Comment by gnaneswarreddy** [comment] 2021-02-16 21:15
Even i tried to fix the TestCaseData(c[0], c[3], c[6], c[12]) and include your parameters like below it saying the same thing
[TestCaseSource(nameof(TestData))]
public void Test(object column0, object column3, object column6, object column12)
{
}
    Too many arguments provided, provide at most 2 arguments. :(

**Comment by gnaneswarreddy** [comment] 2021-02-17 21:15
@rprouse Thankyou you have been great help.. I was able to get the values, I can close this but before that in the same question
I am also passing test to run different browsers using another testcasesource as given below but that has browserName as parameter,  both are there in different class files, how to combine if i give different test case sources it is showing two methods in test explorer. Anyway to combine them?
[TestCaseSource(nameof(TestData))]
[TestCaseSource(nameof(GetBrowsers))]
public void Test(object column0, object column3, object column6, object column12)
{
}

**Comment by mikkelbu** [comment] 2021-02-17 21:49
@gnaneswarreddy I only get one method - which version of the adapter are you using?
```csharp
    [TestCaseSource(nameof(Source1))]
    [TestCaseSource(nameof(Source2))]
    public void TestMultipleSources(string input)
    {
        Assert.That(input, Is.Not.Null);
    }

    public static IEnumerable<string> Source1 => new[] { "Test1", "Test2", "Test3" };
    public static IEnumerable<string> Source2 => new[] { "Test4", "Test5", "Test6" };
```
gives the following in test explorer

![image](https://user-images.githubusercontent.com/1007631/108272239-42736000-7172-11eb-95a6-de447b4f098e.png)

**Comment by gnaneswarreddy** [comment] 2021-02-17 22:27
@mikkelbu I am able to see it but my testcasesource is different and i am getting issue 

[TestCaseSource(nameof(Source1))]
 [TestCaseSource(nameof(Source2))]
    public void TestMultipleSources(string browserToRun, Object Test1, Object Test2, Object Test3 ) //Either string Test4 is working or Object Test1, Object Test2, Object3 both at same time i am not able to pass and run them, but i need both of them
    {
        Assert.That(input, Is.Not.Null);
    }

    public static IEnumerable<TestCaseData> Source1 => new[] { "Test1", "Test2", "Test3" };
    public static IEnumerable<string> Source2 => new[] { "browserToRun" };

Not enough aruguments provided, provide atleast 2 arguments error is coming if i try to run them

**Comment by mikkelbu** [comment] 2021-02-18 11:42
I don't think you can combine `TestCaseData` with additional parameters, as `TestCaseData` should provide all the parameters. You could extract a tuple from the `TestCaseData` (or just make `ReadExcel` return a tuple) then you can do it like this

```csharp
    [Test]
    public void TestMultipleSources([ValueSource(nameof(Source2))] string browserToRun, [ValueSource(nameof(Source1))] (string Test1, string Test2, string Test3) data)
    {
        Assert.That(browserToRun, Is.Not.Null);
    }

    public static IEnumerable<(string Test1, string Test2, string Test3)> Source1 => new []
    {
        ("Test1", "Test2", "Test3"),
        ("TestA", "TestB", "TestC")
    };
    public static IEnumerable<string> Source2 => new[] { "browserToRun1", "browserToRun2" };
```
This gives us 4 tests (the combination of the two `ValueSources`
![image](https://user-images.githubusercontent.com/1007631/108352065-a20b5300-71e6-11eb-8093-952a5c42259d.png)

**Comment by gnaneswarreddy** [comment] 2021-02-18 18:47
@mikkelbu I think the browsertoRun can be tuple but TestCasedata is something i want dynamically as i want to change data in excel when ever required and it should be loaded dynamically, Also i need 1 test method instead of multiple test methods which will run for different browsers. so TestcaseData can be tuple but how to convert it for excel getting dynamic data.

This is the excel reader i am using https://github.com/asmaafawzy/NUnit-DataDriven-tests-from-Excel-files
Please Advice.

**Comment by mikkelbu** [comment] 2021-02-18 21:15
@gnaneswarreddy The current implementation of https://github.com/asmaafawzy/NUnit-DataDriven-tests-from-Excel-files returns a sequence of `TestCaseData`. `TestCaseData` is an abstraction of all the data that a parameterized test needs (plus some additional information). So you cannot use `TestCaseData` and also use some additional information from another source (either you place all the data in `TestCaseData` or you use separate sources - and create suitable data classes for these sources).

Note that NUnit does not know if a `ValueSource`, `TestCaseSource`, ...  gets is data from a hardcoded list or dynamically from a file in the file system, so this should not change anything.

So you have multiple solutions:
* Change `ReadFromExcel` from https://github.com/asmaafawzy/NUnit-DataDriven-tests-from-Excel-files so that it also returns the browser to use along with the data from the Excel sheet)
* Change `ReadFromExcel` to return the data (using some data class) and then get the information about the browser from another source and the use these two source like I did above for string and tuples (using the appropriate types for your case).
* Use the current solution you have for the Excel Sheet and then get the information for the browser via a `TestFixtureSource` - https://docs.nunit.org/articles/nunit/writing-tests/attributes/testfixturesource.html and an parameter in the constructor. This will give you one test fixture per browser.

**Comment by gnaneswarreddy** [comment] 2021-02-19 19:20
Thankyou @mikkelbu I was able to go with the third option but the browser is launching twice
it is calling the constructor twice when i debugged and checked not sure why, below is the template

using NUnit.Framework;
using System;
using System.Collections;
using System.Linq;


namespace NUnitTestProject1
{
    [TestFixture]
    [Parallelizable(ParallelScope.All)]
    [FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
    [TestFixtureSource(typeof(BrowserData))]

public class FirstTest : Base //Base has the driver setup to launch browser and called Ienumerable BrowserData
{
public FirstTest (string browser)
{
SetUp(browser); //This is called twice not sure the reason
}

TestCaseSource(nameof(ExcelData)) //This has excel details
public void Test(string Test1)
{
}

**Comment by mikkelbu** [comment] 2021-02-19 22:20
Regarding the constructor then it seem like a bug (but I've only scratche the surface of this).

Regarding `Parallelizable` did you create another test in the same class? How did you run the tests (note that the nunit adapter disables parallel execution when debugging
https://github.com/nunit/nunit3-vs-adapter/blob/cdcb686e326363b69498959efe0be122c0c47406/src/NUnitTestAdapter/NUnitTestAdapter.cs#L201-L205)

**Comment by gnaneswarreddy** [comment] 2021-02-20 01:17
@mikkelbu Parallel execution i am doing in seperate class files, within the class files it is running in parallel. But i need parallel execution within different class files if possible and also help need for the fix of the constructor issue which is running twice.

**Comment by gnaneswarreddy** [comment] 2021-02-20 04:42
@rprouse @mikkelbu 
I see you have commented in one of this posts which was closed. But my scenario is SetUp() and Teardown() is there in different assembly then how can i use based on the below example template, the same issue is happening for me opening two browsers but you mentioned that to use local variables with setup and teardown methods

//Previous post
you are definitely having a problem with threading. NUnit creates one copy of your test class and runs all SetUp -> Test -> TearDown in parallel, so if any of those are creating, destroying, or possibly even accessing the same member variables in your class, then your tests are going to stomp on each other.

In your case, two setup methods run in parallel creating the two browser windows, but you are using one variable to control both, so it gets overwritten by the second call. All of your tests then run in the one browser window because the reference to the second was lost.

The easiest way to fix this is to only use local variables in your test methods and do the setup and teardown in those methods.

As @jnm2 states, there are plans to support scenarios like yours more safely by instantiating a copy of the test class for each test. That is expensive and slows down performance, so it would not be the default.

//My template
using NUnit.Framework;
using System;
using System.Collections;
using System.Linq;

namespace NUnitTestProject1
{
[TestFixture]
[Parallelizable(ParallelScope.All)]
[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
[TestFixtureSource(typeof(BrowserData))]

public class FirstTest : Base //Base has the driver setup to launch browser and called Ienumerable BrowserData
{
public FirstTest (string browser)
{
SetUp(browser); //This is called twice not sure the reason //This is present in Base class
}

TestCaseSource(nameof(ExcelData)) //This has excel details
public void Test(string Test1)
{
}

**Comment by mikkelbu** [comment] 2021-02-21 23:24
@gnaneswarreddy I'm not sure which closed issues you are referring to (I've commented on more than 250 closed issues), but it sounds like the issue is describing the a problem before the introduction of `[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]` were one had to take more care to make tests parallelizable (aka don't use shared state).

Regarding you problem above with `[Parallelizable(ParallelScope.All)]` then I don't think that just marking this class will make it run in parallel with another class unless the other class is also decorated (and inside the same namespace). You can use the attribute on assembly level if you want to run all tests in parallel, i.e. `[assembly: Parallelizable(ParallelScope.None)]`

Regarding the problem that the constructor is called multiple times I would recommend that you setup the browser using a setup method - https://docs.nunit.org/articles/nunit/writing-tests/attributes/setup.html - rather that in constructor, then I guess/hope that this is only called once.

**Comment by gnaneswarreddy** [comment] 2021-02-24 22:40
@mikkelbu Thankyou I was able to run using the SetUp(SetUp(browser); and is only called once now) but in my browser in app.config  I am giving like this chrome, IE where previously if I use IEnumberable and TestFixtureSource i was able to run chrome and IE successfully but as I am using direct Setup method I am able to run  only using chrome, How can I achieve running chrome and IE for the same test run? Any thoughts would really help?

**Comment by mikkelbu** [comment] 2021-02-25 09:24
I was not proposing that you should remove `TestFixtureSource`. Just that you moved the logic from the constructor to a setup method.

**Comment by gnaneswarreddy** [comment] 2021-02-25 14:44
@mikkelbu i tried doing that by adding TestFixtureSource but it says suitable constructor was not found, i am confused what I need to define in constructor as without constructor it is giving an error.

**Comment by mikkelbu** [comment] 2021-02-25 15:06
But you had a constructor in the code above ???. I was proposing that:
* You keep the constructor, but this should only set the browser in a local field
* Do the setup work in a setup method instead of in the constructor

So to take your code above and change it into
```csharp
using NUnit.Framework;
using System;
using System.Collections;
using System.Linq;

namespace NUnitTestProject1
{
    [TestFixture]
    [Parallelizable(ParallelScope.All)]
    [FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
    [TestFixtureSource(typeof(BrowserData))]
    public class FirstTest : Base //Base has the driver setup to launch browser and called Ienumerable BrowserData
    {
        private readonly string browser; 

        public FirstTest (string browser)
        {
                this.browser = browser;
        }

        [SetUp]
        public void SetUp()
        {
            SetUp(browser);
        }

        [TestCaseSource(nameof(ExcelData))] //This has excel details
        public void Test(string Test1)
        {
        }
    }
}
```

**Comment by gnaneswarreddy** [comment] 2021-03-19 01:09
@mikkelbu  Thankyou i am able to get this but i have few questions below related to TestCaseSource
In Excel i have the below data

TestmethodName | Param1 | Param2 | Param3
Test1     |                     User    | Password | Login
Test2     |                     User2   | Password2| Login

I am using the below method
[TestCaseSource(nameof(ExcelData))] //This has excel details
        public void Test1(string Test1)    //This is returning all the rows but i need the data for just Test1 only
        {
        }

[TestCaseSource(nameof(ExcelData))] //This has excel details
        public void Test1(string Test1)    //This is returning all the rows but i need the data for just Test2 only
        {
        }

How can we return only required set of data based on test method name?

**Comment by mikkelbu** [comment] 2021-03-23 21:42
Closing this as discussion have moved to #3796

**Closed by mikkelbu** 2021-03-23 21:42 UTC
Labels: is:question
