### ISSUE TITLE
NUnit 4.0 fails when [Repeat] is present and test passes

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4491] opened 2023-10-10 17:32 UTC
Trying out the new v4 preview on my test suites, I got the following issue

This passing test does not appear in the test results:
```csharp
public class Tests
{
    [Test]
    [Repeat(30)]
    public void Test1()
    {
        bool x = true;
        Assert.That(x, Is.True);
    }
}
```

Running `dotnet test` yields
``` 
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in C:\Users\rende\source\repos\NUnitRepro\NUnitRepro\bin\Debug\net7.0\NUnitRepro.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

whereas the test
```csharp
public class Tests
{
    [Test]
    [Repeat(30)]
    public void Test1()
    {
        bool x = true;
        Assert.That(x, Is.False);
    }
}
```

yields
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Test1 [26 ms]
  Error Message:
     Assert.That(x, Is.False)
  Expected: False
  But was:  True

  Stack Trace:
     at Tests.Test1() in C:\Users\rende\source\repos\NUnitRepro\NUnitRepro\UnitTest1.cs:line 8

1)    at Tests.Test1() in C:\Users\rende\source\repos\NUnitRepro\NUnitRepro\UnitTest1.cs:line 8



Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 26 ms - NUnitRepro.dll (net7.0)
```

**Comment by OsirisTerje** [comment] 2023-10-10 18:51
Thanks @RenderMichael  !     This is really weird.  I do get the same result.

The repro is here:  https://github.com/nunit/nunit.issues/tree/main/Issue4491

It is the Repeat attribute that seems to cause this.

**Comment by OsirisTerje** [comment] 2023-10-10 20:50
I added an ordinary test (see repro), and enabled dumping of the xml, and it looks like the Repeat attribute changes the NUnit ID.
That is not good.

This is the two tests:
![image](https://github.com/nunit/nunit/assets/203432/7e787e11-0d9b-4cb0-a274-28eddf6d8de7)

Test2 is the one with the repeat attribute, and have the Id = 0-1001.  Test3 is the ordinary test, with the Id = 0-1002.

From the NUnitTestEvents, we get these two for the test cases:
![image](https://github.com/nunit/nunit/assets/203432/93757fb6-a91d-4b3a-be86-c8e509947123)

Note that Test2 now have the Id = 0-1037, whereas Test3 still have the Id = 0-1002.

So, it looks like the Repeat command somehow sets a new number, an Id that doesn't exist in the discovery at all.

**Comment by OsirisTerje** [comment] 2023-10-10 21:01
Adding writing out the test id to the output, the following is displayed (changed the repeat to 5), 
![image](https://github.com/nunit/nunit/assets/203432/f295be4e-40e5-4f1e-94ab-097f236690d2)

So, the repeat attribute increments the Id, starting from the highest current one, which was 1007.

**Comment by OsirisTerje** [comment] 2023-10-10 21:19
And in RepeatAttribute.cs, class RepeatedTestCommand,

![image](https://github.com/nunit/nunit/assets/203432/943a8153-d00d-49d9-84d0-89bea89b5935)

The Id is updated.  If this also had happened for discovery, it would have been better, but it would still fail when RTD is used in VS TE.

**Comment by RenderMichael** [comment] 2023-10-10 21:22
Just double-checked whether `[Theory]` has the same issue, since there ID is changed there as well. That works fine.

**Comment by OsirisTerje** [comment] 2023-10-10 21:33
Where do you see Id change in Theory?

**Comment by RenderMichael** [comment] 2023-10-10 21:47
It would be really nice if, as part of this fix, [Repeat] tests could appear in Test Explorer the same way as [Theory] tests, with children nodes.

However, that may be hard since repeat has a variable number of children, depending on when/if a test fails. I doubt changing [Repeat]'s behavior to always run, even on failure, is desirable.

However, [Repeat] worked in latest v3 so if it could be working again, that would be great enough for me.

**Comment by OsirisTerje** [comment] 2023-10-11 06:57
@RenderMichael   Since you've already been into the code, would you mind having a look at what has changed between v3 and v4 here?

**Comment by RenderMichael** [comment] 2023-10-12 07:18
@OsirisTerje I spent a bit of time looking into this and I can't pinpoint why or even when it started failing. The attribute itself hasn't changed in years.

All I managed to figure out is, this has been failing for a while. A couple years, if I haven't made any crucial mistakes.

**Comment by OsirisTerje** [comment] 2023-10-12 09:12
@RenderMichael Ok, so it doesnt work in 3.13.3 either ?

**Comment by OsirisTerje** [comment] 2023-10-14 08:26
@nunit/framework-team This issue broke in this release, worked in 3.13.3, no apparent changes, but could be a side effect of some other change that was done early 2021.  
It would be nice to have this fixed, even if it is an attribute that is not much used.  It may be other similar attributes having the same fault though.  
It also passed all tests, meaning we're lacking a test for this case.

If we can't fix this before final release, it has to go on a known-bugs list.

**Comment by manfred-brands** [comment] 2023-10-22 10:31
@OsirisTerje The `SetNextId` call you point at was added by @asos-tomlonghurst and also affects `Retry` 
It doesn't reference an issue and I can't even find an issue nor pr assigned to him.
It was his only contribution and I don't know what it was addressing.

**Comment by stevenaw** [comment] 2023-10-22 13:41
Within #3974 ? Good sleuthing @manfred-brands 
That PR explicitly mentions that it aims to create new IDs for repeated runs which seems contrary to how it needs to work based on what we've discovered here.

@asos-tomlonghurst can you explain a bit about what you trying to solve. I'm curious if we can help suggest alternatives to having this id change between runs

**Comment by manfred-brands** [comment] 2023-10-25 11:38
@rprouse You reviewed that PR, can you  remember what it was for?

**Comment by rprouse** [comment] 2023-10-25 23:20
I don't remember more than what is in the PR, sorry.

**Comment by manfred-brands** [comment] 2023-10-26 03:40
So that PR ensured unique-id, but nobody is expecting that and it breaks other tools/parsers.
Should we then revert that PR?
Is there any other way a consumer can find out that a test needed repeating?

**Comment by stevenaw** [comment] 2023-10-26 11:55
I'm ok with reverting it since it hasn't been included in a stable release yet - though I'd suggest we also revert it from the 3.x branch to avoid it accidentally going out there too. Does anyone else in @nunit/framework-team feel differently?

We can also help the contributor of that PR look for alternative ways of supporting their use case once we understand why they wanted unique IDs here

**Comment by mikkelbu** [comment] 2023-10-26 12:26
I agree that we should revert it (especially since we are unsure of what this solves and it blocks the release). Then we can always improve on this later on.

If we revert it, then it would be nice with also a test that captures the expected behaviour (before #3974)

**Comment by OsirisTerje** [comment] 2023-10-26 15:54
Also agree we revert it, but as @mikkelbu says, nice to get a good test in there.

Since the PR has no linked issue, we can't reopen that non-existing issue.  
@thomhurst If this is still an issue for you, can you please open an issue with the details, and we can take your situation from there?

**Comment by thomhurst** [comment] 2023-10-26 16:07
Sorry guys. I wasn't aware changing that ID would break things.

I had a test framework that was collecting test results for a report, and using that ID as a unique key for every different test/execution. If I had a Repeat(5), I still wanted to collect the 5 separate runs to report on. Because this id didn't change, results were being overwritten and only one stored.

If it's breaking things then definitely revert it and I apologize. I just needed a unique identifier and I thought that's what the purpose of that property was.

**Comment by OsirisTerje** [comment] 2023-10-26 16:12
@thomhurst A bit out of the head, haven't checked this properly, but just throwing it out:   I wonder if this setting in the adapter could help here:  https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#newoutputxmlfileforeachrun    Setting it would create a separate test result file for each test run.  That is, if the Repeat/Retry attributes actually produces separate outputs.

**Comment by thomhurst** [comment] 2023-10-26 16:20
I wasn't even using the xmls, I was grabbing it during execution via the TestContext.Current.Test.Id (or whatever it is, I'm on mobile) property. Maybe a second property could be useful that's unique for every execution. Just thinking out loud

**Closed** 2023-10-26 18:33 UTC
Labels: is:bug, brokenInUpgrade
