### ISSUE TITLE
assembly.config not found when running from .nunit project

### ISSUE THREAD

**Issue by agentHoover** [nunit/nunit#944] opened 2015-10-28 20:45 UTC
I have several different test assemblies in various folders that I have configured using an nunit project file. 
Here is the contents of the config. 

````<NUnitProject>
<Settings activeconfig="active" appbase="c:\projects\hyena\source\Tests\"/>
	<Config name="active" binpath="Buzzard.Tests.Unit\bin\Debug\;FileService.Test.Unit\bin\Debug\;Hyena.Tests.Framework.Unit\bin\Debug\">
		<assembly path="Buzzard.Tests.Unit\bin\Debug\Buzzard.Tests.Unit.dll"/>
		<assembly path="FileService.Tests.Unit\bin\Debug\FileService.Tests.Unit.dll"/>
		<assembly path="Hyena.Tests.Framework.Unit\bin\Debug\Hyena.Tests.Framework.Unit.dll"/>
	</Config>
</NUnitProject>
````

 Each test assembly has its own config file named to match the test assembly (i.e. Buzzard.Tests.Unit.dll.config) that resides next to the corresponding test assembly. 

The nunit project file resides in the appbase directory.  

When I run this from the command line with the following 
    ` 'C:\Program Files (x86)\NUnit.org\bin\nunit-console.exe' testconfig.nunit`
the test assemblies are not able to find their own config files.  I logged the `AppDomain.CurrentDomain.SetupInformation.ConfigurationFile` to see what was being picked up and the output was basically the correct file name in the wrong location:
```` 
FileService.Tests.Unit.FileServiceUnitTests.DeleteFile_SavedFile_DeleteIsNotCalled
c:\projects\hyena\source\Tests\FileService.Tests.Unit.dll.config
````
So in this case I would expect the source for the config to be  `c:\projects\hyena\source\Tests\FileService.Tests.Unit\bin\Debug\FileService.Tests.Unit.dll.config` but it is looking in the appbase folder for that file instead of the location where the test assembly is. 

The same set of suites run without failure through VS with the VS test adapter.  They also work if I just pass the file list for the test assemblies directly to the command line without using the nunit project config. 

I discovered this issue when trying to run the suites through TeamCity on our build server.  TeamCity generates a nunit project on the fly in order to execute the tests through the console.  

I feel like I may be missing something fundamental in my setup because it seems like a pretty common configuration and was surprised that no one else seems to have encountered this issue. 

Thanks,

Allen

**Comment by CharliePoole** [comment] 2015-10-28 21:01
What version of NUnit are you running?

**Comment by agentHoover** [comment] 2015-10-28 21:11
Version 3. Beta 5

**Comment by kristianw87** [comment] 2015-11-03 17:10
I ran into the same issue today with nunit3 RC, and in addition to that the .config files was not found, AppDomain.CurrentDomain.BaseDirectory pointed to the "appbase" folder instead of the "appbase"/../project/bin/debug folder. So this issue is not limited to just .config files.

**Comment by kristianw87** [comment] 2015-11-04 09:46
I did some further testing:

uNmQUN73QWQxXH0iOdOx3IQoUR7rCJvR.nunit file that was generated by TeamCity:
```
<NUnitProject>
  <Settings activeconfig="active" appbase="C:\Stea\Kode\clean" />
  <Config binpath="prog\databasesrc\test\Database.Main.Tests\bin\Debug;prog\databasesrc\test\Database.Core.Tests\bin\Debug" name="active">
    <assembly path="prog\databasesrc\test\Database.Core.Tests\bin\Debug\Database.Core.Tests.dll" />
    <assembly path="prog\databasesrc\test\Database.Main.Tests\bin\Debug\Database.Main.Tests.dll" />
  </Config>
</NUnitProject>
```

When Database.Main.Tests.dll tests were run I outputted the following:
```
Console.WriteLine(string.Format("BaseDirectory: {0}", AppDomain.CurrentDomain.BaseDirectory));
Console.WriteLine(string.Format("ConfigurationFile: {0}", AppDomain.CurrentDomain.SetupInformation.ConfigurationFile));
Console.WriteLine(string.Format("PrivateBin: {0}", AppDomain.CurrentDomain.SetupInformation.PrivateBinPath));
```


Nunit3 RC output : ```.\nunit3\nunit3-console.exe C:\Stea\Kode\uNmQUN73QWQxXH0iOdOx3IQoUR7rCJvR.nunit``` 
```
BaseDirectory: C:\Stea\Kode\clean\
ConfigurationFile: C:\Stea\Kode\clean\Database.Main.Tests.dll.config
PrivateBin: prog\databasesrc\test\Database.Main.Tests\bin\Debug;prog\databasesrc\test\Database.Core.Tests\bin\Debug
```
Tests fail.

Running ```Database.Main.Tests.dll``` directly outputs the following:
``` .\nunit3\nunit3-console.exe C:\Stea\Kode\clean\prog\databasesrc\test\Database.Main.Tests\bin\Debug\Database.Main.Tests.dll````
```
BaseDirectory: C:\Stea\Kode\clean\prog\databasesrc\test\Database.Main.Tests\bin\Debug\ 
ConfigurationFile: C:\Stea\Kode\clean\prog\databasesrc\test\Database.Main.Tests\bin\Debug\Database.Main.Tests.dll.config
PrivateBin:
```
Tests are succesful.


Is this an issue of how TeamCity generates the .nunit files, or should the BaseDirectory always be set to the assembly directory (which in turn also will fix the config file path issue if the BasePath is corrected before AppDomainSetup is created)?

**Comment by rprouse** [comment] 2015-11-05 02:31
@CharliePoole, this was in the 3.0 milestone. I moved it to RC2. Can you look at this? I think we should at least confirm before the next release.

**Comment by CharliePoole** [comment] 2015-11-05 20:23
Yes, this is confirmed. See also issue #719 where we simply treated it as a documentation issue.

Basically, there is no way to use an NUnit project file and have separate configs for each assembly. This is partly historical, since one reason for project files in the first place was to force use of a common config! If you don't need other features  (settings) in the project file, you can simply place all the assemblies on the command line and each one uses its own config.

There are two possible enhancements to consider that could help this. One would be to allow specifying the config for each assembly in the file. The other would be to have a top level setting that told NUnit to use a separate config for each assembly. Neither of them can be done now for 3.0.

BTW, this is exactly how NUnit has worked historically.

**Comment by meriturva** [comment] 2015-11-10 09:10
Actually we have the same identical problem with TeamCity: https://youtrack.jetbrains.com/issue/TW-42399

I mean, TeamCity creates nunit project file automatically but without config reference on it so ...no way to use config file in TeamCity CI solution. I already opened issue on TeamCity bug track but i think that nunit has to handle better that context.

**Comment by CharliePoole** [comment] 2015-11-10 17:17
It may not be true that there is no way to handle it. If NUnit finds a config file of the correct name in the same directory where TC creates the project file, then it will use it. What it won't do currently is use **separate** config files per assembly. The historical workaround has been to combine your config files.

I'm not a TC expert - not really even a user, except occasionally - bit I can imagine some problems with the approach of creating a project file.

1. Many users create their own project files, what happens to them?

2. NUnit 3.0 supports a mix of multiple project files and assemblies on the command line, which would make the creation of a single project file even harder. NUnit 2.6.4 supports one project file plus assemblies.

3. Anything we do to make it easier to use this approach will only apply to NUnit 3.0. We expect that many users will continue to use NUnit 2.6.4 for the next few years in addition to 3.0.

It may be that the JB folks have thought about this and have some solutions. Alternatively, you can always ignore the built-in nunit support and run a script of your own. That's the way we did it in the "old days" anyway. :-)

BTW, NUnit 3.0 is being released without any changes to the config file but it's pretty much ready for changing. We're not sure if we will enhance it or provide a new format to replace it. Of course, the old format will always continue to work.

**Comment by NikolayPianikov** [comment] 2015-11-11 15:00
@CharliePoole App config file is supported from TC 9.1.4

**Comment by CharliePoole** [comment] 2015-11-11 15:12
Corrected my comment above config=>nunit

@NikolayPianikov But is it a config file from the app or a proper .nunit project config file. These have always been different things except for projects containing only one assembly.

NUnit (2) has always required the user to create a separate config for projects that have multiple assemblies, combining all the settings for the different assemblies. This is not really great for the user, of course, but it is how it has worked for years. Do the users who have created such a config have a way to force you to use it?

NUnit 3 is a different matter of course. We can make changes to that.

**Comment by NikolayPianikov** [comment] 2015-11-11 15:25
@CharliePoole Users have the additional "advanced" field "Path to the application configuration file". The value from this field is used for creating nunit project file. Like here
``` xml
<Config configfile="composite.config" >
<assembly path="AssemblyName.Test1.dll"/>
<assembly path="AssemblyName.Test2.dll"/>
</Config>
```
Do you think is a right approach for NUnit 3? Do you have plans to do any change related on this question?

**Comment by NikolayPianikov** [comment] 2015-11-11 15:30
@CharliePoole I would like add some notes to our doc for this. Do we have any posts related to app config file over nunit project?

**Comment by CharliePoole** [comment] 2015-11-11 16:52
@NikolayPianikov Since we are at the RC stage, we are only fixing bugs so no new features are planned for 3.0. I think that 3.2 could bring changes to the nunit project format, but they would be backward compatible. Feel free to propose any ideas you have.

That said, we do have one bug that could result in an immediate change. That's #1015. It relates to what we do for a config file when there is an nunit project and config is not specified. In NUnit 2, we used PROJECT.config as the default config for PROJECT.nunit. It has been suggested that we should default to use of the individual configs so long as the user did not force all the projects to run in the same AppDomain. So watch that one for changes.

**Comment by CharliePoole** [comment] 2015-11-11 16:58
@NikolayPianikov For docs of NUnit 2.6.4 we have
    http://nunit.org/index.php?p=configFiles&r=2.6.4
Of cousre, this can't change.

For NUnit 3.0, these two pages give current information:
    https://github.com/nunit/nunit/wiki/NUnit-Test-Projects
    https://github.com/nunit/nunit/wiki/NUnit-Project-XML-Format
But as I said in my prior post the default config for nunit projects that do not specify one is up in the air at the moment.

**Comment by CharliePoole** [comment] 2015-11-14 13:50
@agentHoover I believe this is fixed as of RC3. Can you retest it?

**Comment by agentHoover** [comment] 2015-12-10 16:29
@CharliePoole - sorry, just now saw this.  I have been off in the weeds with other projects so have not been monitoring this.  I will try to look at this again early next week. Thanks.

**Comment by agentHoover** [comment] 2016-02-16 19:39
Well, I realize it has been 2+ months but just now getting back to this.  I can confirm that it is working for me now.  Thanks.

**Closed** 2016-07-22 11:10 UTC
Labels: bug, pri:normal
