### ISSUE TITLE
[Parallelizable(ParallelScope.Children)] Unable to finish tests 2.8.2

### ISSUE THREAD

**Issue by unickq** [nunit/nunit#2459] opened 2017-09-25 08:50 UTC
Hi there,

#### I have following code:

```
    public class Animal
    {
        public Animal()
        {
            Console.Write("Init. Thread #" + Thread.CurrentThread.ManagedThreadId + " ");
            Thread.Sleep(1000);
        }

        public void Do()
        {
            Console.WriteLine("Done. Thread #" +Thread.CurrentThread.ManagedThreadId + " for " + ToString());
        }
    }

    public class Cat : Animal
    {
        public Cat()
        {
            Console.WriteLine("I'm a cat");
        }

        public override string ToString()
        {
            return "cat";
        }
    }

    public class Dog : Animal
    {
        public Dog()
        {
            Console.WriteLine("I'm a dog");
        }

        public override string ToString()
        {
            return "dog";
        }
    }

    public class Base
    {
        public static readonly ThreadLocal<Animal> ThreadLocalContext = new ThreadLocal<Animal>();
    }

```

#### and tests code:

```
    public class BaseTest<T> where T : Animal, new()
    {
        [SetUp]
        public void SetUp()
        {
            Base.ThreadLocalContext.Value = new T();
        }

        [TearDown]
        public void TearDown()
        {
            Base.ThreadLocalContext.Value.Do();
        }
    }

    [TestFixture]
    [Parallelizable(ParallelScope.Children)]
    [TestFixture(typeof(Dog))]
    [TestFixture(typeof(Cat))]
    public class Test1<T> : BaseTest<T> where T : Animal, new()
    {
        [Test, TestCaseSource(typeof(DataProvider), nameof(DataProvider.TestCases))]
        public void Test(string url)
        {
            Console.WriteLine(url + " " + Base.ThreadLocalContext.Value);
        }
    }

   
    public class DataProvider
    {
        public static IEnumerable TestCases
        {
            get
            {
                yield return new TestCaseData("hello");
                yield return new TestCaseData("hi");
                yield return new TestCaseData("bonjour");
            }
        }
    }
```
**ParallelScope.Children**
I have 8 cores CPU - don't have problems running following 6 tests.

But if I want to run 8 tests - sometimes 1, 2, 3, 4 of 8 hang. Reproducible on NUnit console 3.0 and ReSharper 2017.2

If **[assembly: LevelOfParallelism(2)]** is set - 2 tests run and the other hang
![2](https://user-images.githubusercontent.com/6696821/30799528-d0ac3fc8-a1e5-11e7-8dc0-cb32d205443b.png)
![1](https://user-images.githubusercontent.com/6696821/30800144-b5a44642-a1e7-11e7-8ba3-422bc829c744.png)

Have a workaround for that:
If **[assembly: Parallelizable(ParallelScope.Children)]** is set following problem is not reproduced.

Any ideas about that?
Thank you :)

**Comment by rprouse** [comment] 2017-09-26 00:42
I believe this is a duplicate of #2438. We are working on a fix.

**Comment by rprouse** [comment] 2017-11-05 20:08
I have tested this with the recent parallel fixes that @CharliePoole did. I have a quad core cpu with 8 logical cores. Tests run and report 8 test workers. I tested with the MyGet version 3.9.0-dev-04639 and the tests (upped to 10 instead of 6) ran to completion 10 times without an issue.

Closing as fixed.

**Closed by rprouse** 2017-11-05 20:08 UTC
