### ISSUE TITLE
How to make TestCaseGenericAttribute and TestCaseGenericSourceAttribute?

### ISSUE THREAD

**Issue by Denis535** [nunit/nunit#3580] opened 2020-06-07 22:33 UTC
Because NUnit still hasn't way to set up generics, I decided to do it myself.

`TestCaseGenericAttribute` is simple. Only you should have excess type argument.

    [TestCaseGeneric( typeof( int ), 777 )]
    [TestCaseGeneric( typeof( int ), "777" )]
    [TestCaseGeneric( typeof( object ), "777" )]
    public void Test_00<T>(Type _, T value) {
        Console.WriteLine( typeof( T ) );
        Console.WriteLine( value );
    }

    [AttributeUsage( AttributeTargets.Method, AllowMultiple = true )]
    public class TestCaseGenericAttribute : TestCaseAttribute, ITestBuilder {

        public TestCaseGenericAttribute(object arg) : base( arg ) {
        }
        public TestCaseGenericAttribute(object arg1, object arg2) : base( arg1, arg2 ) {
        }
        public TestCaseGenericAttribute(object arg1, object arg2, object arg3) : base( arg1, arg2, arg3 ) {
        }
        public TestCaseGenericAttribute(params object[] arguments) : base( arguments ) {
        }

        IEnumerable<TestMethod> ITestBuilder.BuildFrom(IMethodInfo method, Test suite) {
            try {
                method = MakeGenericMethod( method, Arguments );
                return base.BuildFrom( method, suite );
            } catch (Exception ex) {
                return GetError( method, suite, ex );
            }
        }

        // Helpers/IMethodInfo
        private static IMethodInfo MakeGenericMethod(IMethodInfo method, object[] arguments) {
            var generics = arguments.Take( method.GetGenericArguments().Length ).Cast<Type>().ToArray();
            return method.MakeGenericMethod( generics );
        }
        // Helpers/TestMethod
        private static TestMethod[] GetError(IMethodInfo method, Test suite, Exception ex) {
            var result = new NUnitTestCaseBuilder().BuildTestMethod( method, suite, new TestCaseParameters( ex ) );
            return new[] { result };
        }

    }

But `TestCaseGenericSourceAttribute` is not simple. I failed to do this because I can not get source `TestCaseData` list before `IEnumerable<TestMethod>` which leads to an error.

    [AttributeUsage( AttributeTargets.Method, AllowMultiple = true )]
    public class TestCaseGenericSourceAttribute : TestCaseSourceAttribute, ITestBuilder {

        public TestCaseGenericSourceAttribute(string sourceName) : base( sourceName ) {
        }
        public TestCaseGenericSourceAttribute(string sourceName, object[] arguments) : base( sourceName, arguments ) {
        }
        public TestCaseGenericSourceAttribute(Type sourceType) : base( sourceType ) {
        }
        public TestCaseGenericSourceAttribute(Type sourceType, string sourceName) : base( sourceType, sourceName ) {
        }
        public TestCaseGenericSourceAttribute(Type sourceType, string sourceName, object[] arguments) : base( sourceType, sourceName, arguments ) {
        }

        IEnumerable<TestMethod> ITestBuilder.BuildFrom(IMethodInfo method, Test suite) {
            try {
                var generics = ...
                method = method.MakeGenericMethod( generics );
                return base.BuildFrom( method, suite );
            } catch (Exception ex) {
                var test = new NUnitTestCaseBuilder().BuildTestMethod( method, suite, new TestCaseParameters( ex ) );
                return new[] { test };
            }
        }

    }

Is it possible to do it?

**Comment by CharliePoole** [comment] 2020-06-07 23:00
Here's the start of the code block that does it for TestFixtures: https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs#L101

**Comment by Denis535** [comment] 2020-06-09 13:46
`TestCaseSourceAttribute` is not very extensible. I was forced to write almost completely my own `TestCaseGenericSourceAttribute`. It works, but I don't like it. I could make some bug. Or it will not work in next versions of NUnit.
Original `TestCaseSourceAttribute`: https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs

        private static readonly TestCaseData[] Args = new TestCaseData[] {
            new TestCaseData( typeof( int ), 777 ),
            //new TestCaseData( typeof( int ), "777" ), // doesn't convert string to int
            new TestCaseData( typeof( object ), "Text" ),
        };
        [TestCaseGenericSource( nameof( Args ) )]
        public void Test_000<T>(Type _, T value) {
            Console.WriteLine( typeof( T ) );
            Console.WriteLine( value );
        }

    [AttributeUsage( AttributeTargets.Method, AllowMultiple = true )]
    public class TestCaseGenericSourceAttribute : TestCaseSourceAttribute, ITestBuilder {

        private const string SourceMustBeStatic = "The sourceName specified on a TestCaseSourceAttribute must refer to a static field, property or method.";
        private const string SourceFieldCannotTakeArguments = "You have specified a data source field but also given a set of parameters. Fields cannot take parameters, please revise the 3rd parameter passed to the TestCaseSourceAttribute and either remove it or specify a method.";
        private const string SourcePropertyCannotTakeArguments = "You have specified a data source property but also given a set of parameters. Properties cannot take parameters, please revise the 3rd parameter passed to the TestCaseSource attribute and either remove it or specify a method.";
        private const string NumberOfArgumentsIsWrong = "You have given the wrong number of arguments to the method in the TestCaseSourceAttribute, please check the number of parameters passed in the object is correct in the 3rd parameter for the TestCaseSourceAttribute and this matches the number of parameters in the target method and try again.";


        public TestCaseGenericSourceAttribute(string sourceName) : base( sourceName ) {
        }
        public TestCaseGenericSourceAttribute(string sourceName, object[] arguments) : base( sourceName, arguments ) {
        }
        public TestCaseGenericSourceAttribute(Type sourceType) : base( sourceType ) {
        }
        public TestCaseGenericSourceAttribute(Type sourceType, string sourceName) : base( sourceType, sourceName ) {
        }
        public TestCaseGenericSourceAttribute(Type sourceType, string sourceName, object[] arguments) : base( sourceType, sourceName, arguments ) {
        }


        IEnumerable<TestMethod> ITestBuilder.BuildFrom(IMethodInfo method, Test suite) {
            var builder = new NUnitTestCaseBuilder();
            try {
                var data = GetSourceData( SourceType ?? method.TypeInfo.Type, SourceName, MethodParams )?.Cast<object>().ToArray() ?? GetError( "The test case source could not be found." );
                var cases = data.Select( i => GetTestCase( i, method ) ).Select( i => SetCategory( i, Category ) ).ToArray();
                var methods = cases.Select( i => GetTestMethod( method, suite, i, builder ) ).ToArray();
                if (!methods.Any() && !method.GetParameters().Any()) {
                    return GetError( method, suite, "TestCaseSourceAttribute may not be used on a method without parameters." );
                }
                return methods;
            } catch (Exception ex) {
                return GetError( method, suite, ex );
            }
        }


        // Helpers/TestMethod
        private static TestMethod GetTestMethod(IMethodInfo method, Test suite, TestCaseParameters @case, NUnitTestCaseBuilder builder) {
            method = MakeGenericMethod( method, @case.Arguments );
            return builder.BuildTestMethod( method, suite, @case );
        }
        private static IMethodInfo MakeGenericMethod(IMethodInfo method, object[] arguments) {
            var generics = arguments.Take( method.GetGenericArguments().Length ).Cast<Type>().ToArray();
            return method.MakeGenericMethod( generics );
        }
        // Helpers/TestCase
        private static TestCaseParameters GetTestCase(object? data, IMethodInfo method) {
            return data switch
            {
                TestCaseData data_ => data_,
                TestCaseParameters @case => @case,
                Array array when array.GetType() == method.GetParameters().SingleOrDefault()?.ParameterType => new TestCaseParameters( new[] { array } ),
                Array array2 when array2.Length == method.GetParameters().Length => new TestCaseParameters( array2.Cast<object?>().ToArray() ),
                { } obj => new TestCaseParameters( new[] { obj } ),
                null => new TestCaseParameters( new object?[] { null } ),
            };
        }
        private static TestCaseParameters SetCategory(TestCaseParameters value, string category) {
            if (category != null) {
                foreach (var i in category.Split( ',' )) {
                    value.Properties.Add( PropertyNames.Category, i );
                }
            }
            return value;
        }
        // Helpers/SourceData
        private static IEnumerable? GetSourceData(Type type, string name, object?[]? arguments) {
            if (name == null) {
                return GetSourceData_( type );
            } else {
                return GetSourceData_( type, name, arguments );
            }
        }
        private static IEnumerable? GetSourceData_(Type type) {
            return (IEnumerable?) Reflect.Construct( type, null );
        }
        private static IEnumerable? GetSourceData_(Type type, string name, object?[]? arguments) {
            var flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance | BindingFlags.FlattenHierarchy;
            return type.GetMember( name, flags ).SingleOrDefault() switch
            {
                FieldInfo field => GetSourceData( field, arguments ),
                PropertyInfo property => GetSourceData( property, arguments ),
                MethodInfo method => GetSourceData( method, arguments ),
                _ => null,
            };
        }
        private static IEnumerable? GetSourceData(FieldInfo field, object?[]? arguments) {
            if (!field.IsStatic) return GetError( SourceMustBeStatic );
            if (arguments != null) return GetError( SourceFieldCannotTakeArguments );
            return (IEnumerable?) field.GetValue( null );
        }
        private static IEnumerable? GetSourceData(PropertyInfo property, object?[]? arguments) {
            if (!property.GetGetMethod( true )!.IsStatic) return GetError( SourceMustBeStatic );
            if (arguments != null) return GetError( SourcePropertyCannotTakeArguments );
            return (IEnumerable?) property.GetValue( null, null );
        }
        private static IEnumerable? GetSourceData(MethodInfo method, object?[]? arguments) {
            if (!method.IsStatic) return GetError( SourceMustBeStatic );
            if (arguments?.Length != method.GetParameters().Length) return GetError( NumberOfArgumentsIsWrong );
            return (IEnumerable?) method.Invoke( null, arguments );
        }
        // Helpers/Error
        private static TestMethod[] GetError(IMethodInfo method, Test suite, string message) {
            var error = new TestCaseParameters();
            error.RunState = RunState.NotRunnable;
            error.Properties.Set( PropertyNames.SkipReason, message );
            var result = new NUnitTestCaseBuilder().BuildTestMethod( method, suite, error );
            return new[] { result };
        }
        private static TestMethod[] GetError(IMethodInfo method, Test suite, Exception ex) {
            var error = new TestCaseParameters( ex );
            var result = new NUnitTestCaseBuilder().BuildTestMethod( method, suite, error );
            return new[] { result };
        }
        private static TestCaseParameters[] GetError(string message) {
            var error = new TestCaseParameters();
            error.RunState = RunState.NotRunnable;
            error.Properties.Set( PropertyNames.SkipReason, message );
            return new TestCaseParameters[] { error };
        }


    }

**Comment by Denis535** [comment] 2020-06-09 13:50
I also noticed that this example doesn't work. I think it's due to https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs#L200

    private static readonly IEnumerable<object> Args = new object[] {
        new object[2] { new object[0], 0 },
    };
    [TestCaseSource( nameof( Args ) )]
    public void Test(object[] obj, int i) {
        TestContext.WriteLine( obj );
    }

**Comment by CharliePoole** [comment] 2020-06-09 17:44
`TestCaseSourceAttribute` isn't specifically intended to be extensible. However, the `TestCaseData` class, which is commonly used with `TestCaseSourceAttribute` is quite extensible. You can also provide your own data class, implementing `ITestCaseData`.

Before you ask... NUnit was written a long time ago, when it wasn't customary to seal many classes. Back then, the attitude was "You can try to extend it but it's your problem if it doesn't work." Nowadays, I think we would generally advocate sealing unless inheritance was not specifically intended. However, this isn't something that ought to be done outside of a new major release, as it's clearly a breaking change.

Of the attribute classes I wrote, only PropertyAttribute was intended to be extended, at least AFAIR.

Unfortunately, for any piece of software, all sufficiently interesting behavior eventually becomes a feature that can't be changed. :grin:

**Comment by Denis535** [comment] 2020-06-19 23:00
@CharliePoole I rewrite my attributes so that thay extend directly `NUnitAttribute`. 
But now I have a little problems. Test Explorer can discover my tests only when solution is built. And he can forget only when solution is cleaned.
What I did wrong?

**Comment by CharliePoole** [comment] 2020-06-19 23:33
Have you tested under either NUnitLite or NUnit-Console? That's the way to tell if the attribute is working correctly. If it works in those environments and doesn't work in Test Explorer, that could mean the adapter may need to do some extra work.

**Comment by Denis535** [comment] 2020-06-26 11:18
@CharliePoole I tried NUnitLite. "Test Count" always is right. So, it works right. 
Only it prints only some tests. I don't understand why.
How does NUnit use Roslyn to find tests without compiling? Maybe here is reson for my problem.

**Comment by mikkelbu** [comment] 2020-06-26 13:52
NUnit does not use Roslyn to find tests and require that the code is compiled as it depends on reflection. The test cases are created by calling `BuildFrom` on the attributes deriving from `ITestBuilder` (like `TestCase` or `TestCaseSource`) or from `ISimpleTestBuilder` (like `TestAttribute`).

See e.g. https://github.com/nunit/nunit/blob/830e0df681eb38490742355900436b4a988a0b52/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs#L104

**Comment by stevenaw** [comment] 2024-02-29 00:14
Closing this as a duplicate of #1215. Support for this was recently added in NUnit v4.1 via a new `TypeArgs` property in PR #4620

**Closed by stevenaw** 2024-02-29 00:14 UTC
