### ISSUE TITLE
`CollectionAssert.AreEquivalent` with multidimensional arrays throws System.RankException: The specified arrays must have the same number of dimensions.

### ISSUE THREAD

**Issue by gurustron** [nunit/nunit#4252] opened 2022-11-10 11:12 UTC
```csharp
string[,] expected = new string[,] { { "value1", "value2" } };
var actual = expected;
var xxx = new ArrayList(actual);
CollectionAssert.AreEquivalent(expected, actual);   // throws RankException
```

The issue boils down to using `ArrayList` ctor with the array - it seems that it does not support multidimensional arrays:
```csharp
var throws = new ArrayList(actual);
```

**Comment by gurustron** [comment] 2022-11-10 11:21
Created a bug in runtime also: https://github.com/dotnet/runtime/issues/78150

**Comment by stevenaw** [comment] 2022-11-11 02:00
Thanks for reporting this @gurustron and investigating the cause. The research you've already done into the ArrayList constructor makes me fairly certain that this is the same as https://github.com/nunit/nunit/issues/4095

Just to rule out any doubt, can you please confirm that the version of the framework that you see that on is v3.13.3 ?

Assuming it is, we should have a fix awaiting release. I've also confirmed that the below snippet fails on 3.13.3 and passes on the latest unreleased code:

```csharp
[Test]
public void MultiArrayRank()
{
  var expected = new string[,] { { "value1", "value2" } };
  var actual = new string[,] { { "value1", "value2" } };
  CollectionAssert.AreEquivalent(expected, actual);
}
```

**Comment by gurustron** [comment] 2022-11-11 14:27
@stevenaw thank you for the reply. Yes, I have tested with `3.13.3` version.

**Comment by stevenaw** [comment] 2022-11-12 18:40
Thanks for confirming @gurustron 
I've put up a PR with a test just to help protect against accidental future regressions here. I'm going to close this issue but note that we'll see any future comments.

**Closed by stevenaw** 2022-11-12 18:40 UTC
