### ISSUE TITLE
Running FirebirdClient tests on 3.2.1 fails (3.2.0 is fine)

### ISSUE THREAD

**Issue by cincuranet** [nunit/nunit#1566] opened 2016-06-13 08:20 UTC
Tests of [FirebirdClient ](http://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/) executed using console runner version 3.2.1 fail with error shown below. Version 3.2.0 is fine.

Tests are exeuted as `nunit3-console.exe --noresult --where="test=~/(Default)/" FirebirdSql.Data.UnitTests.dll --framework=net-4.0`.

Anything I can try to quickly help pin point the issue?

```
1) Error :
Exception has been thrown by the target of an invocation.

Server stack trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener, String filter)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
```

**Comment by ChrisMaddock** [comment] 2016-06-13 11:07
Can you try with the `--inprocess` option, and see if you still get a failure?

**Comment by cincuranet** [comment] 2016-06-13 12:08
With `--inprocess` it's fine.

**Comment by ChrisMaddock** [comment] 2016-06-13 12:29
Take a look at #1509 - the symptoms are similar. Try the solution suggested by @CharliePoole in the last comment. If that doesn't help, I suggest you dig out a log as described in that issue.

Your issue looks similar, based on [this Appveyor](https://ci.appveyor.com/project/cincura_net/firebirdsql-data-firebirdclient/build/819/job/9crug5g8bcsuu3lb/tests). The fairly is in a (relatively) long running test, and it still displays in Appveyor as passed. What does TestResult.xml looks like - has everything passed there?

**Comment by cincuranet** [comment] 2016-06-13 14:18
> Take a look at #1509 - the symptoms are similar.

Yes. It's very likely the same. I'll wait for new release and check it. So far the  `--inprocess` "solves" it fine.

**Comment by rprouse** [comment] 2017-05-18 21:50
I am going to close this as a duplicate of the other issues.

**Closed by rprouse** 2017-05-18 21:50 UTC
Labels: confirm
