### ISSUE TITLE
NullReferenceException in console output when running nunit2 tests

### ISSUE THREAD

**Issue by kirillonufreinko** [nunit/nunit#1733] opened 2016-08-11 08:55 UTC
I'm observing following message for one of my test assemblies. I think it's worth improving error reporting in this case

1) Error : D:\apps\teamcity-agent2\work\9f7a9ba8e685a684\Bin\Debug[censored].dll
Object reference not set to an instance of an object.

Server stack trace: 
   at NUnit.Engine.Drivers.XmlExtensions.AddResult(XmlNode parent, TestResult result, Boolean recursive)
   at NUnit.Engine.Drivers.XmlExtensions.ToXml(TestResult result, Boolean recursive)
   at NUnit.Engine.Drivers.NUnit2FrameworkDriver.Run(ITestEventListener listener, String filter)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Agents.RemoteTestAgent.Run(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

**Comment by ChrisMaddock** [comment] 2016-08-11 09:18
Do you see the same exception if you run the assembly directly in nunit3-console.exe, outside of TeamCity? If so, are you able to bisect the test suite, and narrow down a cause?

If not, this may be related to #1732. I believe TeamCity generates it's own nunit project file under the hood, but I'm not sure if it's possible to get hold of that to see what's been generated.

**Comment by kirillonufreinko** [comment] 2016-08-11 13:37
It is the same outside teamcity. It appears it happens for loading certain assemblies - not tests.

**Comment by rprouse** [comment] 2016-12-01 20:57
We are going to need repro steps in order to fix this issue. If you cannot narrow it down to something we can reproduce, we will need to close this.

**Comment by ChrisMaddock** [comment] 2017-01-11 22:27
Closing due to not having enough information to diagnose. 

@kirillonufreinko - if you can figure out a single test you can share, which reproduces this problem, we can reopen and look at a solution. 👍

**Closed by ChrisMaddock** 2017-01-11 22:27 UTC
Labels: confirm, is:bug
