### ISSUE TITLE
Assert(..., Is.EqualTo(...)) issues since 4.3.0

### ISSUE THREAD

**Issue by moshekar** [nunit/nunit#4898] opened 2024-12-15 11:09 UTC
After updating NUnit from 4.2.2 to 4.3.0, assertions of `Is.EqualTo()` are failing when the expected argument is not a string.
From what I see, the compiler selects the `EqualTo(string? expected)` overload.

For example, `RedisValue` is a struct, but the compiler still selects the string? version.
This causes `Assert.That(redisResult, Is.EqualTo(RedisValue.Null)` to fail even if redisResult == RedisValue.Null.

I could overcome this only by casting to object?: `Assert.That(redisResult, Is.EqualTo((object?)RedisValue.Null)`

Also I noticed headers (StringValues) comparisons now fail for assertions that succeeded before.

Using latest .net 9 with latest NUnit.

Thanks.

**Comment by OsirisTerje** [comment] 2024-12-15 11:33
Thanks!  
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by OsirisTerje** [comment] 2024-12-15 12:00
I can reproduce the issue, added this:  https://github.com/nunit/nunit.issues/tree/main/Issue4898

**Comment by moshekar** [comment] 2024-12-15 12:13
Thanks @OsirisTerje 
Here is another small project with both RedisValue and StringValues.
[NUnitIssue4898.zip](https://github.com/user-attachments/files/18140336/NUnitIssue4898.zip)

**Comment by OsirisTerje** [comment] 2024-12-15 12:13
I updated the repro with a test for a "normal" struct, and that works as it should.
Looking at code for the RedisValue, it is very complex struct, with overloads for nearly everything.  We're obviously hitting on of those, but I am not sure what exactly that is being hit.  

The RedisValue.Null is "just" a  zero value, it is not a real null, so it should be working.  But I guess we're fooled by the overloads there.

**Comment by OsirisTerje** [comment] 2024-12-15 12:14
> Also I noticed headers (StringValues) comparisons now fail for assertions that succeeded before.

@moshekar  Example please

**Comment by moshekar** [comment] 2024-12-15 12:16
> > Also I noticed headers (StringValues) comparisons now fail for assertions that succeeded before.
> 
> @moshekar Example please

We've commented together, please see my last comment.

**Comment by OsirisTerje** [comment] 2024-12-15 12:21
Thanks!   I've added your code to the repro :-)

**Comment by OsirisTerje** [comment] 2024-12-15 12:44
@manfred-brands @stevenaw 

The StringValues test show what happens pretty well:
![image](https://github.com/user-attachments/assets/7f95eeec-1159-4897-bf20-d117ba0371c0)

It breaks in the string comparison, due to the type cast there.

![image](https://github.com/user-attachments/assets/726da659-19b0-4175-9b2e-1dbf0587124d)

**Comment by moshekar** [comment] 2024-12-15 12:48
Thanks @OsirisTerje 
Please note that StringValues has implicit operator for pure string and also implements IEquatable<string?>

**Comment by manfred-brands** [comment] 2024-12-15 13:02
Thanks @moshekar, that gives me some ideas to fix this.

**Comment by OsirisTerje** [comment] 2024-12-15 13:20
@moshekar Yes, I noticed that.  But it doesnt't seems like we even get to any of the conversion in the StringValues class.

**Comment by smdn** [comment] 2024-12-15 13:28
I am facing a similar problem.
In my case, on test cases with the structure that implement both `IEnumerable<T>` and `IConvertible`, the `IConvertible` is preferred over `IEnumerable<T>`.

The minimum reproduction code is as follows.
This code succeeds with NUnit 4.2.2, but fails with 4.3.0.

```cs
using System;
using NUnit.Framework;

[TestFixture]
public class Tests {
  [Test]
  public void Test()
  {
    // Tests a structure that implements both IEnumerable<T> and IConvertible
    //   NUNit 4.2.2: Succeeds as expected
    //   NUNit 4.3.0: IConvertible.ToInt32 is called and fails
    Assert.That(new Number(), Is.EqualTo(new Number()));
  }
}

public readonly struct Number : IEquatable<Number>, IConvertible {
  // IEquatable<Number>
  public bool Equals(Number other)
    => true;

  // IConvertible
  TypeCode IConvertible.GetTypeCode() => TypeCode.Object;
  byte IConvertible.ToByte(IFormatProvider provider) => throw new NotImplementedException();
  sbyte IConvertible.ToSByte(IFormatProvider provider) => throw new NotImplementedException();
  ushort IConvertible.ToUInt16(IFormatProvider provider) => throw new NotImplementedException();
  short IConvertible.ToInt16(IFormatProvider provider) => throw new NotImplementedException();
  uint IConvertible.ToUInt32(IFormatProvider provider) => throw new NotImplementedException();
  int IConvertible.ToInt32(IFormatProvider provider) => throw new NotImplementedException();
  ulong IConvertible.ToUInt64(IFormatProvider provider) => throw new NotImplementedException();
  long IConvertible.ToInt64(IFormatProvider provider) => throw new NotImplementedException();
  string IConvertible.ToString(IFormatProvider provider) => throw new NotImplementedException();
  bool IConvertible.ToBoolean(IFormatProvider provider) => throw new NotImplementedException();
  char IConvertible.ToChar(IFormatProvider provider) => throw new NotImplementedException();
  DateTime IConvertible.ToDateTime(IFormatProvider provider) => throw new NotImplementedException();
  decimal IConvertible.ToDecimal(IFormatProvider provider) => throw new NotImplementedException();
  double IConvertible.ToDouble(IFormatProvider provider) => throw new NotImplementedException();
  float IConvertible.ToSingle(IFormatProvider provider) => throw new NotImplementedException();
  object IConvertible.ToType(Type conversionType, IFormatProvider provider) => throw new NotImplementedException();
}
```


NUnit 4.2.2:
```
$ dotnet test --no-build --nologo
Test run for /home/smdn/temp/nunit-number/bin/Debug/net8.0/Number.dll (.NETCoreApp,Version=v8.0)
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 13 ms - Number.dll (net8.0)
```

NUnit 4.3.0:
```
$ dotnet test --no-build --nologo
Test run for /home/smdn/temp/nunit-number/bin/Debug/net8.0/Number.dll (.NETCoreApp,Version=v8.0)
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Test [13 ms]
  Error Message:
   System.NotImplementedException : The method or operation is not implemented.
  Stack Trace:
     at Number.System.IConvertible.ToInt32(IFormatProvider provider) in /home/smdn/temp/nunit-number/Class1.cs:line 28
   at NUnit.Framework.Constraints.Numerics.AreEqual[T1,T2](T1 expected, T2 actual, Tolerance& tolerance)
   at NUnit.Framework.Constraints.EqualNumericWithoutUsingConstraint`1.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, NUnitString message, String actualExpression, String constraintExpression)
   at Tests.Test() in /home/smdn/temp/nunit-number/Class1.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 13 ms - Number.dll (net8.0)
```

**Comment by manfred-brands** [comment] 2024-12-15 13:29
We get to the StringEqualConstraint because of the string passed to the Is.EqualTo and the compiler find an implicit cast to string. The compiler seems to prefer specific types over generic. But the fact that we get here means we should be able to cast.

**Comment by manfred-brands** [comment] 2024-12-15 13:37
@smdn Your type claims to implement IConvertible bit then doesn't. Isn't that a contract violation?

**Comment by OsirisTerje** [comment] 2024-12-15 13:43
@manfred-brands  I have breakpoints on all conversion in the StringValues class, and none are hit.  To me it looks like it is the explicit conversion on line 132 in EqualStringWithoutUsingConstraint.cs that causes this.   The StringValues class have an implicit  conversion on line 74 in that class, but it is not hit.  I would have expected it to be hit.

**Comment by smdn** [comment] 2024-12-15 13:47
@manfred-brands

The implementation of `IConvertible` has been omitted for the purpose of minimize.
In the actual code, `IConvertible` is properly implemented and works as expected.

The problem with this code is that the type implements `IEquatable<T>`, but `Is.EqualTo` ignores `IEquatable<T>`.
Is this expected behavior for `Is.EqualTo`?

**Comment by moshekar** [comment] 2024-12-15 13:48
> @manfred-brands I have breakpoints on all conversion in the StringValues class, and none are hit. To me it looks like it is the explicit conversion on line 132 in EqualStringWithoutUsingConstraint.cs that causes this. The StringValues class have an implicit conversion on line 74 in that class, but it is not hit. I would have expected it to be hit., but then we have to change to not use the `as`

As I mentioned above, the implicit operator is not called for casting with the `as` keyword.

**Comment by OsirisTerje** [comment] 2024-12-15 13:52
> As I mentioned above, the implicit operator is not called for casting with the as keyword.

> but then we have to change to not use the as

Yes, correct, as stated above :-)  Sorry for the quick typing.

**Comment by moshekar** [comment] 2024-12-15 14:13
BTW @OsirisTerje , I just saw you edited my test code for the StringValues in UnitTest2.cs, but you forgot to change the first string.
You are now comparing between `test` and `X-Test` :)

**Comment by OsirisTerje** [comment] 2024-12-15 14:17
Thanks, will fix, it crashes before it gets that far so....

**Comment by OsirisTerje** [comment] 2024-12-15 15:22
@smdn Your code needs to be able to go green.  Can you make an example so it does?   
The struct doesn't hold any data, so calling an empty ctor - does that even make sense here?
If it does, then this is a null issue, like for the RedisValue, otherwise it is varaition of the casting issue like StringValues.  (Strictly speaking, both are casting issues, but at different places)

**Comment by moshekar** [comment] 2024-12-15 15:26
> @smdn Your code needs to be able to go green. Can you make an example so it does? The struct doesn't hold any data, so calling an empty ctor - does that even make sense here? If it does, then this is a null issue, like for the RedisValue, otherwise it is varaition of the casting issue like StringValues. (Strictly speaking, both are casting issues, but at different places)

@smdn code implements `Equal` and returns true. So `new Numer() == new Number()`.
This simple equality check is also broken in 4.3.0

**Comment by stevenaw** [comment] 2024-12-15 16:36
@smdn your description also mentions implementing `IEnumerable<T>` but your sample omits it. Is there a repro you can share which includes the implementation? 

I'm curious if there's been a change in precedence in the comparer chain used by NUnit, but we'd need to see a clearer repro describing your issue to be sure.

**Comment by OsirisTerje** [comment] 2024-12-15 19:03
@manfred-brands wrote:

> We get to the StringEqualConstraint because of the string passed to the Is.EqualTo and the compiler find an implicit cast to string. The compiler seems to prefer specific types over generic. But the fact that we get here means we should be able to cast.

I added some very simple tests to showcase this.  MyStructTestsWithString and MyStructTestsWithStringAndImplicitOperator.  The first one passes, as it use the fallback EqualConstraint, but the second fails as the implicit cast converts the expected constraint to be a EqualStringConstraint - but the **actual value** fails to be converted to string - since it is in a generic **unconstrained** method (if I got that right).  
<img width="844" alt="image" src="https://github.com/user-attachments/assets/aaa8629f-9104-4d9f-9ae2-a9e1f1527a3d" />

The EqualStringConstraint use the "as" conversion when it calls the ApplyTo(string? ....) method, and that cast return a null value.  

I would assume the same thing happens in the other cases we see here.

If we constrained the ApplyTo methods soi that we got one for class and one for struct, the one for class should be able to use the "as" keyword.  (If we only do this: The one for struct would still need to be specially handled, perhaps using dynamic or even reflection. But we can also change the EqualTo).

The EqualTo method could likewise be constrained to struct and class, so that the struct version doesnt apply the implicit operator.

**Comment by moshekar** [comment] 2024-12-15 19:51
@OsirisTerje  @manfred-brands 
I tried to play with a standalone version of the ApplyTo code from EqualStringConstraint.
Please see my results, maybe it will help or give you some idea.
All these assertions pass:
![image](https://github.com/user-attachments/assets/594deaca-7b01-4b25-a10c-1f371cdd0f22)

**Comment by OsirisTerje** [comment] 2024-12-15 20:45
The issue in the EqualsString....Constraint, is that the generic type is not resolved as a string, so the "is string" will return false.  Since the expected value has been resolved to be a string, due to the implicit cast, the challenge is to get the actual value to also be cast as a string.  Or, be able to not invoke the implicit cast of the expected value.  

It's awesome that you try to work out this. I would suggest you clone down the nunit.framework code, and include that - the repro code do have the link there already, you might need to adjust the path though.  That way you can play with the actual code involved.

**Comment by moshekar** [comment] 2024-12-15 20:59
> The issue in the EqualsString....Constraint, is that the generic type is not resolved as a string, so the "is string" will return false. Since the expected value has been resolved to be a string, due to the implicit cast, the challenge is to get the actual value to also be cast as a string. Or, be able to not invoke the implicit cast of the expected value.
> 
> It's awesome that you try to work out this. I would suggest you clone down the nunit.framework code, and include that - the repro code do have the link there already, you might need to adjust the path though. That way you can play with the actual code involved.

The difference in my code is that I don't use `as` - which will fail silently and return null.
I test actual with `is`, and if it is not an instance of a string, I fallback to a more generic actual.Equals(expected).
I guess that to apply this in the NUnit code it would be something like:
```csharp
public sealed override ConstraintResult ApplyTo<TActual>(TActual actual)
{
    bool hasSucceeded;

    if (actual is null)
    {
        hasSucceeded = _expected is null;
    }
    else if (_expected is null)
    {
        hasSucceeded = false;
    }
    else if (actual is string str)
    {
        return ApplyTo(str);
    }
    else
    {
        // fallback to the object? overload?
    }

    return ConstraintResult(actual, hasSucceeded);
}
```

**Comment by manfred-brands** [comment] 2024-12-16 02:28
@moshekar @OsirisTerje The implicit cast operator is a red herring.

The issue is that `StringValues` implements `IEquatable<string>` which wasn't checked in the `EqualStringConstraint`.
I have update the Apply<TActual> method to read:
```csharp
            else if (actual is string s)
            {
                return ApplyTo(s);
            }
            else if (actual is IEquatable<string> equatableString)
            {
                hasSucceeded = equatableString.Equals(_expected);
            }
```

The problem we now have again is that if someone does:
`Assert.That(new StringValues("test"), Is.EqualTo("Test").IgnoreCase);`
This `IgnoreCase` is not used, nor was it in 4.2.2, because NUnit isn't doing the comparison, the class' `IEquality<string>` is and this doesn't have an overload allowing to specify casing.

We can throw an error if a modifier is used that cannot be used.
We can add an analyzer to detect this and warn at compile time.

Alternatively, if the class also implements a cast to string, we can call that.
It then behaves as the equivalent of:
`Assert.That<string?>(new StringValues("test"), Is.EqualTo("Test").IgnoreCase);`

Implemented all in PR #4899

**Comment by stevenaw** [comment] 2024-12-16 02:49
Wow, quick solution you've found @manfred-brands . Thanks! On my end I could try and review it tomorrow with fresh eyes. For now, I've created a 4.3.1 milestone and added this to it

**Comment by smdn** [comment] 2024-12-16 03:03
I am sorry that my post has confused this issue.
Please ignore my post for now as I will re-create the individual issue for this again later.

@stevenaw
Yes, I mean `IEquatable<T>`. `IEnumerable<T>` was a typo. Sorry for the confusion.

**Comment by stevenaw** [comment] 2024-12-16 03:11
Not as problem at all @smdn we do appreciate any bug reports or notices of any issues 🙂

It does sound like the `IEquatable<T>` issue you are hitting could be similar in nature to the other I've discussed here. It would still be helpful if you could provide a repro for your case, of course, as it could help us confirm if it'll be fixed by the open PR or if perhaps other changes were needed to help your scenario.

**Comment by manfred-brands** [comment] 2024-12-16 03:21
The issue with `RedisValue.Null` is strange. Yes the class has an implicit string operator, but why would the compiler pick that when there is an object overload.

```csharp
        RedisValue actual = new byte[] { 1, 2, 3 };
        RedisValue expected = new byte[] { 1, 2, 3 };

        Assert.That(actual, Is.EqualTo(expected));
```

Even here, the compiler picks `Is.EqualTo(string?)` instead of `Is.EqualTo(object?)`
It seems that `object` overloads are always picked last even if conversions are needed.
I'm trying to find a specification that is not ancient.

The only way to pick an appropriate one is to add an overload:
`public static EqualConstraint EqualTo<T>(T expected)`

However that conflicts with `public static EqualNumericConstraint<T> EqualTo<T>(T expected)` overload.

To be continued ...

**Comment by manfred-brands** [comment] 2024-12-16 03:42
@smdn In the `EqualNumericConstraint` there is a preference for NUnit doing the comparison over calling `IEquatable`. The reason is that all .NET primitives implement `IEquatable` but NUnit allows for comparison with a tolerance.
As NUnit's `Numerics.AreEqual` only works on standard primitives, I added that test:
`if (actual is T t && typeof(T).IsPrimitive)`

This fixes your problem.

**Comment by stevenaw** [comment] 2024-12-16 03:59
@manfred-brands In terms of implicit conversion precedence, that behavior is a bit of a surprise to me too.

I found https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#104-standard-conversions which, if I am reading right, treats built -in and user-defined implicit conversions with the same weight - with the conversion of all types to object being "built-in". I think the string overload then "wins" over the object one as it is the most specific available conversion to be satisfied.

I think you may be on the right track about adding the overload, but I'm not at a computer right now to confirm

**Comment by manfred-brands** [comment] 2024-12-16 04:34
@stevenaw Thanks for that reference, the appropriate section would be: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#12642-applicable-function-member

**Comment by manfred-brands** [comment] 2024-12-16 05:17
@moshekar Note that the PR does solve the `RedisValue` case, but only because both arguments will be converted to `string`. The _expected_ value by the compiler and the _actual_ value by NUnit's StringEqualConstraint..

Unless we can solve the overload issue, NUnit never sees an RedisValue for the _expected_ value.

**Comment by manfred-brands** [comment] 2024-12-16 05:19
@OsirisTerje With the PR all tests in the replication issue repo for this ticket pass.

**Comment by manfred-brands** [comment] 2024-12-16 07:25
> BTW, there is a new attribute in .net 9 to control overloads priorities - OverloadResolutionPriorityAttribute. Maybe you can use it in the future to handle edge cases (but it's only for .net 9).

It is a C# 13 issue, as the compiler picks to overload, you don't need to target .net 9, so only the SDK needs updating.
However, I tried it and had no luck. Yes lowering the priority of `Is.EqualTo(string?)` causes the `Is.EqualTo(object?)` to be resolved for `RedisValue` but surprisingly also for `Is.EqualTo("Test")`, even then it doesn't call the string overload.

This matches the [documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-13.0/overload-resolution-priority):

> All members that have a lower overload_resolution_priority than the highest found within its declaring type group are removed.

As `Is.EqualTo(object?)` always matches, even if others are better, it will always be chosen.

**Comment by manfred-brands** [comment] 2024-12-16 07:28
> UPDATE: I now see @manfred-brands PR and I see the addition of the fallback to .Equals. I hope this will cover all new issues.

This is compile time conditional on whether we think it is actually needed.

**Comment by manfred-brands** [comment] 2024-12-16 07:54
> I'm wondering whether it's always correct to convert the values to string.
For example, RedisValue.Null. Although the compiler selects the string? overload, it's special meaning might get lost on the conversion.

I am not disagreeing. But in this case `RedisValue` does do a lot of conversions itself.
```
RedisValue actual1 = 42;
string expected1 = "42";

Assert.That(actual1.Equals(expected1));

RedisValue actual2 = "42";
int expected2 = 42;
Assert.That(actual2.Equals(expected2));
```

You would expect this to fail. It doesn't because `RedisValue.Simplify` converts `string` to `Int64` if possible.
So RedisValue compares Equal with all the supported types.

**Comment by ogborstad** [comment] 2024-12-16 07:59
Seeing this with MongoDB.Bson.ObjectId as well

```
[Test]
public void MongoDBObjectId_equality_exception()
{
    var objectId1 = MongoDB.Bson.ObjectId.GenerateNewId();
    var objectId2 = MongoDB.Bson.ObjectId.GenerateNewId();
        
    Assert.That(objectId1, Is.Not.EqualTo(objectId2));
}
```

**Comment by manfred-brands** [comment] 2024-12-16 08:07
@ogborstad Your test passes when my PR is applied.

**Comment by moshekar** [comment] 2024-12-16 09:08
> > I'm wondering whether it's always correct to convert the values to string.
> For example, RedisValue.Null. Although the compiler selects the string? overload, it's special meaning might get lost on the conversion.
> 
> I am not disagreeing. But in this case `RedisValue` does do a lot of conversions itself.
> ```
> RedisValue actual1 = 42;
> string expected1 = "42";
> 
> Assert.That(actual1.Equals(expected1));
> 
> RedisValue actual2 = "42";
> int expected2 = 42;
> Assert.That(actual2.Equals(expected2));
> ```
> 
> You would expect this to fail. It doesn't because `RedisValue.Simplify` converts `string` to `Int64` if possible.
> So RedisValue compares Equal with all the supported types.

RedisValue is a special case because in redis everything is actually a string (iirc) so it has all those automatic conversions.
But we should consider other cases that 1 is not "1" but another type at all.
In this case will Is.EqualTo result differ between 4.2.2 and 4.3.0? And if so is this the desired behaviour?

**Comment by TadijaB** [comment] 2024-12-16 11:07
Similar issue here. Started happening with update to 4.3.0. Is this considered a bug which will be patched?

![image](https://github.com/user-attachments/assets/a5fd5e57-bcc2-4afc-9d39-b2e872e6025d)

**Comment by TadijaB** [comment] 2024-12-16 15:59
> > Similar issue/breaking change here. Started happening with update to 4.3.0
> > ![image](https://private-user-images.githubusercontent.com/13481035/396070417-a5fd5e57-bcc2-4afc-9d39-b2e872e6025d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjUwMTQsIm5iZiI6MTczNDM2NDcxNCwicGF0aCI6Ii8xMzQ4MTAzNS8zOTYwNzA0MTctYTVmZDVlNTctYmNjMi00YWZjLTlkMzktYjJlODcyZTYwMjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDE1NTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZWE3N2I0Mjc0MmQ0YjY3MWU0MTFlMDMyMDZiYzZhYzA3NTgwMTJmNjg2ZGY3MTQwMWI0NDIwM2VkNWZkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0QSF0MnO43pPyYivHS1NVhWuXce_XydskO4DaLQUSoY)
> 
> try `default(short)` the compiler can't determine the type in this case

I understand, not the best part of our code base but, this code compiles and works in NUnit 4.2.2

**Comment by manfred-brands** [comment] 2024-12-17 09:57
> 
> I understand, not the best part of our code base but, this code compiles and works in NUnit 4.2.2

It compiles, but did it actually test what you were intending?

You are testing that a `short` is not `default(object)` aka `null` which will never fail, even if that short is 0!

```csharp
[TestCase(0)]
[TestCase(1)]
public void Test(short value)
{
    Assert.That(value, Is.Not.EqualTo(default));
}
```

Would you expect one of these two tests to fail? Both pass.
If you wanted to verify that the `short` is not `0`, then either use `0` or  `default(short)`.

The `default` keyword is very dangerous when passed to methods as it will be the default for the method parameter.
At our work I do not allow `default` unless the type is obvious which is only in an declaration initializer.

**Comment by smdn** [comment] 2024-12-17 12:24
Thanks to everyone who replied to me.
I will continue the discussion here, rather than opening a new issue, as it seems that the fix has already been added.

The following are more specific codes.
My code is basically like https://github.com/nunit/nunit/issues/4898#issuecomment-2543927027.
But it is a wrapper struct that holds a `long` instead of an `int`, and it has an implementation of `IConvertible.ToInt32`.

```cs
public readonly struct MyLong(long value) : IEquatable<MyLong>, IConvertible
{
  private readonly long _value = value;

  public bool Equals(MyLong other) => _value == other._value;

  public override bool Equals(object? obj) =>
    obj is MyLong other && Equals(other);

  public override int GetHashCode() => _value.GetHashCode();

  public static bool operator ==(MyLong left, MyLong right) =>
    left.Equals(right);

  public static bool operator !=(MyLong left, MyLong right) =>
    !left.Equals(right);

  // Is.EqualTo of NUnit 4.3.0 tries to call IConvertible.ToInt32.
  // But this implementation may throw OverflowException since `_value` is `long`.
  int IConvertible.ToInt32(IFormatProvider provider) =>
    Convert.ToInt32(_value, null);

  // other IConvertible members (omits implementation since these are irrelevant to this issue)
  TypeCode IConvertible.GetTypeCode() => TypeCode.Object;
  byte IConvertible.ToByte(IFormatProvider provider) => throw new NotImplementedException();
  sbyte IConvertible.ToSByte(IFormatProvider provider) => throw new NotImplementedException();
  ushort IConvertible.ToUInt16(IFormatProvider provider) => throw new NotImplementedException();
  short IConvertible.ToInt16(IFormatProvider provider) => throw new NotImplementedException();
  uint IConvertible.ToUInt32(IFormatProvider provider) => throw new NotImplementedException();
  long IConvertible.ToInt64(IFormatProvider provider) => throw new NotImplementedException();
  ulong IConvertible.ToUInt64(IFormatProvider provider) => throw new NotImplementedException();
  string IConvertible.ToString(IFormatProvider provider) => throw new NotImplementedException();
  bool IConvertible.ToBoolean(IFormatProvider provider) => throw new NotImplementedException();
  char IConvertible.ToChar(IFormatProvider provider) => throw new NotImplementedException();
  DateTime IConvertible.ToDateTime(IFormatProvider provider) => throw new NotImplementedException();
  decimal IConvertible.ToDecimal(IFormatProvider provider) => throw new NotImplementedException();
  double IConvertible.ToDouble(IFormatProvider provider) => throw new NotImplementedException();
  float IConvertible.ToSingle(IFormatProvider provider) => throw new NotImplementedException();
  object IConvertible.ToType(Type conversionType, IFormatProvider provider) => throw new NotImplementedException();
}

[Test]
public void Test()
{
  MyLong l1 = new(0);
  MyLong l2 = new(1);
  MyLong l3 = new((long)int.MaxValue + 1);

  // These work as expected.
  Assert.That(l1, Is.EqualTo(l1));
  Assert.That(l1, Is.Not.EqualTo(l2));

  // NUnit 4.2.2: This works as expected.
  // NUnit 4.3.0: MyLong.IConvertible.ToInt32 is called and it throws OverflowException.
  Assert.That(l1, Is.EqualTo(l3));

  // NUnit 4.2.2: This works as expected.
  // NUnit 4.3.0: As same as above one.
  Assert.That(l3, Is.EqualTo(l3));
}
```

NUnit 4.3.0 output:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Test [18 ms]
  Error Message:
   System.OverflowException : Value was either too large or too small for an Int32.
  Stack Trace:
     at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at MyLong.System.IConvertible.ToInt32(IFormatProvider provider) in /home/smdn/temp/nunit-number/Class1.cs:line 22
   at NUnit.Framework.Constraints.Numerics.AreEqual[T1,T2](T1 expected, T2 actual, Tolerance& tolerance)
   at NUnit.Framework.Constraints.EqualNumericWithoutUsingConstraint`1.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, NUnitString message, String actualExpression, String constraintExpression)
   at Tests.Test() in /home/smdn/temp/nunit-number/Class1.cs:line 55
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

With NUnit 4.3.0, it seems that `IConvertible.ToInt32` is called for the reason described in https://github.com/nunit/nunit/issues/4898#issuecomment-2544499483, but this causes an exception in `Is.EqualTo`.
So I think the addition of the check code `if (actual is T t && typeof(T).IsPrimitive)` will help to solve this problem.

**Comment by ds5678** [comment] 2024-12-19 00:16
I too have encountered this issue. In my case, overload resolution changed from `Is.EqualTo(object?)` to `Is.EqualTo(string?)` since my class is implicitly convertible to string.

https://github.com/nunit/nunit/commit/713452aefe7414ea9499cec24ebddb0d6f7f892e#diff-6e02c03a03ad9e227c03b24512bbf9584534a10fa2f84045074a74454880eb05

**Comment by m-gasser** [comment] 2024-12-19 08:38
We also stumbled over this issue and had to revert back to the old version.

**Comment by ds5678** [comment] 2024-12-19 13:57
In my opinion, these new overloads should be removed or renamed. Even if the pull request makes my tests pass again, my tests will have a subtly different meaning. Testing `Equals(string)` is not the same as testing `Equals(object)`.

**Comment by manfred-brands** [comment] 2024-12-19 13:59
@ds5678 In the latest version the `Equals(string?)` will not be called, even when you class has an implicit conversion to `string`.

**Comment by ds5678** [comment] 2024-12-19 14:14
> @ds5678 In the latest version the `Equals(string?)` will not be called, even when you class has an implicit conversion to `string`.
> 

My apologies. I didn't notice the new generic overload.

**Closed** 2024-12-20 10:10 UTC
Labels: is:bug

**Comment by ORuban** [comment] 2024-12-20 11:54
Could you advice if the following error is related, or it rather indicates a incompatibility in https://github.com/weichch/system-text-json-jsondiffpatch packages:
(dowgrade to Nunit 4.2.1 does not work for me)
> System.TypeLoadException : Method 'get_Description' in type 'System.Text.Json.JsonDiffPatch.Nunit.JsonEqualConstraint' from assembly 'SystemTextJson.JsonDiffPatch.NUnit

package is used to utilize `JsonIs.EqualTo`:
`Assert.That(responseContentJson, JsonIs.EqualTo(expectedJson));`

**Comment by ORuban** [comment] 2024-12-20 11:55
Could you please advice if the following error is related, or it indicates an incompatibility in https://github.com/weichch/system-text-json-jsondiffpatch packages:
(downgrade to Nunit 4.2.1 does not work for me)
> System.TypeLoadException : Method 'get_Description' in type 'System.Text.Json.JsonDiffPatch.Nunit.JsonEqualConstraint' from assembly 'SystemTextJson.JsonDiffPatch.NUnit

in code we have things like
`Assert.That(responseContentJson, JsonIs.EqualTo(expectedJson));`

**Comment by manfred-brands** [comment] 2024-12-20 12:01
@ORuban That is not related to this ticket. The library you mention is written for nunit version 3 and cannot be used with version 4. The library needs updating to have a V4 version.

**Comment by OsirisTerje** [comment] 2024-12-21 16:15
@moshekar @smdn 4.3.1 released now.  Would appreciate if you could confirm it works for you. https://docs.nunit.org/articles/nunit/release-notes/framework.html#nunit-431----dec-21-2024

**Comment by moshekar** [comment] 2024-12-22 13:20
@OsirisTerje Just finished updating all projects to 4.3.1 and everything went well with no issues,
