### ISSUE TITLE
Test not being recognised that have an attribute deriving from TestAttribute

### ISSUE THREAD

**Issue by SeanFarrow** [nunit/nunit#1347] opened 2016-03-14 00:08 UTC
Hi,

I am using JustEat.JustBehave, in Nunit 3.2 tests are no longer being recognized when the attribute derives from TestAttribute. TestAttribute works as I would expect.

Having looked at the NUnit source, I have narrowed it down to the package creation or the TestAssembly building process. What is the best way of debugging the agent process then I can take this further.
Any help is appreciated as always.
I have a simple class library that reproduces the problem.

**Comment by CharliePoole** [comment] 2016-03-14 02:14
I checked the JustBehave source and it references the NUnit 3.0.1 framework. How are you managing to mix two framework versions?

The easiest wasy to debug the agent is not to. :-) Just run the tests using the --inprocess switch. However, if you really nead to, just use the --debug switch which will invite you to attach a debugger right before the tests start to run.

**Comment by CharliePoole** [comment] 2016-03-14 02:16
This issue doesn't really give us much of anything to fix. If you can provide a simple test case that illustrates the inheritance problem without requiring use of 3rd party software I'll keep it open and we can try to see what's happening.

**Comment by SeanFarrow** [comment] 2016-03-14 14:28
Hi,

 

If you look at the following repo:

https://github.com/SeanFarrow/NUnitInheritedTestsNotFoundRepro

This demonstrates the problem quite nicely.

 

Having looked at the NUnit source, the problem seems to be In the DefaultTestCaseBuilder, specifically in the CanBuildFrom method. Here when calling IsDefined on the IMethodInfo instance, false is passed in as the inherit parameter. If True was passed in, I think this would solve the problem.

Where should I put any tests to ensure that this doesn’t break again, given that this is an internal class?

Happy to create a PR.

Cheers

Sean.

**Comment by CharliePoole** [comment] 2016-03-14 15:33
OK... now I understand. "Inheritance" can mean several different things when talking about attributes and I was reading your original post incorrectly.

Please do give it a try. We would be happy to allow inheritance of other attributes from TestAttribute and in fact I thought we did. However, I don't think the problem is in the code you pointed to. That code eventually calls MemberInfo.IsDefined, and per the MS docs the `inherit` argument indicates whether the chain of inheritance of the member should be examined, not that of the attribute.

**Comment by SeanFarrow** [comment] 2016-03-14 15:41
Ok, you did in NUnit 2, let me take a look at that source and see what’s going on!

**Comment by SeanFarrow** [comment] 2016-03-14 15:57
Ok,

 

In v2, there was some code in reflect.cs that checked for inheritance by walking the type hierarchy. This is not in v3, which is why this issue  is happening.

There was also some accompanying tests, so I’m looking at porting this.

Cheers

Sean.

**Comment by CharliePoole** [comment] 2016-03-14 16:11
Have you stepped through this yet? We had that code in V2 because we had to recognize attributes by their name in nunit.core, which had no reference to nunit.framework. There's lots of code in NUnit itself that finds attributes by looking for a base class or even an interface and it's all working. There's something different going on here.

You might consider starting with adding a test case to the NUnit tests. Take a look at `TestMethodBuilderTests.cs`, which tests building tests that use a variety of attributes.

**Comment by CharliePoole** [comment] 2016-03-14 16:13
FYI, because so many fundamental assumptions have changed, it takes in-depth knowledge of both V2 and V3 to compare implementations. I occasionally do it myself, but even I find it pretty hard.

**Comment by SeanFarrow** [comment] 2016-03-14 18:26
Hi,

 

I’ve added a branch Issue1347 in my fork at:

https://github.com/seanfarrow/nunit

I’ve added a test for the inherited attribute, I’m not sure whether it’s being run as I don’t have the compact framework installed, so the cake build is erroring out!

I believe this test should fail, but can’t debug this in vs as resharper claims I’m running an unsupported framework.

Help appreciated.

Kind regards

Sean.

**Comment by CharliePoole** [comment] 2016-03-14 18:40
You should get the latest changes from master, since your branch is a bit behind. The latest build tests for CF and won't error out on you.

Avoid using a third-party runner when working on NUnit. Why? Because by definition the third-party runner isn't using the version of NUnit that you create with your changes. :-) 

I generally set nunit3-console as my startup program and fill in the arguments with the test assembly I want to run plus --inprocess, so that I can debug more easily.

**Comment by SeanFarrow** [comment] 2016-03-14 19:06
Hi,

 

I’ve just recreated the fork and it’s still erroring out in terms of wanting to build the cf. I’ve only got vs2013/2015 on this box.

Should I create another issue?

Cheers

Sean.

**Comment by CharliePoole** [comment] 2016-03-14 19:14
Sorry... I see that the relevant change is in PR #1332 which has not yet been merged. It keeps falling behind master and requiring updates. I'll get it merged and then get back to you.

**Comment by CharliePoole** [comment] 2016-03-14 19:48
I just merged this... please try again.

**Comment by SeanFarrow** [comment] 2016-03-15 14:56
Hi,

 

Ok, I’ve found the problem/fix for this. I’d like to add tests though, so where are tests for DefaultTestCaseBuilder placed as that’s where the problem was.

Essentially, NUnit wasn’t taking in to account classes that were assignable from the interfaces it was checking ITestBuilder and ISimpleTestBuilder in any project other than portable.

Cheers

Sean.

**Comment by CharliePoole** [comment] 2016-03-15 16:40
Are you saying that MethodWrapper.IsDefined is not working for these cases? It looks as if it should.

We don't have tests dedicated to DefaultTestCaseBuilder, though maybe we should. The tests that would normally get at this error are in TestMethodSignatureTests.cs. Adding tests would be a great help, especially failing tests. :-)

@nunit/contributors @nunit/core-team Can somebody confirm this as a bug?

**Comment by SeanFarrow** [comment] 2016-03-15 17:38
Sorry, I mean in MethodWrapper.cs, the IsDefined method is where the issue lies. I’m just putting a test together to show the failure.

**Comment by ChrisMaddock** [comment] 2016-03-17 10:03
Sorry Sean, can I ask exactly what you mean by "not being recognised"? I've pulled your sample repo, and have two tests being run, just as I'd expect? I presume I'm missing something! 

Output under NUnit 3.2, ran in console:

````
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="2" result="Failed" total="2" passed="1" failed="1" inconclusive="0" skipped="0" asserts="2" engine-version="3.2.0.0" clr-version="4.0.30319.42000" start-time="2016-03-17 09:57:41Z" end-time="2016-03-17 09:57:42Z" duration="0.230458">
  <command-line><![CDATA["C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe"  NUnitInheritedTests.dll]]></command-line>
  <test-suite type="Assembly" id="0-1004" name="NUnitInheritedTests.dll" fullname="C:\Users\xxx\git\NUnitInheritedTestsNotFoundRepro\src\NUnitInheritedTests\bin\Release\NUnitInheritedTests.dll" runstate="Runnable" testcasecount="2" result="Failed" site="Child" start-time="2016-03-17 09:57:41Z" end-time="2016-03-17 09:57:41Z" duration="0.121656" total="2" passed="1" failed="1" inconclusive="0" skipped="0" asserts="2">
    <environment framework-version="3.2.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="C:\Users\xxx\git\NUnitInheritedTestsNotFoundRepro\src\NUnitInheritedTests\bin\Release" machine-name="xxx" user="xxx" user-domain="xxx" culture="en-GB" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="WorkDirectory" value="C:\Users\xxx\git\NUnitInheritedTestsNotFoundRepro\src\NUnitInheritedTests\bin\Release" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.6.1" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="8" />
    </settings>
    <properties>
      <property name="_PID" value="13136" />
      <property name="_APPDOMAIN" value="test-domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1005" name="NUnitInheritedTests" fullname="NUnitInheritedTests" runstate="Runnable" testcasecount="2" result="Failed" site="Child" start-time="2016-03-17 09:57:41Z" end-time="2016-03-17 09:57:41Z" duration="0.102971" total="2" passed="1" failed="1" inconclusive="0" skipped="0" asserts="2">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestFixture" id="0-1000" name="CalculatorInheritedAttributeTests" fullname="NUnitInheritedTests.CalculatorInheritedAttributeTests" classname="NUnitInheritedTests.CalculatorInheritedAttributeTests" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2016-03-17 09:57:41Z" end-time="2016-03-17 09:57:41Z" duration="0.097368" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="1">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-case id="0-1001" name="MinusGivesTheExpectedResult" fullname="NUnitInheritedTests.CalculatorInheritedAttributeTests.MinusGivesTheExpectedResult" methodname="MinusGivesTheExpectedResult" classname="NUnitInheritedTests.CalculatorInheritedAttributeTests" runstate="Runnable" seed="2031539648" result="Failed" start-time="2016-03-17 09:57:41Z" end-time="2016-03-17 09:57:41Z" duration="0.075226" asserts="1">
          <failure>
            <message><![CDATA[  Expected: -6
  But was:  6
]]></message>
            <stack-trace><![CDATA[at NUnitInheritedTests.CalculatorInheritedAttributeTests.MinusGivesTheExpectedResult() in C:\Users\xxx\git\NUnitInheritedTestsNotFoundRepro\src\NUnitInheritedTests\CalculatorInheritedAttributeTests.cs:line 36
]]></stack-trace>
          </failure>
        </test-case>
      </test-suite>
      <test-suite type="TestFixture" id="0-1002" name="CalculatorNormalTest" fullname="NUnitInheritedTests.CalculatorNormalTest" classname="NUnitInheritedTests.CalculatorNormalTest" runstate="Runnable" testcasecount="1" result="Passed" start-time="2016-03-17 09:57:41Z" end-time="2016-03-17 09:57:41Z" duration="0.001156" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="1">
        <test-case id="0-1003" name="WhenTheAddOperatorIsCalledTheExpectedResultIsReturned" fullname="NUnitInheritedTests.CalculatorNormalTest.WhenTheAddOperatorIsCalledTheExpectedResultIsReturned" methodname="WhenTheAddOperatorIsCalledTheExpectedResultIsReturned" classname="NUnitInheritedTests.CalculatorNormalTest" runstate="Runnable" seed="202129304" result="Passed" start-time="2016-03-17 09:57:41Z" end-time="2016-03-17 09:57:41Z" duration="0.000558" asserts="1" />
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>
````

**Comment by SeanFarrow** [comment] 2016-04-05 12:29
Hi Chris,

 

Having done some further investigation on this, it appears that if at least one method in the project has a [Test] attribute and hence has a reference to Nunit.Framework, it all works. Can you try changing all the methods with the Test attribute to the Inherited test attribute.

This should, in my mind still work, as InheritedTestAttribute is inherited from TestAttribute.

Hth.

Sean.

**Comment by CharliePoole** [comment] 2016-04-05 15:30
@SeanFarrow Are you implying that your base fixture class is in a different assembly?

**Comment by SeanFarrow** [comment] 2016-04-05 15:40
I’m not sure, it just seems odd, that when I add the test attribute it all works even though my attribute is derived from it in the first place!

**Comment by CharliePoole** [comment] 2016-04-05 15:52
@SeanFarrow I'm confused. How can you be unsure of where you defined the class in question?

However, if that is the case, then the problem is different from how we have been looking at it. When the NUnit test engine examines an assembly to see if it knows how to run it, it looks at all the references of that assembly. If it has a reference to the nunit.framework assembly, then it will run it using either the NUnit2 or the NUnit3 driver, depending on the version. If it has no such reference, then it's either a non-test assembly or a test for some other framework.

In your initial post, you indicated you are using JustEat / JustBehave for your tests. If this framework provides the base class for you, then it's defined in their assembly, not your test assembly. NUnit will find all the inherited attributes if it once loads the tests. But if your test assembly itself contains no direct reference to the nunit framework, then NUnit will never even look at it.

Is that the situation?

**Comment by SeanFarrow** [comment] 2016-04-05 15:56
OK, sorry the class is in the same assembly as the test. I’ve verified things with other projects, and the behaviour seems constant.

**Comment by ChrisMaddock** [comment] 2016-04-05 16:41
Hi @SeanFarrow,

> Having done some further investigation on this, it appears that if at least one method in the project has a [Test] attribute and hence has a reference to Nunit.Framework, it all works. Can you try changing all the methods with the Test attribute to the Inherited test attribute.

Hmm, have tried this, and still unable to replicate the issue, I still see two tests. 

Like Charlie, I'm also a little confused by how the reference to Nunit.Framework comes in to it. I'm still running off your repo at https://github.com/SeanFarrow/NUnitInheritedTestsNotFoundRepro. Would you be able to update this to a reproducible test case, so we're definitely looking at the same thing? 

Can you also clarify exactly what you mean by "not being recognised"? Is this in the nunit-console, or a particular test runner?

**Comment by SeanFarrow** [comment] 2016-04-06 08:00
Hi Both,

The bug is actually simpler than first thought:
when using a third party library JustEat.JustBehave, who has [TestFixture] on there base classes, When inheriting one class, tests are not run, unless the [Test attribute is added to there attribute. I’ll put a sample together to illustrate if required.
This worked in Nunit2.
Cheers
Sean.

**Comment by CharliePoole** [comment] 2016-04-06 09:14
A sample may help. However, if you are saying that the test assembly (your assembly) has to have at least one reference to nunit.framework, then that's already been covered. It's how the engine works currently.

This was not the case in NUnit V2, which tried to run any test assembly you gave it. But the new version supports multiple frameworks so it has to figure out what framework driver to use when loading your tests.

However a good sample may still help us figure out the best workaround.

**Comment by SeanFarrow** [comment] 2016-04-06 09:17
When you say a reference, does a class in the  test assembly have to use the NUnit.Framework namespace, or just reference the NUnit.Framework assembly?

**Comment by CharliePoole** [comment] 2016-04-06 09:28
The reference has to actually exist in the assembly metadata. Most compilers won't actually create the reference unless you actually use the assembly in some way. That use may be direct or indirect. The easiest way to tell is to delete the reference in the IDE. If the compiler doesn't complain, then you were not using it. You can also look at the metadata using ildasm or another utility.

**Comment by SeanFarrow** [comment] 2016-04-06 09:55
Ok, that’s what is happening.
I’ll put a sample together, but in essence, how possible would it be to look at second level references, if the assembly passed in doesn’t reference NUnit.Framework as thurd-party libraries might.
Cheers
Sean.

**Comment by CharliePoole** [comment] 2016-04-06 16:16
@SeanFarrow It's certainly possible to dig deeper into references but it could involve some performance issues. There are two simple approaches to avoid this:

1) Recognize certain known third-party assemblies that wrap nunit.framework. I'd prefer to get that request from the folks maintaining the third-party library, however.

2) Document the necessity of adding a reference to any nunit test assembly that doesn't otherwise have one. This wouldn't be needed if you were using other nunit framework facilities like TestContext. But if you were not, then something as simple as an assembly-level Description attribute should do the job.

**Comment by SeanFarrow** [comment] 2016-04-06 19:27
Could we not provide a mechanism for users to state that they are using a third-party framework. If not how would I ensure that the NUnit.Framework assembly is referenced, you mentioned an assembly level attribute?

**Comment by CharliePoole** [comment] 2016-04-06 21:31
I thought of that. If we had an assembly-level attribute like UsesNUnitFrameworkAttribute that you could add we could check it and avoid looking for the actual framework.

But then I realized that the act of adding the attribute would create a reference to nunit.framework, thereby making the attribute unnecessary! Crazy, right?

So, in fact, __any__ assembly-level existing NUnit attribute will serve: LevelOfParallelism, Description, Timeout, etc. May as well just use one of those.

So, I'm not sure there's actually anything useful to do here!

**Comment by CharliePoole** [comment] 2016-04-06 21:32
Well... except for telling people about this!

**Comment by SeanFarrow** [comment] 2016-04-07 04:50
Ok, that makes sense.
Adding some documentation would be useful. Feel free to close the issue!

**Comment by CharliePoole** [comment] 2016-04-07 05:22
We'll need to figure out where this goes in the documentation and add some info. Maybe we should also reach out to projects that wrap the NUnit framework to let them know they should also document it.

**Comment by SeanFarrow** [comment] 2016-04-07 05:40
Yes, that sounds like a good idea, I’m reaching out to JustEat as we speak.

**Comment by CharliePoole** [comment] 2016-06-21 15:35
Issue moved to [nunit/docs #68](https://github.com/nunit/docs/issues/68) via [**ZenHub.io**](https://www.zenhub.io/)

**Closed by CharliePoole** 2016-06-21 15:35 UTC
Labels: is:docs, pri:low
