### ISSUE TITLE
Has.Property cannot see explicit interface implementation properties

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#1394] opened 2016-04-06 05:00 UTC
Using nunit.framework 3.2 and nunit3-console 3.0.1.

Code:

```
using NUnit.Framework;

namespace NUnitHasProperty
{
    public interface IFoo
    {
        string Description { get; }
    }

    public class ImplicitFoo : IFoo
    {
        public string Description => "Foo";
    }

    public class ExplicitFoo : IFoo
    {
        string IFoo.Description => "Foo";
    }

    [TestFixture(typeof(ImplicitFoo))]
    [TestFixture(typeof(ExplicitFoo))]
    public class HasPropertyTestCase<TFoo>
        where TFoo : IFoo, new()
    {
        [Test]
        public void DescriptionIsFoo()
        {
            IFoo thing = new TFoo();
            Assert.That(thing, Has.Property(nameof(IFoo.Description)).EqualTo("Foo"));
        }
    }
}
```

Results:

```
NUnit Console Runner 3.0.5813
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10240.0
  CLR Version: 4.0.30319.42000

Test Files
    NUnitHasProperty.dll


Errors and Failures

1) Error : NUnitHasProperty.HasPropertyTestCase<ExplicitFoo>.DescriptionIsFoo
System.ArgumentException : Property Description was not found
Parameter name: name
   at NUnit.Framework.Constraints.PropertyConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
   at NUnitHasProperty.HasPropertyTestCase`1.DescriptionIsFoo() in C:\temp\NUnitHasProperty\NUnitHasProperty\HasPropertyTestCase.cs:line 29

Run Settings
    WorkDirectory: C:\temp\NUnitHasProperty\NUnitHasProperty\bin\Debug
    NumberOfTestWorkers: 12

Test Run Summary
    Overall result: Failed
   Tests run: 2, Passed: 1, Errors: 1, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2016-04-06 04:58:54Z
    End time: 2016-04-06 04:58:54Z
    Duration: 0.085 seconds

Results (nunit3) saved as TestResult.xml
```

**Comment by CharliePoole** [comment] 2016-04-06 05:14
Are you sure this is not an artifact of using nameof in the code rather than a string?

**Comment by yaakov-h** [comment] 2016-04-06 05:18
Yes. If I add the following test, then I now have 3 passing and 1 failing - failing one is as above.

```
[Test]
public void NameOfIFooDescriptionIsDescription()
{
	Assert.That(nameof(IFoo.Description), Is.EqualTo("Description"));
}
```

**Comment by rprouse** [comment] 2016-04-07 14:45
I have confirmed this issue and confirmed that it has nothing to do with the nameof operator.

**Comment by mjedrzejek** [comment] 2016-05-06 21:57
Maybe this is not a real case, but if this is an issue, what should be the result in case of a class which have property Description implemented twice (explicit and implicit):
`   public class ExplicitFoo : IFoo
    {
        public string Description => "Foo";
        string IFoo.Description => "Bar";
    }
`
Should we check both properties?

**Comment by yaakov-h** [comment] 2016-05-07 08:22
Good question. For another example, everything that implements `IEnumerable<T>` does this - one `IEnumerator<T> GetEnumerator()` from `IEnumerable<T>` and one `IEnumerator GetEnumerator()` from `IEnumerable`.

**Comment by CharliePoole** [comment] 2016-05-07 14:13
All of this will remain somewhat adhoc so long as we are not passing through the types of the supplied arguments but are converting them to objects. Once we have actual types - probably through use of generic methods - we would want to use the appropriate interfaces implemented for those types. That is, if an interface is passed we would use the explicit implementation, otherwise we wouldn't.

For now, we are forced to do the best we can using some sequence of searching for appropriate implementations.

**Comment by rprouse** [comment] 2016-10-03 13:12
From @NUnitTester, this also causes `Count` to not be found where an array is cast to an `ICollection` because arrays explicitly implement `ICollection`.

--

`ICollection<int> numbersCollection = IWorker.DoMethod();`
`Assert.That(numbersCollection, Has.Count.EqualTo(3));`

Think about the following usecase: You will test different implementations of IWorker given as parameter of tha attribute TestFixture, in my case 3. Two will use an Array to give back as ICollection<int> and one will give back an HashSet<int>. 
How to write the Unit-Test with Has.Count or Has.Length?

And don't answer to use Is.EqualTo ... I know it.

**Comment by CharliePoole** [comment] 2016-10-03 20:56
From #1816...

"Let's decide two things here: (1) how it should be and (2) how it can be right now, since our assertions are currently based on objects."

What I meant is

(1) Let's decide how we think this should work, assuming no restrictions on implementation. I think it's important to decide this first, before making any immediaate changes.

My own view is that we should be able to see an explicitly implemented property if the actual value passed to the assert is of the interface Type. So an array passed as `(ICollection<int>)array` would have a `Count` property and not a `Length` property. If passed directly, it would have `Length` but not `Count`.

(2) Given that the current implementation cannot actually see whether the actual value was passed as an object or as some interface, we next should decide whether to change the current behavior at all. Our choices seem to me to be to never show explicit interface properties or to always show them.

**Comment by MichalBrylka** [comment] 2020-11-30 13:32
Hi,
this still seems to be not fixed. See here for some more practical example:
https://gist.github.com/MichalBrylka/da9028fc4f2a472a1f9de263b0f63dbb

Also - would it be possible to add Has.Cardinality constraint that will look for either Count/Length/Size properties and resolve them appropriately ?


Can I help fixing any of these ?

**Comment by CharliePoole** [comment] 2020-11-30 17:33
Looks like nobody has touched this since my comment in 2016, when I was still working on the framework. I think the comment itself still applies and the team needs to set both a long term and short term direction.

`<meta>`
Back in the early days of Extreme Programming, there was a notion of a "tracker" role. I wonder if we don't need something like that here. Maybe someone in the @nunit/framework-team could volunteer or be selected to track the age of requests like this and see if they can be either closed or moved along to a decision. Just a thought.
`</meta>`

**Comment by jnm2** [comment] 2020-11-30 17:41
From a .NET runtime perspective, an object does not have a property with that name. This is because C# explicitly implemented properties do not become properties of the class with that name. They become properties of the class with the name `Full.Interface.Namespace.And.Type.Name.InterfacePropertyName`.

**Comment by CharliePoole** [comment] 2020-11-30 18:18
@jnm2 Yes... I think the reason it doesn't work has been discussed way back. But what should users expect to work and what should they not expect?

I agree with you that the framework should support some subset of the possible things users might want to use. Since they are passing in a string, I feel it should work wherever c# `className.propName` would work, but not elsewhere. By longer term, I was thinking of the idea of replacing the string by a lambda, which has been floating around for a while - and also not followed up AFAIK.

**Comment by jnm2** [comment] 2020-11-30 20:04
I'd like to propose that we search for properties on `typeof(T)`, where `T` is the generic type parameter of `Assert.That<T>`. Usually it is implicit. In the initial examples, `T` would be `IFoo` because the initial example is implicitly calling `Assert.That<IFoo>`. This would make the initial example work and fit most people's expectations, I think.

We probably don't want to stop our current search for properties on `actual.GetType()`. If we stopped searching on `actual.GetType()`, it would break tests like this:
```cs
Base actual = new Derived(); // This code may have been spread out in reality
Assert.That(actual, Has.Property("SomeProperty").EqualTo(42));

class Base { }
class Derived : Base
{
    public int SomeProperty { get; set; }
}
```

I do not like the idea of being able to find explicitly-implemented properties when `Assert.That<object>` or `Assert.That<ImplementingType>` is called. I think that you should implicitly or explicitly use `Assert.That<InterfaceType>` if you want to use explicitly-implemented properties, just like how C# and VB require you to cast to the interface type to access them.

An outstanding question would be whether to *prefer* `typeof(T)` properties with the same name over `actual.GetType()` properties. The most backwards-compatible answer would be to prefer what we have done in the past and add `typeof(T)` as a fallback if no property was found. It seems unlikely for the difference to matter in practice though. I lean towards preferring `typeof(T)` over `actual.GetType()` because that's the property the compiler would select if you dotted off the `actual` expression passed to `Assert.That`.

I'm not thinking of further benefits that a lambda would give us beyond what I'm proposing above, but we can look at them if they come to light.

**Comment by NUnitTester** [comment] 2020-12-01 12:04
I think there is a big difference if we talk about interfaces and abstract classes or implementation classes.

The object is used by interface in this example. And the interface has such a property, so it must be found in any case, explicit or implicit. It is part of the interface. 

This is the same thing, if IReadOnlyCollection with Count-Property is uses, but the implementing class is an Array with "normal" Property Length.

**Comment by jnm2** [comment] 2020-12-01 13:46
@NUnitTester Yep, that's the point I'm making when I say we should use `typeof(T)` to search for properties, which will be the interface type if the `actual` expression passed to Assert.That was of that interface type.

At least I think it's the same point. I would not say that we should find an explicit implementation in any case. Only in the case where the `actual` expression is of the interface type. Same as how C# will not find an explicit implementation unless you first cast to the interface type.

**Comment by MichalBrylka** [comment] 2020-12-01 14:40
ok, good to hear that this problem is solvable. 
Meanwhile, I might propose both short term (it will work) and long term (probably having better usability) solution for collections sizes. I'd like to add Cardinality Constraint. What's the best approach to do that ? I started quickly with that:
https://gist.github.com/MichalBrylka/183c0cd60e4962a7b7314527142ff33c

Would this be useful ? Would you accept such addition to framework ? Obviously it can be optimized...

**Comment by jnm2** [comment] 2020-12-01 15:58
@MichalBrylka I would recommend starting a separate issue to propose a new API. In the short term, this proposal to fix `Has.Property` should also cause `Has.Count` and `Has.Length` to just start working as you'd expect. In the long term, `Has.Cardinality` would have to give a reason why it's better than changing the way the `Has.Count` constraint works to specifically special-case counting an IEnumerable or ICollection. Having three APIs with such similar meanings is cognitive overload and it would have to be worth its weight compared to the other alternatives.

**Comment by MichalBrylka** [comment] 2020-12-01 16:07
> @nunit/framework-team what do you think?
I'm not in the team but I like the idea. Anybody eager to change that ?

**Comment by MichalBrylka** [comment] 2020-12-01 16:07
> I'd like to propose that we search for properties on `typeof(T)`, where `T` is the generic type parameter of `Assert.That<T>`. Usually the type argument is implicit when calling `Assert.That`. In the initial examples, `T` would be `IFoo` because the initial example is implicitly calling `Assert.That<IFoo>`. This strategy would make the initial example work and fit most people's expectations, I think.
> 
> We probably don't want to stop our current search for properties on `actual.GetType()`. If we stopped searching on `actual.GetType()`, it would break tests like this:
> 
> ```cs
> Base actual = new Derived(); // This code may have been spread out in reality
> Assert.That(actual, Has.Property("SomeProperty").EqualTo(42));
> 
> class Base { }
> class Derived : Base
> {
>     public int SomeProperty { get; set; }
> }
> ```
> 
> I do not like the idea of being able to find explicitly-implemented properties when `Assert.That<object>` or `Assert.That<ImplementingType>` is called. I think that you should implicitly or explicitly use `Assert.That<InterfaceType>` if you want to use explicitly-implemented properties, just like how C# and VB require you to cast to the interface type to access them.
> 
> An outstanding question would be whether to _prefer_ `typeof(T)` properties with the same name over `actual.GetType()` properties. The most backwards-compatible answer would be to prefer what we have done in the past and add `typeof(T)` as a fallback if no property was found. It seems unlikely for the difference to matter in practice though. I lean towards preferring `typeof(T)` over `actual.GetType()` because that's the property the compiler would select if you dotted off the `actual` expression passed to `Assert.That`.
> 
> I'm not thinking of further benefits that a lambda would give us beyond what I'm proposing above, but we can look at them if they come to light.
> 
> In summary, I'm proposing that:
> 
> * We use `typeof(T)` in `PropertyConstraint.ApplyTo<T>` instead of `actual.GetType()` to do the property search.
> * If no property was found, we fall back to doing the same search, this time on `actual.GetType()`, to preserve past behavior.
> * We do _not_ loop over `actual.GetType().GetInterfaces()` and search for properties on each interface.
> 
> With the question of switching them around and searching in `actual.GetType()` first and making `typeof(T)` the fallback.
> 
> Either way, this would fit the `good first issue` label.
> 
> @nunit/framework-team what do you think?

I'm not in the team but I like the idea. Anybody eager to change that ?

**Comment by jnm2** [comment] 2020-12-01 16:20
@MichalBrylka The purpose of the new issue is so that the discussion doesn't happen in this thread. Thanks!

**Comment by jnm2** [comment] 2020-12-01 16:29
@MichalBrylka Thanks for your input, it helps! Your quote included my entire post above. I edited your comment to make the thread more readable.

By "anybody eager to change that" are you asking if anyone is eager to propose something different or if anyone is eager to make the proposed change to NUnit? We'd be grateful for contributions in either area, and it'll be up to the @nunit/framework-team to decide on a direction before the implementation phase starts.

**Comment by MichalBrylka** [comment] 2020-12-01 16:42
@jnm2
ok, thanks for edit

By saying "anybody eager to change that" I meant:
I can contribute here as long as you have consensus on choosing the approach aligned with your taste, so that this work will not go in vain :)

**Comment by rprouse** [comment] 2020-12-01 20:49
> @NUnitTester Yep, that's the point I'm making when I say we should use `typeof(T)` to search for properties, which will be the interface type if the compile-time type of the `actual` expression passed to Assert.That was the interface type.
> 
> At least I think it's the same point. I would not say that we should find an explicit implementation in any case. Only in the case where the compile-time type of the `actual` expression is the interface type. Same as how C# will not find an explicit implementation unless you first cast to the interface type. So `Assert.That<Array>` should not find a `Count` property, but `Assert.That<ICollection>` should.

I'll second @jnm2's comment and the rest of his leadership in this thread, so I think you can go ahead based on his direction.

**Comment by jnm2** [comment] 2020-12-01 20:57
Thanks @rprouse!

@MichalBrylka I'll take you up on your generous offer to contribute. Take your time and feel free to tell us if you change your mind. If you have questions, comment here or in our Slack channel ([join link](https://join.slack.com/t/nunit/shared_invite/zt-jz58jw68-Led8y3WH4n2a~Y5WjuOpKA)). Is there anything I can clarify about the implementation plan for the proposal above?

**Comment by MichalBrylka** [comment] 2020-12-02 13:25
@jnm2 I think I'll be able to tackle that, just not this week. Usual workflow of:
forking repo -> commits-> push -> PR to nunit 
works in your team ?

**Comment by jnm2** [comment] 2020-12-02 15:35
@mjedrzejek Sounds good. Yes, that's what we do.

**Comment by MichalBrylka** [comment] 2020-12-02 15:39
@jnm2 I take this as it was intended as answer to my comment. If so - just gimme some time and I'll be back

**Comment by jnm2** [comment] 2020-12-02 15:44
Sorry about that. Yes, take all the time you need.

**Comment by MichalBrylka** [comment] 2020-12-03 00:19
> * We do _not_ loop over `actual.GetType().GetInterfaces()` and search for properties on each interface.

@jnm2 do I understand that this should pass:
``` csharp
[Test]
        public static void PropertyExists_PropertyDefinedInInterface_ShouldExist_WhenCast()
        {
            var instance = (ICollection<int>)new[] { 1, 2, 3 };
            var sut = new PropertyConstraint(nameof(IList<object>.Count), new EqualConstraint(instance.Count));

            var actual = sut.ApplyTo(instance);

            Assert.That(actual, Has.Property(nameof(ConstraintResult.Status)).EqualTo(ConstraintStatus.Success));
        }
``` 

while this should fail: 
``` csharp
[Test]
        public static void PropertyExists_PropertyDefinedInInterface_ShouldExist_WhenCast()
        {
            var instance = (IList<int>)new[] { 1, 2, 3 };
            var sut = new PropertyConstraint(nameof(IList<object>.Count), new EqualConstraint(instance.Count));

            var actual = sut.ApplyTo(instance);

            Assert.That(actual, Has.Property(nameof(ConstraintResult.Status)).EqualTo(ConstraintStatus.Success));
        }
``` 

?

IList<> "obviously" contains Count property

**Comment by jnm2** [comment] 2020-12-03 15:24
@MichalBrylka That's a great question. I think we should take our cue from how .NET languages work in general. Since `((IList<int>)array).Count` is allowed at compile time, I think `Assert.That((IList<int>)array, Has.Property("Count"));` should succeed. That would allow us to leverage the mental model that people are used to using. "I'm using thing as an `IList<int>`. Does `IList<int>` have a Count property?" The most practical answer is yes, if you have an `IList<int>`, you can get a count.

By the same reasoning, we should not use `actual.GetType().GetInterfaces()` as a solution because `Assert.That((object)array, Has.Property("Count"));` should fail just like `((object)array).Count` would fail.

**Comment by MichalBrylka** [comment] 2020-12-03 16:40
@jnm2 ok, I'm in favour of that approach. In that case, in PropertyConstraint.ApplyTo<T>, if T is any interface, I'll look in all interfaces that T "couples"

**Comment by jnm2** [comment] 2020-12-03 18:17
@MichalBrylka The official term is "inherits" btw; `IList<T>` inherits from `ICollection<T>`. Unlike class inheritance which only allows inheritance from exactly one class, interface inheritance can be from multiple base interfaces.

**Comment by jnm2** [comment] 2020-12-03 18:21
Here's how we can be safe: if `typeof(T).IsInterface` is true, then we know that we should search `typeof(T).GetInterfaces()` if we didn't find the property in `typeof(T)`. If `typeof(T).IsInterface` is false, we had better not search `typeof(T).GetInterfaces()` because we want `Assert.That((object)array, Has.Property("Count"));` to fail. (There should be a test for each of these scenarios.)

**Comment by CharliePoole** [comment] 2020-12-03 18:22
@jnm2 My comment about a lambda-based approach was intended as a reference to issue #26, from 2013 but actually going back to a 2011 request when the project was on Launchpad. So this ties into the separate discussion we have been having about extremely old issues. If that is no longer seen as a potential direction, that issue should be closed.

**Comment by jnm2** [comment] 2020-12-03 18:35
@CharliePoole Thanks for making me aware of #26. I commented there since I believe this current issue is resolved independently of it.

**Comment by MichalBrylka** [comment] 2020-12-03 18:58
@jnm2 I usually use "extend" for interfaces to contrast it from class inheritance. But I wanted to convey the sense of interface "bundling" hence I used other term. Sorry, English is not my first language;)
What you suggested is exactly what I had in mind

**Comment by jnm2** [comment] 2020-12-03 19:01
@MichalBrylka In this case it's not an English term but rather a .NET ecosystem term. Interfaces inherit from other interfaces, classes inherit from other classes, and 'derive' and 'extend' can be used interchangeably with 'inherit' from what I've heard.

You're ahead of me on this one, perfect!

**Comment by CharliePoole** [comment] 2020-12-03 19:16
Agree on the terminology. In addition, I believe the correct usage for class : interface is that the class "implements" the interface. At least that's what I was taught to say. :smile:

**Comment by MichalBrylka** [comment] 2020-12-03 22:00
Have a look here if that's to your liking:
https://github.com/nunit/nunit/pull/3686

Moreover, which set of tests of nunit framework itself should be always passing ? Do you have specific playlists, categories... ?

**Comment by mikkelbu** [comment] 2020-12-03 22:07
Regarding the tests, then they should all pass if you use the cake script `.\build.ps1 -Target Test` in powershell (and similar in bash), see e.g. https://github.com/nunit/nunit/blob/master/BUILDING.md. If you run the tests from VS then the following should pass
* nunit.framework.tests-*
* nunitlite.tests-*

(some of the other test projects contain tests designed to fail purposely for integration tests).

**Comment by MichalBrylka** [comment] 2020-12-03 22:22
@mikkelbu thanks. Upon running tests in VS, some of them failed (cause they should i.e. they were testing faulty stuff), but running build script says everything is fine. Appveyor also seems not to be complaining

**Closed** 2020-12-28 21:15 UTC
Labels: is:bug, pri:normal
