### ISSUE TITLE
NUnit.Console Package Changes

### ISSUE THREAD

**Issue by michael-x** [nunit/nunit#1323] opened 2016-03-07 15:25 UTC
It appears that stuff in **NUnit.Console** has been moved from `tools` to `bin` (which breaks our build server). Furthermore it looks like the new **NUnit.ConsoleRunner** package might be a better replacement, as for one thing it still has got the "tools" in the `tools` folder and for another it's the smaller package (unfortunately we would still need to change our build server to use the other package).

Before we change our build server:
* Was the switch from `tools` to `bin` in **NUnit.Console** intentional or will that be changed back?
* Would it be recommended to use **NUnit.ConsoleRunner** or is that more or less only created for internal purposes? What constraints does it have?

Thanks.

**Comment by rprouse** [comment] 2016-03-07 15:50
I am pretty sure that was not intentional. **NUnit.Console** is intended to be a meta package that includes **NUnit.ConsoleRunner** and all of the engine extension packages. We didn't intend to include the bin directory and it isn't specified in the [NUSPEC](https://github.com/nunit/nunit/blob/master/nuget/runners/nunit.console-runner-with-extensions.nuspec) file. I guess it is getting pulled in because we didn't specify any files? You should ignore everything in the bin folder, they are not intended to be there. At this point, you should switch to using the runner in the tools directory of **NUnit.ConsoleRunner**, that is where it will live going forward.

@CharliePoole, I think I should release an update to the **NUnit.Console** package.   I should probably increment the version. 3.2.0.1?

**Comment by michael-x** [comment] 2016-03-07 16:07
I'm wondering, whether there is a conceptual problem with your **NUnit.Console** package then. How will `nunit3-console.exe` know in which folders to look for the extension packages? Each will be installed into a separate `tools` folder within a separate (versioned) package folder in your `packages` folder. Does it know that it needs to look for `nunit-project-loader.dll` in `..\..\NUnit.Extension.NUnitProjectLoader.3.2.0\tools`? What if the version is changed?

Consumers of the package would have to copy the binaries from each of the `tools` folders into a shared folder or amend the PATH/AssemblyLoadPath somehow.

**Comment by rprouse** [comment] 2016-03-07 16:23
@michael-x loading of the extensions from the tools folders of the extension packages is working. **NUnit.Console** should not contain any files, it is just a meta package that collects the dependencies that make up a full console runner with all of the available extensions.

**Comment by CharliePoole** [comment] 2016-03-07 16:26
I marked this status:confirm because I don't understand where the bin directory is coming from. If the nuget packages are not working right, we should immediately replace them with corrected packages using the same binaries, of course.

I think it's likely that NuGet has some default behavior that I wasn't aware of when you __don't__ specify any files. We may need some sort of test - maybe not NUnit tests, but some sort - that verifies the content of a package against our expecteations.

**Comment by CharliePoole** [comment] 2016-03-07 16:29
@michael-x The ability to find those extensions is something we added in 3.2. It's only available when the engine (included with NUnit.ConsoleRunner is installed as a part of a package. The easiest way to verify this is to install both NUnit.ConsoleRunner and NUnit.Extension.NUnitProjectLoader into a project and then use NUnit to open a `.nunit` project file. It will fail without the extension and succeed with it.

**Comment by rprouse** [comment] 2016-03-07 17:15
@CharliePoole I had already confirmed by downloading the packages using NuGet Package Explorer. It does include the entire bin directory including all frameworks and all extra files. I believe that if you don't specify files, it pulls all files in. I think that is to make it easy to create packages, but it bit us here.

For verifying in the future, I use [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) all the time. It loads packages from feeds or from local files. I should have verified using it before release rather than just installing packages.

I will repackage this afternoon. I still have the initial binaries, I just need to repackage. Since NUnit.Console doesn't contain any packages, I am just going to fix and repackage that.

**Comment by CharliePoole** [comment] 2016-03-07 19:42
Ah, I didn't realized you had done that already.

I usually check them as well (I just use 7-zip) but I didn't do it for anything but the engine packages this time. What I meant was that we should have something automated, in an acceptance test, that does the checking for us. Meantime, we should keep checking manually.

**Comment by CharliePoole** [comment] 2016-03-07 19:46
@rprouse I imagine you will have to redo NUnit.Runners as well as I'd expect it to have the same problem. I think using 3.2.0.1 makes sense for a "packaging  only" update.

**Comment by rprouse** [comment] 2016-03-07 19:56
Actually, NUnit.Runners is fine. It has `<files></files>` at the end, thus the difference. I am working on the update now.

**Comment by rprouse** [comment] 2016-03-07 20:28
@michael-x I have pushed NUnit.Console 3.2.0.1 to NuGet. It is now the meta package that it was intended to be. You will find the console under the tools directory in NUnit.ConsoleRunner. This issue will be closed when the PR for the changes is merged back into master.

**Comment by CharliePoole** [comment] 2016-03-07 20:48
The location is a change for those who have scripts to update. We should probably document this somewhere, but I can't really think where it would go.

**Comment by rprouse** [comment] 2016-03-07 21:12
@CharliePoole, I agree, although the location change is no different than we did with the 3.0 release when we made the existing NUnit.Runners package a meta package that pointed at this one. Unfortunately, we ended up switching again :frowning: 

I am not sure about most build tools, but some, like Cake just search through the packages directories until it finds what it needs. Hopefully that is the case with most?

Does this belong on the breaking changes page?

**Comment by CharliePoole** [comment] 2016-03-07 21:20
The trouble is it never crossed my mind that this was a breaking change in 3.0, so it's not listed. Actually, there's nothing listed about packaging there.

Currently, the page is all about breaking changes from 2.6.4.  Do we want to subdivide it using headers for each release?

Another approach is to have a page somewhere  that goes into more detail about installing and using the nuget packages, and keep that up to date.

**Closed** 2016-03-07 21:21 UTC
Labels: closed:done, is:bug, pri:critical

**Comment by asbjornu** [comment] 2016-04-19 20:33
I just upgraded `NUnit.ConsoleRunner` from version `3.2.0` to version `3.2.1` and got the following output from `nunit3-console.exe` that I haven't seen before:

```
NUnit Console Runner 3.2.1
Copyright (C) 2016 Charlie Poole

ProjectLoader extension .nunit is already handled by another extension.
```

Is this in any way related to the discussion above?

**Comment by rprouse** [comment] 2016-04-19 20:45
@asbjornu, does it cause an error, or is it just the message. I want to assess the seriousness of the issue.

@CharliePoole any idea why we have two extensions handling .nunit projects?

**Comment by asbjornu** [comment] 2016-04-19 21:06
@rprouse It caused an error. Your question to @CharliePoole made me think that the problem might be leftovers from version `3.2.0`, so I did a clean (`git clean -xdf`) a fresh `nuget restore` and a rebuild, and now the tests execute again. Not sure this is anything you can do anything about, but I assume others are going to experience the same problem after upgrading from `3.2.0` to `3.2.1` without doing a clean in-between.

**Comment by CharliePoole** [comment] 2016-04-19 22:21
@rprouse we don't install more than one but there could be leftover stuff hanging around.

**Comment by rprouse** [comment] 2016-04-20 00:06
@asbjornu thanks for the update. It sounds like we are trying to load extensions found in the 3.2 NuGet packages. Going forward, I think it is common that there will be older NuGet packages in the packages directory. I also don't think we deal with ignoring newer packages when older packages are installed. If we are probing for extensions, it is likely that we will load the older versions first since they are first in alpha order.

@CharliePoole, there is a workaround, but it is less than ideal. I think this warrants a new issue and some work, agree?

**Comment by CharliePoole** [comment] 2016-04-20 04:49
I agree although I'm somewhat surprised that upgrading leaves the old packages around.

This may not be so easy to fix either. Some extension points are intended to have multiple extensions. However, the same extension should not be active multiple times on different versions.

**Comment by rprouse** [comment] 2016-04-20 06:36
@CharliePoole, upgrading does leave older packages in place. While I was testing the 3.2.1 release yesterday, I went into the packages directory of a project I use for testing NUnit to check that all the NuGet packages installed correctly and there were copies of the framework going all the way back to early alphas.

I created #1427 to track this.

**Comment by jkonecki** [comment] 2016-05-03 11:56
I can confirm that clearing the packages folder and restoring version 3.2.1 solved the problem.
