### ISSUE TITLE
Assert.Contains does not work with generic lists

### ISSUE THREAD

**Issue by BlueRaja** [nunit/nunit#4093] opened 2022-04-08 02:45 UTC
[The API](https://docs.nunit.org/articles/nunit/writing-tests/assertions/classic-assertions/Assert.Contains.html) only has an overload for `ICollection`. For reasons beyond me, [`ICollection<T>` does not implement `ICollection`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1?view=net-6.0). Thus generic collections don't work with the NUnit API.

The solution would be to add overloads for `ICollection<T>` _(or maybe even `IEnumerable<T>`)_

**Comment by manfred-brands** [comment] 2022-04-08 02:57
It works if you use the new [collection constraints](https://docs.nunit.org/articles/nunit/writing-tests/constraints/CollectionContainsConstraint.html): 

`Assert.That(myGenericCollection, Does.Contain(member))`

**Comment by BlueRaja** [comment] 2022-04-08 03:00
I'm aware of that workaround, but that seems tangential to this bug report.

**Comment by manfred-brands** [comment] 2022-04-08 03:09
It is not a bug if it was never designed to work. The old interface predates generics.
You could call your issue a feature request to add support for generics to the old interface.

My suggestion is not a workaround but the recommended way.
If you run the [nunit.analyzers](https://www.nuget.org/packages/NUnit.Analyzers/) it [suggests](https://github.com/nunit/nunit.analyzers/blob/master/documentation/NUnit2037.md) you to update the code to the newer interface. With CodeFixes to do the change for you.

**Comment by stevenaw** [comment] 2022-04-08 03:41
I agree with @manfred-brands here. I think there may be some documentation updates tracked by #3688 which can help clarify this, but the constraint model would be the recommended way.

**Comment by stevenaw** [comment] 2022-04-08 23:56
Based on https://github.com/nunit/nunit/issues/3644#issuecomment-739528178 the team's default position is that we should not add new Assert APIs. I am going to close this as answered, but please note that we will still see and can respond to additional comments.

**Closed by stevenaw** 2022-04-08 23:56 UTC
