### ISSUE TITLE
Is there anything special in the way NUnit create AppDomain to execute tests in?

### ISSUE THREAD

**Issue by NKnusperer** [nunit/nunit#771] opened 2015-08-11 12:59 UTC
I'am fighting an issue for a while that in the context of a NUnit runner I cannot do .Net remoting calls.
This issue is already logged at Xamarin (https://bugzilla.xamarin.com/show_bug.cgi?id=31091).
Today I found out then when using the `--domain=none` everything works as expected so this must have something to do with the way NUnit create/handles AppDomains.
This happens both in NUnit 2 and 3.
Unfortunately I cannot reproduce the issue when creating my own AppDomain so the question is if NUnit is doing something special that would explain this behavior?

**Comment by CharliePoole** [comment] 2015-08-11 18:51
Here is my guess, based on reading the Xamarin bug... it's only a guess as I have not tried to reproduce the situation.

When your echo service is reached, it tries to connect back to the calling client, which is the executing process. Due to the mechanism of the channel you created, this connection is routed to the proper endpoint when you are running in the primary AppDomain. The primary AppDomain when running under NUnit is taken up by the NUnit code, which is not set up to handle the connection or to forward it to your test in the test domain.

This is exactly the reason for the --domain=None option. There are certain operations that cannot take place except in a primary AppDomain. They are very difficult to test with NUnit but --domain=None gives you a not-very-convenient-but-workable workaround.

I don't believe this is a bug in NUnit. The fact that it works for a Windows server would indicate to me that Windows **is** able to locate the proper endpoint, while Mono is not.

**Comment by rprouse** [comment] 2015-09-08 13:58
Moving to 3.0RC for confirmation. We may change the milestone based on the results of our investigation.

**Comment by rprouse** [comment] 2016-06-29 19:23
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Closed by rprouse** 2016-06-29 19:23 UTC
Labels: confirm
