### ISSUE TITLE
SetUpFixture is not recognized when found in a different assembly.

### ISSUE THREAD

**Issue by MarkKharitonov** [nunit/nunit#2893] opened 2018-06-16 04:51 UTC
I have a trivial reproduction.
The result of building and running the code:
```
C:\temp\2> msbuild /v:m /nologo
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the NuGet Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  Feeds used:
    C:\Users\mkharitonov\.nuget\packages\
    https://api.nuget.org/v3/index.json

  Restoring NuGet package NUnit.ConsoleRunner.3.8.0.
  Restoring NuGet package NUnit.3.10.1.
  Adding package 'NUnit.3.10.1' to folder 'C:\temp\2\packages'
  Adding package 'NUnit.ConsoleRunner.3.8.0' to folder 'C:\temp\2\packages'
  Added package 'NUnit.ConsoleRunner.3.8.0' to folder 'C:\temp\2\packages'
  Added package 'NUnit.3.10.1' to folder 'C:\temp\2\packages'
  Common -> C:\temp\2\Common\bin\Debug\Common.dll
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the NuGet Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  Feeds used:
    C:\Users\mkharitonov\.nuget\packages\
    https://api.nuget.org/v3/index.json

  All packages listed in C:\temp\2\UITests\packages.config are already installed.
  UITests -> C:\temp\2\UITests\bin\Debug\UITests.dll
C:\temp\2> cd .\UITests\bin\Debug\
C:\temp\2\UITests\bin\Debug> ..\..\..\packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe --noresult --inprocess --domain=Single --labels=AFTER .\UITests.dll
NUnit Console Runner 3.8.0
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.16299.0
  CLR Version: 4.0.30319.42000

Test Files
    .\UITests.dll

=> UITests.SomeTestImpl.SomeTest
SomeTest
Passed => UITests.SomeTestImpl.SomeTest

Run Settings
    ProcessModel: InProcess
    DomainUsage: Single
    DisposeRunners: True
    WorkDirectory: C:\temp\2\UITests\bin\Debug
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Passed
  Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2018-06-16 04:48:55Z
    End time: 2018-06-16 04:48:55Z
    Duration: 0.354 seconds

C:\temp\2\UITests\bin\Debug>
```

Notice `SomeTest` in the output. But where is one time setup and teardown? They are specified in the source code, but in another assembly.

The source code is attached
[test.zip](https://github.com/nunit/nunit/files/2107878/test.zip)

**Comment by CharliePoole** [comment] 2018-06-16 13:04
When NUnit is loading tests, it examines all the public Types in a particular assembly and checks to seeing any of them are fixtures. For each fixture, it will find any attributed methods, even if defined in a base class as part of a separate assembly.

But a SetUpFixture is completely independent of the tests in the initial assembly. As a result, it is never examined.

There are two approaches you could use to replace the SetUpFixture:

1. Inherit from the class in question and make your setup method a OneTimeSetUp for the class. Use a static flag to ensure it only runs once.

2. Move the SetUpFixture to the test assembly. If you like, you can keep the logic in the original assembly as a base class.

**Comment by rprouse** [comment] 2018-06-18 13:43
I am marking this as a question because it doesn't work as you expected, but it does work as designed.

**Closed** 2019-05-13 13:39 UTC
Labels: is:question
