### ISSUE TITLE
TestCaseSource skipping item

### ISSUE THREAD

**Issue by Cstolworthy** [nunit/nunit#2083] opened 2017-03-16 01:56 UTC
My coworker and I have come across an odd behavior when using TestCaseSource. I have defined a datasource with 3 items in it, however when my test executes it is only ever handed the first and third item. I have attached a project which replicates the issue.

[NunitTestProject.zip](https://github.com/nunit/nunit/files/846433/NunitTestProject.zip)

**Comment by CharliePoole** [comment] 2017-03-16 03:19
What shows up in the test result xml file?

**Comment by Cstolworthy** [comment] 2017-03-16 20:10
I downloaded the GUI runner (https://github.com/nunit/nunit-gui) and everything works just fine in it.
This seems to be an issue when using the runner in VS.  We have verified that the issue is reproducible in both VS 2015 and 2017.

Does VS produce a result xml file?

**Comment by CharliePoole** [comment] 2017-03-16 21:31
The VS adapter doesn't produce an XML file, but since the file is written out directly from what is returned by the framework, we can readily assume that a file from the console runner would produce the same thing. For that matter, the XML visible in the pre-release GUI should show the same thing.

My guess is that VS is choking on the name given to the missing test. The XML will tell us that name and allow us to experiment with variants of it.

**Comment by Cstolworthy** [comment] 2017-03-17 00:30
I believe this is the XML you are looking for.

[nunitoutput.zip](https://github.com/nunit/nunit/files/849346/nunitoutput.zip)

**Comment by CharliePoole** [comment] 2017-03-17 16:28
@Cstolworthy Is that the output from the exact code in your earlier? What seems odd is that the argument portion in the name of the test should be a quoted string, as it is for the other two tests. In addition the curly braces are not present. If it's from the same code, then I suspect that the curly braces are causing some problem in how nunit names the test.

Additionally, the XML contains the test fjixture twice. Is that just a copy/paste error or did it come from NUnit that way?

**Comment by Cstolworthy** [comment] 2017-03-17 17:41
Ah, my bad.  This is the correct XML.

[NunitOutput.zip](https://github.com/nunit/nunit/files/851354/NunitOutput.zip)

**Comment by CharliePoole** [comment] 2017-03-17 18:48
That looks better. Also, it indicates that the framework is creating the name as should do, so the problem is either in the adapter or in the VS test window itself. I am still confused about the duplication of the entire fixture, which appears twice in the XML output, with duplicate "unique" identifiers for each test. How did you create this file?

What happens if you remove the curly braces from the argument returned by the data source? I realize that may break your test, but does it show up in VS at all?

**Comment by Cstolworthy** [comment] 2017-03-17 20:54
To create the file I downloaded and extracted the GUI runner.  I then hit open and pointed it to my DLL, I then selected the dll in the tree window, hit the XML tab in the details window and copied it into the file I sent.

Some additional details we gathered:
Removing the curly braces does not affect the issue.
It seems to be tied to length somehow.  If you pre-pend enough characters it starts running the test, it replicates this behavior with any string.
If you declare a string statically to return with a GUID in it, that works fine. 

This works
`yield return "{824d7963-66b8-47f5-b196-767e397e51b7}";`

This does not:
`var guidOutput = Guid.NewGuid().ToString();
yield return guidOutput;`

Nor does this:
`yield return Guid.NewGuid().ToString()`

We also tried switching the return type from string to Object. It presents the same behavior if you return a Guid instead of returning the ToString.

There is no question that either the adapter or the test window is at fault as these all run fine in both the console and gui runner.

**Comment by evenflow58** [comment] 2017-10-25 14:56
I think the problem is Guid.NewGuid(). I ran into the same problem but was trying to just return a guid, which did not work. I did notice that parsing a guid (i.e. Guid.Parse("4dcbe9ef-86c1-4e48-ac7e-5d29e3dc62cc")) works fine

**Comment by ChrisMaddock** [comment] 2017-10-25 15:38
@evenflow58 

Try using `TestContext.Random.NextGuid()` to generate your Guid. This uses NUnit's own random functionality, which is seeded for reproducibility.

**Comment by CharliePoole** [comment] 2017-10-26 07:32
Shouldn't this either be closed or moved to the adapter project?

**Comment by mikkelbu** [comment] 2017-10-26 19:53
After some researching I found out that this is a duplicate of nunit/nunit3-vs-adapter#97, and  @CharliePoole gives a nice explanation of the problem here https://github.com/nunit/nunit-vs-adapter/issues/15#issuecomment-39654379. That being said the solution is to do as @ChrisMaddock suggests.

Ps. I tried to do the same exercise with xUnit, and the behaviour is the same in Visual Studio, so I think that the only way to solve this problem is to change the behaviour in VS. I've tried to examine the https://github.com/Microsoft/vstest repository, but I've not found any open issue mentioning the problems described in this thread. So I'll close the issue here and propose that another one is opened in vstest, please reopen if you disagree.

**Closed by mikkelbu** 2017-10-26 19:53 UTC
