### ISSUE TITLE
SetUpFixture not being triggered when running tests using --testlist

### ISSUE THREAD

**Issue by mcopjan** [nunit/nunit#3390] opened 2019-10-07 14:49 UTC
NUnitLite 3.12.0 (.NET Standard 2.0)

I have some code which is loading configuration in SetUpFixture class. I have noticed that this code is not being triggered when tests are executed using --testlist parameter.

Steps to reproduce:
1] Create a SetUpFixture which does not belong to any namespace (will be always triggered)

````
using System;
using NUnit.Framework;

[SetUpFixture]
public class SetUpFixture
{
    public SetUpFixture()
    {
        Console.WriteLine("Hello from SetUpFixture.");
    }
}
````

2]Create a simple test
````
using System;
using NUnit.Framework;

namespace TestAutomation.Dashboard.Tests.Features
{
    public class DummyTest
    {
        [Test]
        public void TestSetUpFixture()
        {
            Console.WriteLine("Hello from the Test.");
        }
    }
}
````

- Execute using where expression:

![image](https://user-images.githubusercontent.com/20699180/66321968-4ace5080-e919-11e9-8db1-d42a8777564a.png)

- Executing using --testlist
![image](https://user-images.githubusercontent.com/20699180/66321999-5d488a00-e919-11e9-97fb-f516cb3202a1.png)

As visible from the output above, when using --testlist there is no log message from the SetUpFixture.

**Comment by CharliePoole** [comment] 2019-10-07 16:34
You should review the documentation for `SetUpFixture`. All the activity in a `SetUpFixture` takes place in methods with the `[OneTimeSetUp]` and `[OneTimeTearDown]` attributes. There is no particular guarantee that the constructor will be executed if there is no reason to construct the class.

The different behavior in the two situations seems odd to me, but since it relies on execution on non-guaranteed behavior (execution of the constructor) it's not totally surprising.

**Comment by mcopjan** [comment] 2019-10-07 18:26
Thanks @CharliePoole, I will move my logic from constructor to OneTimeSetUp and report back.

**Comment by mikkelbu** [comment] 2019-10-07 18:45
I just tried to reproduce the problem, and it also exists when the logic is moved to a method decorated with `OneTimeSetUp`. My guess is that the problem is due to the prefiltering and is essentially the same as  #3356.

**Comment by mcopjan** [comment] 2019-10-09 07:37
@mikkelbu Unfortunately we cannot downgrade Nunit version (because of other external dependencies using Nunit >=3.12.0).  Will the same fix for Nunit Adapter 3.15.1 be roll out for NunitLite please?

**Comment by mikkelbu** [comment] 2019-10-20 19:16
@mcopjan The fix for the adapter was to "hide" the functionality behind a feature flag. I would rather have us solve the underlying problem. I've placed this issue in the milestone for the next release, but currently, I don't have much time to work on it.

**Comment by rprouse** [comment] 2020-12-14 02:14
Resolved by @3679

**Closed by rprouse** 2020-12-14 02:14 UTC
