### ISSUE TITLE
NUnitLite pre-filter breaks the ability to pass an assembly name as a test

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#3001] opened 2018-09-03 10:56 UTC
Prior to the implementation of the NUnitLite pre-filter capability, it was possible to pass a test of the form:
```
--test:assemblyname.dll
```
and all of the tests in that assembly would be run.

Now, that name appears to be interpreted as a namespace identifier, and then used to pre-filter all tests.

Since there are no tests in the assemblyname.dll namespace, no tests are found to run.

However, assemblyname.dll is a valid test name, and is the first name returned in the xml file when an --explore is done.

```
<test-suite type="Assembly" id="1074" name="assemblyname.dll" fullname="assemblyname.dll" runstate="Runnable" testcasecount="62">
```

**Comment by CharliePoole** [comment] 2018-09-03 13:30
I can see how it happens but I wonder how useful it is to fix. Since Nunitlite only supports one assembly, you could just leave it out. For nunit3-console it might be useful.

**Comment by oznetmaster** [comment] 2018-09-03 13:34
Generally, true.

However, my NUnitLite build does support multiple assemblies :(

**Comment by CharliePoole** [comment] 2018-09-03 14:36
Prefiltering is implemented in the framework in `DefaultTestAssemblyBuilder`. Consequently, we have already decided to run the assembly at the point where the prefilter is applied. As a result, there are two errors here, if you want to filter by assembly:

1. As you saw, no tests are found in the assembly since the filter is actually not the name of a test within the assembly. 

2. Any other assemblies are completely loaded, so the pre-filtering doesn't really function.

The same problems don't exist for normal filters because they take place after all assemblies are fully loaded and work on the complete tree of tests.

At the heart of the problem is that `--test=assembly.dll` is one of those "accidental" features. Nobody ever planned for it to work, but it apparently does and therefore you are making use of it. 😞 I think it will take a reworking of pre-filters, and perhaps filters as well to make this work.

@nunit/engine-team Somebody may want to try this out in the console. Does `--test` work with the name of an assembly? One way out of this for both nunitlite and the console might be to support a "noprefiltering" option.

**Comment by jnm2** [comment] 2018-09-05 01:59
What if the prefilter ignores `--test` lines that match assembly suites?

**Comment by CharliePoole** [comment] 2018-09-05 02:59
So we would prefilter the prefilter before applying it! 😄 

Notice that any solution has to deal with both user-supplied prefilters and prefilters generated from `--test` filters.

**Comment by jnm2** [comment] 2018-09-07 00:52
@nunit/framework-team I have a lot on my plate. Is there enough here to put this up for grabs?

**Comment by CharliePoole** [comment] 2018-09-07 01:40
@jnm2 Seems like the team has to decide if filtering on assembly name is a supported feature. We don't know how it works with the console yet AFAIK and we will want both NUnitLite and the console to work the same.

**Comment by CharliePoole** [comment] 2018-09-07 01:43
BTW, I'm unclear about how you are using the "up for grabs" designation. Does it imply that no existing team member wants to do it, so it's opened up to contributors?

**Comment by jnm2** [comment] 2018-09-07 02:50
Good call. (/cc @nunit/framework-and-engine-team then)

I think 'up for grabs' means that the work is simply unclaimed and ready for a team member or non-team-member to begin implementing.

**Comment by rprouse** [comment] 2018-09-07 21:52
I find this one to be a bit of an odd request. NUnitLite is intended to allow one test assembly to self-execute. Using it as a lightweight console is out of scope to me. I know the @oznetmaster does it for reasons unique to his needs, but those are not widespread and he maintains his own fork. I also don't see why you would want to filter assemblies on the command line. Why not just pass the assemblies that you want to run on the command line rather than pass many then filter down to the one you want?

So, even if it does work in the console, I'd say that is a bug and that this shouldn't be a supported feature. Thoughts?

**Comment by CharliePoole** [comment] 2018-09-07 22:16
@rprouse That makes sense to me. My concern with the console was actually that we should __stop__ it from working if it does, since it leads to this conflict with automatic pre-filtering. OTOH, it has never come up before so may not be worth a lot of effort.

**Comment by rprouse** [comment] 2020-05-18 19:35
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 19:35 UTC
