### ISSUE TITLE
ThrowsConstraint behavior inconsistent for async delegates 

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#813] opened 2015-09-17 12:31 UTC
ThrowsConstraint behaves differently depending on whether the exception is thrown directly by the method under test or returned as part of the resulting Task.

``` csharp
[TestFixture]
public class TestFixture
{
  [Test]
  public void TestFails()
  {
    Assert.That(() => ThrowsDirectly(), Throws.TypeOf<InvalidOperationException>());
  }

  [Test]
  public void TestSucceeds()
  {
    Assert.That(() => ThrowsAsync(), Throws.TypeOf<InvalidOperationException>());
  }

  private Task ThrowsDirectly()
  {
    throw new InvalidOperationException();
  }

  private async Task ThrowsAsync()
  {
    await Task.Yield();
    throw new InvalidOperationException();
  }
}
```

**Comment by CharliePoole** [comment] 2015-09-17 15:53
This is closely related to #464

**Comment by spirit11** [comment] 2018-01-10 08:52
ThrowsConstraint in version=3.6.1 still behaves differently for some cases:

```cs
[TestFixture]
public class Tests : AssertionHelper
{
    [Test]
    public void AsyncSuccess()
    {
        Expect(async () => await Task.FromException(new InvalidOperationException()), 
                Throws.Exception.TypeOf<InvalidOperationException>());
    }

    [Test]
    public void AsyncFail()
    {
        Expect(async () => await Task.FromException(new InvalidOperationException()), 
                Throws.Exception);
    }

    [Test]
    public void SyncSuccess()
    {
        Expect(() => { throw new InvalidOperationException(); }, 
                Throws.Exception.TypeOf<InvalidOperationException>());

        Expect(() => { throw new InvalidOperationException(); },
                 Throws.Exception);
    }
}
```

**Comment by mikkelbu** [comment] 2018-01-10 10:02
As far as I can deduct from #1899 this will be solved in version 3.9.

**Comment by jnm2** [comment] 2018-01-13 23:50
@mikkelbu is correct. #1899 was a duplicate of this issue and we published the fix with release 3.9.0 in November.

I'll close this issue as a duplicate of https://github.com/nunit/nunit/issues/1899 even though, in fairness, it should have been the other way around. 😃

**Closed by jnm2** 2018-01-13 23:50 UTC
Labels: is:enhancement, pri:normal
