### ISSUE TITLE
Default test order no longer alphabetic

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1372] opened 2016-03-24 00:56 UTC
I realize that this has never been "guaranteed", but since the addition of the TestOrder attribute (#1264), the default test execution order appears to no longer be alphabetic.

This is apparently not an issue for most people, but my GUI requires that the test execution occur in a known order, and that it be alphabetical.

Since alphabetical is apparently no longer the default, I need a way to be able to specify that the tests execute alphabetically (or perhaps a number of different ways).

Should this be a command line option? I would like to see  both "alphabetical" and "in order specified" as options, the later being the order that the tests appear on the command line.

**Comment by rprouse** [comment] 2016-03-24 02:15
With that PR, we thought we were maintaining backwards compatibility, but I guess we didn't add tests for alpha.

I don't like the idea of command line options. We provide the Order attribute if you need to order tests. I think we should ensure we maintain backwards compatibility because alpha order was the common workaround for test ordering, but in the meantime, isn't the Order attribute more explicit? Can't you add it to your tests or are there so many that it is difficult?

**Comment by oznetmaster** [comment] 2016-03-24 02:30
5K-10K tests.  Explicit ordering is not possible.

**Comment by CharliePoole** [comment] 2016-03-24 03:07
We left the existing sort in place in that change, so if the order has changed it was an unintended outcome. Personally, I would argue that test ordering has never been specified by NUnit, as I have before, but it sounds like the two of you believe that we must maintain old - even accidental - behavior. If so, I think it will be cleaner if we separate the "bug" from the requested new feature.

**Comment by oznetmaster** [comment] 2016-03-24 08:02
I am indifferent to retaining the old behavior, as long as there is a way to force the desired behavior.

But I do see @rprouse point, so maybe we should also, for now, retain the previous default behavior.

**Comment by rprouse** [comment] 2016-04-12 21:58
I am assigning this to myself to confirm for the 3.2.1 release since many people use this undocumented behaviour for test ordering.

**Comment by rprouse** [comment] 2016-04-14 21:52
@oznetmaster, I cannot reproduce this. I created a test fixture with a series of tests ordered randomly and they were run in alpha order. Maybe the ordering is only broken on CF? Can you confirm or clarify?

The output from my tests are,

```
=> nunit.v3.Issue1372.AlphaOrderingTests.A_Test  
A                                                
=> nunit.v3.Issue1372.AlphaOrderingTests.B_Test  
B                                                
=> nunit.v3.Issue1372.AlphaOrderingTests.C_Test  
C                                                
=> nunit.v3.Issue1372.AlphaOrderingTests.D_Test  
D                                                
=> nunit.v3.Issue1372.AlphaOrderingTests.E_Test  
E                                                
=> nunit.v3.Issue1372.AlphaOrderingTests.F_Test  
F                                                
```

**Comment by CharliePoole** [comment] 2016-04-14 22:05
Did you use the Order attribute on some test? It may only break in that situation, if at all.

**Comment by rprouse** [comment] 2016-04-14 22:15
I added [Order] to the last two tests to move them to the front and they work fine.

```
=> nunit.v3.Issue1372.AlphaOrderingTests.F_Test
F
=> nunit.v3.Issue1372.AlphaOrderingTests.E_Test
E
=> nunit.v3.Issue1372.AlphaOrderingTests.A_Test
A
=> nunit.v3.Issue1372.AlphaOrderingTests.B_Test
B
=> nunit.v3.Issue1372.AlphaOrderingTests.C_Test
C
=> nunit.v3.Issue1372.AlphaOrderingTests.D_Test
D
```

I have moved this out of the 3.2.1 milestone since it seems to be working as expected. @oznetmaster, if you can produce a repro, I will reconsider, but I am planning on releasing 3.2.1 this weekend, so please try to come back quickly if this is important to you.

**Comment by oznetmaster** [comment] 2016-04-15 00:55
I have provided @rprouse with a xml result file which shows that the tests are not being run alphabetically.

The are alphabetical within a single TestFixture, but not within the entire TestSuite.  This is why the test that he ran was working,

I was, for some reason, unable to attach the test results here.  I have asked @rprouse to do so.

**Comment by oznetmaster** [comment] 2016-04-15 00:56
And yes, it is important to me.

**Comment by rprouse** [comment] 2016-04-15 01:07
@oznetmaster I got the result file. So, you are saying that the previous behavior was fixtures were run in alpha order, then tests within fixtures? I have never seen that level of test ordering. I didn't even know fixtures were run in alpha order previously.

I don't think we should be adding command line options for legacy behavior, but I am okay to restore the sort original sort order if it does not conflict with the new order attribute. Do you have a proposed fix for this?

**Comment by rprouse** [comment] 2016-04-15 01:08
To be honest, I wasn't planning on putting out a 3.2.1 for CF, but if you get a PR in on time, I will consider it.

**Comment by CharliePoole** [comment] 2016-04-15 01:13
This is a whole new discussion. Although @oznetmaster was probably always meaning high-level suites as well, the rest of us were just hearing sort under test fixtures. However, NUnit's old behavior was to sort all suites that do not have MaintainTestOrder set to true. NUnit controls that setting internally and does not expose it. We use it to cause parameterized test cases to run in the order they are generated and to make sure that multiple assemblies run in the order specified.

**Comment by oznetmaster** [comment] 2016-04-15 01:20
What is also interesting is that the results of Explore are ordered correctly.  I do not understand how they can be correct, and the test execution order incorrect?

I did not follow the changes that implemented the Order attribute, so it would be difficult for me to find what it broke.  Perhaps @CharliePoole who was involved in that change might be able to fix this a lot faster?

**Comment by oznetmaster** [comment] 2016-04-15 01:28
This is probably obvious, but this is issue exists in all builds, not just the CF build.

**Comment by rprouse** [comment] 2016-04-15 01:49
Even if it does appear in all builds, I am not sure if this is a serious enough regression to hold up the release.

**Comment by oznetmaster** [comment] 2016-04-15 02:21
Well, it has broken some of the functionality of my GUI.  Do not know if it affects any other runners or GUI's?

**Comment by CharliePoole** [comment] 2016-04-15 03:15
Our gui displays tests in the order in which they are returned by explore. That should not have changed because we made an effort not to change it.

The change we made is that tests using the order attribute may execute in a different order from the way they are displayed. However, if you don't use the order attribute, it's supposed to remain the same. Also, even if some tests use the attribute, the remaining tests should execute in the same relative order as before.

Is the above description different from what you had expected/wanted to happen? Is it not what you are seeing? If so, I can take a look after I do #1406 but I'll have to timebox it.

**Comment by oznetmaster** [comment] 2016-04-15 03:28
I expect tests to be executed in the order that they are returned by explore if that order is not modified by the order attribute.

That is what use to happen.  That is not what is currently happening, as can be seen by comparing the order of the tests in the explore results to that in the test results.

**Comment by CharliePoole** [comment] 2016-04-15 04:50
As I said, I will spend some time on this but we have a release coming. You are not giving much info to work with though. Does the problem arise all the time or only on some assemblies? Does it matter what attributes I use? I didn't do the change so I have to figure it out using whatever info you give me.

If I can easily restore the prior behavior I will, but the order of execution won't match that of discovery if the Order attribute is used. That was by design.

**Comment by oznetmaster** [comment] 2016-04-15 05:36
Since I have not had a user that ever needed or wanted the Order attribute, that is not an issue to me.

The problem arises 100% of the time.  Not sure what attributes you are referring to, but the order attribute is not ever used.

I thought I had made it clear.  All I want is the original behavior before the Order attribute was added, which means that execution order (with no Order attributes) is the same as explore order.

**Comment by CharliePoole** [comment] 2016-04-15 07:16
I get that from your latest posts, but it's new to this discussion. It seems that we are now talking about more than just one "non-guaranteed" behavior that you would like to see guaranteed:

1. Tests executing in alphabetical order by default
2. Tests being returned from explore in alphabetical order by default
3. Tests executing in the same order as returned by explore

Up until your post of about six hours ago, we had only been talking about item 1.

Let's distinguish a few different "orders" of tests to make this easier to discuss:

1. Retrieval order (I just made that name up) is the order in which NUnit finds tests. NUnit has no control over that and it can vary from one platform or version to another.
2. Presentation order (also just coined) is the order in which the APIs present tests to a runner. If there is no sorting, this is the same as retrieval order, but NUnit has historically sorted most types of  suites alphabetically.
3. Display order is how the tests are displayed by a UI. If the UI makes no effort to change it, then it will probably be the same as presentation order.
4. Execution order is the order of running the tests. If no sorting of work items is done, it will be the same as the presentation order.

The goal of the changes that @dicko2  made were to keep the presentation order unchanged and modify the execution order only insofar as the OrderAttribute was used. If no order attribute is used in a fixture, execution should match the presentation order. If any methods have an OrderAttribute, those should run first, in order. The order of the remaining methods among themselves was indeterminate IIRC (but I'll check this). I'll test to see if it's actually doing what I wrote above.

**Comment by CharliePoole** [comment] 2016-04-15 16:10
@oznetmaster I have run a number of tests using both the console runner and nunitlite, which should make no difference, since all the sorting is in the framework. I can't create XML output that differs between using --explore and simply running the tests.

I also examined the code. The only code that changes execution order from that retrieved by --explore is in CompositeWorkItem's SortChildren method. Please take a look at it yourself and let me know if you think I missed anything! There are only two things I can see that would change the results in your case:

1. If you happen to have a test property named "Order" it will cause the tests to be sorted. In retrospect, I think this should be an internal property (start with underscore). @rprouse Shall I make that change for the release?

2. If you are running tests using multiple threads, obviously they may complete in a different order from that used to start them. This is expected by design.

Please do take a look yourself, as you may see something I am missing.

**Comment by CharliePoole** [comment] 2016-04-15 20:08
Regarding "Order" property... Upon review I see we have quite a lot of standard properties that affect how the test is run. They are used if they exist, no matter how they were put there. We should just document this somewhere, probably with a link from PropertyAttribute. I'll add an issue.

**Comment by oznetmaster** [comment] 2016-04-15 23:49
I have attached the -explore output and the test results from running the tests.  The order is obviously different.  This happens on 100% of the test assemblies I have.

 

No Order property.  No multiple threads.

**Comment by CharliePoole** [comment] 2016-04-16 00:42
Since the email address is merely a  gateway to posting to the forum issue, attachments do not come through. You can send them to me privately if you like.

Were your runs done on our CF build or on your private build?

**Comment by CharliePoole** [comment] 2016-04-16 01:28
@oznetmaster I got your attachments and see the issue. I can even reproduce it.

You are, however, running tests in parallel. The settings in the execution output indicate NumberOfTestWorkers=2. I see the same behavior  when I use the default (4 threads for me) and when I use --workers=1. When I use --workers=0, the order appears to be correct.

I don't yet understand why there is a difference between 0 and 1 yet - I'm looking into it. It will help if you can verify whether the same  behavior occurs for you.

**Comment by oznetmaster** [comment] 2016-04-16 01:42
I believe that NumberOfTestWorkers=2 is the default on the CF build.  I am not setting anything.  However, since none of my test are set to run in parallel, that should not make a difference?  Also, if I examine the running threads, I never see two tests running at the same time.

It is important to note that this is still a changed behavior.  Running (using this default NumberOfTestWorkers) on the CF build (which is a single processor environment), the tests ran in the same order as the -explore output prior to the Order attribute being added, and now do not.

So something has changed.

**Comment by oznetmaster** [comment] 2016-04-16 01:42
@CharliePoole I will verify that behavior when I return to my computer later today (my time).

**Comment by CharliePoole** [comment] 2016-04-16 02:05
If the behavior has changed, we need to figure out why it changed. It's possible that this has nothing to do with the ordering change we introduced. I have a few ideas I want to try.

**Comment by CharliePoole** [comment] 2016-04-16 04:34
OK, here's what's happening...

Test completion is reported (obviously) in the  order that tests finish. If there is only one  thread of execution, then that's the same as the order in which they start. With multiple threads, the order of completion is not the same as the start order. This is a natural result of executing on multiple threads and was planned for in the design of the parallel dispatcher.

In addition, with multiple queues, the actual order of starting some tests changes. Assume that execution begins with parallelizable tests. Any non-parallelizable tests that are found are placed on a different queue. Those tests do not even run until all tests in the parallelizable queues are completed. This happens even in the case where workers=1.

Further, tests that require the STA are placed on one of the STA queues, of which there is one for parallelizable tests and another for non-parallelizable tests. This also happens when workers = 1.

Completely single-threaded operation, compatible with NUnit V2 only happens in two cases:
1. When workers=0
2. When workers=1 AND all tests are either parallelizable or non-parallelizable AND either no tests or all tests are set up to run in the STA.

Without a complete redesign, it is not possible to guarantee that test results are reported in the same order that tests are returned by explore. Such a redesign would take a lot of work and would benefit only one gui that we have heard of. Unfortunately, that one is Neil's. However, by setting up the test package with NumberOfTestWorkers set to 0, I believe the desired ordering will be maintained.

I don't plan to do any more work on the issue at this time.

**Comment by oznetmaster** [comment] 2016-04-16 04:44
That does not explain the change in behavior :(

If no tests are marked as parallelizable, and no tests are set up to run in STA, then the results seemingly should be the same as the -explore results no matter how many worker threads there are?  All test should run on the same thread, in the same order, it would seem?

Are some tests now being defaulted to parallelizble that were not before?

CF does not even support STA, so that should not be an issue in the CF build anyway.

**Comment by CharliePoole** [comment] 2016-04-16 04:53
From the output, it appeared you were running the NUnit tests. They are set up to execute fixtures in parallel through an assembly-level attribute. That is, except for five classes, which are marked as non-parallelizable. There are also a number of tests that require the STA, but those would not affect a CF run.

I think the non-parallelizable fixtures are relatively new and could explain the entire difference. Their execution would not even start until all parallelizable tests were complete. Since they are all under NUnit.Framework, that would explain why that namespace suite did not complete until last.

**Comment by dicko2** [comment] 2016-05-04 03:56
I noticed this issue when writing the units test, @CharliePoole is correct. Initially i was looking at the test completion time in the unit test and they were not correct because the start and finish times where different. So i had to expose one of the properties public to inspect the order the tests were added in to pass the unit test.

**Comment by CharliePoole** [comment] 2016-05-04 06:57
So that gets us down to the question: Is there anything to do here?

**Comment by CharliePoole** [comment] 2016-05-04 07:01
As far as I can tell, it works like before if you set numworkers to zero.

We don't want to abandon queues, which is what causes the difference. Is there any way we can change our use of them to mitigate this?

**Comment by CharliePoole** [comment] 2016-05-21 15:39
@oznetmaster I haven't heard further from you for a few weeks. 

My observation is that the behavior remains unchanged in the following situations:
1. If `--workers=0` is used.
2. if `--workers-1` is used AND there are no tests requiring the STA AND all tests are either parallel or non-parallel.

In all other situations, there is some degree of simultaneity in test execution, so the order of test completion may not match the order of test starting. We display tests in the order of completion.

AFAICS there's nothing to fix here and I'd like to close the issue. What do you say?

**Comment by rprouse** [comment] 2016-06-23 13:35
@oznetmaster  We haven't made any progress on this, so I am closing. If there are changes that need to be made and we decide on how they should be made, please reopen.

**Closed by rprouse** 2016-06-23 13:35 UTC
Labels: status:confirm
