### ISSUE TITLE
nUnit Console runner and Parallel execution

### ISSUE THREAD

**Issue by sravansurabhi** [nunit/nunit#2764] opened 2018-03-16 18:01 UTC
I am using Parallelizable(ParallelScope.Self) at the TestFixture level. Each TestFixure has about 5 tests and has OneTimesetup and OneTimeTearDown methods.   

There are total of Three TestFixures in one assembly
when we Invoke tests through console command line the tests never finish and gets stuck somewhere in between.

`nunit3-console.exe /p="Browser=Chrome" /x86 /workers=3 /agents=3 /trace=Debug "FunctionalTests.dll"`

when I remove Parallelizable(ParallelScope.Self)  from all TestFixures the tests completes fine.

Here is the log.
InternalTrace: Initializing at level Debug
09:40:56.826 Debug [ 5] DefaultTestAssemblyBuilder: Loading FunctionalTests.dll in AppDomain domain-
09:40:56.839 Debug [ 5] DefaultTestAssemblyBuilder: Examining assembly for test fixtures
09:40:56.842 Debug [ 5] DefaultTestAssemblyBuilder: Found 8 classes to examine
09:40:56.892 Debug [ 5] DefaultTestAssemblyBuilder: Found 3 fixtures with 15 test cases
09:40:57.051 Info  [ 5] DefaultTestAssemblyRunner: Running tests
09:40:57.058 Info  [ 5] Dispatcher: Initializing with 3 workers
09:40:57.061 Debug [ 5] WorkShift: Parallel shift adding queue ParallelQueue
09:40:57.061 Debug [ 5] WorkShift: Parallel shift adding queue ParallelSTAQueue
09:40:57.061 Debug [ 5] WorkShift: NonParallel shift adding queue NonParallelQueue
09:40:57.061 Debug [ 5] WorkShift: NonParallelSTA shift adding queue NonParallelSTAQueue
09:40:57.062 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#1
09:40:57.062 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#2
09:40:57.062 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#3
09:40:57.062 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelSTAWorker
09:40:57.062 Debug [ 5] WorkShift: NonParallel shift assigned worker NonParallelWorker
09:40:57.062 Debug [ 5] WorkShift: NonParallelSTA shift assigned worker NonParallelSTAWorker
09:40:57.073 Debug [ 5] Dispatcher: Using NonParallel strategy for FunctionalTests.dll
09:40:57.075 Info  [ 5] WorkShift: NonParallel shift starting
09:40:57.076 Info  [ 5] TestWorker: NonParallelWorker starting on thread [9]
09:40:57.077 Info  [ 5] WorkItemQueue: NonParallelQueue.0 starting
09:40:57.078 Info  [ 9] TestWorker: NonParallelWorker executing FunctionalTests.dll
09:40:57.107 Debug [ 9] Dispatcher: Using Direct strategy for FunctionalTests
09:40:57.107 Debug [ 9] Dispatcher: Using Direct strategy for Tests
09:40:57.107 Debug [ 9] Dispatcher: Using Parallel strategy for UploadTest
09:40:57.107 Debug [ 9] Dispatcher: Using Parallel strategy for UploadTest1
09:40:57.107 Debug [ 9] Dispatcher: Using Parallel strategy for UploadTest2
09:40:57.108 Info  [ 9] WorkShift: NonParallel shift ending
09:40:57.109 Debug [ 9] WorkItemQueue: NonParallelQueue.0 pausing
09:40:57.109 Info  [ 9] WorkShift: Parallel shift starting
09:40:57.110 Info  [ 9] TestWorker: ParallelWorker#1 starting on thread [10]
09:40:57.110 Info  [ 9] TestWorker: ParallelWorker#2 starting on thread [11]
09:40:57.110 Info  [ 9] TestWorker: ParallelWorker#3 starting on thread [12]
09:40:57.111 Info  [ 9] TestWorker: ParallelSTAWorker starting on thread [13]
09:40:57.112 Info  [ 9] WorkItemQueue: ParallelQueue.0 starting
09:40:57.112 Info  [11] TestWorker: ParallelWorker#2 executing UploadTest1
09:40:57.112 Info  [12] TestWorker: ParallelWorker#3 executing UploadTest2
09:40:57.112 Info  [ 9] WorkItemQueue: ParallelSTAQueue.0 starting
09:40:57.112 Info  [10] TestWorker: ParallelWorker#1 executing UploadTest
09:41:05.920 Debug [11] Dispatcher: Using Direct strategy for UploadTest11
09:41:07.024 Debug [10] Dispatcher: Using Direct strategy for UploadTest1
09:41:07.096 Debug [12] Dispatcher: Using Direct strategy for UploadTest21
09:41:22.043 Debug [10] Dispatcher: Using Direct strategy for UploadTest2

**Comment by rprouse** [comment] 2018-03-16 18:05
Which version of NUnit are you using? Is this still an issue in the 3.10.1 release?

**Comment by rprouse** [comment] 2018-03-16 18:06
Possible duplicate of #2761

**Comment by sravansurabhi** [comment] 2018-03-16 18:08
Thank you for quick reply.
using NUnit.ConsoleRunner.3.8.0 .
Just an FYI: NUnit3TestAdapter.3.10.0 the same thing works fine.  Do we have  NUnit.ConsoleRunner.3.10.0 version?

**Comment by rprouse** [comment] 2018-03-16 18:15
I am asking about the version of NUnit framework. The parallel work queues are in the framework, not in the runner that you are using.

**Comment by sravansurabhi** [comment] 2018-03-16 18:17
NUnit 3.10.1

**Comment by rprouse** [comment] 2018-03-16 18:18
Thanks, I will leave this open for now, but it does sound like a duplicate of #2761, so you should watch that issue too.

**Comment by sravansurabhi** [comment] 2018-03-16 18:39
I will attach source code on Monday but meanwhile with VS 2017, NUnit3TestAdapter.3.10.0  the same tests works fine.

**Comment by jnm2** [comment] 2018-03-19 14:58
@sravansurabhi With the VS adapter, does it work fine when running all tests or only when debugging all tests?

**Comment by rprouse** [comment] 2019-04-28 17:00
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Closed by rprouse** 2019-04-28 17:00 UTC
Labels: confirm
