### ISSUE TITLE
Unable to use [TestCaseCourse] and [TestOf] or [Category] attribute together in NUnit Test

### ISSUE THREAD

**Issue by parwalrahul** [nunit/nunit#2999] opened 2018-09-01 06:34 UTC
Ex::
[Test]
[TestCaseSource(typeof(<Class Name>), "<Iterator Name>")]
[TestOf("Functionality")][Category("Regression")]
public void TestA(int a, int b)
{
//***********************
//I want to access TestOf / Category Value inside with logic::
var testOf = TestContext.CurrentContext.Test.Properties["TestOf"];

But it is giving me error that Sequence contain no elements.
If i remove TestCaseSource then it works.

**Comment by rprouse** [comment] 2018-09-03 19:56
This is a duplicate of #1358

**Closed by rprouse** 2018-09-03 19:56 UTC
Labels: is:bug, pri:normal
