### ISSUE TITLE
NullReferenceException in Assert.ReportFailure method

### ISSUE THREAD

**Issue by Egor92** [nunit/nunit#1992] opened 2017-01-19 07:41 UTC
I use NUnit 3.6.0. And I noticed that messages of all failed tests are "System.NullReferenceException: Object reference not set to an instance of an object" every time.

I wrote simple test:
```    [TestFixture]
    public class UnitTest1
    {
        [Test]
        public void TestMethod1()
        {
            Assert.IsTrue(false, "My fail message");
        }
    }
```
And ran it with debug. I got NullReferenceException. StackTrace:
```
   в NUnit.Framework.Assert.ReportFailure(String message)
   в NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   в NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   в NUnit.Framework.Assert.IsTrue(Boolean condition, String message, Object[] args)
```
Here are test fails using NUnit 3.5 and NUnit 3.6:
![nullrefexception](https://cloud.githubusercontent.com/assets/5503885/22097202/e80fc852-de30-11e6-9896-959e7d30d070.png)

**Comment by rprouse** [comment] 2017-01-19 12:21
Do you get the same result if you run the tests with the NUnit console?

**Comment by Egor92** [comment] 2017-01-19 13:37
NUnit console displays correct fail message
![image](https://cloud.githubusercontent.com/assets/5503885/22108707/7c34111c-de65-11e6-9acc-a3cc7c637edb.png)

**Comment by rprouse** [comment] 2017-01-19 16:46
Thanks @Egor92. It looks like a Resharper issue, but I am going to leave this issue open for now so we can investigate.

**Comment by CharliePoole** [comment] 2017-01-19 17:26
Although we have reached out in the past, the R# folks are very close-mouthed about how they use NUnit. We don't know for example, whether they use the engine api, framework api or some home-brew approach of their own. In the case of TeamCity, from the same company, the devs eventually caught on that our not knowing what they make use of is rather bad for them. Maybe that can happen here. 😄

**Comment by CharliePoole** [comment] 2017-01-19 17:34
It would be useful (for us and/or the JB guys) to know if this only occurs when the system language is russian. I doubt that's the case, but somebody should check it. @rprouse I don't have a copy of R# to check this out, do you?

**Comment by rprouse** [comment] 2017-01-19 17:39
I don't have a copy, but I do have a license. I should probably start using it as a small measure of integration testing.

**Comment by ChrisMaddock** [comment] 2017-01-19 17:52
I have resharper, and don't see this issue. What framework are you targetting, @Egor92?

**Comment by Egor92** [comment] 2017-01-19 18:33
@ChrisMaddock, .NET 4.0. I wanted to attach my test project. But I could not attach zip-archive with it.

**Comment by Egor92** [comment] 2017-01-19 20:26
I tried to run tests on other PC. AssertionException occurred. Even with .NET 4.0.

On that computer where NullReferenceException occurred there are following versions of software:
- .NET 4.0
- Visual Studio 2010
- ReSharper 7.1

Maybe it is due to very old version of ReSharper?

**Comment by ChrisMaddock** [comment] 2017-01-19 20:44
Wow - yes, I don't think NUnit 3 was supported until Resharper v10.

With the NUnit 2.6.4 engine - an exception is thrown if you try and run NUnit 3 tests. Versions of NUnit prior to that will attempt to run NUnit 3 tests purely due to the similar naming to things, but won't do so accurately - it's not a supported comination. I'm not sure which NUnit version Resharper 7.1 packages, but I wouldn't be surprised if it's pre-2.6.4.

I'd update ReSharper - or look for another method to run your tests!

**Comment by Egor92** [comment] 2017-01-19 20:54
I install NUnit 3.5.0 and it works fine (watch screenshot in issue description)

**Comment by CharliePoole** [comment] 2017-01-19 21:12
If you are using old NUnit V2 runner code to execute NUnit 3 or later tests, things may __appear__ to work... but not really. I'm pretty sure that the old version of R# is incorporating the V2 runner code.

In our old nunit-console runner, we had the same problem. In the 2.6.4 release, we added the feature that it would __refuse__ to run NUnit 3 code in order to avoid this problem.

In other words, the fact that your 3.5 tests appear to work in this environment is completely accidental - you just are not using any features that make a noticeable difference. Any V2 runner that is not aware of V3 will attempt to execute the code. If you are lucky, it will fail. Consider yourself lucky. :-)

@rprouse I'm pretty sure this is closable, but I'll leave it to you.

**Comment by rprouse** [comment] 2017-01-19 23:30
@CharliePoole yes I think we can close this. I was just worried that we had introduced a regression.

**Closed by rprouse** 2017-01-19 23:30 UTC
Labels: confirm, is:bug, pri:critical

**Comment by gabornemeth** [comment] 2017-02-24 11:09
I experience the same issue in my own [testrunner project](https://github.com/gabornemeth/NUnit.XForms): 
I came across it, when added FsUnit test support. FsUnit 3.0.0-beta1 supports .NET Standard 1.6 and this requires NUnit 3.6.0.
In a Xamarin Android or iOS project the problem appears with .NET Standard version, I suppose. If I update the NUnit NuGet package from 3.5.0 to 3.6.0 in the [iOS or Android samples](https://github.com/gabornemeth/NUnit.XForms/tree/master/Samples), it breaks.
What am I missing?

**Comment by ChrisMaddock** [comment] 2017-02-24 11:37
@gabornemeth - this issue was caused by attempting to run NUnit 3 tests in the NUnit 2 runner. That doesn't sound likely with what you're doing!

It's probably worth you creating a new issue, with more details and the error you're seeing.

**Comment by ChrisMaddock** [comment] 2017-02-24 11:37
By the way - cool project! I'd be intrigued to see how it looks compared to our nunit.xamarin runner!

**Comment by gabornemeth** [comment] 2017-02-24 11:40
Yeah, the environment is different, but the error is the same. Incompatible assemblies try to interop somewhere. I'm going to create a new issue then.
