### ISSUE TITLE
TestCaseSource: "Too many arguments provided" for IEnumerable<> parameter type

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1792] opened 2016-09-14 22:24 UTC
@debugosaurus commented on [Wed Sep 14 2016](https://github.com/nunit/docs/issues/115)

It appears that NUnit has started treating Array and Enumerable TestCaseSource parameters differently. I noticed this behaviour when upgrading from 3.0 to 3.4.1.0 (sorry that covers a lot of ground).

Say I declare some test data:

```
protected static IEnumerable<IEnumerable<string>> EnumerableOfStrings => new[] 
{ 
    new[] { "one", "two" }
};
```

The following test will pass:

```
[Test, TestCaseSource(nameof(EnumerableOfStrings))]
public void AcceptsArrayOfStrings(string[] array)
{
}
```

However this test will fail with the message **"Too many arguments provided"**:

```
[Test, TestCaseSource(nameof(EnumerableOfStrings))]
public void AcceptsEnumerableOfStrings(IEnumerable<string> enumerable)
{
}
```

It seems with the second test that NUnit is attempting to unbox the enumerable and pass each element as an argument rather than passing the enumerable as a single parameter.

---

@ChrisMaddock commented on [Wed Sep 14 2016](https://github.com/nunit/docs/issues/115#issuecomment-247175801)

I can reproduce this - agreed it seems to be a bug. (Great bug report, by the way! :+1:)

I'll also move this issue over to the NUnit framework repo - this ones just for doc issues. :smile:

**Comment by CharliePoole** [comment] 2016-09-15 16:47
Not sure I agree this is a bug - or at least not the same bug you see. It seems to me that the source has to be __either__ for a method that takes a string or for one that takes an IEnumerable<string>. Therefore, both test methods can't be good. One has to be invalid, while the other is valid. I recall that we made some changes to the code to make it work as it does. Are you suggesting that the first one should give an error of "Not enough arguments" or that both should work?

This has always been an ambiguous situation for NUnit: only one argument presented as a single array. Should we expect methods to take a string or an array of strings? Is there some way we can make this clearer? It would be interesting to see what are the minimal syntax changes to the TestCaseSource that would cause NUnit to switch over to the alternate interpretation. What happens if we specify either string[] or object[]?

**Comment by ChrisMaddock** [comment] 2016-09-15 20:13
Not sure I'm following you here Charlie, I'm afraid.

> It seems to me that the source has to be either for a method that takes a string or for one that takes an IEnumerable

There is no test method here that takes a string? Both methods take 'collections' of strings, just one as an array, the other as an ienumerable.

> This has always been an ambiguous situation for NUnit: only one argument presented as a single array. Should we expect methods to take a string or an array of strings

I understand this problem - but with the source here being an ienumerable of ienumerables, doesn't that remove the ambiguity?

**Comment by CharliePoole** [comment] 2016-09-15 20:56
@ChrisMaddock You're right - this is not the situation I imagined. It could still be useful for whomever takes this one to explore the bounds of the problem by trying alternative formulations of the source.

**Comment by ChrisMaddock** [comment] 2016-09-20 12:17
@debugosaurus - Are you working on a pull request to fix this? Would be great if so, not sure when I'd get round to it at the moment!

**Comment by debugosaurus** [comment] 2016-09-22 19:01
Yeah I've forked the repo and have tests to reproduce the issue and expand upon the problem. Progress is slow at the moment and I'm not sure there's an easy elegant fix but I'll press on when I can.

**Comment by ChrisMaddock** [comment] 2016-09-22 20:07
Great - will leave it with you!

**Comment by rprouse** [comment] 2016-09-26 18:31
@debugosaurus did you make any progress on this over the weekend? We are planning on doing the 3.5 release this week and need to know what will be included.

**Comment by debugosaurus** [comment] 2016-09-26 22:57
@rprouse nothing that doesn't undo other previous fixes

**Comment by debugosaurus** [comment] 2016-09-29 19:58
Pull request #1812 created

**Comment by rprouse** [comment] 2016-10-02 21:35
I am going to move this to 3.6. I am preparing the release.

We might even be able to use your code from #1812 soon after the release. We are thinking about splitting CF out to it's own repository, so your fixes might be fine as is.

**Comment by CharliePoole** [comment] 2016-10-31 20:00
We've recently been having some (meta-)discussions about discussing issues. This one should probably have been tossed into the discussion pipeline so we could decide exactly what we want to have work as a test case source. The old definition was that we supported any ienumerable returning a number of possible Types, indicated in the comments as follows:

```C#
        // 1. Source is null. This is really an error but if we
        //    throw an exception we simply get an invalid fixture
        //    without good info as to what caused it. Passing a
        //    single null argument will cause an error to be 
        //    reported at the test level, in most cases.

        // 2. User provided an ITestCaseData and we just use it.

        // 3. An array was passed, it may be an object[]
        //    or possibly some other kind of array, which
        //    TestCaseSource can accept.
```

The comments are not too clear about what types of array can be accepted, so the code has to be consulted. Essentiallly, if all the args are of the same type, then we accept an array of that type as the argument.

In the past, when an __outer__ array was used to provide the enumeration of cases, it was normally an array of objects because that's how .NET represents argument lists. However, since we accept any enumeration, it could also be a typed array. I don't think this ability was used much in the past but the introduction of `new[]` has probably led to its being used more frequently now.

Personally, I don't think we want to extend what the attribute will accept more than necessary. In particular, I don't think a non-array should be used to represent the argument list for a test case. We already stretched a point in accepting, for example, an int[3] array to represent three integer args. The format that uses TestCaseData to hold arguments can always express any ambiguous cases clearly.

I think it would be helpful to understand exactly what new use cases are being accepted by the PR under discussion - aside from just fixing the bug - before we merge it. @debugosaurus Is that something you could articulate? In parallel, I'm going to run your tests against the existing code.

@debugosaurus Thanks for all the work you did on this so far. If it turns out that you went too far, that's our fault for not having discussed what we wanted ahead of time. 😢

**Comment by debugosaurus** [comment] 2016-11-03 02:01
@CharliePoole Thanks for the feedback, your comments about using an outer array of object make sense and I think that's a crucial piece of the puzzle in my understanding the behaviour of test case data. 

From the feedback so far and re-evaluating my PR I'm more inclined to think that extending the use-cases may be undesirable - as it puts more burden on NUnit to guess / figure out intent at the expense of explicitness. On reflection the changes I have introduced do not align with the original use cases for outer arrays (hence the changes to UniqueItemsTests that I was unsure about) and so I think the associated PR is not the right way to go.

The original reported issue could potentially be addressed through documentation and more specialised exception messages; especially the steps required to fix a failing test are trivial in this instance (ie changing a type from an IEnumerable to an array in your TestFixutre).

**Comment by rprouse** [comment] 2017-01-03 01:23
Just a heads up. The framework release is likely going to be at the end of the week. I am moving this issue out of the milestone for the release.

**Comment by pr-yemibedu** [comment] 2017-11-22 22:59
Hello,
 This also happens for me with (**NUnit ~> 3.6.1**):
``` f#
[<TestCase ([| null ; null |], ExpectedResult=2)>]
static member ``Check Length`` (lines:seq<string>) =
    lines |> Seq.length
```
it errors stating it was trying to call the function with `(null, null)` as the argument. Can there be a property *`AsIs=true`* or [*`Splat=false`*](https://4loc.wordpress.com/2009/01/16/the-splat-operator-in-ruby/) that lets us retain control of intent. Thank you. Good day.

**Closed** 2023-04-13 11:48 UTC
Labels: is:bug, pri:high
