### ISSUE TITLE
A test that crashes the runner process is reported as successful.

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#1656] opened 2016-07-11 01:21 UTC
Test:

```
using System;
using System.Threading;
using NUnit.Framework;

namespace CrashyTest
{
    public class CrashingTestFixture
    {
        [Test]
        public void CrashTheAgentProcess()
        {
            var thread = new Thread(ThrowUnhandledException);
            thread.Start();
            thread.Join();
        }

        void ThrowUnhandledException()
        {
            throw new Exception("Execute Order 66.");
        }
    }
}
```

This test shows as passed in the Visual Studio Test Explorer pane when run.

The unhandled exception is only recorded in the Tests Output pane:

<details>

```
------ Discover test started ------
NUnit Adapter 3.4.0.0: Test discovery starting
NUnit Adapter 3.4.0.0: Test discovery complete
========== Discover test finished: 1 found (0:00:00.2289927) ==========
------ Run test started ------
NUnit Adapter 3.4.0.0: Test execution started
Running selected tests in C:\Temp\NUnitRunnerDisposalCrash\CrashyTest.cs\bin\Debug\CrashyTest.dll
NUnit3TestExecutor converted 1 of 1 NUnit test cases
System.Exception: Execute Order 66.
   at CrashyTest.CrashingTestFixture.ThrowUnhandledException() in C:\Temp\NUnitRunnerDisposalCrash\CrashyTest.cs\CrashingTestFixture.cs:line 23
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   at CrashyTest.CrashingTestFixture.ThrowUnhandledException() in C:\Temp\NUnitRunnerDisposalCrash\CrashyTest.cs\CrashingTestFixture.cs:line 23
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
NUnit Adapter 3.4.0.0: Test execution complete
========== Run test finished: 1 run (0:00:00.5845427) ==========
```

</details>

`nunit3-console.exe` also shows this as passed:

<details>

```
NUnit Console Runner 3.4.1
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10240.0
  CLR Version: 4.0.30319.42000

Test Files
    CrashyTest.dll


Unhandled Exception: System.Exception: Execute Order 66.
   at CrashyTest.CrashingTestFixture.ThrowUnhandledException() in C:\Temp\NUnitRunnerDisposalCrash\CrashyTest.cs\CrashingTestFixture.cs:line 23
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Run Settings
    WorkDirectory: C:\temp\NUnitRunnerDisposalCrash\CrashyTest.cs\bin\Debug
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.5.2
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 12

Test Run Summary
  Overall result: Passed
  Test Count: 1, Passed: 1, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-07-11 01:12:49Z
    End time: 2016-07-11 01:12:49Z
    Duration: 0.089 seconds

Results (nunit3) saved as TestResult.xml
```

</details>

When using a custom ITestRunner from `NUnit.Engine`, this test is considered failed in the XML result (below), and then calling `ITestRunner.Dispose()` throws a `SocketException` (also as below).

**Regression:** In NUnit 3.0, this crashing test did not throw an exception from `ITestRunner.Dispose()`.
<details>
XML result:

```
<command-line><![CDATA["C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.x86.exe" /parentProcessId 12784 ]]></command-line><filter><test>MyTests.TestCase.Fail</test></filter><test-suite type="Assembly" id="0" name="Test.dll" fullname="C:\Users\yaakov.smith\AppData\Local\Temp\8cc821a4-ff32-427f-b17c-7cd0a7e1b9b6\Test.dll" runstate="NotRunnable" testcasecount="1" result="Failed" label="Error" start-time="2016-07-11 01:15:35Z" end-time="2016-07-11 01:15:35Z" duration="0.001" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0"><failure><message><![CDATA[An existing connection was forcibly closed by the remote host]]></message><stack-trace><![CDATA[
Server stack trace: 
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)]]></stack-trace></failure></test-suite>
```

`SocketException`:

```
No connection could be made because the target machine actively refused it 127.0.0.1:4856


Server stack trace: 
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket(EndPoint ipEndPoint)
   at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket()
   at System.Runtime.Remoting.Channels.RemoteConnection.GetSocket()
   at System.Runtime.Remoting.Channels.SocketCache.GetSocket(String machinePortAndSid, Boolean openNew)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.SendRequestWithRetry(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Unload()
   at NUnit.Engine.Runners.ProcessRunner.UnloadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Unload()
   at NUnit.Engine.Runners.MasterTestRunner.UnloadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.MasterTestRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at Dat.Implementation.NUnit3.NUnit3TestRunner.RunTests(TestDescriptor[] tests) in C:\Workspace\DevTools\Dat\Dat.Implementation.NUnit3\NUnit3TestRunner.cs:line 49

</details>
```

**Comment by CharliePoole** [comment] 2016-07-11 04:50
Since you're reporting this against  NUnit and since the NUnit behavior is probably where the problem arises, I'm going to pass over the Test Adapter issue for the moment. I believe that fixing this in NUnit would also fix it in the adapter.

When run in-process, a test that causes a stack-overflow exception will crash NUnit. When run out of process, it will crash the agent. There's no way around that. It appears that it crashes without being able to pass the exception along to the calling process. As a result, the test fails when trying to unload the process that has already disappeared.

All of the output appears to me as correct except that the test is reported as succeeding. This shouldn't happen. The default result for a test method is Inconclusive, not success, so it shouldn't be reported as succeeding unless an event was received showing that it succeded. That's what we will have to look into here.

**Comment by yaakov-h** [comment] 2016-07-11 04:54
Yet the XML output from `ITestRunner.Run(...)` shows it very clearly as failed. :confused:

**Comment by CharliePoole** [comment] 2016-07-11 05:18
Indeed. That's what we call a bug. :-)

**Comment by yaakov-h** [comment] 2017-02-06 04:34
In NUnit 3.6, this now throws a `NUnitEngineException` rather than a `SocketException`:

```
NUnit.Engine.NUnitEngineException : No connection could be made because the target machine actively refused it 127.0.0.1:26292
Failed to stop the remote agent. No connection could be made because the target machine actively refused it 127.0.0.1:26292

at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing)
at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
at NUnit.Engine.Runners.MasterTestRunner.Dispose(Boolean disposing)
at NUnit.Engine.Runners.MasterTestRunner.Dispose()
```

Is this the expected result of disposing an `ITestRunner` for a crashed process?

**Comment by CharliePoole** [comment] 2017-02-06 04:49
We have simply wrapped the exception in our own NUnitEngineException. The issue essentially the same and has not been worked on by anyone yet.

**Comment by yaakov-h** [comment] 2017-02-06 05:39
Ok, thanks.

**Comment by OmicronPersei** [comment] 2017-12-31 01:36
Running this test using `NUnit Adapter 3.9.0.0` in VS2017, the test passes and there's no indication of the test having failed at all.  Same thing when running the build script's test suite.

**Comment by OmicronPersei** [comment] 2018-01-11 02:03
After debugging the example test method to see why it's not failing, I ended up finding this method:
https://github.com/nunit/nunit/blob/a8e36883aed269ce352328eb3e64d31ba7c7204a/src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs#L57

How is this method supposed to work?  When the method is executed, `result` is null and it would appear that this is where `ResultState.Success` is assigned.

**Comment by CharliePoole** [comment] 2018-01-11 04:31
That method is one of many `TestCommands` in the command chain that executes the test. As it happens, it's the last one, the one that actually runs your test using reflection. Since the method returns void, it has no expected result and so long as it returns (rather than throwing) it is successful.

You indicated that this method fails. Is it possibly failing in teardown? That happens at a higher point in the command chain.

**Comment by OmicronPersei** [comment] 2018-01-12 00:41
Well the method I'm testing is pretty much a copy paste of the sample code given in the OP of this issue.  I was hoping I could trace the exception to somewhere.

**Comment by CharliePoole** [comment] 2018-01-12 02:39
@OmicronPersei Sorry... I was operating on a stateless protocol: no history! 

OK, looking back I see we are talking about a deliberate exception on a new thread. The only way I know of to catch that is by writing a handler for the AppDomain. We did that in the NUnit V2 Gui, where we then reported that the exception was "possibly caused by" the currently executing test. Only possibly, because a thread could be started by one test and run for a long time before throwing the exception.

Even that limited approach won't work any longer, now that we run tests in parallel. We would need to have a complete record of which threads were created by which tests. We obviously don't have that information and as far as I know there is no way to get it without implementing a debugger inside NUnit. 

We could provide a utility method allowing tests to create "trackable threads" but that would only work for examples like this one, not for threads created by the SUT.

**Comment by jnm2** [comment] 2018-01-14 00:07
As I understand it, it is not possible to catch unhandled exceptions from any thread. AppDomain.UnhandledException only handles exceptions which some other code already 1) caught before it crashed the thread and 2) decided to report via the UnhandledException event.

The catch-all code that reports the exception might be thread pool code, and that is how the thread pool keeps its threads alive, or a message pump, and that is how the message pump keeps running. In the case of the Windows Forms message pump, it uses `Application.ThreadException` rather than `AppDomain.UnhandledException` but it's the same principle.

**Comment by CharliePoole** [comment] 2018-01-14 02:11
If an exception is handled by the message pump, thread pool, etc. then it's not an "unhandled exception" by definition. "Official" unhandled exceptions can only be caught in the primary AppDomain. Which, in this case, would be the domain in which the console runner (for inproc) or agent (all other cases) is running.

In any case, we stopped using AppDomain.Unhandled exception because it wasn't useful any longer. To be honest, it was only minimally useful in NUnit V2.

**Comment by jnm2** [comment] 2018-01-14 02:33
I know; that's the irony. It only makes sense to call it AppDomain.UnhandledException in a certain context; the exceptions were unhandled by a certain point, so the BCL handled them. Anyway, I believe the behavior is as I described. Nothing (except for attaching a debugger or hosting a modified CLR) can handle the exception and prevent you from crashing a process once you run `new Thread(() => throw ...).Start()`.

**Comment by OmicronPersei** [comment] 2018-01-15 19:17
Given the above, should we close this issue?

**Comment by CharliePoole** [comment] 2018-01-15 20:19
I'd say yes.

**Closed** 2018-01-16 02:47 UTC
Labels: hacktoberfest, help wanted, is:bug, pri:normal
