### ISSUE TITLE
NUnit Asserts no longer work in other testing frameworks

### ISSUE THREAD

**Issue by TroyWalshProf** [nunit/nunit#2336] opened 2017-07-28 17:22 UTC
I used to be able to use NUnit asserts with other testing frameworks like XUnit and VSUnit.
Now when I use an NUnit asset outside a NUnit test I get the following error:
> System.NullReferenceException: Object reference not set to an instance of an object.

Note*
This issues stated with the release of V 3.7.0

Sample code:
```
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Sample
{
    [TestClass]
    public class SampleTestClass
    {
        /// <summary>
        /// Test using NUnit asset
        /// </summary>
        [TestMethod]
        public void Sample()
        {
            NUnit.Framework.Assert.Pass();
        }
    }
}
```

**Comment by ChrisMaddock** [comment] 2017-07-29 22:00
@TroyWalshProf Can you confirm what you've been doing with this? I think it's fair to say this isn't a supported feature! 🙂

**Comment by CharliePoole** [comment] 2017-07-30 06:44
Another duplicate of #2242, which is fixed in master. The circumstances are slightly different here because of the use of a foreign test framework, but it's basically about using asserts outside of nunit.

@ChrisMaddock is right that it's not a supported feature, but we will keep it working as well as we can for simple assertions.

**Closed** 2017-07-30 06:44 UTC
