### ISSUE TITLE
StackOverflowException when using Assert.AreEqual (NUnit 3.0.1)

### ISSUE THREAD

**Issue by radimak** [nunit/nunit#1146] opened 2015-12-20 13:40 UTC
StackOverflowException occurs when Assert.AreEqual is comparing 2 object whose type implements IEnumerable and returns as some point this.

The code below prints the expected result and then crashes:
root
root.A
root.B
root.B.BB

Process is terminated due to StackOverflowException.

```csharp
using System;
using System.Collections.Generic;
using NUnit.Framework;
using System.Collections;

namespace NUnitIssue
{
    //=========================================================================
    public class Node : IEnumerable<Node>
    {
        List<Node>          _items = new List<Node>();
        readonly string     _name;
        Node                _parent;
        public string       fullname => _parent == null ? _name : _parent.fullname +  "." + _name;

        public Node(string name)
        {
            _name = name;
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public IEnumerator<Node> GetEnumerator()
        {
            yield return this;

            foreach (Node node in _items)
            {
                foreach (Node itemInner in node)
                    yield return itemInner;
            }
        }

        public void Add(Node n)
        {
            _items.Add(n);
            n._parent = this;
        }

        public override string ToString()
        {
            return fullname;
        }
    }
    //=========================================================================
    class Program
    {
        static void Main(string[] args)
        {
            var root = new Node("root");
            var n = new Node("A");
            root.Add(n);
            n = new Node("B");
            root.Add(n);
            var n1 = new Node("BB");
            n.Add(n1);

            foreach (Node node in root)
                Console.WriteLine(node.ToString());

            var x = root;
            Assert.AreEqual(root, x);
        }
    }
    //=========================================================================
}

**Comment by rprouse** [comment] 2015-12-21 15:03
Thanks for the report. This is a duplicate of #52 and is effectively the same as #1045

**Closed by rprouse** 2015-12-21 15:03 UTC
