### ISSUE TITLE
Assert.Areequal Null reference exception is thrown

### ISSUE THREAD

**Issue by suras48** [nunit/nunit#2301] opened 2017-07-05 08:32 UTC
Null reference exception is thrown whiel using Nunit 3.7.1,
when i tried with NUnit 3.6.1 issue is not seen.

Result StackTrace:	
at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
   at eMSManagerTest.eMSManagerEnglishTest.TheTC001EMSManagerTabsTest() in D:\Automation\SeleniumCSharpWebDriver\eMSManagerTest\eMSManagerEnglishTest.cs:line 99
Result Message:	
Test method eMSManagerTest.eMSManagerEnglishTest.TheTC001EMSManagerTabsTest threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by mikkelbu** [comment] 2017-07-05 10:09
Sounds like a duplicate of #2242, but it is difficult to be sure without some more context, e.g. the test.

Ps. The problem will be solved in 3.8.

**Comment by suras48** [comment] 2017-07-05 10:14
i will post a simple test here while trying this also Null exception is shown.But while downgrading NUnit from 3.7.1 to 3.6.1 issue is not observed.

[TestMethod]
        public void TestMethod1()
        {
            try
            {
                var s = "S";
                var t = "T";             
                NUnit.Framework.Assert.AreSame(s, t);
            }
            catch(AssertionException e)
            {
                throw e;
            }
        }

**Comment by mikkelbu** [comment] 2017-07-05 10:46
So you are using TestMethodAttribute from MS and Assertions from Nunit. Why not just use [TestAttribute] from Nunit?

**Comment by suras48** [comment] 2017-07-05 11:23
>>Why not just use [TestAttribute] from Nunit?
We wna tto generate the test result in specific manner which can be done with TestMethodAttribute from MS, so we have implemented all over the code and need to display all test case on Test explorer for that TestMethod is required . Actually till NUnit v3.6.1 no issues, but after updation to NUnit v3.7.1 Null exception is displaying.
Currently we can use NUnit 3.6.1 for testing purpose.
So we need to know is it a issue from NUnit ?

**Comment by CharliePoole** [comment] 2017-07-05 13:02
You must use one framework or the other. If you are using MSTest to run tests, then use their assertions. If you want to use NUnit, then use NUnit attributes exclusively. The test assembly should reference only one framework.

You can run NUnit tests in VS by installing the NUnit 3 adapter.

Your use if two frameworks appeared to be working in the past because of some combination of the features you used and because VS treats NUnit exceptions as an error. The problem you are seeing in 3.7.1 us likely to disappear in 3.8 but I suspect you have other hidden problems in this approach. Essentially, NUnit assertions rely on the environment set up by NUnit to work reliably. It had not been a design goal so far to make them work in any other environment.

**Closed** 2017-07-05 13:02 UTC
Labels: confirm

**Comment by jnm2** [comment] 2017-07-08 13:47
I don't see why NUnit and MSTest tests can't be in the same assembly. I did this with each test assembly at work as I slowly converted tests. I used the VSTest adapter, and MSTest only runs the `TestClass` tests and NUnit only runs the `TestFixture` tests and so long as you only use NUnit assertions in NUnit tests and MSTest assetions in MSTest tests, you're fine as far as I can see.

**Comment by jnm2** [comment] 2017-07-08 13:48
I'm for making that an explicit design goal because having to convert whole assemblies at a time is a barrier to adoption, plus why not be flexible especially since it already works?

**Comment by jnm2** [comment] 2017-07-08 13:52
(Side note: I'd love to see us decouple the assertion APIs from the rest of the framework, even though it's in the same DLL, and explicitly support other assertion APIs like Shoudly. Maybe v4?)

**Comment by CharliePoole** [comment] 2017-07-08 13:59
VS will let you put both kinds of tests in the same assembly. That's not the issue here. Rather it's __one__ test that uses MSTest attributes and NUnit assertions. Since it's an MSTest attribute, MSTest executes it and any ability for NUnit assertions to function is purely coincidental!

BTW, the NUnit Engine only allows one framework per assembly, picking the first one it finds. But, of course, it doesn't recognize MSTest anyway. 😄

**Comment by CharliePoole** [comment] 2017-07-08 14:00
That was a pet project of mine, which we couldn't agree on 6 months to a year ago. It's something I plan to do in a new framework - maybe - after my vacation.

**Comment by jnm2** [comment] 2017-07-08 14:01
How's the vacation going? 😃

**Comment by CharliePoole** [comment] 2017-07-08 14:04
Leaving for the airport in an hour.

**Comment by WonderGuy** [comment] 2017-07-27 14:14
I'm encountering the same NullReferenceException on simple Asserts. 
Example:
Dim Message As String = "Message"
Assert.That(Message, [Is].Not.Empty)

These Asserts should succeed.

I'm using only NCrunch and Nunit.

Ed Swartz

**Comment by rprouse** [comment] 2017-07-27 19:15
Even if we removed the restriction of requiring a test context to be setup which wouldn't be too hard, what about things like `Assert.Pass()` or `Assert.Warn()`? The first throws an exception that would cause an MSTest to fail and the second wouldn't be able to warn in a non-nunit runner.
