### ISSUE TITLE
Nunit 3.10 somehow recognizes a [TestFixture] as a [SetUpFixture] and fails with an error.

### ISSUE THREAD

**Issue by VinitSankhe1981** [nunit/nunit#3966] opened 2021-10-21 08:42 UTC
Below is my simplest TestFixture

My project: Net461
NUNIT Version: NUnit 3.10
Test Runner: Visual Studio 2019 Test Explorer.

ApplicationEvents is a plain vanilla CSharp class.

```
 [TestFixture]
  public class ApplicationEventsFixture
  {
    [OneTimeSetUp]
    public void SetUp() { }

    [Test]
    public void LoginComplete_Is_True_AfterLogin()
    {
      var appEvents = new ApplicationEvents();
      Assert.IsFalse(appEvents.LoginComplete);
      appEvents.OnAfterLogin();
      Assert.IsTrue(appEvents.LoginComplete);
    }

    [Test]
    public void EmptyEventHandler_Dont_Throw()
    {
      Assert.DoesNotThrow(() => new ApplicationEvents().OnAfterLogin());
      Assert.DoesNotThrow(() => new ApplicationEvents().OnBeginQuit());
      Assert.DoesNotThrow(() => new ApplicationEvents().OnBeginForceShutDown());
    }
  }
```
NUNIT3.10 fails to run it (Test Explorer of VS2019) and throws below error... why does it assume the fixture as [SetUpFixture]???

> LoginComplete_Is_True_AfterLogin
>    Source: ApplicationEventsFixture.cs line 13
>    Duration: < 1 ms
> 
>   Message: 
>     OneTimeSetUp: SetUpAttribute attribute not allowed in a SetUpFixture
>  
> EmptyEventHandler_Dont_Throw
>    Source: ApplicationEventsFixture.cs line 22
>    Duration: < 1 ms
> 
>   Message: 
>     OneTimeSetUp: SetUpAttribute attribute not allowed in a SetUpFixture

**Comment by iamgithb** [comment] 2021-10-21 08:52
`[OneTimeSetUp]
    public void SetUp() { }
`
I think you want to define or init inherent [SetUp]

**Comment by mikkelbu** [comment] 2021-10-21 17:41
This sounds very similar to #3178 and the problem is not in the presented code. Do you have a class that is decorated with a `SetUpFixtureAttribute` which contain a method that is decorated with either `SetUpAttribute` or `TearDownAttribute` (note that this can also be via inheritance).

**Comment by stevenaw** [comment] 2023-04-10 23:57
I've tried to repro using the latest NUnit (3.13.3) using the following definition of `ApplicationEvents` and can't. I'm going to close this as can't repro, but please let us know if you are still facing this and [mikkelbu's suggestion](https://github.com/nunit/nunit/issues/3966#issuecomment-948857309) doesn't work.

```csharp
private class ApplicationEvents
{
    public bool LoginComplete { get; internal set; }

    internal void OnAfterLogin()
    {
        LoginComplete = true;
    }

    internal void OnBeginForceShutDown() { }
    internal void OnBeginQuit() { }
}
```

**Closed by stevenaw** 2023-04-10 23:57 UTC
Labels: is:question
