### ISSUE TITLE
Incomplete info when NUnit runner throws BadImageFormatException with "Could not load file or assembly 'nunit.framework' ...."

### ISSUE THREAD

**Issue by abelbraaksma** [nunit/nunit#2811] opened 2018-04-16 11:07 UTC
Quite often I run into issues related to versions of NUnit and/or other assembly loading issues. To investigate such issues, it is important to have some vital information to even start investigating.

Currently, the error is this (probably forwarded from .NET):

> System.BadImageFormatException : Could not load file or assembly 'nunit.framework' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.

Since both .NET and NUnit use terminology of "runtime", it is unclear whether this error is about the runner of NUnit or of .NET. Also, it is unclear whether there's a dependency failure, or whether the main executable or DLL containing the tests has the wrong version.

I propose that NUnit expands on this error by showing:

* The version of the NUnit loader, engine and runner assemblies (in case one of them is out of sync)
* The version of NUnit or other NUnit libraries (like NUnit engine) used from the loaded project
* Whether the error is because of .NET 4.x version .NET 4.y
* Whether the error is because of bitness (64 bit vs 32 bit)
* What the host is (that is, whether it runs in a console executable, or from TeamCity or another host, probably the `GetEntryAssembly` would return this info)

I heard somewhere that in NUnit 3 the runner and engine are decoupled from the NUnit framework and that those versions do not need to be in line anymore. However, since I am receiving this error, this doesn't account for _all_ situations (which is understandable), but even the more reason to improve on this error.

**Comment by mikkelbu** [comment] 2018-04-16 12:38
@abelbraaksma You are right that the error message is coming directly from .NET. Can you also provide some stacktraces? (just so we can examine whether it is possible to return some more information. I fear that we cannot do much to improve this, unless we do some of the same checking as the .NET loader)

**Comment by CharliePoole** [comment] 2018-04-16 14:48
Let's try to simplify the problem a bit. 

What you state about decoupling is true. The issue is, with one exception, completely due to the nunit framework if it's the nunit framework assembly that is listed in the message. That's because the framework has no other references.

The exception to bear in mind is if you have used console options to force NUnit to run the framework in a particular way. In that case, the console  and engine could obviously impact the ability to load the framework. For example, if you specified --framework:net-2.0 for a test assembly that targets .Net 4.6 you would see the same message.

Of course, you wouldn't do that, but other options can have the same effect in a more subtle way. Examples are --process --inprocess --x86.

This is most likely not the cause of your problem, but it's useful to know that nunit generally tries to do what you tell it to do without analyzing to see if it can work. We assume you know what you're asking for. It was an early design decision to do it this way, albeit one we could conceivably revisit.

Some runners other than the console may be forcing the same behavior that the console runner allows you to control. For example, the VS adapter forces the tests to run inprocess, because VS is responsible for setting up the current process correctly. That's one reason why we often ask users to replicate a problem under the console runner where there is more control.

RE the specific info you are asking about...

* As stated the engine version is generally unimportant but is available in the result XML. The loader is .NET itself and the code that invokes it is in the framework.

* I think you mean the framework version referenced by the tests versus the one that is actually found. If so, that makes sense. FYI this often occurs when multiple assemblies target different runtime or nunit versions and are built to the same output directory.

* Specifying the exact mismatch seems less useful once you know that a mismatch occurred. Failure to load is caused by a very big difference in format, like 2.0 versus 4.x.

* Separately identifying bigness problems makes sense only if it's easy. I suspect .Net will give a different error in that case.

* Frankly, since you ran the program, shouldn't you know what the host is?

**Comment by CharliePoole** [comment] 2018-04-16 16:05
@abelbraaksma I see I missed one comment of yours in my reply...

NUnit and .NET mean exactly the same thing by "runtime" - the specific common runtime version being targeted by you and by the nunit framework build you reference. The framework builds we release and against which you compile your tests target a specific runtime. It's up to you to ensure that the specific framework against which you built is available to the test assembly when it is executing.

Most people simply rely on VS to make that framework available by copying it to the output directory. But in more complicated situations you may have to manually copy it or at least set up a directory structure that prevents it from being overwritten once copied. VS philosophy is a bit like NUnit's in this: it merely does what you tell it to do. 😄

**Comment by abelbraaksma** [comment] 2018-04-16 17:04
@CharliePoole, thanks for the extensive information, it helps a lot in understanding the NUnit infrastructure. I found the issue and you were right, the configuration defaulted to .NET 2.0 (which apparently is the default if you create a new NUnit task runner in TeamCity and I missed it).

If indeed this error means either bitness or .NET version being wrong, I think a good improvement would be to mention that in the error message. Currently, it looks like the default .NET error message, which isn't very helpful, even more so because it can be confusing whether the error is thrown by NUnit's loader, or by .NET itself (it may be clear to you, but not for a developer when faced with this error).

One way would be to wrap in an NUnit exception, which could give the extra info. I think a simple text suffices, something like "Test assembly XYZ could not be loaded, either because it, or one of its dependencies, have the wrong bitness, or are compiled for the another .NET version. Expected: .NET Framework 2.x, 64 bit".

The last bit would help a long way: it would show what the anticipated .NET version and bitness is, which is key (and if it is set to auto-detect, the error could say so too).

**Comment by rprouse** [comment] 2020-05-18 19:15
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 19:15 UTC
