### ISSUE TITLE
ANSI characters in Console Output

### ISSUE THREAD

**Issue by null511** [nunit/nunit#1787] opened 2016-09-07 17:40 UTC
I'm trying to push ANSI color characters through the test output and into the console for highlighting key-items in my test output. I'm able to do this successfully outside of NUnit (writing directly to `Console.Out`), but it looks like the colors are being overwritten by the appender. I was wondering if you guys had any insight as to why this might not be working? I've been digging through the code, but haven't identified anything yet.
- Worth noting, the ansi codes I am pushing are being intercepted (not printed to console).

Before you try to stop me:
- I know ANSI has limited terminal support, but we are running in bash and displaying final results in custom reporting tool that is capable of parsing these characters.
- We are using NUnit for integration tests (using Selenium) which have lengthy output describing each step taken, so separating output into smaller unit-tests is not an option.

**Comment by null511** [comment] 2016-09-07 18:09
**more info:** It appears that the characters are being intercepted, and converted back to a unicode representation. For example, if I input `\x1b[1;34mHello World`, the console will print `\u001b[1;34mHello World`, instead of a *blue* `Hello World`.

**Comment by CharliePoole** [comment] 2016-09-07 18:51
What version of NUnit are you using?

**Comment by null511** [comment] 2016-09-07 18:55
3.4.1

**Comment by null511** [comment] 2016-09-07 19:04
Sorry for the jumbled addition of information.

- Writing to `TestContext.Out` will print the escaped unicode characters. `\x1b[1;34m` -> `\u001b[1;34m`.
- Writing to `TestContext.Error` & `TestContext.Progress` does **not** shown the escaped characters, but it appears the colors are overridden by the Appended.
- Writing to `Console` directly **without NUnit** displays the message colorized properly.

**Comment by CharliePoole** [comment] 2016-09-07 19:12
At first I thought this might be a duplicate of #1575, which is fixed in master. However, that has to do with escaping the user message provided as a part of an Assert call.

If you use `Console.Write` **in an NUnit test** I would expect it to perform the same as `TestContext.Out`. `And Console.Erorr.Write` should work like `TestContext.Error`.

One minor thing to be aware of is that nunit3-console colors the error output itself, by setting the console foreground color. The result will probably depend on who gets there last.

We'll have to look a bit deeper to see where your escaping is removed. For now we will keep this issue in the nunit repository, because I suspect the framework is the culprit.

**Comment by CharliePoole** [comment] 2016-09-07 19:14
This is clearly happening. I marked 'confirm' in the sense of confirming it happens in the framework.

**Comment by null511** [comment] 2016-09-07 19:25
Thank you for your attention to this, I know printing colored output has been requested several times before. While I don't think what I'm trying to achieve is the best way to do so, it should be an easy alternative for most people without modifying NUnit.

I'm still looking further into the issue myself. I suspect that there is an encoding conversion occurring somewhere, but I have no leads yet.

**Comment by CharliePoole** [comment] 2016-09-07 20:45
Odd behavior. I ran a test under nunitlite, to eliminate nunit3-console from the picture. When I run a release build, `Console.WriteLine("\1b[1;34mHelloWorld")` disappears. When I run under debug, the line appears with a special symbol (box with dot) replacing the escape.

**Comment by null511** [comment] 2016-09-07 21:16
May just be a bad copy/paste, but your example does not include the proper escape character. `\1b` should be `\x1b`. I've been looking through NUnit framework & nunit-console all day, no luck yet. I suspected a UTF-8 conversion somewhere, but have found nothing.

**Comment by CharliePoole** [comment] 2016-09-07 22:04
OK, it  just took a little thought to see the obvious problem. The output is being captured and sent as an event. In the case of immediate output (Error, Progress) it's a test-output event. In the other cases, it's in the output element of the test-case result event. Both of these are encoded as XML, so the result is escaped.

Different behaviours, however. The immediate output simply never arrives to the console. The non-immediate output is escaped when it arrives. At first glance, the escaping seems unnecessary, since it's all embedded in a CDATA element.

In any case, it's clear that the console is displaying what it gets from the framework, so this issue is in the right place and available for whomever wants to take it on. In keeping with my notes above, different solutions may be needed for immediate and non-immediate output.

**Comment by CharliePoole** [comment] 2016-09-07 22:06
BTW, there are now Explicit tests of this in nunit-console.tests: ConsoleOutputTests. They could be duplicated somewhere in the framework tests as well.

**Comment by CharliePoole** [comment] 2016-09-07 22:07
@null511 Yes, I eventually caught and fixed that error.

**Comment by null511** [comment] 2016-09-08 00:23
[~/src/NUnitFramework/framework/Constraints/MsgUtils.cs](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Constraints/MsgUtils.cs#L314) `EscapeControlChars(string s)` was my first suspicion, but I was unable to identify it's path in the code, nor could I hit it with a breakpoint. Is this code executed from the framework, or by nunit3-console?

I was also not expecting it to be serialized as xml before it reached the console. Is there a particular reason for this? As you've mentioned, character escaping is unnecessary when your within a `CDATA` tag, unless your data contains a cdata end-tag `]]>`. [W3C](https://www.w3.org/TR/REC-xml/#sec-cdata-sect)

I'll try to get a pull-request put together.

**Comment by null511** [comment] 2016-09-08 00:52
I image the characters are escaped because XML is typically UTF-8, which would cause the two-byte UTF-16 characters to be decoded improperly. it would be ideal not to escape the characters before it's rendered to the console, if the logic can be pushed closer to the xml serialization?

**Comment by rprouse** [comment] 2016-09-08 02:05
> I was also not expecting it to be serialized as xml before it reached the console. Is there a particular reason for this?

All events and data that are passed from running tests to the engine (and thus the console) is sent as XML. This allows the engine to not have any dependencies on any of the classes in `nunit.framework` allowing the engine to run tests that depend on any version of the framework. It allows us to break the coupling between the framework and the engine.

**Comment by CharliePoole** [comment] 2016-09-08 03:38
Here's where the double-escaping of CDATA elements takes place:
https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Interfaces/TNode.cs#L188

Because TNode is a general-purpose class used to do all the framework's XML serialization, we have to take care that there are no side effects.

**Comment by null511** [comment] 2016-09-08 15:31
I see two routes for solving this:

- Use UTF-16 encoding for the transport layer, then convert to UTF-8 before writing to file. This will double the memory usage for transferring the XML though.

- Keep UTF-8 as-is, and unescape the unicode characters before printing to console.

I'm going to look into the latter option, as it should have much less impact.

**Comment by CharliePoole** [comment] 2016-09-08 15:39
Why can't we just remove the inner escaping? If we can resolve this in the framework, it's fixed for all runners. If we resolve in the console runner, it will remain unfixed for all other runners.

**Comment by null511** [comment] 2016-09-08 15:50
I tried simply removing the escaping logic, but it broke something else further down the line (Activator). I honestly didn't debug into this any further.

I was able to get this working be unescaping the unicode characters in `NUnit.ConsoleRunner.ExtendedTextWrapper`. It's a short `Regex.Replace(...)` addition, similar to the escape done in `TNode`. My only concern with this approach is that it will unescape unicode characters even if (for some reason) the user wants to display the escaped sequence. Using UTF-16 internally would give the users more control over the output.

**Comment by null511** [comment] 2016-09-08 16:00
https://github.com/nunit/nunit-console/pull/54

**Comment by CharliePoole** [comment] 2016-09-08 16:01
Did you have a specific place you were thinking of where we are calling out UTF-8 for our transport? If not, I can step through it.

**Comment by null511** [comment] 2016-09-08 16:06
`XmlWriter` should encode to UTF-16 by default, since it uses the encoding of the `TextWriter` it wraps (which is UTF-16 by default). The XML declaration **should** be printed with `encoding="utf-16"`. I suspect that since you are using fragments, this declaration is not written, causing the XML deserializer to decode using UTF-8 (default).

**Comment by CharliePoole** [comment] 2016-09-08 16:15
That's consistent with what I've seen so far: everything looks good all the way through the framework!

I'll debug a bit with the escaping removed from the CDATA element though.

**Comment by null511** [comment] 2016-09-10 23:41
I've done a bit more research on this issue, and discovered I had some misunderstandings of character encodings. But after much testing, I believe I have a firm solution.

- Do not use UTF-16. While XML supports most unicode characters, it unfortunately does **not** support _control characters_, even when using UTF-16. 
- Keep escaping of special unicode ranges (control chars). This makes the existing [EscapeInvalidXmlCharacters(string str)](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Interfaces/TNode.cs#L322) method essential.
- Unescape before printing to console.
- Escape back-slashes. If existing backslashes are escaped (doubled), then these escaped unicode sequences can be easily unescaped while preserving the original document. I've tested this with various unicode characters and colors successfully.

      | Output  | Escaped   | Unescaped | Printed
------|---------|-----------|-----------|---------
 char | `\x1b`  | `\\x1b`   | `\x1b`    | `*`
 text | `\\x1b` | `\\\\x1b` | `\\x1b`   | `\x1b`

To display unicode characters, the console's standrad-output encoding needs to be set to `UTF-8`. The default encoding is `SBCSCodePageEncoding` (IBM437 on WIN). I've added an additional '--encoding' option to `ConsoleOptions` for setting this value.

[MSDN](https://msdn.microsoft.com/en-us/library/system.console.outputencoding(v=vs.110).aspx)
> Of the Unicode encodings, the Console class supports UTF-8 encoding with the UTF8Encoding class and, starting with the .NET Framework 4.5, it supports UTF-16 encoding with the UnicodeEncoding class. UTF-32 encoding with the UTF32Encoding class is not supported. Attempting to set the output encoding to UTF-32 throws an IOException.


I have two pull request pending your review, [nunit #1789](https://github.com/nunit/nunit/pull/1789) & [nunit-console #54](https://github.com/nunit/nunit-console/pull/54). I've been able to successfully colorize the output using control characters, and I am also able to display unicode symbols.

**Comment by null511** [comment] 2016-09-19 13:59
Sorry for the delay, I haven't had time to work on this recently. I plan on getting some tests put around this soon.

I have some concerns about escaping the backslashes though. In the two PR's above, backslashes will be escaped before writing to XML, and then unescaped before being printed to the console. If this XML is saved, I believe the backslashes will still be escaped, which may cause issues for users (would certainly be a breaking change).

However, to properly decode all unicode characters from the saved XML output, this backslash escaping is necessary. So I'm thinking that maybe backslash escaping should be an option? Would like to hear your thoughts on this issue...

**Comment by OsirisTerje** [comment] 2024-01-08 06:13
Based on the commens in #1789 , I'll close this issue.  Please ping back if this is in error.

**Closed by OsirisTerje** 2024-01-08 06:13 UTC
Labels: is:bug, pri:low
