### ISSUE TITLE
Retrieving a random sample of data from TestCaseSource in NUnit 3.0 attribute doesn't work?

### ISSUE THREAD

**Issue by nadvolod** [nunit/nunit#1852] opened 2016-10-19 15:42 UTC
I'm having a strange issue utilizing this combination of technologies: 

 - Nunit(3.4.1.0)
 - NUnit 3 Visual Studio Test Adapter
 - TestCaseSource attribute

My test uses the attribute like this:

            [Test, TestCaseSource(nameof(GetSmallSampleSizeOfTestDataForScratchwork))]
        public void TestMe(string accessionNumber, string loginId)
        {
            var studentAssessmentPage = OpenAdminResetPageAndGoToBookletLocation(accessionNumber, loginId);
            studentAssessmentPage.OpenScratchworkTool();
            Assert.IsTrue(studentAssessmentPage.IsScratchworkToolOpen(), "The scratchwork tool did not open succesfully.");
        }

The implementation of GetSmallSampleSizeOfTestDataForScratchwork() doesn't run any tests whenever I try to execute the test. Even though in debug mode it works as expected.

    protected static IEnumerable<string[]> GetSmallSampleSizeOfTestDataForScratchwork()
        {
            var filePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            filePath = Path.GetFullPath(filePath + @"\TestData\TestData.csv");

            using (var sr = new StreamReader(filePath))
            {
                var reader = new CsvReader(sr);
                IEnumerable<CsvRecord> records = reader.GetRecords<CsvRecord>().OrderBy(x => Guid.NewGuid());

                foreach (var record in records.Take(10))
                {
                    string column1 = record.AccessionNumber;
                    string column2 = record.LoginId;
                    yield return new[] { column1, column2 };
                }
            }
        }

However, this implementation works just fine and runs all of the tests without a problem.

            protected static IEnumerable<string[]> GetAllTestDataForScratchwork()
        {
            var filePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            filePath = Path.GetFullPath(filePath + @"\TestData\TestData.csv");

            using (var sr = new StreamReader(filePath))
            {
                var reader = new CsvReader(sr);
                IEnumerable<CsvRecord> records = reader.GetRecords<CsvRecord>();

                foreach (var record in records)
                {
                    string column1 = record.AccessionNumber;
                    string column2 = record.LoginId;
                    yield return new[] { column1, column2 };
                }
            }
        }

The only difference between these 2 methods are that 1 returns a random subset of data and the other returns all of the data. 

**Therefore, why is it that GetAllTestDataForScratchwork() works just fine when I execute the tests and GetSmallSampleSizeOfTestDataForScratchwork() doesn't run a single test?**

**Comment by CharliePoole** [comment] 2016-10-19 16:33
This is a well-known issue with the Visual Studio adapter. I'm moving it to that repo where the info will be helpful to others and will comment further there.

**Comment by CharliePoole** [comment] 2016-10-19 16:34
Issue moved to [nunit/nunit3-vs-adapter #240](https://github.com/nunit/nunit3-vs-adapter/issues/240) via [**ZenHub**](https://www.zenhub.com/)

**Closed by CharliePoole** 2016-10-19 16:34 UTC

**Comment by rprouse** [comment] 2016-10-19 17:00
@nadvolod, This is a problem with the Visual Studio adapter, it will run fine if you run it using the NUnit Console.

At a high level, the problem is that Visual Studio calls the NUnit adapter to give it a list of tests to display in the test window. You randomly return values, so a random set of tests is given to Visual Studio. When you go to run your tests, Visual Studio asks NUnit to run your random test. NUnit spins up, creates your tests, but in doing so, you give it different random values and therefore different tests are created. NUnit then cannot find the test that Visual Studio is asking it to run because it is randomly different.

We fixed this for our Random attributes in nunit/nunit3-vs-adapter#97, but that doesn't help in your situation. I am going to move this issue to the adapter project to see if we can come up with a more generic solution to issues like this.

If you could generate your test data randomly using the NUnit's `Randomizer`, then I expect it would work because the Adapter will save the random seed between runs.
