### ISSUE TITLE
Named parameters in test names not formatted

### ISSUE THREAD

**Issue by hamjo** [nunit/nunit#3685] opened 2020-12-03 03:03 UTC
When using the pattern {M} as DefaultTestNamePattern in runsettings, the test name does not contain the parameters formatted as named parameters.

Steps to reproduce here : https://github.com/hamjo/github-issues/tree/master/nunit/named-parameter-name

**Comment by mikkelbu** [comment] 2021-04-20 22:52
I was a bit confused by the {M} part as the description and example contains {p}.

I just tried out the example repo and got the same results as described in the repo. Then I noticed that the repo project targets NUnit 3.12 and the Named parameters feature - #3389 - was first introduced in 3.13. So I updated both references to NUnit to 3.13 and then got the following results
![image](https://user-images.githubusercontent.com/1007631/115473305-c9f55200-a23b-11eb-8c0c-a8a344ba890a.png)

**Comment by mikkelbu** [comment] 2021-05-05 07:03
Closing this as answered - as it seem like that the problem is solved by updating to NUnit 3.13.

**Closed by mikkelbu** 2021-05-05 07:03 UTC
Labels: confirm
