### ISSUE TITLE
NetCore3: Support for ApartmentAttribute

### ISSUE THREAD

**Issue by pavelovcharov** [nunit/nunit#3130] opened 2018-12-28 09:22 UTC
As announced .Net Core 3 Preview 1 now supports WPF applications. Currently I'm trying to port my application to .Net Core 3. When I run unit tests, I get an error:

`The calling thread must be STA, because many UI components require this.`

As far as I know ApartmentAtrribute is not supported for .Net Core apps. Will it be supported for .Net Core 3?

**Comment by mikkelbu** [comment] 2018-12-28 16:19
Hi @pavelovcharov 
We have a PR that will enable `ApartmentAtrribute` on .NET Core, but it is awaiting the last review (and hopefully will be in the next version of NUnit).

I'm closing this as a duplicate of #3035, but comments on this issue will still be visible to the project.

**Closed by mikkelbu** 2018-12-28 16:19 UTC
