### ISSUE TITLE
 TestContext.CurrentContext.Test.Properties.Get("Category") always returns First category as default

### ISSUE THREAD

**Issue by thangavel** [nunit/nunit#1416] opened 2016-04-15 16:20 UTC
Considering the below sample, 

@First @second @Third
Scenario: test run
Given I am in the home page
When I login
Then I should logged into the app

Example: nunit3-console test.dll -where "cat==@third" 

Nunit 3.0: 
Nunit 3.2:
TestContext.CurrentContext.Test.Properties.Get("Category") ==> This code always returning "First". Why? It should return the selected category from the console right?

**Comment by CharliePoole** [comment] 2016-04-15 16:43
Your title is correct. It's how our PropertyBag is designed. If you use Properties["Category"] you will get a list of properties.

Clearly, based on your example, you are using some sort of third-party runner that recognizes a format quite different from that which NUnit interprets. However, when using native NUnit, a test with three categories would certainly be executed using the command-line you give.

I'm closing this issue as not a bug, but we can re-open it if you have more info about why it should be considered a problem.

**Closed by CharliePoole** 2016-04-15 16:43 UTC
