### ISSUE TITLE
Release version 4.2

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#4752] opened 2024-07-10 11:54 UTC
We have 28 closed issues, and 2 open issues.  

The open issues are:

- [x] #3981 
- [x] #4577
- [x] #4730    
- [x] #4738    PR in progress

It would be awesome if we could manage to close these during the summer, and get a 4.2 out.

**Comment by stevenaw** [comment] 2024-07-14 18:09
There's also a few filtering or selection bugs introduced in 4.x which may prove blockers for some to upgrade to NUnit 4. These aren't formally in the milestone at the moment, but we may want to keep these on our radar too

- [ ] https://github.com/nunit/nunit/issues/4651
- [ ] https://github.com/nunit/nunit/issues/4589
- [ ] https://github.com/nunit/nunit/issues/4584

The first two of these are similar enough that they may have a common root cause

**Comment by OsirisTerje** [comment] 2024-07-14 18:24
Agree, we should try to do those too, for 4.2

**Comment by maettu-this** [comment] 2024-07-21 08:30
Please note the inconsistency among [merged docs PR 932](https://github.com/nunit/docs/pull/932) and [pending framework PR 4709](https://github.com/nunit/nunit/pull/4709) as [previoulsy mentioned on Jun 18](https://github.com/nunit/docs/pull/932#issuecomment-2166525828), [asking for support on May 13](https://github.com/nunit/nunit/pull/4709#issuecomment-2106752277) and [again on Jun 18](https://github.com/nunit/docs/pull/932#issuecomment-2176766331). In case version 4.2 decides to go without the `ProgressTraceListener`, the docs changes should be reverted. Also note [some considerations](https://github.com/nunit/nunit/pull/4709#issuecomment-2111694347).

**Comment by OsirisTerje** [comment] 2024-08-19 19:58
@stevenaw @manfred-brands @mikkelbu @SeanKilleen 

It seems we are pretty close now.  Are there anything else you want to have included ?
Or can I start doing the release process of 4.2 ?

**Comment by stevenaw** [comment] 2024-08-20 00:03
Nothing from me, thanks @OsirisTerje

**Comment by stevenaw** [comment] 2024-08-20 00:04
I think the ProgressWriter PR is pretty close to merging, just an issue with an unused using I think. Unsure if you wanted to wait on your end or not

**Comment by manfred-brands** [comment] 2024-08-20 00:14
Nothing from me either. Thanks @OsirisTerje

**Comment by manfred-brands** [comment] 2024-08-20 02:27
> I think the ProgressWriter PR is pretty close to merging, just an issue with an unused using I think. Unsure if you wanted to wait on your end or not

I pushed a commit to remove the unnecessary using and @stevenaw merged the PR.

**Closed** 2024-08-29 10:47 UTC
Labels: ReleasePlan
