### ISSUE TITLE
Public facing PropertyBags need to be read only

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2665] opened 2018-01-18 02:34 UTC
As discussed in #1958 , there are multiple `PropertyBag`s (such as `TestContext.Test.Properties`) that are available to the public facing API that are incorrectly mutable.  This has the implication of being a breaking change for end users, so it warrants some discussion among @nunit/framework-team and anyone else potentially affected by this change.

**Comment by CharliePoole** [comment] 2018-01-18 05:53
This appears to me to be a duplicate of #1578. 

While the question warrants some discussion, I don't think it needs a log. It's an error and the breaking change will be a failure to compile. That's a good thing since changing the property bag doesn't currently have any effect. For example, if you set the MaxTime property, you don't suddenly get MaxTime behavior because that was all decided before the test ever ran. IOW, it's a bug to fix.

**Comment by jnm2** [comment] 2018-01-18 13:09
> This appears to me to be a duplicate of #1578.

Quite. Thanks for finding that one. (@OmicronPersei onPersei thanks for getting the ball rolling on this, too.)

**Closed by jnm2** 2018-01-18 13:09 UTC
Labels: awaiting:discussion, design, is:bug, pri:high
