### ISSUE TITLE
NullReferenceException thrown if CollectionAssert.AreEquivalent fails on arrays of unnamed ValueTuples

### ISSUE THREAD

**Issue by anyname2** [nunit/nunit#2660] opened 2018-01-15 18:55 UTC
Try to compare two arrays of ValueTuple, one of which is not (fully) named using the following code:

```cs
var expected = new[] { ("A", 1) };
var actual = new[] { (Key: "B", Value: 2) };
CollectionAssert.AreEqual(expected, actual);
```

**It throws:** System.NullReferenceException : Object reference not set to an instance of an object.
**It should throw:** NUnit.Framework.AssertionException

Here is the StackTrace:

```cs
at NUnit.Framework.Constraints.MsgUtils.GetValueFromValueTuple(Type type, String propertyName, Object obj)
   at NUnit.Framework.Constraints.MsgUtils.FormatTuple(Object value, Boolean printParentheses, Func`4 getValue)
   at NUnit.Framework.Constraints.MsgUtils.<>c__DisplayClass14_12.<.cctor>b__26(Object val)
   at NUnit.Framework.Internal.TestExecutionContext.<>c.<.ctor>b__9_0(Object val)
   at NUnit.Framework.Constraints.MsgUtils.FormatValue(Object val)
   at NUnit.Framework.Constraints.CollectionEquivalentConstraint.get_Description()
   at NUnit.Framework.Internal.TextMessageWriter.WriteExpectedLine(ConstraintResult result)
   at NUnit.Framework.Internal.TextMessageWriter.DisplayDifferences(ConstraintResult result)
   at NUnit.Framework.Constraints.CollectionEquivalentConstraintResult.WriteMessageTo(MessageWriter writer)
   at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.CollectionAssert.AreEquivalent(IEnumerable expected, IEnumerable actual)
```

- The issue affects v3.8.0, v3.8.1, v3.9.0 (at the time of writing). [earlier versions are not affected]
- At least one item in one of the collections must be unnamed.

**Comment by anyname2** [comment] 2018-01-16 10:36
Checked #2520 - it fixes the issue

**Comment by mikkelbu** [comment] 2018-01-16 11:07
@anyname2 Ok. I'll close this as a duplicate of #2518 and then I'll try to get #2520 merged to master ASAP.

**Closed by mikkelbu** 2018-01-16 11:07 UTC
Labels: confirm
