### ISSUE TITLE
Cannot load configuration file

### ISSUE THREAD

**Issue by JornWildt** [nunit/nunit#1893] opened 2016-11-08 13:05 UTC
I am trying to get nunit3-console.exe to load a specific configuration file as described here: https://github.com/nunit/docs/wiki/Configuration-Files. The idea is to use on single config file for many assemblies through the use of a .nunit project file.

I have "ServerTests.nunit" and "ServerTests.nunit.config" and the console runner is started as:

    nunit3-console.exe ServerTests.nunit

or

    nunit3-console.exe /process:Separate /domain:Single ServerTests.nunit

But apparently it is not loading the ServerTests.nunit.config file in any way. What could be wrong?

**Comment by JornWildt** [comment] 2016-11-08 13:14
I am trying to use configFile="ServerTests.config" in the .nunit project file too - without any success.

**Comment by rprouse** [comment] 2016-11-08 13:29
I have assigned a confirm label on this for the team to look at. The feature is not used much and we don't have integration tests for this, so it may have become broken.

**Comment by CharliePoole** [comment] 2016-11-08 16:56
IIRC, we no longer use the default "project.nunit.config" in NUnit 3, which would make the doc page we copied from NUnit V2 incorrect at this point. This needs to be confirmed.

The nunit-project-loader extension does return a package with the configuration file set from what is in the project but we need to check to see whether the framework honors what is passed.

If we find that the framework is honoring what is passed to it, then this issue should be moved to either nunit-console or to the nunit-project-loader extension.

**Comment by CharliePoole** [comment] 2016-11-08 17:11
One possibility here would be to allow an override of the config file on the command-line - although we should honor what's in the nunit project file if not overridden.

@JornWildt has also asked about this on SO, where he mentions the nunit adapter as well. Of course, the adapter can't load nunit project files but only loads what VS tells it to load. We could add a setting to the `.runsettings` file to specify the config file.

**Comment by JornWildt** [comment] 2016-11-09 08:38
> One possibility here would be to allow an override of the config file on the command-line

That would certainly work too. What ever works, I'll take it :-) It is rather troublesome to maintain one test X.config for each assembly X - when it could all be put into one single shared config file.

And, yes, the nunit adapter is an issue too and I do see that it can be difficult here. If only the new GUI runner could use .nunit project files like the old one then I would be happy - running from inside VS 2015 is not as got an experience as the the old GUI runner provided.

**Comment by JornWildt** [comment] 2016-11-09 08:40
> We could add a setting to the .runsettings file to specify the config file.

That would help, but unfortunately we do have solutions that contain many different test projects that would need different .runsettings files (or, rather, different .config files).

**Comment by CharliePoole** [comment] 2016-11-09 08:54
@JornWildt Bear in mind that there is as yet no production release of an NUnit 3 GUI at all! Whatever features it had or doesn't have, if we the developers are telling you it's not ready for production use, I think it makes sense to pay attention!

WRT the adapter, we are limited by the VS architecture, which has no provision for separate setting files other than the nunit per-assembly default. However, your initial question was about how to have a single configuration for all assemblies and an entry in the run settings file would give you that.

**Comment by JornWildt** [comment] 2016-11-09 09:00
> Bear in mind that there is as yet no production release of an NUnit 3 GUI at all!

I know :-) I did compile it myself from GitHub to see how it worked.

So the conclusion is that NUnit 3 has no way of supporting shared config files as it is today, right? The GUI-runner is not ready and neither the console runner nor the nunit adapter supports it. That is unfortunate but not a show stopper. We *really* need NUnit 3 for testing async code :-)

**Comment by JornWildt** [comment] 2016-11-09 09:24
I'll see if some creative app.config copying in the build process solves it.

**Comment by rprouse** [comment] 2016-12-01 20:48
@JornWildt did you solve your problem? Can we close this issue?

**Comment by JornWildt** [comment] 2016-12-01 21:20
I worked around the issue by copying the config files as part of the build process. It would still be nice to have a, per project/assembly, setting that defines which config file to load.

**Comment by rprouse** [comment] 2016-12-01 21:24
Thanks @JornWildt. Based on that, I am making this an idea for discussion.

@nunit/contributors do you think we should promote this from an idea to the backlog or close as is?

**Comment by CharliePoole** [comment] 2016-12-01 21:32
I'm confused as to what the issue actually is after reading through this. It seemed to start out with wanting a __common__ config file and then evolved into a separate config per assembly.

As it now stands, you can specify a common config file either in an NUnit project file or on the console runner command-line (I think). If you want each assembly to have a separate config, then you have to use the naming convention and not specify a common config.

**Comment by JornWildt** [comment] 2016-12-01 22:07
> It seemed to start out with wanting a common config file and then evolved into a separate config per assembly.

No - it evolved into a setting per assembly that points to the common config file :-)

> As it now stands, you can specify a common config file either in an NUnit project file or on the console runner command-line (I think).

But I could not get a common config file to work with the console runner (see my initial comments) - have you fixed that? And it would still be a problem to use a common config file from inside Visual Studio as there currently is no way to specify the config file here (except by naming convention which does not allow assemblies to share config files).

**Comment by ChrisMaddock** [comment] 2016-12-02 10:35
Seems like there's a possible bug to be investigated with the engine/project-loader-extension, as to why the config file isn't being picked up. I had a quick look, and there seems to be code with the intention of doing that. From @CharliePoole's comments, it sounds like we also need to clarify the documentation about what we support. @JornWildt, would be great if you would be able to dig in to it and see what's going on!

If there's also a feature request to add this functionality to the vs adapter, I guess that should be a separate issue. @JornWildt - if you're still interested in this part, can you create an issue over at https://github.com/nunit/nunit3-vs-adapter? 😄 

@rprouse - I've been closing/reclassifying some of the issues you've flagged as I look at them - please feel free to undo anything you disagree with!

**Comment by ChrisMaddock** [comment] 2016-12-02 10:54
@JornWildt - Just had another thought. There was a mistake in the documentation at the time you first tried this, the attribute for the project file should be `configfile`, rather than `configFile`. Would that work?

https://github.com/nunit/docs/issues/80

@nunit/core-team - The mix of camelCase and lowercase in the project file attribute names is a bit of a trip-wire. To keep backwards compatibiltiy, can we make them all case-insensitive?

**Comment by ChrisMaddock** [comment] 2016-12-02 11:19
Ok, I'm confusing myself at this point, so here's a list of distinct issues, as I see it! 😄 

1. NUnit project files _should_ allow setting a `configfile`. This may work, and the issue may just have been caused by incorrect docs already resolved as https://github.com/nunit/docs/issues/80

2. The [docs](https://github.com/nunit/docs/wiki/Configuration-Files) currently state that `MyProject.nunit.config` will be picked up automatically when running `MyProject.nunit` - @CharliePoole thinks that may not be the case. We should look in to that and decide if we want to support it. 

3. We should consider making project file consts case-insensitive. It's not ideal, but imo would be an improvement on the mix of casing we have at the moment.

4. There's possibly a separate feature-request for specifying a config file for the VS adapter, which can be a separate issue. 😄

Have I missed anything?

**Comment by CharliePoole** [comment] 2016-12-02 13:28
@ChrisMaddock There's no backward compatibility issue around casing of tag names. The tags have been the same since they were first created. There was a typo in the docs, which were recently created, but it's only coincidental that it was a casing error - it could easily have been a misspelling, in which case we wouldn't be talking about changing the XML format to match.

**Comment by ChrisMaddock** [comment] 2016-12-02 13:48
@CharliePoole - sure, that's not what I was suggesting at all. :-)

I'm suggesting that we **should** standardise the casing going forwards. And rather than just make everything lowercase, would could make it case insensitive, _so that_ we keep backwards compatibility.

**Comment by CharliePoole** [comment] 2016-12-02 14:54
@ChrisMaddock Sure. But there are a lot of other things we have wanted to change about this format, but didn't change because of backward-compatibility. That's why we continued to use the V2 nunit project format in NUnit 3, in the expectation that it would eventually be replaced. When we do a new format, with capabilities like nested projects and per-assembly config files, we'll be about 10 or 15 years smarter than we were when the first format was designed, so we ought to do a better job. :smile: 

Given that the same project format is used by V2 and V3 and that the project editor is shared by both versions, this could get a bit complicated.

**Comment by CharliePoole** [comment] 2016-12-02 15:04
@ChrisMaddock On your four points...

1. NUnit project files do support setting a common config file. There is no indication this stopped working at any point. Certainly our tests of it continue to pass.

2. We don't want to support that naming. It was talked about as being overly confusing during the V2 era and we decided to drop it in NUnit 3. This is simply a case where the old docs were copied and never changed.

3. As I explained on the issue you created, I don't think this is a good idea.

4. Yes, that would be a separate request.

**Comment by CharliePoole** [comment] 2016-12-02 15:10
@JornWildt So let's go back to your original request...

1. You tried to use a config file called "ServerTests.nunit.config" to match your nunit project. That's no longer supported, in spite of what the docs say.

2. You indicate you tried to specify the config file in the NUnit project file. That didn't work for you. It's supposed to work, which is why this issue is marked confirm. Can you provide a sample of an NUnit file that failed to use the config you specified so we can try to reproduce the problem?

3. As you explained, our side trip into individual configs for each assembly was merely a workaround for the original problem, so let's set that aside for purposes of this issue and try to resolve item 2.

**Comment by CharliePoole** [comment] 2016-12-02 15:24
Correction: There is no configfile command-line option. I guess it was discussed but never added. So the only current way to set a non-standard config file name is through an nunit project.

**Comment by JornWildt** [comment] 2016-12-05 19:04
> Correction: There is no configfile command-line option. I guess it was discussed but never added. So the only current way to set a non-standard config file name is through an nunit project.

Okay. I'll try to see if I can get it to work with a nunit project file and the console runner.

But ... in the end it does not help much if it is not supported from the VS adapter/runner as I would end up having to maintain (make copies of) the identical config files anyway to be able to develop and test from VS. And if I have to maintain multiple identical files anyway then I won't need the nunit project file setting as it will not add anything extra.

**Comment by CharliePoole** [comment] 2016-12-05 19:20
@JornWildt Actually, it matters a great deal for us to know why it isn't working. The only thing the adapter can do is to tell the engine to use a particular config. If the engine doesn't pay attention, then it's not going to work for __any__ runner at all!

You filed this issue against "nunit", which is the framework. The framework doesn't set up any AppDomains, but just runs in the one that it's loaded into by the engine. I'm moving this to the "nunit-console" project because (1) that's where the engine is and (2) you originally complained about the console runner. I'll add more comments there.

**Comment by JornWildt** [comment] 2016-12-05 19:23
Sure :-)

**Comment by CharliePoole** [comment] 2016-12-05 19:24
Issue moved to [nunit/nunit-console #143](https://github.com/nunit/nunit-console/issues/143) via [**ZenHub**](https://www.zenhub.com/)

**Closed by CharliePoole** 2016-12-05 19:24 UTC
Labels: confirm, is:bug, pri:normal
