### ISSUE TITLE
Nunit Console Runner 3.4.1 timeout not working

### ISSUE THREAD

**Issue by StephenMurphy13131** [nunit/nunit#1753] opened 2016-08-17 16:09 UTC
So I am trying to use the timeout feature of the NUnit Console Runner version 3.4.1. I set the timeout to 120000 milliseconds and for one of my tests this timeout is reached and it fails the test. However for another one of my tests the timeout does not kill the test. I am using NUnit 3 with Team City Enterprise 9.1.6 and launching the NUnit tests using the NUnit 3 built-in launcher. Is there some reason why the timeout is only working once for me?

**Comment by CharliePoole** [comment] 2016-08-17 16:17
Can you confirm this problem using the console runner directly?

**Comment by StephenMurphy13131** [comment] 2016-08-17 16:58
I can't use the console runner directly with the test projects needed due to permission constraints. However, I have seen the exact tests passing with NUnit 2.6. We are trying to migrate to NUnit 3 now and we are getting some hanging issues.

**Comment by rprouse** [comment] 2016-08-17 17:05
Do the tests that are not timing out have any other threading related attributes or properties set on them? Are they directly or indirectly creating child threads?

Can you post the attributes on one of these tests so we can get some more information? We don't need the body of the test yet unless it is fairly simple and you are comfortable posting it.

**Comment by StephenMurphy13131** [comment] 2016-08-18 08:03
After some investigating this morning, it seems the issue is that the Console Runner is running tests marked as Explicit. Is there some reason why this is happening? With the same configuration on Console Runner 2.6 this was not happening

**Comment by rprouse** [comment] 2016-08-18 13:57
The console runner should not be running your Explicit tests unless they are specified on the command line. Are you using the `--where` command line? Your test selection might be including your Explicit tests.

**Comment by StephenMurphy13131** [comment] 2016-08-18 13:58
I tried it using the --where command and also the built-in exclude part of the Team City step builder. Both times I excluded two categories, LongRunning and Night tests, and each time the result was the same. That being that the explicit tests were ran.

**Comment by rprouse** [comment] 2016-08-18 14:07
I expect that your --where command is incorrect, can you copy it here so we can take a look?

**Comment by StephenMurphy13131** [comment] 2016-08-18 14:14
There were two ways that I wrote this command: 
1. --where=cat!=longrunning&&cat!=night
2. --where=!(cat==longrunning||cat==night)

**Comment by CharliePoole** [comment] 2016-08-18 14:23
The problem with explicit tests may be the same as #1502. However, I don't see how that relates to Timeout.

**Comment by StephenMurphy13131** [comment] 2016-08-18 14:26
You're right, apologies I should have deleted this issue and created a new one as timeouts was not the issue, I only thought it was as the timeout was not working due to an explicit test being run which was actually hanging the build.

I will try updating the test libraries and let you guys know if it solves the problem

**Comment by rprouse** [comment] 2016-10-25 02:42
Closing this as a duplicate of #1502

**Closed by rprouse** 2016-10-25 02:42 UTC
