### ISSUE TITLE
TestCase doesn't convert array of IConvertible values to array of target type values

### ISSUE THREAD

**Issue by Denis535** [nunit/nunit#3380] opened 2019-09-28 12:58 UTC
NUnit can convert `IConvertible` value to value of target type.

        [TestCase( 777 )]
        public void Test(long value) {
        }
        [TestCase( "2000-01-01 12:30" )]
        public void Test(DateTime value) {
        }

But NUnit can not convert array of `IConvertible` values to array of target type values.

        [TestCase( new[] { 0, 1, 2 } )]
        public void Test(long[] values) {
        }
        [TestCase( arg: new[] { "2000-01-01 12:30:00" } )]
        public void Test(DateTime[] values) {
        }

**Comment by stevenaw** [comment] 2023-02-20 00:48
I think this is a duplicate of #858

**Closed by stevenaw** 2023-02-20 00:48 UTC
