### ISSUE TITLE
NUnitLite nunit3 format differs from regular NUnit's

### ISSUE THREAD

**Issue by cincuranet** [nunit/nunit#1721] opened 2016-08-05 09:57 UTC
Looking at the https://youtrack.jetbrains.com/issue/TW-46195 it looks like the `nunit3` format differs between NUnitLite and regular NUnit. Is that expected? I'm facing same behavior as described in bug report.

**Comment by CharliePoole** [comment] 2016-08-05 10:32
Please attach info about how the format differs. Also please clarify how you ate running tests. The teamcity issue refers to both the dotnet runner and nunitlite, which are not the same thing.

**Comment by CharliePoole** [comment] 2016-08-05 10:35
In fact, there is no nunitlite format. The XML is created by the nunit framework. The runner only creates the top level test-run element.

**Comment by cincuranet** [comment] 2016-08-05 10:47
Attached are the two files for comparison. I know the format should be the same. But the small difference, probably, confuses TeamCity enough. Not sure what's the problem, yet.

[NUnit.xml.txt](https://github.com/nunit/nunit/files/403602/NUnit.xml.txt)
[NUnitLite.xml.txt](https://github.com/nunit/nunit/files/403601/NUnitLite.xml.txt)

**Comment by cincuranet** [comment] 2016-08-05 11:02
OK, with these two files TeamCity can't process any of these. Although it's saying ` Successfully parsed`.

![img](https://cloud.githubusercontent.com/assets/4540597/17434776/bb01be80-5b0c-11e6-93de-473022eef1ef.png)

So I suppose it's something with TeamCity, I can't control much.

**Comment by rprouse** [comment] 2016-08-05 11:05
Does TeamCity support the NUnit 3 XML format, or does it just work with the NUnit 2 format?

**Comment by cincuranet** [comment] 2016-08-05 11:18
It does. At least some other builds working fine.

**Comment by CharliePoole** [comment] 2016-08-05 16:40
The format of the two files are the same. They are both in nunit 3 format.

Of course, some of the content is different. For example, the test-run element for nunitlite has a fullname attribute, while that from nunit does not. That's because nunitlite is designed to run only one assembly at a time, while a test run for nunit may include multiple files. Also, the ids from nunitlite have different values from those for nunit. But none of this is stuff you should be depending on.

You should probably get some comment from JetBrains folks on this problem. Only they know what may be bothering them about the format. My understanding, btw, was the same as @rprouse 's - that teamcity can only handle the nunit2 formatted output file.

@NikolayPianikov could you add anything to this?

**Comment by CharliePoole** [comment] 2016-08-08 20:32
@cincuranet I'm closing this as not a bug, since there is no material difference between the two files you posted. If you have further info, we can always reopen it.

**Closed by CharliePoole** 2016-08-08 20:32 UTC
Labels: confirm

**Comment by cincuranet** [comment] 2016-08-08 20:41
Absolutely.
