### ISSUE TITLE
TimeoutAttribute and TimeoutCommand

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#2134] opened 2017-04-25 01:15 UTC
When a timeout elapses, the TimeoutCommand correctly aborts the thread and records the result of "Test exceeded Timeout value of {0}ms".

However, when the SimpleWorkItem subsequently catches the ThreadAbortException, it then appears to overwrite that result with a "Test Cancelled by User" result.

This is on a platform which does not support Thread.ResetAbort ().  However, from the code:

```
		protected override void PerformWork ()
			{
			try
				{
				Result = MakeTestCommand ().Execute (Context);
				}
			catch (Exception ex)
				{
				// Currently, if there are no command wrappers, test 
				// actions, setup or teardown, we have to catch any
				// exception from the test here. In addition, since
				// users may create their own command wrappers, etc.
				// we have to protect against unhandled exceptions.

#if !PORTABLE && !NETSTANDARD1_6 && !SSHARP
				if (ex is ThreadAbortException)
					Thread.ResetAbort ();
#endif

				Context.CurrentResult.RecordException (ex);
				}
			finally
				{
				WorkItemComplete ();
				}
			}
```

that seemingly does not make any difference, since the ThreadAbortException is always recorded, overwriting the prior result.

It may be that the platform makes a difference in the order in which things happen.  If the Thread.Abort in the TimeoutCommand were to cause the exception before the TimeoutCommand set the new result, then it would overwrite the "Test Cancelled by User" result.  However, that cannot be assumed, which is what seems to be the case here.

**Comment by oznetmaster** [comment] 2017-04-25 01:18
To clarify further, I am seeing the TimeoutCommand.AfterTest occur before the ThreadAbortException occurs.

**Comment by oznetmaster** [comment] 2017-04-25 01:20
This comment in the code:
					// No join here, since the thread doesn't really terminate
after the Thread.Abort puzzles me, since it seems that, in fact, there should be a Join there, at least on platforms which do not support Thread.ResetAbort ()?

**Comment by oznetmaster** [comment] 2017-04-25 01:31
I added the Join, and it returned seemingly immediately after the abort.

However, AfterTest is still being called before the ThreadAbortException is thrown.

**Comment by oznetmaster** [comment] 2017-04-25 01:33
I finally realized that the Before/After are running on a different thread then the one which was aborted.

The current order makes perfect sense.  Therefore, it is unclear to me how this could ever work as expected :(

I must be missing something.

**Comment by oznetmaster** [comment] 2017-04-25 01:47
Ok, so the real problem is that on platforms that do not support Thread.ResetAbort (), the ThreadAbortException bubbles up through all exception handlers.

This means that the same ThreadAbortException is caught in both BeoforeAndAfterTestCommand and SimpleWorkItem.

This causes all sorts of problems upstream, including the actual result being wiped out.

How to handle platforms without Thread.ResetAbort () needs to be further clarified.

**Comment by oznetmaster** [comment] 2017-04-25 01:54
I may have found the cause of the problem.  More to come...

**Comment by CharliePoole** [comment] 2017-04-25 02:16
Looks like you worked this out. I can confirm that we are completely dependent on Thread.ResetAbort for Timeout support. In the platforms that do not have it, we are not supporting Timeout.

After resetting the abort, we use flags to determine whether a user cancellation is in process or if it's a simple timeout.

Right now the only supported platform where we can't do Timeout is NetStandard 1.6. We'll get it when 2.0 is ready.

**Comment by oznetmaster** [comment] 2017-04-25 02:40
In Reflect.Invoke, there is the code:
```
				catch (System.Threading.ThreadAbortException)
					{
					// No need to wrap or rethrow ThreadAbortException
					return null;
					}
```

which seems to make no sense, since ThreadAbortException is always automatically rethrown at the end of the catch block.

```
ThreadAbortException is a special exception that can be caught, but it will automatically be raised again at the end of the catch block.
```

The return null does not to seem to be able to ever actually  happen?

**Comment by oznetmaster** [comment] 2017-04-25 03:54
I am sure you are aware that on platforms without Thread.ResetAbort(), Timout can be fully supported (with one exception) by overriding the Execute method in the TimeoutCommand as follows (and doing nothing else):

```
		public override TestResult Execute (TestExecutionContext context)
			{
			Guard.OperationValid (BeforeTest != null, "BeforeTest was not set by the derived class constructor");
			Guard.OperationValid (AfterTest != null, "AfterTest was not set by the derived class constructor");

			if (Test.Fixture == null)
				Test.Fixture = context.TestObject;

			var thread = new Thread (state =>
				{
				try
					{
					BeforeTest (context);

					context.CurrentResult = innerCommand.Execute (context);
					}
				catch (Exception ex)
					{
					context.CurrentResult.RecordException (ex);
					}
				finally
					{
					if (context.ExecutionStatus != TestExecutionStatus.AbortRequested)
						AfterTest (context);
					}
				});

			thread.Start ();
			thread.Join ();

			return context.CurrentResult;
			}
```

This passes all the tests except for TestWithTimeoutRunsOnSameThread, which is expected.

**Comment by oznetmaster** [comment] 2017-04-25 04:08
Interestingly, this does fix issue #352 : TearDownTimesOutAndNoFurtherTearDownIsRun.

This will correctly timeout an infinite loop in a TearDown.

**Comment by CharliePoole** [comment] 2017-04-25 04:16
@oznetmaster Regarding the bad code in Reflect - either a PR or an actual issue would be most helpful.

**Comment by CharliePoole** [comment] 2017-04-25 04:19
@oznetmaster Re issue #352... that surprises me since he issue was filed during the time that we were creating a separate thread. I verified that it was not possible (at least on some platforms) to abort a thread that was executing in a finally block after an exception.

However, the shape of the actual code may have been changed since that time.

**Comment by CharliePoole** [comment] 2017-04-25 04:23
@oznetmaster It was a design goal for a long time to get rid of the extra threads, which complicate the future implementation of dependencies between WorkItems. We are now mostly rid of them - the exception being situations where the user actually asks for a thread to be created. I would not want to regress in this area.

There is a pattern which would allow platforms without Thread.ResetAbort to do Timeout without an extra thread. It involves cancelling the actual worker thread and immediately creating a new one. I had that in place for a while until I realized that we didn't have to actually cancel the thread on any of our platforms.

**Comment by oznetmaster** [comment] 2017-04-25 04:42
Do you have that pattern somewhere?

**Comment by CharliePoole** [comment] 2017-04-25 06:05
Going to bed...I'll look tomorrow.

**Comment by jnm2** [comment] 2018-01-16 02:39
Did we fix this one? Maybe I'm remembering wrong.

**Comment by CharliePoole** [comment] 2018-01-16 05:05
I didn't do any work on it.

**Comment by rprouse** [comment] 2020-05-18 19:10
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 19:10 UTC
