### ISSUE TITLE
Define TestCaseSource equivalent that does not give an error when there is no data

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/nunit#1856] opened 2016-10-21 18:32 UTC
Hi all,

Thank you for a fantastic product that keeps our codebase in shape.

I am in the process of trying to confirm whether the "issue" I'm seeing is:
- A misunderstanding of NUnit on my part (expectation is wrong)
- A difference in the way test runners treat this scenario 
- An issue with how NUnit services results in this issue.
## Background
- I have a `TestCaseSource` that houses the concept of a temporary exemption (when testing some security rules). 
- When an item is in the temporary exemption list, certain rules / tests apply. 
- Occasionally, the temporary exemptions lists are empty, leading to what I describe below.
## Reproduction steps
- Create a `TestCaseSource` similar to the following (the `ControllerMethodPair` class is mine; substitute any POCO): 

``` csharp
public static readonly List<ControllerMethodPair> TemporaryExemptionsList = new List<ControllerMethodPair> {
                // This list is empty. To add a temporary exemption, use the syntax:
                // new ControllerMethodPair(typeof(ControllerName), nameof(ControllerName.MethodName))
            };
```
- Write a test that uses the list as a source, e.g. below:

``` csharp
        [TestCaseSource(typeof(ControllerActionPermissions_TestCaseSources), nameof(ControllerActionPermissions_TestCaseSources.TemporaryExemptionsList))]
        public void TemporaryExemptionListItemsShouldNotHaveAPermanentExemption(ControllerMethodPair pairToTest)
        {
            SecurityTestHelper.HasPermanentExemption(pairToTest).Should().BeFalse("The controller {0}.{1} is in the temporary list but also has a permanent exemption. Please ensure only one of these is the case", pairToTest.Controller.Name, pairToTest.MethodName);
        }
```
- Run the tests when the temporary exemptions list is empty.
## Expected Result

The tests run and are ignored by my test runner, or given an "inconclusive" label of some kind.
## Actual Result

I see -- at least in ReSharper's test runner -- that the tests fail. See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/2148318/19607904/f222d8f2-979a-11e6-85cd-e429228ab8fc.png)

This makes sense in a way, but I saw it more as a warning and less as a failure.

Is this something I'm missing as to how NUnit works? Or a potential issue with the test runner itself?

I'll look at this in the console runner as well but wanted to put it out there in the meantime.

Thanks!

**Comment by rprouse** [comment] 2016-10-21 19:25
Let us know how the console runner handles the test. We have no visibility into how Resharper runs NUnit tests.

**Comment by CharliePoole** [comment] 2016-10-21 23:55
This is how the framework works and should work the same for any runner. When no test case provider (i.e. attribute) returns any test cases, NUnit tries to create a simple non-parameterized test and fails to do so because the method has parameters and none are provided. This creates an error as opposed to a failure, although the R# runner may not make a distinction. An error generally indicates a mistake in the test itself that you need to fix.

Normally, this situation __is__ an error on the part of the programmer, so the message makes sense. In your case, you are adding and removing temporary exemptions and would have to do something like comment out the TestCaseSource attribute when the list is empty.

To get around this, I suggest putting one do-nothing test case in the list. Use a special ControllerMethodPair that you create. It could have null values or be a derived type, whatever you like. You only need to be able to write an expression that detects it. Start your test with:

```C#
   Assume.That(pairToTest, <is not my do-nothing pair>);
```

You'll always have at least one test case that way and that extra test case will always be Inconclusive.

In the longer run, it may be interesting to provide for some kind of optional source test, which would do what you want. I'm marking this as an idea and re-titling accordingly.

**Comment by CharliePoole** [comment] 2016-10-25 04:18
I think the idea of an optional set of tests is a valid one although I'm not sure that the approach suggested is the right way to go. The issue is only 3 days old and I put it into the discussion pipeline and classified it as an idea so we could talk it over.

I agree that too many "ideas" have sat for too long but I hope we will make some effort to deal with them regularly after this pass through.

**Comment by rprouse** [comment] 2016-10-25 12:48
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.

**Comment by rprouse** [comment] 2016-10-25 12:49
Sorry, I am reopening this. As @CharliePoole says, the idea needs some fleshing out though before we will implement.

**Comment by rprouse** [comment] 2020-05-18 18:37
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 18:37 UTC
Labels: is:idea

**Comment by SeanKilleen** [comment] 2020-05-18 18:39
@rprouse this is a blast from the past! As the original submitter, I agree it should not be necessary. Thanks!
