### ISSUE TITLE
Inherited tests not using derived class in full name

### ISSUE THREAD

**Issue by hamjo** [nunit/nunit#3684] opened 2020-12-03 03:02 UTC
I have an issue with test names that is similar to #3671 

When using the pattern {M} as DefaultTestNamePattern in runsettings, the test name does not contain the name of the derived class being run for inherited tests.

Reproduction steps here : https://github.com/hamjo/github-issues/tree/master/nunit/inherited-test-name

**Comment by stevenaw** [comment] 2024-12-15 15:31
Closing this as I believe it to be a duplicate of https://github.com/nunit/nunit/issues/4446

**Closed by stevenaw** 2024-12-15 15:31 UTC
Labels: closed:duplicate
