### ISSUE TITLE
WorkItemQueue (get_IsEmpty) Not Working

### ISSUE THREAD

**Issue by Cododromo** [nunit/nunit#2419] opened 2017-09-06 13:07 UTC
Hi,

Please see stack trace below. This happens when I run my tests on our build server.

I think this is related to similar issues around WorkItemQueue.

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
--
at NUnit.Framework.Internal.Execution.WorkItemQueue.get_IsEmpty()
at NUnit.Framework.Internal.Execution.WorkShift.get_HasWork()
at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.StartNextShift()
at NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.OnEndOfShift(Object sender, EventArgs ea)
at NUnit.Framework.Internal.Execution.WorkShift.<StartWorkers>b__26_1(TestWorker s, WorkItem ea)
at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by jnm2** [comment] 2017-09-06 13:09
Looks like a duplicate of https://github.com/nunit/nunit/issues/2417.

**Comment by Cododromo** [comment] 2017-09-06 13:10
I was wondering that but not certain so decided to raise, apologies if it is.

**Comment by jnm2** [comment] 2017-09-06 13:15
No worries, always a judgment call and that's fine. If you're wondering sometimes it makes sense to ask in the other thread if you should stat a new one for the problem you're seeing.

**Comment by Cododromo** [comment] 2017-09-06 13:18
Thanks, will do in future. Still learning how to contribute but thanks for the advice.

**Comment by ChrisMaddock** [comment] 2017-09-06 13:22
Haha - I work with @Cododromo, we were looking at this together. 😄 I thought this was separate from #2417, but looking at the code, you're probably right. I'll close this one.

**Closed by ChrisMaddock** 2017-09-06 13:22 UTC

**Comment by jnm2** [comment] 2017-09-06 13:23
Welcome @Cododromo and sorry about the bug! 😛
