### ISSUE TITLE
` [Apartment(ApartmentState.STA)]` is not respected in nunit console 3.18.2?

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit#4831] opened 2024-09-20 01:51 UTC
It seems that ` [Apartment(ApartmentState.STA)]` is not respected in nunit console 3.18.2. 

Here's the test class

```
    [TestFixture]
    [Apartment(ApartmentState.STA)]
    [Category("ApartmentSTA")]
    public class ApartmentTest
    {
        [Test]
        public void ApartmentStateShouldBeSTA()
        {
            Assert.That(Thread.CurrentThread.GetApartmentState(), Is.EqualTo(ApartmentState.STA));
        }
    }

```

And here's the csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
	<PackageReference Include="Microsoft.Net.Test.Sdk" Version="17.10.0" />
	<PackageReference Include="NUnit.ConsoleRunner" Version="3.18.2" />
	    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
	<PackageReference Include="NUnit.Extension.VSProjectLoader" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiTargetAssembly\MultiTargetAssembly.csproj" />
  </ItemGroup>


</Project>


```

When I run the tests in Resharper test runner and `dotnet test`, it passes. But when I run it in nunit console, it fails.

Here's the command line
`"%NunitConsole%\nunit3-console.exe" "%slnFile%" --skipnontestassemblies --result="%testresultxml%"  --timeout=5000 > "%testresulttxt%"`

**Comment by stevenaw** [comment] 2024-09-20 07:40
Thanks for trying this across a few different runners @WindingWinter . I agree with @CharliePoole that this still "feels" like it may be a framework issue so I've transferred this there. 

Are you trying to use any globally-configured timeouts either as a command line argument or in a run settings file?

**Comment by stevenaw** [comment] 2024-09-20 07:43
Oh! I see the `--timeout` command line option, thanks for sharing that. I suspect you may be encountering https://github.com/nunit/nunit/issues/4119

Unfortunately, STA and timeout don't interplay well.

**Comment by WindingWinter** [comment] 2024-09-20 08:57
@stevenaw , I think so. I remove the `timeout` parameter and everything works fine

**Comment by CharliePoole** [comment] 2024-09-20 13:32
Since the issue is already being discussed in #4119 and especially #4658, which has some really creative ideas, I'm going to close this one.

**Comment by CharliePoole** [comment] 2024-09-20 13:37
I see this has already been moved. FWIW #4658 has a number of very creative ideas. I especially like the idea to check for a cancellation token in the Assert code.

**Comment by stevenaw** [comment] 2024-09-21 06:29
Thanks for confirming @WindingWinter . I'm going to close this since it's already being discussed in #4658 and #4119.

Thanks @CharliePoole . That was a particularly interesting one. Unfortunately we never quite squared it with third party assertions.

**Closed by stevenaw** 2024-09-21 06:29 UTC
