### ISSUE TITLE
Unreadable Error message when adding 'null' instance to Test Properties in [OneTimeSetup]

### ISSUE THREAD

**Issue by PavelStryhelski** [nunit/nunit#2278] opened 2017-06-23 13:17 UTC
Hi, 
I`ve found a curious thing:
when you`re trying to  add something which is null (any reference type, e.g. not initialized class) to 
TestContext.CurrentContext.Test.Properties you get an unreadable error message without any reference to where it has happened. The tests are being executed ok, you can debug and see they go to the end and when everything is finished - you can see Resharper/NUnit-console crash error log. Please find below what I mean.

We have a class:

[OneTimeSetUp]
        public virtual void FixtureSetup()
        {
            TestContext.CurrentContext.Test.Properties.Add("any_name", null);
        }
intead of 'null' you can try to add not initialized class.

executing this code via console runner give:

![image](https://user-images.githubusercontent.com/10687394/27483579-b36e7a76-582e-11e7-8638-a06246cbe9f4.png)

Stacktrace:
1) Error :
Exception has been thrown by the target of an invocation.

Server stack trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener, String filter)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Agents.RemoteTestAgent.Run(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

The same we can see for Reshaper runner:

![image](https://user-images.githubusercontent.com/10687394/27483737-4426ef26-582f-11e7-9fb1-dafb39ec87fd.png)

Maybe someone has the same issue and don`t know how to resolve it. I`ve spent almost 1,5 days to understand wtf is going on.

**Comment by ChrisMaddock** [comment] 2017-06-23 13:27
I think there's three separate bugs here! Hopefully someone else can sanity check this...

1. The stacktrace should be more useful. This should be fixed in NUnit Console 3.7 when it's released - see https://github.com/nunit/nunit-console/issues/11. If you were to run this with the `--inprocess` flag, I believe you'd see the stack trace in https://github.com/nunit/nunit/issues/1958. 

This brings us on to the other two bugs, which are taken from https://github.com/nunit/nunit/issues/1958#issuecomment-270693028:

2. Adding null properties should not cause a crash.

3. It should not be possible to modify the test properties during runtime. (At least, with the currently implemented interface!)

I think this covers everything, and makes this issue essentially a duplicate of #1958. I'll close this as a duplicate, but please try things out with the `--inprocess` flag, and confirm that you are seeing the same stack trace - if it's a separate problem, we can reopen this issue. 🙂

**Comment by ChrisMaddock** [comment] 2017-06-23 13:28
I should add - we'd appreciate a Pull Request, to fix all or part of #1958, if you'd be willing! 😄

**Closed by ChrisMaddock** 2017-06-23 13:27 UTC

**Comment by CharliePoole** [comment] 2017-06-23 15:28
Good analysis @ChrisMaddock 

Looking at @1958, I see that it has been sitting for a long time and none of us triaged it. It's still unlabeled and not on the backlog. So, in principle, nobody is supposed to work on it!

Of course, that's crazy! @PavelStryhelski we __would__ appreciate a PR. I'll go in and fix this one, but we should discuss how we can avoid have something sitting untriaged for such a long time.

**Comment by jnm2** [comment] 2017-06-23 15:29
@CharliePoole I'm in favor of reviewing every issue not tagged as closed with an eye to documenting and marking up-for-grabs anyway.

**Comment by jnm2** [comment] 2017-06-23 15:31
You might be more immediately interested in https://github.com/nunit/nunit/issues?q=is%3Aissue no%3Alabel though.

**Comment by CharliePoole** [comment] 2017-06-23 16:12
@jnm2 Yeah... the second is more useful.

I'll defer to @rprouse on how he wants to handle this.

**Comment by rprouse** [comment] 2017-06-28 18:34
Great analysis @ChrisMaddock. For adding null, we can just add a null guard to the property setter and throw with a useful message.

Not allowing adding/modifying properties during test execution is harder. My initial reaction was to make the setters internal, but that won't work because users can extend NUnit and need to be able to set properties. We could just leave it as is, fixing the null reference is probably the higher priority. Any other ideas?

**Comment by CharliePoole** [comment] 2017-06-28 19:08
Somewhere - I can't see it above - I suggested we need an adapter for the properties. The actual properties are in the actual test, which is in the TestExecutionContext. The TestContext exposes an adapter for the Test and Result, but the properties are actually exposed. That was just a mistake and should be fairly easy to fix by returning a readonly adapter that points to the real properties.
