### ISSUE TITLE
[TestFixture (Ignore = true)] should not be allowed

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#427] opened 2014-12-24 17:25 UTC
The NUnit v2 issue nunit/nunitv2#36 reported that the following code crashed 2.6.4. This code does not crash v3, but any tests in the class are not ignored.

```C#
[TestFixture (Ignore = true)]
class MyTests
{

}
```

As @CharliePoole said in the originating issue, this wasn't intended usage, but if people do it, the results are confusing. To fix, we have two choices,

1. Make it ignore tests within the class. I'm not sure if that is correct since an ignore reason is now required.
2. Make the Ignore property internal or protected so that it cannot be used in this way. Would this break extensibility in any way?
3. Raise an error if it is used this way? Can we even do that?

Are there other public properties that people might set in this way?

This isn't recommended usage and is a bug, so I am adding to the final release milestone, but I expect we could even push this to future.

**Comment by CharliePoole** [comment] 2015-01-01 19:23
Not as simple as I thought. The problem is that TestFixture is used in two ways. When used to signify a simple fixture, it's optional. We can ignore a fixture like this...
  [TestFixture, Ignore("some reason")]
or simply like this...
  [Ignore("some reason")]
In this case, there is no need for a public Ignore property.

But if we have a parameterized test fixture, the attriburte is required. If we want to ignore only one of the individual instances, we need some way to force the user to specify the reason. This should be illegal...
  [TestFixture(arg1, arg2, Ignore=true)]
while this should be allowed...
  [TestFixture(arg1, arg2, Ignore=true, IgnoreReason="some reason")]
as should this, which sets Ignore to true automatically...
  [TestFixture(arg1, arg2, IgnoreReason="some reason")]

Options for resolving this:

1. When the test is being ignored at runtime, check that a reason has been provided. If not, "promote" the ignored test to an invalid test and report it as an error.

2. Remove the public Ignore setter and require use of IgnoreReason instead.

3. Change the Ignore property to a string which supplies the reason and remove the separate IgnoreReason property.

Right now, I incline to the third option, but I'm looking for other suggestions.

BTW, the same issue arises with TestCase and we should apply the same solution to both attributes. It also arises with TestCaseData, but we can resolve that in several other ways since we are not limited to the kinds of arguments permitted on attributes.

**Comment by aschlapsi** [comment] 2015-01-01 21:28
I prefer the third option, too. I don't like the first option.
A fourth option could be to find another name like `IgnoreBecauseOf` or a better name.

**Comment by powerdude** [comment] 2015-01-01 23:16
I'd suggest enhancing the Ignore attribute.  Maybe allow:

[TestFixture(arg1, arg2)]
[Ignore(arg1, "reason"]
[Ignore(arg2, "different reason"]

Yes, arg1 is duplicated, but i'd find this easier to read or comment out later.  If no args, then the whole test fixture is ignored.

cliff

**Comment by CharliePoole** [comment] 2015-01-01 23:20
The thing about parameterized fixures is that the attribute is repeated.

[TestFixture("Joe", 32)]
[TestFixture("Sam", 35, Ignore=true)]
[TestFixture("Fred", 21]
public class MyFixture(string name, int age)
{
   ...
}

We want to be able to igonre the Sam fixture but require giving a reason.

We can't use the IgnoreAttribute in this situation because it would apply
to the class as a whole.

Charlie

**Comment by powerdude** [comment] 2015-01-02 13:02
ahh, i see.  then i'd go with 3a.  Remove Ignore and keep IgnoreReason since "Ignore" should probably still be a boolean.

**Comment by rprouse** [comment] 2015-01-03 12:12
I prefer #3 on this, change ignore to a string, that way it will read like the ignore attribute string constructor.

**Comment by CharliePoole** [comment] 2015-01-03 17:01
Well, everyone likes a string arg rather than bool. It's a tie between Ignore and some other name that's more suggestive of a string. I think I'm convinced by Rob's analogy with the constructor, that is: [TestFixture, Ignore("Some reason")] and [TestFixture(Ignore="Some Reason)] are not too different.

**Closed** 2015-01-04 22:38 UTC
Labels: 3.0, is:bug, pri:normal, status:merge
