### ISSUE TITLE
Testing multiple assemblies in nunitlite

### ISSUE THREAD

**Issue by xplicit** [nunit/nunit#481] opened 2015-01-31 18:21 UTC
There are two issues for me in the nunitlite.runner

1. Why not to use Assembly.LoadFrom here?
https://github.com/nunit/nunit/blob/master/src/NUnitFramework/nunitlite.runner/Runner/TextUI.cs#L201
It's more convenient to pass path in command line (ablosute or relative) to assembly instead of it's name. At my user experience I couldn't deternime the reason "assebmly could not be found" for a while before I have run the "strace" command and found that the nunitlite tries to load "myassembly.dll.dll" file. This behaviour also differs from nunit-console behaviour, when your pass the path to the assemlby in command line.

2. Why it runs tests only for the first assembly in the assemblies list? 
https://github.com/nunit/nunit/blob/master/src/NUnitFramework/nunitlite.runner/Runner/TextUI.cs#L208
It's looking strange. Here is use-case example: I have a project with four test assemblies: asm1, asm2, asm3, asm4. I want to run tests without additional components installation, so I decided to create the exe project, which runs all of these assemblies and pushes the result to CI server. Now I can't do this, because only first assembly will be tested and I have to write the script, which iterates over the assemblies and then have to write XML-merging tool to aggregate the result. Why not to do this inside the nunitlite.runner?

**Comment by oznetmaster** [comment] 2015-01-31 20:33
Both issues have been discussed previously.

 

I actually do use LoadFrom in my CF build if the assembly name is not a complete name (contains a ,) and if it has an extension or path.  I have suggested changing to that code, but was told that LoadFrom has problems on some platforms.  I prefer to put all of my test assemblies in a separate folder, so it is a benefit to automatically figure out which form to use.

 

The issue of running multiple assemblies is actually a current issue, but has not been assigned or given a milestone yet.

**Comment by CharliePoole** [comment] 2015-01-31 20:40
For your first point... NUnit has generally avoided LoadFrom, because it makes loads the assembly into a different context from assemblies that are loaded with Load. That concern is probably not relevant in the nunitlite runner, however, since only one assembly is being loaded anyway. 

If you would like to file a separate issue providing a command-line that causes the error you saw, we can see about fixing that problem. The intent is that you should use a file name on the command line, so it sounds as if that isn't actually working.

Your second point relates to a requirement that is outside of the current scope of the nunitlite runner. When the runner was first created, it was part of the nunitlite framework assembly. It's primary purpose was to allow running of the tests in an executable test assembly. This is how it worked through nunitlite 1.0.

We (well I) added the ability to load other assemblies as well as the comment you mention, because it "might be useful." When you think about it, running a test assembly in order to run a different test assembly is a bit strange. Not surprisingly, this facility was not used very much.

It's possible that we will end up resolving this issue by completely removing the ability to use nunitlite to load other assemblies besides the test that invokes it.

Regarding merging Xml files. The NUnit TestEngine already does that. I think that a better solution to your problem here is that we either expose that ability for your use from the command-line or (even better) fix nunit-console so that you are able to use it. I'll comment further on the other issue you filed.

**Comment by oznetmaster** [comment] 2015-01-31 21:05
I am very confused.

 

I NEVER load the NUnitLiteRunner or the NUnitFramework as part of the assembly that is being tested.  I often have many test assemblies on the device at one time.  I use the command line, or my pc based GUI, to specify which assembly to run.  I think the lack of being able to run multiple assemblies, even though they can be specified on the command lines, is an “bug”, which is why I opened an issue about it a while ago.

 

Why would it even be considered to remove this capability?  It needs to be enhanced, not removed.

**Comment by CharliePoole** [comment] 2015-01-31 21:36
@oznetmaster In that case, I don't know how you are using nunitlite. It definitely is not in the way I envisioned it would be used when I wrote it. I don't mean this negatively -- it's often the case that people figure out uses for something we create that we didn't see ourselves.

That said, I think it's up to you to explain how you are using it and why the feature is needed. Since you are a part of our team and therefore familiar with the architecture we are building, I would also hope you could explain why that architecture would _not_ meet your needs. My preference is to not have to develop two entirely different ways of doing things.

"I NEVER load the NUnitLiteRunner or the NUnitFramework as part of the assembly that is being tested." 

I don't understand. Do you mean you don't reference them? Clearly your tests have to reference the framework. And if you don't reference nunitlite, then how are you using it?

"I think the lack of being able to run multiple assemblies, even though they can be specified on the command lines, is an “bug”, which is why I opened an issue about it a while ago."

Yes, and that bug can be resolved in two entirely different ways. Except for your objection, it would have been resolved a long time ago by removing the ability to specify them on the command line. I'm trying to get you to explain, in a way we can understand, why that's the wrong thing to do. So far, my impression is that you want us to support this ability because it's not _yet_ in nunit-console. Is that the case?

**Comment by oznetmaster** [comment] 2015-01-31 22:15
Perhaps the problem is that I (and maybe others) do not have an insight into how you envisioned it would be used.  I thought that the way that I (and apparently others) use it was the correct one.  Maybe this discussion should start with you (re)explaining your vision for how nunitlite would be used?

 

I load the nunit framework and nunitlite runner into the device file system as two independent assemblies.  I also have a very small executable which interfaces with the device console, and instantiates and calls textui in the nunitlite runner with the entered command line, with a new instantiation for each command line entered.  I then load whatever test dlls I am using into the device file system.  I use the command line (or my PC based GUI) to select the desired test assembly, and the desired tests in it, and run them.

 

Obviously, the test assemblies reference the nunit framework, but there is no requirement that they be packaged or loaded into the device with the framework/runner.  I am now looking into the use of network shares to actually load the tests dynamically from the pc (using LoadFrom), rather than ever having to actually copy them to the device (Windows CE/CF does support network shares, and doing a LoadFrom from them).

**Comment by CharliePoole** [comment] 2015-02-01 00:18
Well, the use of NUnitLite has long been documented in its README file, which was the only documentation for some time. It's also outlined in the Program.cs that is added to your project when you use the nuget package.

With the coming of NUnit 3.0, it was proposed that we drop NUnitLite entirely, since our intention is to run nunit tests on devices via the engine. I argued against that, saying that there is an audience for nunitlite as a way to run single assemblies in the same environment as the test itself. Consequently, we kept it.

It may be that others have used NUnitLite as you do. They have never revealed themselves, however. Of course, this is open source, so anyone can take the code of nunitlite and use it for their own purposes, as a library, but you are the first person to tell us they did so.

NUnitLite is quite useful doing what it does: allowing rapid execution of tests from a single assembly in a single local environment. In fact, many people use it that way in desktop .NET, because it avoids the need to install any sort of independent runner on their CI systems. We'll keep supporting it for that purpose.

Our planned architecture for cross-platform execution uses the TestEngine with drivers that match controllers loaded either as part of the framework or alongside it. Except for the controllers, this is not part of the framework and so not an area of NUnit you have previously worked on. Could you consider pitching in on our effort to create a driver / controller combination that will enable running tests remotely on a CF system?

**Comment by oznetmaster** [comment] 2015-02-01 02:25
I fully support doing that, as I have indicated.  In fact, I already am using web sockets, and a framework controller, to do just that.  However, I (and I assume other) still need the capability of doing everything on the device itself, as I am currently doing.  I do not see why the two cannot coexist.  If the final multi-level architecture allows a build to be run on a device locally, and consumes no more resources then currently, that would be fine.  One limitation I have is a single AppDomain and a single Process, so whatever TestEngine/controller that is developed has to be able to run locally in that environment.

**Comment by oznetmaster** [comment] 2015-02-01 02:33
I perhaps seeming unrelated, but not, question.

 

Does anyone have any idea what percentage of NUnit testing is done with the development machine and the target test machine significantly remote from each other (like the opposite sides of the world)?

**Comment by CharliePoole** [comment] 2015-02-01 03:56
I would have to guess zero at this point, since we don't yet do it. NUnit 3.0 was designed to enable exactly that sort of thing. As well, it's intended to support remoting to a smart phone sitting on your desk. We have to get the basics done so we can move on with the remoting.

**Comment by CharliePoole** [comment] 2015-02-01 03:57
When dealing with overall direction, I really think it would be better to return to the discussion we started on the nunit committers list, where all the folks working on NUnit can be involved.

Let's keep the discussion on a particular issue to the point of that issue.

**Comment by CharliePoole** [comment] 2015-02-01 04:10
@oznetmaster 
"I fully support doing that, as I have indicated. In fact, I already am using web sockets, and a framework controller, to do just that. However, I (and I assume other) still need the capability of doing everything on the device itself, as I am currently doing. I do not see why the two cannot coexist."

It would help me if we could be talking about either one approach or the other in a given email or post. I thought you were writing about remote connection to a machine running the nunitlite runner and that's what I responded to. I'm not in favor of doing remoting that way.

If you are talking about wanting to work on the device alone, that's a different matter. In the case of CE devices, it has never even been discussed before. NUnitLite could serve this need but so could other approaches, since CE can support a lot more than many platforms. Feel free to start the conversation on one of the lists. Let's not keep confusing this issue with it.

**Comment by xplicit** [comment] 2015-02-01 08:18
> For your first point... NUnit has generally avoided LoadFrom, because it makes loads the assembly into a different context from assemblies that are loaded with Load. That concern is probably not relevant in the nunitlite runner, however, since only one assembly is being loaded anyway. 

I am looking into .NET source and it seems that the `Load` and `LoadFrom` do exactly the same job (`Load` just additionally converts assembly name into the file). They call `InternalLoadAssemblyName` at the end with the same params. Also there is an answer about contexts, which says, that `LoadFrom` loads the assembly in the context of `Load` https://social.msdn.microsoft.com/Forums/vstudio/en-US/b9154f8e-3b0c-47f7-ac00-52fa73f972b7/differences-between-assemblyload-and-assemblyloadfrom-and-related-concept-load-context-or?forum=clr Am I missing something?

`LoadFrom()`

https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/reflection/assembly.cs#L126
https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/reflection/assembly.cs#L1695
https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/reflection/assembly.cs#L1718

`Load()`
https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/reflection/assembly.cs#L279
https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/reflection/assembly.cs#L285
https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/reflection/assembly.cs#L1734
https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/reflection/assembly.cs#L1750

I'll create other issue which shows "assembly not found" exception, when filename passed to the command line

**Comment by CharliePoole** [comment] 2015-02-01 16:04
Thanks for the links. I'll read them with interest!

Bear in mind that NUnit (2.x) had to run under CLR 1.0, 1.1, 2 and 4. In addition it had to run under Mono. NUnitLite has to run in all those environments plus compact framework and a few others. NUnit 3.0 inherits all the same platforms minus CLR 1 and CF 2.0 but will be adding a few others.

I point this out because the microsoft forum question you point to is about CLR 4 - by which I assume they mean _microsoft_ CLR 4 exclusively. 

Although the code for the framework has a bunch of #ifs, we actually make a big effort to avoid them. Using the same code for all platforms is better because that way the code gets exercised more and bugs tend to be surfaced and removed more quickly.

My comments about LoadFrom should be read in the context of loading assemblies outside of the application base. It has often been suggested that NUnit should do that rather than trying to set up a new AppDomain with its own appbase. We would use LoadFrom in a more judicious way if we had to, after testing it on all the platforms we support. In this case, it doesn't seem to be needed. It looks like nunitlite simply has a bug in it because it doesn't use our standard pattern of getting the AssemblyName and then using Load on that. I settled on this pattern after a lot of experimentation across multiple platforms because it the only one that worked well on all of those we supported.

The intention of both command lines is that you will enter file names rather than assembly names. Coincidentally, the error in nunitlite allows entering assembly names and @oznetmaster seems to have fixed his private copy to allow either. That may actually be a feature to support in both places!

**Comment by xplicit** [comment] 2015-02-01 16:39
I do not insist to use `LoadFrom()`,  what I want just to have the ability to use filenames in nunitlite, if  you think that using GetAssemblyName + Load is better solution it's normal for me.

>Coincidentally, the error in nunitlite allows entering assembly names and @oznetmaster seems to have fixed his private copy to allow either.

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/nunitlite.runner/Runner/TextUI.cs#L197-L203

Do you mean this fix for compact framework? It should work for other platforms too (by the way it uses LoadFrom()), but `name.IndexOf('\\')` should be changed to `name.IndexOf(Path.PathSeparator)` or it won't work on linux.

**Comment by CharliePoole** [comment] 2015-02-01 20:54
No, I meant his private copy (which we can't see anywhere) :-)

However, I suppose it's the same fix, which probably got into our codebase when we were doing mass updates for CF. It shouldn't be a conditional and as you say it won't work on Linux. I'll take care of that in fixing your other issue.

**Comment by CharliePoole** [comment] 2015-02-01 20:57
@xplicit By "other issue" I meant the one you said you were going to create. :-)

**Comment by oznetmaster** [comment] 2015-02-01 21:06
You need to check DefaultAssemblyTestBuilder.cs as well.  There is a NETCF conditional there around Assembly.LoadFrom.

**Comment by CharliePoole** [comment] 2015-02-01 21:20
@oznetmaster Thanks... I'll check that as well.

**Comment by CharliePoole** [comment] 2015-04-19 21:57
Of the two original points, it looks like

1. Was already implemented: https://github.com/nunit/nunit/blob/master/src/Common/nunit/AssemblyHelper.cs#L119

2. Is covered in #533, assuming we go ahead with the runner. There's currently a discussion thread on nunit-developer about whether we should provide general command-line runner support as a part of NUnitLite. Please chime in there!

Given that both items are covered elsewhere, I'm closing this as duplicate.

**Closed by CharliePoole** 2015-04-19 21:57 UTC
Labels: is:feature, status:review

**Comment by oznetmaster** [comment] 2015-04-20 01:03
As far as I know, it was never implemented.  Multiple assemblies can be given on the command line, but only the first one is ever used.  There is another thread on this somewhere.

**Comment by CharliePoole** [comment] 2015-04-20 02:20
Point 1 was indeed implemented as the link to the code shows. The code now opens either a file path or an assembly name.

Point 2, as I said, is not implemented but is covered by a different issue. We have too many issues talking about the same thing, so I'm trying to clean them up in order to move forward.
