### ISSUE TITLE
NullReferenceException when using inherited property for ValueSource

### ISSUE THREAD

**Issue by pjquirk** [nunit/nunit#1109] opened 2015-12-02 18:48 UTC
Consider the following test:

	namespace NUnitTest
	{
		using System;
		using NUnit.Framework;

		[TestFixture]
		public class DerivedFixture : BaseFixture
		{
			[Test]
			public void SampleTestMethod([ValueSource(nameof(MyDataSource))] int value)
			{
				Console.WriteLine("Value: " + value);
			}
		}

		public abstract class BaseFixture
		{
			public static int[] MyDataSource => new[] { 1, 2, 3 };
		}
	}

Running this with the console runner and Visual Studio Test Adapter fails with a `NullReferenceException`:

	C:\Projects\NUnitTest\bin\Debug>"\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" NUnitTest.dll
	NUnit Console Runner 3.0.5797
	Copyright (C) 2015 Charlie Poole

	Runtime Environment
	   OS Version: Microsoft Windows NT 6.3.9600.0
	  CLR Version: 4.0.30319.42000

	Test Files
		NUnitTest.dll

	Errors and Failures

	1) Invalid : NUnitTest.DerivedFixture
	An exception was thrown while loading the test.
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at NUnit.Framework.Internal.Builders.ParameterDataSourceProvider.GetDataFor(IParameterInfo parameter) in C:\Sources\Third Party\Github\nunit\src\NUnitFramework\framework\Internal\Builders\ParameterDataSourceProvider.cs:line 67
	   at NUnit.Framework.CombiningStrategyAttribute.BuildFrom(IMethodInfo method, Test suite) in C:\Sources\Third Party\Github\nunit\src\NUnitFramework\framework\Attributes\CombiningStrategyAttribute.cs:line 142
	   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite) in C:\Sources\Third Party\Github\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultTestCaseBuilder.cs:line 140
	   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildTestCase(IMethodInfo method, TestSuite suite) in C:\Sources\Third Party\Github\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 204
	   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture) in C:\Sources\Third Party\Github\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 179
	   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData) in C:\Sources\Third Party\Github\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 151
	   at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__48.MoveNext() in C:\Sources\Third Party\Github\nunit\src\NUnitFramework\framework\Attributes\TestFixtureAttribute.cs:line 227
	   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfotypeInfo) in C:\Sources\Third Party\Github\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultSuiteBuilder.cs:line 80

	Run Settings
		WorkDirectory: C:\Projects\NUnitTest\bin\Debug
		NumberOfTestWorkers: 12

	Test Run Summary
		Overall result: Failed
	   Tests run: 0, Passed: 0, Errors: 0, Failures: 0, Inconclusive: 0
		 Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
	  Start time: 2015-12-02 18:25:52Z
		End time: 2015-12-02 18:25:52Z
		Duration: 0.052 seconds

	Results (nunit3) saved as TestResult.xml

The issue is that [this line in `ValueSourceAttribute.GetDataSource()`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/ValueSourceAttribute.cs#L108) fails to retrieve the inherited member and so returns `null`.  The return value is subsequently not checked in the [calling code in ParameterDataSourceProvider.GetDataFor()](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Builders/ParameterDataSourceProvider.cs#L67).

The [documentation for this attribute](https://github.com/nunit/nunit/wiki/ValueSource-Attribute) does not mention whether this is a supported scenario or not.  Personally I would like to see it be supported, which I believe can be done simply by adding `BindingFlags.FlattenHierarchy` to the line of code linked above.

`TestCaseSourceAttribute` has the [same code to retrieve data source members](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs#L218), but instead of a `NullReferenceException` the test just fails with the error "No arguments were provided".

Note: I have tested this using _nunit.framework.dll_ from the 3.0.1 Nuget release and also from master at 373dcefa70109a1a4c9a914f17561b6b4d90f977.

**Comment by pjquirk** [comment] 2015-12-02 18:56
This can be worked around by specifying the base class type in the attribute:

    [Test]
    public void SampleTestMethod([ValueSource(typeof(BaseFixture), nameof(MyDataSource))] int value)
    {
        // ...
    }

**Comment by CharliePoole** [comment] 2015-12-02 19:38
This corresponds to #1103, which deals with the same problem in TestCaseSourceAttribute.

In the normal course, we should fix both of these at the same time, in the same way.

**Comment by constructor-igor** [comment] 2016-01-04 16:50
Hi,
I want to try to fix the issue, but I cannot understand what expected behavior: 
* show error message (like nunit v2)
* support loading test data from base classes
* other?
Igor.

**Comment by rprouse** [comment] 2016-01-04 20:17
The expected behaviour is to load test data from base classes. I expect that the issue is with the BindingFlags when we are reflecting the static property.

**Comment by CharliePoole** [comment] 2016-01-20 16:45
Closing manually. 

@jhamm For automatic closure, the PR has to contain the phrase "fix #1109" or "fixes #1109" - GitHub doesn't want to be closing issues arbitrarily so they restrict what they act on.

**Closed by CharliePoole** 2016-01-20 16:45 UTC
Labels: closed:done, easyfix, is:bug, pri:normal
