### ISSUE TITLE
Is.Not.Null evaluates inconsistently if used more than once

### ISSUE THREAD

**Issue by TimothyDJewell** [nunit/nunit#4174] opened 2022-09-10 02:47 UTC
This fails with the following message:
```
var constraint = Is.Not.Null;
object o = new object();
Assert.That(o, constraint, "#1");
Assert.That(o, constraint, "#2"); // fails with the message "#2  Expected: null  But was:  <System.Object>"
```

This passes:
```
var constraint = Is.Null;
object o = null;
Assert.That(o, constraint, "#1");
Assert.That(o, constraint, "#2");
```

This came up as I've been working to update an NUnit 2.6.4 test project to NUnit 3.13.3.  As part of going through https://docs.nunit.org/articles/nunit/release-notes/breaking-changes.html, there's a note that:
> | TestCaseSourceAttribute | The attribute forms using a string argument to refer to the data source must now use only static fields, properties or methods. |

The trivial reproduction I have is:
```
[TestFixture]
public class TestThisStuff
{
    public static TestCaseData[] trivialTestCases = new[]
    {
        new TestCaseData(null, Is.Not.Null),
        new TestCaseData("foo", Is.Not.Null),
    };

    [TestCaseSource(nameof(trivialTestCases))]
    public void TestThings(object o, Constraint expectation)
    {
        Assert.That(o, expectation);
    }

    [TestCaseSource(nameof(trivialTestCases))]
    public void TestThings2(object o, Constraint expectation)
    {
        Assert.That(o, expectation);
    }
}
```
This will run four testcases:
1. `TestThisStuff.TestThings(null,<unresolved <null>>)`
2. `TestThisStuff.TestThings("foo",<unresolved <null>>)`
3. `TestThisStuff.TestThings2(null,<unresolved <null>>)`
4. `TestThisStuff.TestThings2("foo",<unresolved <null>>)`

Which will produce two failures:
> 1) Failed : TestThisStuff.TestThings(null,<unresolved <null>>)
  Expected: not null
  But was:  null
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
>
> 2) Failed : TestThisStuff.TestThings2("foo",<unresolved <null>>)
  Expected: null
  But was:  "foo"
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)

Note that:
* `TestThisStuff.TestThings2(null,<unresolved <null>>)` did not fail
*  `TestThisStuff.TestThings2("foo",<unresolved <null>>)` failed, even though it seemed to be correct.

The solution I have found for now is to turn the static field `trivialTestCases` into a static method, but I felt like this was a strange inconsistency.  If it can't evaluate more than once, it seems like this is something that the constraint should detect and explicitly prevent.  If it can evaluate more than once, it should do so correctly.

**Comment by manfred-brands** [comment] 2022-09-10 07:10
I have never seen constraints being reused and it does seems that these are not intended that way. TestCaseSource is normally for data values.

The first thing `Assert.That` is to call `IResolveConstraint.Resolve()` on the constraint.
This return the `not <null>` constraint from your `<unresolved <null>>` constraint.
But this operation is destructive, After this your original constraint is now only `<null>` aka `Is.Null`, the `Not` part is gone.

What works is if you `Resolve` the constraint before using it:

```csharp
private static readonly IConstraint IsNotNull = ((IResolveConstraint)Is.Not.Null).Resolve();

private static readonly TestCaseData[] TrivialTestCases = new[]
{
    new TestCaseData(null, IsNotNull),
    new TestCaseData("foo", IsNotNull),
};
```

I agree it is not nice and a runtime error would be better than unexpected results.

**Comment by mikkelbu** [comment] 2022-09-10 18:19
I agree that this is an odd behaviour, and I also run into it many years ago, There is a https://docs.nunit.org/articles/nunit/writing-tests/constraints/ReusableConstraint.html which suggest that you can wrap you constraint in a `ReusableConstraint` to avoid the problem.

**Comment by juwens** [comment] 2022-09-19 08:56
> I have never seen constraints being reused and it does seems that these are not intended that way. TestCaseSource is normally for data values.

you may not have seen it, but other people surely did.     
We've wrote our own Version of "Assert.That" (for reporting reasons) and stumbled upon this oddity.

**Comment by OsirisTerje** [comment] 2023-04-30 19:34
Since this is by design, and the workaround is to use ReusableConstraint, and it is documented, we can close this.

**Closed by OsirisTerje** 2023-04-30 19:34 UTC
