### ISSUE TITLE
[Regression] NUnit3 doesn't catch AccessViolationException

### ISSUE THREAD

**Issue by damageboy** [nunit/nunit#1160] opened 2015-12-27 09:19 UTC
The following test works (as expected) in NUnit 2.6.4 but fails to catch the access violation in NUnit 3.0.1:

```c#
using System;
using System.Runtime.InteropServices;
using NUnit.Framework;

namespace NUnitAccessViolation
{
  public class UnsafeTests
  {
    [Test]
    public unsafe void CatchAccessViolation()
    {
      byte* p = (byte *) Marshal.AllocHGlobal(100).ToPointer();
      Assert.That(() => *p, Throws.Nothing);
      Marshal.FreeHGlobal((IntPtr) p);
      Assert.That(() => *p, Throws.Exception.TypeOf<AccessViolationException>());
    }
  }
}
```

**Comment by damageboy** [comment] 2015-12-27 09:20
I've created a gist out of this:
https://gist.github.com/damageboy/b08741ae873cb27de92a

**Comment by damageboy** [comment] 2015-12-27 11:59
For completion, here is the NUnit 3.0 output:

```
C:\temp\NUnitAccessViolation>packages\NUnit.Console.3.0.1\tools\nunit3-console.exe NUnitAccessViolation\bin\Debug\NUnitAccessViolation.dll
NUnit Console Runner 3.0.5813
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

Test Files
    NUnitAccessViolation\bin\Debug\NUnitAccessViolation.dll


Errors and Failures

1) Failed : NUnitAccessViolation.UnsafeTests.CatchAccessViolation
  Expected: <System.AccessViolationException>
  But was:  no exception thrown
at NUnitAccessViolation.UnsafeTests.CatchAccessViolation() in c:\temp\NUnitAccessViolation\NUnitAccessViolation\UnsafeTests.cs:line 27

Run Settings
    WorkDirectory: C:\temp\NUnitAccessViolation
    NumberOfTestWorkers: 8

Test Run Summary
    Overall result: Failed
   Tests run: 2, Passed: 1, Errors: 0, Failures: 1, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2015-12-27 09:17:15Z
    End time: 2015-12-27 09:17:15Z
    Duration: 0.185 seconds

Results (nunit3) saved as TestResult.xml
```

**Comment by constructor-igor** [comment] 2015-12-28 15:39
@damageboy, I cannot reproduce the issue: nunit v2 and v3.0.1 shows same result for test from gist (see details below):

Project should allow "unsafe" code:
![image](https://cloud.githubusercontent.com/assets/1849690/12020672/a55766c6-ad87-11e5-85c9-c9edb7c342b1.png)

nunit v3.0.1 console:
![image](https://cloud.githubusercontent.com/assets/1849690/12020740/3835d950-ad88-11e5-9b20-128830f8270c.png)

nunit v2.6.4 console:
![image](https://cloud.githubusercontent.com/assets/1849690/12020782/a355b6f6-ad88-11e5-9a3a-0661b068ba8b.png)

Resharper usually shows same error message:
![image](https://cloud.githubusercontent.com/assets/1849690/12020861/659b345c-ad89-11e5-966c-a0d28859abe8.png)

sources of the tests (including sample from gist) can be found here: https://github.com/constructor-igor/TechSugar/tree/master/TestingLab/NUnitSamples

**Comment by CharliePoole** [comment] 2015-12-28 16:06
@constructor-igor Thanks for the work!

@damageboy Unless you have more info, we will close this.

**Comment by rprouse** [comment] 2015-12-28 16:06
We made a conscious decision when we were rewriting NUnit 3 not to catch Corrupted State Exceptions (CSE), especially Access Violations. These exceptions often indicate corrupted memory and should not be recovered from. I'm sure your case is simplified, but you should be checking for nullptr rather than checking that an access violation is thrown if you dereference a null pointer.

I am of a fairly strong opinion that NUnit should not be catching CSE's. The code under test may produce them, but I am of the opinion that they are serious enough that they should be fixed immediately, not tested for.

I am of course open to having my mind changed. I will assume that your test case is simplified as an easy way to reproduce the issue you are seeing. Where is the access violation being thrown in your tests and why do you feel we should catch it?

For more information, I recommend that you read https://msdn.microsoft.com/en-us/magazine/dd419661.aspx#id0070035 or go to StackOverflow for the executive summary, http://stackoverflow.com/questions/3469368/how-to-handle-accessviolationexception

I am going to close this as notabug because it is by-design. Feel free to continue commenting on this issue to convince us that we are taking the wrong approach. We will happily re-open the issue if you change our minds :smile:

**Comment by CharliePoole** [comment] 2015-12-28 16:14
@rprouse We crossed each other! It looks as if I misunderstood @constructor-igor 's post. He says that he cannot repro the issue, but the output does show the same result as what the OP complained about.

I think we need to have some user documentation about this but I'm not sure where it goes.

**Comment by rprouse** [comment] 2015-12-28 16:16
I will reopen and make it a doc issue.

**Comment by constructor-igor** [comment] 2015-12-28 17:36
I mean, reported test has same behavior under nunit v2.6.4 and v3.0.1 and I cannot reproduce different behaviors:
> The following test works (as expected) in NUnit 2.6.4 but fails to catch the access violation in NUnit 3.0.1:

**Comment by damageboy** [comment] 2015-12-28 18:54
I'll just pour my use-case here..

The actual tests that I'm running have to do with memory mapped files.
I have a class that does "extended" memory mapped files, above and beyond the .NET supplied classes.

The idea was that my tests should test that the unmapping of a memory mapped file actually does something, so I did that through incurring an access violation.

I could do that outside of an NUnit `Assert.That` if that general consensus is that NUnit must avoid catching these exceptions

**Comment by CharliePoole** [comment] 2016-06-21 16:01
Issue moved to [nunit/docs #75](https://github.com/nunit/docs/issues/75) via [**ZenHub.io**](https://www.zenhub.io/)

**Closed by CharliePoole** 2016-06-21 16:01 UTC
Labels: easyfix, is:docs
