### ISSUE TITLE
Performance degradation on many tests

### ISSUE THREAD

**Issue by timcassell** [nunit/nunit#4009] opened 2021-11-29 09:06 UTC
I've been noticing performance degradation when running many tests (thousands in my project) for a while. It's especially noticeable on my long-running tests, but the test times also show degradation on quick tests also.

I have setup and teardowns for every test.

At first I thought it was because I have objects pooling and the pool could be causing a leak and interfering with the performance, but I still see the same degradation with the pool disabled.

![image](https://user-images.githubusercontent.com/35501420/143837499-37054505-371d-4537-a9b3-5ed2127b89de.png)

![image](https://user-images.githubusercontent.com/35501420/143837063-6ffd6f9c-5549-4e8b-b417-57f31a7af45a.png)

When I run all tests in a group, the last sub-group takes `1.4s`. Then when I run just the last sub-group independently, it takes `480ms`, nearly 1/3 of the time. The more tests I run at a time, the longer it takes the last test to complete. This is a big problem for me with over 3600 tests, half of them are long-running (the images are only showing the quick tests).

I was using NUnit 3.13.0, and I just updated to NUnit 3.13.2 and saw the same behavior on both versions.

Any ideas?

[Edit] I should add that my library is targeting netstandard2.0, and I'm running the tests in net472 and net5.0 (I see the same degradation in both runtimes).

**Comment by mikkelbu** [comment] 2021-11-30 21:50
@timcassell Do you see the same degradation when you run the tests using the NUnit console - https://github.com/nunit/nunit-console/releases/tag/v3.12 - and/or NUnitLite - see e.g. https://docs.nunit.org/articles/nunit/running-tests/NUnitLite-Runner.html

When you are running the tests in VS you are also depending on VS, VSTest, and the NUnit 3 Test Adapter, so the above suggestion is to determine where the problem is. Note that both the NUnit console and the NUnit 3 Test Adapter uses the NUnit engine.

**Comment by timcassell** [comment] 2021-12-02 05:19
@mikkelbu Interestingly, I got the opposite effect with the nunit3-console. Though I could only run the net472 tests with it, not net5.0.

```
nunit3-console ProtoPromiseTests.dll --where "namespace == ProtoPromiseTests.APIs"

SequenceTests duration="0.539729"
```
```
nunit3-console ProtoPromiseTests.dll --where "class = ProtoPromiseTests.APIs.SequenceTests"

SequenceTests duration="0.606604"
```

And I'm not sure if the nunit3-console executes the tests in the same order as the VS test runner...

**Comment by lahma** [comment] 2022-01-26 18:08
When someone says thousands of tests this might be the same problem I encountered with my large parametrized test suite of 86k tests, more information in the PR here https://github.com/nunit/nunit/pull/4034 . You examples use a specific filter so it shouldn't be a filtering issue, but it might be the load phase which I also tried to address.

**Comment by rprouse** [comment] 2023-02-21 02:30
I believe this is fixed with #4034, please reopen if I am wrong.

**Closed by rprouse** 2023-02-21 02:30 UTC
Labels: confirm

**Comment by OsirisTerje** [comment] 2023-10-29 11:02
@lahma Is this also fixed in main ?   Do you have the PR for that?

**Comment by stevenaw** [comment] 2023-10-29 12:16
@OsirisTerje 
I think I ported this in https://github.com/nunit/nunit/issues/4053
I may've set the milestone incorrectly there. On mobile at the moment and can't check too in-depth

**Comment by OsirisTerje** [comment] 2023-10-29 15:28
@stevenaw Thanks!  That's cool!  #4053 is in and correct :-)

**Comment by lahma** [comment] 2023-10-29 15:52
Yes I can also confirm that the linked PR brought the intended changes to `main` too 👍🏻
