### ISSUE TITLE
CollectionAssert.AreEquivalent is extremely slow in NUnit version 3.13.1

### ISSUE THREAD

**Issue by NightElfik** [nunit/nunit#3825] opened 2021-04-18 22:30 UTC
I have recently updated NUnit to version 3.13.1 and some of our tests started to be extremely slow (~1000x). I have identified the culprit as `CollectionAssert.AreEquivalent`. The test case below takes 25 seconds to finish.

```csharp
[Test]
public void NUunitRepro() {
	var dict = new Dictionary<int, string>();
	for (int i = 0; i < 10000; ++i) {
		dict.Add(i, i.ToString());
	}
	CollectionAssert.AreEquivalent(dict.Values.AsEnumerable(),
		Enumerable.Range(0, 10000).Select(j => j.ToString()));
}
```

In comparison, when using `HashSet` for equivalence assertion, the test time is  ~10 ms:

```csharp

[Test]
public void NUunitRepro_UsingSet() {
	var dict = new Dictionary<int, string>();
	for (int i = 0; i < 10000; ++i) {
		dict.Add(i, i.ToString());
	}

	var actual = new HashSet<KeyValuePair<int, string>>(dict);
	NUnit.Framework.Assert.IsTrue(actual.SetEquals(Enumerable.Range(0, 10000)
		.Select(j => new KeyValuePair<int, string>(j, j.ToString()))));
}
```

**Comment by rprouse** [comment] 2021-04-18 23:08
Adding the confirm label but I think this is likely caused by changes in that area of the code. I just want to walk through it in the debugger.

**Comment by stevenaw** [comment] 2021-04-19 00:23
Thanks @NightElfik You'd mentioned a recent version update. Can I ask which version you were using previously (was it < 3.10)?
I'm wondering if this could be a duplicate of https://github.com/nunit/nunit/issues/2799

**Comment by rprouse** [comment] 2021-04-19 00:36
Testing the `NUnitRepro` test in .NET 5.0 with various versions of NUnit;

- 3.9 => 27ms
- 3.10.1 => 6.7 sec
- 3.11 => 6.8 sec
- 3.12 => 6.9 sec
- 3.13 => 17.8 sec
- 3.13.1 => 17.8 sec

So, this does look like a duplicate of #2799 but it was made even worse in the 3.13 release.

I'm going to close this issue as a duplicate and add this info to #2799

**Closed by rprouse** 2021-04-19 00:36 UTC
Labels: confirm, is:bug
