### ISSUE TITLE
The content of "NUnit.Framework.SuccessException" display abnormally.

### ISSUE THREAD

**Issue by vdanche** [nunit/nunit#4116] opened 2022-05-24 02:07 UTC
Affected Branch: Main
Affected Build: Version 17.3.0 Preview 2.0 [32519.311.main]

Steps to reproduce:
1. Open and extract the project(NUnitTestFx4.5.1.zip)
2. Debug the project
3. Observe the Exception window
[NUnitTestFx4.5.1.zip](https://github.com/nunit/nunit3-vs-adapter/files/8759031/NUnitTestFx4.5.1.zip)

Note: It is not a regression, it also repro in 16.11.14

Expected Results:
The content of "NUnit.Framework.SuccessException" should display normally.
![image](https://user-images.githubusercontent.com/65637796/169933843-52eb68d0-421e-4065-bc7f-dc0212106c7e.png)

Actual Results:
The content of "NUnit.Framework.SuccessException" display abnormally.
![image](https://user-images.githubusercontent.com/65637796/169933892-ac3d3999-903e-4ddd-ac14-36e9cce9a6d9.png)

dotnet --info
Microsoft Windows [Version 10.0.22000.675]
(c) Microsoft Corporation. All rights reserved.

C:\Users\v-yuqinsong>dotnet --info
.NET SDK (reflecting any global.json):
Version: 6.0.300
Commit: 8473146e7d

Runtime Environment:
OS Name: Windows
OS Version: 10.0.22000
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
Version: 6.0.5
Commit: 70ae3df4a6

.NET SDKs installed:
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by manfred-brands** [comment] 2022-05-25 02:40
The '' is the message you passed to `Assert.Pass`. If you change your code to `Assert.Pass("All good")` you get:

![image](https://user-images.githubusercontent.com/8655218/170167137-6645d700-989d-42bf-b499-8fd0903cd263.png)

How the message gets displayed is a matter of Visual Studio.
I suspect that they now put single quotes around the message and if the message is empty, it looks what you saw.
The exceptions look the same in both VS2019 and VS2022.

I went all the way back to NUnit version 3.0.0 and the exception pop-up was all the same.

**Comment by stevenaw** [comment] 2022-12-05 00:29
I can confirm, I hit this while testing a separate bug report today. I haven't tested different permutations for this but if it's as @manfred-brands says and that the formatting has changed within VS, then I wonder if the solution here would be to define a default message?

**Comment by stevenaw** [comment] 2022-12-05 00:30
I'm going to label this an enhancement for further discussion on approach

**Comment by stevenaw** [comment] 2022-12-13 16:59
I'd also be fine with closing it too.
I hadn't thought it a risk to break someone, but if we think there's even a potential for it to then I think it's not worth the risk of changing this

**Comment by stevenaw** [comment] 2023-01-02 15:36
I'm going to close this since there doesn't seem to be a strong interest in changing anything here.

**Closed by stevenaw** 2023-01-02 15:36 UTC
Labels: is:enhancement, awaiting:discussion
