### ISSUE TITLE
Test input for tests using TestCaseSource does not use correct apartment state

### ISSUE THREAD

**Issue by dfev77** [nunit/nunit#2717] opened 2018-02-16 12:24 UTC
When a fixture is marked with [Apartment(ApartmentState.STA)] all test will be run under STA context, but the the collection of test cases through a methods used as test case source is done in a MTA context.

Expected behavior: collect test cases data under STA context.

See attached tests
[NunitTests.zip](https://github.com/nunit/nunit/files/1731263/NunitTests.zip)

Using Nunit 3.9. Same behavior is encountered running with console 3.8 or Resharper 2017.3.2

**Comment by ChrisMaddock** [comment] 2018-02-16 13:04
Thanks @dfev77 - I haven't downloaded your sample, but this sounds like a believable issue. Would you be interested in contributing a Pull Request to fix this?

**Comment by jnm2** [comment] 2018-02-16 13:09
Since `[Apartment]` has only targeted test execution thus far, I wonder if this shouldn't be considered a new feature? Test case sources aren't part of test execution, only test discovery, I think.

**Comment by ChrisMaddock** [comment] 2018-02-16 13:17
Sorry - I'd misread. I thought you were saying the tests themselves were run under MTA. 

I agree this is to be discussed as a new feature. How to implement if could possibly be messy...

**Comment by jnm2** [comment] 2018-02-16 13:21
@dfev77 I'm actually really curious what your test case source uses STA for?

<details>
<summary>Here's a workaround, in the meantime.</summary>

```cs
/// <summary>
/// If the current thread is STA, invokes directly. Otherwise invokes on a new STA thread and blocks (Thread.Join) until it returns.
/// </summary>
public static T BlockInvokeSTA<T>(string threadName, Func<T> action)
{
    if (Thread.CurrentThread.GetApartmentState() == ApartmentState.STA)
        return action.Invoke();
    var exception = (Exception)null;
    var result = default(T);
    var staThread = new Thread(() =>
    {
        try
        {
            result = action.Invoke();
        }
        catch (Exception ex)
        {
            exception = ex;
        }
    }) { Name = threadName };
    staThread.SetApartmentState(ApartmentState.STA);
    staThread.Start();
    staThread.Join();
    if (exception != null) throw exception;
    return result;
}
```
</details>

**Comment by jnm2** [comment] 2018-02-16 13:25
Workaround:

```cs
private static IEnumerable<TestCaseData>  SomeTestCaseSource()
{
    return BlockInvokeSTA(nameof(SomeTestCaseSource), RequiresSTA);
}

private static IEnumerable<TestCaseData> RequiresSTA()
{
    yield return new TestCaseData(Thread.CurrentThread.GetApartmentState()).SetName("TestCaseSource marked as STA");
}
```

Using:

```cs
/// <summary>
/// If the current thread is STA, invokes directly. Otherwise invokes on a new STA thread and blocks (Thread.Join) until it returns.
/// </summary>
public static T BlockInvokeSTA<T>(string threadName, Func<T> func)
{
    if (func == null) throw new ArgumentNullException(nameof(func));

    if (Thread.CurrentThread.GetApartmentState() == ApartmentState.STA)
        return func.Invoke();

    var exception = (ExceptionDispatchInfo)null;
    var result = default(T);

    var staThread = new Thread(() =>
    {
        try
        {
            result = func.Invoke();
        }
        catch (Exception ex)
        {
            exception = ExceptionDispatchInfo.Capture(ex);
        }
    });

    staThread.Name = threadName;
    staThread.SetApartmentState(ApartmentState.STA);
    staThread.Start();

    staThread.Join();

    exception?.Throw();
    return result;
}
```

**Comment by ChrisMaddock** [comment] 2018-02-16 13:37
My opinion currently is that this is a sufficiently niche case, it's better to be implemented in workaround, rather than in the core library. @dfev77 - it may even work well to implement a custom ITestBuilder attribute, which creates the test cases under STA. (That's not an implementation I'm sure will work or not - it will need some investigation!)

That attribute could then be made available as it's own open source project, if you feel there's a wider audience.

As every - I could be convinced otherwise. 😄

**Comment by CharliePoole** [comment] 2018-02-16 16:03
Agree. This is how it works by design. I imagine that you're trying to do too much work in the source method. Consider shifting more of it to the execution phase.

@team if we did this it would seriously complicate any future parallelism in loading tests, in addition to the complexity it would add now.

**Comment by dfev77** [comment] 2018-02-22 14:40
@jnm2 the scenario for me was like this: there was some code dealing with both WinForms and WPF forms.  Had to add some tests for the WPF part and guess what, those did not work.
The test case source was creating some controls that will later be used as input to the test method.
Ended up doing it manually: writing two tests that will call the same "worker" method.

So, it is your call if to take it in consideration or reject it.

**Comment by jnm2** [comment] 2018-02-22 14:53
@dfev77 The thing is, do the controls really need to be created at test discovery time? You want to be doing as little as humanly possible during test discovery to generate the test case metadata. Instead of the test method receiving a `SomeControl` instance, it could receive a `Func<SomeControl>` instance. It sounds like you got a worker method to do a similar job which is also a good approach.

**Comment by rprouse** [comment] 2018-02-24 23:41
I also agree that this is fairly niche and that it would add unwanted complexity, so I am going to close this as won't implement.

**Closed by rprouse** 2018-02-24 23:41 UTC
Labels: closed:notabug, is:idea
