### ISSUE TITLE
Empty <failure /> element on <test-case /> failed due to [Timeout]

### ISSUE THREAD

**Issue by estrizhok** [nunit/nunit#4297] opened 2023-02-22 11:12 UTC
nunit.framework: 3.13.3

In version 3.12.0 you made it possible to use [Timeout] attribute in tests targeting .NETCore. However, reporting of an error caused by this attribute was and still is different from when the same error occurs in tests targeting .NETFramework:

Stripped of irrelevant for this issue attributes, the reports look as follows:

In `net7.0`
```
<test-case id="0-1001" 
           fullname="TestProject1.Tests.Test000" 
           runstate="Runnable" 
           result="Failed" 
           asserts="0"
           label="Test exceeded Timeout value 1000ms.">
  <properties>
    <property name="Timeout" value="1000" />
  </properties>
  <failure />
</test-case> 

```

In `net48`:
```
<test-case id="0-1001"
           fullname="TestProject1.Tests.Test000"
           runstate="Runnable" 
           result="Failed"
           asserts="0">
  <properties>
    <property name="Timeout" value="1000" />
  </properties>
  <failure>
    <message><![CDATA[Test exceeded Timeout value of 1000ms]]></message>
  </failure>
</test-case> 
```

Note how `net7.0` has an empty <failure /> element and a new label attribute not seen in `net48` variant.

Would you consider unifying how the failure is reported across different target frameworks?

**Comment by stevenaw** [comment] 2023-02-25 23:47
Thanks for the detailed comparison @estrizhok 
Run-time-based differences like this aren't ideal. While this exact behavior isn't described in #4021 , my instinct is that this could be a duplicate. I'm going to label this `confirm` to verify if that's the cause.

**Comment by stevenaw** [comment] 2023-02-25 23:57
Oh sorry, I misunderstood at first.
I had thought the failure message wasn't included at all, but I see it's instead just in a different place. Still, not ideal for any tooling dependent on this.

I still suspect the root cause is #4021 but I suspect this can also be fixed independently of the larger issue there.

**Comment by OsirisTerje** [comment] 2023-04-05 20:38
@manfred-brands  I see you aligned the messages in Commit 4f09e92dd025ecafd4fe30f85510056ccf183576
Author: Manfred Brands <manfred-brands@users.noreply.github.com>
Authored Date: Saturday, May 28, 2022 4:22 AM
Committer: Manfred Brands <manfred-brands@users.noreply.github.com>
Commit Date: Saturday, June 4, 2022 9:06 AM
Parent: ccbbd117

Ensure consistent messages for TimeoutCommand for both .NETFramework and .NETCore

I see it is merged to both v3 and v4, May 29th and June 4th 2022.   PR #4122 and PR #4118.  We should be able to close this as done then, right?

**Comment by manfred-brands** [comment] 2023-10-10 06:48
Yes, the messages were aligned.

It seems to work in our tests, but when I create a test in a separate project, the message wasn't there.
As the thread running the test cannot be stopped on .NET Core, it eventually will overwrite the test result.
It will also result in errors when eventually trying to run the `TearDown` as in the mean time the `TestExecutionContect.TestObject` had been reset in `WorkItem.WorkItemComplete`.
`TestExecutionContext.CurrentResult` is both overwritten and modified using `SetResult` calls.

After a timeout occurred, the next tests are run, but the existing test is still running.
If the test really hangs, it only affects that test, but if it eventually continues, we have two tests running in parallel.

I have update the code to create a separate `TestExecutionContext` and `TestResult` for the test at hand.
For my small example, this now keeps the Message as the completion of the slow test no longer overwrites the timeout message.

However, any tests that use `CurrentContext` etc, might fail.
Also AssertionCounts are likely wrong, even if the test runs normally within the allotted time.

Therefore, I'm not confident on this approach and I am of the opinion that keeping `TimeOutAttribute` enabled for NET Core build is severely flawed.

Developers targeting .NET 6 or later should use the `CancelAfter` attribute and use a `CancellationToken`.

@nunit/framework-team Shall we remove `Timeout` from our .NET 6 build, but keep it for the .NET Framework build?

**Comment by OsirisTerje** [comment] 2023-10-10 14:49
> Shall we remove Timeout from our .NET 6 build, but keep it for the .NET Framework build?
Imho, Yes.   
I assume you mean, "not deliver it with the net 6 framework version".  We need something to point users to the CancelAfter and CancellationToken.  We could add an obsolete warning on it, even Error, and use the message there to point devs further.

**Comment by stevenaw** [comment] 2023-10-10 15:55
> Shall we remove Timeout from our .NET 6 build, but keep it for the .NET Framework build?

> I assume you mean, "not deliver it with the net 6 framework version". 

I like the idea of obsolete as a nudge, but one thing I think we should consider here is how a multi-targeted test project could handle this.
For example, given the following TFMs:
```xml
<TargetFrameworks>net462;net60</TargetFrameworks>
```

It might be really jarring if we go with an approach which requires users to `#ifdef` different attributes based on their own runtimes. For example:

```csharp
#if NETFRAMEWORK
[CancelAfter]
#else
[Timeout]
#endif
[Test]
public async Task MyPotentiallyLongRunningTest()
{
}
```

**Comment by OsirisTerje** [comment] 2023-10-10 18:37
@stevenaw  Gooood point!

But, these two attributes are very similar.  Could we just have one (TimeOut) but different implementations for netfw and net6 ?
@manfred-brands  ?

**Comment by manfred-brands** [comment] 2023-10-11 00:04
@stevenaw `CancelAfter` also works with net48. And should be used for any multi-targeted code.

@OsirisTerje These attributes require different code in the tests. Replacing `Timeout` with `CancelAfter` without making changes to the test will not cancel the test. A [CancellationToken](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=net-7.0) enables cooperative cancellation. This means that the `CancellationToken` parameter supplied by NUnit must be passed to cancellable methods, see [Cancellation in Managed Threads](https://learn.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads)

I was indeed leaning to adding an ObsoleteAttribute like:
```csharp
#if !NETFRAMEWORK
    [Obsolete(".NET No longer supports aborting threads. Update your code to use CancelAfterAttribute instead")]
#endif
    public class TimeoutAttribute : PropertyAttribute, IApplyToContext
```

The `CancelAfterAttribute` is not documented anywhere. I will create a PR in the docs repo as part of this.

**Comment by manfred-brands** [comment] 2023-10-11 08:09
Does anyone know the history of `TestCaseTimeoutException`?
At the moment it is not used, so I would like to remove it.

**Comment by OsirisTerje** [comment] 2023-10-11 08:22
@rprouse @CharliePoole You know ?

**Comment by CharliePoole** [comment] 2023-10-11 08:53
It was added as part of PR #2106, which was an important step in allowing tests to be individually cancelled without cancelling the worker thread on which they were running. Before this PR, tests with the `TimeoutAttribute` had to be run on a separate thread, for which the worker thread waited by calling `Join`.

**Comment by CharliePoole** [comment] 2023-10-11 08:59
I wasn't familiar with `CancelAfter`. I wonder if it could be used under the covers in the same way the code in #2106 hid the creation and cancellation of threads from the user. If you tell the user to specify it, then you may end up killing worker threads and if all the worker threads happen to be killed, then the tests just stop running... which is how we determined that we needed that PR in the first place.

**Comment by manfred-brands** [comment] 2023-10-11 10:34
@CharliePoole With `Timeout` the thread is "Aborted", but then the `ThreadAbortException` is caught and then `Thread.ResetAbort()` is called, cancelling the abort. It is as if the user code threw the exception, except that no `finally` clause will be executed. A quick look at PR #2106 doesn't seem to show usages of the `TestCaseTimeoutException`, but I could have missed it at least they are no longer there.

`CancelAfter` I have created because `Timeout` doesn't work in .NET Core as `Thread.Abort` is no longer supported.
The test simply keeps running, despite returning to the caller as being timed-out.
With `CancelAfter`, there are no threads created nor killed. The time out will only occur is something obeys the passed in `CancellationToken`. Either the test needs to check itself using `IsCancelationRequested` or `ThrowIfCancelationRequested`. Or pass the token to api calls like `Task.Wait`, `HttpClient.GetAsync` etc. will do the checking.

**Comment by CharliePoole** [comment] 2023-10-11 12:08
@manfred-brands It could be that the `TestCaseTimeoutException` is left over from an earlier attempt to avoid cancelling the worker threads. I seem to remember that using `Thread.ResetAbort()` was the last of several attempts.

**Comment by manfred-brands** [comment] 2023-10-14 00:25
@nunit/framework-team Even though `TimeOutAttribute` *works* under .NET Framework, even there it is [strongly discouraged](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.abort?view=netframework-4.8#remarks).
Should we mark the attribute `Obsolete` unconditional?

**Comment by OsirisTerje** [comment] 2023-10-14 20:53
As long as we can use CancelAfter, I think that is wise. 
It might be considered a breaking change, as teams that have WarningAsError set will have to change.  I think we should just mark it as breaking and release it in 4.0.

**Closed** 2023-10-14 23:58 UTC
Labels: is:bug, pri:low
