### ISSUE TITLE
TestCaseSource to recognize new async streams

### ISSUE THREAD

**Issue by SavchukSergey** [nunit/nunit#3391] opened 2019-10-08 07:57 UTC
Would be nice to have support new .net core 3.0 async streams feature.

```c#
[Test, TestCaseSource(nameof(EnumerateAsync))]
public void AsyncStreamTest(object val) {
    Assert.IsNotNull(val);
}

public static async IAsyncEnumerable<object> EnumerateAsync()  {
    yield return await Create();
    yield return await Create();
}

public static Task<object> Create() {
    return Task.FromResult(new object());
}
```

Currently it says:
```
  X AsyncStreamTest [< 1ms]
  Error Message:
   System.InvalidCastException : Unable to cast object of type '<EnumerateAsync>d__1' to type 'System.Collections.IEnumerable'.
  Stack Trace:
     at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(IMethodInfo method)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
```

**Comment by AnthonyMastrean** [comment] 2022-01-20 15:03
Duplicates #2729

**Comment by SavchukSergey** [comment] 2022-01-20 15:21
Hello @AnthonyMastrean 

This issue is little different from #2729 

#3391 refers to ```IAsyncEnumerable``` interface while #2729 refers to pure ```IEnumerable```

**Comment by stevenaw** [comment] 2023-10-14 17:55
Closing this as I think this is a duplicate of #3043

**Comment by stevenaw** [comment] 2023-10-15 00:02
Reopening. I'd originally thought this may make sense to tackle in #3391 but I'm reconsidering now

**Closed** 2023-11-09 16:30 UTC
Labels: is:enhancement, pri:normal
