### ISSUE TITLE
Test case source increased by one after version 3.8.0

### ISSUE THREAD

**Issue by kholoudmohamed** [nunit/nunit#2775] opened 2018-03-25 11:47 UTC
Currently i have a test case that is data driven based on an enum which contains only 3 items
after upgrading from 3.7.1 (last working one for me) i got 4 test instances instead of 3

Here's the code.
Test Case
![image](https://user-images.githubusercontent.com/4224381/37874626-c37d92a8-3032-11e8-892d-7770863eeeb3.png)

Enum
![image](https://user-images.githubusercontent.com/4224381/37874635-ea9fdf9e-3032-11e8-8041-fe6d857c27de.png)

Test Cases
When i upgrade NUnit later than 3.7.1 i got an extra instance without a value and sure it fails as the test case source is not found
![image](https://user-images.githubusercontent.com/4224381/37874644-183916aa-3033-11e8-9360-1a6b481b868d.png)

**Comment by ChrisMaddock** [comment] 2018-03-25 12:54
This looks like a duplicate of this issue to me, do you agree? https://github.com/nunit/nunit3-vs-adapter/issues/489

One way to check would be to run it with the nunit-console, and see that runs 'correctly' or not.

I'll close this for now - but let us know if it needs reopening. 🙂

**Closed by ChrisMaddock** 2018-03-25 12:54 UTC
