### ISSUE TITLE
Generic test cases should work for int, double, string data.

### ISSUE THREAD

**Issue by KetakiNanaware** [nunit/nunit#2800] opened 2018-04-11 05:27 UTC
I am trying to write test case for generic type data. But I am getting error as
Unable to determine type arguments for fixture

**Comment by CharliePoole** [comment] 2018-04-11 05:36
I assume you mean a generic test fixture. Please show some code so we can help. At a minimum, we need the class definition and the TestFixture attributes you use to provide arguments.

**Comment by KetakiNanaware** [comment] 2018-04-11 06:11
[TestCaseSource("If2TestData")]
        public void If2Test(Option<int> self, Func<int, bool> predicate, Func<int> ifFunc, Func<int> elseFunc, Option<int> expected)
        {
            var actual = self.If(predicate, ifFunc, elseFunc);
            Assert.That(actual, Is.EqualTo(expected));
        }

        #region If2TestData
        private static object[] If2TestData =
        {
            #region Positive Cases
            new object[]
            {
                new Option<int>(25),
                new Func<int,bool>((s)=> s > 10),
                new Func<int>(()=> sqrt()),
                new Func<int>(()=> square()),
                new Option<int>(5),
            },
}

**Comment by KetakiNanaware** [comment] 2018-04-11 06:12
[TestCaseSource("If2TestData")]
        public void If2Test(Option<int> self, Func<int, bool> predicate, Func<int> ifFunc, Func<int> elseFunc, Option<int> expected)
        {
            var actual = self.If(predicate, ifFunc, elseFunc);
            Assert.That(actual, Is.EqualTo(expected));
        }

        #region If2TestData
        private static object[] If2TestData =
        {
            #region Positive Cases
            new object[]
            {
                new Option<int>(25),
                new Func<int,bool>((s)=> s > 10),
                new Func<int>(()=> sqrt()),
                new Func<int>(()=> square()),
                new Option<int>(5),
            },
}

**Comment by KetakiNanaware** [comment] 2018-04-11 06:13
[TestCaseSource("If2TestData")]
        public void If2Test(Option<int> self, Func<int, bool> predicate, Func<int> ifFunc, Func<int> elseFunc, Option<int> expected)
        {
            var actual = self.If(predicate, ifFunc, elseFunc);
            Assert.That(actual, Is.EqualTo(expected));
        }

        #region If2TestData
        private static object[] If2TestData =
        {
            #region Positive Cases
            new object[]
            {
                new Option<int>(25),
                new Func<int,bool>((s)=> s > 10),
                new Func<int>(()=> sqrt()),
                new Func<int>(()=> square()),
                new Option<int>(5),
            },
}

**Comment by KetakiNanaware** [comment] 2018-04-11 06:15
In this below exaple i want to use T instead of int so that i can pass string to double to it.


[TestCaseSource("If2TestData")]
        public void If2Test(Option<int> self, Func<int, bool> predicate, Func<int> ifFunc, Func<int> elseFunc, Option<int> expected)
        {
            var actual = self.If(predicate, ifFunc, elseFunc);
            Assert.That(actual, Is.EqualTo(expected));
        }

        #region If2TestData
        private static object[] If2TestData =
        {
            #region Positive Cases
            new object[]
            {
                new Option<int>(25),
                new Func<int,bool>((s)=> s > 10),
                new Func<int>(()=> sqrt()),
                new Func<int>(()=> square()),
                new Option<int>(5),
            },

**Comment by KetakiNanaware** [comment] 2018-04-11 10:26
I want comare the contents of two object of custom type. Even though two objects are having same value Assert.AreEqual return false.
What we should used to compare Contents of two object.

**Comment by mikkelbu** [comment] 2018-04-11 13:30
I don't think you can do what you describe. An alternative approach would be to have a generic testfixture and then have that specialized for int and the other types. That being said I think I would just duplicate the test as this seems like less overhead (and much easier to read) that introducing a generic testfixture, inherit it, ... . But perhaps I'm overlooking something?

Wrt. to `Assert.AreEqual` then you should ensure that your custom type has defined equality, otherwise the assertion will just use `Object.Equals` (e.g. reference equality for reference types).

**Comment by CharliePoole** [comment] 2018-04-11 14:18
@KetakiNanaware It may be more helpful if you post the code that is __not__ working, where you have used a generic method. NUnit supports generic test methods but only if the arguments are sufficient to allow us to deduce the type you want to use. Some things work and others don't. The only way to know is to see the actual code.

**Comment by KetakiNanaware** [comment] 2018-04-12 04:41
Wrt. to Assert.AreEqual as u said ensure that your custom type has defined equality. How to ensure that custom type has defined equality?

**Comment by jnm2** [comment] 2018-04-12 12:29
@KetakiNanaware By the way, you'll get a big performance benefit by implementing `IEquatable<Option<T>>` and override `Equals(object)` to call the `Equals(Option<T>)` method and override GetHashCode. The default ValueType GetHashCode and Equals implementations which structs use by default actually use reflection and are terribly slow. Implementing `IEquatable<T>` allows equality to be checked without boxing which wastes CPU and memory.

**Comment by jnm2** [comment] 2018-04-12 12:33
@CharliePoole @mikkelbu I don't see any reason why we can't infer the appropriate `T` here. I really want to improve this.
I wrote [very similar code](https://github.com/AutoMapper/AutoMapper/pull/1207/files#diff-91224148d55a3328cbab7963e1864b2fR50) for AutoMapper a long time ago.

**Comment by CharliePoole** [comment] 2018-04-12 13:54
@jnm2 I don't disagree. But we needed his exact generic signature in order to figure out what's wrong .

Next step IMO is to confirm the problem. Then it would be good to tell him if some simpler signature can work while we queue this up for a fix.

**Comment by jnm2** [comment] 2018-04-12 15:33
@CharliePoole Oops, I'm sorry! I wasn't thinking of making a comparison between my opinion and yours, but I remember that that phrase can be confusing! Your approach makes perfect sense to me.

@KetakiNanaware With NUnit 3.10.1, both your generic If1Test and your generic If2Test work without any  `Unable to determine type arguments for fixture` message:

```cs
public class ReproTests
{
    [TestCaseSource("If2TestData")]
    public void If2Test<T>(Option<T> self, Func<T, bool> predicate, Func<T> ifFunc, Func<T> elseFunc, Option<T> expected)
    {
    }

    private static object[] If2TestData =
    {
        new object[]
        {
            new Option<int>(25),
            new Func<int, bool>((s) => s > 10),
            new Func<int>(() => 2),
            new Func<int>(() => 3),
            new Option<int>(5),
        }
    };
}
```

As well as your [If1Test](https://github.com/nunit/nunit/issues/2800#issuecomment-380680919).

Do you have any idea what you were doing differently to cause `Unable to determine type arguments for fixture`? What version of NUnit are you using?

**Comment by CharliePoole** [comment] 2018-04-12 15:53
@jnm2 I didn't  think we were disagreeing, just taking a different approach since @KetakiNanaware had not originally given us the code that was failing. I like to get full info from issue posters before I put too many cycles onto the problem. 😈

Looking at that code, I think it should work and I believe you just confirmed that. I'll go further and say I'll be surprised if it doesn't work in fairly old versions of NUnit as well. IIRC, we had some problems with nested generic arguments, but not with multiple, single-level arguments.

**Comment by KetakiNanaware** [comment] 2018-04-13 06:38
@jnm2 I a using 2.6.3 version of N-unit. 
I am very new to N-unit so need some information like How to download .exe file  of NUnit 3.10.1.

**Comment by siprbaum** [comment] 2018-04-13 07:16
2.6.3 is the old NUnit2. 
NUnit3 is a rewrite of that which intentionally breaks some of the old (no longer supported) stuff.
If you start with a new project, I would strongly suggest to start with NUnit3.
You can download the framework and the console runner from http://nunit.org/download/

**Comment by jnm2** [comment] 2018-04-13 12:06
@KetakiNanaware @siprbaum is correct. Closing since this is not an issue in NUnit 3, but let us know if you run into any problems getting this example to work in NUnit 3.

**Closed by jnm2** 2018-04-13 12:06 UTC
Labels: closed:notabug
