### ISSUE TITLE
NullReferenceException when [TestFixtureSource] refers to data in a generic class.

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#1346] opened 2016-03-13 09:44 UTC
NUnit output:

```
Executing: C:\Tools\NUnit3\bin\nunit3-console.exe
NUnit Console Runner 3.0.5813 
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    ValveKeyValue/ValveKeyValue.Test/bin/Release/ValveKeyValue.Test.dll


Errors and Failures

1) Invalid : ValveKeyValue.Test.ArrayTestCase<TEnumerable>
An exception was thrown while loading the test.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData)
   at NUnit.Framework.TestFixtureSourceAttribute.<BuildFrom>d__17.MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)

2) Invalid : ValveKeyValue.Test.TopLevelEnumerableTestCase<TEnumerable>
An exception was thrown while loading the test.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData)
   at NUnit.Framework.TestFixtureSourceAttribute.<BuildFrom>d__17.MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)

Run Settings
    WorkDirectory: C:\projects\valvekeyvalue
    NumberOfTestWorkers: 2

Test Run Summary
    Overall result: Failed
   Tests run: 85, Passed: 85, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2016-03-13 09:36:40Z
    End time: 2016-03-13 09:36:41Z
    Duration: 1.241 seconds
```

Full build process output is available at https://ci.appveyor.com/project/xPaw/valvekeyvalue/build/1.0.0.20-AppVeyor#L60

Seemingly, nunit3-console returns a status code of 0. I'd expect in a failure case such as this, it would return non-zero.

Code that causes this issue:

`[TestFixtureSource]` here: https://github.com/SteamDatabase/ValveKeyValue/blob/dc20dcde8d4efddfcc0ed7730fd693563401300a/ValveKeyValue/ValveKeyValue.Test/Text/ArrayTestCase.cs#L7
Points to this collection here: https://github.com/SteamDatabase/ValveKeyValue/blob/dc20dcde8d4efddfcc0ed7730fd693563401300a/ValveKeyValue/ValveKeyValue.Test/TestFixtureSources.cs#L9

**Comment by ChrisMaddock** [comment] 2016-03-27 19:50
I've created a minimum example of this error - the issue appears to be that `TestFixtureSource` doesn't work with generic classes. The below reproduces the crash:

```
    [TestFixtureSource("SupportedEnumerableTypesForDeserialization")]
    public class ArrayTestCase<T>
    {
        private string _aString;

        public ArrayTestCase(string aString)
        {
            _aString = aString;
        }

        [Test]
        public void Test()
        {
            Assert.That(_aString, Is.EqualTo("Something"));
        }

        public static IEnumerable<string> SupportedEnumerableTypesForDeserialization
        {
            get
            {
                yield return "TestCase";
            }
       }
    }
```

Additionally verified that the console returns zero on this crash - as it's at test-suite level, and only invalid assemblies, or individual tests are counted towards the return code. That seems like a separate issue - I'll create another.

**Comment by CharliePoole** [comment] 2016-03-27 20:21
@ChrisMaddock It's usually best if somebody manages to actually review, categorize and prioritize an issue before we work on it. As a committer, you're able to do that yourself. It's a small thing, but it allows us all the opportunity to come back and say whether we agree or disagree with how you are suggesting to handle it. Additionally, if you then decide you want to work on the issue, please assign it to yourself, so that everybody knows.

In this case, it's probably no harm since it seems like your review and fix all came together  this morning anyway. We can all comment on the issue and the fix simultaneously. :-)

**Comment by CharliePoole** [comment] 2016-03-27 20:22
The return code issue is something I thought we had already dealt with. I'll have to search.

**Comment by CharliePoole** [comment] 2016-03-27 20:27
I changed the title again. The problem isn't using [TestFixtureSource] in a generic class, it's when the data referred to lives in the same or probably even a different generic class.

I'd expect this to occur if the data source were an instance member of a class implementing IEnumerable. In that case, NUnit has to create an instance of the object and would not have enough information to do so, since no Type parameter is provided anywhere.

However, your example uses static data, so I find it a bit surprising.

**Comment by ChrisMaddock** [comment] 2016-03-27 20:38
@CharliePoole 
>In this case, it's probably no harm since it seems like your review and fix all came together this morning anyway. 

A little confused - I haven't done any work to fix this issue? This is unrelated to #1377, if that was your thinking? Was just aiming to first create a smaller reproducible example here, apologies if I've overstepped somewhere!

>The problem isn't using [TestFixtureSource] in a generic class, it's when the data referred to lives in the same or probably even a different generic class.

In @yaakov-h's original project, it's the test fixture class which is generic, not the class where the data lives. I've inadvertently lost that distinction in my example however, by trying to oversimplify.

**Comment by CharliePoole** [comment] 2016-03-27 20:51
@ChrisMaddock Au contraire! If anything, you understepped - if that's a word. I was taking it that you didn't feel "authorized" to label things as bugs, assign priorities, etc. and I wanted you to know that you are and should absolutely do those things the first time you start looking at an issue. Issues with no labelling have either not yet been looked at or were too puzzling to categorize.

I initially thought you also had a PR on this, but that was for another issue, so never mind that.

OK, so do we have confirmation of this bug in some form or another? If not, you should either confirm it or label and leave it for somebody else. If you want to work on it, assign it to yourself. As a new guy, you'll probably get a bunch of advice from us once you put your name on something, but you'll just have to live with that. :-)

**Comment by CharliePoole** [comment] 2016-03-27 20:53
This is potentially tricky in that there could be some things that can never work along with others that really should be made to work. For example, if NUnit is expected to instantiate some generic class without knowing what Type parameters to use... well, that's just not gonna happen!

**Comment by ChrisMaddock** [comment] 2016-03-27 21:10
@CharliePoole - Ok, no problem. Have generally left such things to yourself or @rprouse - as I'm not sure how you assign priorities/milestones, but can cope with marking bugs as bugs. :-)

>This is potentially tricky in that there could be some things that can never work along with others that really should be made to work.

I imagined it would be of that ilk once I narrowed it down. Hopefully there should be scope to at least catch the error however!

**Comment by CharliePoole** [comment] 2016-05-21 16:09
@yaakov-h @ChrisMaddock I looked at this further, planning to work on it, but I no longer think it's a bug, at least not as originally stated. Please review the following and comment before I go further.

TestFixtureSourceAttribute provides the arguments for instantiating a TestFixture, that is constructor arguments. The ArrayTestCase class has only a default constructor and @yaakov-h is trying to use the attribute to provide the type parameters. Unfortunately, since that's not what the attribute does, NUnit is unable to determine what type parameter to use in instantiating the class.

The repro that @ChrisMaddock wrote is slightly different. He provides a constructor taking a string argument. However, for NUnit's generic type parameter detection to come into play, we need a constructor that takes an argument of type T.

In both these examples, the simplest way to specify the type parameters is to forget about TestFixtureSoureAttribute and simply use the TypeArgs named parameter of TestFixtureAttribute. This won't solve the problem where you may need a degree of indirection in determining the types to instantiate, but that doesn't seem to be the case here.

There is at least a minimal bug here: we should be giving a better error message.

Alternatively, we could take it a step further and create a new feature whereby TestFixtureSourceAttribute allowed you to specify the type parameters directly. That may be a separate issue, however.

What do you guys think?

**Comment by ChrisMaddock** [comment] 2016-05-21 17:46
> However, for NUnit's generic type parameter detection to come into play, we need a constructor that takes an argument of type T.

Aha! That makes sense. I think your new feature proposal would be the ideal, but low priority, if the workaround is as simple as that.

**Comment by yaakov-h** [comment] 2016-05-22 08:57
> This won't solve the problem where you may need a degree of indirection in determining the types to instantiate, but that doesn't seem to be the case here.

It doesn't solve the problem of having multiple tests needing the same set of types. If `TestFixtureSourceAttribute` behaved as I expected it to here originally, then I could refactor the list of types shared by multiple tests into a common location.

Why is it though that this works with `TestFixtureAttribute`, but not with `TestFixtureSourceAttribute`? E.g., these two cases are functionally identical:

```
using System;
using System.Collections;
using NUnit.Framework;

namespace NUnit1346
{
    public class Class1
    {
        [TestCase(typeof(string))]
        [TestCase(typeof(bool))]
        public void TypeIsValueType(Type typeToTest)
        {
            Assert.That(typeToTest, Has.Property(nameof(Type.IsValueType)).EqualTo(true));
        }
    }
    
    public class Class2
    {
        [TestCaseSource(typeof(TestCaseSources), nameof(TestCaseSources.TypesToTest))]
        public void TypeIsValueType(Type typeToTest)
        {
            Assert.That(typeToTest, Has.Property(nameof(Type.IsValueType)).EqualTo(true));
        }
    }

    public class TestCaseSources
    {
        public static IEnumerable TypesToTest
        {
            get
            {
                yield return typeof(string);
                yield return typeof(bool);
            }
        }
    }
}
```

But these two are not:

```
using System;
using System.Collections;
using NUnit.Framework;

namespace NUnit1346
{
    [TestFixture(typeof(string))]
    [TestFixture(typeof(bool))]
    public class Class1<TTypeToTest>
    {
        [Test]
        public void TypeIsValueType()
        {
            Assert.That(typeof(TTypeToTest), Has.Property(nameof(Type.IsValueType)).EqualTo(true));
        }
    }

    [TestFixtureSource(typeof(TestCaseSources), nameof(TestCaseSources.TypesToTest))]
    public class Class2<TTypeToTest>
    {
        [Test]
        public void TypeIsValueType()
        {
            Assert.That(typeof(TTypeToTest), Has.Property(nameof(Type.IsValueType)).EqualTo(true));
        }
    }

    public class TestCaseSources
    {
        public static IEnumerable TypesToTest
        {
            get
            {
                yield return typeof(string);
                yield return typeof(bool);
            }
        }
    }
}
```

**Comment by CharliePoole** [comment] 2016-05-22 11:32
@yaakov-h Your comment is correct. TestFixtureSource allows reuse across multiple classes. That's what I meant when I wrote "This won't solve the problem where you need a degree of indirection..."  

It's a problem we need to solve and I hope we can next move on to discussing how to solve it. However, you asked for some explanation about why TestFixtureSourceAttribute works as it does. The answers may help us with our next steps, so I'll try to shed some light on that in this post.

TestFixtureSource was modelled on TestCaseSource and works pretty much the same. There are, however, some key difference that can't be avoided.

TestCaseSource always appears on the method for which it is supplying arguments. TestFixtureSource - as well as TestFixture - appears on a class and not on the constructor for which it is supplying arguments. Since there may be multiple constructors, NUnit has to deduce which one to use. This is a key difference between working with test classes and working with methods.

A second difference arises when dealing with generics. A test method may be generic, of course, but NUnit requires that it be possible to deduce the Type parameters from the method arguments. In the case of generic fixtures, it's fairly common that the Type parameters are not used in the constructor, so we supply several alternative means of specifying them.

Those differences aside, however, TestFixtureSource works pretty much like TestCaseSource. Your last example can be rewritten so that it works correctly:

```C#
    [TestFixtureSource(typeof(TestCaseSources), nameof(TestCaseSources.TypesToTest))]
    public class Class2
    {
        private Type TypeToTest;

        public Class2(Type typeToTest)
        {
            TypeToTest = typeToTest;
        }

        [Test]
        public void TypeIsValueType()
        {
            Assert.That(typeof(TypeToTest), Has.Property(nameof(Type.IsValueType)).EqualTo(true));
        }
    }
```

This example is actually a better one for comparison with your TestCaseSource example because it actually takes the type as an argument to the constructor, rather than as a Type parameter. Of course, I realize that you may need the fixture to be generic for other reasons, so let's move on to that issue.

TestFixtureAttribute gives you three different ways to specify Type parameters:
1. Use the TypeArgs named property to specify them directly.
2. If TypeArgs is not used and the leading attribute arguments are Types, they are used as Type parameters, while subsequent arguments are used as actual arguments.
3. Otherwise, NUnit attempts to deduce the Type parameters based on the actual arguments.

The second approach has long ago proven to be a design error. It confuses many users and makes the code overly complex. Nowadays, we advise people to use the TypeArgs property when the deductive approach doesn't work. When we were creating NUnit 3, I actually considered removing this feature, since we were allowing many other breaking changes, but ended up leaving it in for TestFixtureAttribute.

TestFixtureSourceAttribute OTOH is an entirely new class. It only supports the first and third approaches. The TypeArgs property, however, doesn't appear on the attribute itself, because that would make all the fixture instances use the same Type parameters. Instead, it is specified on a  TestFixtureData instance, supplied by the source. Here is how I believe your last example could be rewritten to use this feature:

```C#
    [TestFixtureSource(typeof(TestCaseSources), nameof(TestCaseSources.TypesToTest))]
    public class Class2<TTypeToTest>
    {
        [Test]
        public void TypeIsValueType()
        {
            Assert.That(typeof(TTypeToTest), Has.Property(nameof(Type.IsValueType)).EqualTo(true));
        }
    }

    public class TestCaseSources
    {
        public static IEnumerable TypesToTest
        {
            get
            {
                yield return new TestFixtureData().TypeArgs(typeof(string));
                yield return new TestFixtureData().TypeArgs(typeof(bool));
            }
        }
    }
```

Note I say "I believe" because I'm not able to check this out on the compiler right now. The syntax may vary slightly.

So... with that added background as requested, where do you think we should go from here?

**Comment by yaakov-h** [comment] 2016-05-29 07:26
With the additional background, this makes a whole lot more sense... except there's no `TestFixtureData.TypeArgs(Type)` API to do what you've done above - which looks like a very sane example.

The closest I could get was by abusing `TestFixtureAttribute`, which happens to implement `ITestFixtureData`. Without deep knowledge of the full NUnit APIs, I had to resort to this:

```
static class TestFixtureSources
{
    public static IEnumerable SupportedEnumerableTypesForDeserialization
    {
        get
        {
            yield return CreateTestFixtureDataForGenericTest(typeof(List<string>));
            yield return CreateTestFixtureDataForGenericTest(typeof(string[]));
            yield return CreateTestFixtureDataForGenericTest(typeof(Collection<string>));
            yield return CreateTestFixtureDataForGenericTest(typeof(IList<string>));
            yield return CreateTestFixtureDataForGenericTest(typeof(ICollection<string>));
            yield return CreateTestFixtureDataForGenericTest(typeof(ObservableCollection<string>));
        }
    }

    static TestFixtureParameters CreateTestFixtureDataForGenericTest(Type genericType)
    {
        var data = new TestFixtureAttribute
        {
            TypeArgs = new[] { genericType }
        };
        var parameters = new TestFixtureParameters(data);
        return parameters;
    }
}
```

So I think that perhaps:

1. NUnit should throw an exception indicating that it could not find a suitable constructor, rather than crashing with a `NullReferenceException`
2. If there's no suitable constructor, and the test fixture type is generic, and there's `type.GetGenericArguments().Count` arguments of type `Type`, the error message should instruct the user to use `TypeArgs` instead, if that was their intention. I'd think this error/mistake should be fairly easy to detect.
3. There should be an API on `TestFixtureData` to allow a consumer to set `TypeArgs`. Currently it's getter-only.

**Comment by CharliePoole** [comment] 2016-05-29 09:26
I agree on all three counts

**Closed** 2017-10-17 11:05 UTC
Labels: is:bug, pri:normal
