### ISSUE TITLE
Write up recommended way to test and link it from the readme

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2973] opened 2018-08-21 12:54 UTC
I find https://github.com/nunit/nunit/blob/master/BUILDING.md#build-script a bit vague and we've had a number of folks asking us how we test.

I think there's a lot of room for personal style assuming we have solid CI. My ideal workflow:

1. Locate existing tests or write new tests
2. Pin that test fixture to make it quick to rerun the tests while typing (even better, start continuous testing) by filtering classes in Test Explorer or adding tests to a new ReSharper test session
3. Implement a change
4. Before creating a Git commit, run `.\build.ps1 -t test` to make sure the passes and failures are as expected
5. If there are any surprises, find and pin the affected tests I didn't know about and go to step 3

**Comment by BrunoJuchli** [comment] 2018-08-21 18:07
Since you mention Resharper: I've tried running the tests with R# (2018.2 EAP 7 or 8, VS 2017.7) but they all end up with "Inconclusive". Starting with debugging there's an exception stating that Nunit 3.11 is not supported.
I've tried manually configuring the path to Nunit @ Resharper settings. I've chosen bin/Debug/net4.5 (and tried /Release, too) of the checked-out and built repository. Resharper finds nunit but the tests are still inconclusive.
What do I need to do to get the tests running @R#?

**Comment by jnm2** [comment] 2018-09-07 03:10
> What do I need to do to get the tests running @r#?

I opened https://github.com/nunit/nunit/issues/3008 to track this.

**Comment by FrankRay78** [comment] 2021-05-31 15:45
Hi @BrunoJuchli 

A multi-year follow up I know, but I wondered if you had any joy getting the Rider test runner working such that you could run tests directly in the IDE? 

It seems that JetBrains have had a bit of trouble circa 2018 / 2019 with their auto-detection of tests, see:  https://twitter.com/jetbrainsrider/status/1123930158627299328

However, it's 2021, I'm using the latest Rider (2021.1.2) and the issue is still occurring for me.

**Comment by BrunoJuchli** [comment] 2021-06-01 05:52
@FrankRay78 
Haven't tried again ever since. We're currently using xunit only in our projects, so...
On a sidenote: xunit 2.0 features are mostly still unsupported by R#/rider. There's been no significant development there for years.

**Comment by FrankRay78** [comment] 2021-06-09 10:52
FYI - I'm going to take this issue @rprouse

**Comment by rprouse** [comment] 2021-06-09 13:12
Thanks @FrankRay78

**Comment by rprouse** [comment] 2021-06-09 13:14
FYI, I made a pass at getting the tests to run in Visual Studio recently but couldn't get them working. Now that @OsirisTerje has released the 4.0 version of the adapter, we might have more luck.

**Comment by FrankRay78** [comment] 2021-06-09 13:50
Hi Rob.  I propose to address this issue with a more general documentation update to the BUILDING.md file, and then specifically address issue #3008 which covers running tests in the IDE. I hope this approach is acceptable.

**Comment by FrankRay78** [comment] 2021-06-11 10:15
Update. PR submitted to (hopefully) close this issue - https://github.com/nunit/nunit/pull/3875

**Comment by FrankRay78** [comment] 2022-10-01 09:57
Hi @rprouse, see my most recent comment above - PR https://github.com/nunit/nunit/pull/3875 has been merged. Unless there is something else regarding this issue that I'm not aware of, I suggest it can now be marked as closed.

**Closed** 2022-10-01 17:34 UTC
Labels: is:build, is:docs
