### ISSUE TITLE
TestCaseData.SetName issue

### ISSUE THREAD

**Issue by dgm90** [nunit/nunit#2333] opened 2017-07-28 13:23 UTC
When I use the SetName method to name my test and the name contains a dot, the VS Test Explorer doesn't display the test properly.
![image](https://user-images.githubusercontent.com/29230919/28718886-8f8c0ab8-73b0-11e7-9606-569e33edde92.png)

All the tests on the screen above are used in the same methods, but in the Test Explorer they are shown like different classes. All tests that don't have a dot in their name are combined in "CreateOrdersTests" - 5 items. But the "CreateSingleOrderChargeRate1.5 is put in the separate class "CreateSingleOrderChargeRate1".

If I substitute the dot with a comma, the issue is resolved. Check the screen.
![image](https://user-images.githubusercontent.com/29230919/28718991-f4708a62-73b0-11e7-87ee-b90e1c599797.png)

Thanks.

**Comment by CharliePoole** [comment] 2017-08-01 17:37
NUnit test names look like the full name of a method - plus optional arg list - by default, but we allow the user to change the name of the method part. NUnit actually has no expectations at all for the format of a name and does not even use the name to find tests unless you ask it to via a filter. IOW, an NUnit test name is an arbitrary string that does not even have to be unique.

Visual Studio, OTOH, assumes that tests are named as the full name of a test method and requires them to be unique. This is a mismatch that can never be completely overcome. For that reason, we can only suggest that users do not use names containing a dot, since it confuses visual studio.

My inclination is to close this as not a bug. An alternative is to mark it as an adapter bug. It's possible for the adapter to modify the name to meet vs requirements. I definitely do not think we should modify it generally, just for the sake of a single runner. 

@OsirisTerje If you would want to accept this as an issue for the adapter, please move it. Otherwise, let's close it.

**Comment by dgm90** [comment] 2017-08-02 10:30
Hello Charlie,

Thanks for your detailed response.

**Comment by OmicronPersei** [comment] 2017-08-25 00:27
Closing this for the reasons @CharliePoole gives above.

**Closed by OmicronPersei** 2017-08-25 00:27 UTC

**Comment by xhafan** [comment] 2019-04-25 07:40
This actually helped me: _we can only suggest that users do not use names containing a dot_

**Comment by ksokolowski7** [comment] 2020-11-13 15:26
Solution for this case is to replace dot with \u2024. So just before naming the test use `.Replace(".", "\u2024")`
