### ISSUE TITLE
Test reported as cancelled when it's really a timeout

### ISSUE THREAD

**Issue by oskarb** [nunit/nunit#3364] opened 2019-08-30 20:34 UTC
NUnit Console 3.10
Framework 3.12

Runs under Teamcity. It was not cancelled but it claims so and it turns out that it is most likely really the Timeout attribute that triggered this.

```stacktrace
[My.NameSpace.TestCaseName(3,null,True,null,null,False,null)] Test cancelled by user
[My.NameSpace.TestCaseName(3,null,True,null,null,False,null)]    at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Threading.TimerQueueTimer.Close()
   at System.Threading.TimerHolder.Close()
   at System.Threading.Timer.Dispose()
   at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass3_0.<.ctor>b__1(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TimeoutCommand.cs:line 78
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__1() in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 63
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 73
```

```
[03:49:06]
[Step 3/4] 1) Cancelled : C:\BuildAgent\[....]\SystemTests.dll
[03:49:06]
[Step 3/4] Cancelled by user
[03:49:06]
[Step 3/4] 2) Cancelled : NameSpace
[03:49:06]
[Step 3/4] Cancelled by user
[03:49:06]
[Step 3/4] 3) Cancelled : NameSpace.1
[03:49:06]
[Step 3/4] Cancelled by user
[03:49:06]
[Step 3/4] 4) Cancelled : NameSpace.1.2
[03:49:06]
[Step 3/4] Cancelled by user
[03:49:06]
[Step 3/4] 5) Cancelled : NameSpace.1.2.FixtureSetup
[03:49:06]
[Step 3/4] Cancelled by user
[03:49:06]
[Step 3/4] 6) Cancelled : NameSpace.1.2.Fixture
[03:49:06]
[Step 3/4] Cancelled by user
[03:49:06]
[Step 3/4] 7) Cancelled : NameSpace.1.2.Fixture.TestCase
[03:49:07]
[Step 3/4] Cancelled by user
[03:49:07]
[Step 3/4] 8) Cancelled : NameSpace.1.2.Fixture.TestCase(with, parameters)
[03:49:07]
[Step 3/4] Test cancelled by user
[03:49:07]
[Step 3/4]    at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
[03:49:07]
[Step 3/4]    at System.Threading.TimerQueueTimer.Close()
[03:49:07]
[Step 3/4]    at System.Threading.TimerHolder.Close()
[03:49:07]
[Step 3/4]    at System.Threading.Timer.Dispose()
[03:49:07]
[Step 3/4]    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass3_0.<.ctor>b__1(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TimeoutCommand.cs:line 78
[03:49:07]
[Step 3/4]    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__1() in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 63
[03:49:07]
[Step 3/4]    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 73
[03:49:07]
[Step 3/4] Run Settings
[03:49:07]
[Step 3/4]     RuntimeFramework: net-4.0
[03:49:07]
[Step 3/4]     RunAsX86: True
[03:49:07]
[Step 3/4]     DisposeRunners: True
[03:49:07]
[Step 3/4]     WorkDirectory: C:\BuildAgent\...
[03:49:07]
[Step 3/4]     BasePath: C:\BuildAgent\...
[03:49:07]
[Step 3/4]     ImageRuntimeVersion: 4.0.30319
[03:49:07]
[Step 3/4]     ImageTargetFrameworkName: .NETFramework,Version=v4.7.2
[03:49:07]
[Step 3/4]     ImageRequiresX86: True
[03:49:07]
[Step 3/4]     ImageRequiresDefaultAppDomainAssemblyResolver: False
[03:49:07]
[Step 3/4]     NumberOfTestWorkers: 2
[03:49:07]
[Step 3/4] Test Run Summary
[03:49:07]
[Step 3/4]   Overall result: Failed
[03:49:07]
[Step 3/4]   Test Count: 44, Passed: 42, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 1
[03:49:07]
[Step 3/4]     Failed Tests - Failures: 0, Errors: 1, Invalid: 0
[03:49:07]
[Step 3/4]     Skipped Tests - Ignored: 1, Explicit: 0, Other: 0
[03:49:07]
[Step 3/4]   Start time: 2019-08-30 00:18:46Z
[03:49:07]
[Step 3/4]     End time: 2019-08-30 01:48:59Z
[03:49:07]
[Step 3/4]     Duration: 5413.265 seconds
```

**Comment by stevenaw** [comment] 2024-07-26 20:26
Apologies for coming in so late here.

I've tried this using using net48 and the latest version of the console runner (3.18.1) targeting the following framework versions:
- 3.12.0
- 3.14.0 (latest 3.x as of today)
- 4.1.0 (latest stable as of today)

With the following test
```csharp
[Test, Timeout(500)]
public void Test1()
{
    Thread.Sleep(1000);
}
```

and haven't been able to reproduce. All scenarios output the following:

```
1) Failed : TestProject1.Tests.Test1
Test exceeded Timeout value of 500ms
```

I'm going to close this as cant reproduce

**Closed by stevenaw** 2024-07-26 20:26 UTC
Labels: confirm
