### ISSUE TITLE
Test Id should remain valid so long as name doesn't change

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1336] opened 2016-03-10 19:01 UTC
Currently, the test id is only valid so long as the assembly is not rebuilt and reloaded. This is the minimum guarantee that the engine requires of all frameworks. In the case of the 3.0 framework, we should strengthen the id so that it takes in to account the assembly, class and method names and the arguments provided. If any of these change, the id will no longer be guaranteed. The id must still be unique to the test itself. See issue #1331 for some discussion about this.

**Comment by remcomulder** [comment] 2016-03-10 22:00
It would be great if we could leave the assembly itself outside the ID generation.

This is because an assembly can be rebuilt with a different version, or in a different location, and when this happens we don't want all the test IDs to change.  Probably it's OK to rely on the test runner to add an assembly prefix onto the ID if this becomes necessary.

Elements that I'm aware should be included in the ID are:

Namespace
Class name
Method name
Test case parameters

We'll probably need to think through how to handle tests that are generated dynamically (i.e. using TestCaseSource).  In this instance, it might be OK to simply use the sequence number of the test in much the same way as NUnit currently does.  Since the user can assign any name to each individual test case, it would be hard to tell them apart any other way ... though this would give us some strange results if the user were to remove a single test case from the generation (the IDs would get mixed up).  Would it perhaps be best to introduce an error case for when a user generates multiple tests with the same physical name?  They'd have no way of telling them apart in a UI either..

**Comment by CharliePoole** [comment] 2016-03-10 22:12
The status of the assembly is a difficult issue. NUnit can load various combinations of assemblies at any one time. Let's say I have loaded A.dll and B.dll, in that order. The current implementation would add prefixes of "1-" and "2-" for these. Now consider some other session where I load B.dll, C.dll and A.dll. So we need to at least identify assemblies by their file name, I think.

However, that may not be sufficient. Consider the NUnit build itself, where multiple copies of nunit.framework.tests.dll are built and stored in different directories. That might lead us to use the full path to the assembly, except that would break the case where we copy the assembly or rebuild it to another location. It definitely will take some thought.

Regarding TestCaseSource, I don't actually see the problem. I assumed we would use the actual arguments to the test, as generated by the source of the data, rather than the parameters, which would be used for the test representing the suite of test cases. The name assigned the test should have nothing to do with generating the id as far as I can see.

BTW, we don't call these "dynamic" in NUnit, because we have another, as yet unimplemented, concept for dynamically generated tests.

**Comment by remcomulder** [comment] 2016-03-11 01:27
In my use case, including the assembly file name (without directory) in the hash would be fine.  I think I can see how you might need to go further than this for other use cases ... could including the directory or version of the DLL perhaps be configurable?

I see what you mean in regards to TestCaseSource.  I forgot that NUnit calls this only to create the parameters, and these parameters can then be recognised during test discovery and thus added to the hash.  I think there may still be a use case here that could be a problem for us though.  Consider the following code:

```
using System;
using System.Collections.Generic;
using NUnit.Framework;

public class Fixture
{
    static IEnumerable<TestCaseData> TestData()
    {
        yield return new TestCaseData(new MyClass(1)).SetName("Hello");
        yield return new TestCaseData(new MyClass(2)).SetName("Hello");
    }

    [TestCaseSource("TestData")]
    public void Test1(MyClass parameter)
    {
        if (parameter.Value == 1)
            throw new Exception("First test");

        if (parameter.Value == 2)
            throw new Exception("Second test");
    }

    public class MyClass
    {
        public MyClass(int value)
        {
            Value = value;
        }

        public int Value { get; private set; }
    }
}
```

In this above case, we have two tests that are generated using TestCaseSource, each with the same visible name and relying on a user defined type for their only point of difference (the parameter).  To handle this with a generated ID, we would need some way to uniquely hash MyClass consistently across discovery runs.  I grant that this is a bit of an edge case.  I guess there's a few ways we could solve it ... perhaps use some kind of sequence-generated fallback method or push the problem to the user to make sure.ToString() always returns something unique?

**Comment by CharliePoole** [comment] 2016-03-11 01:41
Yes, I see your point. However, it does seem that any hash-based algorithm we use will
1. Fail in situations like this, where the current method already fails
2. Actually work in some other situations, where the current method currently fails
3. Work as well or better in all situations where the current method already works.

Maybe that's as good as it gets. :-)

**Comment by remcomulder** [comment] 2016-03-11 04:19
I agree that it's definitely an improvement over the original approach.  I wonder what the best way would be to handle the above scenario.  Should we kick up an error to the user, so they know what's going on?  If we create the two test cases with the same identifier, we're likely to see some inconsistent results when attempting to run the tests.  NCrunch does already warn the user when it sees two tests with the same ID, but I'm thinking in regards to other runners here .. and the NUnit GUI.

**Comment by rprouse** [comment] 2021-05-01 00:50
Closing as duplicate of #2771

**Closed by rprouse** 2021-05-01 00:50 UTC
Labels: is:feature, pri:high
