### ISSUE TITLE
CollectionAssert count/length

### ISSUE THREAD

**Issue by Jameskmonger** [nunit/nunit#1310] opened 2016-03-03 13:50 UTC
It would be good to be able to use `CollectionAssert` to directly assert the size of a collection.

Current syntax like this:

    Assert.AreEqual(someCollection.Count(), 1);

Could be replaced by this:

    CollectionAssert.Count(someCollection, 1);

**Comment by CharliePoole** [comment] 2016-03-03 15:28
I'd be inclined  not to do this...

1. CollectionAssert is a legacy assert and we have been limiting ourselves to fixing bugs up to now.

2. It was designed to match MsTest, which is the reason it exists.

In light of item 2, I suppose we could check if MsTest has added anything new recently.

**Comment by CharliePoole** [comment] 2016-03-16 19:27
Nobody has commented further on this for two weeks. Shall we close it?

**Comment by rprouse** [comment] 2016-03-16 20:49
I agree, I am going to close as won't fix.

**Closed by rprouse** 2016-03-16 20:49 UTC
