### ISSUE TITLE
Run the tests parallel

### ISSUE THREAD

**Issue by pmadhuyadav** [nunit/nunit#985] opened 2015-11-04 08:55 UTC
HI,

am using Nunit.3.0 rc, to run tests parallel

while running the tests using  [Parallelizable(ParallelScope.Children)] at test method, test are running one by one

please suggest me how to run the tests parallel one each another, below is my code 

namespace NunitTestProject
{
    [TestFixture]
    [Parallelizable(ParallelScope.Fixtures)]
    public class TestSet001
    {
        [Test]
        [TestCase("2")]
        [TestCase("3")]
        [TestCase("4")]
        [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test001(string dataRow)
        {
          SeleniumTest.RunSeleniumTestInLocalChrome(dataRow);
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test002()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test003()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test004()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test005()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test006()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test007()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test008()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test009()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test010()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test011()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }

        [Test]
     [Parallelizable(ParallelScope.Children)]
        public void TestSet001Test012()
        {
            SeleniumTest.RunSeleniumTestInLocalChrome();
        }
}

**Comment by CharliePoole** [comment] 2015-12-05 05:04
Duplicate of #164

**Closed by CharliePoole** 2015-12-05 05:04 UTC
Labels: closed:duplicate
