### ISSUE TITLE
Add ToleranceMode that measures significant digits

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#1094] opened 2015-11-30 09:06 UTC
From discussion in #1029.

When one of the comparands is 0.0 ToleranceMode.Ulps the number of representable numbers to the other comparands can be very high making it unsuitable in some cases. A variation of Ulps that is defined as measuring significant digits instead would be useful. It'd be a variation of Ulps that has special handling for the case of one of the comparands being 0.0. 

Something like the following.

``` csharp
        [Test]
        public void DoubleEqualityWithUlps2()
        {
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(0.0, 1e-100, 1));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(0.0, 1e-20, 1));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(0.0, 8e-15, 90));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(123, 0, 1));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(123, 123, 1));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(1.0, 0.9999999999999995, 1));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(1.0, 0.9999999999999995, 5));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(1.0, 0.99999999999999, 89));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(1.0, 0.99999999999999, 90));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(1.0, 0.9999999999999, 900));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(1.0, 0.9999999999999, 901));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(double.NaN, double.NaN, 1));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(-2, 2, 1));

            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(0.0, -1e-100, 1));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(0.0, -1e-20, 1));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(0.0, -8e-15, 90));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(-123, 0, 1));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(-123, -123, 1));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(-1.0, -0.9999999999999995, 1));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(-1.0, -0.9999999999999995, 5));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(-1.0, -0.99999999999999, 89));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(-1.0, -0.99999999999999, 90));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(-1.0, -0.9999999999999, 900));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(-1.0, -0.9999999999999, 901));
            Assert.IsTrue(FloatingPointNumerics.AreAlmostEqualUlps2(double.NaN, double.NaN, 1));
            Assert.IsFalse(FloatingPointNumerics.AreAlmostEqualUlps2(2, -2, 1));
        }

        public static bool AreAlmostEqualUlps2(double left, double right, long precision)
        {
            if (precision <= 0)
                throw new ArgumentOutOfRangeException("precision", precision, "Must be greater than zero.");

            DoubleLongUnion leftUnion = new DoubleLongUnion();
            DoubleLongUnion rightUnion = new DoubleLongUnion();

            leftUnion.Double = left;
            rightUnion.Double = right;

            ulong leftSignMask = (leftUnion.ULong >> 63);
            ulong rightSignMask = (rightUnion.ULong >> 63);

            ulong leftTemp = ((0x8000000000000000 - leftUnion.ULong) & leftSignMask);
            leftUnion.ULong = leftTemp | (leftUnion.ULong & ~leftSignMask);

            if (leftUnion.ULong == 0)
                return Math.Abs(right) < precision * 1e-16;

            ulong rightTemp = ((0x8000000000000000 - rightUnion.ULong) & rightSignMask);
            rightUnion.ULong = rightTemp | (rightUnion.ULong & ~rightSignMask);

            if (rightUnion.ULong == 0)
                return Math.Abs(left) < precision * 1e-17;

            if (leftSignMask != rightSignMask)
            {
                if (Math.Abs(leftUnion.Long) > precision || Math.Abs(rightUnion.Long) > precision)
                    return false;
            }

            return (Math.Abs(leftUnion.Long - rightUnion.Long) <= precision);
        }
```

**Comment by CharliePoole** [comment] 2015-11-30 21:44
Would you explain what is meant by the third argument?

How would you see this expressed in our fluent syntax... that is...
    .Within(n).What?
How would you explain it in the docs, without confusing users?

Lots of question marks, you see!

**Comment by thriolsson** [comment] 2015-12-01 07:58
I think that the original FloatingPointNumerics.AreAlmostEqualUlps is fine except that it does not work for the special and common case when the comparand is zero. This is a pity since it makes it much less useful.
The problem is that the number of "ulps" between any number and zero is undefined.
One pragmatic way to solve that would be to detect and handle this special case by 
if (left == 0.0)
{
   left = 1
   right = right + 1
}

**Comment by CharliePoole** [comment] 2015-12-01 17:00
But FloatingPointNumerics is internal and not accessed by users. Users write something like...
    Assert.That(x, Is.EqualTo(y).Within(2).Ulps);
and that causes a call to the method.

How do you propose users trigger a call to AreAlmostEqualUlps2? Or are you proposing it to replace the original?

Perhaps I am confused because in #1029 you talked about introducing a new kind of tolerance, which led me to expect something like .Within(2).NewKind.

**Comment by appel1** [comment] 2015-12-01 18:02
I thought it would be better to start with what we want to accomplish and not what to call it in the public interface. 

I thought that we couldn't change the meaning of Ulps since it'd be a breaking change for those that rely on it to be always false when comparing with 0. 

.Significant, .UlpsThatWorksWithZero or something perhaps. Significant because it'd be significant digits in the binary sense.

**Comment by appel1** [comment] 2015-12-03 10:50
For our needs having Ulps handle if any of the comparands is zero would be perfect. But I can't be sure that there are no use cases where it makes sense to adhere more strictly to the current definition, that comparing with zero is always(?) false. 

.BinaryDigits would be fine as well but as you wrote it might be confusing since the difference is so minute.

**Comment by rprouse** [comment] 2020-05-18 18:26
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 18:26 UTC
Labels: is:idea
