### ISSUE TITLE
Timeout value not resetting on Retry of failed test

### ISSUE THREAD

**Issue by db798** [nunit/nunit#2786] opened 2018-03-28 19:13 UTC
Not sure if this has been raised before, could find a similar issue. 

I have a test with both Retry and Timeout attribute but when a test is retried the timeout isn't being reset to 0.

```
using NUnit.Framework;
using System;
using System.Threading;

namespace RetryTimeoutTest
{
    public class Class1
    {
        private static int count1 = 0;
        private static int count2 = 0;

        [Test]
        [Retry(3)]
        public void Test1()
        {
            count1++;
            Console.WriteLine(count1);

            Thread.Sleep(2000);

            if (count1 < 2)
            {
                Console.WriteLine("In failing assert");
                Assert.True(false);
            }
            else
            {
                Console.WriteLine("In passing assert");
                Assert.True(true);
            }
        }

        [Test]
        [Retry(3)]
        [Timeout(3000)]
        public void Test2()
        {
            count2++;
            Console.WriteLine(count2);

            Thread.Sleep(2000);

            if (count2 < 2)
            {
                Console.WriteLine("In failing assert");
                Assert.True(false);
            }
            else
            {
                Console.WriteLine("In passing assert");
                Assert.True(true);
            }
        }
    }
}
```

**Expected Result:** Both tests to pass after a retry

**Actual Result** Test1 passes as expected but Test2 fails with message _Test exceeded Timeout value of 3000ms_. 

It looks like the timeout isn't being reset when the test starts the second time, is this the expected result or should a reset be performed for each retry of the tests. 

_**ps** sorry about the code sample, doesn't look to be formatting everything_

_@ChrisMaddock edit: fixed formatting_

**Comment by ChrisMaddock** [comment] 2018-03-28 19:16
This sounds to me like an edge case we haven't thought of. I agree I'd expect it to work as you say.

Will just wait for someone else on @nunit/framework-team to confirm!

**Comment by jnm2** [comment] 2018-03-28 21:09
Yes, I can't think of any good way to use timeouts with retries the way it currently.

We'll have to make sure the timeout command wraps the test command before any attributes get a chance to wrap it. Would that change any behavior in combination with other attributes?

**Comment by CharliePoole** [comment] 2018-03-28 22:12
I think you can consider this confirmed. Rationale: Timeout works at the WorkItem level. Retry works at the command level. Since the work item executes the command chain, the single timeout value applies to the aggregate of the repetitions. 

Changing this would probably mean re-implementing timeout at the command level, since attributes don't generally get to play at the WorkItem level.

**Comment by DaiMichael** [comment] 2018-05-02 20:07
If you'll let me... I'll have a crack at this and look at what @CharliePoole has suggested.

**Comment by CharliePoole** [comment] 2018-05-03 17:59
That's precisely the kind of thinking that went into the original V2 implementation. It failed because assigning an arbitrary mapping like that requires global knowledge of all possible attributes, including those created by users (or us) in the future. It doesn't suit an implementation, which is by its very nature, a decentralized aggregation of unconnected (attribute) nodes.

OTOH if we say: here are the possible __kinds__ of wrappers you can add and things within each category may be applied in __any order__ then we force authors to create attributes that are aware of the possibility that other attributes may pile on top of them or be found beneath them. They have to write the wrapper code in a more robust way in order for all combinations to work.

A categorization of wrappers by what they want to wrap makes the most sense to me. We have now...

1. Wrappers that wrap a test method
2. Wrappers that wrap the "whole" test (setup+method+teardown)
3. Wrappers that repeat things (proposed)

I understand the urge to do something extremely general. It's the way we were all trained to think. It's also the way that many of us deliberately cast aside in the 90s, when we saw it wasting more time in the present than it saved in the future.

This is something that needs design, obviously. But it doesn't need to be designed to accommodate future needs that may come up. We'll never have to back out something we didn't implement!

My design for wrapping tests (in my head) was "Create categories of things to be wrapped." My implementation was "Create two categories right now and see if more are needed later." If it were me, I'd simply follow up by adding another category before giving up on the entire concept.

**Comment by DaiMichael** [comment] 2018-05-03 19:52
I get the gist of what is being said, I will take a look at the option @CharliePoole is suggesting.

I have created a couple of unit tests as per @ChrisMaddock and I will suplement them when I get going. I've tweeked them to have short `Sleep()` as is.

I have created a branch issue-2786 (on my fork) as well which I'll work off.

I'll keep everyone posted!

**Comment by CharliePoole** [comment] 2018-05-03 20:45
@DaiMichael My suggestion, of course, involves a moderately significant internal change to how NUnit applies attributes to tests. We'll point you to the places where you may need to make changes. As a starter, you'll see that the wrapping of commands takes place in SimpleWorkItem.cs

Fair warning... because this is a fairly important change, expect lots of reviewing. 😈

**Comment by DaiMichael** [comment] 2018-05-06 19:43
Apologies for radio silence, I didn't run for the hills, busy in work and it is unbelieveably not raining in the UK so been riding my bike!

@CharliePoole Looking forward to it 😩 😉 ...

Here is a brief investigation with Charlies suggestion 

```
// Repeatable rather than Repeated as a retry doesn't necessary 
// repeat as it is optional on outcome. Happy to go 
// with Charlie suggestion if not liked?
interface IRepeatableTest { }

// Add interface to commands
public class RetryCommand : DelegatingTestCommand, IRepeatableTest
public class RepeatedTestCommand : DelegatingTestCommand, IRepeatableTest

// Need to do a bit more debugging / investigation for full solution. But...
// Change the command order in regards to 
// IRepeatableTest (i.e. repeat after timeout command) to following method.
SimpleWorkItem.MakeTestCommand()
```
If this seems like a fair way to proceed, I will on this basis and flag any questions or issue / gotchas ?

**Comment by jnm2** [comment] 2018-05-06 21:40
> I understand the urge to do something extremely general. It's the way we were all trained to think. It's also the way that many of us deliberately cast aside in the 90s, when we saw it wasting more time in the present than it saved in the future.

I agree with this principle and it may well be the case here. I'm not looking for something general so much are trying to get rid of the feeling that it's arbitrary to make repetition the fundamental thing instead of making temporal duration a fundamental thing. But it's probably the easiest design. 👍

`IWrapTestRepeat` seems more like the naming style we moved toward with `IWrapSetUpTearDown`.

@CharliePoole Are you thinking you'd implement this if you wanted to hook the start and end of each repetition, versus the other two which hook the start and end of the outer parts of the lifecycle?

**Comment by DaiMichael** [comment] 2018-05-08 20:51
@jnm2 @CharliePoole 

I have a working solution, with tests that uses Charlie's interface idea and I used Joseph's naming `IWrapTestRepeat`. It will also makes the `Test` which has both 'RetryAttribute` and `RepeatAttribute` have a warning with a message.

It was relatively straight forward, so I hope there is nothing controversial in there.

Code is checked in on my branch <https://github.com/DaiMichael/nunit/tree/issue-2786>, shall I do a Pull Request?

**Comment by jnm2** [comment] 2018-05-08 20:59
> Code is checked in on my branch, shall I do a Pull Request?

As soon as you would like reviews, yes please!

**Comment by CharliePoole** [comment] 2018-05-08 21:16
@jnm2 This is definitely a nit, but here goes...

Current naming pattern for this family of interfraces is IVerbObject, where Verb and Object describe what the interface does in the construction or execution of a test.

IApplyToTest applies changes to the test itself
IApplyToContext applies changes to the test execution context
IWrapTestMethod wraps the execution of a test method
IWrapSetUpTearDown wraps the setup and teardown
IRepeatTest repeats the test execution

The "-able" convention for interfaces is a good one - it's just not the one we have been using  for attributes.

IWrapTestRepeat would appear to mean that the interface wraps the repetition of a test rather than actually repeating the test.

**Comment by jnm2** [comment] 2018-05-08 22:09
> IWrapTestRepeat would appear to mean that the interface wraps the repetition of a test rather than actually repeating the test.

Oops—and that's what I was accidentally envisioning. `IRepeatTest` is better because it is responsible to cause the repetition.

**Comment by CharliePoole** [comment] 2018-05-09 22:31
@DaiMichael Has a nice fix of this issue in PR #2849. Aside from the basic fix, there's the question of issuing a warning if multiple `IRepeatTest` attributes are used. I think we need to discuss what we want to happen and then how to implement a warning, if that's what we decide. This is a kind of warning we have never had before, so how we do it will create some kind of precedent.

WHAT WE MIGHT DO

There are a range of options...

1. Do nothing... document that multiple repeat attributes together may interfere with one another and are not recommended. User deals with any mess they create. This is what we do with multiple combining attributes, for example, like `Combinatorial` and `PairWise`.

2. Create some kind of Warning status which shows up as a warning result on the test if it otherwise succeeds.

3. Use an actual warning (Assert.Warn) that will combine with any other warnings and errors that show up.

4. Mark the test as invalid and don't allow it to run at all.

On top of all this, I think we need to ask whether this is something NUnit should do centrally or each repeating attribute should do on its own if it can't work with other repeating attributes.

HOW TO WARN

If we decide to warn, I kind of think it should use the standard warning facility. That way, other warnings or failures will show up as well.

**Comment by DaiMichael** [comment] 2018-05-10 08:38
I'm leaning towards option 4 or a derivative (Skip with warning etc...).

Whilst I accept generally we can't protect the overall usage of the framework against every eventuality, with repeatable tests it could cause problems and might be worth guarding against. Obviously someone could do `[Retry(99999999)]`  but that is their problem (although we could but a limit in!). But if we get a race condition between 2 repeatable attributes (one could be a custom written one) that only manifests itself on a server and not locally, this might be hard to discover plus randomly hang up a server/build/process with no helpful message. By making the test Skipping/Invalid/etc.. and warning at least we don't get to a situation where issues might occur. We might save ourselves further issues being raise here! :wink:

My 2 cents..

**Comment by jnm2** [comment] 2018-05-16 02:28
I think we should mark as invalid (4) and do this centrally. This blocks the area off, giving us freedom to do whatever we want without fear of backwards compatibility down the road is someone ever asks for the ability to combine repeating attributes.

**Comment by DaiMichael** [comment] 2018-05-16 20:10
Okay, will proceed with this.

**Closed** 2018-09-06 23:53 UTC
Labels: is:bug, pri:normal
