### ISSUE TITLE
NUnit doesn't seem to be able to deal with `PublicSign`

### ISSUE THREAD

**Issue by maettu-this** [nunit/nunit#4681] opened 2024-04-07 10:54 UTC
NUnit 3.14.0 + TestCentric 1.6.4 as well as reproduced with latest TestCentric 2.0.0-beta4.

Running NUnit on [SignatureIssue.zip](https://github.com/nunit/nunit/files/14896837/SignatureIssue.zip) results in:

_original German error message_
System.IO.FileLoadException : Die Datei oder Assembly "InvertedTomato.Crc, Version=1.3.6.0, Culture=neutral, PublicKeyToken=db609c8c3d9a5f69" oder eine Abhängigkeit davon wurde nicht gefunden. Die Signatur mit starkem Namen konnte nicht überprüft werden. Die Assembly wurde möglicherweise geändert oder verzögert aber nicht vollständig mit dem richtigen privaten Schlüssel signiert. (Ausnahme von HRESULT: 0x80131045)

_translated to English_
System.IO.FileLoadException : The file or assembly "InvertedTomato.Crc, Version=1.3.6.0, Culture=neutral, PublicKeyToken=db609c8c3d9a5f69" or a dependency could not be found. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Ausnahme von HRESULT: 0x80131045)

Root cause is [`<PublicSign>true</PublicSign>`](https://github.com/invertedtomato/crc/blob/6894b41c9c96ebf030e99530591e1bf607e178df/Library/Library.csproj#L29C8-L29C38) documented at [C# compiler options for security](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/security). NUnit works fine when "fully signing" the assembly, i.e. remove the `<PublicSign>true</PublicSign>` from the project configuration. However, [InvertedTomato.Crc](https://github.com/invertedtomato/crc) is published including `<PublicSign>true</PublicSign>`, i.e. the pubished assembly cannot be used with NUnit.

To work around the issue, [my project](https://sourceforge.net/p/y-a-terminal/) currently uses a "fully signed" build of the assembly. Note that [reducing the strong name key to the Microsoft default width of 1024-bit](https://github.com/invertedtomato/crc/pull/14) also did not solve the issue.

**Comment by stevenaw** [comment] 2024-04-15 19:49
@maettu-this Are you using .NET Framework or .NET Core for your project?
I see this same error as you when trying to run the `InvertedTomato.Crc` test suite itself on .NET Framework 4.8, which uses xunit. Removing the `<PublicSign>` there then also allows the net48 test target to work.

You can see my branch here where I've added the new test runtime target and removed the `<PublicSign>` in separate commits
https://github.com/invertedtomato/crc/compare/master...stevenaw:crc:net48-test-target?expand=1

**Comment by stevenaw** [comment] 2024-04-15 20:31
While I haven't found any documentation on it, I believe this could be a compatibility issue between .NET Framework and `<PublicSign>`. I've submitted this PR to `InvertedTomato.Crc` to try to fix the root issue: https://github.com/invertedtomato/crc/pull/15

**Comment by stevenaw** [comment] 2024-04-15 20:49
I found a write-up here: https://github.com/dotnet/runtime/blob/main/docs/project/public-signing.md and there are indeed some known issues on .NET Framework. Some of the scenarios like `partial trust` have since been removed in NUnit 4 so it's _possible_ that it will work there but I haven't tested it

> Known issues when debugging and testing public signed assemblies on .NET Framework:
> - You will not be able to install the assembly to the Global Assembly Cache (GAC)
> - You will not be able to load the assembly in an AppDomain where shadow copying is turned on.
> - You will not be able to load the assembly in a partially trusted AppDomain
> - You will not be able to pre-compile ASP.NET applications
> - You may not be able to load the assembly if the app.config file specifies <configuration>/<runtime>/<NetFx40_LegacySecurityPolicy enabled="true" />

**Comment by stevenaw** [comment] 2024-04-16 00:30
I'm going to close this.

I haven't been able to reproduce outside of the CRC repo where a fix for the issue itself has also now been fixed.
I've tried reproducing this on a standalone app using InvertedTomato.Crc@1.3.6 and NUnit 3.14 consumed from NuGet and both net48 and net8 as TFMs and it seems to pass whether I sign the test assembly or not. I've run them both in Visual Studio and from CLI via `dotnet test`.

https://github.com/nunit/nunit.issues/tree/main/Issue4681

@maettu-this Can you please see if the latest merged PR to `InvertedTomato.Crc` helps you?

**Closed by stevenaw** 2024-04-16 00:30 UTC
Labels: Investigate

**Comment by maettu-this** [comment] 2024-04-20 19:08
@stevenaw thanks for evaluating. And sorry for not responding earlier, been off for a week. And yes, I am still on .NET 4.8 for a bunch of reasons, where `AppDomain` migration is one of them.

I'll check again once a new release of `InvertedTomato.Crc` becomes available. If still an issue on .NET 4.8 I'll consider requesting separate builds of `InvertedTomato.Crc` for .NET Framework and .NET Standard 2.1+.
