### ISSUE TITLE
Unable to find version '2.6.4' of package 'NUnit'.

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/nunit#776] opened 2015-08-17 14:30 UTC
as of 
commit f23c6a0c27c37472e12dfc6703998fbab7ed6505
Date:   2015-08-16T14:27:06-07:00

        # nuget restore nunit.linux.sln
        Unable to find version '1.1.10' of package 'Microsoft.Bcl'.
        Unable to find version '1.0.168' of package 'Microsoft.Bcl.Async'.
        Unable to find version '1.0.21' of package 'Microsoft.Bcl.Build'.
        Unable to find version '2.6.4' of package 'NUnit'.

Of course it can't find NUnit in local repository, because I am just building it for the first time

Isn't it better to add project dependency instead of package dependency?

**Comment by CharliePoole** [comment] 2015-08-17 14:36
The package dependency on NUnit 2.6.4 is not to the framework project being built, but to the legacy 2.6.4 framework used by the addin that handles tests written against 2.6.4. NUnitV2 is a completely separate project from NUnit 3.0.

Odd. This seems to be the result of a change we just merged, which worked in our Travis build.

@chris-smith-zocdoc Did you modify the linux solution as well?

@ArsenShnurkov How are you running this build?

**Comment by CharliePoole** [comment] 2015-08-17 16:43
@ArsenShnurkov You posted info on the gentoo/dotnet project that included a reference to your build script. It seems to me - if I understand correctly - that you are building NUnit yourself, using your own script instead of ours, and it isn't working. Is that right?

If so, please explain why this is an NUnit bug? I'm not yet saying it isn't, but it seems to be your own script that isn't working.

It may help us understand if you tell us what you are trying to accomplish.

**Comment by ArsenShnurkov** [comment] 2015-08-17 16:57
> Is that right?

not at all. I looked into your ./build,
https://github.com/nunit/nunit/blob/master/build
and copied it into mine ebuild (it actually calls nuget restore, mine does the same, but on nunit.linux.sln).
I don't see how this differs from your main line.

>  please explain why this is an NUnit bug?

This is not exactly a bug, because you are trying to keep your trade secrets,
you want to be the only builder of this project and don't want to explain,
how to build that for all people in the world.
Of course you have no obligation to explain anything,
so you are right, that I should figure out this myself, 
If I want provide the solution for all people who use portage package manager
(which are second sort people from your point of view).

**Comment by ArsenShnurkov** [comment] 2015-08-17 17:20
Just for completeness, here is the result of your script:

        # ./build
        ./build: line 2: ./tools/nuget.exe: cannot execute binary file: Exec format error
        XBuild Engine Version 12.0
        Mono, Version 4.0.3.0
        Copyright (C) 2005-2013 Various Mono authors
        
        Build started 8/17/2015 8:18:27 PM.

**Comment by CharliePoole** [comment] 2015-08-17 17:38
You are pretty off-base here. Open source is not helped by people who think that their "brand" of open source is the only one that's valid. You are sounding like one of those folks and I wish you would think two or three times before jumping to conclusions. You are also making statements about my "point of view" which you cannot possibly know. Talking about what you imagine is in other folks' heads is usually not a good sign.

NUnit is an open source project. It doesn't have trade secrets. We help everyone who asks for us to the extent they make it easy for us to help by explaining what they are trying to do. IF you are really working in open source you should know that. We give a lot of extra help to other open source projects, as many folks could tell you. We have to know who we are talking to before we go that extra distance and we only know you from these posts.

You have said little, but based on what you wrote you appeared to be working on a proprietary corporate project with strong security concerns. You said nothing about open source project or about Gentoo. I tried to answer your questions of course, but there was no reason to give you the extra effort you seem to expect as a right.

NUnit is already built by many people. For one thing, almost every Linux distro builds NUnit. We have spent many days work to help people doing that but they have to show us they are credible first.

Anyway...

You indicated you want to write an ebuild file according to gentoo philosophy. I have a vague idea what that is, but no more. Do I need to know more to understand your problem?

Your gist seems to suggest you are building in a mono environment that does not support CLR 2.0. Our special version of Mono.Addins is modified to work under 2.0. That's why you are getting duplicate definitions. Since we are in the process of dropping Mono.Addins, my suggestion is that you wait.

I don't understand why nuget.exe won't run on your system. It's the most recent download unless our repo has gotten messed up. I assume you are using the latest master.

**Comment by ArsenShnurkov** [comment] 2015-08-17 17:57
https://github.com/nunit/nunit/issues/778

**Comment by CharliePoole** [comment] 2015-08-17 18:54
Is this a duplicate of #778?

**Comment by ArsenShnurkov** [comment] 2015-08-17 18:55
no, this issue is about dependencies,
and that issue is about error checking in scripts

**Comment by CharliePoole** [comment] 2015-08-17 19:06
In that case @chris-smith-zocdoc please give #778 priority, since we know what the problem is. We should fix it asap if you can. 

I still don't understand this issue. It's clear that the restore is working perfectly well on our Travis build, which I think uses Ubuntu. I'll be at home today with my own Linux machine, so I can try it there as well, now that #125 is fixed.

**Comment by CharliePoole** [comment] 2015-08-17 19:08
@ArsenShnurkov Please comment on #778 regarding what error checking you would like to see in which of our scripts. I interpreted the problem as build script simply missing the mono prefix, which we always use for managed programs.

**Comment by ArsenShnurkov** [comment] 2015-08-17 19:12
I make assumption that online repository is available, which doesn't true in my case. I should be able to emerge all ebuilds one-by-one according to direct acyclic graph (DAG) of dependencies.
I probably will cut all test projects and 2.0 compatibility code with patch, and replace target framework versions to 4.0 to get the local trusted gentoo package built.

In general it is illogical, that program uses itself as external dependency, when it's code is available in the same repository.

Yes, I will need to build other packages first, to put them to local repository, and they will be restored with nuget restore command from your script. But I can't do the same for the package being built.

**Comment by CharliePoole** [comment] 2015-08-17 19:34
@ArsenShnurkov You may be right about online repository availability. However, this is a very specialized situation and I think we have to get the new approach working generally before worrying about how to build it in the situation you describe. Frankly, I don't think our build is ready for use by you in your situation... that's why we call it non-production, non-stable, beta, etc.

However, you missed something crucial. You said "it is illogical that program uses itself as external dependency, when it's code is available in same repository." Your statement is right, but your facts are wrong. NUnit 2.6.4 is not in the same repository but in the NUnitV2 repo. The two programs are incompatible underneath, even though they use similar user interfaces like attributes and assertions.

Many users will want to install both of them on their systems. Some will want 2.6.4 only. Some will want 3.0 only. Some will want the 2.0 compatibility addin and some will not.

Our current build mixes everything together. As I told you when you first posted about this, we don't plan to retain this structure (or unstructure) when we go to production. Making your private installer depend on the current structure is a guarantee that you will have to change it. As a minimum, for my own work on Linux, I will be splitting framework, engine, console, gui and each addin into a separate package. The current code has only three addins. The final release will probably have more. Some features that are now internal will probably become addins. IOW, you are aiming for a moving target.

Back to the topic: How would you recommend we structure our dependencies to avoid the necessity for an external build. My own assumption was that anyone concerned could easily use a local source of nuget packages. Doesn't that work for you?

**Comment by ArsenShnurkov** [comment] 2015-08-17 21:01
I will try to create two ebuild based on the same tarball. One with Addins, and another with the rest of code.

My ebuilds are anchored to sha1 of specific commit, so they will work for me for next 20 years, or as long as I will keep my gentoo source base archive. Gentoo is rolling distribution, so it doesn't matter for me at which point of time to anchor. So, i don't worry that the work is not finished - I just should know what is possible and what is not at my version, and I will learn that with time. And I can make a new version anytime, ofcourse, or use a vesion created by followers.

Here the list of existing versions (they are all was not marked as stable, lates one is 2.5.3):
http://gpo.zugaina.org/dev-dotnet/nunit
but my requirements deffers (I need to control debug info for stacktraces, and I need local nupkg's), 
that is why I am writing a new one.

Having two separate packages for Addins and another code should allow me to resolve this dependency thing.

> How would you recommend we structure our dependencies

I don't know, because I havn't tried yet. For now I think I would be good to have separate github project for addins.

**Comment by CharliePoole** [comment] 2015-08-17 23:59
The problem I was thinking of is independent of version. It has to do with package content. If the package "nunit" contains the console runner when it comes from one source but does not from another source, that's very confusing to users, especially to users who work on multiple platforms. Of course, we have already dealt with that problem, when we changed the meaning of "nunit" at NuGet.org. Personally, I feel that the Debian guys subdivide it in a much more satisfactory way - better than we do actually - and we will probably move in that direction.

However, so long as you are consistent and it's a private build that works for you, I guess no harm is done.

Regarding stable versions: For NUnit 2.x, all our numbered binary versions are stable. It's only those with suffixes like -beta, -alpha, etc. that are unstable, as well as anything built from source without a version tag.

For NUnit 3.0, it will be much cleaner. We are planning to use odd/even minor versions to indicate unstable/stable. For now, it's all unstable because it's all alpha or beta. (We publish announcements telling people not to use it for production, so we are serious about beta.) 

That said, the current beta is probably stable for folks using it to run tests but not for folks who want to build other things that depend on our code.

We have a single GitHub project right now because we are building three independent components that require frequent API changes. Keeping them in separate projects proved to be too hard for the devs. If we split the packaging, we will split the repos at a later stage.

Right now it's convenient to keep addins in the same project because we are working on the addin API. Jumping between different repos has proven inconvenient in the past. Most likely we will split out at least some addins before the final release. I say only "some" because some basic features we want everyone to have may actually be implemented as addins.

I'm still wondering if there shouldn't be some option in the build script to let you build using known binaries rather than importing a nuget package.

**Comment by CharliePoole** [comment] 2015-08-18 00:03
I thought I commented on this, but I can't find it anywhere, so exuse any repetition...

"Yes, I will need to build other packages first, to put them to local repository, and they will be restored with nuget restore command from your script. But I can't do the same for the package being built."

The NUnit 2.6.4 nuget package is **not** the package being built. It's the old version of NUnit, which is used as a part of the addin that runs NUnit 2.x tests. The version used should be fixed at 2.6.4.

**Comment by ArsenShnurkov** [comment] 2015-08-18 07:53
"does not from another source"

here is a list of installed files:
https://gist.github.com/ArsenShnurkov/1d94c37ee9c0a03cbcb1

"so long as you are consistent"

I can't speak for all users of gentoo, funtoo, sabayon, calculate and other distributions from this list:
https://wiki.gentoo.org/wiki/Distributions_based_on_Gentoo
they will probaby receive this ebuild (in a ~month), because gentoo/dotnet is official overlay
They can distribute their locally built version of nupkg, and I can't control them.

"2.6.4 is another package"

Not in terms of gentoo (DRY principle and so on). It is possible to do what you recommend (make 2 different versions of package and make a dependency between them), but I don't see that as a right thing.
And gentoo have another definition (criterias) for package stability. Ebuild is stable, when it is possible to use it with ALL other packages in tree (otherwise it keeps marked unstable).

**Comment by CharliePoole** [comment] 2015-08-18 12:14
Very confusing. First you say it's private, now it's "official." Very well...

Here are the problems I see...

1. You are distributing an unfinished beta version of NUnit 3.0 but you are saying it is stable and leaving out the beta.

2. Your packaging will not match ours in the sense that you will have a single package that includes more than we include in the nunit package.

3. We treat NUnit and NUnitV2 as separate programs, with separate packages. You treat them as two versions of the same package.

All of this is potentially confusing to your community and it's not the way other distros work with upstream developers.

**Comment by CharliePoole** [comment] 2015-08-18 12:18
I'm closing this issue since the dependency problem seems to be because @ArsenShnurkov is treating NUnit 2.6.4 as the "same package" as NUnit 3.0, at least as far as I can understand the explanation. It's very likely that we still have other problems with the Linux build, but this particular issue isn't an actual bug but a difference in points of view.

**Closed** 2015-08-18 12:18 UTC
Labels: is:bug, status:confirm
