### ISSUE TITLE
COM object that has been separated from its underlying RCW cannot be used.

### ISSUE THREAD

**Issue by magol** [nunit/nunit#4060] opened 2022-03-10 22:09 UTC
I'm creating tests for a wrapper around a COM API. It take some time to initialize the connection, so I want to save the COM object between each test. For some COM functions, it is important that it is in STA and that the COM object is created in the same thread as the calling code.

I have test with code like this:

```C#
    [Apartment(ApartmentState.STA)]
    public class Test
    {
        private MyComObject _myComObject;

        [Test]
        public void Foo1Test()
        {
            var value = _myComObject.Foo1;
            // ...
        }

        [Test]
        public void Foo2Test()
        {
            var value = _myComObject.Foo2;
            // ...
        }


        [OneTimeSetUp]
        public void Init()
        {
            _myComObject = new MyComObject();
            // ...
        }
    }
```

If I only run only one test, it works. But if I run all tests in the class, I get following exception:

> System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used.

What am I doing wrong?

**Comment by manfred-brands** [comment] 2022-03-11 06:07
This seems to be a duplicate of #3740 (and #4012) and similar to #3500.

**Comment by magol** [comment] 2022-03-11 09:06
I have also tested with this code with the same result

```C#
    [Apartment(ApartmentState.STA)]
    public class Test
    {
        private MyComObject _myComObject;

        [Test]
        public void Foo1Test()
        {
            var value = BuildObject().Foo1;
            // ...
        }

        [Test]
        public void Foo2Test()
        {
            var value = BuildObject().Foo2;
            // ...
        }

        private MyComObject BuildObject()
        {
            if(_myComObject == null)
            {
                _myComObject = new MyComObject();
                // ...
            }
            return _myComObject
        }
    }
```

In this case, the building of the object is run in the same context as the tests. But it dosn't work.

**Closed** 2022-03-26 22:28 UTC
