### ISSUE TITLE
When CollectionAssert.AreEqual do compare each element, it will ignore the IEquatable of the element too

### ISSUE THREAD

**Issue by LiyueWang** [nunit/nunit#2271] opened 2017-06-20 18:32 UTC
With the code changes #2118 for [Issue2097](https://github.com/nunit/nunit/issues/2097), the test below still will fail, since when the `NUnitEqualityComparer` does each item comparison, the property `compareAsCollection` is still `true`,  so it will not get in the  [condition](https://github.com/nunit/nunit/blob/release/3.7/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L229), which ignoring the `IEquatable` of the element and will fail the assertion. 
```
namespace Nunit3TestsSamples {
	[TestFixture]
	class TestSample1 {

		[Test]
		public void test() {
			var set1 = new List<TestObject>() {
				new TestObject { Value = "test1" },
				new TestObject { Value = "test2" },
				new TestObject { Value = "test3" }
			};
			var set2 = new List<TestObject>() {
				new TestObject { Value = "test1" },
				new TestObject { Value = "test2" },
				new TestObject { Value = "test3" }
			};

			CollectionAssert.AreEqual( set1, set2 );
		}

		class TestObject : IEquatable<TestObject> {
			public string Value { get; set; }

			public bool Equals( TestObject other ) {
				return Value.Equals( other.Value );
			}
		}
	}
}
```

**Comment by CharliePoole** [comment] 2017-06-20 18:56
The purpose of PR #2118 was to make ` CollectionAssert.AreEqual` operate exactly as you describe. The intention was that you would not use `CollectionAssert` if you didn't want that behavior, but instead `Assert.AreEqual`.

I'm closing this as not a bug, but you can still comment and we will respond.

**Comment by LiyueWang** [comment] 2017-06-20 21:26
@CharliePoole  Thanks! So for now `CollectionAssert.AreEqual` will ignore any implement of `IEquatable`, and `Assert.AreEqual` will use any implement of `IEquatable`, right?

I list 4 tests below.  what is the specific use case for `CollectionAssert.AreEqual`? For Test3 and Test4, if we want to compare only the elements of the collection, we could both use `Assert.AreEqual( set1.ToArray(), set2.ToArray() );` instead.  Is any case we could not use `Assert.AreEqual` instead of `CollectionAssert.AreEqual`?

And a more general question is that  When comparing set1 and set2, what is supposed to be compared? what's the common sense here?

```
namespace Nunit3TestsSamples {
	[TestFixture]
	class TestSample1 {

		[Test]
		public void Test1_WithoutIEquatable() {
			var set1 = new string[] { "x", "y", "z" };
			var set2 = new string[] { "x", "y", "z" };

			Assert.AreEqual( set1, set2 );
			CollectionAssert.AreEqual( set1, set2 );
		}

		[Test]
		public void Test2_WithElementIEquatable() {
			var set1 = new List<TestObject>() {
				new TestObject { Value = "test1" },
				new TestObject { Value = "test2" },
				new TestObject { Value = "test3" }
			};
			var set2 = new List<TestObject>() {
				new TestObject { Value = "test1" },
				new TestObject { Value = "test2" },
				new TestObject { Value = "test3" }
			};

			Assert.AreEqual( set1, set2 );
			//CollectionAssert.AreEqual( set1, set2);	//fail, since CollectionAssert.AreEqual will ignore IEquatable of Element TestObject
		}

		[Test]
		public void Test3_WithCollectionIEquatable() {
			var set1 = ImmutableArray.Create( "x", "y", "z" );
			var set2 = ImmutableArray.Create( "x", "y", "z" );

			Assert.IsFalse( set1.Equals(set2) );
			//Assert.AreEqual( set1, set2 );	//fail, since Assert.AreEqual will use the IEquatable of Collection ImmutableArray
			CollectionAssert.AreEqual( set1, set2);
		}

		[Test]
		public void Test4_WithCollectionAndElementIEquatable() {
			var set1 = ImmutableArray.Create(
				new TestObject { Value = "test1" },
				new TestObject { Value = "test2" },
				new TestObject { Value = "test3" } );
			var set2 = ImmutableArray.Create(
				new TestObject { Value = "test1" },
				new TestObject { Value = "test2" },
				new TestObject { Value = "test3" } );

			Assert.IsFalse( set1.Equals( set2 ) );
			//Assert.AreEqual( set1, set2 );	//fail, since Assert.AreEqual will use the IEquatable of Collection ImmutableArray
			//CollectionAssert.AreEqual( set1, set2 );	//fail, since CollectionAssert.AreEqual will ignore IEquatable of Element TestObject
		}

		class TestObject : IEquatable<TestObject> {
			public string Value { get; set; }

			public bool Equals( TestObject other ) {
				return Value.Equals( other.Value );
			}
		}
	}
}
```

**Comment by CharliePoole** [comment] 2017-06-20 22:56
Well, the point of #2097 was that NUnit should __not__ be using an IEquatable implementation when we were asked to compare two collections. At first, we resisted, but the logic is that **Collection**Assert demands collection logic even if the collection object has an IEquatable implementation.

As I think about it, you may have a point. The same logic that got us to agree to the change would seem to say that it's only the __top-level__ collection that this should apply to, not the members. 

What do @nunit/framework-team members think about this? Should I reopen?

**Comment by jnm2** [comment] 2017-06-20 23:02
I agree to reopen. I missed this outcome earlier.

**Comment by CharliePoole** [comment] 2017-06-20 23:10
Two ways to go...
1. Apply to top level collection only
2. Apply to any members, but only if they are collections (i.e. IEnumerable)

**Comment by jnm2** [comment] 2017-06-20 23:21
I think (1) should be the default.

**Comment by OmicronPersei** [comment] 2017-08-23 01:17
Going to pick this one up 😄

**Comment by rprouse** [comment] 2017-08-23 01:24
@OmicronPersei all yours, enjoy 😄 

I have assigned you to the issue, but you should be able to assign yourself now as you take issues.

**Comment by OmicronPersei** [comment] 2017-08-23 01:27
Noted!  Just wanted to make sure someone else didn't want to take it up for some reason..

**Comment by jnm2** [comment] 2017-08-25 01:52
@OmicronPersei To the best of my knowledge, yes. This is also what makes the most sense to me. I think we want collection equality comparing the root objects and default NUnit equality (as in `Is.EqualTo`) when comparing the elements which will make use of `IEquatable`.

**Comment by Zubaloo** [comment] 2017-09-26 05:12
Just want to say that from the name of the "CollectionAssert.AreEqual" I would expect the method to iterate thru given collections and do "Assert.AreEqual" for the respective elements

**Comment by jnm2** [comment] 2017-09-26 11:31
@Zubaloo Yes, your expectation is correct and this is an open bug.

**Comment by OmicronPersei** [comment] 2017-10-30 00:15
The main problem I'm seeing is that `NUnitEqualityComparer` recursively copies the settings from itself as it compares elements within an `IEnumerable`.  This is problematic because a true value for `compareAsCollection` tags along and prevents `EquatablesComparer` from actually looking at any `IEquatable` implemetation, because, the way it's currently implemented, comparisons are completely ignored if `compareAsCollection` is flagged as true.  Trying to think whether or not this an easy fix or not, may be somewhat of a fundamental design flaw of `NUnitEqualityComparer` construction.

**Comment by OmicronPersei** [comment] 2017-10-30 00:20
What we could do is create a constructor for `NUnitEqualityComparer` that serves as a copy constructor, where when `NUnitEqualityComparer` creates its child comparers (`ArraysComparer`, `DictionariesComparer` and the like...), but it then instructs those to have `compareAsCollection` set to false as opposed to the super comparer, the original calling `NUnitEqualityComparer`.  Are there any design problems with this, I wonder?

**Comment by OmicronPersei** [comment] 2017-10-30 00:48
As a quick and dirty implementation, I temporarily falsified the `CompareAsCollection` flag within the EnumerablesComprarer.Equal` method like so

```C#
 bool compareAsCollectionPrevValue = _equalityComparer.CompareAsCollection;
_equalityComparer.CompareAsCollection = false;

if (expectedHasData != actualHasData ||
	!_equalityComparer.AreEqual(expectedEnum.Current, actualEnum.Current, ref tolerance))
{
	_equalityComparer.CompareAsCollection = compareAsCollectionPrevValue;

	
```

Not the most elegant solution, but since the original `NUnitEqualityComparer` object reference is passed around for making note of things like `FailurePoints` etc, I'm not sure we can get away with just creating a new temporary `NUnitEqualityComparer` that does equality within a collection correctly.

**Comment by CharliePoole** [comment] 2017-10-30 00:55
What if we give `NUnitEqualityComparer` a flag `_topLevelComparison`, which is initially set but is reset before making any recursive calls. Then add a new modifier to `EqualConstraint` with internal visibility... something like `IsCollectionAssert`... and use it rather than `AsCollection`. The `IsCollectionAssert` setting could cause the comparer to set `AsCollection` internally for the top level only.

The "only" drawback I see is that we are making an overly-complicated class more complicated. But we will have to rewrite it eventually anyway.

**Comment by jnm2** [comment] 2017-10-30 02:48
It's nice to stay away from mutability. It makes a lot of sense to me to keep the comparer instance for the collection instance separate from the comparer instance to be used on the items within the collection. If the copy constructor idea isn't hard, that's what I'd want. That way we're also more in control of which equality settings are applied recursively to different levels of an object graph.

**Closed** 2017-11-10 00:40 UTC
Labels: is:bug, pri:normal
