### ISSUE TITLE
GreaterThan (and similar) order dependent when combining with Null constraint

### ISSUE THREAD

**Issue by chphe** [nunit/nunit#660] opened 2015-05-22 12:55 UTC
While playing around with the Constraint Assertion feature of NUnit, my team mates made the following remark.
When combining _Null_ and _GreaterThan_ (or similar constraint) the order of writing is critical when used with _Or_ condition.

Take following examples:

``` c#
[TestCase(10)]
[TestCase(null)]
public void ConstraintNUnitNull(int? i)
{
    Assert.That(i, Is.Null.Or.GreaterThan(9));
}
```

``` c#
[TestCase(10)]
[TestCase(null, ExpectedException = typeof(ArgumentException))]
public void ConstraintNUnitNullFail(int? i)
{
    Assert.That(i, Is.GreaterThan(9).Or.Null);
}
```

From the perspective of fluent reading, both should work and behave the same. But in the second case, it throws an exception.
Technically I can understand why the exception is thrown, and I'm not sure this should be logged as a bug or that lazy evaluation should be documented.

I'm using NUnit Version 2.6.3.13283 and I also quickly tested the case when using Compound Constraints, it's the same...

``` c#
[TestCase(10)]
[TestCase(null)]
public void ConstraintOperatorNUnitNull2(int? i)
{
    Assert.That(i, Is.Null | Is.GreaterThan(9));
}

[TestCase(10)]
[TestCase(null, ExpectedException = typeof(ArgumentException))]
public void ConstraintOperatorNUnitNull1(int? i)
{
    Assert.That(i, Is.GreaterThan(9) | Is.Null);
}
```

**Comment by rprouse** [comment] 2015-05-22 14:02
Definitely a bug, thanks for the detailed report. I have marked it as status:confirm to make sure it is still happening in NUnit 3, although I suspect it is. I also set to priority low because I expect that this combination with a nullable int is probably fairly rare.

**Comment by CharliePoole** [comment] 2015-05-22 17:48
Definitely still happening by design. The Or and And operators have always been evaluated from left to right with Or having precedence over And. We used to explain this somewhere but it may have been lost over time. We should definitely document it.

Additionally, although I understand why @chphe might have expected it to work differently, it seems not to have caused surprise to anyone since the feature was introduced with NUnit 2.4 in 2007.

**Comment by ChrisMaddock** [comment] 2018-08-15 18:41
Thanks for making the docs update Mikkel! I think your changes do a good job of recording the current behaviour.

Regarding whether this is something we should close as a docs issue, I'm less sure however. I understand the current functionality was written with intended to work in this way, however I would still consider it surprising behaviour - as the original poster did. 

My gut feeling is also that it will require a very involved fix, and may not even be possible without a significant rewrite, but I'm not sure that's a reason to not consider this a change we want to make,.

**Comment by CharliePoole** [comment] 2018-08-15 19:58
I'm still a bit mystified as to why one would expect it to be different.

`Assert.That(i, Is.Null.Or.GreaterThan(9))` is written just as we write `if (i == null || i > 9)` in C#. If one were to write `if (i > 9 || i == null)` you would get an NRE on a null value.

Apparently, something in the fluent syntax is leading folks to expect it to work differently from other programming. I'd like to understand what exactly that is so I can design better syntax in the future. What leads one to expect "parallel" evaluation in this case?

**Comment by ChrisMaddock** [comment] 2018-08-15 20:09
> If one were to write if (i > 9 || i == null) you would get an NRE on a null value.

I had to double check this - but if `i` is a nullable int, that wouldn't be the case. `i > 9` would return false.

> Apparently, something in the fluent syntax is leading folks to expect it to work differently from other programming. I'd like to understand what exactly that is so I can design better syntax in the future. What leads one to expect "parallel" evaluation in this case?

Because, with my 'user' hat on, I'm calling library methods. How those methods are implemented isn't known to me - my expectation is simply how the syntax reads. That I'm testing if something is "Null or greater than nine". That fact that this chain of properties is evaluated left to right isn't immediately visible to me as a user, and, in my opinion, and implementation detail.

(The above is solely an attempt to explain my expectations as a user. I don't expect us to come to an agreement on the 'best' approach here! 🙂 )

**Comment by CharliePoole** [comment] 2018-08-15 20:33
This relates to a discussion on another thread about __who__ is the user NUnit aims at. In my time, she was a programmer using languages that focus on left-to-right evaluation, so NUnit works that way as well. After all, The user base now may be different, of course, but you guys still get to decide which users you want to focus on. You can't make everyone happy. 

Personally, I'd find it very surprising if you used right-to-left or parallel evaluation in this situation, but maybe I'm to close to it. I'm a programmer whether I have my user hat on or not. 😄 

If it's true that i > 9 doesn't throw for null i, while the corresponding constraint does throw, then maybe that's an error in NUnit, entirely separate from the question of order of evaluation. I know we went to a lot of trouble to throw rather than returning false in a number of places. Maybe this was one of them.

**Comment by jnm2** [comment] 2018-08-15 20:54
If CompareTo and nullable comparison operators behaved the same in .NET, I'd want to say that we should do what they do. But [they don't](https://stackoverflow.com/a/23787253/521757). CompareTo defines null as a valid input less than any other input, while C#'s lifted nullable operators follow the SQL practice of failing when either operand is null (except for `==` and `!=`!).

If we allowed our `GreaterThan` to work with nulls when used in isolation, which logic would we follow?
If we don't allow it in isolation, it feels wrong to me to have it start accepting null when `.Or` follows it.

In C# we're used to doing the null check first. The order is even embedded in names like `IsNullOrEmpty`. So long as the fix is obvious to a user who runs into this (switch the order of the checks), I kind of prefer our current situation.

**Comment by ChrisMaddock** [comment] 2018-08-15 21:00
@jnm2 You make good points. 😄

**Comment by ChrisMaddock** [comment] 2018-08-15 21:02
(Sorry, I should elaborate further.)

You make a good argument that this potentially opens a big can of worms. I'm not keen on the current behaviour, but given a) can of worms, and b) changing this behaviour feels like a huge piece of work, I can be convinced to close this as is. Given that makes four of us in agreement, I'll go ahead and do that.

Thanks for making the actual docs change, Mikkel!

**Closed by ChrisMaddock** 2018-08-15 21:02 UTC
Labels: is:bug, pri:low
