### ISSUE TITLE
All tests are executed when no test in assembly matches the filter

### ISSUE THREAD

**Issue by overeemm** [nunit/nunit#1403] opened 2016-04-08 12:08 UTC
We use filters on TestCategory to select which tests to run during the build. When no tests matches a filter, the adapter correctly signals that 0 tests match the filter. But still, setup and teardown methods are executing.
Adding a simple test that will always run (in our case one without category) will work around this issue.

I've traced through the code and I think the problem is in the EmptyTestFilter, the setup and teardown methods are collected by calling .Pass on the filter, and that always returns true.

**Comment by CharliePoole** [comment] 2016-04-08 14:07
Please give us a more complete description of how you are running tests and exactly which methods are running. That's always a good idea but I'm asking particularly here because: 

1. You filed an NUnit issue but it sounds like you're talking about some version of the adapter and using a TFS filter.
2. It's hard to imagine SetUp methods running by themselves as opposed to OneTimeSetUp.

Please also tell us what versions of NUnit you are using and if applicable the adspter

**Comment by overeemm** [comment] 2016-04-11 07:27
Okay, sorry for the incomplete story. I'm using the NUnit 3.2.0 nuget package, and the 3.0.9-ctp-9 testadapter.

The reason that I filled the bug here, is that I traced the source code (from github) and found the error to be in the engine.

The problem arises on the build server (But I could also reproduce this locally with the vstest runner). We use testcategories to filter which tests we want to run. We have three test assemblies, but this filter only selects tests from one assembly. The other assemblies do not match any tests.

As I said, I traced the code. What I have found is that the filtering in the adapter works.
This is what I get in the log:

    2016-04-08T07:28:30.0195482Z Information: TFS Filter detected: LoadedTestCases 187, Filterered Test Cases 0

But the next line is

    2016-04-08T07:28:31.0005245Z ##[error]Error: TearDown failed for test fixture Afas.Runtime.Client.IntegrationTests.BelongsTo.Dierentuin_Verblijf_Dier

That doesn't seem right, because it says that it hasn't got test cases that match the filter.

I'm not sure if it is the OneTimeSetUp & OneTimeTearDown or the normal SetUp & TearDown (or both) that is the problem, because my tests have both.

The workaround is that I place a test that matches the filter in every assembly, this makes that the filter finds one test, and everything works again.

Again, why I have put the issue here: I've traced the code and debugged all the way up to the CompositeWorkItem and the EmptyFilter in nunit.framework.dll.  The CreateChildWorkItems method calls ITestFilter.Pass , but this returns always true in the case of EmptyFilter.

The EmptyFilter is created in TestFilter.FromXml because of the filter count (which is 0 in my case).

I hope this helps.

**Comment by CharliePoole** [comment] 2016-04-11 08:29
So, if I understand correctly, the problem only arises with the nunit3 adapter when running all tests using  a yes filter that selects no tests in a particular assembly. The adapter creates a simple name filter with no names. It runs tests in the assembly using that filter leading to the error you see.

This will all have to be confirmed with test cases, but if it is we have the following bugs:

1. The adapter should not even run tests in an assembly when it already knows that assembly contains no tests.

2. An assembly run by nunit under a simple name filter with no names should not execute any test code.

3. The adapter should not generate a false error message implying that setup or transient code is being run.

It's likely that either 2or3, but not both is happening.

Does that sound right to you?

**Comment by overeemm** [comment] 2016-04-11 13:52
Yes, this sounds right. I think 2 is happening, but that needs to be confirmed.

**Comment by CharliePoole** [comment] 2016-04-11 16:08
I marked it as a bug, since I know that at least point 1 is true from the code itself.

**Comment by CharliePoole** [comment] 2016-04-11 20:18
As indicated by the name change, it's more than just setup and teardown. All assemblies are actually executed. I created nunit/nunit3-vs-adapter#153 to deal with the adapter side of this. In fact, the problem will disappear if either side is fixed, but I think we need to fix both.

The NUnit issue appears to be that an empty simple name filter runs all the tests. I'll try to make this happen with the console runner next, then add some tests and fix.

**Comment by CharliePoole** [comment] 2016-04-11 20:18
@overeemm I think you are right... it's 1 and 2.

**Comment by CharliePoole** [comment] 2016-04-15 00:20
After reviewing the code, this appears not to be an NUnit problem but a misuse of the filter builder service by the Adapter. If you get a TestFilterBuilder from the TestFilterService and just ask it for a filter without adding any restrictions, it will be an empty filter, which runs all tests. The adapter shouldn't be using the filter builder if it has nothing to filter.

**Closed by CharliePoole** 2016-04-15 00:20 UTC
Labels: is:bug, pri:normal

**Comment by CharliePoole** [comment] 2016-04-15 00:22
PR nunit/nunit3-vs-adapter#153 fixed this in the adapter.
