### ISSUE TITLE
"System.MissingMethodException" error appears after update from 3.13.0 to 3.13.1 version

### ISSUE THREAD

**Issue by oleksandrp1** [nunit/nunit#3766] opened 2021-02-09 11:53 UTC
"System.MissingMethodException : Method not found: 'System.Reflection.MethodInfo[] NUnit.Framework.Internal.TestSuite.get_OneTimeTearDownMethods()'." error appears after update of NUnit nuget package from 3.13.0 to 3.13.1 version.

Stack Trace: 
    AllureNUnitHelper.GetNUnitHelpMethods(NUnitHelpMethodType type, TestFixture fixture)
    AllureNUnitHelper.BuildFixtureResults(NUnitHelpMethodType type, TestFixture testFixture)
    AllureNUnitHelper.StopAll(Boolean isWrappedIntoStep)
    AllureNUnitAttribute.AfterTest(ITest test)
    <.ctor>b__1(TestExecutionContext context)
    <>c__DisplayClass1_0.<Execute>b__1()
    BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

The error appears after the execution of a test case. The error disappears after rollback to the 3.13.0 version.

**Comment by mikkelbu** [comment] 2021-02-09 13:12
I guess the problem is that the properties have changed type from `MethodInfo` to `IMethodInfo` in #3701, but allure-nunit is compiled again version 3.12.0 (thus matching the types in 3.13.0) - https://github.com/unickq/allure-nunit/blob/15b13970770405c6996e7cb781846e169443386b/src/allure-nunit/allure-nunit.csproj

I think the best solution for now will be to use the same version that allure-nunit references - meaning 3.12.0. You could ask them to bump their dependencies, but I guess this could give problems to users using allure-nunit and older versions of nunit e.g. 3.12.0

**Comment by stevenaw** [comment] 2021-02-16 00:51
Thanks for filing a sister issue against allure-nunit @oleksandrp1 
It looks that issue has now been closed and a newly released version of allure-nunit , 1.0.12, has been compiled against NUnit 3.13.1.

I'm going to close this issue as well. We'll continue to see any additional comments made here, however.

**Closed by stevenaw** 2021-02-16 00:51 UTC
Labels: confirm
