### ISSUE TITLE
Native Win32 Exceptions not handled/reported by NUnit Agent

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#736] opened 2015-07-14 10:41 UTC
I try with 3 parameters sets: "--workers=4 --x86" and "--x86" and without parameters (assembly name only).

![image](https://cloud.githubusercontent.com/assets/1849690/8671344/f2d4fda2-2a2c-11e5-80a5-ab6b0446f9c2.png)

```

System.Net.Sockets.SocketException (0x80004005): No connection could be made bec
ause the target machine actively refused it 127.0.0.1:59867

Server stack trace:
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket(EndPoint
 ipEndPoint)
   at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket()
   at System.Runtime.Remoting.Channels.SocketCache.GetSocket(String machinePortA
ndSid, Boolean openNew)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.SendRequestWit
hRetry(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage
(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITranspor
tHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMess
age(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
Msg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
ta, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Unload()
   at NUnit.Engine.Runners.ProcessRunner.UnloadPackage()
   at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter
 filter)
   at NUnit.ConsoleRunner.ConsoleRunner.Execute()
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

When I selects "Debug" of "nunit agent" VS shows
![image](https://cloud.githubusercontent.com/assets/1849690/8671460/e8f35d32-2a2d-11e5-9ddb-7ff2bbd1b0a1.png)

**Comment by constructor-igor** [comment] 2015-07-14 11:17
found interested comment near the test class definition:
```
//[Ignore("This test occasionally causes Nunit to crash, thus failing the entire tests dll")]
```
But now the tests are passed under nunit v2.6.4.

**Comment by CharliePoole** [comment] 2015-07-14 11:31
I'm confused. Are you intending to say that this is somehow connected with the error you are experiencing with your own tests?

**Comment by constructor-igor** [comment] 2015-07-14 11:41
seems, somettinh happens in c++ method, which we call from our test.
Now I reproduced the crash from VS
![image](https://cloud.githubusercontent.com/assets/1849690/8672373/479ff5e0-2a36-11e5-83cc-dffdec0f82e2.png)

**Comment by CharliePoole** [comment] 2015-07-14 11:49
OK, I see now that the comment _is_ in your tests. I was confused because one of NUnit's tests has an almost identical Ignore for one of our tests!

I'm afraid this will join a variety of issues we have with running C++ tests.

One small thing to check: make sure you are not trying to load any 64-bit assembly.

**Comment by CharliePoole** [comment] 2015-07-14 11:51
Note that the original error (your first post) is not the cause of the problem. It's just an error caused by the fact that the agent has terminated.

**Comment by constructor-igor** [comment] 2015-07-14 11:56
The c# test project has "Platform target x86" and, according to my tests, doesn't try to load x64 assembly.
Also, the test sometimes passes with nunit v3.

**Comment by rprouse** [comment] 2015-07-14 12:55
@constructor-igor, my guess is that NUnit is working 'properly' and that the native code in your test is failing occasionally, probably by throwing something like a Win32 AccessViolation which we do not handle. We could add a Structured Exception Handler to NUnit to log an error before we exit, but they tend to cause other problems in managed code.

You say that your code fails occasionally. What I can see of your code, you create the source array with a length and m_rnd. Is m_rnd a random number? If so, is this test failing with some values of m_rnd?

If you have the source for MKLAccess.cblas.blascopy, this would be fairly easy to debug if it was x64 code, but unfortunately it is x86. I can give you two options to try to debug it. Even if you do not have the source, this will likely show you the Win32 exception that is being thrown in the output window.

### 1 - Create an x86 nunitlite runner to run the tests

- Switch your test project's Output type to console application.
- Reference the nunit.runner nuget package, this should add a program.cs to your project.
- If it doesn't already, ensure your test project targets x86
- Make sure 'Enable native code debugging' is checked under the debug settings
- Set your test project as the startup project
- Debug through your test

### 2 - Use coreflags to switch nunit.console.exe to an x86 process

This changes nunit.console.exe, so you will make a copy of it.

- Copy the NUnit bin directory somewhere where you can change it without admin
- Open a visual studio command prompt and cd to that directory
- Run `corflags nunit.console.exe /32BITREQ+ /Force` to switch nunit.console to x86
- Set your test project as the startup project
- Under the debug settings, switch Start action to Start external program and put in the full path to your x86 nunit.console.exe
- Under command line arguments enter `--process=Single your.test.dll`
- Set the working directory to the build directory of your test assembly
- Make sure 'Enable native code debugging'
- Debug through your test

**Comment by rprouse** [comment] 2015-07-14 12:58
Also, looking at the failure you are seeing, it is an Assert Failure. This might not be an NUnit assert (likely it isn't), but a C++ assert in the native code that you are calling. See https://msdn.microsoft.com/en-us/library/ww5t02fa.aspx

**Comment by constructor-igor** [comment] 2015-07-14 14:29
thank you for detailed comments of the issue.

I investigated the "occasionally failed" test and found incorrect parameter (incorrect number of copied items). The incorrect number of items we transfer to MKL (Intel Math Kernel Library).

When I fixed the parameter, the test passed without any problems.

So, problem found and fixed in our test.

If nunit will able to support "unmanaged" exceptions, it'will allow us to find our problems faster.

thank you again!

**Comment by CharliePoole** [comment] 2015-07-14 14:32
@rprouse I don't think we have an issue on support for unmanaged exceptions. They could, of course, be wrapped if we can catch them. Should we make a new issue? Or we can change this one's title.

I see this as "future" if at all.

**Comment by rprouse** [comment] 2015-07-14 14:45
I just looked at the App.config files and we have
`<legacyUnhandledExceptionPolicy enabled="1" />` and `<startup
useLegacyV2RuntimeActivationPolicy="true">` so native exceptions should be
getting translated to SEHExceptions and handled. We should be reporting
these as errors. I will rename this issue to reflect that and check by
modifying our C++ test assemblies.

The issue might be that the exception that is being thrown in this case is
one of the exceptions that cannot be caught. If we handle normal Win32
exceptions properly, I will then close this issue.

On 14 July 2015 at 10:32, CharliePoole <notifications@github.com> wrote:

> @rprouse <https://github.com/rprouse> I don't think we have an issue on
> support for unmanaged exceptions. They could, of course, be wrapped if we
> can catch them. Should we make a new issue? Or we can change this one's
> title.
>
> I see this as "future" if at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/736#issuecomment-121256070>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by rprouse** [comment] 2015-07-14 14:48
I added status:confirm and assigned to myself for confirmation.

**Comment by rprouse** [comment] 2015-09-05 02:43
I am closing this issue without action. I tested by modifying our C++ mock test assemblies to access a native nullptr and we handled the error correctly. As I suspected, we do not handle the native `assert` method which is to be expected since it breaks immediately. I change the code to the following and reproduced a similar error as expected.

```C++
#include <assert.h>

#include "TestClass.h"

void TestClass::TestMethod()
{
    assert(false);
}
```

The `ExecutionEngineException` in the one screenshot is odd since it is generally only thrown for "an internal error in the execution engine of the common language runtime," but this class has been marked as obsolete.

If anyone runs into this issue again, please re-open, but until then I am closing.

**Closed by rprouse** 2015-09-05 02:43 UTC
Labels: is:bug, pri:normal, status:confirm
