### ISSUE TITLE
Broadcasting messages through engine

### ISSUE THREAD

**Issue by nvborisenko** [nunit/nunit#3016] opened 2018-09-12 10:46 UTC
Continuing https://github.com/nunit/nunit-console/issues/433

Sometimes a test needs send a message which is not kind of test output.

It would be nice to have something like:
```csharp
TestContext.BroadcastMessage(Type fromType, Type destinationType, string message);
```

- `destinationType` can be null, what means that message is broadcast to everybody
- `fromType` is for understanding who sent a message

And any logger can handle it via xml:
```xml
<broadcast-message from="fullTypeName" to="fullTypeName" testId="123" time="....Z">
  <![CDATA[ This is message content ]]>
</broadcast-message>
```

- `to` attribute is optional
- `testId` attribute is optional due a message may be broadcast from empty context
- `time` attribute is DateTime when message was sent

@CharliePoole please welcome here to review

**Comment by CharliePoole** [comment] 2018-09-12 12:50
@nvborisenko Not sure why you created a new issue rather than using the old one.

I write some guidelines for that issue as requested by @ChrisMaddock but I don't see the comment posted! I'll check further after a little more sleep. :smiley

**Comment by ChrisMaddock** [comment] 2018-09-12 12:58
@CharliePoole - this comment? https://github.com/nunit/nunit-console/issues/433#issuecomment-419655440

I saw it, and it looked ideal to me. 🙂

**Comment by CharliePoole** [comment] 2018-09-12 13:19
@ChrisMaddock Strange. I can't see it in OctoDroid at all but if I switch to the browser I do.

**Comment by nvborisenko** [comment] 2018-09-12 16:45
I created this issue in correct repository, previous one is in `nunit-console`.

I am ready to provide a pull request, let's just finalize specification for xml events.

**Comment by CharliePoole** [comment] 2018-09-12 18:04
Interesting... I thought of it as an engine issue, but it looks like all the actual code will be in the framework. We could have continued there, so long as the PR is here, but this is OK as well.

Comments on the proposed design...

1. I originally suggested a method in TestContext, but I'm having second thoughts. Is this really a facility to be used by test writers or is it really for use in custom attributes, etc.? Discussion leading up to this point has tended to be about needing to send a message to an engine extension, so I assumed a custom attribute would be distributed with such an extension. If it is really only for use in and with extensions, then I'd put it in `TestExecutionContext` without any access from `TestContext`. If it's really for users (non-extenders) then a frontend in `TestContext` is needed.

2. I don't think you can use a `Type` in the signature, since the receiving extension won't be loaded in the same AppDomain (or possibly Process) as the test that is making the call. The Source Type may not be known to the receiver and the Destination Type may not be known to the sender. If you need a source or destination, they have to be some sort of logical value, probably a string.

3. I'm not sure we need source. Do you have a specific use for this or is it added for completeness? If the latter, we may want to wait for the need to arise. Adding an attribute to an XML fragment is non-breaking.

4. Do we really want to broadcast? In the original description, the assumption was that the text of the message would be formatted in a way that a particular destination could understand. Other destinations would likely not know how to interpret the message. Of course, in terms of implementation, this is a broadcast because the potential recipients decide if they want to handle the message, based on the destination field. But from a usage perspective, it's really a Send to a particular destination. I presume most extensions that use this would have a single destination value, but some of them could have multiple values for different purposes.

5. I'm confused by the statement "a message may be broadcast from empty context." If this is being used by and from tests, then not having a context is a serious error in NUnit.

I think some of my comments arise out of your having generalized the solution from the original problem statement. I'd rather see us aim for the simplest solution that solves the issue at hand but doesn't block us from further enhancements in several possible directions in the future.

**Comment by nvborisenko** [comment] 2018-09-12 18:48
Any of these solutions is comfortable for me and resolves my initial issue. Basically I wanted to think about feature in more generic way.

1. We can begin from `TestExecutionContext`, and then in future just wrap a method for `TestContext`
2. Ok, will use `string`
3. No specific cases, though that a source would be useful for handlers to apply some logical implementation
4. I tried to call it somehow, no better than "Broadcast" I think
5. Ok

So, still need your green light for implementation.

**Comment by CharliePoole** [comment] 2018-09-12 18:56
I'm OK with that approach. It would be nice if some other @nunit/framework-team members added comments as well.

On item 2, since it has to go through the XML, it will be a string anyway. 😄 

Why not just "SendMessage"?

**Comment by nvborisenko** [comment] 2018-09-12 19:16
So the following changes are required:
- Add `TestMessage` class which is similar to `TestOutput` class
- Add new method to `ITestListener` interface (SendMessage?)
- Add method `SendMessage` to `TestExecutionContext` class for "users" (because of `Listener` property is for internal usage)

@CharliePoole please suggest xml node name for these messages. After that I will create a PR to continue our discussion there. Thanks for your supporting.

**Comment by jnm2** [comment] 2018-09-12 19:47
If I remember right, we should discourage users and extenders alike from using `TestExecutionContext` or any other `NUnit.Framework.Internal` types, since by design we want to be free to make breaking changes of any severity at any time to types in that namespace.

I like the name `Broadcast`, so long as we don't use the term `destination` which has a non-broadcast sense. What about `TestContext.Broadcast(string channel, string message)`?

> Add new method to ITestListener interface (SendMessage?)

We try to avoid adding new methods to existing interfaces unless they are in the `Internal` namespace. It means compile errors when folks upgrade, and really bad runtime crashes when an extending library is run against newer versions of NUnit than it was compiled against.

I'd suggest creating a `BroadcastArgs` type with the two string properties so that in the future we'd be free to add a third property to the type without breaking the interface. (Say, for example, we added a `Broadcast(string sender, string destination, string message)` overload in a future release.)

**Comment by CharliePoole** [comment] 2018-09-12 21:01
@nvborisenko I think we may be misunderstanding one another.

Here is my understanding: 

* The messages are to be received by engine extensions, which are not part of the framework at all. Specifically, by extensions that implement the test listener extension point.
* The interface at that extension point is `NUnit.Engine.ITestEventListener`, which has only one method:

```C#
void OnTestEvent(string report);
```

The string is an XML string. A test event listener gets every report and handles those it is interested in. Normally, the report is dispatched according to the element name.

OTOH, IFF we were interested in sending messages to classes in the test assembly, we would probably want to use `NUnit.Framework.ITestListener`. However, that's a departure from what this issue initially seemed to be about, at least as I read it.

Do you yourself have a specific use case? Does it involve an engine extension? We should clarify what we are trying to do here, since dispatching messages to extensions is really very different from dispatching them within the framework.

**Comment by CharliePoole** [comment] 2018-09-12 21:05
@jnm2 We have traditionally treated extenders of the framework as writing trusted code that becomes (almost) a part of NUnit. That's why we used an Internal namespace rather than giving the classes internal visibility. Of course, we have made too much visible and have to back away from that, but it's not possible to write meaningful extension attributes without accessing the `TestExecutionContext`, for example.

OTOH, as I just posted separately, I see no need to get involved with the `ITestListener` interface unless I have completely misunderstood the goal of this issue, i.e. to communicate with engine extensions.

**Comment by nvborisenko** [comment] 2018-09-13 09:29
Initial my question was how to send a message from test to listeners. This message is NOT output, and should not appear in console. Anyway I created PR.

**Comment by CharliePoole** [comment] 2018-09-13 10:02
I see now that you have to modify ITestListener in order to get the message handled in the first place.

@jnm2 I don't see this addition as breaking anything but if you see some cases, let's talk about it.

**Comment by jnm2** [comment] 2018-09-23 23:53
@CharliePoole Adding `ITestListener.SendMessage` will cause compile-time errors for anyone that implements an `ITestListener`, and runtime crashes for libraries compiled against NUnit 3.10 and run against NUnit 3.11. The runtime crashes make it impossible to write a helper library that works against both NUnit 3.10 and 3.11 simultaneously.

However, my [PR to remove the ITypeInfo abstraction](https://github.com/nunit/nunit/pull/2796) has already placed us in this territory with 3.11 in far more places.

(Just curious: do we expect NUnit users and extenders to implement `ITestListener`?)

**Comment by jnm2** [comment] 2018-09-24 00:31
@CharliePoole The way NuGet works, I might reference directly reference NUnit 3.11 and Some.NUnit.Helper 1.1. Some.NUnit.Helper 1.1 might have a package reference to NUnit 3.10 because that's what the author compiled against at the time.

The C# SDK will then run my tests using the assemblies in the Some.NUnit.Helper 1.1 package (which were compiled against NUnit 3.10) and the assemblies in the NUnit 3.11 package.

This is a very common scenario with NuGet package references. As a user, I want to use the latest version of Some.NUnit.Helpers but I also need to upgrade to NUnit 3.11 to fix a bugfix. Out in the wild, I very rarely see this cause binary compatibility issues.

To show that we do not follow the status quo with regard to binary compatibility across versions, we should recommend that NUnit extension authors put fixed version ranges in their nuspecs, such as `version="[3.10.0]"`. That way, the C# SDK will prevent consumers of those helpers from referencing the NUnit 3.11 package and creating the unsafe combination.

**Comment by CharliePoole** [comment] 2018-09-24 01:57
@jnm2 Right. I'm describing how framework customization was set up to work, before we had a nuget.

I think it would be great to make it work as you say, but I don't know what it would take.

IMO, whatever you do needs to work for everyone, whether they use package referenced or not.

**Comment by jnm2** [comment] 2018-09-24 12:04
> I think it would be great to make it work as you say, but I don't know what it would take.

To make this work, we need to avoid all changes that break binary compatibility (i.e., ones that cause the runtime to refuse to load assemblies). A good way to achieve that is to follow the BCL's breaking change guidelines: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md

Of which, the first disallowed in the [Members section](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#members) is:

> ✗ Disallowed
> 
> - Adding an member to an interface

In other words, if we want to allow the same NuGet extension assembly to work against 3.10 and 3.11 without runtime crashes, we have to find a solution to broadcasting messages that does not involve adding an interface member or anything else in that file. Similar to how you added `IFixtureBuilder2` in #2878.

The complicating factor is that there are already such binary incompatibilities between 3.10 and 3.11, the largest of which was my removal of the ITypeInfo abstraction. The ITypeInfo abstraction was also added in a binary-breaking way originally so there is a symmetry there. In order to allow an extension to work against both 3.10 and 3.11, we'd have to roll back some PRs in time for 3.11 and save them for a future version of NUnit.

**Comment by CharliePoole** [comment] 2018-09-24 19:41
True. I was thinking of our engine API interfaces, to which we only add methods. But that's only breaking if users need to __implement__ the interface, not to those who consume it. Good reminder that we need to think more deeply about this.

In this particular change, the engine interface remains the same. The internal interface (in the framework) does change. If you follow the rule that anything a user is technically capable of using is a part of your supported interface, then we can't do this at all. As you know from past discussions, that's not my own interpretation of what we support and what may be considered breaking.

The `IFixtureBuilder` interface is one that we documented and told people to implement as a part of certain custimizations of NUnit. That's why we needed to add `IFixtureBuilder2`.

The `ITestListener` interface is purely internal, so I feel comfortable "breaking" it.

BUT I also believe that the majority of the team (i.e. those remaining with the team) have to decide what approach you want to take. This seems to come up continually without ever being resolved.

**Comment by nvborisenko** [comment] 2018-11-29 19:13
Do you prefer to keep this issue opened to continue discussion about breaking changes, or close this? From my point of view this initial issue is resolved.

**Comment by CharliePoole** [comment] 2018-11-29 19:38
I thought this was implemented.

**Comment by rprouse** [comment] 2020-05-18 19:41
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 19:41 UTC
