### ISSUE TITLE
ITestAssemblyRunner provides no ability to be asynchronously notified when RunAsync completes

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1186] opened 2016-01-10 21:51 UTC
Perhaps there was a good reason for this, but normally, if an asynchronous operation can be initiated through an interface, there is a method to be notified when it completes, either through an event, or through a callback.

ITestAssemblyRunner defines the RunAsync method to start the asynchronous operation, the WaitForCompletion method to synchronously wait for it to complete, and the StopRun method to asynchronously stop the run, but has no way to asynchronously be notified that it has completed.

It would seem that either an event (OnRunComplete) should be added to the interface, or another method like RunAsync (ITestListener, ITestFilter, RunCompleteCallback) should be added to the interface, and implemented in NUnitTestAssemblyRunner, as well as any other runners.

**Comment by rprouse** [comment] 2016-01-10 22:36
Sounds reasonable although we should reflect those changes out to the engine's ITestRunner interface as well. This would require incrementing the engine.api version though, so we should make sure it is what we want to do and get it in to 3.2 if we can.

The Wait call does signal you when the test is completed by returning. This is probably less elegant than a callback, but it is workable. Admittedly, it isn't very async since you would likely run the tests then wait. Either way, you need to block.

My preference would be to add a new RunAsync method, or just add the parameter to the existing method with a null default value.

**Comment by oznetmaster** [comment] 2016-01-10 22:49
I added a RunAsync method to my CF version.

The Wait call is of no use if a truly asynchronous environment is desired.  It is not workable in that environment, because once it has been called, then things become synchronous.

C# 3.0 has no default values, so a new method is necessary.  This is from my version of ITestAssemblyRunner:

```
		/// <summary>
		/// Run selected tests asynchronously, notifying the listener interface as it progresses.
		/// </summary>
		/// <param name="listener">Interface to receive EventListener notifications.</param>
		/// <param name="filter">A test filter used to select tests to be run</param>
		/// <param name="runCompletedCallback">An optional callback for the completion of the run</param>
		void RunAsync (ITestListener listener, ITestFilter filter, Action<ITestResult>runCompletedCallback);
```

**Comment by CharliePoole** [comment] 2016-01-11 03:09
@oznetmaster It's definitely customary as you say. In this case, every test start and finish, including the end of the run, is sent to the test listener. For some uses, I can see an explicit end of run action would be more convenient, so I would suggest starting with that. What's the use case, specifically. Remember, this is not a general-purpose interface we publish for everyone to use, so there is even less reason than usual to add features speculatively.

OTOH, if  there is a specific need for it in some runner we want to support, we should add it. Let's start from the client rather than from the lowest level code. And lets keep in mind that up to now we have not been treating this as an interface for others to use, even though it's a public Type.

@rprouse I think the same approach has to be taken with the engine. Is there a use case for the engine having an async call with a callback? There could be. If so, let's start top down by adding what is needed to ITestRunner and working inward from there.

There is a certain amount of circumstantial evidence that such a method is not needed. NUnit V2 has lasted for 15 years, with a console runner, GUI and varous IDE adapters without having such a signature. The TestRunner interface has Run (synchronous) and BeginRun (async). Back when it was created, it would have been "normal" to have an EndRun method as well but the presence of the event listener made it unnecessary.

******

I'm not actually saying this is a bad idea, only that justifying it bottom-up is not the right way to do it. It could even be that we didn't need an async method for running tests, although I doubt it. At one point, I didn't have it but added it for the GUI. (V2 uses BeginRun for the same reason)

In the case of ITestRunner, I think you could argue for a callback on the RunAsync method on the basis of general principles, because we advertise it as a general-purpose API. In fact it's a major feature of NUnit 3.0. But we don't tell people to use ITestAssemblyRunner, so I think it only needs to support those things we use it for.

Neither of you mentioned IFrameworkDriver, which is where the two pieces connect. That interface does not have a RunAsync method at all. If you wanted RunAsync to work from top to bottom, you would have to add that ability and every driver (and framework) would probably need it too.

Charlie

**Comment by oznetmaster** [comment] 2016-01-11 03:20
ITestRunner??  I can not find that interface :(  What am I missing?  I can only find ITestAssemblyRunner.

**Comment by oznetmaster** [comment] 2016-01-11 03:22
ItestListener only has methods for TestStarted and TestFinished.  None for RunStarted and RunFinished.

**Comment by CharliePoole** [comment] 2016-01-11 03:22
@oznetmaster It's one of the primary engine interfaces. In nunit.engine.api.dll.

**Comment by oznetmaster** [comment] 2016-01-11 03:23
Well, I am not using the engine, so it would be of no use to me.

**Comment by CharliePoole** [comment] 2016-01-11 03:23
@oznetmaster We deduce the end of run by examining the TestFinished events.

**Comment by oznetmaster** [comment] 2016-01-11 03:24
In what way is that deduction done?

**Comment by CharliePoole** [comment] 2016-01-11 03:24
@oznetmaster "Well, I am not using the engine, so it would be of no use to me." 

There are more people in this discussion than just you and I.

**Comment by oznetmaster** [comment] 2016-01-11 03:24
I understand.  But I was specifically talking about nunitlite, and that was what @rprouse had responded to.

**Comment by CharliePoole** [comment] 2016-01-11 03:25
@oznetmaster This is precisely the itty-bitty level of discussion I was hoping to avoid. Can't we start with everyone first understanding what you are trying to accomplish?

**Comment by CharliePoole** [comment] 2016-01-11 03:26
@oznetmaster "that was what @rprouse had responded to"

read his response again. I replied toeach of you in separate paragraphs. Then I summarized
Perhaps, read my response again as well.

**Comment by CharliePoole** [comment] 2016-01-11 03:27
@oznetmaster NUnitLite is now working without such a method. Why does it need it? 

I'm not saying it doesn't need it - merely that you haven't said yet.

**Comment by oznetmaster** [comment] 2016-01-11 03:30
I want to expose a "complete" asynchronous interface, for whatever reason someone may want to use it.

It makes little sense to expose RunAsync without exposing a way to asynchronously determine when that asynchronous operation has completed.  Maybe RunAsync should not be exposed, but obviously, at some point in time, it was decided to do so.  If it is going to continue to be exposed, then lets make it fully usable.

It would make little sense for Microsoft to have exposed the Beginxxx methods without the corresponding Endxxx, Similarly here.

A callback or an event seem to be the logical way to handle this.

I do not think this discussion needs to be driven by a current "need".  It has to do with the semantic completeness of the interface.

**Comment by oznetmaster** [comment] 2016-01-11 03:38
It is working if one uses AutoRun (Assembly).  If one wants to be more inovative, and use AutoRun (null) with the assemblies being specified on the command line (as we now allow), then there are interesting and perhaps valuable extensions to be had.

In my case (which is notably very specific), I have a "console runner" running on the device itself.  It, in turns, calls TextRunner.Execute when commands are inputted to it.  Since I do not want it to block (allowing additional command while the tests are running), I fully support the RunAsync with a callback.

This allows command to entered to stop the run (using the ITestAssemblyRunner.StopRun method), and to determine current test status (accessing the ITestAssemblyRunner.Isxxx properties) while the tests are running.

**Comment by rprouse** [comment] 2016-01-11 03:39
@oznetmaster, when we discuss issues like this, we need to think of the impact and the use on the whole system which is why I thought that if you have a valid use case for this functionality in nunitlite, then that use case would likely apply to the nunit engine. 

You may not use the engine, but only a very small fraction of the community uses nunitlite. By current download statistics, only 1% of NUnit uses use NUnitLite. The vast majority use the console runner or other 3rd Party runners based on the engine interface, so if there is a valid need for an Endxxx method, then we should consider it just as valid for engine.

I agree that it makes sense to have some sort of end event, but changing our interfaces at this point effects many potential consumers of those interfaces, so we need to only do so for reasons that are stronger than the semantic completeness of the interface. Changing the interfaces forces third party runners like Resharper, NCrunch, TestDriven.NET, etc to play catch up with us and makes it difficult for them to support multiple versions of NUnit in one product. Users of NUnitlite don't have this problem because they take a dependency on a specific version of nunit.

**Comment by CharliePoole** [comment] 2016-01-11 03:42
@oznetmaster You asked "In what way is that deduction done?"

 * NUnitLite doesn't do it at all because it doesn't use the RunAsync method.

 * In the Engine, we detect that an assembly run is finished in the TestFinished event by looking for a "test-suite" element with a "type" attribute of Assembly.

 * In the GUI, I do it by detecting a"test-run" element in the TestFinished event.

**Comment by oznetmaster** [comment] 2016-01-11 03:45
Why the difference between the engine and the gui?  Shouldn't the method be identical in both situations.  If not, then it is not really definitive, is it?

**Comment by oznetmaster** [comment] 2016-01-11 03:47
If there is a single definitive method to make the determination from the TestFinished event, then the whole issue can probably be ignored.  It then becomes one of syntactic completeness rather than semantic completeness.

**Comment by oznetmaster** [comment] 2016-01-11 03:51
However, on second thought, there is a small difference.  Having either a callback or a specific run completed event does provide a different timing.  This would occur after the thread the test is running on has exited (from the dispatcher thread).  The TestFinished event is raised from the thread the test is running on.

**Comment by CharliePoole** [comment] 2016-01-11 03:56
@rprouse I'll add to your comments that even the 1% who use NUnitLite are not dependent on that interface. Most people will follow the rote instructions involving use of AutoRun. I think that Neil's logic makes sense if we apply it to an interface we are publishing for people to use. Both the internal V2 TestRunner interface and the existing ITestAssemblyRunner are somewhat idiosyncratic in how they handle asynchronicity. It hasn't been a problem for us so far.

If we did change this, we would have to decide whether to reflect the change in the FrameworkController reflection-based "interface" which is used by our drivers and (I believe) by some third party runners. That is one of our "published" interfaces.

Together with an offline conversation I've been having with a long-time user, this issue makes me think we need to express more clearly which are the interfaces that we guarantee for users. The fact that this one is in NUnit.Framework.Api may be a bit deceptive if we intend it to be for use by our own programs only.

**Comment by CharliePoole** [comment] 2016-01-11 04:00
@oznetmaster "Why the difference ... "

We have a three-layer architecture. The engine is the middle layer between the runners and the frameworks. The concept of "test run" is really an engine concept. It detects that each assembly has completed in it's respective framework instance, puts them all together and wraps them in a test-run element.

Any runner (not just the GUI) would be dealing with engine concepts, not frameworks, so it would have to watch for "test-run".

**Comment by CharliePoole** [comment] 2016-01-11 04:18
OK, looking at the code... ITestAssemblyRunner.RunAsync is referenced
* by NUnitTestAssemblyRunner.Run (which immediately waits on it)
* by FrameworkController.RunAsync

It is not called by NUnitLite

The FrameworkController.RunAsync method would be triggered by any driver that used reflection to create a FrameworkController.RunAsyncAction object. This would normally be a framework driver in the engine.

In our code, RunAsyncAction is only created by tests. Our framework driver uses RunTestsAction, which is synchronous.

IOW, we don't actually use RunAsync for any of our code. It is available for third parties who go through the reflection-based interface. The ITestAssemblyRunner interface was designed to be callable through the reflection-based interface and therefore only has members that can be accessed using the conventions of that interface (constructor triggers the action).

**Comment by oznetmaster** [comment] 2016-01-11 04:26
Not sure what that has to do with the issue?

'    public class NUnitTestAssemblyRunner : ITestAssemblyRunner'

However, I am assuming that it is mostly there to be used by third parties.  That is why I think it should be complete.

**Comment by CharliePoole** [comment] 2016-01-11 04:50
@oznetmaster Are you saying that it looks like it should be used by third parties because it's public?

Having people assume they can safely use our public methods has been a long-time problem for NUnit. I tried to mitigate this in 3.0 by sticking some things into an "Internal" namespace, but I've just been having an offline discussion with someone who finds that odd.

Bear in mind that xUnit style testing was invented by people who worked in languages that didn't have any privacy levels. In Smalltalk, you could just see everything. I know that's a long time ago, but our code goes back almost that far. Our philosophy until quite recently has been "just because a method is visible to you, it doesn't mean it's published for your use." If you use public methods that we consider internal, you may be out of luck. Note that not all .NET languages support the public/private distinction.

Very recently, we have started changing things to be internal and using InternalsVisibleTo, which has its own problems. Personally, I like the older view: we'll tell you what you can safely use and you may be scr***d if you use something else. Of course, that means we would have to do better at telling people what to use. I agree that this class looks like it's there to be used, primarily because of the namespace it ended up in.

However, we currently **do not have** a published binary API for accessing the framework. We do have a reflection-based API, which is what we suggested that the 3rd party runners use.

Let's start from what we **intend** third parties to use and build from there.

**Comment by CharliePoole** [comment] 2016-01-11 04:59
Our published documentation regarding the framework API is probably relevant to this discussion: https://github.com/nunit/dev/wiki/Framework-Api

I don't think we want to add ITestAssemblyRunner to that API because it requires users to work with a specific version of the framework. I think we should use it to build things that those users can use themselves.

None of this resolves the question of whether we should add a new method to the ITestAssemblyRunner interface. But I think it puts it in perspective: we should add it IFF there is a net benefit to us in doing our work.

Neil: if this were a published interface we wanted others to use, I would completely agree with you that we should add it so as to make it easy for them to use.

Now that you have highlighted the question, I'm wondering why we have it. I think I felt the driver would use it, and it may even have done so at one time.

**Comment by CharliePoole** [comment] 2016-01-11 05:12
I sent a note to the 3rdparty-runners list asking if anyone is using the interface.

**Comment by oznetmaster** [comment] 2016-01-16 09:57
As I mentioned in #1187, I actually implemented this as a new interface ITestAssemblyRunner2, which derives from ITestAssemblyRunner.  The new RunAsync with a callback is in the new interface.

This provides full backward compatibility, and does not change the existing interface at all

**Comment by CharliePoole** [comment] 2016-01-16 17:13
Do you mean you are doing the work of this issue in the branch for fixing #1187 or only that you implemented it in your own private code? This issue is an "idea" and we have not yet decided it should be a feature or exactly how it should be done if it is a feature.

**Comment by oznetmaster** [comment] 2016-01-16 20:16
I meant in my own code.

However, I always try to implement so it could be a PR if later desired,  Do not like to revisit things later if not necessary.

I do not develop in a branch, since my code base is not a branch, but a totally separate code base.

If you remember, I use a program to back port to the repo when I want to submit code to the actual code base.

**Comment by CharliePoole** [comment] 2016-01-16 22:16
I had forgotten that you back port changes that way. I suppose that inclines you more toward doing as much as possible in one merge, whereas we tend to try to work in smaller bits. Just keep the review process in mind - we can only digest so much at once.

**Comment by rprouse** [comment] 2020-05-18 18:30
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 18:30 UTC
Labels: is:idea
