### ISSUE TITLE
Can't test object type with constraint 

### ISSUE THREAD

**Issue by TobiasSekan** [nunit/nunit#2649] opened 2018-01-08 15:12 UTC
Hello, I can't test object types with a constraint, but the classic assert is still working

```csharp

enum TestEnum : ushort
{
    one = 0x01,
    two = 0x02
}

// test is okay
Assert.AreEqual(typeof(ushort), typeof(TestEnum).GetEnumUnderlyingType());

// test failed
//
// Expected: <System.Uint16>
//  But was: <System.RuntimeType>
//
Assert.That(typeof(TestEnum).GetEnumUnderlyingType(), Is.TypeOf<ushort>());
```

**Comment by CharliePoole** [comment] 2018-01-08 15:59
What platform and what nunit version please?

**Comment by mikkelbu** [comment] 2018-01-08 20:40
Hi @TobiasSekan. I would say that this is expected. In the classic assertion you are just comparing two types. The constraint "_tests whether the actual value is of the type supplied as an argument or a derived type._" and the type of the value `typeof(TestEnum).GetEnumUnderlyingType()` is `System.RuntimeType`.

Similar the following would also fail (with the same kind of message)
```
Assert.That(typeof(string), Is.TypeOf<string>());
```
whereas
```
Assert.That("", Is.TypeOf<string>());
```
would work. You could always rephrase the constraint as `Assert.That(typeof(TestEnum).GetEnumUnderlyingType(), Is.EqualTo(typeof(ushort)));`

**Comment by rprouse** [comment] 2018-01-09 02:32
Good catch @mikkelbu. I am going to close this as `not a bug`. @TobiasSekan I can see the confusion, but effectively your first parameter is `TypeOf<Type>` not `ushort`.

**Closed by rprouse** 2018-01-09 02:32 UTC

**Comment by TobiasSekan** [comment] 2018-01-09 05:47
Okay, thank you for the information
