### ISSUE TITLE
dotnet-test-nunit - issues with non public methods decorated with e.g. SetupAttribute

### ISSUE THREAD

**Issue by danielwertheim** [nunit/nunit#1657] opened 2016-07-11 19:26 UTC
I have a base-class which defines this:

``` csharp
[SetUp]
protected void Init()
{
    Sync = new AutoResetEvent(false);
    OnBeforeEachTest();
}

protected virtual void OnBeforeEachTest() { }
```

When converting this from "traditional" NUnit tests running in an .Net4.5 lib, to `dotnet-test-nunit` and `NUnit 3.4.1` I need to make the member decorated with the attribute `public`.

**Comment by rprouse** [comment] 2016-07-11 19:43
I assume that SetUp is not run if the method is protected?

**Comment by danielwertheim** [comment] 2016-07-11 19:49
Exactly, that's why I had to make it `public`. But that was not necessary in a non .net core project running 3.4.1 in .Net4.5

The repo and the test project is here: https://github.com/danielwertheim/mynatsclient/blob/master/src/MyNatsClient.IntegrationTests/ClientIntegrationTests.cs

**Comment by rprouse** [comment] 2016-07-11 19:58
This is still the right repository for this issue. We wrote a lot of our own Reflection methods for the Portable version of the NUnit framework, so we likely have a problem there.

**Comment by wilhen01** [comment] 2017-03-09 09:29
I've just run into this myself. Making everything public is an easy workaround but it'd be nice to have this fixed going forward

**Comment by rprouse** [comment] 2017-09-19 23:18
I am closing this as a duplicate of #2448 which has a bit more up to date information.

**Closed by rprouse** 2017-09-19 23:18 UTC
Labels: is:bug, pri:high
