### ISSUE TITLE
Missing reference to nunit.framework with NUnit 3.4.1 NuGet package

### ISSUE THREAD

**Issue by bunnu** [nunit/nunit#1766] opened 2016-08-24 07:35 UTC
# Issue
When upgrading an existing project with NUnit v3.4.0 to v3.4.1 the reference to nunit.framework is removed. Same problem exists, when creating a new project and add NUnit 3.4.1 via NuGet. 
In both cases Visual Studio complains about missing namespace NUnit.

I'm using Visual Studio 2015 Professional Update 3 (14.0.25425.01) on Windows 10 x64.

# Steps to reproduce
1. Create a new C# Console Application
2. Add NUnit 3.4.1 via NuGet
3. Add using directive 
```c#
 using NUnit.Framework
```
=> nunit.framework doesn't shows up in Solution Explorer -> References
=> namespace NUnit isn't found

**Comment by CharliePoole** [comment] 2016-08-24 14:04
I am unable to duplicate this problem, except by checking the wrong project for installation of the reference. Is it possible that's what you are doing?

**Comment by bunnu** [comment] 2016-08-24 14:18
The NuGet package is installed on the correct project. If i downgrade the package to v3.4.0 the test project is working. If I update back to v3.4.1 the project isn't working anymore.

Take a look at this screenshots:

Sample-Project with NUnit 3.4.0
![340](https://cloud.githubusercontent.com/assets/5147219/17933865/002b7146-6a16-11e6-8006-f1bfe430c491.png)

NuGet-Dialog for Updating to NUnit 3.4.1
![nuget update](https://cloud.githubusercontent.com/assets/5147219/17933900/22413dc4-6a16-11e6-9323-ef589034f5bd.png)

Sample-Project after updating to NUnit 3.4.1
![341](https://cloud.githubusercontent.com/assets/5147219/17933915/3923b508-6a16-11e6-8ed1-420ea265db16.png)

**Comment by CharliePoole** [comment] 2016-08-24 14:23
I tested what you described under "Steps to Reproduce" - the problem does not occur for me - the reference is added. I'll try again using the upgrade scenario.

**Comment by NikolayPianikov** [comment] 2016-08-24 14:31
@bunnu It could be an issue of VS NuGet Package manager. Try to remove manually the NUnit reference in packages.config of this project and install package again

**Comment by bunnu** [comment] 2016-08-25 06:18
@NikolayPianikov manually remove NUnit and reinstall the package also didn't solve the problem. I even downgraded the NUnit package manager to the previous version.

@CharliePoole  the problem occurs in the scenario described in "Steps to Reproduce" as well as in the upgrade scenario.

**Comment by rprouse** [comment] 2016-08-26 13:33
@bunnu, I followed your steps and I cannot reproduce. I also believe that if everyone was not able to update to 3.4.1, we would have a flood of issues. 3.4.1 has been downloaded over 140,000 times.

I think you probably have an issue with your Visual Studio or NuGet installation, so I am going to close this as Can't Reproduce. Feel free to add comments if you can figure out anything else you might be doing differently. We will see them and do our best to help you.

Here are my repro steps using Visual Studio 2015 Update 3 with all updates applied. Is there anything you are doing differently?

1 - Create new class library,

![image](https://cloud.githubusercontent.com/assets/493828/18006573/268fa704-6b6e-11e6-8f5f-7b39a1d55b1d.png)

2 - Add NUnit 3.4.0 NuGet package,

![image](https://cloud.githubusercontent.com/assets/493828/18006621/60152210-6b6e-11e6-831f-a7658b73bf0b.png)

3 - Create a simple test and run tests using the adapter

![image](https://cloud.githubusercontent.com/assets/493828/18006675/ad36fa50-6b6e-11e6-9d03-0e0e680de6ee.png)

4 - Right click and **Manage NuGet Packages for Solution**
5 - Go to **Updates**
6 - Click on NUnit and install

![image](https://cloud.githubusercontent.com/assets/493828/18006741/0d3fa91a-6b6f-11e6-85b3-5cbbc03da640.png)

7 - Check the version of NUnit installed, it is 3.4.1

![image](https://cloud.githubusercontent.com/assets/493828/18006779/5d26d1ce-6b6f-11e6-9073-af70a0144644.png)

8 - Run tests again to make sure everything works,

![image](https://cloud.githubusercontent.com/assets/493828/18006830/9ad025f2-6b6f-11e6-9932-4e8d3a5e413c.png)

**Closed by rprouse** 2016-08-26 13:33 UTC

**Comment by bunnu** [comment] 2016-08-29 07:22
Thanks for your support. Unfortunately I still get the error, even if I follow the steps as @rprouse described. I've got a lot of other NuGet packages, which all don't produce reference errors. It's kind of mysterious why this error only appears with NUnit V3.4.1 package. I'll wait for the next NUnit or NuGet release and hope the problem doesn't appears anymore.

**Comment by rprouse** [comment] 2016-08-29 07:27
@bunnu I am guessing, but the copy of NUnit in your NuGet cache might be corrupt. Try clearing your cache. I'm on my phone so don't have the steps handy, but you should be able to find it with Google.

**Comment by bunnu** [comment] 2016-08-29 11:22
@rprouse I already deleted the NUGet cache last Friday because You and Charlie couldn't reproduce the error. Just now I again deleted the cache (C:\Users\<username>\.nuget\packages) and hurray: NUnit 3.4.1 NUGet package is working! 

So you are right, it seems to be a corrupt NUGet -package. It's some kind of mysterious. Why did my first cache clean up didn't solve the problem and isn't NUGet checking the checksum of each package?

Nevertheless, thanks a lot for your support and your work on NUnit.

**Comment by dchinn** [comment] 2016-09-21 03:54
In fact, i just encountered the same problem.  very annoying.  It was working, then it was not.
I was able to get it to work by removing the following line from the .csproj file:

<Private>True</Private>

It was an inadvertent change from a merge, and it was added to the nunit reference element.

**Comment by dchinn** [comment] 2016-09-21 03:56
hmmm... that line didn't render in the editor.  here is a screen shot of the diff.

![image](https://cloud.githubusercontent.com/assets/10609776/18697285/9cd71b3a-7f74-11e6-8340-785fab44788e.png)

**Comment by CharliePoole** [comment] 2016-09-21 06:04
@dchinn I edited your first comment so the xml tags display. If you look at it in the editor, you'll see how to do it.

If your reference is not being copied to where it can be found when running the tests, then of course it won't be found. NuGet is supposed to set this up on install and AFAIK generally does. However this got changed, it doesn't appear to be an NUnit problem.

**Comment by BavyaR** [comment] 2018-02-23 10:48
Hi friends, I facing one problem please provide me a solution.
## _My Problem:_
       Am trying to XSD validate for XML files by using BizUnit with Nunit interface.
//**this is my code**
`using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.Services.BizTalkApplicationFramework.BizUnit;
using NUnit.Framework;
using System.IO;
using System.Xml;
using System.Xaml;

namespace BizTalkUnitTest
{
    [TestFixture]
    public class TestPO
    {
        public TestPO()
        {
        }
        [Test]
        public void File_Setup()
        {
            // Stopping and Starting BizTalkHostInstance
            BizUnit bizUnit = new BizUnit(@"C:\Users\demo\Desktop\Dunovant_test\Dunovant_test\Dunovant_test\Test_2_POSystem.xml");
            bizUnit.RunTest();
        }
        [Test]
        // [ExpectedException(typeof(XML))]
        public void Schema_Validation()
        {
            // Stopping and Starting BizTalkHostInstance
            BizUnit bizUnit = new BizUnit(@"C:\Users\demo\Desktop\Dunovant_test\Dunovant_test\Dunovant_test\XSD_Validation.xml");
            bizUnit.RunTest();
        }
        //PO_testcase
        [Test]
        public void Xpath_Validation()
        {
            // Stopping and Starting BizTalkHostInstance
            BizUnit bizUnit = new BizUnit(@"C:\Users\demo\Desktop\Dunovant_test\Dunovant_test\Dunovant_test\PO_testcase.xml");
            bizUnit.RunTest();
        }
    }
}`  
![nunit_error](https://user-images.githubusercontent.com/36071904/36590381-84df2240-18b4-11e8-95e5-430b6d951fc3.png)


--> i bemused. what can i do??
--> Please provide me a solution ...

**Comment by mikkelbu** [comment] 2018-02-23 12:31
Hi @BavyaR 
Which version of the nunit framework are you referencing in the tests? The gui looks like the GUI for NUnit2, but I think that the error is different if you open a dll containing NUnit3 tests. On my machine it is something like
![image](https://user-images.githubusercontent.com/1007631/36594245-a8f1e71a-189d-11e8-9e02-0f9c88f6c3b1.png)

Have you remember to compile the dll after adding the tests? (and are you compiling in debug)

**Comment by BavyaR** [comment] 2018-02-23 16:43
Hi Mikkel, thanks for your replay :-) ...

1) Am using Nunit V-3.5
2) After build the C# code, I couldn't call the respective dll in Nunit Interface. 

_Note:-_
While calling dll in Nunit interface - i got the assemble error(mentioned above screen shoot)

**Comment by CharliePoole** [comment] 2018-02-23 18:21
It's not at all possible to run NUnit 3 tests in the NUnit GUI, which is for NUnit V2.

**Comment by marjisound** [comment] 2018-09-13 11:37
With NUnit 3.5.0 I still had the problem. I removed the reference (so csproj was modified). And then undid the change in csproj using git. And now its working.

**Comment by AriaZLi** [comment] 2019-11-19 20:29
I had the same problem after left a project for 6 months.  It was a headache. I solved it by going to References -> nunit.framework. In the Properties, I changed Specific Version from true to false. Then it all worked again.
