### ISSUE TITLE
Consuming ITestAction

### ISSUE THREAD

**Issue by NUnitTester** [nunit/nunit#2103] opened 2017-03-29 18:33 UTC
I have some problems how it works. Perhaps you can help me out.

`public class MyActionAttribute : Attribute, ITestAction`

- Constructor with the same parameters is called more than one time. This might be a problem but depends on the next point. BeforeTest and AfterTest is called once.
- I cannot pass data from the attribute to the test. This is my need. The solution i have tried was 
`object[] attrs = method.GetCustomAttributes(typeof(MyActionAttribute), true);`
but the object that is delivered is not the one which is used for calling BeforeTest and AfterTest.
The interface ITest has no member to the object of the test, so I see no chance to set properties of the testobject from the methods BeforeTest and AfterTest as an alternative way.

**Comment by CharliePoole** [comment] 2017-03-29 19:04
You have no control over when or how often the constructor of an Attribute is called. That's not a limitation of NUnit - it's just a part of the strangeness of Attributes! They get constructed when they are needed.

The `ITestAction` interface gives you an `ITest` to work with. `ITest` provides information about the test. Hypothetically, you could use the `Properties` member to add a property, but because of __when__ an action attribute is used, that wouldn't necessarily have any effect. (And if you just wanted to change a property, there's `PropertyAttribute` for that purpose.)

The idea of an action attribute is to perform some action immediately before and immediately after a test is run. That's all it is supposed to do. If you want to modify a test, there are other interfaces to use, like `IApplyToTest`.

Can you post some code - even if it doesn't work - that shows what you are actually trying to do?

**Comment by NUnitTester** [comment] 2017-03-30 15:44
public class LoginActionAttribute : Attribute, ITestAction
{
  public LoginActionAttribute(string userName, string passWord)
  {
    UserName = userName;
    PassWord = passWord;
  }

  public Session Session { get; private set; }

  void ITestAction.BeforeTest(ITest test)
  {
    Session = Login(UserName, PassWord, Culture);
  }

  void ITestAction.AfterTest(ITest test)
  {
    Logout(Session);
  }

  ...
}

-------------------------------------    
    
public Session Session { get; set; }

[Test]    
[LoginAction("User1", "Password", "de-DE")]  
public void MethodWithLogin1()
{
  // Session should be set by LoginActionAttribute and can here be used
}

**Comment by NUnitTester** [comment] 2017-03-30 15:49
This will not work. The thing is to use something like aspect oriented programming to add common functionality without using inheritance. Every method can have othe users and other logins.
This would be a nice way to do. But there must be a way to give the information in the attribute to the test. The other way I have documented in the first note does not work because more than one attribute constructors a called.

**Comment by CharliePoole** [comment] 2017-03-30 16:04
Yes... Test Actions were designed to give you something very much like aspect oriented programming. The key difference is that you are required to mark each place where the code will be run by use of an attribute. What you are trying to do seems reasonable.

You don't show a definition of UserName and Password, but I assume they are properties of the attribute, since they are used in the Before method.

You create a Session, which is another property of the Attribute. The problem is that you probably want to access the Session from your test fixture, where it is not available. That's not the way to do it. If you use reflection to access the Attribute, you get a different instance of the attribute from that which was used to log in. I'll pause here so you can tell me if I have understood the problem before I go further...

**Comment by NUnitTester** [comment] 2017-03-30 16:16
Yes, that's it. UserName and Password are String Properties, not important I thought.
Two possible ways:
- Access the attribute to get the session. Does not work at all because .Net Framework.
- Pass the value from the Methods of the Attribute to the Test. - I see up to now no way because I have no object which I can ask if has a Session Property as shown in my example.

The only way out is in my eyes to give the two Methods BeforeTest and AfterTest a second parameter with Type object what is the current test object. Then get the Session-Property of the test by reflection and set the value in BeforeTest to the session und null in AfterTest.

**Comment by jnm2** [comment] 2017-03-30 16:20
If it was me I'd try to get `Session` as an argument to the test method if at all possible because that's the cleanest strictly from a code design standpoint.

**Comment by NUnitTester** [comment] 2017-03-30 16:28
@jnm2  Two problems with this approach (I think you are talking about testcase or values-Attribute):
- time of creating is much before running the test and all tests not only the decided one
- my latest news was that testcases are static, not dynamic - this is an open feature or is it implemented in 3.6?
- Logout is missing or must be done in TearDown, so it is an unsymmetric approach. I really don't like something unsymmetric. An it must be done in every test class again.

Test Action would be a nice symmetric approach with one implementation only.

**Comment by jnm2** [comment] 2017-03-30 16:35
I don't mean that you'd stop using the attribute for symmetric cleanup and teardown, but that the attribute would also inject the session value into the test method's `Session` parameter. To do this, `LoginActionAttribute` would implement `ITestBuilder`.

**Comment by NUnitTester** [comment] 2017-03-30 16:40
Can you please make an example with the LoginAction how to do?

**Comment by CharliePoole** [comment] 2017-03-30 16:49
@jnm2 The`ITestBuilder`  approach won't work because it would involve logging the user on at the time the test is constructed, rather than before the each execution.

Action Attributes were invented to do this sort of thing. However, in moving from NUnit 2 to 3, some of the functionality got lost - or at least became harder to access.

Here is how to do it... it's not very pretty...

1. Create an interface like `IAcceptSession` with a publicly settable Session property.
2. You can either decorate the interface with the `LoginActionAttribute` or keep it on each method. Obviously, if you use more than one user/password, it has to be per method.
3. Every class that contains methods using this action must implement `IAcceptSession`
4. In your before method, cast `ITest.Fixture` to the interface and set the session.

An alternative would be to derive from an abstract class rather than implement an interface. That's slightly easier because you only have to implement the property once but it means you can't inherit your fixtures from any other Type, since C# only supports single inheritance.

**Comment by jnm2** [comment] 2017-03-30 16:53
@CharliePoole Oh right. It would make a nice feature request though, if `ITestBuilder` could specify a value provider for an argument rather than specifying the value of the argument. The value provider would be executed at execution time to obtain the value.

**Comment by NUnitTester** [comment] 2017-03-30 17:00
Thanks. ` ITest.Fixture` was my missing link. Of course, interface is the nicer way.

**Comment by CharliePoole** [comment] 2017-03-30 17:22
@jnm2 That's a possible approach to dynamic test cases. See #7.

**Comment by CharliePoole** [comment] 2017-03-30 17:27
@NUnitTester I agree. What you describe would be a way to implement something to replace ITestAction entirely. We'd like to do that because its implementation is a remnant of V2 architecture that we keep working only with some difficulty. We kept it because it's the only way we have to create attributes that apply to lower level tests, similar to aspect-oriented programming.

**Comment by CharliePoole** [comment] 2017-04-03 04:34
I don't see any more to do with this, so I'm closing it. We can re-open if I've missed anything.

**Closed by CharliePoole** 2017-04-03 04:34 UTC

**Comment by NUnitTester** [comment] 2017-04-05 10:35
I only want to clearify how I think it would be a good way to use ITestActions-Attributes:

`IReadOnlyList<Attribute> attrs = TestContex.TestActions.GetOfType(typeof(MyTestAction));
MyTestAction action = attr[0] as MyTestAction;
Session s = action.Session;
string userName = action.UserName;`

**Comment by CharliePoole** [comment] 2017-04-05 18:12
@NUnitTester That approach would reverse how NUnit normally works.

In general, a Test does not know about it's own attributes. Rather, the attribute knows about the tests. NUnit itself invokes the attribute and allows it to modify the test. Now the test has the information that was transmitted by the attribute.

Another approah is possible, where tests examine their own attributes, but that's not how NUnit is written. I think it's important to figure out how to meet your needs while maintaining the design structure of NUnit otherwise .we make things confusing.

Also, the whole notion of TestAttributes is intended to __avoid__ the need for your test to know which attributes are applied to it.
