### ISSUE TITLE
TestCaseSource unable to pass one element byte array

### ISSUE THREAD

**Issue by m-wilczynski** [nunit/nunit#1851] opened 2016-10-18 16:28 UTC
**NUnit version:**  3.5.0
**Runner**: NUnit3TestAdapter 3.4.1
**Environment**: Visual Studio 2015 Pro Update 1

I'm having troubles using one element byte array passed to NUnit test with `TestCaseSourceAttribute`.

How to reproduce:

```
public class Test
    {
        private static List<byte[]> _byteArrays = new List<byte[]>
        {
            new byte[] { 80 }, // - works fine with commented out
            new byte[] { 80, 75 },
            new byte[] { 80, 75, 03 }
        };

        [Test]
        [TestCaseSource("_byteArrays")]
        public void TestStuff(byte[] byteArray)
        {
            Assert.IsFalse(false);
        }
    }
```

When you run `TestStuff` it will attempt to test things in seperate tests like this:

![nunit](https://cloud.githubusercontent.com/assets/6330789/19486757/ec8547d2-955f-11e6-866f-0132fb608532.jpg)

It clearly seems that first element is treated as an `System.Byte` instead of `System.Byte[]`.

Error produced by NUnit tells it clearly:

> Result Message:System.ArgumentException : Object of type 'System.Byte' cannot be converted to type 'System.Byte[]'

Any ideas on fixing this?
Thanks!

**Comment by rprouse** [comment] 2016-10-18 17:58
This was reported in #1327 and was supposed to have been fixed in PR #1354, but I can confirm that this is still happening using v3.5 of the framework and the console runner.

As a temporary workaround, you can change your source to

```C#
private static IEnumerable _byteArrays = new object[]
{
    new TestCaseData(new byte[] { 80 }), // - works fine with commented out
    new byte[] { 80, 75 },
    new byte[] { 80, 75, 03 }
};
```

Thanks for the report.

**Comment by GCichosz** [comment] 2017-03-01 16:09
Can I grab this issue?

**Comment by CharliePoole** [comment] 2017-03-01 20:50
@GCichosz I assigned it to you.

It's a tricky issue. I suggest first ensuring we have sufficient tests to cover all the cases that may arise.

Basically, this problem comes up with all array types. In this case, with a byte array being passed...

 * If the method requires a byte[], that should be used as the argument to the (single) test case.
 * If the method requires a __single__ argument of type byte, then we should generate one test case for each member of the array
 * If the method requires (for example) 3 arguments __all of type byte__ and the array length is 3, then we should generate one test case with the three arguments.

It gets even more complicated when the argument type is object, because an object[] __is__ an object. So, in that case we can't be sure we have done it right.

When in doubt, write a test! 😄

**Comment by GCichosz** [comment] 2017-03-28 10:51
As I can see, I don't have time for this issue lately, so you can unassign me. I'll come back to it when I have time, and it's still available.

**Comment by ChrisMaddock** [comment] 2017-03-28 11:03
No worries - thanks for the update! Hope things calm down for you soon. 😄

**Closed** 2017-07-12 16:04 UTC
Labels: is:bug, pri:high
