### ISSUE TITLE
NUnit should properly distinguish between .NET 4.0 and 4.5

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#244] opened 2014-09-23 16:31 UTC
This issue came up in discussing #237. See comments there.

The problem:

NUnit-console is normally compiled to target .NET 2.0 and when it sees an assembly built with .NET 4.0/4.5 it runs tests in another process. This worked well through .NET 4.0 but 4.5 and subsequent releases introduced several problems, which we'd like to resolve in this issue. All these problems are basically caused by the fact that 4.5 is a _replacement_ for 4.0 on any machine where it is installed, as opposed to being installed side by side. (That's a Good Thing because side-by-side has it's own problems, but it is the root of the problems we are seeing.)

1. When examining the assembly, NUnit only looks at the version of the framework that it targets. Because 4.0 and 4.5 use the same version number, it treats everything as 4.0.

2. When NUnit looks for what runtimes are installed on a machine, it is able to detect 4.5. (This appears to work correctly, but should be verified. If it sees 4.5, then it offers (in the Gui menu) to run the tests under either 4.0 or 4.5. If it only sees 4.0, then it only offers 4.0. (This also seems to work correctly, but should be verified)

3. When creating a process in which to invoke nunit-agent, NUnit uses an environment variable to ask for a runtime using the version number. If only 4.0 is installed on the machine, we get 4.0 behavior If 4.5 is installed, we get 4.5 behavior. That's a problem when 4.5 is installed and the user has asked to target 4.0. Either we should not promise 4.0 behavior in item 2 above, or we should issue a warning, or we should give the user true 4.0 behavior.

We didn't deal with this in the past, primarily because it didn't come up as an issue, but also because it was thought that there is no way to give 4.0 behavior once 4.5 is installed. Rob's research on #237 indicates that there is a way to tell the 4.5 assemblies - or at least some classes - to emulate 4.0 behavior at the time the AppDomain is created. We should do that to the extent possible and also document to what extent it is possible.

**Comment by rprouse** [comment] 2015-06-23 03:37
I've run into a bit of a chicken and egg problem with this issue and could use some suggestions. 

In order to determine if an assembly targets .NET 4.5 so that we can disable 4.0 compatibility mode, I use reflection on the test assembly to get the `TargetFrameworkAttribute` and parse the `FrameworkName` attribute. I have added this into `DefaultTestAssemblyBuilder` because that is where we have the `Assembly` loaded.

The problem is, in order to turn off 4.0 compatibility mode, we need to use the value I retrieve from `FrameworkName` to set the `AppDomainSetup.TargetFrameworkName` when we create the app domain to load and run the tests. We are loading the Assembly inside of the AppDomain, so that is too late.

I don't want to create another AppDomain and load the Assembly another time just to inspect this one attribute, but I can't think of an alternative. Any ideas? Am I missing an earlier load of the assembly? We have the ReflectionDomain in `DriverService`, but I need to add the info to the test's PackageSettings to use later in the `AppDomainSetup`, but I don't see any way to pass that sort of information into the `IFrameworkDriver`.

Do I need to just bite the bullet and create an AppDomain to check the attribute right before I create the test AppDomain?

**Comment by jcansdale** [comment] 2015-06-23 13:14
Hi Rob,

I've had a similar challenge with TestDriven.Net. I needed to examine
a target assembly before deciding which test runner to execute tests
with (in a fresh app domain). To begin with I did some premature
optimization and used some custom IL reading code.

I later did some performance tests and discovered that creating a new
app domain and using Assembly.ReflectionOnlyLoadFrom can actually be
surprisingly fast. There was no point in having extra IL reading code
to maintain, so I dropped it.

Regards,
Jamie.

--
http://www.testdriven.net
http://twitter.com/jcansdale
http://weblogs.asp.net/nunitaddin

**Comment by CharliePoole** [comment] 2015-06-23 14:12
Do we know for sure that the property has to be set before loading the assembly? If .NET is checking it dynamically, it could be possible to set it after the assembly is loaded. Is this documented? If not, maybe you can run a quick experiment to find out.

If it has to be set before loading, then I would do the extra ReflectionOnlyLoad for now. If / when we start using mono.cecil, we could improve this.

Ideally, I'd like to see us pre-reading the assembly only once. We now do it twice: once when we create the new process (AssemblyReader) and once when we get a driver (RO Load). My hope would be to use mono.cecil at the earliest time and just add settings to the package.

One easy out for now would be to not check this at all, but set the property if the 4.0 framework was specified on the command line. We would document that this is the only way to get 4.0 behavior if 4.5 is installed on the machine.

Charlie

**Comment by jcansdale** [comment] 2015-06-23 15:50
> Do we know for sure that the property has to be set before loading the assembly? If .NET is checking it
> dynamically, it could be possible to set it after the assembly is loaded. Is this documented? If not, maybe
> you can run a quick experiment to find out.
>
I've had a dig around and it looks like the key to the different
behavior is the following internal class:
System.Runtime.Versioning.BinaryCompatibility

Here is one of its methods:
private void AddQuirksForFramework(TargetFrameworkId
builtAgainstFramework, int buildAgainstVersion);

It appears this class is initialized very early and setting the
TargetFrameworkName for the app domain will be the only way to change
it.

Regards,
Jamie.

--
http://www.testdriven.net
http://twitter.com/jcansdale
http://weblogs.asp.net/nunitaddin

**Comment by rprouse** [comment] 2015-06-23 17:31
Jamie,

Thanks, I found that method when I was first trying to figure out the
original issue that spawned this issue :) I was tearing my hair out trying
to figure out why the URI constructor was behaving differently in NUnit
than on the command line :) Before that, I never knew that there was a
quirks mode :)

Charlie, your 'easy out' isn't quite right. The issue is that 4.5
assemblies are running in 4.0 quirks mode because NUnit is not compiled
4.5. We need to detect that a test assembly was compiled to target > 4.0
and disable the quirks mode when we create the AppDomain. We might actually
want to always set the TargetFramework attribute on the AppDomainSetup just
in case their are additional quirks modes going forward.

Rob

On 23 June 2015 at 11:50, jcansdale <notifications@github.com> wrote:

> > Do we know for sure that the property has to be set before loading the
> assembly? If .NET is checking it
> > dynamically, it could be possible to set it after the assembly is
> loaded. Is this documented? If not, maybe
> > you can run a quick experiment to find out.
> >
> I've had a dig around and it looks like the key to the different
> behavior is the following internal class:
> System.Runtime.Versioning.BinaryCompatibility
>
> Here is one of its methods:
> private void AddQuirksForFramework(TargetFrameworkId
> builtAgainstFramework, int buildAgainstVersion);
>
> It appears this class is initialized very early and setting the
> TargetFrameworkName for the app domain will be the only way to change
> it.
>
> Regards,
> Jamie.
>
> --
> http://www.testdriven.net
> http://twitter.com/jcansdale
> http://weblogs.asp.net/nunitaddin
>
>
>
>
> On 23 June 2015 at 15:12, CharliePoole <notifications@github.com> wrote:
> >
> > Do we know for sure that the property has to be set before loading the
> assembly? If .NET is checking it dynamically, it could be possible to set
> it after the assembly is loaded. Is this documented? If not, maybe you can
> run a quick experiment to find out.
> >
> > If it has to be set before loading, then I would do the extra
> ReflectionOnlyLoad for now. If / when we start using mono.cecil, we could
> improve this.
> >
> > Ideally, I'd like to see us pre-reading the assembly only once. We now
> do it twice: once when we create the new process (AssemblyReader) and once
> when we get a driver (RO Load). My hope would be to use mono.cecil at the
> earliest time and just add settings to the package.
> >
> > One easy out for now would be to not check this at all, but set the
> property if the 4.0 framework was specified on the command line. We would
> document that this is the only way to get 4.0 behavior if 4.5 is installed
> on the machine.
> >
> > Charlie
> >
> > —
> > Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/244#issuecomment-114554334>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by jcansdale** [comment] 2015-06-23 19:12
I actually need to implement exactly the same feature in TestDriven.Net.
Shall I post the utility class I use here when I'm done? We can then
compare notes/do a code review. :)

Regards,
Jamie.

--
http://www.testdriven.net
http://twitter.com/jcansdale
http://weblogs.asp.net/nunitaddin

**Comment by rprouse** [comment] 2015-06-23 19:15
Sure, I don't mind sharing :) If my wife lets me have some computer time
tonight, I should have something working soon :)

On 23 June 2015 at 15:12, jcansdale <notifications@github.com> wrote:

> I actually need to implement exactly the same feature in TestDriven.Net.
> Shall I post the utility class I use here when I'm done? We can then
> compare notes/do a code review. :)
>
> Regards,
> Jamie.
>
> --
> http://www.testdriven.net
> http://twitter.com/jcansdale
> http://weblogs.asp.net/nunitaddin
>
>
>
> On 23 June 2015 at 18:31, Rob Prouse <notifications@github.com> wrote:
>
> > Jamie,
> >
> > Thanks, I found that method when I was first trying to figure out the
> > original issue that spawned this issue :) I was tearing my hair out
> trying
> > to figure out why the URI constructor was behaving differently in NUnit
> > than on the command line :) Before that, I never knew that there was a
> > quirks mode :)
> >
> > Charlie, your 'easy out' isn't quite right. The issue is that 4.5
> > assemblies are running in 4.0 quirks mode because NUnit is not compiled
> > 4.5. We need to detect that a test assembly was compiled to target > 4.0
> > and disable the quirks mode when we create the AppDomain. We might
> actually
> > want to always set the TargetFramework attribute on the AppDomainSetup
> just
> > in case their are additional quirks modes going forward.
> >
> > Rob
> >
> >
> > On 23 June 2015 at 11:50, jcansdale <notifications@github.com> wrote:
> >
> > > > Do we know for sure that the property has to be set before loading
> the
> > > assembly? If .NET is checking it
> > > > dynamically, it could be possible to set it after the assembly is
> > > loaded. Is this documented? If not, maybe
> > > > you can run a quick experiment to find out.
> > > >
> > > I've had a dig around and it looks like the key to the different
> > > behavior is the following internal class:
> > > System.Runtime.Versioning.BinaryCompatibility
> > >
> > > Here is one of its methods:
> > > private void AddQuirksForFramework(TargetFrameworkId
> > > builtAgainstFramework, int buildAgainstVersion);
> > >
> > > It appears this class is initialized very early and setting the
> > > TargetFrameworkName for the app domain will be the only way to change
> > > it.
> > >
> > > Regards,
> > > Jamie.
> > >
> > > --
> > > http://www.testdriven.net
> > > http://twitter.com/jcansdale
> > > http://weblogs.asp.net/nunitaddin
> > >
> > >
> > >
> > >
> > > On 23 June 2015 at 15:12, CharliePoole <notifications@github.com>
> wrote:
> > > >
> > > > Do we know for sure that the property has to be set before loading
> the
> > > assembly? If .NET is checking it dynamically, it could be possible to
> set
> > > it after the assembly is loaded. Is this documented? If not, maybe you
> > can
> > > run a quick experiment to find out.
> > > >
> > > > If it has to be set before loading, then I would do the extra
> > > ReflectionOnlyLoad for now. If / when we start using mono.cecil, we
> could
> > > improve this.
> > > >
> > > > Ideally, I'd like to see us pre-reading the assembly only once. We
> now
> > > do it twice: once when we create the new process (AssemblyReader) and
> > once
> > > when we get a driver (RO Load). My hope would be to use mono.cecil at
> the
> > > earliest time and just add settings to the package.
> > > >
> > > > One easy out for now would be to not check this at all, but set the
> > > property if the 4.0 framework was specified on the command line. We
> would
> > > document that this is the only way to get 4.0 behavior if 4.5 is
> > installed
> > > on the machine.
> > > >
> > > > Charlie
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/nunit/nunit/issues/244#issuecomment-114554334>.
> > >
> >
> >
> >
> > --
> >
> > Rob Prouse
> >
> >
> >
> > I welcome VSRE emails. Learn more at http://vsre.info/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nunit/nunit/issues/244#issuecomment-114581773>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/244#issuecomment-114614045>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by rprouse** [comment] 2015-06-24 00:18
Jamie,

If you want to crib off my code or code review, it is up at
https://github.com/nunit/nunit/pull/705. You are welcome to it if yours
isn't done yet.

Rob

On 23 June 2015 at 15:14, Rob Prouse <rob@prouse.org> wrote:

> Sure, I don't mind sharing :) If my wife lets me have some computer time
> tonight, I should have something working soon :)
>
> On 23 June 2015 at 15:12, jcansdale <notifications@github.com> wrote:
>
>> I actually need to implement exactly the same feature in TestDriven.Net.
>> Shall I post the utility class I use here when I'm done? We can then
>> compare notes/do a code review. :)
>>
>> Regards,
>> Jamie.
>>
>> --
>> http://www.testdriven.net
>> http://twitter.com/jcansdale
>> http://weblogs.asp.net/nunitaddin
>>
>>
>>
>> On 23 June 2015 at 18:31, Rob Prouse <notifications@github.com> wrote:
>>
>> > Jamie,
>> >
>> > Thanks, I found that method when I was first trying to figure out the
>> > original issue that spawned this issue :) I was tearing my hair out
>> trying
>> > to figure out why the URI constructor was behaving differently in NUnit
>> > than on the command line :) Before that, I never knew that there was a
>> > quirks mode :)
>> >
>> > Charlie, your 'easy out' isn't quite right. The issue is that 4.5
>> > assemblies are running in 4.0 quirks mode because NUnit is not compiled
>> > 4.5. We need to detect that a test assembly was compiled to target > 4.0
>> > and disable the quirks mode when we create the AppDomain. We might
>> actually
>> > want to always set the TargetFramework attribute on the AppDomainSetup
>> just
>> > in case their are additional quirks modes going forward.
>> >
>> > Rob
>> >
>> >
>> > On 23 June 2015 at 11:50, jcansdale <notifications@github.com> wrote:
>> >
>> > > > Do we know for sure that the property has to be set before loading
>> the
>> > > assembly? If .NET is checking it
>> > > > dynamically, it could be possible to set it after the assembly is
>> > > loaded. Is this documented? If not, maybe
>> > > > you can run a quick experiment to find out.
>> > > >
>> > > I've had a dig around and it looks like the key to the different
>> > > behavior is the following internal class:
>> > > System.Runtime.Versioning.BinaryCompatibility
>> > >
>> > > Here is one of its methods:
>> > > private void AddQuirksForFramework(TargetFrameworkId
>> > > builtAgainstFramework, int buildAgainstVersion);
>> > >
>> > > It appears this class is initialized very early and setting the
>> > > TargetFrameworkName for the app domain will be the only way to change
>> > > it.
>> > >
>> > > Regards,
>> > > Jamie.
>> > >
>> > > --
>> > > http://www.testdriven.net
>> > > http://twitter.com/jcansdale
>> > > http://weblogs.asp.net/nunitaddin
>> > >
>> > >
>> > >
>> > >
>> > > On 23 June 2015 at 15:12, CharliePoole <notifications@github.com>
>> wrote:
>> > > >
>> > > > Do we know for sure that the property has to be set before loading
>> the
>> > > assembly? If .NET is checking it dynamically, it could be possible to
>> set
>> > > it after the assembly is loaded. Is this documented? If not, maybe you
>> > can
>> > > run a quick experiment to find out.
>> > > >
>> > > > If it has to be set before loading, then I would do the extra
>> > > ReflectionOnlyLoad for now. If / when we start using mono.cecil, we
>> could
>> > > improve this.
>> > > >
>> > > > Ideally, I'd like to see us pre-reading the assembly only once. We
>> now
>> > > do it twice: once when we create the new process (AssemblyReader) and
>> > once
>> > > when we get a driver (RO Load). My hope would be to use mono.cecil at
>> the
>> > > earliest time and just add settings to the package.
>> > > >
>> > > > One easy out for now would be to not check this at all, but set the
>> > > property if the 4.0 framework was specified on the command line. We
>> would
>> > > document that this is the only way to get 4.0 behavior if 4.5 is
>> > installed
>> > > on the machine.
>> > > >
>> > > > Charlie
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/nunit/nunit/issues/244#issuecomment-114554334>.
>> > >
>> >
>> >
>> >
>> > --
>> >
>> > Rob Prouse
>> >
>> >
>> >
>> > I welcome VSRE emails. Learn more at http://vsre.info/
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/nunit/nunit/issues/244#issuecomment-114581773>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nunit/nunit/issues/244#issuecomment-114614045>.
>>
>
>
>
> --
>
> Rob Prouse
>
>
>
> I welcome VSRE emails. Learn more at http://vsre.info/
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by jcansdale** [comment] 2015-06-24 09:43
Hi Rob,

I have similar challenges. I've just installed myself in a coffee shop to get some guaranteed computer time ;)

Thanks for the link. I've going to be working on a version that works with .NET 4.5, but still compiles/runs on .NET 2.0.

Regards,
Jamie.

**Comment by OliverHallam** [comment] 2015-06-24 16:50
We've been having some trouble with our tests - I believe it's caused by the same bug.

It's taken a couple of days of head-scratching though so I hope mentioning it here will make this come up in a google search and might save someone else from the same pain before coming to this conclusion.

The particular case we have is with MEF open generic support which was added in .NET 4.5

Here's a minimal test that reproduces the problem:

    using System.ComponentModel.Composition;
    using System.ComponentModel.Composition.Hosting;
    
    using NUnit.Framework;
    
    interface IRepository<T>
    {
        T Get();
    }
    
    [Export(typeof(IRepository<>))]
    class Repository<T> : IRepository<T>
    {
        public T Get()
        {
            return default(T);
        }
    }

    public class TestClass
    {
        [Test]
        public void Test()
        {
            var container = new CompositionContainer(new TypeCatalog(typeof(Repository<>)));
            var repo = container.GetExportedValue<IRepository<string>>();
        }
    }

Some decompiling shows that support for open generics is ultimately toggled based on the Environment.TargetFrameworkVersion

    public bool IsPartDiscoverable()
    {
      if (AttributeServices.IsAttributeDefined<PartNotDiscoverableAttribute>((ICustomAttributeProvider) this._type))
      {
        CompositionTrace.DefinitionMarkedWithPartNotDiscoverableAttribute(this._type);
        return false;
      }
      if (!BinaryCompatibility.TargetsAtLeast_Desktop_V4_5 && this._type.ContainsGenericParameters)
      {
        CompositionTrace.DefinitionContainsNoExports(this._type);
        return false;
      }
      if (!this.HasExports())
      {
        CompositionTrace.DefinitionContainsNoExports(this._type);
        return false;
      }
      return this.AllExportsHaveMatchingArity();
    }

It's good to hear that work is in progress, but I suspect it'll come too late for us to avoid a hacky workaround in the short term!

**Comment by rprouse** [comment] 2015-06-24 19:54
Oliver, if you are already using NUnit 3, you might want to set an ignore on your tests. The fix for this is done. I am going to make a few small tweaks to it today and the next beta will hopefully be out next week.

**Comment by OliverHallam** [comment] 2015-06-24 21:41
Rob,

Thanks, that's great news!

We're still on NUnit 2, although if there's a compelling reason (which this is) to upgrade to a beta release , then I see no reason why we couldn't.

This bug was blocking a big refactoring from being checked in (it behaved in the resharper runner which was used for development).  Unfortunately it affects all of our integration tests so muting them isn't viable in this case.

I've implemented a horribly hacky workaround with a stub .NET 4.5 exe that calls the Main method in the standard console runner.  That sets up the appdomain, and "/domain=none" uses it to run the tests.

I was hoping that would tide us over until the next release, but if it's only a week or so away then I suspect it'll be better to leave the change hanging for a bit longer - I don't want to be supporting a hack like that if I can help it!

**Comment by rprouse** [comment] 2015-06-24 21:53
If you are using Resharper, you may want to hold off on moving to NUnit 3
since it isn't supported in Resharper yet. Sorry.

**Closed** 2015-06-25 01:28 UTC
Labels: is:feature, pri:high
