### ISSUE TITLE
TestContext.Out is not always updated

### ISSUE THREAD

**Issue by espenalb** [nunit/nunit#2182] opened 2017-05-22 15:31 UTC
As mentioned in my comment on #51 - this "bug" is specifically related to cases where we use NUnit for _integration testing_, not unit testing. I know that this is not the primary target of NUnit, but since NUnit is very well suited for this task, it would be nice if this issue was fixed.

In our integration test of embedded hardware, we typically connect to an external system as the first step in `FixtureSetUp` (or better by using a `ITestAction` and an attribute). The connect sometimes needs to start a new thread - listening for incoming data from the device.

Incoming data is typically logged using TestContext.Out.

The problem is that when NUnit generates the xml output, the textwriter used for logging device data was created before the test - and therefore the data "belongs" to the FixtureSetUp section, not the TestCase section.

Our workaround is that we use a test attribute that updates the TextWriter so that we _force_ the logger to use the "current" text writer.
Code is quite simple - but it really is a hack for something NUnit _could_ have solved for us.

Here is our code:

```
 public class DecorateTestBeforeAndAfterAttribute : Attribute, ITestAction
    {
        private readonly Logger _logger = new Logger("NUnit");
        public void BeforeTest(ITest test)
        {
            NUnitLoggerService.SetOutWriter(TestContext.Out);
            _logger.LogInfo($"--- BeforeTest '{TestContext.CurrentContext?.Test?.FullName}'");
        }

        public void AfterTest(ITest test)
        {
            var message = $"--- AfterTest {TestContext.CurrentContext?.TestResult()}";
            var logLevel = Equals(TestContext.CurrentContext?.Result?.Outcome, ResultState.Success)
                ? eLogLevel.Log
                : eLogLevel.Warn;
            _logger.Log(logLevel, message);
            NUnitLoggerService.SetOutWriter(null);
        }

        public ActionTargets Targets => ActionTargets.Suite | ActionTargets.Test;
    }
```
and then in our logger implementation, we have this code:
```
 public class NUnitLoggerService : ILoggerService
    {
        private static TextWriter _outWriter;

        public void WriteLine(eLogLevel logLevel, string logMsg)
        {
            if (Debugger.IsAttached)
            {
                Debug.WriteLine(logMsg);
            }
            else if (logLevel < eLogLevel.Debug) // Do not write Debug messages to Progress
            {
                TestContext.Progress?.WriteLine("[Progress]:" + logMsg);
            }
            var writer = _outWriter ?? TestContext.Out ?? Console.Out;
            writer.WriteLine(logMsg);
        }

        public static void SetOutWriter(TextWriter outWriter)
        {
            _outWriter?.Flush();
            _outWriter = outWriter;
        }
    }
```

**Comment by CharliePoole** [comment] 2017-05-22 15:46
I don't see this issue as particularly related to any kind of testing - unit or otherwise.

My first inclination was to say this is simply not a bug. The test context you are using does not "belong" (your quotes) to the fixture, it __actually__ belongs to the fixture! Each test in NUnit runs in its own context. Fixtures are tests, hence they have a context. The TestFixtureSetUp and TestFixtureTearDown run in the context of the fixture. Each test case within the fixture runs in its own context.

However, I'm not closing this right now, because of your statement test NUnit could have fixed this for us." I'd like to be clear what it is that you would like us to do. Note that any general solution has to work in the context of parallel test methods. As far as I can tell without seeing the code to your logger, It doesn't seem that your workaround would be usable in that case.

**Comment by espenalb** [comment] 2017-05-22 15:56
Ok. Let me try to explain better.
We use NUnit for integration test - and typicalle start a new thread (For example in OneTimeSetUp) _before_ the first test case. This thread receives and logs data from our Device Under Test (DUT), let's call it tDeviceListener. (We also observe this when the "tDeviceListener" is inside an infite async Task.Run call as well.

The first test case then starts and writes to the device. The write happens in the context of the testcase, so the write is logged in the testcase. However - the tDeviceListener (using `TestContext.Out.WriteLine`) "belongs" to OneTimeSetup context - so when it logs the device response, the response appears in the OneTimeSetup section of the xml file. 

For an integration test, _time_ is really the grouping factor - so in _our_ case we want the request and response to be logged "together" _in_ the test case. This falls apart in a scenario where multiple test cases execute in parallell, but that is not a possible scenario in _our_ integration tests.

I hope this made it more clear. The reason why I stated that NUnit could have handled this was that my expectation was the TestContext.Out (And TestContext.Current) would reflect the currently running test at all times. Since it does not, we were forced to implement the workaround as described above...

Hope that this was more clear. :-)

**Comment by CharliePoole** [comment] 2017-05-22 20:06
Actually, that's what I already understood about your issue. What I do not know is what you would ask us to do. We can't just change the general way NUnit works without taking __all__ valid patterns of use into account. Since some people do have parallel cases, we have to allow for that possibility.

Try to imagine what feature would help you and describe it. Try to avoid making fundamental changes to existing features.

**Comment by CharliePoole** [comment] 2017-05-22 20:08
Also, would your request pertain only to immediate output?

**Comment by rprouse** [comment] 2017-07-25 00:18
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Closed by rprouse** 2017-07-25 00:18 UTC

**Comment by cosminstirbu** [comment] 2018-12-04 09:47
Hello,

We're having a similar issue and going through the discussion above, it's not clear why the `TestContext.Out` is not updated as the test goes through each of the hooks.

Our tests start writing to  `TestContext.Out` from a `OneTimeSetUp` hook and they continue writing to it as the tests progress (during each `Test`). However the output is not displayed, and I assume that's because somehow `TestContext.Out` is not updated :-?.

Are there any other alternatives that don't involve adding a new custom attribute on each test?

Thank you,
Cosmin

**Comment by CharliePoole** [comment] 2018-12-04 14:35
@cosminstirbu Not sure what you mean by a "OneTimeSetUp hook" - the word "hook" is what is confusing me. 

If you mean that you write to `TestContext.Out` in a method marked `[OneTimeSetUp]` then that output is saved as part of the test (fixture) that contains the `OneTimeSetUpAttribute`. If you subsequently write  to `TestContext.Out` from your individual test methods, each of those is also saved as part of the output of the particular test. That is, all these writes do not necessarily go to the same place.

I say "not necessarily" because it's possible for some runner to capture them and put them back together as part of some output. So the final result depends to a large extent on how you are running your tests. For example, the console runner puts them all back together for display in the console window. OTOH, the VS test adapter doesn't do that.

I think your main problem is that you are trying to use `TestContext.Out` to do something it isn't designed to do: display output immediately. We do have `TestContext.Progress`, which __does__ display it's output immediately but once again the implementation depends on the runner you use. All the framework is responsible to do is send the output back to the runner.

**Comment by CharliePoole** [comment] 2018-12-04 16:30
That's exactly correct and is what you "should" see - for some definition of "should." :smile: 

As explained, it's up to the runner to decide what output to show where. The NUnit framework (this repo) is sending the output to the runner, which is the VS IDE helped by the NUnit adapter.

The Test Explorer paradigm is __only__ concerned with individual test cases. So there is no place to show output except for that produced by an individual test case. NUnit's adapter, like any adapter, "adapts" to this situation by only giving the IDE what it wants.

In the case of something really bad that happens outside of an individual test, the adapter forces it to your attention by writing it to the VS "output window." That's the only place in the IDE to show output that is not specific to a test.

Does that make sense? IOW this is not an NUnit issue but a Test Explorer + IDE issue. If I've misunderstood and we are talking here about individual test output, then hit me again!

**Comment by cosminstirbu** [comment] 2018-12-08 11:58
I'll provide a more simple code snippet that hopefully makes it more clear what I mean:

```
using NUnit.Framework;
using System.Threading;

namespace Tests
{
    public class Tests
    {
        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            var thread = new Thread(
                () => 
                {
                    while (true)
                    {
                        TestContext.Out.WriteLine("Expected Output Line");
                        Thread.Sleep(100);
                    }
                } );
            thread.Start();
        }

        [Test]
        public void Test()
        {
            TestContext.Out.WriteLine("Test");
            Thread.Sleep(5000);
            TestContext.Out.WriteLine("Test");
        }

        [Test]
        public void Test2()
        {
            TestContext.Out.WriteLine("Test2");
            Thread.Sleep(5000);
            TestContext.Out.WriteLine("Test2");
        }

        [Test]
        public void Test3()
        {
            TestContext.Out.WriteLine("Test3");
            Thread.Sleep(5000);
            TestContext.Out.WriteLine("Test3");
        }

        [Test]
        public void Test4()
        {
            TestContext.Out.WriteLine("Test4");
            Thread.Sleep(5000);
            TestContext.Out.WriteLine("Test4");
        }
    }
}
```

So in the example above, I would expect that at least some of the "Expected Output Line" to be printed as part of an individual test output, since the thread executes concurrently tests themselves, so `TestContext.Out` should return a `Test` specific context while the thread executes concurrently with a test.
 
Thank you,
Cosmin

**Comment by CharliePoole** [comment] 2018-12-08 12:48
Sorry to say your expectation isn't how it works. :smile:

Older versions of NUnit (pre-3.0) associated output with tests by simply observing which test was running at the time the output was received.

With the introduction of parallel test execution, that approach was no longer possible. Every test (where test means an individual test case, a fixture or some other type of suite) has its own test context. The output from that context arrives at the runner tagged with the name of the "test" that produced it. We go to a lot of trouble, in fact, to avoid the very behavior you want to rely upon.

There is another hitch in your code sample. I'm not really sure without testing it that your new thread retains the test context of the initial thread. Behavior here could vary depending on the runtime you are targeting. You could create a test of this for your own situation to be sure.

In your example, are you able to ascertain whether the output from the thread you start goes anywhere at all?

**Comment by cosminstirbu** [comment] 2018-12-08 14:06
Indeed, if I run the test above using `dotnet test PATH_TO_CSPROJ --logger:trx` then I can't see the "Expected Output Line" text nowhere in the `.trx` file.

However if I run it using `nunit3-console.exe PATH_TO_DLL` then in the `TestResult.xml` I can see the output under the `test-suite` element, but not under the `test-case` element, which as you've mentioned it is by design.

I guess for my use-case, I'll need to inject somehow `TestContext.Out` just like the initial workaround suggests.

Thanks again.

**Comment by CharliePoole** [comment] 2018-12-08 14:57
Most Microsoft test software looks only at individual test cases. This is the greatest mismatch any adapter for a framework based on the Composite pattern has to overcome. Since virtually all open source test frameworks were originally based on that pattern, it's a rather big problem.

I think NUnit runs into the problem more frequently than other frameworks because of its use of hierarchical setup and teardown as well as its support for parallelism.

I'm glad you explained the problem. I'll keep it in mind for the future.

**Comment by CharliePoole** [comment] 2018-12-08 15:06
You should also keep in mind that since console stdout is written to the test result, the output from the fixture is not available until all the tests have already run.
