### ISSUE TITLE
NUnit3 Is.EquivalentTo in certain case performs much worse than for NUnit2

### ISSUE THREAD

**Issue by anat0li** [nunit/nunit#2852] opened 2018-05-11 18:16 UTC
The following testing code being executed for the NUnit 3.10.1 framework 

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Diagnostics;
using NUnit.Framework;

namespace NUnitTest1
{
    [TestFixture]
    public class TestClass1
    {
        [Test]
        public void TestEquivalentToPerformance()
        {
            const int listLength = 20000;
            var expected = Enumerable.Range(0, listLength).Select(i => $"inte{i}");
            var actual = expected.ToList();
            var sw = Stopwatch.StartNew();
            Assert.That(actual.SequenceEqual(expected));
            sw.Stop();
            Console.WriteLine($"SequenceEqual\t{sw.Elapsed}.");
            sw.Restart();
            Assert.That(expected, Is.EquivalentTo(actual));
            sw.Stop();
            Console.WriteLine($"Is.EquivalentTo\t{sw.Elapsed}.");
            actual = actual.OrderByDescending(e => e).ToList();
            Assert.False(actual.SequenceEqual(expected));
            sw.Restart();
            Assert.That(new HashSet<string>(actual).SetEquals(expected));
            sw.Stop();
            Console.WriteLine($"SetEquals\t{sw.Elapsed}.");
            sw.Restart();
            Assert.That(expected, Is.EquivalentTo(actual));
            sw.Stop();
            Console.WriteLine($"Is.EquivalentTo reordered\t{sw.Elapsed}.");
        }
    }
}
```

outputs:

SequenceEqual	00:00:00.0076299.
Is.EquivalentTo	00:00:25.4525447.
SetEquals			00:00:00.0096878.
Is.EquivalentTo reordered	00:00:12.4085114.

The same code being executed for the NUnit 2.6 framework outputs:

SequenceEqual	00:00:00.0071261.
Is.EquivalentTo	00:00:00.1143779.
SetEquals	                00:00:00.0104875.
Is.EquivalentTo reordered	00:00:16.7547591.

In my experience a comparison of identical sequences happens quite often. For this case nunit3 implementation for Is.EquivalentTo spends 25.45 sec. to give the expected result versus 0.11 sec. spent by nunit2 framework. For the sequences in reverse order nunit3 performs slightly better ( 12.4 sec vs 16.7 sec ), but IMHO it does not compensate slow performance for the first case.

**Comment by mikkelbu** [comment] 2018-05-11 18:35
Hi @anat0li. I've added ``` before and after the code to format it correctly. I think that this is a duplicate of #2799, but I'll have to examine it further.

**Comment by anat0li** [comment] 2018-05-11 18:41
Thank you, @mikkelbu. It looks close, but not exactly duplicate I think. Just spent some time today looking for the reason why upgrade to nunit3 showed down the projects tests execution.

**Comment by anat0li** [comment] 2018-05-11 19:00
@mikkelbu reporting of the differences is supposed to start after finding some difference. An average project has hundreds or thousands of tests; and none of them normally fails. It does not seem to be logical spending huge amount of time in preparation for the worse.

**Comment by CharliePoole** [comment] 2018-05-11 21:13
@anat0li That's a rather good point.

**Comment by jnm2** [comment] 2018-05-27 13:00
@anat0li With the use of a hash table, the nice part is that the most efficient way to determine the difference also has the side effect of handing us the perfect info to build the message.

**Comment by rprouse** [comment] 2020-05-18 19:27
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 19:27 UTC
