### ISSUE TITLE
Process isolation per test

### ISSUE THREAD

**Issue by xavierzwirtz** [nunit/nunit#3378] opened 2019-09-24 23:19 UTC
We are currently using one of the solutions in #2280 to run each of our tests inside of their own AppDomain. This has worked surprisingly smoothly, however the upgrade to .NET Core is requiring a new solution.  Our app has a large deal of legacy code that precludes running tests without isolation. We need some sort of test isolation, process isolation per test looks like the best solution currently.

**Comment by xavierzwirtz** [comment] 2021-05-26 19:25
I am now using [Tmds.ExecFunction](https://github.com/tmds/Tmds.ExecFunction) to run tests in sub processes, using `DelegatingTestCommand` to override `Execute`. This is pretty seamless, especially with [this pr](https://github.com/tmds/Tmds.ExecFunction/pull/14) that adds automatic attaching of the debugger to the sub process.

The only issue is that since we are overriding `Execute`, none of NUnit's logic for things like `Teardown`, `Setup`, or any custom `PropertyAttribute` fire. It would be nice if process isolation was implemented inside of NUnit so that tests using process isolation were not operating in their own special world apart from NUnit's facilities.

**Comment by stevenaw** [comment] 2023-05-13 02:04
Closing as this looks to be a duplicate of https://github.com/nunit/nunit/issues/3788
While this one is older, it has received less discussion and as a result the other one now has more "history" to it.

**Closed by stevenaw** 2023-05-13 02:04 UTC
