### ISSUE TITLE
Test runner doesn't link my custom property to the <test-case> but adds it to the <test-suite>

### ISSUE THREAD

**Issue by sonudavidson** [nunit/nunit#3591] opened 2020-07-08 08:11 UTC
Hi, 
I'm using NUnit 3 with SpecFlow 3. 
I'm adding a custom property called "ScenarioContent"
Here is an example
Scenario Outline: Calculator 23
  Given I have entered <first> into the calculator
  And I have also entered <second> into the calculator
  When I press add
  Then the result should be <result> on the screen
  
  Examples:
  | first | second | result |
  | 20    | 30     | 50     |
  | 85    | 15     | 100    |

While the code-behind the feature is generated correctly (which looks like this)

`[NUnit.Framework.DescriptionAttribute("Calculator 23")]
        [NUnit.Framework.TestCaseAttribute("20", "30", "50", null, TestName="Calculator 23_20_30_50")]
        [NUnit.Framework.Property("ScenarioContent", @"Scenario Title:
Calculator 23

Context:
In order to avoid silly mistakes
As a math idiot
I want to be told the sum of two numbers

Background:
Given I have few background services to be started

Steps:
Given I have entered 20 into the calculator
And I have also entered 30 into the calculator
When I press add
Then the result should be 50 on the screen

")]
        [NUnit.Framework.TestCaseAttribute("85", "15", "100", null, TestName="Calculator 23_85_15_100")]
        [NUnit.Framework.Property("ScenarioContent", @"Scenario Title:
Calculator 23

Context:
In order to avoid silly mistakes
As a math idiot
I want to be told the sum of two numbers

Background:
Given I have few background services to be started

Steps:
Given I have entered 85 into the calculator
And I have also entered 15 into the calculator
When I press add
Then the result should be 100 on the screen

")]
       `public virtual void Calculator23(string first, string second, string result, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculator 23", null, exampleTags);
#line 386
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
this.FeatureBackground();
#line hidden
#line 387
  testRunner.Given(string.Format("I have entered {0} into the calculator", first), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 388
  testRunner.And(string.Format("I have also entered {0} into the calculator", second), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 389
  testRunner.When("I press add", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 390
  testRunner.Then(string.Format("the result should be {0} on the screen", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }`

But the result file that is generated by the NUnit3 test runner looks this way. 

` <test-suite type="ParameterizedMethod" id="0-1075" name="Calculator23" fullname="Com.Vanderlande.SFP.Tests.CalculatorFeature.Calculator23" classname="Com.Vanderlande.SFP.Tests.CalculatorFeature" runstate="Runnable" testcasecount="2" result="Passed" start-time="2020-07-08 08:09:03Z" end-time="2020-07-08 08:09:03Z" duration="0.005026" total="2" passed="2" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
                  <properties>
                    <property name="Description" value="Calculator 23" />
                    <property name="ScenarioContent" value="Scenario Title:&#xD;&#xA;Calculator 23&#xD;&#xA;&#xD;&#xA;Context:&#xD;&#xA;In order to avoid silly mistakes&#xD;&#xA;As a math idiot&#xD;&#xA;I want to be told the sum of two numbers&#xD;&#xA;&#xD;&#xA;Background:&#xD;&#xA;Given I have few background services to be started&#xD;&#xA;&#xD;&#xA;Steps:&#xD;&#xA;Given I have entered 20 into the calculator&#xD;&#xA;And I have also entered 30 into the calculator&#xD;&#xA;When I press add&#xD;&#xA;Then the result should be 50 on the screen&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;" />
                    <property name="ScenarioContent" value="Scenario Title:&#xD;&#xA;Calculator 23&#xD;&#xA;&#xD;&#xA;Context:&#xD;&#xA;In order to avoid silly mistakes&#xD;&#xA;As a math idiot&#xD;&#xA;I want to be told the sum of two numbers&#xD;&#xA;&#xD;&#xA;Background:&#xD;&#xA;Given I have few background services to be started&#xD;&#xA;&#xD;&#xA;Steps:&#xD;&#xA;Given I have entered 85 into the calculator&#xD;&#xA;And I have also entered 15 into the calculator&#xD;&#xA;When I press add&#xD;&#xA;Then the result should be 100 on the screen&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;" />
                  </properties>
                  <test-case id="0-1073" name="Calculator 23_20_30_50" fullname="Com.Vanderlande.SFP.Tests.CalculatorFeature.Calculator 23_20_30_50" methodname="Calculator23" classname="Com.Vanderlande.SFP.Tests.CalculatorFeature" runstate="Runnable" seed="240080650" result="Passed" start-time="2020-07-08 08:09:03Z" end-time="2020-07-08 08:09:03Z" duration="0.002920" asserts="0">
                    <reason>
                      <message><![CDATA[A simple background step]]></message>
                    </reason>
                    <output><![CDATA[Given I have few background services to be started
-> error: A simple background step
Given I have entered 20 into the calculator
-> skipped because of previous errors
And I have also entered 30 into the calculator
-> skipped because of previous errors
When I press add
-> skipped because of previous errors
Then the result should be 50 on the screen
-> skipped because of previous errors
]]></output>
                  </test-case>
                  <test-case id="0-1074" name="Calculator 23_85_15_100" fullname="Com.Vanderlande.SFP.Tests.CalculatorFeature.Calculator 23_85_15_100" methodname="Calculator23" classname="Com.Vanderlande.SFP.Tests.CalculatorFeature" runstate="Runnable" seed="217858778" result="Passed" start-time="2020-07-08 08:09:03Z" end-time="2020-07-08 08:09:03Z" duration="0.001992" asserts="0">
                    <reason>
                      <message><![CDATA[A simple background step]]></message>
                    </reason>
                    <output><![CDATA[Given I have few background services to be started
-> error: A simple background step
Given I have entered 85 into the calculator
-> skipped because of previous errors
And I have also entered 15 into the calculator
-> skipped because of previous errors
When I press add
-> skipped because of previous errors
Then the result should be 100 on the screen
-> skipped because of previous errors
]]></output>
                  </test-case>
                </test-suite>
              </test-suite>
              <test-suite type="TestFixture" id="0-1076" name="KeywordRulesFeature" fullname="Com.Vanderlande.SFP.Tests.KeywordRulesFeature" classname="Com.Vanderlande.SFP.Tests.KeywordRulesFeature" runstate="Runnable" testcasecount="1" result="Passed" start-time="2020-07-08 08:09:03Z" end-time="2020-07-08 08:09:03Z" duration="0.042619" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="1">
                <properties>
                  <property name="Description" value="KeywordRules" />
                  <property name="qcTestPlanPath" value="TestPlan\in multiple" />
                  <property name="qcTestLabPath" value="TestLab\in multiple\" />
                  <property name="qcTestSet" value="KeywordRules" />
                </properties>
                <test-case id="0-1077" name="KeywordRules01" fullname="Com.Vanderlande.SFP.Tests.KeywordRulesFeature.KeywordRules01" methodname="KeywordRules01" classname="Com.Vanderlande.SFP.Tests.KeywordRulesFeature" runstate="Runnable" seed="595591960" result="Passed" start-time="2020-07-08 08:09:03Z" end-time="2020-07-08 08:09:03Z" duration="0.041864" asserts="1">
                  <properties>
                    <property name="TestCaseName" value="FeatureFile Keyword Rules 01" />
                    <property name="Description" value="KeywordRules 01" />
                    <property name="ScenarioContent" value="Scenario Title:&#xD;&#xA;KeywordRules 01&#xD;&#xA;&#xD;&#xA;Context:&#xD;&#xA;A Feature file with no TestSet and Testplanpath and labpath in multiple lines&#xD;&#xA;&#xD;&#xA;Objective:&#xD;&#xA;To check if the single line keywords are truncated and&#xD;&#xA;multi line keywords are not truncated&#xD;&#xA;&#xD;&#xA;Steps:&#xD;&#xA;Given I have entered 50 into the calculator&#xD;&#xA;And I have also entered 70 into the calculator&#xD;&#xA;When I press add&#xD;&#xA;Then the result should be 120 on the screen&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;" />
                    <property name="Category" value="mytag" />
                  </properties>
                  <output><![CDATA[Given I have entered 50 into the calculator
-> done: CalculatorSteps.GivenIHaveEnteredSomethingIntoTheCalculator(50) (0,0s)
And I have also entered 70 into the calculator
-> done: CalculatorSteps.GivenIHaveAlsoEnteredIntoTheCalculator(70) (0,0s)
When I press add
-> done: CalculatorSteps.WhenIPressAdd() (0,0s)
Then the result should be 120 on the screen
-> done: CalculatorSteps.ThenTheResultShouldBe(120) (0,0s)
]]></output>
                </test-case>`

I'd expect the attribute <ScenarioContent> added to each of the example <test-case> and not all to the <test-suite>.

This looks like an issue.

**Comment by sonudavidson** [comment] 2020-07-08 10:17
This is the result file
![image](https://user-images.githubusercontent.com/5096397/86906972-a0d45c80-c114-11ea-9ac0-958ddf4b696e.png)

This is the feature scenario outline
![image](https://user-images.githubusercontent.com/5096397/86907193-f577d780-c114-11ea-9741-9204084ce0c8.png)


This is the code behind the feature file
![image](https://user-images.githubusercontent.com/5096397/86907074-cbbeb080-c114-11ea-8c73-4b842a60e69e.png)
![image](https://user-images.githubusercontent.com/5096397/86907116-d9743600-c114-11ea-9ced-4ba5dbc3d1a0.png)

**Comment by ChrisMaddock** [comment] 2020-07-14 19:40
Hi @sonudavidson,

In NUnit terms, this is worked as intended. `Calculator23` is your suite, and there are two different `TestCaseAttributes` creating two test cases inside that suite. The `PropertyAttributes` are both applied to the `Calculator23` method, meaning your properties are both applied to the suite, and not the individual test cases.

`TestCaseAttribute` itself doesn't have a way to add test properties - you would need to instead use `TestCaseData`. As your NUnit code is actually generated by Specflow however, I'm not sure what the right solution is - I think you'll need to follow that up with the Specflow team.

I'll close this issue now, as I think your problem lies outside NUnit. Feel free to comment further if you think we're missing something, and we can reopen. 🙂

**Closed by ChrisMaddock** 2020-07-14 19:40 UTC
