### ISSUE TITLE
when using nunit 3 adapter for VS, my engine extensions are not being called

### ISSUE THREAD

**Issue by EtgarZ** [nunit/nunit#2576] opened 2017-11-26 11:57 UTC
Hi,
I wrote some engine extensions and put them in the addins directory, as documented.
When I run the project with nunit3-console.exe, everything work fine.
I tried to use the "nunit 3 test adapter" for visual studio 2013, and when I run the test it doesn't use my nunit engine extensions.
Is there a way to control how to run the tests, so it would include my nunit engine extensions?

**Comment by CharliePoole** [comment] 2017-11-26 13:33
That's because the adapter is not using the same engine as the console runner. It has its own copy of the engine and any extensions would have to be in some directory relative to that engine's location. You would also have to create a `.addins` file to point to the location of the extensions. This is only practical using the NuGet package, since otherwise you would have to add files in VS directories.

Closing this as a duplicate of nunit/nunit3-vs-adapter#222

**Closed by CharliePoole** 2017-11-26 13:33 UTC

**Comment by EtgarZ** [comment] 2017-11-26 17:28
How can I discover the location of the copied engine, so I can add my extensions?

**Comment by CharliePoole** [comment] 2017-11-26 17:50
It should be in the directory where NuGet has installed the adapter.

**Comment by EtgarZ** [comment] 2017-11-26 20:56
Thanks!
I found the directory and created a .addins file and addins directory with all extensions as it is in my NUnit installation folder (which works when running via console runner), but still it seems like adapter engine copy doesn't run my extension (I created TestEventListener which doesn't invoke).
Any idea why?

**Comment by CharliePoole** [comment] 2017-11-26 20:58
What are the contents of your `.addins` file?

**Comment by EtgarZ** [comment] 2017-11-27 08:01
It contains the following:
addins/nunit.v2.driver.dll
addins/nunit-v2-result-writer.dll
addins/nunit-project-loader.dll
addins/vs-project-loader.dll
addins/teamcity-event-listener.dll
addins/MyEngineExtension.dll 

MyEngineExtension.dll is located in addins directory.

**Comment by CharliePoole** [comment] 2017-11-27 08:41
Just to check...

 * Your addins directory should be in the same directory as nunit.engine.dll
 * Do you actually have all the listed extensions? It should work in any case but remove those that aren't present to be sure.
 * Are you targeting the .NET framework? Extensions are not supported for other targets.

**Comment by EtgarZ** [comment] 2017-11-27 09:26
Thanks,
- My addins directory is in the same directory as nunit.engine.dll
- I have all the listed extensions in the addins directory.
- I do targeting the .NET framework.

I will give more information about what I do, maybe it will help: 
My extension opens a TCP listener and in tests code I connect to this listener as a client.
When working via console runner it works fine, so I guess that something is still missing in order to load the extension via adapter, because when running via adapter I get error that server is down.

**Comment by CharliePoole** [comment] 2017-11-27 14:14
If you have a message that server is down, doesn't that mean your extension is running in order to produce that message?

**Comment by EtgarZ** [comment] 2017-11-27 14:53
No, I will clarify myself - the error occurs in client code(Test) because there is no server listening to IP and port. That server should have been initialized in the extension code and that is why I know that extension code doesn't run.
