### ISSUE TITLE
Dll has no TestFixtures

### ISSUE THREAD

**Issue by maddo5** [nunit/nunit#1207] opened 2016-01-21 16:55 UTC
Hi,

We have a project with a number of dlls that have tests in them. One dll is being picked up and the tests are being run, but the others are failing.  If I copy the failing dlls to my local machine the tests run successfully.  Dll's are 32 bit so using --x86 parameter.  

Failing Machine: Windows 7 64bit Virtual Machine, VS2015 Update 1, .NET 4.6.1, NUnit 3.0.1
Working Machine: Windows 10 64bit, VS2015 Update 1, .NET 4.6.1, NUnit 3.0.1

Running the nunit gui on the failing machine I get "Value cannot be null. Parameter name: test". This is the stack.
   at NUnit.Gui.Model.TestEventArgs..ctor(TestAction action, TestNode test) in C:\temp\nunit-gui-master\src\nunit-gui\Model\TestEventArgs.cs:line 44
   at NUnit.Gui.Model.TestModel.LoadTests(IList`1 files) in C:\temp\nunit-gui-master\src\nunit-gui\Model\TestModel.cs:line 205
   at NUnit.Gui.Presenters.MainPresenter.OnOpenProjectCommand() in C:\temp\nunit-gui-master\src\nunit-gui\Presenters\MainPresenter.cs:line 175
   at NUnit.UiKit.Elements.MenuElement.<.ctor>b__9_0(Object <sender>, EventArgs <e>) in C:\temp\nunit-gui-master\src\nunit.uikit\Elements\MenuElement.cs:line 41
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at NUnit.Gui.Program.Main(String[] args) in C:\temp\nunit-gui-master\src\nunit-gui\Program.cs:line 84
   at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

This is the source for the tests.
    [TestFixture] 
    public class SpreadsheetTests
    {
        public SpreadsheetTests()
        {
        }

        [TestCase(5, "E")]
        public void GetColumnNameTests(int column, string expectedResult)
        {
              // Test code is here
        }
    }

Any idea on why it fails on one machine but not the other?

Thanks
maddo

**Comment by CharliePoole** [comment] 2016-01-21 17:03
There has been no gui release for nunit 3.0. Can you duplicate this problem with the nunit3 console?

**Comment by maddo5** [comment] 2016-01-21 17:30
I ran the gui from the source here https://github.com/nunit/nunit-gui which I thought was for 3?

Yes running nunit3-console.exe I get "Dll name has no test fixtures" on the failing machine. On the working machine it runs the tests as expected.

**Comment by rprouse** [comment] 2016-01-21 18:59
Can you give us errors our output from nunit3-console? Callstacks from there would be more useful than from the GUI which is currently under heavy development.

**Comment by maddo5** [comment] 2016-01-21 19:50
The TestResult.xml file contains this. Is this what you were after? 

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="0" result="Failed" label="Invalid" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0" engine-version="3.0.5813.39036" clr-version="4.0.30319.42000" start-time="2016-01-21 19:45:00Z" end-time="2016-01-21 19:45:00Z" duration="0.127108">
  <command-line><![CDATA[nunit3-console.exe  "TheFullDllName" --x86 --verbose]]></command-line>
  <test-suite type="Assembly" id="0-1000" name="DllName" fullname="TheFullDllName" runstate="NotRunnable" testcasecount="0" result="Failed" label="Invalid" site="SetUp" start-time="2016-01-21 19:45:00Z" end-time="2016-01-21 19:45:00Z" duration="0.023092" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
    <environment framework-version="3.0.5813.39031" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="c:\Program Files (x86)\NUnit.org\nunit-console" machine-name="VMUSBUILD05" user="user" user-domain="domain" culture="en-US" uiculture="en-US" os-architecture="x86" />
    <settings>
      <setting name="RunAsX86" value="True" />
      <setting name="WorkDirectory" value="c:\Program Files (x86)\NUnit.org\nunit-console" />
      <setting name="Verbose" value="True" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_SKIPREASON" value="Has no TestFixtures" />
      <property name="_PID" value="3728" />
      <property name="_APPDOMAIN" value="test-domain-" />
    </properties>
    <failure>
      <message><![CDATA[Has no TestFixtures]]></message>
    </failure>
  </test-suite>
</test-run>

**Comment by maddo5** [comment] 2016-01-21 19:53
Hi, 

Attached are the results of TestResult.xml. Is this what you were after?

Thanks

[TestResult.zip](https://github.com/nunit/nunit/files/99786/TestResult.zip)

**Comment by rprouse** [comment] 2016-01-21 20:01
Not the greatest error reporting on our part :-1: 

What I do see is `runstate="NotRunnable" testcasecount="0" result="Failed" label="Invalid" site="SetUp"`

I think this happens when a setup method crashes. Do you have an assembly level setup for your tests? If so, is it doing some initialization that might require specific paths, configurations, ODBC connections, etc that might not be on the build machine?

@CharliePoole can you confirm my reading of the test result? You are more familiar with the combinations and what they mean.

**Comment by maddo5** [comment] 2016-01-21 20:10
This assembly has 1 file with tests in it. I commented out all of them except 1. The code I posted in the original post at the end is literally all the code from that file (minus the actual test code for brevity sake).  The constructor is empty as posted above and there is no SetUp/TearDown or OneTimeSetUp/OneTimeTearDown attributes used.

**Comment by CharliePoole** [comment] 2016-01-22 21:46
@rprouse The message indicates that no test fixtures were found. What seems to be key is that this is a teamcity run. We know that teamcity generates an nunit project file, which may be invalid or may activate some otherwise hidden bugs in nunit.

@maddo5 We need you to run this using nunit3-console directly in order to see what happens and to rule out any teamcity problems.

**Comment by CharliePoole** [comment] 2016-01-22 21:52
@maddo5 Regarding the gui... NUnit has always been extremely conservative in terms of releasing. Even when we have a beta release, we advise people not to use it for production purposes, but only for trying out the release. All the more so for an alpha release.

This code is pre-1.0.  In our eyes, that's less than alpha, less than pre-alpha, less than communty preview, etc. In fact, it's even pre it's first binary release, because we don't think it's ready for anything except possibly reviewing and commenting on usability. I hope you will take this to heart!

I wanted to explain this at length because I know that is not the attitude of a lot of other open source projects and it's not even the attitude of some of the biggest commercial software companies. :-)

**Comment by maddo5** [comment] 2016-01-22 23:31
Hi Charlie,

Thank you for your replies. I used the gui in the hope it may have shown me something that would help me in identifying the issue.   Understand that it's still being developed.  

The attached results file above was created from the console, it's just that the location happened to be in the Teamcity work location.  The dll i was testing from that folder was created on my machine (which runs the tests successfully from the console) and I copied it to that location so that I could get the error file to send.  Given those steps I don't believe there should be any interference by what Teamcity does.  Is this a safe assumption? 

Cheers

**Comment by CharliePoole** [comment] 2016-01-23 01:47
It shouldn't matter that you are in the TeamCity work directory, provided that it's empty when you copy your files there. OTOH, if being in that directory leads to NUnit assemblies that are bundled with TeamCity being loaded then it might make a difference.

**Comment by rprouse** [comment] 2016-04-07 15:35
@maddo5 have you made any progress on this? I am marking it as confirm because we are running out of ideas. If this does not move forward, I will close as can't reproduce.

**Comment by Giganticus** [comment] 2016-06-08 11:54
"Dll name has no test fixtures" - I had this problem too on TeamCity. In my case the issue was that I'd upgraded the NUnit.Console package (to 3.2.1), but not the version of NUnit (still had 3.0.1). Running tests locally was fine as I wasn't using the runner locally, but on TeamCity, the runner is used.

**Comment by CharliePoole** [comment] 2016-06-08 13:15
Nunit 3.2.1 console and engine can run tests built against any framework version >= 3.0. However, the framework version you reference must be available or the tests can't load. Many people assume that "backward compatibility" means something else and try to just drop in the new framework without recompiling. That won't work.

**Comment by Giganticus** [comment] 2016-06-08 15:27
Sorry, what I had was actually runner 3.0.1 with framework 3.2.1.

**Comment by CharliePoole** [comment] 2016-06-08 15:31
The same applies in that case. You should have the 3.0.1 runner and engine available to run and the 3.2.1 framework available for your tests to use. However, in this case, there is no forward compatibility guarantee although I have found it works for most tests. Easiest thing to do is to upgrade the runner to always be greater than or equal to the frameworks you are using.

**Comment by rprouse** [comment] 2016-06-23 13:28
@Giganticus and @maddo5 are you still seeing this with newer versions of NUnit? I would like to close confirm issues that don't have any progress.

**Comment by maddo5** [comment] 2016-06-23 16:42
Hi @rprouse, I haven't seen it for a while. I seem to vaguely remember that the issue went away when we turned of code coverage in TeamCity and expressly named the dll's to run tests on (rather than using a wild card for all dll's).

**Comment by rprouse** [comment] 2016-06-23 17:49
@maddo5 thanks for the update. I am going to close this. If anyone can provide more info, please post it here and we can reopen.

**Closed by rprouse** 2016-06-23 17:49 UTC
Labels: status:confirm

**Comment by Giganticus** [comment] 2016-06-23 18:13
It still happens if versions are out of synch, but it's ok to close.

**Comment by sanjitmisra** [comment] 2017-03-13 18:46
I ran into the same issue. I have 2 test projects in the same solution and the solution is built on TeamCity. All tests were running fine till I decided to point the output of the different projects into a common location for easier artifact management. After this, one of the test dlls started throwing errors with NUnit console runner complaining that the dll "Has no TestFixtures". Many hours of hair pulling later I realized that I have used 2 different versions of nunit in the 2 projects. While one had 3.4.1 the other had 3.6.1. This made the project having 3.6.1 running fine while the one on 3.4.1 was erroring out. I decided to downgrade both to 3.4.1, clean the packages folder on the build server and run the job again. Luckily this time things worked as before.

So, lesson learnt is, use the same version of nunit throughout your solution. Either that or I have no clue why things stopped working at the first place and how did they come back to normal.

**Comment by CharliePoole** [comment] 2017-03-13 19:04
Just a comment ... you __can__ have projects that use different versions of NUnit in the same project. We do something like that with our own NUnit tests, except rather than different versions we have six different build targets.

What you can't have is two different `nunit.framework.dll`s in the same directory - obviously. So to have multiple frameworks, you need to use separate output directories and you should probably run in a separate process for each test assembly - which is the default.

**Comment by koilBhupat** [comment] 2017-09-27 11:48
Hi Team,
I am facing the same issue through NUnit Console. I am using NUnit 3.7.1.
I could see the value of  parameter 'site="SetUp"' in failed <test-suite ...>. My test class does have [Setup] and [OneTimeSetUp] methods. Does this indicate anything regarding the issue?

**Comment by CharliePoole** [comment] 2017-09-27 12:01
@koilBhupat This is a closed issue related to use of TeamCity and assemblies with no test fixtures. Could you explain in what way your problem is the same?

**Comment by koilBhupat** [comment] 2017-09-27 13:20
I have a test project that uses NUnit. When I am trying to execute it using NUnit console with parameter as test dll, I am facing the same error 'Has no testFixture'.

**Comment by CharliePoole** [comment] 2017-09-27 16:02
You said you are using NUnit 3.7.1 framework. What version of the console runner are you using? What is your command-line?

Of course, the message means that NUnit could not find any test fixtures. It appears when you try to run tests against an assembly that contains nothing that is recognizable as an NUnit test fixture. Can you post an example - redacted as necessary - of one of your test fixtures?

**Comment by nullpainter** [comment] 2017-11-25 01:28
@koilBhupat  - I fear I may be muddying the original issue, however if its of any use - I received the no test fixtures message when I had a NUnit mismatch. I was using NUnit 3.9.0 for my test, who's fixture inherited from a base class in a project using NUnit 3.7.1. Perhaps verify you don't have a similar problem.
