### ISSUE TITLE
NUnitLite could process multiple assemblies

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#344] opened 2014-11-08 01:16 UTC
Currently in the built-in runner in nunitlite, TextUI correctly captures multiple assemblies on the command line, but then only processes the first of them.

```
                // TODO: For now, ignore all but first assembly
                Assembly assembly = _assemblies[0];
```

Is there a reason that all assemblies provided could not be processed? It would be seem to be beneficial to be able to.

**Comment by CharliePoole** [comment] 2015-09-22 04:13
After review, we have decided to keep NUnitLite as simple as possible. Running multiple assemblies will requier use of a runner that makes use of the test engine. This is in constrast to NUnitLite, which is intended to run a single test assembly without use of the engine.

**Comment by oznetmaster** [comment] 2015-12-22 13:17
It is interesting that pretty much everything that was rejected in this discussion has now been implemented.

Given that, it would seem reasonable to revisit the base issue of allowing multiple test assemblies to be listed on the command line, and run.

In fact, my CF builds have pretty much done everything that has been done in restructuring nunitlite since the beginning (including the nunitlite runner), and including multiple test assemblies being processed from the command line, so I know it is both possible, and pretty straightforward.

**Comment by CharliePoole** [comment] 2015-12-22 17:48
@oznetmaster I don't understand the comment. This issue is about running multiple assemblies from the nunitlite command-line. As you state, we decided not to do that. I'm not sure how you can say that "pretty much everything that was rejected has now been implemented" since that's the only thing this issue is about.

Here's the current status. 
 * Self-executing NUnitLite tests run themselves and can't run anything else.
 * There is a new program that is able to run a single test from the command-line. That new program is designed for use in continuous integration and runs tests from the **desktop** command-line in all cases. I postponed implementing it for CF because the PR was getting too complex as is. It is available for both portable and silverlight tests, however.
 * The classes in the nunitlite assembly have been reorganized so that the AutoRun capability is now entirely separate from and layered on top of the TextRunner, which actually executes tests.
 * Some glitches remain. The autorun command-line options probably need to be separate from the more general options for the text runner.

We have, in fact, done many things that you suggested. But this simply was not one of them.

If your intention is to reopen the discussion about running multiple assemblies from the command-line, I suggest you do that. At this point, you have put forth only two reasons for us to consider:

1. That we have already done many things you suggested, so we may as well do this too.
2. That you have private code that does what you want.

I already commented on point 1. On point 2, I can only say that there has never been a question about whether this is possible to do, only about whether it is desirable. If you have private code that would help us understand your reasoning better, then it can only affect the discussion if you make it available to us. Alternatively, you could create a PR, but it might be better if we had some sort of discussion first.

Here is what I think we need in order to have a discussion:

1. A description of **exactly** what you are proposing. Superficially, it sounds to me like a different program from the existing nunitlite-runner, but that may be because you haven't described it.

2. An indication of who would use it and why they would need it. In particular, I'm not clear if this is a proposal for CF only or for NUnitLite in general.

Beyond that, I will suggest that your ability to influence the decision is always going to be in proportion to your willingness to pitch in and do the work. Even when proposals come from non-committers, folks who are actually willing and able to contribute to the solution while staying within our guidelines always get priority.

**Comment by rprouse** [comment] 2015-12-22 18:35
My thought is that the nunitlite.runner.exe is already too close in functionality to  nunit3-console.exe and I worry that it will begin causing confusion and support problems. Before we add any additional functionality, I would like to discuss exactly what the usage scenarios are and how they differ from nunit3-console.exe usage.

If the difference is that nunit3-console.exe does not run tests for other platforms, then I would rather see us putting in the effort to adding functionality to the agent to identify the target platform of tests and then creating test agents for those platforms. For cases like Universal Apps, .NET core or SilverLight, those agents can run on the desktop/server machine and for CF, Android, iOS, etc, I would like to see us get to a point where we can deploy tests to devices, run them and get the results, probably through a TCP channel. In other words, I would rather be tackling issues like #1138 and #362.

**Comment by oznetmaster** [comment] 2015-12-22 20:05
I agree fully with @rprouse.

It is a perfectly valid question as to why nunit3-console is not available for all platforms.  If it were, there would be no need for nunitlite.runner.

In my CF environment, this is almost the case.  I am currently working on auto deployment of the tests using SFTP, which I have available on my CF devices, although a dedicated TCP channel would work as well.

I did not use nunit3-console as the basis for this,because of its dependency on remoting and the engine.  I chose to go straight to a GUI that uses SSH and SFTP to interface to the remote device.

However, this still does not address the very simple issue of processing multiple test assemblies on the command line.  They are already allowed (no error given).  Currently, just the first one is used.  The limitation is arbitrary.

Why do this?  Because now that nunitlite allows the execution of arbitrary tests through the nunitlite.runner, and no longer restricts the test to be in a single framework, there is no reason to artificially restrict this to be a single test assembly.

I often have 5-10 test assemblies on the CF device, and want to run the tests in them selectively, either singly, or in groups.  That is why I chose to allow multiple test assemblies on the command line.  I cannot be the only person to ever want to do this within the nunitlite framework?

As to @CharliePoole about actually doing things.  I have indicated that I am very interested in doing things that are appropriate to the CF environment, whether limited to that environment or not.  I do not use nunit in any other environment, not am I likely to do so.  I would certainly assign tasks such as this to myself, if there was agreement to actually implement them.

**Comment by oznetmaster** [comment] 2015-12-22 20:19
Also, @CharliePoole, I thought I was reopneing "the discussion about running multiple assemblies from the command-line"?  That is what this issue that I originally posted has always been about.

**Comment by oznetmaster** [comment] 2015-12-22 20:26
I perhaps need to be more precise.

In the nunitlite environment, allowing multiple test assemblies on the command line would seemingly simply sequentially run the tests in those assemblies.  The test assemblies would all have been compiled for the same framework, and same environment.  The output from those tests would either be concatenated in a single output file, or perhaps in multiple files based on the test assemblies name.

This is a significant simplification from the current console/engine/agent situation, as I thought was the intent on nunitlite.

**Comment by CharliePoole** [comment] 2015-12-23 01:31
@oznetmaster I'm glad we are in agreement about using TCP and the console runner. That's our direction and has been for a long time. Where we seem to part company is that I feel very strongly that we lose a lot of time to work on the long-term solution as we attempt to make NUnitLite into something that will suit all needs.

I feel that I have to point out that you already did assign this issue to yourself, over a year ago. IIRC that was as a result of some discussion you and I had. But nothing more ever happened with it and I closed it a few months ago for that reason. It sounds (in the current discussion) as if you were expecting somebody else to do something, but I'm not sure what that was.

If you would like to re-open this and work on it, then I think you should describe what you would do and for what platforms. I'll respond separately to the description you just posted.

**Comment by CharliePoole** [comment] 2015-12-23 01:40
Comments on @oznetmaster 's proposal:

"I perhaps need to be more precise."

Thanks. :-)

"In the nunitlite environment, allowing multiple test assemblies on the command line would seemingly simply sequentially run the tests in those assemblies. The test assemblies would all have been compiled for the same framework, and same environment. The output from those tests would either be concatenated in a single output file, or perhaps in multiple files based on the test assemblies name."

 * I assume you are refering to the nunitlite-runner command-line, not that for self-executing tests.
 * As you say, all the assemblies would have to be compiled for the same runtime framework for which the particular copy of nunitlite-runner was designed, that is, all silverlight, all net.4.5, all portable, etc.
 * Sequential execution without any combination would be the easiest approach.
 * Text output would have to be concatenated.
 * XML output can't be concatenated, since that would produce an illegal XML file. We would have to add at least minimal code to combine the results into a single valid file.
 * Creating separate output files is a bit problematic if we want to keep using the --result option to specify where it goes.

"This is a significant simplification from the current console/engine/agent situation, as I thought was the intent on nunitlite."

Of course, only running one file per execution is even simpler.

**Comment by oznetmaster** [comment] 2015-12-23 02:11
Yes, I did assign this to myself, and was developing a "mini-engine" to base this on. Then you assigned the core engine to yourself.  We all agreed that using the core engine would be a consistent approach for all platforms.

Then the decision was made by you to dump the core engine.

I have been waiting for some consensus about a replacement strategy, so that I do not go "running off in my own direction again").

Perhaps I missed the arrival at that consensus?

**Comment by oznetmaster** [comment] 2015-12-23 02:15
I fully agree with everything @CharliePoole wrote in his elaboration of my description of how this would work.

If there is an agreement that this would make sense for the nunitlite-runner command line, I will assign it to myself to implement.  I would probably implement it in TextRunner, so it would be available for other nunitlite runners if desired.

**Comment by CharliePoole** [comment] 2015-12-23 02:47
@oznetmaster What do you mean by "other" nunitlite runners? That is, what's the scope of what you propose to implement versus what might be implemented by others later on.

**Comment by CharliePoole** [comment] 2015-12-23 03:00
@oznetmaster Some of the points you are agreeing with were actually intended as negatives WRT this feature. See the last two bullet points.

I could be talked into something minimalistic that allowed multiple files on the command-line provided it didn't interfere with AutoRun and didn't change the fundamental purpose of nunitlite-runner in doing CI builds. My sense, however is that you actually want a runner that runs on CF, not the CI platform.

**Comment by oznetmaster** [comment] 2015-12-23 19:49
Since I would implement the feature as in TextRunner, as a new Execute method with a bool flag indicating whether to allow multiple files on the command line, it could be used by anyone who calls TextRunner.Execute.  The bool would allow for an error to be given if there are multiple files on the command line and only one is allowed.

I would also add the error for a testAssembly being provided in the constructor, and then files being specified on the command line.  I fully agree with @CharliePoole that these things should not fail silently.

**Comment by CharliePoole** [comment] 2015-12-23 20:11
@oznetmaster Seems as if the presence or absence of a test assembly could serve as the flag without messing up TextRunner with an extra argument. Adding a guard clause to AutoRun for a null assembly argument makes sense as well.

However, my main question remains unanswered, perhaps because I have not spelled it out clearly enough: Would you plan on creating a new build of nunitlite-runner to allow executing tests from the command-line on CF devices that have a console?

If that's the plan, it would be good to test whether it can be used in the CI builds. There's a good chance that it may be useable, due to .NET's assembly unification feature, but I'm not entirely sure if that is still supported for CF in newer .NET releases. It should be easy to find out, however.

If OTOH you find that that's not possible, then I think the CI runner and the device runner will need to be entirely separate programs. For me, this would reopen the question of what we call the program and I would advocate a name like nunitlite-ci-runner for the programs that are designed to allow running tests compiled for a device on the desktop, while keeping nunitlite-runner for the programs that run entirely in the device environment.

**Comment by oznetmaster** [comment] 2015-12-24 04:14
If you remember, I already have a version of AutoRun which has been adapted to run on the CF console on the device itself.  It is more robust then the current nunitlite-runner, but basically does the same thing.  I see no reason it should not work for the CI builds as well, but would certainly test that.  There is nothing CF specific in it.

**Comment by CharliePoole** [comment] 2017-04-24 21:28
@nunit/framework-team I propose we wrap this up once and for all. From our discussion, it's clear that we want nunitlite to be for primarily for self-executing tests. A secondary use is for single assemblies that can't be self-executing because of their platform. In that case, nunitlite-runner is used to pass a single assembly to nunitlite.

To handle both cases, I propose we eliminate the detection of a file on the nunitlite command-line and let the runner do it. The runner can pass the identity of a pre-loaded assembly using a special interface, separate from AutoRun, which handles the main, self-executing case.

Comments?

**Comment by rprouse** [comment] 2017-04-25 02:39
I agree, I think the standard AutoRun should just execute the current assembly, or you should pass in the assembly (in code) that you want to execute.

**Closed** 2017-04-30 15:05 UTC
Labels: is:feature, pri:low
