### ISSUE TITLE
Add runner for Universal Apps

### ISSUE THREAD

**Issue by njale** [nunit/nunit#948] opened 2015-10-29 09:57 UTC
My unit-tests run fine in the runner from Resharper (providing I use options CopyNuGetImplementations=true in csproj). If running in nunit-console for TeamCIty I get heaps of problems, but the real show stopper has been the following:

```
System.Runtime.Serialization.SerializationException: Type 'NUnit.Framework.Api.FrameworkController' in assembly 'nunit.framework, Version=3.0.5767.14876, Culture=neutral, PublicKeyToken=2638cd05610744eb' is not marked as serializable.

Server stack trace:
at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
at NUnit.Engine.Runners.AbstractTestRunner.Load()
at NUnit.Engine.Agents.RemoteTestAgent.Load()
at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
at NUnit.Engine.ITestEngineRunner.Load()
at NUnit.Engine.Runners.ProcessRunner.LoadPackage()
at NUnit.Engine.Runners.AbstractTestRunner.Load()
at NUnit.Engine.Runners.MasterTestRunner.LoadPackage()
at NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded()
at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEventListener listener, TestFilter filter)
at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
at NUnit.ConsoleRunner.Program.Main(String[] args)
```

My project is a UniversalApp compiled for x86, running on an x64 WIndows 10 setup.

NjE

**Comment by rprouse** [comment] 2015-10-29 12:12
Even though we have compiled a portable version of NUnit for use in Universal Apps, we don't currently have a runner for Universal Apps. The current console runner is a desktop app and cannot run tests that use the portable framework.

**Comment by rprouse** [comment] 2015-10-29 13:47
@njale, I am going to rename this issue to "Add runner for Universal Apps" and assign it to the 3.0 extras milestone. If I have misinterpreted your report, please let me know :wink:

**Comment by CharliePoole** [comment] 2015-10-29 16:27
@rprouse I agree with your disposition of the issue itself, but we should investigate a bit more to see what the engine thinks it is looking at and how it is attempting to run it. I'm intrigued that it even tries at all!

**Comment by rprouse** [comment] 2015-10-29 19:25
The problem is that Portable uses our compatibility SerializableAttribute and ICallbackHandler, so it is not capable of serializing across remoting. We could add a flag to the portable framework that the driver could check so that it refuses to run tests referencing the portable framework.

**Comment by CharliePoole** [comment] 2015-10-29 19:39
I think that's more of a side issue. As we discussed on another PR, the presence of [Serialized] on this class is probably a mistake. The class is not designed to be serialized but to be referenced. It inherits from LongLivedMarshalByRefObject, which is another Compatibility class. In the Portable build, it's a dummy class because MarshalByRefObject was not available in the profile we were using originally. Is it available in the new one?

**Comment by rprouse** [comment] 2015-10-29 19:53
No, MarshalByRefObject is not available.

**Comment by CharliePoole** [comment] 2015-10-29 20:22
In any case, the not serializable error is what you get when an object is
neither serializable nor mbr.

**Comment by njale** [comment] 2015-10-30 06:34
@rprouse  To respond to your question to me above, yes you got it right. I would be happy to do some testing if you ever would need that.

**Comment by rprouse** [comment] 2015-10-30 13:06
@CharliePoole, do you think we should add a check for portable in the engine for the RC so that it will not try to run tests built with the portable framework and prevent issues like this being reported in the future?

**Comment by CharliePoole** [comment] 2015-10-30 14:57
@rprouse That's why I was wondering what the engine actually thinks it is running. In the case reported, the engine examined the assembly and decided to create a process to run it under some particular runtime. What did it see? What did it decide? Is it possible that this might actually work with a bit of tweaking or would fixing the "serialization" problem just lead to further issues.

What is confusing me is the fact that one of the portable targets is .NET 4.5. That being the case, it seems we should be able to run at least some tests that use the portable framework. Maybe not universal apps though..

Maybe some stepping through in the debugger would help. If we can't make it work, then an intelligent error message is the next best thing.

**Comment by rprouse** [comment] 2015-12-12 23:27
Not running portable tests was fixed in 3.0 and running UWP apps is part of the Xamarin runners. I am going to close this.

**Closed by rprouse** 2015-12-12 23:27 UTC
Labels: is:feature, pri:high

**Comment by njale** [comment] 2016-01-04 04:43
If running portable tests with nunit3-console.exe I get "The NUnit 3.0 driver does not support the portable version of NUnit. Use a platform specific runner."

Is this by design? If so, which runner can I use to run universal tests? I use TeamCity for continuos integration, and TeamCity relies on the console runner. 

Universal tests Works fine in Resharper runner inside VisualStudio, but I can't use that in Team City.

**Comment by CharliePoole** [comment] 2016-01-04 04:54
As @rprouse noted, we currently only support running xamarin tests using the xamarin runners. We would like to be able to run them with the console eventually.

For the xamarin runners, see nunit/nunit-xamarin

**Comment by njale** [comment] 2016-01-19 15:25
I can't compile the code as I don't have Xamarin. Are binaries available anywhere, and will they work with a regular non-Xamarin Universal App?

**Comment by rprouse** [comment] 2016-01-19 19:51
@njale I haven't tried building the Xamarin version of the Universal runner without Xamarin installed, but it will likely work. For Universal I don't think it requires any special compilers or project types, everything is just a NuGet package. Check out [Testing Xamarin Projects using NUnit 3](http://www.alteridem.net/2015/12/21/testing-xamarin-projects-using-nunit-3/) and see if it works for you.

I am currently working on a solution for running UWP tests without Xamarin. Hopefully it will be in NUnit 3.2 hopefully coming out Q1 2016.
