### ISSUE TITLE
Xml Documentation in the Nuget packages

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1922] opened 2016-12-11 18:23 UTC
@cinnamon25 commented on [Fri Dec 09 2016](https://github.com/nunit/docs/issues/146)

Can you please, include the XML Documentation in the nuget packages, so that Visual Studio shows the documentation, when I hover on a method...

---

@CharliePoole commented on [Fri Dec 09 2016](https://github.com/nunit/docs/issues/146#issuecomment-266165803)

I assume you mean in the nuget package for the framework?

---

@cinnamon25 commented on [Sun Dec 11 2016](https://github.com/nunit/docs/issues/146#issuecomment-266288108)

Yes

---

@rprouse commented on [Sun Dec 11 2016](https://github.com/nunit/docs/issues/146#issuecomment-266294313)

@cinnamon25 we do include the XML Docs for the NUnit framework in the package. Is there another project that it is missing from or are you seeing problems?

Here is a screenshot of the 3.5 release in NuGet Package Explorer

![image](https://cloud.githubusercontent.com/assets/493828/21081796/1d63feb4-bf9c-11e6-8c50-dc71500d4856.png)

**Comment by CharliePoole** [comment] 2016-12-11 18:25
I suspect that the xml is not getting copied to the output directory. Should it be in `content`?

**Comment by rprouse** [comment] 2016-12-11 19:53
I checked xUnit and Newtonsoft.json, their XML docs are the same as ours.

I also opened a test project that uses the NuGet package and I am seeing the docs,

![image](https://cloud.githubusercontent.com/assets/493828/21082823/702f17ae-bfb1-11e6-951e-f84d69c03326.png)

I am closing this as not a bug. @cinnamon25, we can reopen if you can provide steps to reproduce.

**Closed by rprouse** 2016-12-11 19:53 UTC
Labels: confirm

**Comment by CharliePoole** [comment] 2016-12-11 19:56
Fair enough!
