### ISSUE TITLE
Using NUnit.engine and GetRunner, then Load() throws FileNotFoundException: 'nunit-agent.exe could not be found.'

### ISSUE THREAD

**Issue by abelbraaksma** [nunit/nunit#2904] opened 2018-06-23 12:06 UTC
I have the following code, which mimics this post on StackOverflow:

```f#
let LoadTests() =
    let path = Assembly.GetExecutingAssembly().Location
    let package = new TestPackage(path)
    package.AddSetting("WorkDirectory", CliParser.workingDirectory)

    let engine = TestEngineActivator.CreateInstance()
    engine.WorkDirectory <- CliParser.workingDirectory

    let filterService = engine.Services.GetService<ITestFilterService>()
    let filterBuilder = filterService.GetTestFilterBuilder()
        
    // see: https://github.com/nunit/docs/wiki/Test-Selection-Language
    //filterBuilder.SelectWhere "name !~ /.*avt.*/"
    let whereFilter = filterBuilder.GetFilter()     // empty filter
        
    let runner = engine.GetRunner(package)

    if not <| isNull runner then
        // Without the following line there are no errors and no tests (should be 7500 tests)
        // With the following line: FileNotFoundException: 'nunit-agent.exe could not be found.'
        let loadedXml = runner.Load()
        printfn "Filtered tests:  %i\n" (runner.CountTestCases(whereFilter))
        let result = runner.Run(null, whereFilter)
        result
            
    else
        eprintfn "Could not load test assembly from location '%s'" path
        failwith "Unable to get a test runner"
```

I have the following references (all newest available from NuGet)

![image](https://user-images.githubusercontent.com/16015770/41809440-e3f5cbb6-76ed-11e8-9bad-ce8fb92f8382.png)

And the following packages (I think these are not all required):

```xml
<packages>
  <package id="NUnit" version="3.10.1" targetFramework="net46" />
  <package id="NUnit.Console" version="3.8.0" targetFramework="net46" />
  <package id="NUnit.ConsoleRunner" version="3.8.0" targetFramework="net46" />
  <package id="NUnit.Engine" version="3.8.0" targetFramework="net46" />
  <package id="NUnit.Extension.NUnitProjectLoader" version="3.6.0" targetFramework="net46" />
  <package id="NUnit.Extension.NUnitV2Driver" version="3.7.0" targetFramework="net46" />
  <package id="NUnit.Extension.NUnitV2ResultWriter" version="3.6.0" targetFramework="net46" />
  <package id="NUnit.Extension.TeamCityEventListener" version="1.0.4" targetFramework="net46" />
  <package id="NUnit.Extension.VSProjectLoader" version="3.7.0" targetFramework="net46" />
  <package id="NUnit.Runners" version="3.8.0" targetFramework="net46" />
  <package id="System.ValueTuple" version="4.3.0" targetFramework="net46" />
</packages>
```

Following our discussion in #2812 I had a working version, but after updating everything not anymore. I noticed that the package directories NUnit.Console and NUnit.Runners are empty (only contain a nupkg file). In the output directory I do not see `nunit-agent.exe`, but I'm not sure it needs to be there, since I already have `nunit.engine`.

I need this approach to work (as opposed to out-of-process runners), for profiling, ease of testing and most importantly, for debugging my tests, which is a pain if I need to go through NUnit GUI runner (which, btw, takes half an hour to load the tests).

**Comment by CharliePoole** [comment] 2018-06-24 02:39
To evaluate this, we would need to see the contents of the directory in which you are executing. The references and packages all influence that, but it's much easier to start with your executable, and the location of the engine assemblies and then go from there.

Not sure what you are using the console runner for, however.

**Comment by CharliePoole** [comment] 2018-06-24 02:43
I notice you are creating a default test package, which means the tests are run in a separate process per test assembly. That's why the agent is needed. You don't need the agent if you always provide a package setting to indicate you want to run in process. Since the agents are packaged with the engine, it's a bit surprising that it can't be found, however.

**Comment by abelbraaksma** [comment] 2018-06-25 09:58
@CharliePoole, thanks for looking into this. I think the relevant bits of the output dir (and running dir) look as follows (and indeed doesn't have nunit.agent.exe).

![image](https://user-images.githubusercontent.com/16015770/41843682-71bf8ffa-786e-11e8-9ac4-eedf032b5850.png)

In the project I set the working dir of the tests, because they need to load data, that working dir has no NUnit-related files.

> Not sure what you are using the console runner for, however.

The build server (TeamCity) has as recommended practice to include a NuGet package of the console runner, so that's why.

> I notice you are creating a default test package, which means the tests are run in a separate process per test assembly. That's why the agent is needed.

Interesting, I didn't know. I thought NUnit.Engine.dll to be enough to run any test. I actually prefer to run in-process for this use-case, it's easier with debugging. I'll have to try to find out how to configure it to do so.

> it's a bit surprising that it can't be found, however.

I can try removing and reinstalling the packages, maybe something went amiss, but it clearly doesn't get copied.

**Comment by CharliePoole** [comment] 2018-06-25 11:03
Most likely the problem is what did get copied, not what didn't. Did you add a reference to `nunit.engine`? If you did that, then the engine gets copied to your output directory. Normally, it's in the packages directory, if installed with the console. The copy in the packages directory has all the required files.

As an alternative to the console runner, you may consider using the engine package. It's designed to be used by third-party runners that need to incorporate the engine. Right now, you have the engine as a side effect of the console runner, which you are not actually using.

To run in-process, add setting "ProcessModel" with value "Single" to the `TestPackage`. Look at the source code for the nunit3 console runner to see how console arguments get translated to package settings.

**Comment by mikkelbu** [comment] 2019-01-05 16:31
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂

**Closed by mikkelbu** 2019-01-05 16:31 UTC
Labels: is:question
