### ISSUE TITLE
Add support for Timeout attribute for .NET Standard builds

### ISSUE THREAD

**Issue by mvonballmo** [nunit/nunit#3076] opened 2018-10-24 15:53 UTC
**Observed Behavior**

The `TimeoutAttribute` is not available in the NUnit .NET Standard build. A project converted from .NET Framework to .NET Core can no longer enforce a timeout. The attribute does not exist and must be removed in order to compile the project.

**Expected Behavior**

NUnit supports the `TimeoutAttribute` under .NET Standard or provides documentation on how to replicate the behavior without the attribute.

**Details**

The documentation indicates that the attribute is,

> Not currently available in the .NET Standard builds of the framework.

But offers no further assistance. Is the attribute gone for good? Or is it coming back sometime? Is there a known workaround?

**Example**

```csharp
    [Test]
    [Timeout(2000)] // Compile error
    public async Task TestTasks() {}
```

**Version**

NUnit 3.10.1

**Comment by mikkelbu** [comment] 2018-10-24 17:02
Hi @mvonballmo 
I think this is a duplicate of #1638 for which a PR is underway #3027 (both issue and PR have been some time underway), so I'm going to close this issue. If you disagree or if I have misunderstod something then please comment and we can reopen this issue.

**Closed by mikkelbu** 2018-10-24 17:02 UTC

**Comment by mvonballmo** [comment] 2018-10-26 07:12
Yes, thank you! That other issue was just what I was looking for.
