### ISSUE TITLE
Optional parameters aren't handled when using TestCase/TestCaseSource

### ISSUE THREAD

**Issue by IanKemp** [nunit/nunit#4132] opened 2022-06-17 06:48 UTC
Given the following test setup:

```csharp
[TestCase(typeof(IThing), typeof(Thing))]
public void ResolvesTypes(Type @interface, Type expectedImplementation, MyEnum? value = MyEnum.Something)
```

NUnit fails with:

```
System.ArgumentException : Object of type 'System.Int32' cannot be converted to type 'System.Nullable`1[Some.Name.Space.MyEnum]'.
```
---

Given the following test setup:

```csharp
private static readonly IEnumerable<object[]> TestCases = new[]
{
    new object[] { typeof(IThing), typeof(Thing) },
};

[TestCaseSource(nameof(TestCases))]
public void ResolvesTypes(Type @interface, Type expectedImplementation, MyEnum? value = MyEnum.Something)
```

NUnit fails with:

```
Not enough arguments provided, provide at least 2 arguments.
```
---

NUnit 3.13.3
NUnit3TestAdapter 4.2.1
Visual Studio 2022 17.2.4

**Comment by manfred-brands** [comment] 2022-06-18 05:49
@IanKemp

There is support in NUnit for optional parameters when using `TestCase`.

This functionality is actually supplied by .NET using the [`Type.Missing`](https://docs.microsoft.com/en-us/dotnet/api/system.type.missing?view=net-6.0#remarks)
But it fails for nullable enum parameters. I have raised the [issue in dotnet/runtime](https://github.com/dotnet/runtime/issues/70925)

In your case, if your remove the '?' from your last parameter, it works,
Do you really expect users to pass `null` as a value for the `value` parameter ?

But you are right, NUnit doesn't support it for `TestCaseSource`.
If you explicitly pass `Type.Missing` it works, except for the bug in .net runtime.

```csharp
private static readonly IEnumerable<object[]> TestCases = new[]
{
    new object[] { typeof(IThing), typeof(Thing), Type.Missing },
};

[TestCaseSource(nameof(TestCases))]
public void ResolvesTypes(Type @interface, Type expectedImplementation, MyEnum value = MyEnum.Something)
```

**Comment by stevenaw** [comment] 2022-09-29 00:17
Thanks for the report @IanKemp , do @manfred-brands 's work-arounds work for you?

While not terribly clear from the titles, I suspect that this would be caught under the purview of https://github.com/nunit/nunit/issues/2268. There's a bit of a discussion in there about some inconsistencies across parameterized attributes in the framework, which itself seems to have been thought of as a duplicate of this historical issue tracking the `TestCaseSource` side of things https://github.com/nunit/nunit/issues/1281. Unfortunately a few attempts at fixing it appear to have stalled out, but it sounds like there may be an interest in fixing it as part of the next major release.

I'd like to close this issue as a duplicate, but we'll continue to see comments or if the workaround isn't working

**Closed by stevenaw** 2022-09-29 00:17 UTC
