### ISSUE TITLE
Build Portable Framework on Linux

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#784] opened 2015-08-21 14:57 UTC
## Updated Issue ##

Add portable framework to the Linux solution and document how to build it.

## Original Issue ##

Based on some discussions around issue #760, we will remove the portable build from the zip and nuget distributions and create separate packages. For now at least, we will leave it in the msi, since that is only produced on Windows machines.

Tasks:
1. Remove portable build from the binary NUnit zip package.
2. Remove portable build from the NUnit nuget package.
3. Remove portable build from the NUnitLite nuget package.
4. Create a binary zip with just the portable build.
5. Create a portable NUnit nuget package.
6. Create a portable NUnitLite nuget package.

Naming: we will use nunit.portable in the package names.

Future: At some point in the (relatively near) future, we will freeze these packages and stop issuing them. At that point, we can remove silverlight from the msi as well.

**Comment by rprouse** [comment] 2015-08-21 16:40
I understand the problems of packaging Silverlight and CF on Linux, but reading through the discussions, I don't see what the problem is with the PCL versions other than the paths might be wrong.

It is fairly common practice to include the PCL versions of assemblies in NuGet packages and not have separate versions for them. Don't the PCL libraries build on Linux?

**Comment by CharliePoole** [comment] 2015-08-21 16:48
Well, I wasn't sure about portable but I created the issues to force the comments I wasn't getting back on the email proposal. :-)

I haven't tried to build the PCL projects on Linux but I can unless you want to try - I can't remember if you have a Linux machine.  I'd much rather be able to build them and I agree that they make sense in a general distribution.

I have found some links that say MonoDevelop and Xamarin support portable libraries but that it doesn't mean the same thing as in the Microsoft world.

**Comment by rprouse** [comment] 2015-08-21 18:53
I don't have a Linux box right now to test on, but I do know that MonoDevelop and Xamarin both support compiling PCLs. If it is a pain for you to test, I will dust off my linux laptop and get everything up to date. I probably should anyway :smile:

**Comment by CharliePoole** [comment] 2015-08-21 18:55
I can give it a try later - expecting company today. I'll just add the portable projects to the linux solution and see what happens.

**Comment by rprouse** [comment] 2015-08-21 18:56
If I get time, I will try too. I will let you know if I do to save you time.

**Comment by CharliePoole** [comment] 2015-08-21 18:57
I guess we could just create a branch and push it to see what Travis does.

**Comment by rprouse** [comment] 2015-08-21 20:50
I updated my linux box to the latest version of MonoDevelop (4.0.12) and Mono (3.2.8) available via apt-get on Ubuntu. I can create a portable project in MonoDevelop, but I cannot compile the blank project. It gives me the error "PCL Reference Assemblies not installed."

Microsoft opened the PCL reference assemblies for other platforms back in Oct 2013 (http://blogs.msdn.com/b/dotnet/archive/2013/10/14/portable-class-library-pcl-now-available-on-all-platforms.aspx). The workaround on the web for portable projects is to copy .netportable from (c:\program files (x86)\reference assemblies\microsoft\framework\.netportable) folder over to linux (/usr/lib/mono/xbuild-frameworks/). I will give that a try.

I'm not sure if we should be leaving stuff out of our NuGet packages just because the version of Mono on most Linux distros is very out of date. The one case where someone was trying to build NuGet packages on Linux seemed like an edge case. I also think that it should only be the team building NuGet packages, so maybe we don't remove Silverlight either. I am less attached to that though, I am pretty sure Silverlight is dead now that Microsoft is updating everyone to Windows 10 and the Edge browser. :smile:

**Comment by rprouse** [comment] 2015-08-21 21:25
Okay, after copying the `.NetPortable` directory over to Linux and switching the ToolsVersion in the project files to 4.0 from 12.0, I was able to load the portable nunit.framework project and compile it.

**Comment by CharliePoole** [comment] 2015-08-21 23:26
So the remaining question is whether you can run tests, since the reference libraries need to point to something.

**Comment by akoeplinger** [comment] 2015-08-25 17:55
@rprouse the PCL Reference Assemblies are available if you install the latest Mono from the official Xamarin apt repositories: http://www.mono-project.com/docs/getting-started/install/linux/ (install the `referenceassemblies-pcl` package). Mono 3.2.8 as package in Debian/Ubuntu is quite old.

**Comment by rprouse** [comment] 2015-09-03 19:36
@akoeplinger, thanks for the update. Even more reason to close this issue without action :+1:

**Comment by CharliePoole** [comment] 2015-09-03 19:42
Do we want to close this and make a new issue or just change it to say "Make portable build work on Linux"?

**Comment by rprouse** [comment] 2015-09-03 19:46
I vote for make Portable build work on Linux with a 3.2 milestone. I got it
working and have a branch for it, I just don't want to commit it because
the versions of Mono on Ubuntu are currently so far behind that your
average user would need to jump through hoops. I think we should wait a bit
on this.

On 3 September 2015 at 15:43, CharliePoole <notifications@github.com> wrote:

> Do we want to close this and make a new issue or just change it to say
> "Make portable build work on Linux"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/784#issuecomment-137554249>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by akoeplinger** [comment] 2015-09-03 20:04
Please note that I don't think the reference assemblies will ever be packaged in Ubuntu/Debian as they don't have source code (just the DLLs). You'll likely always need to rely on the Xamarin repository for this, which frankly should be preferred in almost all cases for installing Mono anyway.

If someone wants to build NUnit on Linux requiring a current Mono doesn't seem too bad to me. Running should of course continue to work with the Mono most distros provide.

**Comment by rprouse** [comment] 2015-09-08 13:36
I have renamed this to adding the portable build to the Linux solution and documenting how to build it including updating Mono on Debian/Ubuntu based systems. I have taken ownership because I already have a branch for this on my Linux box.

**Comment by rprouse** [comment] 2015-09-08 16:07
For the docs, http://www.monodevelop.com/download/linux/

**Comment by rprouse** [comment] 2015-09-20 13:46
Closed with PR #802 and PR #803

**Closed by rprouse** 2015-09-20 13:46 UTC
Labels: is:build, pri:normal
