### ISSUE TITLE
Syntax suggestions errors as warnings

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2698] opened 2018-02-03 03:25 UTC
Looks like my VS2017 is treating some of these as errors, I want to say our `.editorconfig` settings are probably causing this?  Are these intended by chance?

![image](https://user-images.githubusercontent.com/5589035/35762623-7fef0f1c-085f-11e8-879a-e46289744ea5.png)

**Comment by rprouse** [comment] 2018-02-03 14:02
Do you have latest? We fixed some of these recently. It could also be caused by analyzers you have installed.

**Comment by OmicronPersei** [comment] 2018-02-03 20:35
Should be:
```
$ git log -n 1
commit 259066fb2b8edb753f982a88662834e0c6a09215 (HEAD -> master, nunit-upstream/master)
Merge: faa77153 6b6c7b52
Author: Joseph Musser <me@jnm2.com>
Date:   Wed Jan 31 19:29:35 2018 -1000

    Merge pull request #2692 from OmicronPersei/issue-1578

    Extracted a PropertyBagAdapter on the TestContext.Properties property.

```

**Comment by jnm2** [comment] 2018-02-05 21:15
@OmicronPersei The editorconfig at the commit you mention only causes warnings, no errors: https://github.com/nunit/nunit/blob/259066fb2b8edb753f982a88662834e0c6a09215/.editorconfig

Have you closed and reopened all editor windows after checking out that commit?

**Comment by OmicronPersei** [comment] 2018-02-06 03:12
Does closing/opening Visual Studio count?  I know they're supposed to be warnings but, at least visually, they look like errors to me.

**Comment by jnm2** [comment] 2018-02-06 03:23
Yes, closing amd reopening works. Does your checked-out .editorconfig have the word 'error' in it?

**Comment by OmicronPersei** [comment] 2018-02-07 01:53
It does not.  Maybe someone else can try reproducing this?  My workspace is clean so it should be reproducible elsewhere.

**Comment by mikkelbu** [comment] 2018-02-07 11:15
I've the same problem. Changing the warning to a suggestion helps, but buth warning and error give rise to an error (and my default VS configuration - overridden by editorconfig - is to have these as warnings)
![image](https://user-images.githubusercontent.com/1007631/35912091-e1bbc89e-0bfb-11e8-8869-e5ecdd749f5c.png)

**Comment by rprouse** [comment] 2018-02-07 14:00
I am seeing the same thing, but only when the files are open, for example TestContext.cs. I deleted `.editorconfig` and reopened the solution and it went away. I am not sure why Visual Studio is showing these as errors and not respecting the warning, but switching them to suggestions works, so I am going to submit a PR for this.

**Closed** 2018-02-07 19:51 UTC
Labels: is:build, pri:high

**Comment by jnm2** [comment] 2018-02-07 21:45
Thanks Rob!
