### ISSUE TITLE
Assert user message: newline "\r\n" is shown in output as text

### ISSUE THREAD

**Issue by p-gintare** [nunit/nunit#1814] opened 2016-09-30 14:00 UTC
Nunit 3.4.0 and 3.4.1 does not escape new line

**Code:**

var magic = $"Message {Environment.NewLine}new line";
Assert.IsTrue(false, magic);

**Output:**
  Message \r\nnew line
  Expected: True
  But was:  False

**Comment by CharliePoole** [comment] 2016-09-30 15:07
This is a duplicate of issue #1575, which is fixed in master for the 3.5 release.

Please search for existing issues, including closed issues, before filing a new one.

**Closed by CharliePoole** 2016-09-30 15:07 UTC
