### ISSUE TITLE
Move Portable agent to its own repository

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1597] opened 2016-06-21 14:24 UTC
@rprouse Would you add a real description here?

**Comment by rprouse** [comment] 2016-06-21 16:24
Closing as a duplicate of #1573

The portable agent is now in https://github.com/nunit/nunit.portable.agent

**Comment by CharliePoole** [comment] 2016-06-21 16:53
I looked for an issue, but didn't realize it was closed. However, I still see the portable agent in the tree for the nunit repo.

**Comment by rprouse** [comment] 2016-06-21 17:19
Opps, my miss. I forgot to remove it. I will reopen and clean it up.

**Closed** 2016-06-21 18:47 UTC
Labels: is:feature, pri:normal
