### ISSUE TITLE
We have no way to configure tests for several assemblies using NUnit project file and the common installation from msi file

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#719] opened 2015-07-01 08:42 UTC
Here is an example of my command line:
`"C:\Program Files (x86)\NUnit.org\bin\nunit-console.exe" C:\Projects\NUnitTest\1.nunit "`

When I use following project file (case 1):
`<NUnitProject>
<Settings activeconfig="active" appbase="C:\Program Files (x86)\NUnit.org\bin"/>
<Config binpathtype="auto" name="active">
<assembly path="C:\Projects\NUnitTest\bin\HelloWorld.Tests.dll"/>
</Config>
</NUnitProject>`

The NUnit can't find C:\Projects\NUnitTest\bin\nunit.framework.dll
LOG: Attempting download of new URL file:///C:/Program Files (x86)/NUnit.org/bin/nunit.framework.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/NUnit.org/bin/nunit.framework/nunit.framework.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/NUnit.org/bin/nunit.framework.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/NUnit.org/bin/nunit.framework/nunit.framework.EXE.
LOG: All probing URLs attempted and failed.

Case 2
`<NUnitProject>
<Settings activeconfig="active"/>
<Config binpathtype="auto" name="active">
<assembly path="C:\Projects\NUnitTest\bin\HelloWorld.Tests.dll"/>
</Config>
</NUnitProject>`

LOG: Attempting download of new URL file:///C:/Projects/NUnitTest/nunit.framework.DLL.
LOG: Attempting download of new URL file:///C:/Projects/NUnitTest/nunit.framework/nunit.framework.DLL.
LOG: Attempting download of new URL file:///C:/Projects/NUnitTest/nunit.framework.EXE.
LOG: Attempting download of new URL file:///C:/Projects/NUnitTest/nunit.framework/nunit.framework.EXE.
LOG: All probing URLs attempted and failed.

Case 3
`<NUnitProject>
<Settings activeconfig="active"/>
<Config binpathtype="auto" name="active" appbase="C:\Projects\NUnitTest\bin">
<assembly path="C:\Projects\NUnitTest\bin\HelloWorld.Tests.dll"/>
</Config>
</NUnitProject>`

Works fine

I want to note that the common installation using msi file have no nunit.framework.dll in the "bin" directory, but the zip file has it.

Could you suggest any way how I can run tests for several assemblies using NUnit project file?

**Comment by CharliePoole** [comment] 2015-07-01 22:49
Case 1: This isn't an error. You set your appbase to NUnit's own bin directory. Nobody should ever do that. Since you used binpathtype=auto, the probing path is set to the C:\Projects\NUnitTest\bin directory. Since that's not under the appbase, it's an error.

Case 2: The appbase defaults to the location of the NUnit project file. The auto probing path is the same as in the preceding example. The only reason it would fail is if the nunit.framework.dll is not present. Is it being copied?

Case 3: The appbase is set to your bin directory. There are no additional probing directories. I don't really understand why this would work any differently from case 2, so it's worth looking into.

Regarding common installation: NUnit has always (i.e. since about 2000) that the framework assembly should be copied into the appbase or probing path of the test assembly. If you think about it, this is completely necessary. When multiple framework builds, versions and even types are possible, NUnit (the console and engine) has no way to figure out what framework you want to use for your tests. The tests have to reference the framework, so it has to actually be present.

Multiple project files should work the same as a single project file. Once we solve the initial problem, I think that multiple assemblies will fall out of it as a side effect. SO... the big question is "Where is your framework assembly?"

**Comment by NikolayPianikov** [comment] 2015-07-02 10:01
The nunit.framework.dll is located in the "bin" directory near the HelloWorld.Tests.dll

Case 4
<NUnitProject>
<Settings activeconfig="active"/>
<Config name="active">
<assembly path="C:\Projects\NUnitTest\bin\HelloWorld.Tests.dll"/>
</Config>
</NUnitProject>

It does not work:
LOG: Attempting download of new URL file:///C:/Projects/NUnitTest/nunit.framework.DLL.
LOG: Attempting download of new URL file:///C:/Projects/NUnitTest/nunit.framework/nunit.framework.DLL.
LOG: Attempting download of new URL file:///C:/Projects/NUnitTest/nunit.framework.EXE.
LOG: Attempting download of new URL file:///C:/Projects/NUnitTest/nunit.framework/nunit.framework.EXE.
LOG: All probing URLs attempted and failed.

NUnit project file could be located far from testing assembly, moreover it does not work for cases when we have several assemblies in the several directories

When we pass testing assemblies via command line it works

**Comment by rprouse** [comment] 2015-07-02 13:15
I have confirmed 2 and 3, I am looking at it.

**Comment by rprouse** [comment] 2015-07-02 14:40
Okay, I've dug into this and I think this is a documentation issue. In all the cases that you site above, you use absolute paths, but that isn't the way that the project files were designed, nor is it good practice since it does not translate across machines.

The project file should be in a common parent directory for your tests. If you do not specify the AppBase, then it defaults to that of the project file. 

Here is an example from the documentation

```xml
<NUnitProject>
  <Settings activeconfig="Debug" autoconfig="true" />
  <Config name="Debug" binpath="bin/Debug/lib;bin/Debug/tests;bin/Debug/framework" 
        runtimeFramework="v2.0.50727">
    <assembly path="bin/Debug/tests/nunit.framework.tests.dll" />
    <assembly path="bin/Debug/tests/nunit.core.tests.dll" />
    <assembly path="bin/Debug/tests/nunit.util.tests.dll" />
    <assembly path="bin/Debug/tests/nunit.mocks.tests.dll" />
    <assembly path="bin/Debug/tests/nunit-console.tests.dll" />
    <assembly path="bin/Debug/tests/nunit.uikit.tests.dll" />
    <assembly path="bin/Debug/tests/nunit.uiexception.tests.dll" />
    <assembly path="bin/Debug/tests/nunit-gui.tests.dll" />
    <assembly path="bin/Debug/tests/nunit.fixtures.tests.dll" />
  </Config>
  <Config name="Release" binpath="bin/Release/lib;bin/Release/tests;bin/Release/framework"
        runtimeFramework="v2.0.50727">
    <assembly path="bin/Release/tests/nunit.framework.tests.dll" />
    <assembly path="bin/Release/tests/nunit.core.tests.dll" />
    <assembly path="bin/Release/tests/nunit.util.tests.dll" />
    <assembly path="bin/Release/tests/nunit.mocks.tests.dll" />
    <assembly path="bin/Release/tests/nunit-console.tests.dll" />
    <assembly path="bin/Release/tests/nunit.uikit.tests.dll" />
    <assembly path="bin/Release/tests/nunit.uiexception.tests.dll" />
    <assembly path="bin/Release/tests/nunit-gui.tests.dll" />
    <assembly path="bin/Release/tests/nunit.fixtures.tests.dll" />
  </Config>
</NUnitProject>
```

I have tried a variant of this with tests in multiple sub-directories and it works as expected.

Clearly we need to document this better. Currently there is only the sample given above with no explanation or references to what other settings can be included.

I am going to switch this to a documentation issue. @CharliePoole, I never use project files, so I am not as familiar with them as you. Can you confirm my analysis?

**Comment by CharliePoole** [comment] 2015-07-02 15:12
Yes, that's the case... assuming it solves all of @NikolayPianikov 's issues.

NUnit 2.6.4 works with absolute paths in memory but always saves the project file using a relative path. It's pretty easy to mess it up when hand-editing.

NUnit 3.0 doesn't have any way to save project files, although you can still use the old project editor because the format has not changed. One result is that we will probably get more hand-edited project files to deal with, so documentation is definitely needed. I can take this one.

A further point to be aware of: project files originally were required to be in the application base - that is, they defined it. Allowing the user to change the application base within the project file is a fairly recent (last few years) addition so there could still be bugs.

@NikolayPianikov can you verify that using relative paths resolves the issue for you?

**Comment by NikolayPianikov** [comment] 2015-07-08 09:09
It helps. Thank you

**Comment by CharliePoole** [comment] 2015-09-22 19:19
I have updated the docs at https://github.com/nunit/nunit/wiki/Multiple-Assemblies

Please review @rprouse and @NikolayPianikov

**Comment by rprouse** [comment] 2015-09-22 20:42
It looks good. We might want to include relevant command line options like `--config=NAME` directly on that page to save people having to jump to the other page and read through all of the options.

**Comment by CharliePoole** [comment] 2015-09-22 20:59
I hate to put things in two places usually, but I'll take a look at it.

**Comment by NikolayPianikov** [comment] 2015-09-24 15:10
We have the client, he runs selenium tests using the NUnit from the different assemblies and from the different directories. He prefers to have appBase like path to his assembly. Is there any way to do it using NUnit project file? If there is not, could we add this feature?

**Comment by CharliePoole** [comment] 2015-09-25 17:28
Currently, you can set the appbase in the NUnit project file at the top level (under settings) or the config level. Any assemblies in the same config would have the same appbase.

Configs can be anything you like and the client could easily put each assembly into its own config, at the cost of having to run each assembly separately. This is no advantage over running the assemblies directly, however.

I gather that the client would prefer not to put all the assemblies on the command line?

As a future enhancement, we could add this feature to the nunit project format. However, I would not expect to give it high priority for a few releases.

Charlie

**Comment by CharliePoole** [comment] 2015-09-26 16:03
@NikolayPianikov If you would like to have some additions to the nunit project format, would you document them in a separate issue please? I'm going to update the docs and close this one.

**Comment by CharliePoole** [comment] 2015-09-26 18:58
I've made substantial changes:

* Renamed the page to NUnit Test Projects
* Moved it under Running Tests in the wiki menu
* Added a complete description of all xml elements 

@rprouse Would you re-review this? I'll close the issue then since we made it about the docs. BTW, if we like the format I used for describing XML elements, I'd like to use the same for the result file.

The new page location is https://github.com/nunit/nunit/wiki/NUnit-Test-Projects

**Comment by NikolayPianikov** [comment] 2015-09-28 16:08
Yes, I mean user can run tests for the several assemblies using one build step.

I found following text in the doc:

`The following command-line options override what is specified in the NUnit project file:
--appbase`

Does it mean we can override "appbase" in the last version? I am not sure it is working now ...

**Comment by NikolayPianikov** [comment] 2015-09-28 16:17
I think we could have additional sections "AppDomainSetup" with attributes, something like these: "applicationBase", "configurationFile", "licenseFile" and so on. 
Also we could specify the "evidence" for app domain. We could add the attribute to the section <Config> / <assembly> / <Settings> to specify app domain's configuration for the different scope (config/per assembly/for all)

**Comment by CharliePoole** [comment] 2015-09-29 00:28
@NikolayPianikov I removed "appbase" - it's not an option in the current build.

**Comment by CharliePoole** [comment] 2015-09-29 00:30
Since the documentation has been updated, I'm closing this issue. Any change requests for the content of the nunit project file should go into separate issues so we can schedule them for a future release.

**Closed by CharliePoole** 2015-09-29 00:30 UTC
Labels: closed:done, is:docs, pri:low
