### ISSUE TITLE
UnsupportedFrameworkException NUnit 3.0.1

### ISSUE THREAD

**Issue by muhammetsahin** [nunit/nunit#1115] opened 2015-12-04 16:58 UTC
![image](https://cloud.githubusercontent.com/assets/2045788/11595611/feb051b0-9ab8-11e5-9b81-0e03d903541e.png)

**Comment by rprouse** [comment] 2015-12-04 17:21
@muhammetsahin your tests are referencing the portable version of the framework. Currently, the Visual Studio Adapter and the NUnit3 Console cannot run portable tests, you must create an NUnitLite runner or use the nunit.xamarin runners.

If that is a Xamarin project, I have had luck referencing my portable assembly in a .NET 4.5 test project and testing that way. If you have to run your tests in a platform specific way, for example to initialize Xamarin Forms, then you should use the NUnit Xamarin runners.

Let me know what you are testing and the structure of your application and I can help you get going.

**Comment by muhammetsahin** [comment] 2015-12-04 17:31
Thanks. Yes i currently using xamarin forms portable my project.  But another issue is i've added NUnitLite to my test project than tested again but i've got same error.

**Comment by rprouse** [comment] 2015-12-04 17:41
For NUnitLite, your project needs to be self executing, so needs to be switched to an EXE and you need to update the program.cs accordingly.

In your case though, it is probably easiest to just retarget your test assembly to .NET 4.5. Remove and re-add the NUnit reference and remove NUnitLite. The tests should run then. The only tests that won't run are if they cause Xamarin.Forms code to run. I get around those problems in nearly every case by creating mocks for things like INavigation and injecting them into the tests.

**Comment by rprouse** [comment] 2015-12-05 15:29
I am closing this as not a bug. If you are still having trouble, post here and I will see it.

**Closed by rprouse** 2015-12-05 15:29 UTC
