### ISSUE TITLE
In the some cases when tests cannot be started NUnit returns exit code "0"

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#685] opened 2015-06-11 12:05 UTC
In the some cases when tests cannot be started NUnit returns exit code "0" and shows error messages. TeamCity marks this step as successful because it has no messages about failed tests and just has exit code. In these cases we should send the "buildProblem" service messages, see [https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity]

See PR #686

**Comment by CharliePoole** [comment] 2015-06-11 17:53
We did this by design, but I agree that returning zero is a bug. We will need to decide what to return if _no_ assemblies can be run as well as what to return if only _some_ assemblies fail to load.

I don't think we should need a special message in this case, provided we return an error code. At least, I hope not. :-)

**Comment by NikolayPianikov** [comment] 2015-06-15 10:27
Special messages will allow users to get more information about problem

**Comment by NikolayPianikov** [comment] 2015-07-01 08:50
For example:

[18:56:06][Step 4/6] Starting: "C:\Program Files\NUnit 3.0.0 b2\bin\nunit-console.exe" C:\Projects\TeamServer\BuildServer.idea_artifacts\agent_deployment_debug\temp\agentTmp\FwndJdLbHTCYvMyzqGzuxUqkqoeZg9KH\project.nunit "--work=C:\Program Files\NUnit 3.0.0 b2\bin" --noresult --framework=4.0 --workers=10 --verbose
[18:56:06][Step 4/6] in directory: C:\Projects\TeamServer\BuildServer.idea_artifacts\agent_deployment_debug\work\33abfa34feab3e5d
[18:56:06][Step 4/6] NUnit Console Runner 3.0.5610 
[18:56:06][Step 4/6] Copyright (C) 2014 Charlie Poole
[18:56:06][Step 4/6] 
[18:56:07][Step 4/6] Test Files
[18:56:07][Step 4/6] C:\Projects\TeamServer\BuildServer.idea_artifacts\agent_deployment_debug\temp\agentTmp\FwndJdLbHTCYvMyzqGzuxUqkqoeZg9KH\project.nunit
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Runtime Environment
[18:56:07][Step 4/6] OS Version: Microsoft Windows NT 6.3.9600.0
[18:56:07][Step 4/6] CLR Version: 4.0.30319.0
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Options
[18:56:07][Step 4/6] ProcessModel: Default DomainUsage: Default
[18:56:07][Step 4/6] Execution Runtime: 4.0
[18:56:07][Step 4/6] Worker Threads: 10
[18:56:07][Step 4/6] Work Directory: C:\Program Files\NUnit 3.0.0 b2\bin
[18:56:07][Step 4/6] Internal Trace: Off
[18:56:07][Step 4/6] Display TeamCity Service Messages
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Agent process 1464 starting
[18:56:07][Step 4/6] Running under version 2.0.50727.8009, Net 3.5
[18:56:07][Step 4/6] Agent process 1464 exiting
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Test Run Summary
[18:56:07][Step 4/6] Overall result: Failed
[18:56:07][Step 4/6] Tests run: 0, Passed: 0, Errors: 0, Failures: 0, Inconclusive: 0
[18:56:07][Step 4/6] Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
[18:56:07][Step 4/6] Start time: 2015-06-11 14:56:07Z
[18:56:07][Step 4/6] End time: 2015-06-11 14:56:07Z
[18:56:07][Step 4/6] Duration: 0,007 seconds
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Errors and Failures
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] 1) Failed : C:\Projects\TeamServer\BuildServer.idea_artifacts\agent_deployment_debug\temp\agentTmp\FwndJdLbHTCYvMyzqGzuxUqkqoeZg9KH\project.nunit
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] 2) Invalid : C:\Projects\TeamServer\BuildServer.idea_artifacts\agent_deployment_debug\work\33abfa34feab3e5d\trunk\HelloWorld.Tests\bin\Debug\HelloWorld.Tests.dll
[18:56:07][Step 4/6] Could not load file or assembly 'file:///C:\Projects\TeamServer\BuildServer.idea_artifacts\agent_deployment_debug\work\33abfa34feab3e5d\trunk\HelloWorld.Tests\bin\Debug\HelloWorld.Tests.dll'; or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.
[18:56:07][Step 4/6] 
[18:56:07][Step 4/6] Process exited with code 0

**Comment by CharliePoole** [comment] 2015-07-01 23:02
It looks like there is sufficient info given in the console output that we could simply define a code to return when some assembly cannot be loaded. Since an rc > 0 is defined to mean the number of failing test cases, this should be one of our negative codes.

I think all the codes are already defined, we just stopped returning them between 2.6.4 and 3.0.

**Comment by rprouse** [comment] 2015-07-02 13:06
The return codes are in `ConsoleRunner`. @CharliePoole, as you say, we just need to start returning them again :smile: 

```C#
public static readonly int OK = 0;
public static readonly int INVALID_ARG = -1;
public static readonly int FILE_NOT_FOUND = -2;
public static readonly int FIXTURE_NOT_FOUND = -3;
public static readonly int UNEXPECTED_ERROR = -100;
```

**Comment by CharliePoole** [comment] 2015-07-02 15:20
NUnit 2.x returned -2 and -100 in response to exceptions it caught. By design, we no longer throw those exceptions but instead return a TestResult that includes the error information. The console runner should analyze the result and return the appropriate error code. 

In fact, it's already analyzing the result in order to display the errors, so this shouldn't be too hard.

I spotted another error in the output posted by @NikolayPianikov - there is a separate error line displayed for the nunit project file. That's erroneous because the project file is only marked as a failure because of an error at the assembly level. If it's convenient, we should fix this at the same time. Otherwise, another issue can be filed.

**Closed** 2015-08-11 13:41 UTC
Labels: is:bug, pri:normal, status:merge
