### ISSUE TITLE
NUnit fails on incorrect but ignored test

### ISSUE THREAD

**Issue by toolmagic** [nunit/nunit#3101] opened 2018-11-28 04:36 UTC
NUnit 3.11.0 
NUnit3TestAdapter 3.11.2
Visual Studio 2017 (15.9.2) 
ReSharper 2018.2

````
using NUnit.Framework;

namespace NUnit3Samples
{
    [TestFixture]
    public sealed class ValueSourceAttributeTest
    {
        private static int SourceInt()
        {
            return 100;
        }

        private static int[] IntValues()
        {
            return new[] {1, 2, 3, 4, 5};
        }

        [Test]
        [Ignore("It's not completed yet")]
        public void Test1([ValueSource(nameof(SourceInt))] int x)
        {
            Assert.Inconclusive();
        }

        [Test]
        public void Test2([ValueSource(nameof(IntValues))] int x)
        {
            Assert.Pass();
        }
    }
}
````

1. I tried to run tests in the test fixture with ReSharper and got an error:
```
An exception was thrown while loading the test.
System.InvalidCastException: Unable to cast object of type "System.Int32" to type "System.Collections.IEnumerable".
   at NUnit.Framework.ValueSourceAttribute.GetDataSourceValue(MemberInfo[] members) at C:\src\nunit\nunit\src\NUnitFramework\framework\Attributes\ValueSourceAttribute.cs:line 139
   at NUnit.Framework.ValueSourceAttribute.GetDataSource(IParameterInfo parameter) at C:\src\nunit\nunit\src\NUnitFramework\framework\Attributes\ValueSourceAttribute.cs:line 96
   at NUnit.Framework.Internal.Builders.ParameterDataSourceProvider.GetDataFor(IParameterInfo parameter) at C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\ParameterDataSourceProvider.cs:line 55
   at NUnit.Framework.CombiningStrategyAttribute.BuildFrom(IMethodInfo method, Test suite) at C:\src\nunit\nunit\src\NUnitFramework\framework\Attributes\CombiningStrategyAttribute.cs:line 90
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite) at C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultTestCaseBuilder.cs:line 114
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter) at C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 201
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter, ITestFixtureData testFixtureData) at C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 175
   at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__47.MoveNext() at C:\src\nunit\nunit\src\NUnitFramework\framework\Attributes\TestFixtureAttribute.cs:line 238
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter) at C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultSuiteBuilder.cs:line 96
```
Expected behaviour: Test2 passed successfully.

2. I tried to run tests with Visual Studio Test Explorer and NUnit wrote to Output window that it could not find tests with filter by test name.

Expected behaviour: Test2 passed successfully.

**Comment by mikkelbu** [comment] 2018-11-28 08:09
You could say that it should be able to run `Test2`, however the problem occurs when NUnit tries to figure out which tests there are in `ValueSourceAttributeTest`, so even if `Test1` is marked as ignored it still needs to figure out which tests there are under `Test1`. And this fails. 

If we e.g. placed `Ignore` on `Test2` (and removed `Test1`) then one would see that this in VS (after running the tests)
![image](https://user-images.githubusercontent.com/1007631/49137534-059ac480-f2ed-11e8-9744-eb8fd49d7450.png)

Personally, I would just avoid the problem by removing the `TestAttribute` on `Test1` and perhaps add a TODO, but that depends on your workflow.

**Comment by toolmagic** [comment] 2018-11-28 10:22
@mikkelbu , OK, it's not problem for me, I could just comment the code. But it would be better to fail just incorrect test (and skip ignored tests on building test suite) but not test fixture overall. It's somewhat inconvenient when NUnit fails correct tests and makes developers check the whole test class to look for which test is wrong. Thank You!

**Comment by ChrisMaddock** [comment] 2018-12-22 13:37
This is somewhat fundamental to how NUnit works. 

Before running your tests, NUnit does an 'explore' phase, which evaluates your test assembly, and builds up a tree containing all the tests it can discover. To build this tree, it needs to evaluate all attributes which 'build tests', such as ValuesSource here - hence why this 'discovery' process errors and fails. Attributes such as Ignore are not recognised at this point in the process, as NUnit still needs to discover the tests to display them as ignored. 

Features such as https://github.com/nunit/nunit3-vs-adapter/pull/553 will limit this discovery phase and help with certain parts of this problem, but only down to a class level, which won't help for your particular issue here.

Personally, I think this issue should be closed. `Ignore` is functionality which applies to tests once they have already been discovered and created - which is how we're able to show Ignored tests in a GUI. To do the discovery phase, a valid test structure is required. I can understand the pain to the developer here - perhaps the solution is to throw a better error message, which pinpoints exactly the method in which the issue lies? That sounds like it may be possible?

**Comment by rmaurmeier** [comment] 2018-12-27 20:44
I had an ignored NUnit test fail on me earlier, that was a little awkward but after reading this thread, i have a good idea where to do to fix the issue. It would be nicer if NUnit could handle discovery a little better...

**Comment by CharliePoole** [comment] 2018-12-28 00:48
Part of the problem is the original choice of the word "Ignore" by the developers of NUnit. We don't really ignore the method. We skip running it but give it a special result status of "Ignored." We still have to discover the individual tests if only to know how many tests were ignored.

**Comment by rprouse** [comment] 2020-05-18 18:59
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 18:59 UTC
Labels: is:idea
