### ISSUE TITLE
Enhancement: provide TestContext.CurrentContext.TestResultsDirectory

### ISSUE THREAD

**Issue by juwens** [nunit/nunit#4148] opened 2022-08-04 08:10 UTC
Sometimes you want to save a file to the configured ResultsDirectory (either by `--results-directory ./foobar/` or my.runsettings.  
Currently i see no option to get the wanted Directory from TestContext

**Comment by stevenaw** [comment] 2022-08-04 21:14
Thanks for suggesting this @juwens 
There may have been a similar suggestion in the recent past here: https://github.com/nunit/nunit/issues/4020
Would you consider this a duplicate of that or is this something different?

**Comment by stevenaw** [comment] 2024-07-27 00:01
Coming back to this, I see I misunderstood your ask @juwens .

I didn't think the framework is the right place for this, unfortunately. While the `TestContext` already has `TestDirectory` and `WorkDirectory` properties, writing of results to an output file is something handled at a higher level than the framework. In fact, the framework doesn't know if results from a test run are written to a directory at all - it only knows which streams to publish outputs to. These streams are set up by runners at a higher level and may point to a file or even a network stream in theory.

Without knowing the specifics of your use case, my guess is that a script which can run after the test run has been completed may be your best bet here as it would run from a context where the `results-directory` is known, and at a time that the test run has completed and the results file fully populated.

I'm going to close this as `wont do`, however note that we will see any further comments. Please do chime in if I've misunderstood again and you wanted to clarify

**Closed by stevenaw** 2024-07-27 00:01 UTC
