### ISSUE TITLE
Report doesn't reflect effective number of retries for retried test

### ISSUE THREAD

**Issue by nvborisenko** [nunit/nunit#2916] opened 2018-06-28 12:59 UTC
I have test with [Retry] attribute.

In `TestResult.xml` I see:
```xml
<test-case id="0-1009" name="Test4" fullname="Example.Tests.Class1.Test4" methodname="Test4" classname="Example.Tests.Class1" runstate="Runnable" seed="41650845" result="Failed" start-time="2018-06-27 10:48:27Z" end-time="2018-06-27 10:48:42Z" duration="15.031428" asserts="5">
            <properties>
              <property name="Retry" value="5" />
              <property name="Description" value="Test should be retried" />
            </properties>
            
            ...
</test-case>
```

In this report I can see that meta info for test is Retry=5, but cannot understand how many times test was retried to became passed. Could we add one more attribute for `test-case` which will say how many actual times test was retried?

**Comment by ChrisMaddock** [comment] 2018-06-28 14:09
I think this is a duplicate of https://github.com/nunit/nunit/issues/1879 - would you agree? Let me know if I should reopen this.

We'd love a pull request for this though, if you're interested! Have a read through the discussion on the older issue, you'll see it's not trivial - but definitely not beyond reason!

**Closed by ChrisMaddock** 2018-06-28 14:09 UTC

**Comment by CharliePoole** [comment] 2018-06-28 15:49
Seems like it is a duplicate. The only difference is that #1879 asks for a new property, whereas this issue asks for a new attribute on test case. Of course, how we solve it is up to us.

The property-based solution is a bit of a problem, IMO. Conceptually, properties pertain to the test itself, not to a particular execution of the test. In a GUI situation, the test, represented as an `NUnitTestMethod`, remains in memory after execution. The result is a `TestResult` and is cleared before each run. We should not add the number of runs to the test, but to the result.

Note that the XML representation currently merges test and result together. That's a decision I made very early in the design of NUnit 3, simplifying the old V2 XML that keeps results separate from tests. The new representation breaks down a little with repeated tests, I'm afraid.
