### ISSUE TITLE
NUnit target framework net7.0 TeamCity results issue

### ISSUE THREAD

**Issue by valentinvs** [nunit/nunit#4258] opened 2022-11-24 12:24 UTC
Hello
I am trying to figure out why the results are no longer reported to teamcity:

Before net7.0:
![image](https://user-images.githubusercontent.com/3611349/203782884-f29e75e2-d801-469d-a987-39d86bf90afd.png)

After net7.0:
![image](https://user-images.githubusercontent.com/3611349/203782945-94a329ec-c490-42a8-be71-e9584f21233c.png)

What I tried is to update the following packages:
```
<PackageReference Include="NUnit" Version="3.13.3" />
<PackageReference Include="NUnit.Extension.TeamCityEventListener" Version="1.0.7" />
<PackageReference Include="NUnit3TestAdapter" Version="4.3.1" />
<PackageReference Include="NUnit.Analyzers" Version="3.5.0">
```

In the build log I can see that the tests are passing:
![image](https://user-images.githubusercontent.com/3611349/203783576-248b1a3f-ce0d-492f-a06b-0b6d015de5da.png)

Is this some kind of NUnit **.NETCoreApp,Version=v7.0** support issue?

**Comment by edvinasz** [comment] 2022-11-26 20:37
Confirmed I see same problem.  But it looks like the issue is breaking change in dotnet 7 and teamcity, not NUnit.  See https://youtrack.jetbrains.com/issue/TW-77992.  Suggested workaround is provided in the link, but here is a copy of it here

> It's going to be fixed in the upcoming release. Till that, I can suggest using environment variables (set for build configuration via parameters) or defining properties in csproj as a workaround. To sum up, three variables must be defined:
>
>    "VSTestTestAdapterPath" should be similar to "{teamcity_agent_installation_dir}/plugins/dotnet/tools/vstest15"
>   "VSTestLogger" with the value of "logger://teamcity"
>    "VSTestVerbosity" with the value of "normal"

**Comment by stevenaw** [comment] 2022-11-27 18:19
Thanks for noticing that and sharing @edvinasz 
I'm going to leave this open for visibility for a short bit before closing but it sounds like an issue outside of nunit and not something that can be fixed in the framework here

**Comment by valentinvs** [comment] 2022-11-28 08:05
Thanks for the input!

Just for anyone who might jump into the issue I would like to share the setting values that helped me:

![image](https://user-images.githubusercontent.com/3611349/204224680-f9665302-181b-45d6-af17-a382f6dc1279.png)

The variable **VSTestTestAdapterPath** might have a different value based on the teamcity version (I guess). In my case I couldn't find the parameter **teamcity_agent_installation_dir** so I used **teamcity.agent.home.dir**

**Closed** 2022-11-28 08:05 UTC
Labels: closed:notabug
