### ISSUE TITLE
RetryAttribute not support TestFixture/Assembly level, also not support retry in case of exceptions

### ISSUE THREAD

**Issue by LirazShay** [nunit/nunit#2543] opened 2017-11-08 16:26 UTC
Current Retry-Attribute:
https://github.com/nunit/docs/wiki/Retry-Attribute

> RetryAttribute  is used on a test method to specify that it should be rerun if it fails, up to a maximum number of times.
> Notes:
> It is not currently possible to use RetryAttribute on a TestFixture or any other type of test suite. Only single tests may be repeated.
> If a test has an unexpected exception, an error result is returned and it is not retried

My FR is:
1. Assembly level:
**I need this support in assembly level (I use SpecFlow and need global configuration to run each test once again if failed**
2. Retry also if failed for unknown exception, this is meaningless if it only retry just if assertion was failed, I need it to retry for any failure

Clarification:
What I meant by Assembly level is that is should work exactly like it was declared on all methods,
so if 1 test failed - rerun only it, not the entire assembly / fixture

**Comment by CharliePoole** [comment] 2017-11-08 16:34
Just noting that (1) is a major feature change. That is, it goes beyond merely allowing the attribute to appear at the class and assembly level. We will need completely different code to retry fixtures and possibly different from both of them for assemblies (or at least some differences).

The second request is really separate and I'm not in favor of it. For proper testing, I think you need to write the test to expect the exception. Asserting that something does not throw will convert the error into a failure and allow retry. That's how the Retry feature was designed to be used.

**Comment by jnm2** [comment] 2017-11-08 21:13
You can already accomplish (2) today by converting exceptions into failures via `Assert.That(() => { }, Throws.Nothing);`

**Comment by jnm2** [comment] 2017-11-09 05:51
(1) is a duplicate of https://github.com/nunit/nunit/issues/2452.
(2) can be trivially worked around as I showed, but feel free to reopen if you run into issues with that.

**Comment by CharliePoole** [comment] 2017-11-09 07:03
This doesn't duplicate #2452, which asks for a way to apply a Retry to each method in an assembly. This one asks to actually retry the assembly. (Personally, this one seems reasonable but lots of work, the other seems like a bad idea.)

**Comment by LirazShay** [comment] 2017-11-09 11:21
@CharliePoole 
OK, sorry for the misunderstanding, but I didn't want to retry the entire assembly, I not see any reason to do this in normal execution, of course, sometimes there are flaky tests that failed only when you run the entire assembly but to debug those tests I can just re run the tests manually.

The real reason I need to mark all methods with retry is that I'm using NUnit with Selenium, and until now I never believed in the idea of retrying failing test, and always researched for the reason of the flakiness and fixed those tests.
Recently, when I started with cross browser testing, I had a problem with 3rd party components (like InternetExplorerDriver) that sometime just crashes for unknown reason. 
When I run the test again it will pass, when I run all tests again, another test will fail due to crash of the browser for unknown reason.

I know that in Google, they run ALL their tests in mechanism of retrying failed tests (I don't remember the number of times they use to retry), the idea is that it will help you to recognize flaky test (send alert if failed in first try) but will not fail the entire build.
What do you think?

The solution of wrapping all methods with Assert.That(() => { }, Throws.Nothing); is not usable at all, I have thousands of methods, should I wrap all my code with this dirty code??
It will help if the error is in single place but not if it can happen in multiple places.

**Comment by jnm2** [comment] 2017-11-09 11:59
I do see why both requests would be desirable. Off the top of my head I can't think why it would hurt to retry after exceptions in the method body. I wonder what others think?

**Comment by CharliePoole** [comment] 2017-11-09 16:45
On errors (exceptions) we have previously refused that request: #1388. @LirazShay makes a good case for needing it when some of the components involved in the test are unreliable. My own bias is that a programmer is always supposed to know when an exception is possible and - if necessary - should provide a wrapper that does the retrying. I can, however, see the point in this particular test environment. We could possibly add a property to `RetryAttribute` like `TreatErrorsAsFailures`.

Regarding a general way of setting the retry for subordinate tests, that would be a new feature and I don't think it should be implemented by `RetryAttribute`. We already made that mistake with `TimeoutAttribute`, which has two meanings: (1) set timeout on this test (2) set default timeout for child tests. We should have made a separte `DefaultTimeoutAttribute` and we should probably do the same thing here.

**Comment by jnm2** [comment] 2017-11-09 17:22
I agree with all of that. So this issue is a duplicate of two other issues. Should we take each discussion to the respective original issue?

**Comment by CharliePoole** [comment] 2017-11-09 17:31
Good idea!

**Comment by jnm2** [comment] 2017-11-09 17:39
Alright, closing to move the discussion to:

 - https://github.com/nunit/nunit/issues/2452 to discuss applying default retry settings to all test methods in an assembly
 - https://github.com/nunit/nunit/issues/1388 to discuss an option to to retry on exceptions as well as failure

@LirazShay and @CharliePoole: would you like to comment on the existing issues?

**Closed** 2017-11-09 17:39 UTC
