### ISSUE TITLE
nunit-console hangs on Mac OS X after all tests have run

### ISSUE THREAD

**Issue by rstam** [nunit/nunit#573] opened 2015-04-03 15:38 UTC
Our CI builds on Travis are failing because nunit-console apparently never exits after running the unit tests.

I can reproduce this locally on a Mac using these commands from a Terminal window:

    $ git clone https://github.com/mongodb/mongo-csharp-driver.git
    $ cd mongo-csharp-driver
    $ ./build.sh Build
   
Though many of our tests require a MongoDB server to be running, I can reproduce this using just one of our test projects (one that doesn't require a server):

    $ mono --runtime=v4.0.30319 src/packages/NUnit.Runners.2.6.4/tools/nunit-console.exe -nologo -noshadow artifacts/bin/net45/MongoDB.Bson.Tests.dll -framework:mono-4.0

The tests run to completion, but then nunit-console.exe just hangs and never exits.

We are using version 2.6.4 of NUnit on version 10.10.2 of OS X.

**Comment by CharliePoole** [comment] 2015-04-03 20:00
Can you get turn on the internal trace log from NUnit to see what's going
on?

**Comment by rstam** [comment] 2015-04-03 23:51
I added -trace:Debug as documented here:

http://www.nunit.org/index.php?p=consoleCommandLine&r=2.6.4

But it says Debug is not a valid value. So I tried Verbose instead (found it by running nunit-console -help).

Where is this Verbose trace info supposed to go? Nothing new was output to standard out.

**Comment by CharliePoole** [comment] 2015-04-04 00:39
it's in a log directory under the same Application Data directory where the NUnit settlings are saved. On my Ubuntu system it's ~/.local/share/NUnit but it could vary for different platforms.

If you can't find it easily, you can programatically determine what is returned for special folder Environment.SpecialFolder.LocalApplicationData in your environment and add NUnit/logs

**Comment by rstam** [comment] 2015-04-06 16:16
On a Mac the log files are also stored in ~/.local/share/NUnit. I just needed to know where to find them.

I found two log files:

nunit-console_7543.log
test-domain-MongoDB.Bson.Tests.dll_7543.log

You can see their contents here:

https://gist.github.com/rstam/e2120525f0f544547c33

Looks like something goes wrong when unloading the app domain. But this only happens on the Mac, not on Windows.

Thanks for your help!

**Comment by CharliePoole** [comment] 2015-04-07 14:58
Interesting. We recently (either 2.6.3 or 2.6.4) changed the code to wait 30 seconds for the AppDomain to unload and then exit. Previously we waited indefinitely. The change was supposed to _prevent_ hanging the runner like this and appeared to succeed, at least on Windows.

You say this runs OK on Windows, can you check the log there and see if the same error appears? If it does, then it would seem that process and domain termination on the Mac works differently from what it does on WIndows. If you have a non-Mac Linux system and can run there, it would be interesting to know what happens there. If this turns out to be a mono rather than mac issue, we may be able to get some help on the mono list.

Clearly, something is happening in one of your tests to prevent the domain from unloading. If it's caused by a single test, you can find it by tthe tedious process of running half your tests, then a quarter, etc. OTOH, if it's caused by the interaction of two or more tests - like some sort of deadly embrace - then finding the cause is... even more tedious!

**Comment by rstam** [comment] 2015-04-07 20:10
When I run the same test that I ran on the Mac (command line adjusted as necessary) nunit-console.exe exits immediately when it is done running the tests. There is no delay of any kind at the end.

I could only find one log file on Windows. Its contents are here:

https://gist.github.com/rstam/d4aeb4aad635efb9a60d

Not sure why there were two log files on the Mac but only one on Windows.

**Comment by rstam** [comment] 2015-04-07 20:41
I redirected the output of a test run with -labels to a text file and edited it to make a runlist.txt file. I then ran more and more of the tests until I got nunit-console.exe to hang. I can run the first 634 tests without nunit-console.exe hanging. When I add the 635th test then nunit-console.exe hangs.

This is the 635th test in the runlist.txt file:

https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Bson.Tests/IO/BsonStreamExtensionsTests.cs#L54

Take a look and see if there is anything in this test that catches your attention.

One thing I notice is that this is probably the first that uses the NSubstitute library. Perhaps NSubstitute is doing something that is preventing the AppDomain from unloading?

**Comment by rstam** [comment] 2015-04-07 21:32
I can now reproduce nunit-console.exe hanging using this simplified project that has a single test in it:

```csharp
using System.IO;
using FluentAssertions;
using NSubstitute;
using NUnit.Framework;

namespace TestNUnitConsoleHang
{
    [TestFixture]
    public class TestClass
    {
        [Test]
        public void TestNSubstitue()
        {
            using (var stream = Substitute.For<Stream>())
            {
                stream.Should().NotBeNull();
            }
        }
    }
}
```

**Comment by Amarok79** [comment] 2015-05-07 07:00
Hello!

I don't think this is related to your tests, because we have a very similar problem with nunit-console.exe hanging after running even the simplest test case. For us, this only happens when using nunit-console on Mono (4.0.1) on Windows, but not when using the same Mono on Linux. We don't test on Mac.

We can even reproduce nunit-console not returning by calling it on Windows with following command line:

    "c:\Program Files (x86)\Mono\bin\mono.exe" --runtime=v4.0 "c:\program files (x86)\NUnit 2.6.4\bin\nunit-console-x86.exe" c:\*

Specifying c:\* causes nunit-console to fail because it can't find any dlls and tests. On Windows, it never returns. On Linux, it returns as intended.

The same behavior when running simple unit tests.

**Comment by rprouse** [comment] 2015-09-08 14:33
I used your example code on a Mac running mono 4.0.3 and the latest version of NUnit 3.0 and can confirm that this issue is fixed in 3.0.

```C#
using System.IO;
using NSubstitute;
using NUnit.Framework;

namespace TestNUnitConsoleHang
{
    [TestFixture]
    public class TestClass
    {
        [Test]
        public void TestNSubstitue()
        {
            using (var stream = Substitute.For<Stream>())
            {
                Assert.IsNotNull(stream);
            }
        }
    }
}
```

I also tried the command line above.

Since this is fixed in 3.0 and won't be putting out new releases for the 2.6.x stream, I am closing this issue.

**Closed by rprouse** 2015-09-08 14:33 UTC
Labels: is:bug, pri:normal, status:confirm

**Comment by TioNoob** [comment] 2019-08-16 03:34
I'm having the same problem using the NUnit3. It happened on my Mac yesterday too.
I enabled the --trace option with the Verbose value, but the runner didn't print anything.

I have just one test that runs instantaneously on my WIndows machine, follows the test file:
https://github.com/TioNoob/web-page-screensaver/blob/master/WebpageScreensaver.Test/Extension/ListExtensionTest.cs

Follow the Travis logs:

with the NUnit Runner 3.9:
https://travis-ci.org/TioNoob/web-page-screensaver/builds/572576631#L1396

with the NUnit Runner 3.10:
https://travis-ci.org/TioNoob/web-page-screensaver/builds/572574087#L1400

Ps.: It's not a problem of not founding the file, cause' on a build, it hasn't found the file and threw an error:
https://travis-ci.org/TioNoob/web-page-screensaver/builds/572575903#L1396

**Comment by mikkelbu** [comment] 2019-08-16 12:54
The `--trace` option just output more information into the log files, but unless you expose these as artifacts from the build then I don't think you can access them (and the file names are depending on the process ids).

What happens if you add `--inprocess` to run inprocess? You can also add `--labels=All` to make the console write before each test.
