### ISSUE TITLE
Data type conversion

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1881] opened 2016-11-04 00:26 UTC
In many places, the Convert.ChangeType method is used to convert the type of an object to a desired type.

This works fine for the base types (Boolean, Char, SByte, Byte, Int16, Int32, Int64, UInt16, UInt32, UInt64, Single, Double, Decimal, DateTime and String) and for user-defined types that implement IConvertible.

However, for all other types, a TypeConverter needs to be used.

NUnit currently does not use the TypeConverter class anywhere.

It would seem useful to add support for TypeConverter in some of these conversion instances.  For instance, the ValuesAttribute would be seemingly be enhanced by doing so.

**Comment by oznetmaster** [comment] 2016-11-07 00:46
No thoughts on this?

**Comment by CharliePoole** [comment] 2016-11-07 00:57
Duplicate of #89?

**Comment by oznetmaster** [comment] 2016-11-07 01:35
Related, I guess.

Certainly applies to TestCase, but also to Parameters.Get<>, TestValues, and many other places.

Since Cf is no longer an issue, TypeConverter should be a solution that would work in all builds.

I use it in my CF build wherever Convert.ChangeType is currenty used.  I check if Convert.ChangeType is applicable (through a global HashSet of convertible types), and if not, then try to use TypeConverter.

**Comment by CharliePoole** [comment] 2016-11-07 02:58
We usually make better progress with issues that are narrower in scope. Maybe we should think about identifying one place where this change could be made profitably.

**Comment by oznetmaster** [comment] 2016-11-07 03:10
I think that if its made, it needs to be made in those three places at the same time.

Otherwise, support for arbitrary types will be inconsistent.

In my CF build, most of the code was common anyway.

**Comment by rprouse** [comment] 2020-05-18 19:06
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 19:06 UTC
