### ISSUE TITLE
NUnit runner(?) 3.4.1 issue with test runners

### ISSUE THREAD

**Issue by leadensky** [nunit/nunit#1665] opened 2016-07-14 16:55 UTC
I previously posted this issue under Docs issues (my apologies for placing it in the wrong place). [https://github.com/nunit/docs/issues/92#issuecomment-232715712](url)

Quick summary of the previous issue post, after updating my test projects from NUnit 3.0.1 to 3.4.1, many of my tests won't, indeed don't even appear as tests to at least two different test runners: DevExpress and NCrunch. After rolling back to 3.0.1, everything worked again. On subsequent attempts, 3.2.1 also worked correctly.

Charlie, if you want to close this for the same reasons you posted on my other issue, I guess that's fine. It just seems that something is wrong since both runners are having similar issues trying to use 3.4.1. I guess I also just want to get this out there in case other people run into the same problem.

I haven't tried 3.4.0, but I'll do that next.

_Thank you_...and sorry if I'm wasting your time by reposting.

**Comment by CharliePoole** [comment] 2016-07-14 17:05
@leadensky No problem. It's not a waste of time and it **is** possible more people will notice it here than in the docs repo - although I think Google will find it there as easily as here. :-)

As I explained on nunit/docs#92, the two problems don't actually look that similar. In both cases, it appears that "something" we changed, which we consider internal is being depended on by them. But from the limited stack traces, it looks like the two of them are depending on different "somethings" and any similarity may be coincidental.

We have tried very hard to tell those vendors who joined our third-party mail list exactly what we consider to be a published api and what not. For that reason, I want to put the burden on those guys, who actually have day jobs working on their applications, to specify what problem they may be having. The burden should not be on either you or on us to do that and I think it's a responsibility that third-party vendors generally accept.

To help things along, @remcomulder could you comment on the problem that @leadensky is having?

DevExpress guys, I don't have contact with you, but it would be great if you could chime in as well. :-)

**Comment by CharliePoole** [comment] 2016-07-14 17:08
@leadensky Sorry you had to repost this. I could have just moved it myself at the click of a button! But I figured that at least NCrunch, with whose author we regularly work, would post something pretty quick anyway.

**Comment by leadensky** [comment] 2016-07-14 18:09
It's definitely something with 3.4.0 and above, and appears to be nunit, not nunit.runner. I've tried both 3.4.0 and 3.4.1 of nunit and both exhibit the problem. 3.2.1 does not. I'll hit up DevExpress support and see what they have to say.

**Comment by remcomulder** [comment] 2016-07-14 23:00
Thanks for sharing this problem.  I'm looking into this now, but I need some more help with reproducing it.  NCrunch investigation thread is here - http://forum.ncrunch.net/yaf_postsm8975_NCrunch-is-not-seeing-some-tests.aspx#post8975

**Comment by remcomulder** [comment] 2016-07-17 00:12
Ok, with much help from a few people I've now managed to reproduce this problem.

It looks like there was a functional change in v3.4 with how the classname of a test-case is reported in NUnit's XML.

Prior to v3.4, the classname of a test-case was always set to the type name of its _parent fixture_.

After v3.4, the classname of a test-case is now set to the type name of the _declaring_ type.  So this means the value is now different for any test that is inherited from a base class.

This causes NCrunch to explode in situations where a test is being inherited from a base class in another assembly, as it doesn't expect the fixture type to be sourced from a different assembly and doesn't think to look there.

I've included XML captures of a the same test project run between both versions of NUnit.  Note that the classname field has a different value:

---- NUnit 3.4.1
```
<?xml version="1.0" encoding="UTF-8"?>
<test-suite type="Assembly" id="1002" name="ClassLibrary5.DLL" fullname="F:/NCrunch/17984/2/ClassLibrary5/bin/Debug/ClassLibrary5.DLL" runstate="Runnable" testcasecount="1">
   <properties>
      <property name="_PID" value="11668" />
      <property name="_APPDOMAIN" value="nCrunch.TestRunner.AppDomain_b91bc65980914a65bb4383654379ae75" />
   </properties>
   <test-suite type="TestSuite" id="1003" name="ClassLibrary5" fullname="ClassLibrary5" runstate="Runnable" testcasecount="1">
      <test-suite type="TestFixture" id="1000" name="Fixture" fullname="ClassLibrary5.Fixture" classname="ClassLibrary5.Fixture" runstate="Runnable" testcasecount="1">
         <test-case id="1001" name="instantiate" fullname="ClassLibrary5.Fixture.instantiate" methodname="instantiate" classname="ClassLibrary1.SimpleSUTBase`1" runstate="Runnable" seed="1732936252" />
      </test-suite>
   </test-suite>
</test-suite>
```
---- NUnit 3.2.0
```
<?xml version="1.0" encoding="UTF-8"?>
<test-suite type="Assembly" id="1002" name="ClassLibrary5.DLL" fullname="F:/NCrunch/17984/30/ClassLibrary5/bin/Debug/ClassLibrary5.DLL" runstate="Runnable" testcasecount="1">
   <properties>
      <property name="_PID" value="6928" />
      <property name="_APPDOMAIN" value="nCrunch.TestRunner.AppDomain_0391681403bf48e3958de60bb40e44fe" />
   </properties>
   <test-suite type="TestSuite" id="1003" name="ClassLibrary5" fullname="ClassLibrary5" runstate="Runnable" testcasecount="1">
      <test-suite type="TestFixture" id="1000" name="Fixture" fullname="ClassLibrary5.Fixture" classname="ClassLibrary5.Fixture" runstate="Runnable" testcasecount="1">
         <test-case id="1001" name="instantiate" fullname="ClassLibrary5.Fixture.instantiate" methodname="instantiate" classname="ClassLibrary5.Fixture" runstate="Runnable" seed="2031539648" />
      </test-suite>
   </test-suite>
</test-suite>
```

In many ways, this change actually makes good sense.  Without the classname being set to the declaring type, we actually wouldn't have any way of knowing (from the XML) which type physically declared the test.  In my case, it's not something I really care about, but perhaps someone else might.

The type name of the parent fixture can always be obtained by just traversing upwards to the fixture and extracting its classname.  In this way, I can fix NCrunch to make it work with the new change.

However ...

It still means that the NUnit API has a functional difference between versions of the framework.  This means every test runner that uses this field would need to implement special handling across different versions of NUnit.  I believe it is the goal of the API to avoid this kind of thing, as it tends to create confusion for all our users.  For example, if I fix this problem in NCrunch now, I'll need to advise any user that they'll need to upgrade to NCrunch v2.24 if they want to work with NUnit v3.4 or above .. otherwise they'll just get weird behaviour with missing tests and obscure errors.

What are your thoughts Charlie?

**Comment by CharliePoole** [comment] 2016-07-17 05:19
This change came out of issue #1366. The intent wasn't to change the API, rather it was to fix the implementation so that the API worked as originally intended. This is shown in the docs for the `<test-case>` element at https://github.com/nunit/docs/wiki/Test-Result-XML-Format#test-case but I can see that it's possible to read the definitions in different ways.

Classname and methodname were added as attributes in the first place so that the VS Test Adapter - as well as future clients - could figure out where in the source the class is defined. We tried to reflect this intention in the docs for the `<test-case>` element at https://github.com/nunit/docs/wiki/Test-Result-XML-Format#test-case but the wording is probably not clear enough.

In any case, it sounds as if you are using these attributes for some purpose we never thought of. Can you enlarge a bit on how you use it? Then maybe we can come up with a workaround.

**Comment by remcomulder** [comment] 2016-07-17 05:38
At the moment, I'm only using the classname attribute as a shortcut to get the name of the fixture the test-case is discovered under.  NCrunch uses this information to correlate the test-case's physical method with data that is obtained from the assembly's IL, thus finding the first code line of the method and using this as a point of navigation and other things.

It was implemented this way because by observation, the field seemed to contain the data I needed to do this and it seemed to be easily accessible.  It isn't really necessary for NCrunch to use it in this way, as the data is actually available on the fixture itself.

If you were to ask my opinion about the design itself, I would say it is more useful and more sensible to have the field describe the declaring type and not the fixture type, so basically I would agree with the change that has been made.  It's just a little unfortunate that its a breaking change for NCrunch.

I think the cleanest way to change behaviour like this would actually be to introduce a new field in the XML.  For example, 'declaring-type-classname'.  In this way, any existing consumer of the API will see no functional change to the classname field, and any consumer that needed the fixed behaviour could reference the new field.

**Comment by remcomulder** [comment] 2016-07-17 05:55
I just want to add that I think how NCrunch uses this data and why it fails on the change is actually a fairly academic discussion.  From the NCrunch side, it's trivial to fix it.

But this would mean that anyone using a version of NCrunch below v2.24 will have a very bad experience when they update their NUnit.

So in my view, it's about choosing between two evils.  Either we have a slightly less sensible design, or we have a few thousand (?) developers that get a confusing experience followed by the need to upgrade their tooling.

**Comment by CharliePoole** [comment] 2016-07-17 17:26
@remcomulder Ironically, the change to fix bug #1366 was proposed by a contributor who initially wanted to create a new DeclaringClassName attribute. I commented on the change that the existing attribute was only used for the purpose of locating the source code and was broken for that purpose, so we didn't really want to multiply attributes. :-( I was pretty certain that no third-party runner was making use of the field, unless it were to locate the source code, because that was it's purpose.

I think the initial (non-academic) purpose of this thread should be to find out what, if anything, you would like to see done about this now. We can't turn back time - NUnit 3.4 and 3.4.1 have already been released. It's too bad that this didn't come up in the discussion of the original bug, but that's water under the bridge as well.

The second purpose, which I guess you are calling academic, but which I don't see as such, is to figure out how to avoid such situations in the future. An approach such as you describe of never changing the content of any attribute or element in the XML sounds wrong to me. If a field has a bug in it, we should fix that bug, even if there is a remote possibility that somebody has come to depend on the existence of the bug. There may be a need to vet certain changes but it's unlikely that we can do that for everyone. We can do a bit more, however, for third-party authors like you, who actually communicate with us. How can we know that we are about to break something before we do it? How can we do that without slowing down the pace of development, which already seems glacially slow?

Any ideas on either point?

One possibility on our side may be to describe what API-like guarantees we are willing to give for the stability of the XML. The major reason we use XML results is so that we can change them as time goes on without breaking the APIs you use to get those results. Technically, all we are guaranteeing is that we will return a well-formed XML string from the framework and an XmlNode from the engine. Obviously, there are some things we shouldn't change about that XML, but we don't actually say anywhere what those things are. I'm not sure how to go about this sort of documentation. We don't currently have a schema, but I don't think that would have helped us in this case anyway. If such documentation existed somewhere - it would have (perhaps) warned you from using the field in the way you used it. Sounds like a lot of work though. :-(

We do document through our tests, of course. But the bug in question arose precisely because we didn't have a test for an inherited test case. One was added as a part of the fix. 

First priority then... what can we do? Second priority... what can we do in future?

**Comment by remcomulder** [comment] 2016-07-17 23:31
@charliepoole I think we got really unlucky here.

The part of NCrunch that broke here didn't actually break because NCrunch's view of this field was different from what it was changed to.  The logic NCrunch uses to correlate the test method's first line actually would have worked fine with the updated field, the only reason it failed was because of an assumption that the method should only be found within the test assembly (and not within a referenced one).

In an ideal world, we'd have some kind of integrated CI between the products where a change made to one would also be tested against the other.  It isn't really practical to set up and maintain something like this though (especially as NCrunch is closed source).

In terms of what we can do now, I'm about to release v2.24 including a fix for this issue.  The timing of this isn't so bad, as I needed to do a release to fix some other problems anyway.  v2.24 will still work regardless of whether the classname field is changed back or it stays the same (v2.24 doesn't use it on test-case).

I think it should be NUnit's decision whether to back out the classname change.  There is a benefit to doing so - even though 3.4.1 won't work, most of the people that have already updated to this version will be tracking the latest version through Nuget, so a new version will essentially make 3.4.1 redundant for all but a tiny minority.  The question is whether you would want to live with the existing bug (or a new XML attribute) in the API over the long term.  Note that if the bug is fixed 12 months from now, the impact will be smaller as most people will probably already be running on fixed NCrunch builds.

In terms of how to handle situations like this in future, I don't think there is an ideal approach.  Really this is about balancing the need to keep an API stable with the need to continue to fix and advance the product.  If the API never changes, the product stagnates and problems can pile up.  If the API is constantly adapting, consumers are all living on a treadmill of changes and users will become reluctant to update NUnit for fear of breaking their tooling.  Really, we need a bit of both.

My suggestion would be to try to contain any breaking changes to the API to be only in major releases of NUnit - even if they are fixing erroneous behaviour.  In this way, consumers have a chance to perform a full regression test against a major version while it is in a beta state or shortly after its release.  This way you would have the flexibility to continue to release frequently, and still have the chance for more controlled careful releases where tool vendors can be involved.  NCrunch has around 9000 tests at the moment running through/over NUnit in different environments, which could be a great asset when making any functional changes.  I expect other tool vendors will also have similar setups.

**Comment by CharliePoole** [comment] 2016-07-18 03:01
Ah... that makes sense. Of course, the situation could not arise if we didn't report the base class. Ironically, the class name is of no help to us in this situation unless the source of the base class happens to be  available.

So, if I have understood correctly, this will only break those users who have tests that inherit from a base class in another assembly. Have I got that right? That sounds like a pretty limited number but we'll give it a thought and also check if there is anything else calling for a hot fix. Otherwise, the next minor update wouldn't be for three months in our normal schedule.

In the long term, I agree we need some kind of integration testing with various products. Of course, such tests would not have caught this problem unless we included the situation that triggers it. Our own unit tests certainly don't deal with inheritance from a class in a separate assembly.

**Comment by remcomulder** [comment] 2016-07-18 04:33
Your understanding is correct.  This only affects users with tests that inherit across assemblies.  It's been my observation that people working on large projects very often do this, so my gut feel is that it's a fairly common case.  I have no data to support this theory.

I'm aiming to have v2.24 out within the next couple of days, so I guess from my side it's more a matter of knowing what to advise our users.  I'll assume that the 3.4.1 change stays in effect.  If you do decide on a hotfix, let me know and I'll pass on the word to those affected.

**Comment by SeriousM** [comment] 2016-07-18 07:23
> Your understanding is correct. This only affects users with tests that inherit across assemblies. It's been my observation that people working on large projects very often do this, so my gut feel is that it's a fairly common case.

I worked for big companies and all of them had a common base class for performance measurements, logging or ioc setup (so you just have to import what you want to test).

> I have no data to support this theory.

I do, and it is definitely a large portion of professional developers that are affected by this defect.

**Comment by mkoertgen** [comment] 2016-07-18 07:37
I second that. We use common base fixtures in almost all of our bigger projects, usually for convention checks similar to https://github.com/awesome-inc/NEdifis#convention-tests

**Comment by leadensky** [comment] 2016-07-18 13:30
I also use common base classes for many of my tests.

**Comment by ChrisMaddock** [comment] 2016-07-18 13:50
Looking at avoiding such problems in future, should we consider releasing an RC for each new version? I remember Teamcity had similar problems for 3.4.0. 

If we did this, we could allow third-party libraries (and any keen users) time to test, and catch such issues before release. @CharliePoole - is NUnit talking to enough 3rd party developers to make that viable? And @remcomulder - do you have tests which would have caught this before release?

**Comment by CharliePoole** [comment] 2016-07-18 13:57
@ChrisMaddock I've been thinking of getting away from formal RCs, because they don't seem to catch any issues. I guess an alternative would be to have them and (somehow) get more people to participate.

Another alternative is to have an unstable feed as we have discussed separately and to try to get the folks with third-party runners to consume it.

We could, of course, do both. (I'd still like to get away from alphas and betas, however)

**Comment by rprouse** [comment] 2016-07-18 14:24
I would also prefer to stay away from RC releases. Our experience is that they are not well tested by the community, so they increase our work for limited benefit. I would prefer to start promoting our CI feeds for 3rd Party developers to consume in their integration tests. They can stand in for RCs but give a much longer runway for testing changes.

I would also like us to be more diligent in posting changes we are making to the 3rd Party Developers mailing list and taking more time with PRs that might affect them. For example, we should notify about any engine API additions or changes, about any changes to events and any changes to the XML format, even if they are just bug fixes.

Short term, we should ensure that all @nunit/core-team members are on the 3rd Party Developer mailing list. @CharliePoole, should we also advertise the existence of the list along with the other mailing lists? We can continue to make it an approved person only list, but I don't think there is any reason to keep its existence quiet.

**Comment by CharliePoole** [comment] 2016-07-18 15:46
I confess I have pretty much stopped posting to the 3rd party list as it didn't seem to get much traffic coming back from vendors. I suppose they don't incline to communicate their own approaches to one another. We should think about how (if) we want to use it.

**Comment by remcomulder** [comment] 2016-07-18 22:32
I agree with much of Rob's comments, though I think that in certain cases, an RC or beta can still be of use.  For example, if there is a release including known API changes that could affect 3rd party devs, it's really useful to have an early build we can play with that we know is a candidate for release.  I certainly wouldn't suggest this for every build.

Speaking as a tools vendor, I can understand why other 3rd parties are not very interested in responding on the mailing list.  These people are juggling many integration points at one time along with other planned features and support issues, so being proactive on NUnit changes is difficult to allocate time for.  The ecosystem has become so large and fragmented that even keeping track of how products are changing is very difficult to balance with productive time spent actively building or fixing things.  You might find that many of them are still listening to the broadcasts on the mailing list but don't have time to add to the discussion.  IMHO if you are looking to give people a heads up, the mailing list might still be useful.  At the very least, you can always say 'I told you so!' :)

I'm fairly certain that my tests would have picked up on this problem had I set up NCrunch to target this version of NUnit.  My main problem is that it does still take some effort to update the suite to target the new version (in addition to all the older versions), so I prefer to only do this when I know it's a big release that could cause problems.  Again, this is where batching up API or large scale changes would be very helpful for me.

**Comment by CharliePoole** [comment] 2016-07-18 22:38
I think both @rprouse and I are thinking of the unstable nuget feed as a sort of continuous beta or rc. We want to refine it but it actually is available each time we merge a feature to master.

**Comment by CharliePoole** [comment] 2016-07-18 22:39
Maybe all that's needed is to tell you when a release is close.

**Comment by jcansdale** [comment] 2016-07-18 22:52
> Maybe all that's needed is to tell you when a release is close.

How about opening a "3rd party integration" issue when a significant release is close? 3rd party devs can then try out the new binaries and hopefully flush out any problems. Having a specific time and place to do this might work out better than a more general mailing list.

**Comment by remcomulder** [comment] 2016-07-18 23:13
@CharliePoole @jcansdale If this can be done with a short comment identifying whether the release contains anything that might impact 3rd parties, then that would be absolutely perfect.

**Comment by remcomulder** [comment] 2016-07-20 13:16
NCrunch v2.24 is released now, with a fix for this issue - http://www.ncrunch.net/download

**Comment by rprouse** [comment] 2016-10-25 02:34
I am closing this as fixed in NCrunch.

**Closed by rprouse** 2016-10-25 02:34 UTC
