### ISSUE TITLE
System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host --SocketException

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit#4636] opened 2024-02-22 08:12 UTC
### My version

NUnit Console:  3.16
NUnit framework 3.13.3
Net framework: 4.8

### Issue description

I encounter a crash of my NUnit test agent problem that happens quite _intermittently_.  The test runner terminates itself about 30~ minutes into the run, and after running hundreds of tests.  

I encountered the crash only since the beginning of February, though we did check in code during this period of time, but none of the code change could explain why the crash happened, and prior to February, the test agent didn't crash at all. 

The log files are attached at the end of this message. Hopefully someone can shed some light!

Here's the error message:

```
1) 
System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
--SocketException
An existing connection was forcibly closed by the remote host

Server stack trace: 
   at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.Process

Message(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)


Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2024-02-22 05:29:39Z
    End time: 2024-02-22 05:57:04Z
    Duration: 1645.483 seconds


NUnit.Engine.NUnitEngineUnloadException : Multiple exceptions encountered. Retrieve AggregatedExceptions property for more information
  ----> NUnit.Engine.NUnitEngineUnloadException : Agent Process was terminated successfully after error.
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:52188

```

In the NUnit console, I've used `--labels=before` to identify where the test stops prematurely, and every single time the test runner crashes, it always _always_ stops at `MiTS.IntegrationTest.EW3D.VM.Action.BatchUpdatePlatformDisplayTest.ChangeInPropertyGrid`. No idea why, but disabling that test and the few immediate tests before and after seem to solve the issue ( though I have to run it a few more times to be sure).

And of course, if I run `MiTS.IntegrationTest.EW3D.VM.Action.BatchUpdatePlatformDisplayTest.ChangeInPropertyGrid` by itself, then it **_won't_** crash at all, **not a single time**. 

I also can reproduce the crash of NUnit agent in test explorer, so I don't think it's the NUnit console or test explorer problem. 

### What could cause the crash of NUnit agent? 

As I refer to the event viewer, and I get two different errors (**STATUS_STACK_BUFFER_OVERRUN** and **heap corruption error**), both of which seems to indicate that the problem happens much earlier, based on my reading of forum posts. I have no idea why disabling the test and the neighboring ones solve the issue. 

```
Faulting application name: nunit-agent.exe, version: 3.16.2.0, time stamp: 0xfaf2cc19
Faulting module name: ucrtbase.dll, version: 10.0.22621.2506, time stamp: 0x097c794c
Exception code: 0xc0000409
Fault offset: 0x000000000007f61e
Faulting process id: 0x0x2888
Faulting application start time: 0x0x1DA65581A051CB3
Faulting application path: C:\Users\User\Documents\MES\Assemblies\NUnit\NUnitConsole\agents\net462\nunit-agent.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: a5c72fe0-cd5b-41e6-a8d5-698820a8c155
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Faulting application name: nunit-agent.exe, version: 3.16.2.0, time stamp: 0xfaf2cc19
Faulting module name: ntdll.dll, version: 10.0.22621.3085, time stamp: 0xbced4b82
Exception code: 0xc0000374
Fault offset: 0x000000000010c7a9
Faulting process id: 0x0x19A0
Faulting application start time: 0x0x1DA65502CC0A163
Faulting application path: C:\Users\User\Documents\MES\Assemblies\NUnit\NUnitConsole\agents\net462\nunit-agent.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 0ebe2a0c-0ee2-460c-a0dd-a8a41d14bd5f
Faulting package full name: 
Faulting package-relative application ID: 
```

I tried to use `--inprocess` to see whether I can get more clues out, but then I don't feel that it could be fruitful, plus there seems to be [a bug](https://github.com/nunit/nunit-console/issues/1390) with nunit console with respect to `--inprocess` and `App.config`. 

### About NUnit console setting:

I've turned on the `legacyUnhandledExceptionPolicy` and `legacyCorruptedStateExceptionsPolicy`, just so that `AccessViolationException` won't crash the test runner. 

```
    <legacyUnhandledExceptionPolicy enabled="1" />
    <!--
     Since legacyUnhandledExceptionPolicy keeps the console from being killed even though an NUnit framework
     test worker thread is killed, this is needed to prevent a hang. NUnit framework can only handle these
     exceptions when this config element is present. (Or if future versions of NUnit framework drop support
     for partial trust which would enable it to use [HandleProcessCorruptedStateExceptions].)
    -->
    <legacyCorruptedStateExceptionsPolicy enabled="true" />
```

[TestResultCombined.txt](https://github.com/nunit/nunit-console/files/14370504/TestResultCombined.txt)
[InternalTrace.6560.MiTS.IntegrationTest.dll.log](https://github.com/nunit/nunit-console/files/14370512/InternalTrace.6560.MiTS.IntegrationTest.dll.log)
[InternalTrace.6560.log](https://github.com/nunit/nunit-console/files/14370513/InternalTrace.6560.log)

**Comment by OsirisTerje** [comment] 2024-02-22 08:34
Does the same happen with version 3.17?

**Comment by WindingWinter** [comment] 2024-02-22 08:36
> Does the same happen with version 3.17?

You mean `NUnit Console` 3.17? Not sure.

Any reason to think that it might make a difference? I ran it also in test explorer on a different machine, and I could reproduce the crash issue. So I don't incline to think that this is a NUnit console issue.

**Comment by OsirisTerje** [comment] 2024-02-22 09:19
Yes.  If you search the issues in NUnit.Console you will see a series of similar crash issues in the 3.16 series.  
The 3.17 comes from the 3.15 and 3.15 is used in the adapter, thus in dotnet test.  No such issues reported there, but then it also works differently.

**Comment by OsirisTerje** [comment] 2024-02-22 09:23
>  I ran it also in test explorer on a different machine, and I could reproduce the crash issue. So I don't incline to think that this is a NUnit console issue

Noticed you said this, which means you run with the 3.15 engine and adapter.  We don't have any such errors reported in the adapter though, nor here in the nunit repo.  Since it happens intermittently it is hard to repro this.

**Comment by stevenaw** [comment] 2024-02-24 18:57
@WindingWinter You mentioned that when it happens it is always when a particular test is running, and that commenting out some of the immediate tests stops the errors.

Is there anything unique about those tests relative to the rest of the suite which could contribute here? Given these seem to be integration tests, I'm also wondering if perhaps a data change (or something else consumed by your tests) could've also changed a behavior here.

Separate, but related: Is there any chance COM or partial trust is also at play here based on what your tests are doing?

**Comment by WindingWinter** [comment] 2024-02-27 02:26
@stevenaw ,

Could be be a data change ( eg: a singleton) on a multithreading nature of the code that causes the issue? Possible, but I'm unsure how to debug further. You have any idea?

As for the COM or partial trust, I'm not sure how it is relevant here. True, our code calls C++ code, but we've already set `legacyUnhandledExceptionPolicy`  and `legacyCorruptedStateExceptionsPolicy` as enabled

```
    <legacyUnhandledExceptionPolicy enabled="1" />
    <!--
     Since legacyUnhandledExceptionPolicy keeps the console from being killed even though an NUnit framework
     test worker thread is killed, this is needed to prevent a hang. NUnit framework can only handle these
     exceptions when this config element is present. (Or if future versions of NUnit framework drop support
     for partial trust which would enable it to use [HandleProcessCorruptedStateExceptions].)
    -->
    <legacyCorruptedStateExceptionsPolicy enabled="true" />
```

So that shouldn't affect anything I suppose?

**Comment by stevenaw** [comment] 2024-02-27 03:09
Admittedly, it will be tough for us to get to the bottom of this for you without an easy, runnable repro. The root cause here, unfortunately, is likely something within your codebase. However, I have a few thoughts that may help you narrow down the cause:

The fact that the suite reliably fails at a particular point, and completes when it and a few other tests are commented out, indicates that something about either those tests or the system under test is causing the corruption. I'd asked about COM as stack corruption is much easier to accidentally occur in C++. Partial Trust also factors is here as an application running under `PartialTrust` will cause settings like `legacyCorruptedStateExceptionsPolicy` [to be ignored](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.handleprocesscorruptedstateexceptionsattribute?view=netframework-4.8#remarks), however re-reading your earlier statement this must not be the case for you if the setting prevented a crash.

There is, also, apparently an edge case that link mentions which could also be relevant in your case:

> This configuration element has no effect on applications that were compiled in versions previous to the .NET Framework 4 but are running in the .NET Framework 4 or later; corrupted state exceptions will continue to be delivered for those applications. 

I hope some of this could be of help. The earlier suggestion above to see if any similar issues in the https://github.com/nunit/nunit-console repo seem familiar may also help provide additional threads for your investigation

**Comment by WindingWinter** [comment] 2024-02-28 02:15
I'm not too sure it has anything to do with how Autofac does the Dispose thing, because if I comment out the Autofac dispose on the test immediately preceding the crash point, then no such issue. Here's[ the ticket](https://github.com/autofac/Autofac/issues/1413).

**Comment by WindingWinter** [comment] 2024-02-28 02:17
@stevenaw , about the point that you raise


> This configuration element has no effect on applications that were compiled in versions previous to the .NET Framework 4 but are running in the .NET Framework 4 or later; corrupted state exceptions will continue to be delivered for those applications.

I think it's still not relevant in my situation because my applications are compiled in .Net framework 4.8, so it should have effect on the applications.

**Comment by stevenaw** [comment] 2024-02-28 11:43
Great work narrowing it down to a dispose call! I'm going to close this issue as it doesn't seem nunit-related in cause. Best of luck with your investigation.

**Closed by stevenaw** 2024-02-28 11:43 UTC
