### ISSUE TITLE
Runtime parameter validation

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1771] opened 2016-08-27 00:35 UTC
Now that there is the ability to specify runtime parameters on the command line, it would be very useful to be able to validate them.

I am thinking of something like a UseParameterAttribute that could be applied to the assembly, namespace, TestFixture, or Test.  The attribute would have the parameter names, acceptable value type, and perhaps even a description.

When the test suite is initiated, all of the valid parameter names (and perhaps types) would be obtained from the test assemblies and accumulated in a dictionary.  Then, that dictionary would be used to validate the parameters entered on the command line prior to actually running any tests.

If a parameter is entered which is does not validate, either a warning could be given, or the test run could be inhibited.

Validation could be both for parameter name and for type.

Also, the explore command line option would not only list the tests, but that acceptable parameters.  This would allow a GUI to provide a list of parameters (and descriptions), and to only accept valid values for them.

**Comment by oznetmaster** [comment] 2016-09-16 22:44
This could even be carried further, and allow the parameters specified in the attribute to be passed to the test as method arguments.

```
[UseParameter ("mystring", typeof(string)]
public void Test (string mystring)
{
}
```

**Comment by oznetmaster** [comment] 2016-10-01 05:08
No comments at all? :(

**Comment by CharliePoole** [comment] 2016-10-01 15:41
Well, I've been keeping quiet to see if somebody came along to agree with it. I don't like it as a feature.

When we implemented run parameters, we decided to do it in a way consistent with how other frameworks, notably MsTest implement them. That is, it's up to the test code to access the parameters. They are all strings, which is what they start out as when entered either on the command-line or in a .runparameters file (for the adapter). It's up to the test code to verify that the string is actually an int.

I would support enhancements to the way we do it, perhaps making it easier to verify that the string passed can be converted, or even having some conversion embedded in the TestContext for the user to call. I can't support backing away from the earlier decision in favor of an attribute-based approach.

**Comment by oznetmaster** [comment] 2016-10-01 16:47
After I added support for the parameters to my GUI, I discovered my users were using them a lot.

Being able to have all available parameters displayed in the GUI, along with validation of values entered for them, was a significant enhancement to just have a place to enter them.

The only way I could see to easily do that was with attribute based definition of the parameters used in each test, if any.

I implemented it that way, and it works very well.

**Comment by CharliePoole** [comment] 2016-10-01 16:57
I'll continue to wait for others to chime in. :-)

**Comment by oznetmaster** [comment] 2016-10-01 16:59
How do you propose to handle parameters in the NUnit GUI?

**Comment by CharliePoole** [comment] 2016-10-01 17:49
I haven't thought much about it since it's a brand new feature to support.
Client-side validation seems out of the question in a runner that supports
multiple frameworks without adding an entire capabilities API to every
framework.

On Oct 1, 2016 9:59 AM, "Neil Colvin" <notifications@github.com> wrote:

How do you propose to handle parameters in the NUnit GUI?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nunit/nunit/issues/1771#issuecomment-250923475>, or mute
the thread

**Comment by rprouse** [comment] 2016-10-03 13:46
I like the fact that this would make the parameters discoverable. The problem with the existing parameters is that they are invisible unless you search through the code, so you need to document what your tests require. If we were to do this, I would like to see it extended so that it includes default values and descriptions of what the parameter is used for. We could then add a command line option to output parameters, their types, their defaults and a description of what they are.

I wish this was brought up before the existing implementation though. If we add a new way to inject parameters, it will confuse users if they asked for a list of available parameters, but only get those implemented one way.

Also, as @CharliePoole says, it would also require that we change our engine API.

For those reasons, my inclination would be to say no to this enhancement. Parameters in the GUI can be handled in the same way as in the console. Users can enter name/value pairs as strings. It isn't the best user experience, but it is no different than the command line.

**Comment by CharliePoole** [comment] 2016-10-03 18:25
@rprouse In fairness to @oznetmaster, he did bring it up but I thought the idea was a  bit over-engineered. What he describes involves fairly tight coupling between a gui and the framework, which is something he can do for his own CF gui, but which we can't do so easily in a gui that is two steps removed from the framework.

Nevertheless, I like the idea of creating visibility within the existing implementation. That seems possible with only a small amount of work and without coupling, so long as we avoid validating the types or values of the parameters and don't try to tie them to method parameters.

**Comment by oznetmaster** [comment] 2016-10-03 21:16
My implementation does all of those things, so I know it is possible in a tightly coupled runner like nunitlite, which is how my GUI works - it talks to nunitlite through a special console runner on CF.

I believe that my approach could be adapted to the two step removed current environment, since in the end, the parameters are still passed in the same way as is currently done.  Discovery is part of the test exploration, and the parameters and their validation rules are returned in the xml from that.  These added elements are of course ignored if not handled.  All the work is really done by the user interface, whether gui or command line.

The only thing done by the actual framework is parameter insertion.  Because of the static nature of nunit, parameter insertion is only allowed in certain Test procedures, ones where the parameter is not needed during discovery.  The parameter to procedure mapping is wrapped with the parameter itself  in the test context, so again, it can be ignored.

I do support parameter injection into the test method parameters as an option, so it is backward compatible.  In fact it is all backward compatible.  Parameters can still be specified on the command line that are neither defined nor validated.

I hope this clarifies rather then muddies things?

**Comment by CharliePoole** [comment] 2016-10-03 21:24
What does your XML look like WRT parameter discovery?

**Comment by oznetmaster** [comment] 2016-10-03 22:18
It is an xml element that can be a child to test-suite or test-case elements.

```
<test-parameter name="parameterName" type="System.String" inject="methodParameterName" minvalue="minValue" maxvalue="maxValue">
     <valid-value value="validValue1">
     <valid-value value="validValue2">
</test-parameter>
```
Everything except the name attribute is optional.

All the information is extracted from the test parameter attribute which can be applied to the assembly, test suite or test case.

Note that there can be conflicting test-parameter elements (differing types or validation rules) in the discovery xml, since currently, no validation of the set of attributes is done during discovery.

type defaults to string if not specified.

Only types that have a type converter from string to the type are allowed.

minvalue and maxvalue require that the type implement IComparable<type>, while valid-value requires that the type implement IEquatable<type>.

**Comment by oznetmaster** [comment] 2016-10-04 04:26
In my implementation, things are very flexible.

If the attribute specifies a method parameter insertion, and the parameter is not defined in the test method definition, there is no error, and the test parameter can still be used in the current fashion.  Even if the method does specify the given parameter, and the insertion occurs, the old methodology of getting the parameter from the test context is still valid, as well as using the method parameter (which is correctly type converted).

If no type is specified, then string is used. If a valid type with a type converter is specified, then the parameter is converted to that type for both access methodologies.

All validation occurs in the GUI.

The command line knows about none of the validation or discovery, and simply passes the parameter as a string.

The GUI does do validation, both for the type conversion and value validation.  This means that the specified type must exist on the machine running the GUI as well as the machine running the tests.  This may be an unreasonable limitation?  The value of the parameter is still passed to nunit as a string, and it is converted again in the test environment to the specified type.

**Comment by oznetmaster** [comment] 2016-10-05 01:22
Given that this approach is fully backward compatible, and would impose no required changes on any test or runners/guis, it would seem to be a good thing.  It would open up a lot of possibilities for future enhancements.

It has worked very well in my CF implementation.

**Comment by CharliePoole** [comment] 2016-10-05 03:49
@oznetmaster In case you don't know, @rprouse and I are pretty tied up trying to complete the various 3.5 releases right now, which is why this isn't getting our immediate attention. :smile:

**Comment by oznetmaster** [comment] 2016-10-13 02:56
I will try to be patient 😄

**Comment by oznetmaster** [comment] 2016-10-15 04:44
So, now that 3.5 is out, any thoughts on this?

**Comment by CharliePoole** [comment] 2016-10-15 05:10
We did the framework, engine and console. Now I'm working on the vs adapter as well as entertaining company. Maybe you and @rprouse can discuss and I'll chime in as I can.

**Comment by oznetmaster** [comment] 2016-10-15 05:31
Entertaining company always has priority 😄

I would be happy to have @rprouse input.

I could, if appropriate, backport my existing code to nunit/nunitlite in a PR.  Do not know if that is a worthwhile use of time if there is no consensus on the value of the approach.

**Comment by oznetmaster** [comment] 2016-10-19 22:24
Maybe @rprouse has no more thoughts on the issue ☹️ ?

**Comment by rprouse** [comment] 2016-10-20 03:22
I like the idea of making parameters visible, but I can't see how you can do that with the existing params implementation which are accessed in code, not via attributes. Does your approach only work with a new attribute and not the existing implementation? I am uncomfortable not supporting the existing parameters and adding support for a new style so soon.

Is my interpretation correct? Can you show me some code examples of the parameters in use and explain how it works with the parameters we just released?

**Comment by oznetmaster** [comment] 2016-10-20 04:07
The current implementation has to do with providing parameter and their values.  I am not changing that at all.  It still works the same way.  The parameters are added to the TestContext in the same way.

There are two parts to the process with the addition of discovery and validation.

The TestParameterAttribute defines a parameter that is used by the assembly/testsuite/test. It provides a name, and optionally a type, validation, and method parameter assignment if it is a Test.  This is the information used to generate the xml elements in the discovery results, as I described earlier.

The runner/gui is free to use or ignore this information in any way it wants.

When the TestContext is created, the parameters are added to the TestContext exactly as they are currently, and can be accessed by any test exactly as is currently the case (TestContext.Parameters).

However, in addition, if the TestParameterAttribute specified a Type for the parameter, and that Type has a TypeConverter from string, it is also added to the TestContext.Parameters<type> property (with TestContext.Parameters<string> mapping to the existing TestContext.Parameters).  If a type conversion error occurs, or if, after converting, any specified validation fails, then that assembly/testsuite/test is failed (as in any setup failure) with an appropriate error generated to the results. This allows strongly typed references to the parameters.

Finally, if, and only if, the TestParameterAttribute is being applied to a Test, and the Test method parameter name is specified, then the invocation of the Test method has the value passed to that parameter.  The test could still get the parameter value as is currently done (from TestContext.Parameters, or from the strongly typed parameter TestContext.Parameters<Type>, or by simple referencing the test method parameter (as it would with a TestCase, for instance).

So this is all totally backward compatible, and requires no change in any test unless it is desired.

I hope this makes sense?

**Comment by ChrisMaddock** [comment] 2016-10-20 11:39
I like the visibility/validation stuff. 😄 

Personally I'm less keen on retrieving the attribute by passing that in as a parameter, as I'm not sure I see sufficient benefit to add a second method to retrieve parameters, and add more to the API. I think this could have been a nice implementation if we'd started with it, but I'm less keen on adding it as 'alternative syntax'. Just my 2c!

**Comment by oznetmaster** [comment] 2016-10-20 14:52
I actually added two methods for retrieving parameters.  The TextContext.Parameters<Type> property, and the ability to optionally pass them in as method parameters.

I actually use that method in most of my tests that use test parameters, because it is the cleanest, but that is a personal preference.  That is why I supported all three.

**Comment by rprouse** [comment] 2016-10-20 19:43
Okay, I am pretty sure I understand now. Correct me if I am wrong, but the attributes are just markers that the code is expecting parameters, the attributes do not supply the parameters. The supply of the parameters is the same code we have now.

English is so imprecise, I prefer code 😆 

If my understanding is correct, let's see the code 👍

**Comment by oznetmaster** [comment] 2016-10-20 21:01
Yes, you are correct in your understanding.

I will backport my code then, and open a PR.

**Comment by rprouse** [comment] 2016-10-25 01:45
I am switching this from idea to enhancement.

**Comment by oznetmaster** [comment] 2016-10-25 01:55
I have opened a PR #1863 with my backported implementation.

**Comment by CharliePoole** [comment] 2016-10-25 03:04
@rprouse I continue to not like the idea but I'll bow to the majority.

**Comment by rprouse** [comment] 2016-10-29 15:09
@oznetmaster as I stated in the PR, this is much more than I expected, so I am going to close this as a won't fix.

**Comment by oznetmaster** [comment] 2016-10-29 20:09
You realize that rejecting "more then you expected", even though I clearly documented exactly what I was back-porting before I did the work, seems a bit a strange response.

If you only want the limited parameter discover/validation, then remove the method insertion code.  To throw the baby away with the bathwater seems like a real waste, even more so given that it seems very difficult to implement a full functioned GUI without at least that limited capability.

**Comment by oznetmaster** [comment] 2016-11-03 23:44
In reviewing @CharliePoole comments, I have removed (made obsolete) TestMethodParameterName from the TestParameterAttribute, so it no longer plays any role in providing data to the test method.

I have added a TestParameterValueAttribute, which is only applicable to the test method parameter, and works similarly to the RandomAttribute in providing data to that parameter, in this case one or more test parameter values (the name(s) of the test parameters are provided in the attribute).

The result is that it would be easy to provide only the TestParameterAttribute for discovery and validation, and not provide the TestParamaterValueAttribute, if that was what was desired.

I can back-port the changes to the PR, if it is of any interest?

**Comment by oznetmaster** [comment] 2016-11-04 00:18
Also note that the TestParameterValuesAttribute is unrelated to the TestParameterAttribute.

It might be useful to consider each of them independently.

**Comment by CharliePoole** [comment] 2016-11-08 23:40
@oznetmaster You re-opened this without explanation. If it was intentional, would you add one?

**Comment by oznetmaster** [comment] 2016-11-09 00:01
I reopened it because I addressed the issues raised by both you and @rprouse, and it seemed like that justified a reconsideration of each of the two pieces.

**Comment by rprouse** [comment] 2016-12-01 20:42
I am moving this into the Discussion column. I still vote to close, but would like the @nunit/contributors opinions.

**Comment by CharliePoole** [comment] 2016-12-01 20:54
I don't see the need. Runtime parameters are entered on the command-line or in a text file. They are strings by their very nature. Most test frameworks that allow such parameters take them as strings and convert them as needed. We can do the same. We have other things to spend time on.

**Comment by oznetmaster** [comment] 2016-12-01 21:17
Then how are you going to handle them in the GUI?  No command line there.  How are you going to provide a user friendly GUI for parameters without at least having discovery?

**Comment by CharliePoole** [comment] 2016-12-01 21:24
I would imagine a text box could do the job. :-)

**Comment by CharliePoole** [comment] 2016-12-01 21:26
A little less facetiously: I am not a believer in pushing features from the bottom up. I think any runner, including our gui, should pull features out of the backend software. If the users of the gui raise a clamor for something other than simple text input, then the gui project can request such a facility from the engine and framework. But creating features speculatively benefits nobody.

**Comment by oznetmaster** [comment] 2016-12-01 21:51
All I can say is that my users love the feature and the GUI support I have provided for it.

I have had many comments about how it has made it significantly easier to write tests that can exercise parts of their code under differing conditions without having to touch their test assemblies.

The fact that the GUI not only lists the parameters, but also a description of what they are, and also validates the values they enter, seeming has increased their productivity significantly.  They do not have to refer back to the source code for the test to "interface" with it, and to appropriately configure the currently desired behavior.

Sometimes, a feature is not fully appreciated until it is available, because users do no realize what functionality could be provided, but currently is not being.

**Comment by rprouse** [comment] 2016-12-01 21:59
I can see this being useful for a GUI, but we don't currently have a shipping GUI and the majority of users these days use the various Visual Studio runners or the command line where this enhancement isn't very useful as there is no way to surface it.

A simple GUI (once we get to it) could also just provide an experience like setting environment variables in Windows, just name/value pairs.

**Comment by CharliePoole** [comment] 2016-12-01 22:04
@rprouse I'm not against having this feature eventually, if we need it. But if we try to do it now, predicting the future need, there's a strong probability that we will end up making changes to it. That's what usually happens when features are designed into libraries without waiting for a demand.

**Comment by oznetmaster** [comment] 2016-12-01 22:18
I guess that since I have had a GUI for the Crestron CF version of NUnit 3.0 since day one, and 99% of my users utilize that GUI to interact with NUnit, I already have a good feel for what makes the GUI more productive, at least to my users.

**Comment by oznetmaster** [comment] 2016-12-01 22:21
Originally, all I had was a box for the parameters, where the user could enter name value pairs.

I was constantly asked "How do we know what we can put in there?"  When i indicated that they should read the test source code to find out, the response was always very negative.

Now, there is no need to refer to the test source code, since the parameters are listed, described, and validated, in the GUI

**Comment by jnm2** [comment] 2016-12-01 22:58
So all @oznetmaster is really after is an API to list, describe and validate test parameters?

I'm a little fuzzy on what the use case is for the GUI. I'm picturing the GUI users entering parameters into a property-grid-like configuration window based on the selected tests before hitting a Test button? Why are the test parameter values chosen by users rather than encoded into parameterized tests?

**Comment by oznetmaster** [comment] 2016-12-01 23:29
Try using parameterized tests to run 1000 tests with trying different timing tolerence, just as an example.

**Comment by oznetmaster** [comment] 2016-12-01 23:30
@jnm2 you should read the issue (I do not know the number) that discussed the introduction of runtime parameters int he first place.

**Comment by jnm2** [comment] 2016-12-02 02:32
@oznetmaster but why not either randomize it or just run all essential impacted tests? Is it just for a short period of development? Long term I'd assume you'd want automated tests, right?

**Comment by oznetmaster** [comment] 2016-12-02 02:47
Read #720, which was not started by me.

**Comment by jnm2** [comment] 2016-12-02 03:36
@oznetmaster I read it, but it didn't answer my question. Why is this useful? Why wouldn't you plan to (long term) always run all tests that you know are important? I can't imagine releasing software without running every test that I know the code has needed.

**Comment by jnm2** [comment] 2017-06-27 19:37
There hasn't been any response here for a while. Okay to close for now?

**Comment by oznetmaster** [comment] 2017-06-27 21:40
Not ok by me.  I still feel it is an important issue.

**Comment by oznetmaster** [comment] 2017-06-27 21:42
As I indicated earlier, my CF build has had this feature for over three years now, and it is widely used by those who use this version.

My GUI also uses it to present the user with a list of parameters that are used by the tests, and the valid range of values for them.  The GUI also validates the provided values BEFORE any tests are run.

**Comment by jnm2** [comment] 2017-06-27 21:50
@oznetmaster Cool. Can you help me understand some more use cases? The only use case that was presented above seems like poor practice to me, and my [question about it](https://github.com/nunit/nunit/issues/1771#issuecomment-264365468) still hasn't been answered.

**Comment by jnm2** [comment] 2017-06-27 21:52
In other words if I'm writing the tests, I'm not expecting to put the burden of finding the right parameters on the person/machine that runs the test. I'm expecting to have to know the corner cases in the implementation and test *all* the possibilities that could ever be important.

**Comment by CharliePoole** [comment] 2017-06-27 23:13
I think that the use of runtime parameters in @oznetmaster 's framework and gui is quite different from what it was designed for in NUnit. We don't have the same use case because they are intended to be a sort of global parameter, which may be used by many tests. People use them to specify things like whether to use the test database or the production database. When used in that way, I don't think this is a necessary feature, which is why we closed the issue as won't fix last year.

If we wanted to encourage use of many user-defined parameters, tied directly to the arguments of parameterized fixtures and tests, then we would probably need this feature as well. But this is not a usage we are making any effort to support, at least right now. If that changes in the future, we can always address it.

**Comment by rprouse** [comment] 2017-06-29 00:55
I am still against this idea as overkill and would vote to close. Sorry @oznetmaster but I don't see it as high enough value for the majority of users.

**Comment by rprouse** [comment] 2020-05-18 18:46
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 18:46 UTC
Labels: is:idea
