### ISSUE TITLE
Is.Zero

### ISSUE THREAD

**Issue by NUnitTester** [nunit/nunit#1778] opened 2016-08-31 17:03 UTC
Is.Zero is not working as expected:

```
IntPtr ptr = IntPtr.Zero;
Assert.That(ptr, Is.Zero);
```
Expected: 0
But was:  0

**Comment by jplebre** [comment] 2016-09-23 17:30
I never used IntPtr before, but looking at the docs I see there's an explicit cast to convert it into int64.

The IsZero() has no overload for IntPtr and tbh without my machine in front of me can't really play around with the equalities.

The MSDN docs do say it should be int32 or int64 depending on the system... interesting

**Comment by jplebre** [comment] 2016-09-25 19:07
I can confirm the problem. 
However, Both of the following tests pass:
```
            Assert.That(ptr.ToInt32, Is.Zero);
            Assert.That(ptr.ToInt32, Is.Zero);
            Assert.That((int)ptr, Is.Zero);
```

I've never used IntPtr in any of my software so I'm not sure what the good practices around this are. It seems to me that IntPtr is not intended to be compared against string without casting or using the conversion methods.

We could add an overload to allow IntPtr. What say the nunit team? @nunit/contributors

**Comment by CharliePoole** [comment] 2016-09-25 19:18
The only rational that I can see for doing it is that there is an IntPtr.Zero member, which could lead one (did lead someone) to thinking that Assert.IsZero should work. I'm not sure that's enough justification.

**Comment by immeraufdemhund** [comment] 2016-09-25 20:16
I've used IntPtr.Zero many times. Normally it's to subustitue for native code that calls for `NULL` which is defined as the value 0. I would think that maybe making `Assert.That(IntPtr.Zero, Is.Null);` a valid scenario.

**Comment by jplebre** [comment] 2016-09-25 20:40
If I do `Assert.That(IntPtr.Zero, Is.Null);` it fails:
```
Expected: null
But was: 0
```

**Comment by CharliePoole** [comment] 2016-09-25 23:04
Since the result from NUnit's Assert matches what the language returns, I'd say this is not a bug. @rprouse Would you agree?

**Comment by rprouse** [comment] 2016-09-26 00:25
I can understand wanting `Assert.That(IntPtr.Zero, Is.Zero)` or  `Assert.That(IntPtr.Zero, Is.Null)` to pass, but like @CharliePoole says, we are not matching what the language returns. When we evaluate requests like this, we usually try to stay within the bounds of the language and not introduce implicit casts. So, 

```C#
IntPtr.Zero == 0 // not valid
Assert.That(IntPtr.Zero, Is.Zero) // Fails because the class IntPtr is not a zero valued int, it is a struct

IntPtr.Zero == null // false
Assert.That(IntPtr.Zero, Is.Null) // Fails
```

The problem is, we have added convenient overrides  for stuff like this in the past, so users come to expect it to work for everything.  Our code also becomes very complicated with all of the implicit casts. 

I am inclined to close this as won't fix. The following works,

```C#
IntPtr.Zero.ToInt32() == 0 // true
Assert.That(IntPtr.Zero.ToInt32(), Is.Zero) // Passes
```

**Comment by CharliePoole** [comment] 2016-09-26 01:16
I agree. Done.

**Closed by CharliePoole** 2016-09-26 01:16 UTC
Labels: closed:wontfix

**Comment by jnm2** [comment] 2016-09-26 12:31
I don't think the fact that `IntPtr` is a struct is relevant. `decimal` is also a struct with number semantics. 
`IntPtr` is what you use instead of `int` and `long` when you need the size to be platform-specific.

**Comment by rprouse** [comment] 2016-09-26 14:09
@jnm2 true, but I mention it is a struct because it doesn't have implicit conversions (AFAIK) to int, long or null and I would prefer if NUnit not add additional implicit conversions internally.

**Comment by immeraufdemhund** [comment] 2016-09-26 14:19
@jnm2 not to mention that it's a pointer, not a value. The value `IntPtr.Zero` does happen to be 0 and in the C++ world is the same as null... but to put what @rprouse  said a tad differently is that the pointer points to a location in memory and can point to numbers, as well as by reference objects, and arrays (including strings and wide strings). The idea of checking for `IntPtr.Zero` instead of the value `0` sounds better to me.

One thought that crosses my mind though is making a `Is.ZeroPointer` or `Is.NullPointer` or similar named constraint. And that could check for `IntPtr.Zero` as well as `UIntPtr.Zero`

**Comment by rprouse** [comment] 2016-09-26 14:37
I would also extend that a bit, older C++ uses a define for `NULL` that is an int 0, but newer C++ uses `nullptr` which is not of type `int`, but a special type `std::nullptr_t` and if I remember correctly, there is not implicit cast for that either.

@immeraufdemhund if we were to implement anything, your semantics of `Is.ZeroPointer` or `Is.NullPointer` would be more palatable, but we don't want to be adding constraints for every possible type or variation. We have a bunch for strings and collections because they are so widely used, but we need to stop somewhere otherwise we would be writing `Is.EmptyGuid`, etc...

Unfortunately, there are no extension properties in C#, but you could probably write an extension method for `Is.ZeroPointer()` if you used it enough in your own tests. Personally, I think it would be used so infrequently that I am happy with the extra typing of `Assert.That(IntPtr.Zero.ToInt32(), Is.Zero)`

**Comment by jnm2** [comment] 2016-09-26 15:14
That makes sense. `IntPtr` in C# doesn't actually have number semantics, it has pointer/native handle semantics.

Along those lines though it feels less clean to convert it and compare using number semantics. I'd prefer `Assert.That(value, Is.EqualTo(IntPtr.Zero))` over anything else.

**Comment by NUnitTester** [comment] 2016-09-27 12:18
@rprouse: Sorry, but this is not a solution!

`IntPtr.Zero.ToInt32() == 0 // true
Assert.That(IntPtr.Zero.ToInt32(), Is.Zero) // Passes`
It will be wrong on a 64 bit system, because the Pointer has the size of a register all the time.

NULL is defined as followed ((void*)0) in compiler I used last years. In C++11 nullptr ist the right on to use.

I dont't like it really, but if Zero is interpreted as an int, what about this solution?
`Assert.That(IntPtr.Zero, Is.ZeroPtr)`

IntPtr and UIntPtr we use to pass Pointer from C++ to C# which could be 32 bit or 64 bit depends on the running system and Asserts on that a currently not very nice. Because C# has decided to call it Zero, I expect that Is.Zero will work. What the problem about some overloads of this Constraint?

**Comment by jnm2** [comment] 2016-09-27 12:23
@NUnitTester What do you need that `Assert.That(value, Is.EqualTo(IntPtr.Zero))` doesn't give you?

**Comment by NUnitTester** [comment] 2016-09-27 12:25
I think most people talking about having no problems with IntPtr didn't write there software in native language like C++ and D. Only surface and server interfaces are written in managed, so NUnit tests use IntPtr or UIntPtr. But one important thing is that the size of the pointer is unknown, so a cast To Int32 is definitively wrong.

**Comment by NUnitTester** [comment] 2016-09-27 12:29
It's not really quite nice, you don't write 
`Assert.That(value, Is.EqualTo(0))
Assert.That(value, Is.EqualTo(string.Empty))`

Instead you use 
`Assert.That(value, Is.Zero)
Assert.That(value, Is.Empty)`
won't you?
It is very good readable. 
And back to pointer. In almost all times only the difference to IntPtr.Zero is important, not the exact value, which is not useful for the surface/nunit.

**Comment by NUnitTester** [comment] 2016-09-27 12:32
I would prefer to have an overload for IntPtr and UIntPtr. I don't think that will be more than 10 lines of code, are it?
The time we talking about is more than fixing the problem.
@CharliePoole : Can you please solve the problem? If you don't like to have it as an bug, call it feature request.

**Comment by NUnitTester** [comment] 2016-09-27 12:37
Sorry, I don't understand this:
> Since the result from NUnit's Assert matches what the language returns, I'd say this is not a bug. @rprouse Would you agree?

What does it mean, that the Assert matches what the language returns? NUnit give the message:
**Expected: 0
But was: 0**

**Comment by CharliePoole** [comment] 2016-09-27 12:43
Actually, the error message is a bit of a bug. Apparently, IntPtr.ToString simply displays the int value.

**Comment by jplebre** [comment] 2016-09-27 12:46
I'm not sure I understand. From what you just said:

> IntPtr.Zero.ToInt32() == 0 // true Assert.That(IntPtr.Zero.ToInt32(), Is.Zero) // Passes
>It will be wrong on a 64 bit system, because the Pointer has the size of a register all the time.

in both examples, you are using the `.ToInt32()` method

So we know all of these pass:
```
            IntPtr ptr = IntPtr.Zero;

            Assert.That(ptr.ToInt32, Is.Zero);
            Assert.That(ptr.ToInt64, Is.Zero);
            Assert.That((int)ptr, Is.Zero);
            Assert.That(value, Is.EqualTo(IntPtr.Zero))
```

What would the overload add that you don't have above?

Like I said on my previous post looking at the documentation it gives the feel you are expected to either cast or use `.ToInt` before using this value as an integer.

As per my first post, never used IntPtr in .net so I'm not aware of the best practices, and am trying to understand it better

**Comment by jplebre** [comment] 2016-09-27 12:50
@CharliePoole hmmm 
Looking at the posts above by @rprouse seems it would make more sense that the .ToString() returned null not 0. What is the likelyhood the .net team would accept our PR?

Adding an overload for IntPtr to Is.Zero could cover this issue but seems like we are driving a pneumatic drill on a M3 flathead screw

**Comment by NUnitTester** [comment] 2016-09-27 12:55
M3 flathead screw ??? What this?

Ok, try an UIntPtr in 64 Bit with a value all bits are set: 0xffffffffffffffff.
(Or IntPtr with 0x7fffffffffffffff).
What does the function ToInt32 do? I think, an exception is thrown.
If not, than think about a pointer to 0xffffffff00000000.
ToInt32 will give 0 but the Pointer is not UIntPtr.Zero.
That's what I'm talking about.

**Comment by rprouse** [comment] 2016-09-27 13:15
Wow, I am surprised so many people are interested in this issue. I agree that the message is misleading because `IntPtr.Zero.ToString()` returns 0. I also agree that it would be an easy fix, but my concern is that it is a slippery slope. If we add `Is.ZeroPtr`, shouldn't we do the same for every struct in the .NET framework that has a Zero, Empty, MinDate, MaxDate, etc? My thinking is that people will write unit tests for this so infrequently that I would rather they write `Assert.That(ptr, Is.EqualTo(IntPtr.Zero))` rather than slow down the framework with additional casts and checks.

**Comment by CharliePoole** [comment] 2016-09-27 13:17
Well since Is.Zero is a property, you can't actually overload it.

Any variable behavior based on the type of the actual value requires us to
create a ZeroConstraint, similar to EmptyConstraint, which would postpone
the choice of the real constraint until the Type of the actual value us
known.

The alternative would be to make a much deeper change in how NUnit
determines equality. I wouldn't want us to do that.

The problem is that we agreed, very recently, to accept Is.Zero as a bit of
syntactic sugar, with no extra behavior behind it. It's a great
illustration of the unintended consequences such "simple" changes can have!

**Comment by jnm2** [comment] 2016-09-27 13:23
I hope no one seriously thinks `.ToInt32()` should be used unless the semantic you want is the discarding of the most significant half. And `IntPtr.Zero.ToString()` should most definitely be `0`. But that's a side conversation.

@NUnitTester I wouldn't want `Is.Zero` to run slower and I wouldn't want `Is.ZeroPtr` cluttering the API unless it was a truly central use case. It is a fact that what you are doing is unusual in C#. When you're doing something unusual like that, that's when you expect to use `Is.EqualTo`. It's not much to type and you can even write your own `IsIntPtr.Zero` constraint if you so desire.

**Comment by jnm2** [comment] 2016-09-27 13:28
@rprouse @CharliePoole Is there another discussion on `Is.Zero`? I don't think this should be done necessarily, but I'm curious what the ramifications would be of implementing `Is.Zero` as `value?.ToString() == "0"`. Perf would be decent. Probably a internationalization nightmare? False negatives and positives?

**Comment by rprouse** [comment] 2016-09-27 14:08
@jnm2 there isn't an open discussion on `Is.Zero`. I would also be worried about the ramifications of comparing the ToString value, it just feels wrong 😉

**Comment by NUnitTester** [comment] 2016-09-27 14:13
@jnm2: I think if the compare with `value?ToString` is removed, the code is faster even if a `Is.Zero` is added for IntPtr und UIntPtr.

**Comment by CharliePoole** [comment] 2016-09-27 14:28
Guys... all this talk of how to implement Is.Zero misses a key point: Is.Zero does no comparison at all. It's just a static property that returns a new Constraint. The actual value is not available when it is invoked. Currently, I believe it returns `new EqualConstraint(0)`. Here are our choices...

1. Remove Is.Zero from the framework entirely. However, IIRC it's already released in 3.4, so I wouldn't do that - if it's not yet released, that's a real option.

2. Just live with it and leave this issue closed as won't fix.

3. Create a ZeroConstraint that works in a way similar to EmptyConstraint - that is, generates a different constraint internally depending on the actual value that is passed to it's ApplyTo method.

4. Completely change the way NUnit does equality so that integer 0 is considered equal to IntPtr.Zero. This would make Is.Zero work and also Is.EqualTo(0) would work on IntPtrs. It might - likely would - have side effects.

5. Create something like Is.IntPtrZero. IMO this is the worst possible choice, even though simple, because it clutters the API. That's much worse than complicating the code internally.

**Comment by CharliePoole** [comment] 2016-09-27 14:31
@NUnitTester Since we only invented Is.Zero "yesterday", people have actually been writing Is.EqualTo(0) for many years without a complaint. Similarly, before we invented Is.Empty, they used Is.EqualTo(""). A slightly longer syntax is not an absolute deal-breaker for most programmers, particularly if it reads clearly.

**Comment by CharliePoole** [comment] 2016-09-27 14:33
@rprouse On the separate problem of the error message, I think we should create an issue to add special handling in the display of IntPtrs as expected or actual values, just as we do for many other types. What do you think?

**Comment by jnm2** [comment] 2016-09-27 14:34
I strongly agree; I think `Assert.That(value, Is.EqualTo(IntPtr.Zero))` is the clearest and most semantically correct thing to do. Also, @NUnitTester can easily write his own `IsIntPtr.Zero` which is a fun exercise left to the reader because I have other things to do at the moment. ;-)

**Comment by NUnitTester** [comment] 2016-09-27 14:35
Nice options, I would prefer option 3 most.

**Comment by CharliePoole** [comment] 2016-09-27 14:40
@jnm2 Comparing the string value would break Is.Zero as applied to decimals, doubles, etc.

@NUnitTester The five options are in my order of preference, but number 1 is probably a fantasy and 4 and 5 are only listed to show why they are bad ideas in my view. Practically, it's between 2 and 3.

@rprouse We did already release this, right? I guess we can't unrelease. 😦

**Comment by jplebre** [comment] 2016-09-27 15:36
I have to agree with @jnm2 for the leave as is and use 'Is.EqualTo(IntPtr.Zero)' as this is an edge case. Reading the docs gives me the distinct idea a conversion is necessary if it needs to be handled as an int too.

Also agree that if adding Is.Zero started this discussion, adding further properties like the IntPtr would probably cause a barrage of requests for every similar property.

Id leave it w current status

**Comment by rprouse** [comment] 2016-09-27 16:16
1. `Is.Zero` has been released, so we cannot remove it.
2. I am fine with leaving it as is 😄 
3. I would be reluctant to add a `ZeroConstraint` as I think it could lead us down a rabbit-hole of supporting different concepts of Zero
4. Rather than add a special case for the message for an IntPtr.Zero, I think we should have a more generic fix for where the message looks the same. We have seen similar issues in the past. One possibility is that if we are reporting inequality and the string representations are the same we include the type in the message? Or always include the type?

**Comment by ChrisMaddock** [comment] 2016-09-27 16:16
I think creating a ZeroConstraint could potentially open the floodgates a little as to what is 'semantically zero'. `TimeSpan.Zero` springs to mind as being a similar situation, and I guess there's many more.

Seems to me like an ideal candidate for a user-custom-constraint. Perhaps there's a documentation issue however that we should clarify `Is.Zero` checks solely for integer zero?

**Comment by ChrisMaddock** [comment] 2016-09-27 16:20
Apologies mine and @rprouse's posts crossed - didn't intend to just reinforce the same points! 

> One possibility is that if we are reporting inequality and the string representations are the same we include the type in the message? Or always include the type?

This seems like a good idea - although I'd vote only when string representations match. It's a problem in 0.1% of comparisons, I don't see that justifying making everything more long-winded.

**Comment by jplebre** [comment] 2016-09-27 19:03
I like the adding the type to the message best.
Expected: 0 (Int32)
But was: 0 (string)

Liking it already

**Comment by CharliePoole** [comment] 2016-09-27 23:10
Created issue #1808 for the error message.
