### ISSUE TITLE
TestContext.Out null when used in task with .NET Core

### ISSUE THREAD

**Issue by jhickson** [nunit/nunit#1952] opened 2017-01-04 16:25 UTC
Hi,

I have a test project targeting both .NET Framework (4.6.2) and .NET Core (1.1) and am finding that for the latter `TextContext.Out` is null when used from a `Task`. The code below reproduces the issue:

```C#
[Test]
public void SomeTest()
{
    if (TestContext.Out == null)
    {
        Console.WriteLine("Out null");
    }
    else
    {
        Console.WriteLine("All ok");
    }

    Task.Factory.StartNew(() =>
                          {
                              if (TestContext.Out == null)
                              {
                                  Console.WriteLine("Out null");
                              }
                              else
                              {
                                  Console.WriteLine("All ok");
                              }
                           }).Wait();
}
```

For .NET Core 1.1 I get
```
All ok
Out null
```
printed at the console.

I'm using NUnitLite 3.5.0 with dotnet-test-nunit 3.4.0-beta-3. The failure occurs when using `dotnet test` from the command-line as well as from Visual Studio.

**Comment by CharliePoole** [comment] 2017-01-09 19:20
The problem is a bit more general than that. The same thing will happen if you create your own thread in any way at all. To avoid crashes, a new TestExecutionContext and TestContext are created as soon as you reference them. However, they are not initialized because NUnit has no opportunity to intervene until it's too late - after the coded is already run.

It has been a fundamental problem with NUnit for some time but shows up more frequently as more use is made of asychronicity. We need to look into this.

**Comment by CharliePoole** [comment] 2017-02-27 20:08
@jhickson I think this is now fixed in master. Can you try one of our myget builds >= 3.7.0-dev-03707 ?

**Comment by jhickson** [comment] 2017-02-28 10:07
@CharliePoole That's looking good now. Many thanks.

**Closed** 2017-02-28 11:32 UTC
Labels: closed:done, is:bug, pri:high
