### ISSUE TITLE
No Tests found: Using parametrized Fixture and TestCaseSource

### ISSUE THREAD

**Issue by stffabi** [nunit/nunit#320] opened 2014-10-30 15:39 UTC
Using: NUnit Console Runner 3.0.5378

The following construct seems to make problems. The nunit runner doesn't find any tests in an assembly if the following TestFixture is implemented in the test assembly.

```
<TestFixture("MyParam")>
<TestFixture("MyParam1")>
Public Class MyTest

    Public Sub New(aParam As String)
    End Sub

    Public ReadOnly Property MySource() As Object()
        Get
            Return New Object() {"Test1", "Test2"}
        End Get
    End Property

    <TestCaseSource("MySource")> _
    Public Sub MyTest(aSource As String)
        Assert.AreEqual("", aSource)
    End Sub

End Class
```

**Comment by constructor-igor** [comment] 2015-04-27 12:57
nunit v2:
```c#
    [TestFixture("MyParam")]
    [TestFixture("MyParam1")]
    public class NUnitIssue320
    {
        public NUnitIssue320(string testFixtureName)
        {            
        }
        public object MySource = new[] {"Test1", "Test2"};

        [TestCaseSource("MySource")]
        public void MyTest(string source)
        {
            Assert.That(source, Is.EqualTo("Test2"));
        }

        [Test]
        public void Test()
        {
            Assert.Pass();
        }
    }
```
Resharper v8 shows:
![image](https://cloud.githubusercontent.com/assets/1849690/7347910/bacb9930-ecf5-11e4-83f2-9dd99a3fb2b0.png)

nunit UI shows:
![image](https://cloud.githubusercontent.com/assets/1849690/7347966/249c7956-ecf6-11e4-9780-f469cb11cc1f.png)

nunit command line:
```
          <test-suite type="ParameterizedFixture" name="NUnitIssue320" executed="True" result="Failure" success="False" time="0.075" asserts="0">
            <results>
              <test-suite type="TestFixture" name="NUnitIssue320(&quot;MyParam&quot;)" executed="True" result="Failure" success="False" time="0.068" asserts="0">
                <results>
                  <test-case name="NUnit_v2_samples.NUnitIssue320(&quot;MyParam&quot;).Test" executed="True" result="Success" success="True" time="0.027" asserts="0">
                    <reason>
                      <message><![CDATA[]]></message>
                    </reason>
                  </test-case>
                  <test-suite type="ParameterizedTest" name="MyTest" executed="True" result="Failure" success="False" time="0.026" asserts="0">
                    <results>
                      <test-case name="NUnit_v2_samples.NUnitIssue320(&quot;MyParam&quot;).MyTest(&quot;Test1&quot;)" executed="True" result="Failure" success="False" time="0.020" asserts="1">
                        <failure>
                          <message><![CDATA[  String lengths are both 5. Strings differ at index 4.
  Expected: "Test2"
  But was:  "Test1"
  ---------------^
]]></message>
                          <stack-trace><![CDATA[at NUnit_v2_samples.NUnitIssue320.MyTest(String source) in d:\My\MyProjects\NUnit.That.Resharper.Plugin\trunk\NUnit_v2_samples\NUnitIssue320.cs:line 18
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="NUnit_v2_samples.NUnitIssue320(&quot;MyParam&quot;).MyTest(&quot;Test2&quot;)" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="TestFixture" name="NUnitIssue320(&quot;MyParam1&quot;)" executed="True" result="Failure" success="False" time="0.003" asserts="0">
                <results>
                  <test-case name="NUnit_v2_samples.NUnitIssue320(&quot;MyParam1&quot;).Test" executed="True" result="Success" success="True" time="0.000" asserts="0">
                    <reason>
                      <message><![CDATA[]]></message>
                    </reason>
                  </test-case>
                  <test-suite type="ParameterizedTest" name="MyTest" executed="True" result="Failure" success="False" time="0.001" asserts="0">
                    <results>
                      <test-case name="NUnit_v2_samples.NUnitIssue320(&quot;MyParam1&quot;).MyTest(&quot;Test1&quot;)" executed="True" result="Failure" success="False" time="0.000" asserts="1">
                        <failure>
                          <message><![CDATA[  String lengths are both 5. Strings differ at index 4.
  Expected: "Test2"
  But was:  "Test1"
  ---------------^
]]></message>
                          <stack-trace><![CDATA[at NUnit_v2_samples.NUnitIssue320.MyTest(String source) in d:\My\MyProjects\NUnit.That.Resharper.Plugin\trunk\NUnit_v2_samples\NUnitIssue320.cs:line 18
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="NUnit_v2_samples.NUnitIssue320(&quot;MyParam1&quot;).MyTest(&quot;Test2&quot;)" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
```

**Comment by constructor-igor** [comment] 2015-04-27 13:05
NUnit v3. console creates report file without any information about the test class.

**Comment by constructor-igor** [comment] 2015-04-27 13:13
@CharliePoole how can I help in the issue (status:confirm)?

**Comment by rprouse** [comment] 2015-04-27 14:36
@constructor-igor, when you checked this in NUnit v3, did you do so with the current beta release, or a recent build? @CharliePoole mentioned some recent fixes that aren't released yet, so they may change the behavior.

**Comment by CharliePoole** [comment] 2015-04-27 15:53
Yes, that's a good question because there were two errors here: 
1. The fundamental error: that the class could not be constructed
2. A secondary error: that the failure was not reported, leaving the user in ignorance

When we have a situation like that, we like to fix the secondary reporting error first, using the primary error as a sort of acceptance test. I thought I had done that, so let's verify it with the current code. The test should be reported as not-runnable, and the run should continue with any other tests in the assembly.

For the primary error, I'm not sure we should fix it. We are deprecating this form of TestCaseSource in NUnit 3.0. We could simply document that a default constructor is required. I guess it will depend on how much effort would be required.

Anyway @constructor-igor , let us know what build you are testing with and we'll go on from there.

**Comment by constructor-igor** [comment] 2015-04-28 07:41
I checked last release (nunit.framework.dll - 3.0.5562.31843).

**Comment by constructor-igor** [comment] 2015-05-04 10:07
Current nunit shows next errors (see below).
what can I do to remove "status:confirm"?

2bb09638af868070d6e5f0c27e0646a33faba9c3

```c#
    [TestFixture("MyParam")]
    [TestFixture("MyParam1")]
    public class NUnitIssue320
    {
        public NUnitIssue320(string testFixtureName)
        {            
        }
        public object MySource = new[] {"Test1", "Test2"};

        [TestCaseSource("MySource")]
        public void MyTest(string source)
        {
            Assert.That(source, Is.EqualTo("Test2"));
        }

        [Test]
        public void Test()
        {
            Assert.Pass();
        }
    }
```

```
      <test-suite type="TestFixture" id="0-1009" name="NUnitIssue320" fullname="NUnit_v3_samples.NUnitIssue320" classname="NUnit_v3_samples.NUnitIssue320" runstate="NotRunnable" testcasecount="0" result="Failed" label="Invalid" site="SetUp" start-time="2015-05-04 10:02:23Z" end-time="2015-05-04 10:02:23Z" duration="0.000000" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <properties>
          <property name="_SKIPREASON" value="An exception was thrown while loading the test.&#xD;&#xA;NUnit.Framework.Internal.InvalidTestFixtureException: NUnit_v3_samples.NUnitIssue320 does not have a default constructor&#xD;&#xA;   at NUnit.Framework.Internal.Reflect.Construct(Type type) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 147&#xD;&#xA;   at NUnit.Framework.Internal.Reflect.Construct(Type type, Object[] arguments) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 158&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(MethodInfo method) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 207&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(MethodInfo method) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 102&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.BuildFrom(MethodInfo method, Test suite) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 239&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(MethodInfo method, Test parentSuite) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultTestCaseBuilder.cs:line 141&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildTestCase(MethodInfo method, TestSuite suite) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 209&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCases(Type fixtureType) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 184&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(Type type, TestFixtureAttribute attr) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 156&#xD;&#xA;   at NUnit.Framework.TestFixtureAttribute.BuildFrom(Type type) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Attributes\TestFixtureAttribute.cs:line 164&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildMultipleFixtures(Type type, IFixtureBuilder[] attrs) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultSuiteBuilder.cs:line 114&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(Type type) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultSuiteBuilder.cs:line 89" />
        </properties>
        <failure>
          <message>An exception was thrown while loading the test.
NUnit.Framework.Internal.InvalidTestFixtureException: NUnit_v3_samples.NUnitIssue320 does not have a default constructor
   at NUnit.Framework.Internal.Reflect.Construct(Type type) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 147
   at NUnit.Framework.Internal.Reflect.Construct(Type type, Object[] arguments) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs:line 158
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(MethodInfo method) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 207
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(MethodInfo method) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 102
   at NUnit.Framework.TestCaseSourceAttribute.BuildFrom(MethodInfo method, Test suite) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 239
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(MethodInfo method, Test parentSuite) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultTestCaseBuilder.cs:line 141
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildTestCase(MethodInfo method, TestSuite suite) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 209
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCases(Type fixtureType) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 184
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(Type type, TestFixtureAttribute attr) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\NUnitTestFixtureBuilder.cs:line 156
   at NUnit.Framework.TestFixtureAttribute.BuildFrom(Type type) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Attributes\TestFixtureAttribute.cs:line 164
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildMultipleFixtures(Type type, IFixtureBuilder[] attrs) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultSuiteBuilder.cs:line 114
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(Type type) in d:\My\MyProjects\NUnit.v3\constructor.NUnit\nunit\src\NUnitFramework\framework\Internal\Builders\DefaultSuiteBuilder.cs:line 89</message>
        </failure>
      </test-suite>
```

**Comment by CharliePoole** [comment] 2015-05-04 16:44
Is the console runner listing the error? In fact the error has always been shown in the XML, but the console was silent about it. That's the secondary error I was referring to.

**Comment by CharliePoole** [comment] 2015-05-04 17:04
The error is definitely confirmed. The question is now whether we are going to fix it.

We have deprecated the use of a TestCaseSource within the same class. That being the case, we may want to limit how much effort we put into this bug.

We should definitely add information about the problem to the docs and we should fix the secondary error, if it is not already fixed. I believe the current code should now be giving a generic message. Ideally, we should mark the test class as non-runnable with a very specific message like... "Classes containing the target of a test case source attribute must have a default constructor"

Actually trying to fix the primary error be fairly difficult and the effort would go toward a test pattern we are advising people not to use. In fact, this problem is one of the reasons we deprecated the pattern in the first place!

To "fix" this would mean creating separate instances of each parameterized fixture to generate the arguments used by that fixture. Currently, we cache each instance we create at load time so that only one instance is created, so that's a fairly invasive change to how test generation works.

Frankly, I would rather see us spend the time on creating dynamic tests at run time, which is in our road map but not yet being worked on.

@nunit/core-team I feel this is a rather important decision. Comments?

**Comment by CharliePoole** [comment] 2015-05-04 17:06
@constructor-igor If you'd like to go ahead and fix the secondary error while we discuss what to do about the primary error, I can assign this to you.

**Comment by constructor-igor** [comment] 2015-05-14 11:09
As I understand NUnit console (v3 beta 2) shows same error message as xml report (see details below).
Seems, secondary issue was fixed.

NUnit v3 Beta 2 console:
![image](https://cloud.githubusercontent.com/assets/1849690/7630782/74f29d78-fa42-11e4-9f98-e9b32e4be4c5.png)

```
      <test-suite type="TestFixture" id="0-1009" name="NUnitIssue320" fullname="NUnit_v3_samples.NUnitIssue320" classname="NUnit_v3_samples.NUnitIssue320" runstate="NotRunnable" testcasecount="0" result="Failed" label="Invalid" site="SetUp" start-time="2015-05-14 11:05:26Z" end-time="2015-05-14 11:05:26Z" duration="0.000052" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
        <properties>
          <property name="_SKIPREASON" value="An exception was thrown while loading the test.&#xD;&#xA;NUnit.Framework.Internal.InvalidTestFixtureException: NUnit_v3_samples.NUnitIssue320 does not have a default constructor&#xD;&#xA;   at NUnit.Framework.Internal.Reflect.Construct(Type type)&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(MethodInfo method)&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(MethodInfo method)&#xD;&#xA;   at NUnit.Framework.TestCaseSourceAttribute.BuildFrom(MethodInfo method, Test suite)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(MethodInfo method, Test parentSuite)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCases(Type fixtureType)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(Type type, TestFixtureAttribute attr)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildMultipleFixtures(Type type, IFixtureBuilder[] attrs)&#xD;&#xA;   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(Type type)" />
        </properties>
        <failure>
          <message>An exception was thrown while loading the test.
NUnit.Framework.Internal.InvalidTestFixtureException: NUnit_v3_samples.NUnitIssue320 does not have a default constructor
   at NUnit.Framework.Internal.Reflect.Construct(Type type)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(MethodInfo method)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(MethodInfo method)
   at NUnit.Framework.TestCaseSourceAttribute.BuildFrom(MethodInfo method, Test suite)
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(MethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCases(Type fixtureType)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(Type type, TestFixtureAttribute attr)
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildMultipleFixtures(Type type, IFixtureBuilder[] attrs)
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(Type type)</message>
        </failure>
      </test-suite>
```

**Comment by CharliePoole** [comment] 2015-05-14 13:37
I think we fixed this sufficiently. I updated the documentation page on the wiki and I'm closing this issue.

@rprouse My thought is to just update the release notes and change list under the beta 2 heading since the issue was substantially fixed there. What do you think?

**Closed by CharliePoole** 2015-05-14 13:37 UTC
Labels: is:bug, pri:normal

**Comment by rprouse** [comment] 2015-05-14 13:45
Sure, makes sense to include it.
