### ISSUE TITLE
CollectionAssert.AreEquivalent is broken from 3.13.2 to 3.13.3

### ISSUE THREAD

**Issue by damiang78** [nunit/nunit#4190] opened 2022-09-28 17:26 UTC
Hi, 

It looks like upgrading NUnit from 3.13.2 to 3.13.3, causes CollectionAssert.AreEquivalent to break when comparing ImmutableDictionary. Here is a test to reproduce the bug

```
using System.Collections.Immutable;

namespace nunit_bug;

[TestFixture]
public class MyTestFixture
{
      [Test]
      public void Test()
      {
         var expected = new Dictionary<string, string>
         {
            {"Fred", "London"},
            {"Bob", "Paris"}
         }.ToImmutableDictionary();
      
         var actual = new Dictionary<string, string>
         {
            {"Fred", "London"},
            {"Bob", "Paris"}
         }.ToImmutableDictionary();
      
         CollectionAssert.AreEquivalent(actual, expected);
      }
}
```

Running the above test in 3.13.2 succeeds, whereas running with 3.13.3 fails.

Looking at the difference in these versions it looks like it's because of this [change](https://github.com/nunit/nunit/commit/ac6a91da3bc56aa06bd859890fef25619f12b84f) on line 92.

We make good use of ImmutableDictionary, and as a result quite a few of our tests have failed because of this.

This is using .NET 6.0

**Comment by stevenaw** [comment] 2022-10-05 00:44
Sorry you hit this @damiang78 and thank you for the detective work in narrowing down the exact cause. I suspect this is a duplicate of https://github.com/nunit/nunit/issues/4095 which we found this shortly after 3.13.3 was released. The fix hasn't been released yet, but hopefully soon. 🙂

I'm going to close this issue as a duplicate for now but we'll still see any follow-up comments here

**Closed by stevenaw** 2022-10-05 00:44 UTC
