### ISSUE TITLE
TestContext.CurrentContext has no information

### ISSUE THREAD

**Issue by mr-raptor** [nunit/nunit#1102] opened 2015-12-01 12:24 UTC
Hello. I have updated my project to NUnit 3.0 and now TestContext.CurrentContext has no information about current test (see screenshot http://prntscr.com/991sn9). Could you please advise how to fix it?

Thanks.

**Comment by rprouse** [comment] 2015-12-01 12:46
Looks like you are using Resharper, correct? Resharper doesn't support NUnit 3 yet.

**Comment by mr-raptor** [comment] 2015-12-01 13:00
No, it's not. I run tests from nunit3-console.

**Comment by appel1** [comment] 2015-12-01 13:11
Since OneTimeSetup is executed before any tests in the fixture I don't think TestContext.CurrentContext is available.

**Comment by mr-raptor** [comment] 2015-12-01 13:23
I also tried to get context in SetUp method and inside test - in both cases there is no information. It worked with NUnit 2.6.4.

**Comment by appel1** [comment] 2015-12-01 13:40
What version of NUnit does your test assembly reference and what version of nunit3-console?

**Comment by mr-raptor** [comment] 2015-12-01 13:56
NUnit in project - 3.0.5797.27534
nunit3-console - 3.0.5797.27555

**Comment by CharliePoole** [comment] 2015-12-01 17:44
The screenshot shows an error in debugging. Where was the debugger paused when you made it?

CurrentContext is **only** available while the tests are actually running. To see values in the debugger, you will have to break in the test (or setup) on the thread that is actually running the test. Otherwise, I can guarantee that CurrentContext will be null.

**Comment by constructor-igor** [comment] 2015-12-14 09:05
I copied original picture with reported problem from http://prntscr.com/991sn9 to the issue 
![image](https://cloud.githubusercontent.com/assets/1849690/11776773/876c7844-a252-11e5-965f-ff4080062d8e.png)

**Comment by constructor-igor** [comment] 2015-12-14 09:10
I cannot reproduce the issue with debugging under R# or NUnit3 Test Adapter + nunit (v3.0.5813.39031):
![image](https://cloud.githubusercontent.com/assets/1849690/11776819/d3960d48-a252-11e5-9da7-c8e5e09b7797.png)

Sometimes I see same issue (debugger doesn't show value of variables) for other area of program (not related to nunit).

**Comment by rprouse** [comment] 2015-12-14 09:55
@mr-raptor did you get it working? We can't reproduce, so I am closing this issue. If you can provide more information, we will reopen it.

**Closed** 2015-12-14 09:55 UTC
Labels: closed:norepro

**Comment by mr-raptor** [comment] 2015-12-14 10:15
I'm sorry, but now I have no time for this issue. Thanks for your help. I'll investigate it later.
