### ISSUE TITLE
Linux CI failure

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2400] opened 2017-08-31 01:38 UTC
https://travis-ci.org/OmicronPersei/nunit/jobs/270226749#L1666

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc () [0x00079] in <867b41d1d7c942ed9d9930695ba85889>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
```

**Comment by jnm2** [comment] 2017-08-31 13:55
That means one of the lines here is missing a null check:

https://github.com/nunit/nunit/blob/ec7dddd3d89c2a8a6ff1dc166f01b249b3155bbf/src/NUnitFramework/framework/Internal/Execution/TestWorker.cs#L109-L138

**Comment by jnm2** [comment] 2017-08-31 13:59
Either:
 -  `WorkQueue` was null in line 117
 -  `_workerThread` was null in line 121
 -  `log` was null in lines 121 or 136
 - `_currentWorkItem` became null after the null check in lines 121 and 123.

If any exception happened and `log` was null, the finally block would wipe out the exception by throwing an NRE instead.

**Comment by jnm2** [comment] 2017-08-31 14:11
The stack return offset 0x79 confirms that the line that caused the NRE was `_currentWorkItem.Execute()`.

**Comment by jnm2** [comment] 2017-08-31 14:15
@CharliePoole So sorry to keep bothering you with these. It's evident that `_currentWorkItem` was not null on line 123 and was null on line 127. That means either `Busy` invoked something that caused it to become null, or multiple threads are accessing `_currentWorkItem` concurrently. Do you have time to take this over?

**Comment by CharliePoole** [comment] 2017-08-31 14:20
We set it to null in Cancel to ensure we only cancel once. Probably shouldn't do that!

**Comment by CharliePoole** [comment] 2017-08-31 15:14
A quick fix might be to break out of the loop whenever the item is nulll. But that's pretty ugly.

I think my reasoning in the Cancel method was that it only gets called once, when trying to do a forced shutdown. Can you figure out why it's being called in this test? I would have thought we wanted to cancel the test, not the test worker. I'm pretty tied up today, but I could take a more in-depth look at it in a few days.

**Comment by jnm2** [comment] 2017-08-31 16:03
I can't think of an approach to figure out why Cancel was called. The stack trace of this worker thread is all we have. If this can be repro'd locally I could.

**Comment by CharliePoole** [comment] 2017-08-31 16:36
I assume somebody with a Linux box will have to take this on eventually. It's pretty hard to debug it via CI runs only.

**Comment by jnm2** [comment] 2017-08-31 16:38
I'm running the stereotypical Ubuntu VM...

**Comment by jnm2** [comment] 2017-08-31 16:39
For extremely intermittent values of "running"...

**Comment by jnm2** [comment] 2018-01-20 04:12
This is a duplicate of https://github.com/nunit/nunit/issues/2282.

**Closed by jnm2** 2018-01-20 04:12 UTC
