### ISSUE TITLE
NUnit framework AssertionException inner exception null at NUnit.Framework.Assert.ReportFailure(String message)

### ISSUE THREAD

**Issue by Priyank-Agrawal** [nunit/nunit#2330] opened 2017-07-27 19:15 UTC
I've written Specflow test cases to perform integration testing. I'm using Assert.Fail() method to report any failure from my test case in case of failed validations. However, whenever my validation fails and I reach to code statement Assert.Fail() I'm seeing below exception.

at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at NUnit.Framework.Assert.Fail(String message)

Nuget Packages that I'm using in my project -
NUnit - 3.7.1
Specflow.NUnit - 2.2.0
NUnit 3 test Adapter for Visual Studio - 3.8.0

**Comment by rprouse** [comment] 2017-07-27 19:31
Possible duplicate of #2327 and caused by TestContext being null for SpecFlow tests?

**Comment by Priyank-Agrawal** [comment] 2017-07-27 20:16
To make sure this issue is not caused by objects that I'm comparing in assertion statement I tired comparing two strings
 Assert.That("abc".Equals("xyz"));

Which is resulting in same error.

**Comment by jnm2** [comment] 2018-01-15 16:54
@Priyank-Agrawal Would you please create a minimal repro if this is still a problem in NUnit 3.9.0?

**Comment by rprouse** [comment] 2018-01-30 21:54
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Closed by rprouse** 2018-01-30 21:54 UTC
Labels: confirm
