### ISSUE TITLE
Assertions outside of test thread

### ISSUE THREAD

**Issue by SeanFeldman** [nunit/nunit#2275] opened 2017-06-22 00:29 UTC
I've gone through issue #2223 and have a different case where assumption about test thread doesn't necessarily hold true.

This issue is manifesting itself when working with the [WindowsAzure.ServiceBus Client SDK](https://www.nuget.org/packages/WindowsAzure.ServiceBus/) and registering a message pump (callback) within the test method. Assertions within the callback fail with NRE.

```c#
public async Task Should_not_fail()
{
	var namespaceManager = NamespaceManager.CreateFromConnectionString(connectionString);
	var queuePath = "repro";

	var queueClient = QueueClient.CreateFromConnectionString(connectionString, queuePath);
	await queueClient.SendAsync(new BrokeredMessage("message"));

	queueClient.OnMessageAsync(async message =>
	{
		var payload = message.GetBody<string>();
		Assert.AreEqual(payload, "message"); // THROWS NRE
		await message.CompleteAsync();
	}, new OnMessageOptions
	{
		AutoComplete = false,
		MaxConcurrentCalls = 1
	});
}
```

Full repro code is [here](https://github.com/SeanFeldman/NUnitWithASB.TextExecutionContext.Repro/).

The [safe guarding in 3.6.1](https://github.com/nunit/nunit/blob/3.6.1/src/NUnitFramework/framework/Internal/TestExecutionContext.cs#L219) guaranteed this would not happen, but in [3.7.0](https://github.com/nunit/nunit/blob/3.7/src/NUnitFramework/framework/Internal/TestExecutionContext.cs#L192) NREs are now thrown. 

The [suggested approach](https://github.com/nunit/nunit/issues/2223#issuecomment-306458085)
```c#
var context = new NUnit.Framework.Internal.TestExecutionContext();
context.EstablishExecutionEnvironment();
Assert....
```
seems a bit intrusive.

**Comment by CharliePoole** [comment] 2017-06-22 00:41
I'm curious to know how this could ever have worked correctly. It's definitely true that the NRE is not thrown prior to 3.7, so successful tests should have worked. But a failing assert in a separately created thread has never been supported. What happened in the past if your test failed?

The standard way to deal with callbacks in the past has been to store the value to be tested in an accessible member, then perform the Assert on the test thread. It looks as if you could do that here. The "suggested approach" is not one I would recommend and I don't think @rprouse is actually recommending it either. We do something like that in certain tests of NUnit itself, but we're testing the internals in that case.

We are investigating a way to allow tests to be run without NUnit having first created a test context. The solution to that might also be a fix for this issue, so I think we should hold on to it.

**Comment by SeanFeldman** [comment] 2017-06-22 00:45
@CharliePoole this is a simplified test, so don't take it as-is. It is solely to demonstrate what happens. Storing the value outside would be a challenge as ASB is one of the many messaging services automated test suite is running through. None of them has the issue like ASB does, so the tests are not organized to "keep something for verifying later".

**Comment by SeanFeldman** [comment] 2017-06-22 00:48
> I'm curious to know how this could ever have worked correctly.

It did 🙂 Downgrade NUnit to 3.6.1 and it will work.

**Comment by CharliePoole** [comment] 2017-06-22 00:53
Is a failure of the Assert reported as such?

**Comment by CharliePoole** [comment] 2017-06-22 01:23
LOL I'm always closing these things by mistake and re-opening them. 😃 

OK, so that example shows me that NUnit does __not__ see the failure. What's happening is that your `Assert.True` is taking the result and effectively converting an error to a failure.

I'd be very surprised to find any AssertionException in a separate thread that NUnit captured and processed as a __failure__ unless that thread had been started in a way that the allowed the context to be passed to it. 

Unfortunately, I don't have the software installed to try out exactly what you are doing under any version of NUnit. I wonder if it can be simulated without the ServiceBus client.

All that said... if not getting the NRE will make it work for you, we are working on that. 😄

**Comment by SeanFeldman** [comment] 2017-06-22 02:59
@CharliePoole you're correct. I tried a simple `Assert.IsTrue(false)` and `AssertionException` was not propagated out of the callback. So there's also an issue on our end.

You don't need any software to be installed to run the repro, all self contained. You do need an Azure account and a namespace (basic would do) to get the connection string.

In regards to NRE - an issue/PR I could track?

**Comment by CharliePoole** [comment] 2017-06-22 05:06
See #2242. It's not clear if we will fix it or just improve the error message so it basically tells you what you already had to figure out. Fixing it would obviously be better, but is tricky. Your error arises in a different situation, but it still seems to be the same cause.

BTW, the creation of a context on the fly, as we did in 3.6.1 resolves the problem of the NRE, but since we don't have any information to use, the context is not properly initialized. That makes problems harder to discover, which is why we stopped doing that.

I think we might consider a sort of null context, one that works as well as it can but gives a meaningful error if you try to do anything with the fields we are unable to initialize.

**Comment by SeanFeldman** [comment] 2017-06-22 18:05
Raised an issue with ASB client team. Would be good for NUnit to avoid throwing NRE and provide a meaningful message 🙂

**Comment by CharliePoole** [comment] 2017-06-22 18:44
Perhaps best is to do the message - which is easy - and come back to it again later to try for a different approach. @jnm2 What do you think?

**Comment by jnm2** [comment] 2017-06-22 19:08
@CharliePoole Since I'm swamped, I can't argue. :-D

**Comment by CharliePoole** [comment] 2017-06-22 19:19
@jnm2 So are you doing the simpler fix? Or should somebody else do it?

**Comment by jnm2** [comment] 2017-06-22 20:40
I'm going to let someone else because I didn't even get time to start.

**Comment by rprouse** [comment] 2017-06-22 21:36
Should we close this as a duplicate of #2223? It is a different use case, but it is the same issue.

**Comment by rprouse** [comment] 2017-06-22 21:54
Sorry, #2223 is a marked as a question, it is #2242 that I am thinking of. I will do the simple fix and I am going to close this as a duplicate. If anyone thinks we should keep this open for a deeper fix, please comment and reopen.

**Closed by rprouse** 2017-06-22 21:54 UTC
