### ISSUE TITLE
Assert.Warn setting result="Warning" instead of leaving Passed or Failed

### ISSUE THREAD

**Issue by jonnydatester** [nunit/nunit#3153] opened 2019-02-01 20:26 UTC
We were previously on NUnit 3.8.1 and on 7/3/18 we updated to 3.10.1. In our framework we do a final check for errors after the test has passed or failed and we use Assert.Warn() to display warning messages. In the result.xml it is displaying the result as "Warning" instead of pass/fail. Previously we didn't notice it on 3.81 so not sure if there was a change that caused this.

**Comment by CharliePoole** [comment] 2019-02-01 21:42
Where he the code that does the Assert.Warn? Can you provide a basic example?

**Comment by jonnydatester** [comment] 2019-02-01 23:02
I created a test which has a simple Assert.Warn.

[Test]
public void TestWarning()
{
	Assert.True(1 == 1);
	Assert.Warn("THIS IS A TEST");
}

public void TeardownWarning()
{
      var testStatus = TestContext.CurrentContext.Result.Outcome.Status; //The value for this is "Warning"
}

**Comment by CharliePoole** [comment] 2019-02-02 00:57
Yes, that's to be expected. Assert.Warn terminates the test with a status of Warning, just as Assert.Fail terminates it with a status of Failed.

**Comment by rprouse** [comment] 2019-02-02 15:08
I am going to close this as "by design". Feel free to post if you have questions.

**Closed by rprouse** 2019-02-02 15:08 UTC
