### ISSUE TITLE
Nunit 3.10.1.0 + ReSharper 2020.1.4: Test execution delayed by ~60seconds 

### ISSUE THREAD

**Issue by h4kun4m4t4t4** [nunit/nunit#3601] opened 2020-07-22 14:39 UTC
Hi,

first of all, I'm not sure whether NUnit or Resharper might be the problem. (But problems started after upgrading to latest resharper)

When I start the execution of a test via resharper test runner, the test shows pending for about 60 seconds before even starting the relevant test code. I tracked it down to be a loading/performance issue at **RuntimeFramework.cs** 
`Type monoTouchType = Type.GetType("MonoTouch.UIKit.UIApplicationDelegate,monotouch");`
The call to the above takes about 60 seconds and will then continue normal test execution.

Does anyone know what the problem might be or how I can track it further down?

What I did so far:

- Execution with MS Test and NUnitTestadapter: works fine

- setup a new Solution: no problem of test execution

- When at the above position in debugger -> execute at immediate window (without the "**,monotouch**"):  `Type.GetType("MonoTouch.UIKit.UIApplicationDelegate");` --> returns immediately

**Comment by CharliePoole** [comment] 2020-07-22 15:33
The key bit you have left out is what kind of an application you are targeting. :smiley: That line of code will execute differently depending on whether you are using MonoTouch or not.

To be more precise, it will execute differently depending on whether an assembly containing that UI delegate is loaded or not.

**Comment by h4kun4m4t4t4** [comment] 2020-07-23 06:08
Thanks for the info.
The application is written in C# and targeting .Net Framework 4.7. 
In fact in our company we have different Solutions with the above settings... some show the delay and some not.

I did non hear about MonoTouch until yesterday, so I do not think it is involved at all. The call always returns "Null".

In the meantime I believe it might be something how the resharper testrunner orchestrates NUnit. Maybe it is something in the environment. But currently I'm lost and do not know what to look for.

**Comment by ChrisMaddock** [comment] 2020-07-23 20:09
I suspect a PR I did 2 years ago is the reason for the change between 3.10 and 3.12 --> https://github.com/nunit/nunit/pull/3131

I have no idea what might be the cause of your current issue, I'm afraid.

**Comment by h4kun4m4t4t4** [comment] 2020-07-28 06:39
Morning, 
I'm currently back to my old setup **Nunit 3.10.1.0 + ReSharper 2019.2.4**. This works fine so far.

Last Friday I was experimenting and tried to create a simple test project, to be able to reproduce the problem.... It is not that easy :-/.
In the end I took one of my company projects and stripped down all unnecessary code parts. 
In my company all solutions and projects output-folder points to the same directory -> ~10k files (exe, dll, config, pdb, folder)

- test project with delayed test: output-folder with about ~10k files --> show delay
- test project with delayed test: change output directory to a unique folder (about 20 files) --> no delay

Then I tried to find out if a file maybe affects ReSharper or NUnit, by deleting chunks of 500 files. But that did not lead to clear results:

- test project
-- on one point the execution was not delayed anymore. But after restoring the last removed chunk it works as well.
-- some times the execution was delayed by ~20 seconds, some times not.

The Testrunner of resharper shows only one real difference between 2019.2.4 and 2020.1.4 in the verbose log (apart from different bin folder):
- 2019.2.4: VERBOSE Running elements from criterion: {TestAncestorCriterion: NUnit3x::A953C6C0-11F1-43E0-96F8-46C072EDBB0C::.NETFramework,Version=v4.7::TestProject.TestFixture.Foo}

- 2020.1.4: VERBOSE Running elements from criterion: {ConjunctiveCriterion: {TestAncestorCriterion: NUnit3x::A953C6C0-11F1-43E0-96F8-46C072EDBB0C::.NETFramework,Version=v4.7::TestProject.TestFixture.Foo}, {TestAncestorCriterion: NUnit3x::A953C6C0-11F1-43E0-96F8-46C072EDBB0C::.NETFramework,Version=v4.7::TestProject.TestFixture.Foo}}
 => I guess this would be some thing to ask in the resharper forum

**Comment by ChrisMaddock** [comment] 2020-07-29 20:04
@h4kun4m4t4t4 I agree you need to follow this one up with the ReSharper team. Those log messages you've shared are from ReSharper, not NUnit, but sound like they might point to the difference.

I'll close this issue, as I don't think there's any more we can do here - but please open a new one if you can trace a cause back to NUnit. 👍

**Closed by ChrisMaddock** 2020-07-29 20:04 UTC

**Comment by rprouse** [comment] 2023-02-21 02:31
I believe this was fixed by #4034
