### ISSUE TITLE
Prerequisite Tests (Feature)

### ISSUE THREAD

**Issue by JeffCave** [nunit/nunit#1031] opened 2015-11-17 14:53 UTC
I have a couple of cases where I would like to mark a test as a prerequisite of another test. It would be nice to have an attribute that indicated tests that were prerequisites of the current test.

In the case where routines depend on one another, it is possible to know that a given test is going to fail because a sub-routine failed its test. If the test is a long running one, there really isn't any point in running the test if the sub-routine is broken anyway.

Contrived Example:

	public static class Statistics
	{
		public static double Average(IEnumerable<double> values)
		{
			double sum = 0;
			double count = 0;
			foreach (var v in values)
			{
				sum += v;
				count++;
			}
			return sum / count;
		}

		public static double MeanVariance(IEnumerable<double> values)
		{
			var avg = Average(values);
			var variance = new List<double>();
			foreach (var v in values)
			{
				variance.Add(Math.Abs(avg - v));
			}
			avg = Average(variance);
			return avg;
		}
	}

	[TestFixture]
	public class TestStatistics
	{
		[Test]
		public void Average()
		{
			var list = new List<double> { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 };
			var avg = Statistics.Average(list);
			Assert.AreEqual(4.5, avg);
		}

		[Test]
		//[Prerequisite("TestStatistics.Average")]
		public void MeanVariance()
		{
			//try { this.Average(); } catch { Assert.Ignore("Pre-requisite test 'Average' failed."); }
			var list = new List<double> { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 };
			var variance = Statistics.MeanVariance(list);
			Assert.AreEqual(0, variance);
		}
	}

Given the example, if the test `Average` fails, it makes sense to not bother testing `MeanVariance`.

I would conceive of this working by chaining the tests (though I can see variations): 
* if `MeanVariance` is run, `Average` is forced to run first. 
* If `Average` has already been run, the results can be reused.
* If `Average` fails, `MeanVariance` is skipped.

May be a duplicate of something that was on the list many years ago: http://sourceforge.net/p/nunit/feature-requests/347/ .

**Comment by rprouse** [comment] 2015-11-17 15:43
Excellent write-up. I think this is a duplicate of #51. If so, can you copy and paste this into that issue and close this one? I could do it for you, but if you add the comment, you will get notified of updates.

If it isn't a duplicate, can you explain the difference?

**Comment by CharliePoole** [comment] 2015-11-17 17:37
We should take a close look at test dependency when planning the next release. Issue #51, like a lot of releases, was put into the 'future' milestone when we decided we couldn't get it in the final 3.0 release. Subsequently, we created the '3.2' milestone and started putting things there but we really have not given a lot of thought to what **really** belongs in 3.2 versus the vague 'future'.

**Comment by JeffCave** [comment] 2015-11-17 18:47
Darn... I searched for it too. Obviously some keyword differences between the two.

Copied over.

**Comment by rprouse** [comment] 2015-11-17 18:57
Thanks @JeffCave. It took me awhile to find it too and I knew what the attribute was going to be called :smile: 

I am closing this as a duplicate now.

**Closed by rprouse** 2015-11-17 18:57 UTC
