### ISSUE TITLE
ConstructFixtureCommand.cs not found

### ISSUE THREAD

**Issue by pavlikpatrycja** [nunit/nunit#2937] opened 2018-07-19 12:26 UTC
Hi, 
I'm using NUnit in 3.10.1 version downloaded by NUget Packages Manager. While debugging my project in test constructor I have an error that ConstructFixtureCommand.cs was not found. There is no ConstructFixtureCommand.cs in NUnit directory. How to fix this ? 
Thanks in advance

**Comment by mikkelbu** [comment] 2018-07-21 16:21
As far as I can tell, the file has been in the same location since 3.7. How are you debugging @pavlikpatrycja ?
* From within VS
* Are you using the adapter
* How are the Debug settings (especially, Debug > Options > ‘Enable Just My Code’ and n Debug > Options > ‘Enable source server support’)

**Comment by ChrisMaddock** [comment] 2018-08-28 12:26
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2018-08-28 12:26 UTC
Labels: confirm
