### ISSUE TITLE
Current Nunit Test Properties are always coming as null when using TestCaseSource in Test method

### ISSUE THREAD

**Issue by RafeeqMohammed** [nunit/nunit#3587] opened 2020-06-25 16:44 UTC
Current Nunit Test Properties are always coming as null when using TestCaseSource in Test method.

Below is my test mthod

 [TestCaseSource("DeviceInfoFromAppConfig"), Description("MyTestDescription")]
 public void TestMethod(MobileOs os, string appName)
{
var desc1 =TestContext.CurrentContext.Test.Properties["Description"];
var desc2 =TestExecutionContext.CurrentContext.CurrentTest.Properties.Get("Description");
var desc3 = TestExecutionContext.CurrentContext.CurrentTest.Properties["Description"];
Assert.Pass();
}

desc1 count is 0
desc2 is null
desc3 count is 0

![image](https://user-images.githubusercontent.com/34459276/85761955-df135a00-b6d8-11ea-8bc8-130f9f46a6bb.png)

If i use Test or TestCase then it is working fine, i can get description property without any issues.

**Comment by cjconrad2** [comment] 2020-08-02 22:33
@RafeeqMohammed, which version of the framework are you using?

**Comment by CharliePoole** [comment] 2020-08-02 23:04
This is a well-known "gotcha" in NUnit, which has been discussed many times. When a test method has arguments, a suite of tests is created, which contains the individual test cases. The attribute is applied to that suite, not to the individual tests.

Basic question is "Why does your test need to know it's own description?"

**Comment by Dreamescaper** [comment] 2020-08-05 08:37
Duplicate of https://github.com/nunit/nunit/issues/1358.

**Comment by mikkelbu** [comment] 2021-08-28 11:36
I'm closing this as a duplicate of #1358 (and all the related issues in https://github.com/nunit/nunit/projects/3)

**Closed by mikkelbu** 2021-08-28 11:36 UTC
