### ISSUE TITLE
It's recommended to reference NuGet test adapters in each test project in the solution.

### ISSUE THREAD

**Issue by chucklu** [nunit/nunit#3334] opened 2019-07-31 06:17 UTC
It's weird, previously the unit test works fine.
Suddenly I got the following info:

> 
> [7/31/2019 2:06:58.100 PM Warning] No test matches the given testcase filter `FullyQualifiedName=SilverFishTest.ChuckTest.CardIdEnumTest` in C:\repository\GitHub\ChuckLu\Test\HearthbuddyRelease\Routines\DefaultRoutine\SilverFishTest\bin\Debug\SilverFishTest.dll
> [7/31/2019 2:06:58.447 PM Informational] Test project SilverFishTest does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
> It's recommended to reference NuGet test adapters in each test project in the solution.

I have no idea why this happened.

**Comment by chucklu** [comment] 2019-07-31 06:18
I am using vs2019 16.2, and the NUnit version is  3.12.0

**Comment by chucklu** [comment] 2019-07-31 06:22
The problem could be resolved by reference  the following package.
<package id="NUnit3TestAdapter" version="3.13.0" targetFramework="net48" />

But I am wondering why I did not need the above package in the past.

**Comment by mikkelbu** [comment] 2019-07-31 08:31
Hi @chucklu Have you just updated Visual Studio or changed the test configuration in Visual Studio? Visual Studio have since version 2017 (the latter updates) started a path towards having test adapters as nuget packages instead of VSIX extensions, so depending on your configuration you should reference the appropriate adapter, see eg https://stackoverflow.com/questions/52033250/facing-test-case-not-found-on-visual-studio-2017-version-15-8-1.

Ps I'm closing this issue as answered, but we will still see followup questions/comments.

**Closed by mikkelbu** 2019-07-31 08:31 UTC

**Comment by chucklu** [comment] 2019-07-31 09:04
@mikkelbu  Yes, I upgrade vs 2019 from 15.9 to 16.2 recently.

> Microsoft Visual Studio Community 2019
> Version 16.2.0

I am not sure why my configuration section is different from the one you mentioned above.
I did not have chance to `Uncheck the option and restart your visual studio`

![image](https://user-images.githubusercontent.com/3004057/62198850-feb0de00-b3b4-11e9-8095-aa5aba2a8999.png)

**Comment by chucklu** [comment] 2019-07-31 09:09
I just review the release notes of 16.2 of vs 2019, it seems there are changes about test explorer. But it did not mention the adapter problem.
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#test-explorer

**Comment by stevenaw** [comment] 2019-07-31 12:10
Hi @mikkelbu @chucklu
This sounds familiar. I think you're right about the VS 16.2 connection, it sounds similar to this issue here: https://github.com/nunit/nunit3-vs-adapter/issues/639

**Comment by chucklu** [comment] 2019-08-18 08:08
Previously I am using Resharper with vs 2019, after I upgrade Resharper to current latest version. I can run unit test without adapter.

**Comment by CharliePoole** [comment] 2019-08-18 09:24
@chucklu Just a bit of advice for the future... AFAICS you never mentioned before that you are using Resharper. Did I miss that? It's a pretty important bit of information because it basically changes what problem folks are trying to help you solve.

**Comment by chucklu** [comment] 2019-08-18 09:32
@CharliePoole  Thanks for your advice, but I did not realized that the problem is related to Resharper when I file this issue.

**Comment by CharliePoole** [comment] 2019-08-18 13:42
It's a good idea to let us know what you use to run tests, in particularly if a third-party runner is involved. That's because we'll be trying to reproduce the problem but won't be using the same software that you use.

**Comment by adnan-sharif** [comment] 2019-12-24 15:18
I was having the same issue while running unit tests on `Visual Studio 2019 v16.0.2`.
So, I just want to share with others who are facing the same issue.
According to [this comment](https://github.com/nunit/nunit/issues/3334#issuecomment-516714223) of @chucklu and [Krishna Seelam's comment](https://social.msdn.microsoft.com/Forums/en-US/b0ab2a3f-d8ab-403a-85f7-39fbb246e2a2/cannot-run-unittests-with-testexplorer?forum=vstest) on msdn forum,

---
**Installing latest stable version of `NUnit3TestAdapter` solves the problem.**
