### ISSUE TITLE
NUnit crashes with an ArgumentException when an environment variable is defined with mutliple cases on windows

### ISSUE THREAD

**Issue by matthid** [nunit/nunit#1796] opened 2016-09-18 09:59 UTC
git bash on windows:

```bash
export LocalAppData=/c/test
// run nunit -> crashes because on windows usually 'LOCALAPPDATA' is already defined.
```

```
System.ArgumentException: Item has already been added. Key in dictionary: 'LocalAppData'  Key being added: 'LOCALAPPDATA'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
   at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)
   at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
   at NUnit.Engine.Runners.ProcessRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Load()
   at NUnit.Engine.Runners.MasterTestRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

**Comment by rprouse** [comment] 2016-09-29 13:37
Adding a confirm because I want to ensure it is our code that is causing this, not a general issue with `ProcessStartInfo.EnvironmentVariables`.

**Comment by rprouse** [comment] 2016-09-29 13:58
I am closing this as `not our bug` (TM)

NUnit does not set `LOCALAPPDATA`, but it does have to set other environment variables. I reproduced your bug with the following console app.

```C#
static void Main(string[] args)
{
    Process p = new Process();
    p.StartInfo.UseShellExecute = false;
    p.StartInfo.FileName = @"C:\Windows\notepad.exe";
    p.StartInfo.EnvironmentVariables["COMPLUS_Version"] = "4.0.30319";
    p.StartInfo.LoadUserProfile = false;
    p.Start();
}
```

**Closed by rprouse** 2016-09-29 13:58 UTC
Labels: confirm

**Comment by rprouse** [comment] 2016-09-29 14:00
As a workaround, you could probably run with `--inprocess`, or switch to CMD or PowerShell for running from the command line.

**Comment by ChrisMaddock** [comment] 2016-09-29 14:13
Agreed its not-our-bug. The issuse is that `p.StartInfo.EnvironmentVariables` tries to build a case-insensitive StringDictionary, leading to duplicate keys.

I did wonder if we could however work around it by NUnit using `Environment.SetEnvironmentVariable("variable", "value", EnvironmentVariableTarget.Process)` instead. Never got round to investigating.

**Comment by rprouse** [comment] 2016-09-29 14:33
Good point about case sensitivity @ChrisMaddock. I retested using the correct case for the environment variable `export LOCALAPPDATA=/d/tmp` and it works fine. Based on this, even if we were to try and fix it, I would class it as extremely low priority based on that.
