### ISSUE TITLE
NUnitLite package always installs both Program.cs and Program.vb

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1428] opened 2016-04-20 09:24 UTC
The NUnitLite package has an install script which looks like it should be delete either of these files if they do not match the project type. It doesn't seem to be working. Haven't really looked in to why, yet.

**Comment by CharliePoole** [comment] 2016-04-20 10:08
I can verify that it worked at one time.

**Comment by ChrisMaddock** [comment] 2017-03-28 08:38
Update: I believe install.ps1 is no longer ran at all for `PackageReference` or `project.json` NuGet scenarios.

We probably need to find a different solution for this functionality.

https://github.com/aspnet/EntityFramework6/issues/189#issuecomment-279820372

**Comment by ChrisMaddock** [comment] 2017-03-28 08:45
The contentfiles can be specified with a target language in the directory - although I don't know how backwards compatible that is. Given this has been 'not working' since this time last year though, maybe not worth worrying about too much. 😄

https://docs.microsoft.com/en-us/nuget/schema/nuspec#package-folder-structure

**Comment by CharliePoole** [comment] 2017-03-28 17:02
@ChrisMaddock From the docs, it's not clear whether installing the package would cause the files to be copied only to the corresponding project type. Experiment if you like. 😄 

We also have had some discussion that indicates this causes problems when the package is installed in CI, if the user already provided their own entry point, so we may want to rethink this. Maybe it should just be provided as a sample or not provided at all.

**Comment by rprouse** [comment] 2017-03-29 21:20
We can drop the install.ps1 and just put the files in `Content` and they will be copied in. If they already exist in a user's project, they will be prompted if they want to overwrite when they install or upgrade the package. It is never copied in a restore.

**Comment by CharliePoole** [comment] 2017-03-29 23:32
@rprouse The problem isn't with overwriting a file but with having two files in the project that define Main. Whoever works on this should ensure that it works in that situation.

**Comment by ChrisMaddock** [comment] 2017-09-01 14:05
This is another one that causes me regular pain, and I want to get round to fixing.

There's some debate here as if we want to install the file at all. Personally - I'd like to fix the current (intended) behaviour, and leave any further improvements to a separate issue.

Any objections to that?

**Comment by CharliePoole** [comment] 2017-09-01 14:52
I don't think it matters which way we go - either dropping both or using the correct language.

**Comment by jnm2** [comment] 2017-09-02 15:59
@ChrisMaddock sounds good.

**Comment by mikkelbu** [comment] 2021-08-30 20:40
I looks like install.ps1 is not supported anymore - see NuGet/Home#6330 and NuGet/Home#5963 - but perhaps we can use Init.ps1 instead - see https://stackoverflow.com/a/40932008 - but that will be executed every time the solution is opened.

**Comment by CharliePoole** [comment] 2021-08-30 22:05
Why not just remove the install script and both files? Neither file has been installed for about three years. I just installed nunitlite in a project yesterday. I typed in a one-line main and that was it.

**Comment by mikkelbu** [comment] 2021-10-02 21:38
I agree with Charlie. I've supplied a PR and I'll update https://docs.nunit.org/articles/nunit/running-tests/NUnitLite-Runner.html when this is merged.

**Closed** 2021-10-05 10:41 UTC
Labels: is:bug, pri:normal
