### ISSUE TITLE
PropertyConstraint throws away the more helpful message in the base constraint result

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2427] opened 2017-09-08 19:08 UTC
## Problem

PropertyConstraint keeps the base constraint description but throws away the actual comparison message and just prints the actual value.

Starting with a familiar example, `Is.EquivalentTo`:

```cs
var actual = new SomeClass { SomeProperty = { 2, 3, 5, 7 } };
Assert.That(actual.SomeProperty, Is.EquivalentTo(new List<int> { 2, 3, 5, 8 }));
```

>   Expected: equivalent to < 2, 3, 5, 8 >
>   But was:  < 2, 3, 5, 7 >
>   Missing (1): < 8 >
>   Extra (1): < 7 >

But as soon as you compose it with `PropertyConstraint`:

```cs
var actual = new SomeClass { SomeProperty = { 2, 3, 5, 7 } };
Assert.That(actual, Has.Property("SomeProperty").EquivalentTo(new List<int> { 2, 3, 5, 8 }));
```

>   Expected: equivalent to < 2, 3, 5, 8 >
>   But was:  < 2, 3, 5, 7 >

In that example, just printing the actual value is still pretty okay.
But when the value is a complex object that doesn't `.ToString()` to something you care about, you get something like this:

>   Expected: property SomeProperty [long description from custom constraint]
>   But was:  \<Appearance>

```cs
Assert.That(new SomeClass(), Has.Property("SomeComplexThing")
    .SomeCustomConstraint(expectedComplexThing));
```

## Proposal

Here you can see the constraint, which understands the semantics of the actual value, getting thrown away. Only the actual value and success bool are retained: 

https://github.com/nunit/nunit/blob/bf8f2dc863036655dc37583dd5b7408b356b6026/src/NUnitFramework/framework/Constraints/PropertyConstraint.cs#L73-L74

Rather than the existing code below, I think we should have an internal-for-now  `ChainedConstraintResult` class which delegates all its writing to the base constraint result:

```cs
internal class ChainedConstraintResult : ConstraintResult
{
    private readonly ConstraintResult _baseResult;

    public ChainedConstraintResult(IConstraint constraint, ConstraintResult baseResult) : base(constraint, baseResult.ActualValue, baseResult.Status)
    {
        _baseResult = baseResult;
    }

    public override void WriteActualValueTo(MessageWriter writer)
    {
        _baseResult.WriteActualValueTo(writer);
    }
}
```

PropertyConstraint would then do this:

```cs
var baseResult = BaseConstraint.ApplyTo(propValue);
return new ChainedConstraintResult(this, baseResult);
```

**Comment by CharliePoole** [comment] 2017-09-08 19:24
All our other "chained" constraints produce a single result because that's what the Assert methods expect to deal with. Internally, they look at the nested constraint in producing their result. It seems like this was missed in `PropertyConstraint`. 

IMO, a linked chain of constraints gives Assert too much to do. Note that whatever Assert needs to do, Assume, Warn and any other similar classes also have to do. Having a single `ConstraintResult` was intended to simplify things for those upstream classes.

**Comment by jnm2** [comment] 2017-09-08 19:26
@CharliePoole I don't understand how this impacts `Assert` and the rest. They still get handed a single `ConstraintResult`. They don't need to know that it is a `ChainedConstraintResult`.

**Comment by CharliePoole** [comment] 2017-09-08 19:32
See my edit of the first comment.

`Assert` etc. need a "flattened" result. `ConstraintResult` or it's derivative is supposed to provide it. `ConstraintResult` already has access to a chain of `Constraints` to allow it to produce that result. Creating a chain of `ConstraintResults` seems like an unnecessary level of complexity to me, unless there is something we can do with a chain of results that we can't do with a chain of constraints.

Taking this further, would you implement a chain of results for every constraint that uses a base constraint? For binary constraints? I'm for it if it enables some feature we want to implement, although even then I'd prefer to just fix the bug before coming back and rewriting all constraints.

**Comment by jnm2** [comment] 2017-09-08 19:33
@CharliePoole I guess I'm just not seeing a simpler way to flatten the results than the one I proposed. But I'm now very interested to see one 😃

**Comment by jnm2** [comment] 2017-09-08 19:36
See, `AndConstraint` does the [exact same thing](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Constraints/AndConstraint.cs#L73) I'm proposing for `PropertyConstraint`!

Only difference is the class is private, not internal.

**Comment by jnm2** [comment] 2017-09-08 19:42
Hmm, I see that I need to make a correction though. I should only be delegating `WriteActualValueTo` to the base constraint, not `WriteMessage`, or otherwise the property's prefix on the message would never be shown. Nor would anything higher up.

**Comment by jnm2** [comment] 2017-09-08 19:45
Then if I make the constraint nested and private and name it `PropertyConstraintResult` on the assumption that it won't see any reuse either directly or as a base class, then I’ve exactly duplicated your technique with the binary operators.

**Comment by jnm2** [comment] 2017-09-08 19:45
But maybe that was your point all along?

**Comment by CharliePoole** [comment] 2017-09-08 19:54
Maybe I misunderstood. Don't we already have `PropertyConstraintResult`?

**Comment by CharliePoole** [comment] 2017-09-08 20:11
I did misunderstand...

Currently we have chained constraints but only one result is produced for the chain.

My understanding was that you would create a mesh like this...
```
ConstraintResult ==> NestedResult1     ==> NestedResult2     ==> etc.
     |                     |                     |
     V                     V                     V
Constraint       ==> NestedConstraint1 ==> NestedConstraint2 ==> etc.
```

I'm totally in favor of doing it like AndConstraint. See also EqualConstraint.

**Comment by jnm2** [comment] 2017-09-08 20:28
Ah, okay. We do not have a `PropertyConstraintResult`.

So what do you think of keeping it as an internal `ChainedConstraintResult` class to be directly used or derived for use in constraints with exactly one base constraint? Meh?

**Comment by CharliePoole** [comment] 2017-09-08 21:30
Personally I like a nested class that is tailored for exactly the constraint in which it is nested. If you create a reusable class, then you're almost certain to run into cases where it needs to test what it's being used for and do something different. Either way the code is minimal though, so it can be changed later if that happens.

**Comment by jnm2** [comment] 2017-09-08 21:34
Okay, let's go that route then:

```cs
class PropertyConstraint
{
    private sealed class PropertyConstraintResult : ConstraintResult
    {
        private readonly ConstraintResult _baseResult;

        public PropertyConstraintResult(IConstraint constraint, ConstraintResult baseResult) : base(constraint, baseResult.ActualValue, baseResult.Status)
        {
            _baseResult = baseResult;
        }

        public override void WriteActualValueTo(MessageWriter writer)
        {
            _baseResult.WriteActualValueTo(writer);
        }
    }
}
```

**Comment by jnm2** [comment] 2017-09-08 21:38
### Notes to implementors

All we need is the class defined above and to use `return new PropertyConstraintResult(this, baseResult);` instead of this line:

https://github.com/nunit/nunit/blob/bf8f2dc863036655dc37583dd5b7408b356b6026/src/NUnitFramework/framework/Constraints/PropertyConstraint.cs#L74

And we need a test that fails before and succeeds afterwards, confirming that `PropertyConstraint.ApplyTo(...).WriteActualValueTo` calls the base constraint's result's `WriteActualValueTo`.

**Comment by CharliePoole** [comment] 2017-09-08 21:46
I'm surprised you aren't doing it, since you wrote the code already. 😄 

Doesn't your `PropertyConstraintResult` code simply give the message of the base constraint, rather than any thing like "Expected property Name equal to "xxxx" but was ÿyyy"?

**Comment by jnm2** [comment] 2017-09-08 22:01
I most likely am doing it, but why discourage someone else from saving me the hassle? 😁 

No, I fixed that by removing the `WriteMessage` override earlier. It keeps the message but swaps out the writing of the “actual value” part of the message.

**Comment by jnm2** [comment] 2017-09-08 22:04
Plus, good tests are more work than implementation. Plus, I like inviting collaboration.

**Comment by Steve-Boyd** [comment] 2017-10-04 00:06
I'll help out with this one. Been looking for a project I actually use to help out with 😃 and what better time than Hacktoberfest.

**Comment by jnm2** [comment] 2017-10-04 00:46
Awesome! It's yours. 😃 @rprouse can you invite and assign?

**Comment by rprouse** [comment] 2017-10-04 01:34
@Steve-Boyd I've sent an invite to the contributors team which allows us to assign issues to you. One of the team will assign this issue once you accept, just ping us here.

**Comment by nisha-kaushik** [comment] 2018-04-10 08:40
I want to work on this as my 'good first issue', if this is still available.

**Comment by mikkelbu** [comment] 2018-04-10 10:00
@nisha-kaushik you are most welcome. I've assigned the issue to myself, just so nobody else takes it (but it can be that @jnm2 makes more sense). Do you need any help creating a fork, building etc.?

**Comment by jnm2** [comment] 2018-04-10 12:31
> but it can be that @jnm2 makes more sense

@mikkelbu No, please do. I appreciate it!

**Comment by nisha-kaushik** [comment] 2018-04-10 15:44
Thanks :)

**Closed** 2018-05-23 12:48 UTC
Labels: good first issue, is:bug, pri:normal
