### ISSUE TITLE
Switch from MSBuild based build system to Cake

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#930] opened 2015-10-25 17:41 UTC
This is a post 3.0 task and up for discussion, but I wanted to capture it. We have talked several times in the past about using a cross platform build system other than MSBuild. I am bringing this up again because NUnit.proj is getting really hard to read or maintain.

One option that I will put out there is [Cake](http://cakebuild.net/). It is cross platform, uses a C# based DSL which is very readable and it pulls down all its dependencies on run. Just looking at what they do in [the build script for their project](https://github.com/cake-build/cake/blob/develop/build.cake) is appealing. They clean, build, test, create zip files, package NuGet packages and deploy them to MyGet and even NuGet. I also like how they automatically version everything and auto-append build version numbers for CI builds. I also love how readable the script is.

**Comment by CharliePoole** [comment] 2015-10-25 17:59
I'd like to consider Rake as well. Other scripting (non-XML) approaches should be looked at  too.

**Comment by ctaggart** [comment] 2015-10-25 20:36
FAKE is more popular and mature.
http://fsharp.github.io/FAKE/

**Comment by CharliePoole** [comment] 2015-10-25 21:47
An issue I've been thinking about for a while is the selection of a language for general scripting purposes. This can, of course, be different than the underlying syntax of the build system but it's something to think about.

**Comment by devlead** [comment] 2015-11-13 14:02
@rprouse nice that you bring up Cake. I'm one of the maintainers behind Cake and would be happy to help with any questions you might have.

@ctaggart true, Fake is an excellent build tool, they've done truly excellent work there and they've got an amazingly dedicated community around it.
Cake's starting to mature too, it's running a couple of thousand (that I know of) projects in production, is actively maintained and has decent documentation(but it's always a work in progress :smile:).

@CharliePoole @ctaggart an advantage using C# would be that's something basically everyone contributing to this project knows. So more could read, understand and contribute.

Regardless of which, having a build system (like Rake, Fake, Bau, Cake etc.) in place is superb way to be environment and platform independent. 
So the idea is great, it will enable you to have the same process locally, on AppVeyor, TeamCity, TravisCI, VSO or TFS and on both OSX, Linux and Windows.

A good way to start would be to break down which tasks that need to be done like:
1. Clean
2. Build
3. Test
4. Package
5. Publish
6. Release 
..etc.

That would be common regardless of which build system is chosen.

**Comment by CharliePoole** [comment] 2015-11-13 16:58
@devlead Thanks for your thoughts. Let me pick your brain a bit more...

One thing I've had in mind for a while is the "official" adoption of a scripting language for the project. There are a lot of little tasks we need to do that are not really part of the build, like scanning files for proper copyright and license headers. 

Ever since I first tried ruby, I have liked it for that role. And one could combine it with use of rake for the build. But in the past, I got a fairly negative reaction on our mail list because it was not .NET oriented, although some folks said, "OK, but only if it's Iron Ruby" :-)

So, how would you rate C# + Cake for that sort of role?

Second question...

When I first looked at Cake, I was put off by the bootstrap script. First of all, it's powershell, which I really dislike. However, that's just personsal. :-) Mainly, it seemed like an unnecessary complexity. Later, I began to see why you introduced that complexity and how it benefited both CI and use of the script by new developers. May I suggest that you explain that somewhere in your docs? I would not have gone any farther if @rprouse weren't so enthusiastic.

Anyway... Since I didn't like the bootstrap and since your docs indicate that I could just download the binaries and use them, that's what I did. I put Cake into a tools directory and tried to use it to run the sample "Hello World" script. That worked fine in Linux but on Windows it gave me a mysterious null reference error, without indicating any line number in the script. Can you explain what might be going on? I'd like to give this a fair trial but being unable to run its own sample is a bad start. Is the bootstrap doing something that I need to do manually? I checked the code but didn't see anything.

I do plan to go back in the next day or two and redo the whole thing using the bootstrap. But I'd still like to know why simply copying the binaries was insufficient.

**Comment by devlead** [comment] 2015-11-13 19:32
Hi @CharliePoole,
First of all thanks for your feedback, first time users impressions is really important for us to find where potential friction lies.
### Question 1

It's .Net & C# so you can do anything it can do or that's available via assemblies or nuget. 

Beyond that Cake adds allot of global helper methods that are typed & documented which makes it convenient to work with tools for builds, tests, code analyzing, packaging etc. were call these methods aliases.

We also abstract the file system and provide aliases for working with files and folders in an xplat way, here we offer globbering options so you can do recursive pattern searching for files. I.e. `var csFiles = GetFiles("./**/*.cs");` would let you iterate over all C# files. We also provide aliases deleting/cleaning based on these patterns.

We also provide aliases which parses & writes assembly info files, for so you i.e. in one place can set common properties like copyright, version, company etc. for multiple projects. Aliases for parsing solution and project files.

We have a rich story around NuGet & Chocolatey packages where you no longer need to create a nuspec (even it's fully supported to use an existing one), so you can reuse values like version, author, copyright and just specify them once.

For versioning we offer an option to automatically do semver like versioning via release notes or git history (via GitVersion).

We've also wrapped so you easily can access information like build number, if pull request, scm details and so on from the build environment your running under(AppVeyor/TeamCity/Kudu/etc.) 

Cake also like many build system lets you devide work into tasks and declare dependencies and between them 

There's allot more aliases and also several plugins which extend Cake with even more features.

So in short I would rate C# + Cake to be very suited for that sort of role you're describing.
If you have any specific use case raise an issue and we'll gladly see if we can assist/suggest and way to solve it.

### Question 2
You're absolutely right the bootstrapper isn't required you could just install Cake from NuGet/Homebrew/Chocolatey/Github release zip etc.

What the bootstrapper does is an convenient way for a dev to just clone the repo and then run depending on platform either `build.sh` or `build.ps1` and those will fetch what's needed to run the cake build script. Without needing to install anything on their system everything's self-contained within the repo.
Also just as you state it makes really easy for the build servers.

### Question 3
I'm sorry to here you had issues with running just the binaries, that should definitely just work, me too would be really interested why.
Don't know exactly why it didn't work for you, you might encountered some bug, if you can repo the steps I gladly investigate to see what might be causing it.
Could be an issue we've already addressed, but if it isn't we would be very thankful if you raised an issue so we can fix it.

**Comment by gep13** [comment] 2015-11-13 19:37
@CharliePoole My name is Gary, and I am one of the owner maintainers of Cake.  I am sorry to hear that your first *taste* of Cake hasn't been very good.  I am relatively new to the Cake project, so I don't think I can speak to the first of your questions, but I think I can help you out with the other one.  I am sure that @devlead or @patriksvensson will be able to help you out with the first.

Here is what I did...

1. Downloaded the latest zip file of Cake (0.6.0)
2. Extracted the contents to `c:\temp\cakedemo`
3. Create a new file called `build.cake` at the root of the `c:\temp\cakedemo` folder and took the contents of the example script from http://cakebuild.net/docs/tutorials/setting-up-a-new-project and put this into the file
4. Then I executed the following command `Cake-bin-v0.6.0\Cake.exe build.cake` which resulted in the following:

![image](https://cloud.githubusercontent.com/assets/1271146/11155450/790a7a26-8a3d-11e5-9e8b-b1a8c9703e94.png)

Hopefully this is the same error message that you are getting, if it is, we need to insert another step, 2a, which is to first unblock the zip the zip file that was download

2a. Right click on the zip file, select properties, and then unblock:

![image](https://cloud.githubusercontent.com/assets/1271146/11155478/b2f5b58e-8a3d-11e5-9bc5-52d481fe9ea6.png)

After doing that, I can run the same command, and the output is the following:

![image](https://cloud.githubusercontent.com/assets/1271146/11155488/c2851292-8a3d-11e5-8c7a-d55be8b97243.png)

If this is the problem you were seeing, then this is standard Windows Security in action, where all files download from the Internet are inherently untrusted, and if you want to run any executables, or use any dll's, then you have to unblock them first.  This is one advantage of using the bootstrapper to do the work, as it actually makes use of the NuGet infrastructure to download Cake, and put it into a useable format.

Hope this helps!

**Comment by gep13** [comment] 2015-11-13 19:39
Ah, I see @devlead has already posted while I was typing :+1:

**Comment by CharliePoole** [comment] 2015-11-13 20:32
@gep13 My error message was "Object reference not set to an instance of an object." I didn't actually download the zip to my windows machine. It was on another system and I opened it from a shared folder. The windows security error didn't arise.

Just in case, I erased it all and started over, following the steps you used. I got the security error with the same message and fixed it. That brought me back to my original error message.

**Comment by CharliePoole** [comment] 2015-11-13 20:33
@devlead Thanks for all the info. I'll try to use it again and then may have some more questions.

**Comment by gep13** [comment] 2015-11-13 20:36
@CharliePoole hmm, would really like to get to the bottom of this, and understand exactly why this is happening, and why we can't reproduce it.

Some questions (if you don't mind)...

1. What Operating System are you using?
2. Can you confirm it is Cake 0.6.0 that you are using?
3. Can you put the build.cake file that you are using in to a gist, or paste into this chat?  (Just want to make sure we are using the same thing)
4. Can you provide a screenshot of the folder structure that you are using, and the output from the command that you are running?

Thanks!

**Comment by CharliePoole** [comment] 2015-11-13 23:57
@gep13 
I'm running it on Windows 7.
I'm using the 0.6.0 zip from github cake-build/cake
My build file is the sample file shown here: https://github.com/cake-build/cake#2-create-a-cake-script

So here is what I just did, starting from scratch...
1. Created a temp directory
2. Made sure that the security setting on the zip was cleared
3. Unzipped, creating a temp\Cake directory
4. Began typing in the script a bit at a time, running it after each change.

All the results were as expected until I filled in the last bit, which I already suspected. 
That was the line
    Information("Hello World!");
It gave me a null reference error.

I tried setting verbosity. It ran without error but still didn't produce the "Hello" output. If I used different settings I got more or less info from Cake but still no "Hello World!"

Finally, after running with verbosity set a few times, I removed that setting from the command line. It still didn't display anything but also didn't give an error.

So it seems to be something that only occurs right after install up to the point where you use a verbosity argument. Is it remembering that argument? Is it initializing something?

And of course, it's still not saying hello to me :-(

Next I'll try the bootstrapper.

**Comment by gep13** [comment] 2015-11-14 10:03
@CharliePoole thanks for sticking with us while we figure this out.  I am still trying to replicate the issue, but I am currently not able to.  Would it be possible to get a screenshot similar to the following...

![image](https://cloud.githubusercontent.com/assets/1271146/11163014/d057eee8-8ab6-11e5-804a-9f4f39f4f16a.png)

So I can see exact folder structure etc being used, and I can try and replicate from there.  Thanks!

**Comment by patriksvensson** [comment] 2015-11-14 10:10
@CharliePoole Could you run the script with the parameter `-verbosity=diagnostic` and post the output.

````
Cake-bin-v0.6.0\Cake.exe build.cake -verbosity=diagnostic
```

**Comment by patriksvensson** [comment] 2015-11-14 10:38
@CharliePoole Currently spinning up a Win7 VM to see if I can reproduce this.

**Comment by CharliePoole** [comment] 2015-11-14 13:22
@patriksvensson Posted diagnostic output as comment on cake-build/cake#521

**Comment by CharliePoole** [comment] 2015-11-14 13:31
@gep13 Screen shots are a pita!

Here's the directory structure:

```
D:\temp>dir /s
 Volume in drive D is DATA
 Volume Serial Number is A861-AF00

 Directory of D:\temp

11/13/2015  03:28 PM    <DIR>          .
11/13/2015  03:28 PM    <DIR>          ..
11/13/2015  04:24 PM               140 build.cake
11/13/2015  03:29 PM    <DIR>          Cake
               1 File(s)            140 bytes

 Directory of D:\temp\Cake

11/13/2015  03:29 PM    <DIR>          .
11/13/2015  03:29 PM    <DIR>          ..
11/04/2015  06:23 PM           203,264 Autofac.dll
11/04/2015  06:23 PM           280,064 Cake.Common.dll
11/04/2015  06:23 PM           634,368 Cake.Common.pdb
11/04/2015  06:23 PM           579,444 Cake.Common.xml
11/04/2015  06:23 PM            96,768 Cake.Core.dll
11/04/2015  06:23 PM           341,504 Cake.Core.pdb
11/04/2015  06:23 PM           202,588 Cake.Core.xml
11/04/2015  06:23 PM            62,464 Cake.exe
11/04/2015  06:23 PM             1,107 LICENSE
11/04/2015  06:23 PM         1,340,416 Mono.CSharp.dll
11/04/2015  06:23 PM           532,656 Nuget.Core.dll
11/04/2015  06:23 PM             4,518 README.md
11/04/2015  06:23 PM            12,203 ReleaseNotes.md
11/13/2015  03:29 PM         2,931,352 Roslyn.Compilers.CSharp.dll
11/13/2015  03:29 PM         1,113,736 Roslyn.Compilers.dll
              15 File(s)      8,336,452 bytes

     Total Files Listed:
              16 File(s)      8,336,592 bytes
               5 Dir(s)  98,200,281,088 bytes free
```

Here's the test file..

```
var target = Argument("target", "Default");

Task("Default")
  .Does(() => 
{ 
  Information("Hello World");
});

RunTarget(target);
```

Output of the run is posted at cake-build/cake#521

**Comment by rprouse** [comment] 2015-11-14 21:25
@CharliePoole, total aside from this issue, but I take a lot of screenshots for documentation, presentations, etc. I install the open source screen capture tool Greenshot on all my machines. It does full screen, regions or windows and has a simple editor built in that is great for highlighting, putting in arrows or instruction text.

http://sourceforge.net/projects/greenshot/files/

**Comment by CharliePoole** [comment] 2015-11-14 22:19
I'll take a look. Thanks.

**Comment by CharliePoole** [comment] 2015-11-14 22:25
Since it's smaller and simpler, I'm going to try setting up Cake for use in building the NUnit 3 VS adaptor.

**Comment by CharliePoole** [comment] 2015-11-16 01:30
OK, turns out building a VS extension is a bit harder than the average project. I'm going to set this aside and work on doing it for NUnit first.

**Comment by CharliePoole** [comment] 2015-11-16 01:37
That said, let's go with Cake. :-)

**Comment by devlead** [comment] 2015-11-16 09:07
@CharliePoole superb! @cake-build team is here to help if you got any questions. We also have an [Gitter](https://gitter.im/cake-build/cake) channel where contributors and users hang out.

**Comment by CharliePoole** [comment] 2015-12-06 18:15
Just did a forced push, rebased on master, and squashed a bunch of small commits. I'm moving off this branch for a bit and have created branches travis-issue-930 and appveyor-issue-930. Those will only build on the specific CI system and will allow me to experiment without cluttering the commits for this issue.

**Comment by CharliePoole** [comment] 2015-12-09 03:44
Marking this as temporarily blocked due to cake-build/cake#573

We need a way for the travis build to reflect our test failure. I could switch over to the Appveyor build, but I'm already in mid-flight on the travis side and there is no point of using a technology that will not work on both of our CI servers.

**Comment by rprouse** [comment] 2015-12-09 13:06
@CharliePoole based on cake-build/cake#573, you can use the new NUnit 3 task that I added to Cake to run the tests by setting the ToolPath to the nunit3-console.exe in the bin directory. You will need to change the version of Cake in `tools/packages.config` to at least 0.6.1 although 0.6.4 is available.

**Comment by CharliePoole** [comment] 2015-12-09 15:01
So, by setting ToolPath, we are guaranteed to be running the version we just built? The comments on the cake issue talked about ways of using new options to console, which isn't relevant here. The Cake guys didn't actually seem to understand that what we need is to be running the new build of console.

I had actually planned on figuring out if there were some way to make this work using your new code after getting the brute force approach to work, so it would be great if it already works. OTOH, I will first continue to press a bit on what seems like an obvious bug in Cake, since there's some chance it will also affect your code when running on Linux.

**Comment by CharliePoole** [comment] 2015-12-09 15:03
FWIW, the fundamental problem I see with Cake right now is that they are dependent on code, which is not their own, in order to work correctly and that that code is **different** on two platforms. Because of xunit problems, they do not seem to  be testing thoroughly on Linux, so it's understandable if something has escaped them.

**Comment by devlead** [comment] 2015-12-09 15:11
@CharliePoole FWIW it's hard to do any xplat build system without depending external code.
See your point, we are working on integration tests across 3 os's and 5 build systems, combined with unit tests and help from our users we hope this will result in less things escaping us.

**Comment by patriksvensson** [comment] 2015-12-09 15:16
@CharliePoole By setting the tool path, you set what executable to be called when invoking the tool. So if you point out the new build of NUnit that is the one that will be invoked.

Example of this is:

```csharp
NUnit("./tests.slm", new NUnitSettings {
   ToolPath = "./output/nunit-fresh-from-the-oven.exe",
   NoLogo = true
})
```

Which would execute the following given that the script reside in `C:/project`:

```
C:/project/output/nunit-fresh-from-the-oven.exe "C:/project/tests.sln" -nologo
```

We're working on getting the xplat unit tests to run again but sadly, this has been out of our control since xunit 2 had problems with their console runner on Mono. Not sure if this has been resolved, but we're going to pursue it.

Not sure what code you refer to that we depend on that is not our own, but please feel free to come by our [Gitter](https://gitter.im/cake-build/cake) or raise an issue if there's something that doesn't work for you and we'll try to take a look as soon as possible.

**Comment by CharliePoole** [comment] 2015-12-09 15:48
I agree. In this case, you are forced to deal with different compilers to
build and run the script.

Our nunit script is probably hitting something that hasn't been hit before.

**Comment by rprouse** [comment] 2015-12-09 16:50
@patriksvensson I could always get your unit tests running on mono again by converting them to NUnit :smile:

**Comment by gep13** [comment] 2015-12-09 19:58
>@rprouse said...
I could always get your unit tests running on mono again by converting them to NUnit 

@rprouse that would be very meta!  Using Cake to build NUnit, and then using NUnit to test Cake :smile:

**Comment by CharliePoole** [comment] 2015-12-10 22:11
Resolved the Cake issue, continuing to work on this...

**Closed** 2015-12-28 15:11 UTC
Labels: is:build, pri:normal, status:started
