### ISSUE TITLE
Filter not used in ExploreTests

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1213] opened 2016-01-26 00:13 UTC
The TestFilter that is constructed in TextRunner (nunitlite) is never used when ExploreTests is called.

The filter should be passed to ExploreTests, and used to limit the set of tests returned by ExploreTests.

**Comment by CharliePoole** [comment] 2016-01-26 00:16
It would be good to make sure that the filter passed to FrameworkController is also passed on and used. That should fix any problem with the console runner too.

**Comment by rprouse** [comment] 2016-04-07 15:30
I think this is a duplicate of #1143. I am going to close it as such and add a comment to that issue.

**Closed by rprouse** 2016-04-07 15:30 UTC
