### ISSUE TITLE
Unit testing with the use of EF Core InMemoryDatabase throws ObjectDisposedException

### ISSUE THREAD

**Issue by Stadzior** [nunit/nunit#4090] opened 2022-03-29 09:46 UTC
Hi, the whole story is available at [my stackoverflow question](https://stackoverflow.com/questions/71587176/unit-testing-using-ef-core-inmemorydatabase-along-with-moq-mocks).

I have the following:
EF Core db context:

    public class MyDbContext : DbContext
    {        
        public virtual DbSet<Foo> Foos { get; set; }

        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) { }
        
        public virtual void PreSaveActions()
            => throw new NotImplementedException(); //Here I've got something that must be done pre-save.

        public override int SaveChanges()
        {
            PreSaveActions();
            return base.SaveChanges();
        }
    }

TestMyDbContext:

    public class TestMyDbContext : MyDbContext
    {
        public override void PreSaveActions() {}
    }

Unit under test:

    public class SafeRemover
    {
        private readonly IDbContextFactory<MyDbContext> _contextFactory;    

        public SafeRemover(IDbContextFactory<MyDbContext> contextFactory)
        {
            _contextFactory = contextFactory;
        }

        public int SafeRemove(string name, int barId)
        {
            using var context = _contextFactory.CreateDbContext();
            var itemToRemove = context.Foos.SingleOrDefault(foo => foo.BarId == barId && foo.Name == name);

            if (itemToRemove != null)
                context.Foos.Remove(itemToRemove);
            
            return context.SaveChanges();
        }
    }
    
Dependency injection:

    Host = Microsoft.Extensions.Hosting.Host.CreateDefaultBuilder()
           .ConfigureServices((_, services) => 
           {
               services
                   .AddDbContextFactory<MyDbContext>(options => options.UseSqlServer(configuration.GetConnectionString("MyDbContext")))
                   .AddSingleton<SafeRemover>();
           }).Build();

Unit test:

    private static readonly object[] _safeRemoveSource = 
    {
        new TestCaseData("Foo1", 1, new List<Foo>()).SetName("SafeRemove_FooExists_FooRemoved"),
        new TestCaseData("Foo2", 1, new List<Foo> { new Foo { Name = "Foo1", BarId = 1 } }).SetName("SafeRemove_FooWithDifferentNameExists_FooNotRemoved"),
        new TestCaseData("Foo1", 2, new List<Foo> { new Foo { Name = "Foo1", BarId = 1 } }).SetName("SafeRemove_FooWithDifferentBarIdExists_FooNotRemoved"),
    }    
    
    [TestCaseSource(nameof(_safeRemoveSource))]
    public void SafeRemoveTest(string name, int barId, IList<Foo> expectedFoos)
    {
        var initialFoos = new List<Foo> { new Foo { Name = "Foo1", BarId = 1 } };
        var options = new DbContextOptionsBuilder<MyDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;  

        using var context = new TestMyDbContext(options);
        context.Foos.AddRange(actualFoos);
        context.SaveChanges();

        var contextFactoryMock = new Mock<IDbContextFactory<MyDbContext>>();
        contextFactoryMock.Setup(factory => factory.CreateDbContext()).Returns(context);

        var safeRemover = new SafeRemover(contextFactoryMock.Object);
        
        safeRemover.SafeRemove(name, barId);
        var actualFoos = context.Foos.ToList();

        Assert.AreEqual(expectedFoos.Count(), actualFoos.Count());
        for (var i = 0; i < expectedFoos.Count(); i++)
            Assert.That(expectedFoos[i].Name.Equals(actualFoos[i].Name) && expectedFoos[i].BarId == actualFoos[i].BarId);
    }

And at line `var actualFoos = context.Foos.ToList();` I am gettting `ObjectDisposedException`.
Please let me know if my approach is correct and if yes then why ObjectDisposedException occurs and how can I avoid it without changing UUT.

**Comment by stevenaw** [comment] 2022-03-29 17:05
Hi @Stadzior 
Thanks for providing a complete example. I'm not sure if this is caused by NUnit or not, especially since all the work appears contained within a single test. Are you seeing it for only one of your test cases, or several? Also, what happens if you take this block and run it in a standalone console app?

```csharp
var initialFoos = new List<Foo> { new Foo { Name = "Foo1", BarId = 1 } };
    var options = new DbContextOptionsBuilder<MyDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;  

    using var context = new TestMyDbContext(options);
    context.Foos.AddRange(actualFoos);
    context.SaveChanges();

    var contextFactoryMock = new Mock<IDbContextFactory<MyDbContext>>();
    contextFactoryMock.Setup(factory => factory.CreateDbContext()).Returns(context);

    var safeRemover = new SafeRemover(contextFactoryMock.Object);
    
    safeRemover.SafeRemove(name, barId);
    var actualFoos = context.Foos.ToList();
```

Does the error still happen if you remove this line? 
```
safeRemover.SafeRemove(name, barId);
```

**Comment by Dreamescaper** [comment] 2022-03-29 18:10
> using var context = _contextFactory.CreateDbContext();

This line disposes you DbContext at the end of the SafeRemove method. And your mock returns single DbContext instance, which will remain disposed.

You can create your mock via smth like that, it should do the trick:
```csharp
contextFactoryMock.Setup(factory => factory.CreateDbContext()).Returns(() => new TestMyDbContext(options));
```

**Comment by Dreamescaper** [comment] 2022-03-29 18:13
This question is not related to NUnit, you'd get the same behavior with console app, so I'm closing this issue.

But feel free to add more comments, maybe we'd be able to help.

**Closed by Dreamescaper** 2022-03-29 18:13 UTC
Labels: is:question, closed:answered

**Comment by Stadzior** [comment] 2022-03-30 09:25
Hello again. Thanks a lot your for comments and useful tips.
Indeed at the second thought I seems to not be exactly the problem with NUnit but it really is one of the most common scenarios of usage NUnit along with EF Core so I thought it would be fitting here.

Regarding your suggestion about returning new instance of TestMyDbContext each time when the CreateDbContext is invoked. That might work but how then I'd get the actualFoos for the assertion?

**Comment by Dreamescaper** [comment] 2022-03-30 09:35
Ideally you'd create separate DbContext instances for arranging the data and for assertions - so that any DbContext cache wouldn't affect the result.
In this case, though, even using the same instance seems to work.

**Comment by Stadzior** [comment] 2022-03-30 09:59
@Dreamescaper I don't quite catch the concept of separate DbContext instances for "Arrange" and "Assert" parts of the test. Can you maybe modify the given test method to illustrate what's on your mind?

**Comment by Stadzior** [comment] 2022-03-30 11:37
You don't have to go far with the code amendments, just please explain to me how using separated DbContext instances would make it possible for me to check what was added/removed from the in memory database.

**Comment by Dreamescaper** [comment] 2022-03-30 19:50
DbContext are short living objects. For example, when you use EF Core with ASP.NET Core, lifetime of DbContext instance is usually limited by request lifetime. But different DbContext still work with the same database, they re-use DB connections etc. Same applies to InMemory DB - the fact they you have two separate contexts doesn't mean that they work with separate DBs.

**Comment by Stadzior** [comment] 2022-03-31 11:07
@Dreamescaper you're totally right! Now it's all makes sense. After the given amendment all works just fine:

    private static readonly object[] _safeRemoveSource = 
    {
        new TestCaseData("Foo1", 1, new List<Foo>()).SetName("SafeRemove_FooExists_FooRemoved"),
        new TestCaseData("Foo2", 1, new List<Foo> { new Foo { Name = "Foo1", BarId = 1 } }).SetName("SafeRemove_FooWithDifferentNameExists_FooNotRemoved"),
        new TestCaseData("Foo1", 2, new List<Foo> { new Foo { Name = "Foo1", BarId = 1 } }).SetName("SafeRemove_FooWithDifferentBarIdExists_FooNotRemoved"),
    }    

    [TestCaseSource(nameof(_safeRemoveSource))]
    public void SafeRemoveTest(string name, int barId, IList<Foo> expectedFoos)
    {
        var initialFoos = new List<Foo> { new Foo { Name = "Foo1", BarId = 1 } };
        var options = new DbContextOptionsBuilder<MyDbContext>().UseInMemoryDatabase("SafeRemoveTestDb").Options;  

       context.Foos.AddRange(actualFoos);
        context.SaveChanges();

        var contextFactoryMock = new Mock<IDbContextFactory<MyDbContext>>();
        contextFactoryMock.Setup(factory => factory.CreateDbContext()).Returns(new TestMyDbContext(options));

        var safeRemover = new SafeRemover(contextFactoryMock.Object);
    
        safeRemover.SafeRemove(name, barId);
        var actualFoos = new TestMyDbContext(options).Foos.ToList();

        Assert.AreEqual(expectedFoos.Count(), actualFoos.Count());
        for (var i = 0; i < expectedFoos.Count(); i++)
            Assert.That(expectedFoos[i].Name.Equals(actualFoos[i].Name) && expectedFoos[i].BarId == actualFoos[i].BarId);
    }
        
Thank you for your tips and I hope that you are safe & sound in Kyiv (guess you are from there from your bio).
Regards,
Kamil
