### ISSUE TITLE
Don't enforce [Timeout] when debugger is attached

### ISSUE THREAD

**Issue by bormm** [nunit/nunit#3054] opened 2018-10-09 15:15 UTC
Greetings NUnit team!

I was just debugging within a nunit test that has a Timeout attribute. Unfortunately it was aborted by timeout while debugging. I have found this existing issue #1479 that was already fixed by #1785 in 2016.
For me it seems the fix got lost with commit 1a164db06b1a91b0d82f5481286b960cc6db2644 .

So is there something wrong with my little research result or was the feature lost without intention?

**Comment by bormm** [comment] 2018-10-10 12:13
Ok. I will try to do it. I never changes something in NUnit, but the code looks quite readable :-)

**Comment by ChrisMaddock** [comment] 2018-10-10 12:17
Great - thanks! Check out https://github.com/nunit/nunit/blob/master/BUILDING.md for a few specialist details, if you have any issues building/running the tests, and let us know if we can help at all. 🙂

**Comment by ChrisMaddock** [comment] 2018-10-10 12:18
Also, given we've already had one regression, it would be really cool if we could unit test this. Maybe we could put a wrapper around the Debugger class or something, to make that possible. 🙂

**Comment by thepinkmile** [comment] 2018-11-07 10:00
Hey guys,
Any update on this at all?
I was just about to post this very same issue.

Currently my codebase has it's own implementation of TimeoutAttribute which does this.
Also just to mention that this should probably also be done for MaxTimeAttribute too?
Depending on my workload, I may be able to help with this.

**Comment by ChrisMaddock** [comment] 2018-11-07 10:16
Thanks @thepinkmile! The change to MaxTimeAttribute sounds good to me, would appreciate a PR for that.

@bormm How are you getting on with this issue? 🙂 Do shout if we can help at all!

**Comment by thepinkmile** [comment] 2018-11-07 10:46
Not sure if this is the correct way to do it, but based on referenced items in initial post.
Would not have a clue how this could be tested though.
Any thoughts welcome.

**Comment by bormm** [comment] 2018-11-07 11:12
@thepinkmile @ChrisMaddock Unfortunately I got no resources to work on this issue in my working time, so I am currently not able to do something for this issue. Especially for the DI + testing part, which would take the most time. I am also not sure how useful the testing could be, because you can't test if the encapsulated debugger function is working as expected.

But long story short: If @thepinkmile would just adapt his change and pick this issue, it would be a good thing.

**Comment by ChrisMaddock** [comment] 2018-11-07 17:28
I was thinking it might be possible to pass in an `IDebugger` interface into Timeout command, so we could then mock out the debugger being attached or not, and put in a test that the command doesn't time out when under the debugger.

In this case, perhaps we're just better to get a fix in however. @thepinkmile - if you'd like to PR your fix to TimeoutCommand, that would be very welcome! The MaxTime one, the team might want to discuss a little more, but I think it sounds sensible to me!

@bormm - thanks regardless for your help in identifying and logging the issue. 😄

**Comment by thepinkmile** [comment] 2018-11-07 17:53
I currently have it all as a single commit. Will break it down tonight and add as 2 separate commits with 2 different PRs. Will probably have a look at doing some kind of tests for it over weekend if I get time.

**Comment by ChrisMaddock** [comment] 2018-11-07 18:10
Sounds great, thanks!

**Comment by thepinkmile** [comment] 2018-11-08 15:38
Not had a chance to fix this up yet. Will likely be over the weekend I do it all.
However, I was just wondering what the expectation would be with using [Timeout] or [MaxTime] with [Retry]?
Not sure if this is because of our custom internal impl of Timeout, but we seem to get the timeout error every time.
E.G. If I set Retry(3) and Timeout(20000) and my test takes 10000ms to fail, the retry doesn't seem to reset the timeout for each attempted run.
Not sure if this would be the same as i think our internal version sets the timeout at start of execution (e.g. before SetUp) and ends after completion (e.g. after TearDown). From what I can gather from the TimeoutCommand, this happens only for the test it's self. So this would mean each retry causes a new TimeoutCommand for each attempted run?

**Comment by ChrisMaddock** [comment] 2018-11-08 16:32
Which version of the NUnit framework are you using? This was a bug which was recently fixed in 3.11, see https://github.com/nunit/nunit/issues/2786. Not sure whether the fix will be relevant to your custom attribute or not, but if you have a look at the related PR, it should hopefully point you in the right direction!

> Not had a chance to fix this up yet. Will likely be over the weekend I do it all.

No rush - and thanks! 😄

**Comment by ChrisMaddock** [comment] 2018-11-12 13:29
Thanks for taking on the IDebugger idea - sounds promising!

dotcover's an interesting situation. I'm not sure how this works...but you might want to test it out...what happens if you use the `--timeout=60` command line parameter? Does that also not work when the debugger is attached?

**Comment by zdenek-jelinek** [comment] 2019-07-29 15:15
Hello, since the topic has not been active for several months and this bug is bothering me, I took a liberty in analysing the problem and would like to ask you for further guidance.

1. I have tested several versions of dotcover (2017.3.5, 2018.2.0, 2019.1.3, 2019.2.0-eap2) with VS2019, directly with `dotcover.exe` and through `dotnet dotcover test` and none of these cases had `Debugger.IsAttached` true during the run, in contrast to what was stated previously.
1. With respect to the `IDebugger` dependency inversion: While I think this an excellent idea, it seems to require quite a lot of work on passing the `IDebugger` from tests all the way down to the `TimeoutCommand` where the logic should take place. It seems that the system was not designed for this and I don't feel confident enough to make such change. It could also cause conflicts with other people's work. I would suggest to expose a static property on `TimeoutCommand` or possibly a singleton abstract factory (returning `IDebugger`) that would allow to override the `Debugger.IsAttached` value for test purposes. Its value would be assigned before and reset after the tests covering the debugger-related logic.
1. The timeout parameterization is currently streamlined into one timeout parameter so that test timeout has precedence over fixture timeout which has precedence over the argument. Should the command line argument `--timeout` behave differently from the attributes with respect to test abort in debug, it would be necessary to clarify weird temporal issues such as what happens when command line timeout is shorter than test timeout and debugger is attached during the test (so that the test should fail on argument timeout which happened before the actual timeout for the test occurred). I would rather not do this.
1. I'm not sure if the fix should touch `MaxTimeAttribute`. For me, the issue is that the test run gets aborted in the middle of my debugging session, I don't care so much about the result being timeout or anything else. Additionally, the debugger attach => no timeout is only mentioned on `Timeout` documentation, not `MaxTime`. On the other hand, the change is trivial - I just need your philosophical guidance here.

Please advise on the way forward with this, I would be happy to implement the fix.

**Comment by benviss** [comment] 2019-08-30 20:54
Hello,
Just curious if there is going to be any work done on this ticket soon.

**Closed** 2020-05-09 18:32 UTC
Labels: is:bug, pri:normal
