### ISSUE TITLE
Add command line parameter definition

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1533] opened 2016-05-29 04:41 UTC
I have recently implemented a number of test suites where I would have been significantly more productive if I had been able to pass certain parameters to the test suite through the command line.

I am proposing that this be added as a feature.

I would suggest a syntax similar (but modified to fit into NUnit syntax) to that used by the C++ compiler:

`/Dname[= | # [{string | number}] ]`

These parameters would be included in the xml results so they could be easily displayed and documented.

A test would access these parameters from the TestContext as the Parameters property.

This could be a simple indexed property (object Parameters["parameter name"]), or a more easily used set of properties like bool BoolanParameter["parameter name"], int IntegerParameter["parameter name"] and string StringParameter["parameter name"].

These parameters would be passed around as part of the Settings, and then added to the TestExecutionContext and TestContext when they are created.

For more control, a new attribute UsesParameter ("name", [default value])  could be added to limit validate, and define default values for parameters  in a specific TestSuite or Test, and to further document their use.  If a parameter appears in a UsesParameter attribute without a default value, then it is an error if the parameter is not defined on the command line.

**Comment by CharliePoole** [comment] 2016-05-29 05:37
I'm closing this as a duplicate of #720. The link in #720 will lead us here so this serves as a sort of virtual commentary on that issue.

**Comment by oznetmaster** [comment] 2016-05-29 05:47
#720 seems to encompass two somewhat unrelated issues.  That was why I did not notice this discussed in it.  Perhaps the two issues should be separated?

**Comment by CharliePoole** [comment] 2016-05-29 09:21
In the course of the discussion we rejected the category idea and changed the issue title to be about command-line arguments alone.

**Comment by oznetmaster** [comment] 2016-05-29 09:38
I have implemented my approach in my CF build.  Should I port it to a PR so it can be looked at?

Or is this approach of no interest generally?

**Closed** 2016-05-29 15:57 UTC
Labels: closed:duplicate, is:idea

**Comment by CharliePoole** [comment] 2016-05-29 15:58
I referenced this proposal in #720 and marked that issue as in design review. We generally ask for comments when there is a user-facing change to be made.
