### ISSUE TITLE
ANSI Color code are being escaped when running within dotnet test

### ISSUE THREAD

**Issue by Socolin** [nunit/nunit#4126] opened 2022-06-11 14:24 UTC
Hello,

I'm not sure if the problem is with NUnit or `dotnet test` but the ANSI Color Codes are being escpaed when writing to the console

Actual output:
![image](https://user-images.githubusercontent.com/539620/173191823-9bf31899-2aba-498c-927a-c77475dd54b2.png)

Repro:
https://github.com/Socolin/ReproDotnetTestColorBug/tree/main/ANSIColorInTestsOutput.NUnit 

When running with the rider test runner the color is working as expected

![image](https://user-images.githubusercontent.com/539620/173191875-f970543b-4984-4ef1-abc0-dfb2bb667560.png)

https://github.com/Socolin/ReproDotnetTestColorBug/runs/6843884993?check_suite_focus=true#step:6:76

Note: With MS Test it seems to works well

https://github.com/Socolin/ReproDotnetTestColorBug/runs/6843926653?check_suite_focus=true#step:6:81

**Comment by stevenaw** [comment] 2022-06-11 16:51
Thanks for raising this @Socolin , and for producing a clear repro.
I think this may be a duplicate of #1787 which had at one point been investigated unfortunately appears to have stalled out. There's a bit of notes there about the root cause, which does appear to be within nunit framework itself.

I'm going to close this as a duplicate, but since you've already done some digging, would you be interested in continuing to pursue a fix and to submit a PR based on the research in that issue?

**Closed by stevenaw** 2022-06-11 16:51 UTC

**Comment by Socolin** [comment] 2022-06-11 20:52
Hello,

Before opening a PR I would validate that I'm on the good path here.

So after digging more, based on the other story too:
- NUnit is escaping characters in `EscapeInvalidXmlCharacters` in `TNode`
- The result is then serialized to an XML
- Then the runner is reading the XML without un-escaping the `\u001b`

Since my problem is with `dotnet test` and since it's working well for MSTest I'm seeing 2 options:
- Stop escaping the `\u` in the xml, but that would be a breaking changes
- Un-escape the characters when loading the XML

So the fix may be done at multiple location:
- Nunit runner / console ? (I don't know at all about this part since I'm not using it)
- NUnit3TestAdapter which bridge nunit with vstest

So for NUni3TestAdapter I was able to find where to fix this. It's using `System.Xml.XmlNodes.InnerText` to read the content, so when accessing I added a step to un escape the value

Here is my WIP, if you can confirm me this is the right way to fix this one, I'll add some tests and clean things a bit and the create the PR

https://github.com/Socolin/nunit3-vs-adapter/commit/a9d7e9440fc2caf95e5b6f3b658ab4b0fb14aeea

Since the problem I'm fixing is not "exactly" the same as the other issue (not same place for the fix NUnit console / Nunit adapter) do you want me to continue the discussion on the other issue, or stay on this one ?
