### ISSUE TITLE
Ncrunch: System.Xml.XmlException: Root element is missing. when adding nUnit 3.7.0

### ISSUE THREAD

**Issue by BrianLanghoor** [nunit/nunit#2205] opened 2017-05-30 09:04 UTC
Hi,

When creating a new solution (wep api) with a unit test project I get the following error when I add nUnit 3.7.0 to the unit test project.

`An error occurred while analysing this project after it was built: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at NUnit.Framework.Interfaces.TNode.FromXml(String xmlText)
   at NUnit.Framework.Internal.TestFilter.FromXml(String xmlText)
   at NUnit.Framework.Api.FrameworkController.ExploreTests(ICallbackEventHandler handler, String filter)
   at NUnit.Framework.Api.FrameworkController.ExploreTestsAction..ctor(FrameworkController controller, String filter, Object handler)
   --- End of inner exception stack trace ---
`

To clarify The project will run properly in Visual Studio. The error is shown in the NCrunch test runner and therefor I cannot start TDDing properly. The problem is resolved when reverting to nUnit version 3.6.1. In this new solution I also installed specFlow and I have resharper installed in Visual Studio.

I do not know if this is an NCrunch, nUnit, VS issue. Because the problem is fixed when going back to an older version of nUnit i suspect it to be here hence this post.

**Comment by ChrisMaddock** [comment] 2017-05-30 09:15
This will be due to the new functionality to use the filter passed to Explore. It looks like NCrunch is passing a non-xml string in, @remcomulder - can you shed any light? For context, prior to v3.7, the `string filter` passed into `ExporeTests()` was unused, however it's now being parsed and read. It should be an xml `<filter>` element I believe - and an empty `<filter />` if unused.

I'd guess this was caused by the change in NUnit 3.7, but will fixing in NCrunch. Will leave this issue open until confirmed.

**Comment by remcomulder** [comment] 2017-05-30 11:13
Thanks for pinging me in on this one.  NCrunch is passing string.Empty into the filter parameter here.  I can't remember the reasoning behind this.  It may have been that I tried to pass (null), and that didn't work, so string.Empty seemed like the next best thing and NUnit has always accepted this.  I don't remember it ever being specified that an empty filter should be passed here in the event of no filter.

Regardless, this is easy to fix in NCrunch, but it's still a bit a problem, because it completely breaks the forwards compatibility for using NUnit with older versions of NCrunch.  I would state my preference being that perhaps NUnit should avoid exploding when an empty string is passed into the filter.  In this way, we can avoid breaking things for people when they perform a Nuget update.

@CharliePoole Thoughts?

**Comment by rprouse** [comment] 2017-05-30 11:31
As a shallow fix, we could transform a null or empty string to an empty filter. Even though the behaviour isn't specified AFAIK, I think we should handle it. The question is, is this serious enough to warrant a hotfix? We may get the same error from other runners since filters weren't previously supported.

Related, @remcomulder is there any way that NCrunch could do some integration testing with our dev builds on MyGet so that we can catch issues like this prior to release?

**Comment by CharliePoole** [comment] 2017-05-30 12:14
@rprouse Bit of history: We used to transform null into TestFilter.Empty. I stopped that with 3.0 because it seemed to me to encourage sloppy programming (on our part).

I wondered if this had anything to do with rushing to get the fix into the release, but that's not the case, since this fix went into master a month ago. If ncrunch were running regular builds against our dev packages, then this would have been caught. That's what I recommended when we did the last hotfix for @remcomulder.

@remcomulder I see this as another unfortunate occurrence, one which we would have avoided if we knew it was a problem. I would have favored adding special code to allow your older versions to keep working.... i.e. translate the empty string to "<filter />" ... i.e. would have if you had told us about the problem before we released. The dev build that contained this change was on our feed on April 24.

Now however, we are released, which makes things more difficult. The decision is up to @rprouse but frankly, I think this is a problem that we didn't have to have. If you had been running builds against our dev releases, as I asked the last time something like this happened, then you would have told us about the problem and we would have put in code - even ugly code if necessary - to keep you working. My vote on this occasion is to put in the fix but not release a hotfix until/unless we see there are other fires to put out.

**Comment by remcomulder** [comment] 2017-05-30 12:28
I think the ideal approach here would be for me to introduce an immediate fix into NCrunch to align with the change, and also for a fix to be introduced to NUnit to check for string.Empty and default the filter to <filter/>.  It would be best if we can release both of these as soon as possible.  Ideally, we want to avoid having a few thousand people get a really bad experience when they update their NUnit.  To me this seems like the most effective form of damage control we can offer.

I agree that this is something that seems like it could have been avoided.  Regarding automated testing against NUnit dev builds, this is unfortunately not a simple thing to set up.  Beyond the infrastructure investment needed to make this work effectively, I'm concerned about the cost involved in hot-tracking live development of every change made to NUnit, since I'm likely to end up chasing many problems that I don't really need to be involved in.  Do you have other API consumers using such an approach?

Is there perhaps any way of marking the builds as release candidates so that the testing can be more targeted?

**Comment by CharliePoole** [comment] 2017-05-30 12:42
@remcomulder Yes, some others do that. Since they don't all choose to discuss it on public forums, I can't tell you who they are. (BTW, I appreciate that you do so!)

I don't know what resources you have to do builds, but I assume you have a local machine you can use for it. All it would require is a build of NCrunch which references the latest dev build nuget package on our feed. It's true that many changes won't impact you, but the simplest way of figuring out whether you are impacted is probably to run a test. 

I'm not clear what you mean about chasing problems in which you don't need to be involved. If a change breaks your integration, then you need to be involved. Otherwise not. The dev builds are already merged, they are not work in progress or anything like that, so each change is something that will eventually be in a release.

We are trying to make these builds act as an ongoing substitute for release candidates, so any feedback about this possibly not being a good idea is valuable. However, so far it seems to work quite well.

**Comment by rprouse** [comment] 2017-05-30 12:51
@remcomulder, our MyGet feed only includes builds of master, so it only includes code that has been reviewed in a PR and approved. I would also consider that feed as RC quality as we only run a series of our own tests before release. It is also fairly low volume. Even if you could pull latest from that feed once a week and test, it would have caught this issue.

As for an update to NUnit, I will consider it, but as @CharliePoole says, I would prefer to wait a short time to see if there are other issues reported that will also need to be fixed.

**Comment by rprouse** [comment] 2017-05-30 12:53
I have assigned this to myself. I will make the fix on the release branch in preparation for a hotfix.

**Comment by remcomulder** [comment] 2017-05-30 12:54
I think the situation I'm trying to avoid is that of myself needing to be 'at the table' for every change made to NUnit.  If the dev builds are infrequent enough or of high enough quality that broken builds don't happen, then an automated setup that downloads newly released NUnit dev builds and runs NCrunch over them could work ok.  I expect you'd likely have a good idea of how many dev builds are stable enough for full integration testing, so I will rely on your advice here.

An unfortunate reality for a project like NCrunch is that maintaining integration points (like this one) is by far the largest part of the job.  NCrunch is tied into many different projects, most of which are under development.  Even being aware of every change that happens is impossible, so heavy automation and reacting to user support requests is about the only way things can get done.  I mention this only as I often find myself a target of blame for integration problems like this one and I think it helps if everyone can understand the broader context of dev tooling further up the stack.  Considering everything that has changed in the last 12 months, it hasn't been a fun year :(

**Comment by remcomulder** [comment] 2017-05-30 12:55
I understand re: the wait for the hotfix.  I'll be advising users to stay on NUnit 3.6 for now.  Thanks for introducing the fix :)

**Comment by CharliePoole** [comment] 2017-05-30 13:11
When we say the "dev feed" we mean binaries from MyGet that represent changes proposed, reviewed, passed in CI and merged into master. Essentially they are already released - at least for those who follow the master source., I'm assuming you consume NUnit as a nuget package. If you don't, we can put a zip up somewhere instead.

The number of merges is growing because we tend to do small changes. But I don't think that's a big problem if you can automate it. In fact, smaller changes may make it easier to discover the cause of any problems.

**Comment by BrianLanghoor** [comment] 2017-06-02 08:41
@rprouse are you gonna implement a solution for this in 3.7.1? Because @remcomulder has created a fix in nCrunch with version 3.9. For me the issue is now resolved using nUnit 3.7.0 in combination with nCrunch 3.9. Just want to make sure you guys are not building a solution in both places.

**Comment by remcomulder** [comment] 2017-06-02 08:43
@BrianLanghoor beat me to the punch!  I was just about to announce that NCrunch v3.9 is out now with a fix for this issue.

**Comment by rprouse** [comment] 2017-06-02 12:30
@remcomulder any ideas how many of your users upgrade or continue to run on older versions? Trying to gauge how much of a priority it is to release an update.

**Comment by remcomulder** [comment] 2017-06-02 12:39
@rprouse I don't have any hard metrics on this unfortunately :(  I very often have support requests from versions going back as far as 4 years ago.  I'm not sure how many of these users will be tracking NUnit for the latest Nuget update.  NCrunch doesn't have an auto-update system, so probably it will be a while before the bulk of people are on v3.9.

**Comment by rprouse** [comment] 2017-06-06 00:16
Fixed with PR #2214, but not closed automatically because it was merged into the release branch.

**Closed by rprouse** 2017-06-06 00:16 UTC
Labels: is:bug, pri:high

**Comment by rprouse** [comment] 2017-06-06 02:23
The 3.7.1 hotfix is out. I also updated the docs to state that a null or empty string is also accepted for an empty filter as of NUnit 3.7.1, but "<filter/>" should be used for backwards compatibility.
