### ISSUE TITLE
CollectionAssert.AreEquivalent is extremely slow

### ISSUE THREAD

**Issue by nvborisenko** [nunit/nunit#2799] opened 2018-04-09 13:58 UTC
```csharp
var lines1 = new List<string> { };
var lines2 = new List<string> { };

for (int i = 0; i < 10000; i++)
{
  lines1.Add(i.ToString());
  lines2.Add(i.ToString());
}

CollectionAssert.AreEquivalent(lines1, lines2);
```

Verification of 10000 string elements takes 10 seconds. Verification of 100k elements may take more than 30 minutes (cannot wait until it finishes). This behavior takes a place in NUnit **3.10** and not reproducible in **3.9**

**Comment by CharliePoole** [comment] 2018-04-09 18:38
Several of us did changes to collection assert in that period. I'll take a look to see if one of mine caused this.

**Comment by mikkelbu** [comment] 2018-04-09 18:49
Actually, I think that my change in nunit/nunit#2600 has caused the problem (I've not had time to check it yet, as I'm halfway a VS upgrade). In the case above we will have to run through the entire remaining collection for every match we want to remove. Before my change we would find each match immediately as the first element.

**Comment by jnm2** [comment] 2018-04-09 19:27
The ideal situation might be to implement `IEqualityComparer` in all our internal comparer classes so they can be used with `HashSet` and `Dictionary`. `AreEquivalent` would use `HashSet.SetEquals` with [O(n + m)](https://msdn.microsoft.com/en-us/library/bb346516(v=vs.110).aspx#Anchor_2) (the counts of the two collections).

**Comment by jnm2** [comment] 2018-04-09 20:59
That sounds like a good idea. Either way, the collection equivalence constraint itself will probably need to use HashSet.SetEquals eventually to get to the standard O(n+m) people expect. It won't be able to do that unless all our internal NUnit equality comparers implement IEqualityComparer.

**Comment by jnm2** [comment] 2018-04-10 12:27
That's an interesting question. Is it even meaningful to test for set equality with tolerance? I don't know what set equality means without transitive element equality comparisons, and if you have tolerance, you don't have transitive equality. My attempt at searching didn't turn anything up. It would be cool to know.

We'd only need to adapt to IEqualityComparer when using a hash table. We'd only use a hash table for operations that compare two collections. A hash table in theory requires transitive equality comparisons and transitive hash codes. This is what the IEqualityComparer contract demands, so if it's inherently possible to use a hash table for the comparison, it's inherently possible to adapt our element comparer to IEqualityComparer.

Let's say there is a hypothetical comparison we want NUnit to do between two collections which is *not* inherently possible to losslessly adapt to IEqualityComparer. If that is the case, that would mean the comparison cannot even in theory make use of a hash table. We would then have to fall back to something slower. But before we worry about that, does such a comparison meaningfully exist?

**Comment by herebebeasties** [comment] 2018-04-16 14:14
I think set equality with tolerance does makes sense. Essentially, "is it possible to match every item in set A with one or more items in set B using equality function F such that no item in set B is left unmatched".  But I think that's always going to be O(n*m) in the general case.

Even items that implement `IComparable` such that you could potentially sort them first and then compare the streams pairwise might have out-of-order matches between the sets, so that wouldn't be good enough. To really speed it up you'd need the ability to map your items into some kind of lower-precision ordered map (e.g. `Math.Round()` and search in adjacent buckets). None of that would really work with a general `IEqualityComparer<T>` and you'd still need to flag every item that's within tolerance and then see if there are any left over afterwards.

I don't think I'd expect NUnit to try solve any of that for me out of the box.

**Comment by jnm2** [comment] 2018-04-26 12:50
@herebebeasties Good point. I was talking about set equality, but `Is.EquivalentTo` goes beyond set equality since that compares the number of repeated values. (The conceptual equivalent of comparing two `Dictionary<T, int> countsByValue` rather than comparing two `HashSet<T> uniqueValues`.)

We'd have to have an algorithm that not only did the O(m\*n) initial mapping but also proceeded by trying every combination of overlaps to see if it could match the items 1:1. It seems like that would have factorial complexity on top of the n\*m, depending on how connected the mapping is (worse with larger tolerances). This logic doesn't sound familiar, so I wonder if NUnit is currently returning wrong results for `EquivalentTo` in combination with `Tolerance`. Separate issue to fix, though.

How does it sound to implement the logic to first determine whether the comparison is transitive, and if so, use `HashSet<>.SetEquals`?

**Comment by jnm2** [comment] 2018-04-26 12:53
Also, any takers? If this interests you, please jump in!
If not, I'll do it as one of my next PRs.

**Comment by ggeurts** [comment] 2018-04-26 22:11
I solved this one already in commit https://github.com/ggeurts/nunit/commit/91639b65764c27207d3e81361f23745b9755c05f. That was supposed to become a pull request.

**Comment by jnm2** [comment] 2018-04-26 23:47
Well, this went quite a bit quicker than I anticipated! @ggeurts has started a PR already.

**Comment by ggeurts** [comment] 2018-04-27 13:41
Yes, I have started work on a PR, but still need to work out a way to get a hash code provider where that is possible for equivalence operations.

**Comment by jnm2** [comment] 2018-04-27 14:28
@ggeurts I'm thinking we need IChainComparer to have something like a `bool TryGetHashCodeProvider(out Func<object, int> hashCodeProvider)` method.

`TimeSpanToleranceComparer` would return false if a nonzero tolerance is specified. StringComparer would return `StringComparer.Ordinal.GetHashCode` and `StringComparer.CurrentCultureIgnoreCase.GetHashCode`, whichever matches the equality comparison it's doing. Etc.

**Comment by ggeurts** [comment] 2018-04-27 17:50
Is the collection element type always known?

**Comment by jnm2** [comment] 2018-04-27 17:55
@ggeurts No. You may find this PR quite relevant: https://github.com/nunit/nunit/pull/2501/files#diff-f6b841c6c7eed9838e33cf9082f26944R73

**Comment by CharliePoole** [comment] 2018-04-27 18:09
@ggeurts In fact, as it seemed to me in that PR, analyzing the args to decide if the element type can be known in advance is most likely the key to an efficient implementation. The current inefficient implementation has the virtue of actually working for `object[]` arguments containing mixed types, but that's probably not something that really happens a lot.

**Comment by ggeurts** [comment] 2018-04-27 20:54
So it makes sense to provide a more generic way to attempt to get an
IEqualityComparer<T> for a collection argument, based on the pull request
mentioned earlier. I will look into that.

Op vr 27 apr. 2018 20:09 schreef CharliePoole <notifications@github.com>:

**Comment by CharliePoole** [comment] 2018-04-27 22:26
@ggeurts Yes, I agree. The full set of criteria (as far as I've figured out) for a more efficient approach is:

1. All elements must be same type, which is most easily guaranteed if it's a typed array or other enumerable.

2. Must not be using a non-zero tolerance.

3. Must not be a type handled in a non-standard way by our equality comparer.

You could probably cross off the third point by providing special IEqualityComparers for such types.

**Comment by ggeurts** [comment] 2018-05-04 11:45
I have extended NUnitEqualityComparer and related classes (such as chain comparers and equalityadapter) with hash code generation. For most collection equivalence tests the complexity is now O(log(n)) instead of O(n*m). The exception is where external comparers are used that are based on IComparer or Comparison delegates, because it is not possible to calculate unique hash codes for those cases.

It is possible to speed up collection equivalence tests further by providing CollectionTally with an optimized IEqualityComparer<T> implementation rather than it Always using NUnitEqualityComparer for comparisons. However, I prefer to first wait for review of the changes committed so far.

**Comment by ggeurts** [comment] 2018-05-07 08:35
@jnm2 @CharliePoole Is https://github.com/ggeurts/nunit/commit/d893d83bbd18dd19474511d9058561f6713123da ok for review or do I need to break it down into smaller commits?

**Comment by jnm2** [comment] 2018-05-22 22:42
@ggeurts Sorry, I haven't had a lot of free time! That is difficult to review all at once. How much work do you think it is to break it into smaller descriptive commits?

**Comment by ggeurts** [comment] 2018-05-25 12:38
I will break down the changes into smaller commits to simplify review. However, my spare time is limited as well. It may take a short while to get there.

**Comment by nvborisenko** [comment] 2019-12-23 19:54
Hello Team,

Up this issue.

Actually this issue is not a big problem for us because of we decided not to use nunit on one of our project. But I remember that I spent several days to figure out what is wrong in my continuous integration setup to execute super simple tests there. I was so surprised when saw the actual reason why tests execution was hanging.

To save other people, let's review the fix. Thanks!

**Comment by cidthecoatrack** [comment] 2020-10-07 16:31
I would like to bump this - it's still open, and I definitely still see the issue in 3.12.0

**Comment by rprouse** [comment] 2021-04-19 00:40
From #3825, this has gotten even worse in 3.13. The example code from @NightElfik

```csharp
[Test]
public void NUunitRepro() {
	var dict = new Dictionary<int, string>();
	for (int i = 0; i < 10000; ++i) {
		dict.Add(i, i.ToString());
	}
	CollectionAssert.AreEquivalent(dict.Values.AsEnumerable(),
		Enumerable.Range(0, 10000).Select(j => j.ToString()));
}
```

My timings for various versions of NUnit;

- 3.9 => 27ms
- 3.10.1 => 6.7 sec
- 3.11 => 6.8 sec
- 3.12 => 6.9 sec
- 3.13 => 17.8 sec
- 3.13.1 => 17.8 sec

We should probably dust of the PR #2830 and see if we can get it finished.

**Comment by rprouse** [comment] 2021-04-19 21:45
I've been profiling the code and going through it all day. The fact that our constraints are not generic and take in objects is part of the problem, but most of it is a build-up of small features that we have accepted over time. The recent increase in time looks to be caused by recursion detection that was fixed recently. Other increases are the addition of new comparers for new types and fixes for equivalence.

@NightElfik, @nvborisenko and @cidthecoatrack , In both of the code examples, they are determining equivalence of two collections that are in the same order. `AreEquivalent` checks if the collections contain the same items in any order, so it is expensive because it must compare each item in actual to every item in expected.

Switching the above example to the following runs in 0.037 sec.

```csharp
[Test]
public void CollectionAreEqualTests()
{
    var dict = new Dictionary<int, string>();
    for (int i = 0; i < 10000; ++i)
    {
        dict.Add(i, i.ToString());
    }
    CollectionAssert.AreEqual(dict.Values.AsEnumerable(),
        Enumerable.Range(0, 10000).Select(j => j.ToString()));
}
```

**Comment by cidthecoatrack** [comment] 2021-04-19 22:24
I have user an Order By expression, coupled with Is.EqualTo, as a workaround for some time now, so the recommendation is valid. But the beauty of Is.EquivalentTo is that is compares what is missing and what is extra, not just that index i is different.  Could we maybe extend the equivalence to do some internal sorting of some kind, and then essentially do the same as Is.Equal, but instead of kicking out at the first unmatched index, keeps assessing?

**Comment by CharliePoole** [comment] 2021-04-19 22:39
It may be important to remember that NUnit's `CollectionAssert`, although modeled after Microsoft's, works on `IEnumerable` as well as `ICollection`. Of course, that could be taken into account in the implementation.

**Comment by stevenaw** [comment] 2021-04-20 09:42
It's separate from most of the ideas discussed in this issue and corresponding PR, but something I've been trying to wrap my head around recently is how it might look to make the internal `IChainComparer` determination less O(n) and and more O(1). The comparer used is largely based on _types_ of objects being compared and might be a good opportunity for caching (potentially pre-seeded for some simple primitives like `int` and `string`).

@rprouse 's point of furthering generic constraint usage could also help there (though I suspect would make it harder to port to 3.13.x in a non-breaking way)

**Comment by rprouse** [comment] 2021-04-20 14:19
I made a small breakthrough this morning. If the two collections are in the same order it is really slow, but if the two lists are reverse of each other, then it is fast.

This takes 22 seconds

```csharp
[Test]
public void IntCollectionAreEquivalentTests()
{
    var actual = Enumerable.Range(0, SIZE);
    var expected = Enumerable.Range(0, SIZE);
    CollectionAssert.AreEquivalent(actual, expected);
}
```

This takes 0.006 seconds

```csharp
[Test]
public void IntCollectionReversedAreEquivalentTests()
{
    var actual = Enumerable.Range(0, SIZE);
    var expected = Enumerable.Range(0, SIZE).Select(i => SIZE - i - 1);
    CollectionAssert.AreEquivalent(actual, expected);
}
```

Initial thinking is that `CollectionTally.TryRemove` iterates through the `actual` in reverse order making the evaluation of the two lists O(n) for reversed lists but O(n*n) for lists in the same order.

```csharp
public void TryRemove(object o)
{
    for (int index = _missingItems.Count - 1; index >= 0; index--)
    {
        if (ItemsEqual(_missingItems[index], o))
        {
            _missingItems.RemoveAt(index);
            return;
        }
    }

    _extraItems.Add(o);
}
```

I expect that the `actual` and `expected` are usually in at least a similar order, so an easy fix would be to reverse the iteration in the `for` statement making lists in the same order best case scenario degrading to fully reversed lists being worst case scenario.

Then we can apply an optimization by sorting the two collections in the tally if they are sortable. Determining if the collections are sortable is the hard part. My thinking there is that a collection is sortable if,

- It is strongly typed by being generic. All items in the collection need to be the same type to be sortable.
- The type of the items is numeric, a string, or `Comparer<T>.Default` finds an `IComparable<T>` for the type.

I'll do some experimentation with that, but I'd appreciate if the @nunit/framework-team can poke holes in my **sotable** logic. I'm sure I am missing something 😄

**Comment by siprbaum** [comment] 2021-04-20 16:22
What about the the non generic `IComparable` like listed in 
https://docs.microsoft.com/en-us/dotnet/standard/collections/comparisons-and-sorts-within-collections#determine-sort-order  ?

**Comment by mikkelbu** [comment] 2021-04-20 21:29
Regarding the ordering, then I noted above - https://github.com/nunit/nunit/issues/2799#issuecomment-379855198 - (and later lost track of it) that I introduced this problem, when I reversed the iteration, so that we delete from the back of the list instead of the front (as the example was comparing two large collections which mostly consisted of 0s).

**Closed** 2021-04-26 15:53 UTC
Labels: is:bug, pri:high, requires:releasenotes
