### ISSUE TITLE
TimeoutAttribute value wrapping not working

### ISSUE THREAD

**Issue by gps7** [nunit/nunit#3801] opened 2021-03-24 10:13 UTC
Hi,
Our projects commonly is using 3 standard timeout values and we want to keep thru all projects. Additionally, I've added logic to determine if the debugger is attached and then change this value to way much longer value. This way we would avoid often changing timeout value to something big or completely removing and then accidentally committing this change.
After implementing very simple wrapper for Timeout thought it is going to work but it turned out that wrapper has no affect at all anymore despite fact that looks like it is simple property change in [TimeoutAttribute ](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TimeoutAttribute.cs) implementation.

Why timeout wrapping is not working and?

Here is my code:
```
	public abstract class DefaultTimeoutAttribute : TimeoutAttribute
	{
		protected DefaultTimeoutAttribute(TimeSpan timeOut, TimeSpan debuggingTimeOut)
			: base(DefaultTime(timeOut, debuggingTimeOut))
		{
		}

		private static int DefaultTime(TimeSpan timeOut, TimeSpan debuggingTimeOut)
		{
			var value = System.Diagnostics.Debugger.IsAttached ? debuggingTimeOut : timeOut;
			return Convert.ToInt32(value.TotalMilliseconds);
		}
	}


	public class DefaultUnitTimeoutShortAttribute : DefaultTimeoutAttribute
	{
		public DefaultUnitTimeoutShortAttribute()
			: base(TimeSpan.FromSeconds(1), TimeSpan.FromDays(1))
		{
		}
	}
```

And then simple with 1 second timeout still green:
```
	[TestFixture]
	internal class TimeoutTests
	{
		[Test, DefaultUnitTimeoutShort]
		public void TestShortTimeout()
		{
			Console.WriteLine(DefaultTimeoutAttribute.Output);
			Thread.Sleep(11000);
			Assert.Pass();
		}
	}
```

The wrapper sets it to 1 second when not debugging and I checked all this logic, however, execution takes 11 seconds and it is passed. Changing Attribute to _DefaultUnitTimeoutShort_ to Timeout(1000) fails after expected time.

Why my wrapper is not working? I also tried to copy same logic from [TimeoutAttribute.cs](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TimeoutAttribute.cs) code and still have same problem.

**Comment by mikkelbu** [comment] 2021-03-25 22:00
Hi @gps7 

I can understand your confusion and I spent more time trying to understand this than I had expected. The problem is that the `TimeoutAttribute` sets the timeout in two different manners. The value passed as part of the constructor is used when the attribute is placed on a higher level. When the attribute is placed directly on a test, then it works as it sets a property on the test with the name `Timeout` (the name of the attribute). I don't know why it has been implemented in this manner, but I guess that there are historical reasons for this.

https://github.com/nunit/nunit/blob/af52b9a3b93edb5e54442ed6121b718532202a8f/src/NUnitFramework/framework/Internal/Execution/SimpleWorkItem.cs#L152-L161

So your attribute will work when you place it on the fixture (or on a parametric test), but not placed directly on a test. You can extend your code to also add a property like this
```csharp
	public class DefaultTimeoutAttribute : TimeoutAttribute
	{
		private readonly int _timeOut;

		protected DefaultTimeoutAttribute(TimeSpan timeOut, TimeSpan debuggingTimeOut)
			: base(DefaultTime(timeOut, debuggingTimeOut))
		{
			_timeOut = DefaultTime(timeOut, debuggingTimeOut);
		}

		private static int DefaultTime(TimeSpan timeOut, TimeSpan debuggingTimeOut)
		{
			var value = System.Diagnostics.Debugger.IsAttached ? debuggingTimeOut : timeOut;
			return Convert.ToInt32(value.TotalMilliseconds);
		}

		public override void ApplyToTest(Test test)
		{
			test.Properties.Add("Timeout", _timeOut);

			base.ApplyToTest(test);
		}
	}
```
If you only want to place the attribute on tests (and not on testfixtures or parametric tests), then it will probably be simpler to create an attribute that just adds a `"Timeout"` property with the appropriate value.

**Comment by mikkelbu** [comment] 2021-04-07 21:33
Closing this as answered. Note that we will still see additional comments.

**Closed by mikkelbu** 2021-04-07 21:33 UTC
Labels: is:question
