### ISSUE TITLE
OneTimeTearDown and Dispose Ordering

### ISSUE THREAD

**Issue by mriswyth** [nunit/nunit#2225] opened 2017-06-07 16:26 UTC
Using v3.7.0/v3.7.1 from nuget.
Run with NUnit3TestAdapter, NUnit-Gui-0.3, and nunit3-console.

I have some TestFixtures that implement IDisposable. Prior to the v3.7.0 release these test fixtures always executed the OneTimeTearDown (and TestFixtureTearDown before that) method before the TestFixture class' Dispose method. After performing a NuGet update to NUnit v3.7.0 and NUnit v3.7.1 these tests started throwing exceptions in the OneTimeTearDown method as some members had been disposed already.

I was able to reproduce this behavior with the cs-money sample project by having MoneyTest implement IDisposable, add a OneTimeTearDown method, and set breakpoints in each method. NuGet NUnit version before 3.7 execute the OneTimeTearDown method first, 3.7 and 3.7.1 execute Dispose first.

Should I be assuming an ordering of these methods?

**Comment by CharliePoole** [comment] 2017-06-07 18:09
I have confirmed this error by inspecting the code. The commands that make up a test setup are executed in reverse order, whereas one time setup commands are independent and are executed in the order specified in the command list. I updated the list of commands for fixture one-time teardown incorrectly.

I'm assigning this to myself, since I caused it. Too bad we didn't here about this before the hotfix.

@rprouse I'm making this high priority rather than critical. I think only you should decide what's critical and therefore requires a hotfix.

**Comment by oznetmaster** [comment] 2017-06-07 21:00
I think it might be critical :(

**Comment by CharliePoole** [comment] 2017-06-08 04:12
It probably is. Sigh.

**Closed** 2017-06-08 05:35 UTC
Labels: is:bug, pri:high
