### ISSUE TITLE
Test Order not respected in MonoDevelop on OSX

### ISSUE THREAD

**Issue by hoihoi8** [nunit/nunit#2180] opened 2017-05-19 23:07 UTC
Using Unity's MonoDevelop on OSX Sierra
Target Framework: Mono / .NET 4.5

`	
[Test, Order(1)]
	public void GameIsLoaded()
	{
		...
	}
`
`
		[Test, Order(2)]
		public void CanEnterCombatMode()
		{
			...
		}
	`

The test "CanEnterCombatMode" runs first because it is first alphabetically. The order attribute is not respected.

**Comment by CharliePoole** [comment] 2017-05-20 02:06
If it compiles, you are using a newer version of NUnit. But if you are using the MonoDevelop NUnit integration, I think it's trying to run it using the V2 nunit.core, which will appear to work but... not really. 😞

**Comment by CharliePoole** [comment] 2017-05-20 05:36
Closing as not a bug due to apparently incompatible software. Feel free to comment further. We can reopen if more info becomes available.

**Closed** 2017-05-20 05:36 UTC

**Comment by hoihoi8** [comment] 2017-05-22 23:28
Switching to Visual Studio for Mac solved this issue
