### ISSUE TITLE
NonParallelizable doesn't work on parameterized tests with parallel parent scope

### ISSUE THREAD

**Issue by eduherminio** [nunit/nunit#3874] opened 2021-06-10 23:06 UTC
I'm having issues overriding parallelizable behavior at method level using `[NonParallelizable]` attribute when `[Parallelizable(ParallelScope.All)]` is already set at either class or assembly level.

~~I've attempted to put together a minimal reproducible example, but didn't manage to reproduce it outside of my main project.~~

By renaming the tests in my original example, I'm able to reproduce the issue now.
I've updated the code below, but it can also be found in [this repo](https://github.com/eduherminio/nunit-issue-3874/actions/runs/930136811).

<details>
 <summary>Code to reproduce it</summary>
    
## Project file

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0"/>
  </ItemGroup>

</Project>
```

## Test file

```csharp
using NUnit.Framework;

[assembly: Parallelizable(ParallelScope.All)]

namespace TestNamespace
{
    public static class Config
    {
        public static Parameters Parameters { get; set; } = new Parameters();
    }

    public class Parameters
    {
        public int Integer { get; set; } = 1;
    }


    public class Tests
    {
        [TestCase(1, Category = "LongRunning", Explicit = true)]
        [TestCase(2, Category = "LongRunning", Explicit = true)]
        [TestCase(3, Category = "LongRunning", Explicit = true)]
        [TestCase(4, Category = "LongRunning", Explicit = true)]
        [TestCase(5, Category = "LongRunning", Explicit = true)]
        [TestCase(6, Category = "LongRunning", Explicit = true)]
        [TestCase(7, Category = "LongRunning", Explicit = true)]
        [TestCase(8, Category = "LongRunning", Explicit = true)]
        public void BestMove_Mate_in_3(int n)
        {
            TestContext.WriteLine($"Value: ${Config.Parameters.Integer}");  // Seeing values different to 1 here, and therefore test cases failing
            Validate(1);
        }

        [NonParallelizable]
        [TestCase(1, Category = "LongRunning", Explicit = true)]
        [TestCase(2, Category = "LongRunning", Explicit = true)]
        [TestCase(3, Category = "LongRunning", Explicit = true)]
        [TestCase(4, Category = "LongRunning", Explicit = true)]
        [TestCase(5, Category = "LongRunning", Explicit = true)]
        [TestCase(6, Category = "LongRunning", Explicit = true)]
        [TestCase(7, Category = "LongRunning", Explicit = true)]
        [TestCase(8, Category = "LongRunning", Explicit = true)]
        public void BestMove_Quiescence(int n)
        {
            int oldValue = Config.Parameters.Integer;

            try
            {
                TestContext.WriteLine($"Changing value to ${n}");
                Config.Parameters.Integer = n;

                Validate(n);
            }
            finally
            {
                TestContext.WriteLine($"Restoring value to ${oldValue}");
                Config.Parameters.Integer = oldValue;
            }
        }

        public static void Validate(int a)
        {
            for (int i = 0; i < 1_000; ++i)
            {
                Assert.AreEqual(a, Config.Parameters.Integer);
            }
        }
    }
}
```

## Bash command

```bash
dotnet build -c Release && dotnet test -c Release --no-build -v=normal --filter "TestCategory=LongRunning"
```

## Output

In my real example I can see `Parallelizable` and `NonParallelizable` tests being intercalated, with some `Parallelizable` ones failing due to the field of the static class not being 1.

## dotnet version

5.0.201
</details>

**Comment by mikkelbu** [comment] 2021-06-11 21:36
Hi @eduherminio 
This is not an area that I know much about, but you can try to run your test while setting `InternalTraceLevel` to `Debug`. That could perhaps give some hints of why this happens. You can add runsettings file in the same location as the project file, e.g. called `test.runsettings` and then add the following into the project file
```xml
  <PropertyGroup>
    <RunSettingsFilePath>$(MSBuildProjectDirectory)\test.runsettings</RunSettingsFilePath>
  </PropertyGroup>
```
This should generate files named `InternalTrace.NUMBER.PROJECTNAME...` which wil contain information about how the tests are being run. E.g.
```
...
23:28:46.763 Info  [ 4] TestWorker: ParallelSTAWorker starting on thread [18]
23:28:46.765 Info  [ 4] WorkItemQueue: ParallelQueue.0 starting
23:28:46.766 Info  [ 4] WorkItemQueue: ParallelSTAQueue.0 starting
23:28:46.766 Info  [14] TestWorker: ParallelWorker#1 executing NUnitParallel.dll
23:28:46.776 Debug [14] Dispatcher: Using Direct strategy for TestNamespace
23:28:46.776 Debug [14] Dispatcher: Using Parallel strategy for Tests
23:28:46.776 Info  [17] TestWorker: ParallelWorker#4 executing Tests
23:28:46.779 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable
23:28:46.779 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable(1)
23:28:46.803 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable(2)
23:28:46.807 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable(3)
23:28:46.811 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable(4)
23:28:46.817 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable(5)
23:28:46.822 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable(6)
23:28:46.826 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable(7)
23:28:46.830 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable(8)
23:28:46.838 Debug [17] Dispatcher: Using Direct strategy for NonParallelizable OneTimeTearDown
23:28:46.839 Debug [17] Dispatcher: Using Direct strategy for Parallelizable
23:28:46.839 Debug [17] Dispatcher: Using Parallel strategy for Parallelizable(1)
23:28:46.839 Debug [17] Dispatcher: Using Parallel strategy for Parallelizable(2)
23:28:46.839 Debug [17] Dispatcher: Using Parallel strategy for Parallelizable(3)
23:28:46.839 Info  [15] TestWorker: ParallelWorker#2 executing Parallelizable(1)
...
```

**Comment by eduherminio** [comment] 2021-06-11 23:35
Thanks @mikkelbu.
The logs look good to my unexperienced eye in terms of parallel/non parallel execution. I've reduced the tests cases of the parallelizable method to one to avoid as much noise as possible.

```
00:19:44.880 Info [15] TestWorker: ParallelWorker#3 executing Lynx.NUnit.Test.dll
00:19:44.883 Info [4] WorkItemQueue: ParallelSTAQueue.0 starting
00:19:44.899 Debug [15] Dispatcher: Using Direct strategy for Lynx
00:19:44.899 Debug [15] Dispatcher: Using Direct strategy for NUnit
00:19:44.900 Debug [15] Dispatcher: Using Direct strategy for Test
00:19:44.900 Debug [15] Dispatcher: Using Parallel strategy for EngineTest
00:19:44.900 Info [14] TestWorker: ParallelWorker#2 executing EngineTest
00:19:44.904 Debug [14] Dispatcher: Using Direct strategy for ParallelizableTest
00:19:44.904 Debug [14] Dispatcher: Using Parallel strategy for ParallelizableTest(1,[1])
00:19:44.904 Info [15] TestWorker: ParallelWorker#3 executing ParallelizableTest(1,[1])
00:19:44.904 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest
00:19:44.906 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest(1,[1])
00:19:45.078 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest(2,[1])
00:19:45.086 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest(3,[1])
00:19:45.087 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest(4,[1])
00:19:45.157 Debug [15] Dispatcher: Using Direct strategy for ParallelizableTest OneTimeTearDown
00:19:49.885 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest OneTimeTearDown
00:19:49.886 Debug [14] Dispatcher: Using Parallel strategy for EngineTest OneTimeTearDown
00:19:49.886 Info [15] TestWorker: ParallelWorker#3 executing EngineTest OneTimeTearDown
00:19:49.886 Debug [15] Dispatcher: Using Direct strategy for Test OneTimeTearDown
00:19:49.886 Debug [15] Dispatcher: Using Direct strategy for NUnit OneTimeTearDown
00:19:49.886 Debug [15] Dispatcher: Using Direct strategy for Lynx OneTimeTearDown
00:19:49.886 Debug [15] Dispatcher: Using Direct strategy for Lynx.NUnit.Test.dll OneTimeTearDown
00:19:49.886 Info [14] WorkShift: Parallel shift ending
```

However, the execution results suggest that non parallelizable tests don't wait for the parallelizable one to end, so the latter modifies a value in a static class and affects the execution of the first one, which also reads the same value.

<details>
<summary>Complete debug logs</summary>

```
InternalTrace: Initializing at level Debug
00:19:44.671 Debug [ 4] DefaultTestAssemblyBuilder: Loading Lynx.NUnit.Test, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null in AppDomain testhost
00:19:44.681 Debug [ 4] DefaultTestAssemblyBuilder: Examining assembly for test fixtures
00:19:44.682 Debug [ 4] DefaultTestAssemblyBuilder: Found 8 classes to examine
00:19:44.736 Debug [ 4] DefaultTestAssemblyBuilder: Found 2 fixtures with 54 test cases
00:19:44.853 Info  [ 4] DefaultTestAssemblyRunner: Running tests
00:19:44.858 Info  [ 4] Dispatcher: Initializing with 4 workers
00:19:44.860 Debug [ 4] WorkShift: Parallel shift adding queue ParallelQueue
00:19:44.861 Debug [ 4] WorkShift: Parallel shift adding queue ParallelSTAQueue
00:19:44.861 Debug [ 4] WorkShift: NonParallel shift adding queue NonParallelQueue
00:19:44.861 Debug [ 4] WorkShift: NonParallelSTA shift adding queue NonParallelSTAQueue
00:19:44.861 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelWorker#1
00:19:44.861 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelWorker#2
00:19:44.861 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelWorker#3
00:19:44.861 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelWorker#4
00:19:44.861 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelSTAWorker
00:19:44.861 Debug [ 4] WorkShift: NonParallel shift assigned worker NonParallelWorker
00:19:44.861 Debug [ 4] WorkShift: NonParallelSTA shift assigned worker NonParallelSTAWorker
00:19:44.872 Debug [12] EventPump: Starting EventPump
00:19:44.872 Debug [ 4] Dispatcher: Using Parallel strategy for Lynx.NUnit.Test.dll
00:19:44.874 Info  [ 4] WorkShift: Parallel shift starting
00:19:44.875 Info  [ 4] TestWorker: ParallelWorker#1 starting on thread [13]
00:19:44.876 Info  [ 4] TestWorker: ParallelWorker#2 starting on thread [14]
00:19:44.876 Info  [ 4] TestWorker: ParallelWorker#3 starting on thread [15]
00:19:44.876 Info  [ 4] TestWorker: ParallelWorker#4 starting on thread [16]
00:19:44.877 Info  [ 4] TestWorker: ParallelSTAWorker starting on thread [17]
00:19:44.880 Info  [ 4] WorkItemQueue: ParallelQueue.0 starting
00:19:44.880 Info  [15] TestWorker: ParallelWorker#3 executing Lynx.NUnit.Test.dll
00:19:44.883 Info  [ 4] WorkItemQueue: ParallelSTAQueue.0 starting
00:19:44.899 Debug [15] Dispatcher: Using Direct strategy for Lynx
00:19:44.899 Debug [15] Dispatcher: Using Direct strategy for NUnit
00:19:44.900 Debug [15] Dispatcher: Using Direct strategy for Test
00:19:44.900 Debug [15] Dispatcher: Using Parallel strategy for EngineTest
00:19:44.900 Info  [14] TestWorker: ParallelWorker#2 executing EngineTest
00:19:44.904 Debug [14] Dispatcher: Using Direct strategy for ParallelizableTest
00:19:44.904 Debug [14] Dispatcher: Using Parallel strategy for ParallelizableTest(1,[1])
00:19:44.904 Info  [15] TestWorker: ParallelWorker#3 executing ParallelizableTest(1,[1])
00:19:44.904 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest
00:19:44.906 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest(1,[1])
00:19:45.078 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest(2,[1])
00:19:45.086 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest(3,[1])
00:19:45.087 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest(4,[1])
00:19:45.157 Debug [15] Dispatcher: Using Direct strategy for ParallelizableTest OneTimeTearDown
00:19:49.885 Debug [14] Dispatcher: Using Direct strategy for NonParallelizableTest OneTimeTearDown
00:19:49.886 Debug [14] Dispatcher: Using Parallel strategy for EngineTest OneTimeTearDown
00:19:49.886 Info  [15] TestWorker: ParallelWorker#3 executing EngineTest OneTimeTearDown
00:19:49.886 Debug [15] Dispatcher: Using Direct strategy for Test OneTimeTearDown
00:19:49.886 Debug [15] Dispatcher: Using Direct strategy for NUnit OneTimeTearDown
00:19:49.886 Debug [15] Dispatcher: Using Direct strategy for Lynx OneTimeTearDown
00:19:49.886 Debug [15] Dispatcher: Using Direct strategy for Lynx.NUnit.Test.dll OneTimeTearDown
00:19:49.886 Info  [14] WorkShift: Parallel shift ending
00:19:49.887 Debug [14] WorkItemQueue: ParallelQueue.0 pausing
00:19:49.887 Debug [14] WorkItemQueue: ParallelSTAQueue.0 pausing
00:19:49.888 Info  [14] WorkItemQueue: ParallelQueue.0 stopping - 4 WorkItems processed
00:19:49.888 Info  [14] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed
00:19:49.888 Info  [16] TestWorker: ParallelWorker#4 stopping - 0 WorkItems processed.
00:19:49.888 Info  [14] WorkItemQueue: NonParallelQueue.0 stopping - 0 WorkItems processed
00:19:49.888 Debug [12] EventPump: EventPump Terminating
00:19:49.888 Info  [14] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed
00:19:49.888 Info  [17] TestWorker: ParallelSTAWorker stopping - 0 WorkItems processed.
00:19:49.888 Info  [14] TestWorker: ParallelWorker#2 stopping - 1 WorkItems processed.
00:19:49.888 Info  [13] TestWorker: ParallelWorker#1 stopping - 0 WorkItems processed.
00:19:49.893 Info  [15] WorkShift: Parallel shift ending
00:19:49.893 Debug [15] WorkItemQueue: ParallelQueue.0 pausing
00:19:49.893 Debug [15] WorkItemQueue: ParallelSTAQueue.0 pausing
00:19:49.893 Info  [15] WorkItemQueue: ParallelQueue.0 stopping - 4 WorkItems processed
00:19:49.893 Info  [15] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed
00:19:49.893 Info  [15] WorkItemQueue: NonParallelQueue.0 stopping - 0 WorkItems processed
00:19:49.893 Info  [15] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed
00:19:49.894 Info  [15] TestWorker: ParallelWorker#3 stopping - 3 WorkItems processed.
```

Regular execution logs
```
  Passed NonParallelizableTest(1, [1]) [166 ms]
  Passed NonParallelizableTest(2, [2]) [6 ms]
  Passed NonParallelizableTest(3, [3]) [1 ms]
  Failed ParallelizableTest(1,[1]) [250 ms]
  Error Message:
     (...)
NUnit Adapter 4.0.0.0: Test execution complete
   Passed NonParallelizableTest(4, [4]) [1 ms]
```
</details>

I'll keep trying to create a minimal reproducible example, but since I'm observing this issue with a project I'll end up open-sourcing anyway, I'm happy to point to the real example if someone decides to dive into this.

**Comment by eduherminio** [comment] 2021-06-11 23:58
**Update**

By renaming the original tests to the actual ones that were causing me issues in my project, I've managed to reproduce the issue.
I've pushed the code to [a repo](https://github.com/eduherminio/nunit-issue-3874/actions/runs/930136811).

That CI run is passing on Windows, but I normally work locally on Windows, so I wouldn't point to the OS as the root cause.

<details>
<summary>Here's the debug log</summary>

```
InternalTrace: Initializing at level Debug
01:43:29.869 Debug [ 4] DefaultTestAssemblyBuilder: Loading tmnp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in AppDomain testhost
01:43:29.882 Debug [ 4] DefaultTestAssemblyBuilder: Examining assembly for test fixtures
01:43:29.883 Debug [ 4] DefaultTestAssemblyBuilder: Found 4 classes to examine
01:43:29.916 Debug [ 4] DefaultTestAssemblyBuilder: Found 1 fixtures with 16 test cases
01:43:30.009 Info  [ 4] DefaultTestAssemblyRunner: Running tests
01:43:30.019 Info  [ 4] Dispatcher: Initializing with 4 workers
01:43:30.022 Debug [ 4] WorkShift: Parallel shift adding queue ParallelQueue
01:43:30.022 Debug [ 4] WorkShift: Parallel shift adding queue ParallelSTAQueue
01:43:30.022 Debug [ 4] WorkShift: NonParallel shift adding queue NonParallelQueue
01:43:30.022 Debug [ 4] WorkShift: NonParallelSTA shift adding queue NonParallelSTAQueue
01:43:30.023 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelWorker#1
01:43:30.023 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelWorker#2
01:43:30.023 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelWorker#3
01:43:30.023 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelWorker#4
01:43:30.023 Debug [ 4] WorkShift: Parallel shift assigned worker ParallelSTAWorker
01:43:30.023 Debug [ 4] WorkShift: NonParallel shift assigned worker NonParallelWorker
01:43:30.023 Debug [ 4] WorkShift: NonParallelSTA shift assigned worker NonParallelSTAWorker
01:43:30.031 Debug [12] EventPump: Starting EventPump
01:43:30.032 Debug [ 4] Dispatcher: Using Parallel strategy for tmnp.dll
01:43:30.033 Info  [ 4] WorkShift: Parallel shift starting
01:43:30.035 Info  [ 4] TestWorker: ParallelWorker#1 starting on thread [13]
01:43:30.035 Info  [ 4] TestWorker: ParallelWorker#2 starting on thread [14]
01:43:30.035 Info  [ 4] TestWorker: ParallelWorker#3 starting on thread [15]
01:43:30.036 Info  [ 4] TestWorker: ParallelWorker#4 starting on thread [16]
01:43:30.036 Info  [ 4] TestWorker: ParallelSTAWorker starting on thread [17]
01:43:30.038 Info  [ 4] WorkItemQueue: ParallelQueue.0 starting
01:43:30.038 Info  [ 4] WorkItemQueue: ParallelSTAQueue.0 starting
01:43:30.039 Info  [16] TestWorker: ParallelWorker#4 executing tmnp.dll
01:43:30.054 Debug [16] Dispatcher: Using Direct strategy for TestNamespace
01:43:30.054 Debug [16] Dispatcher: Using Parallel strategy for Tests
01:43:30.054 Info  [13] TestWorker: ParallelWorker#1 executing Tests
01:43:30.057 Debug [13] Dispatcher: Using Direct strategy for BestMove_Mate_in_3
01:43:30.058 Debug [13] Dispatcher: Using Parallel strategy for BestMove_Mate_in_3(1)
01:43:30.058 Info  [15] TestWorker: ParallelWorker#3 executing BestMove_Mate_in_3(1)
01:43:30.058 Debug [13] Dispatcher: Using Parallel strategy for BestMove_Mate_in_3(2)
01:43:30.060 Info  [16] TestWorker: ParallelWorker#4 executing BestMove_Mate_in_3(2)
01:43:30.061 Debug [13] Dispatcher: Using Parallel strategy for BestMove_Mate_in_3(3)
01:43:30.061 Debug [13] Dispatcher: Using Parallel strategy for BestMove_Mate_in_3(4)
01:43:30.061 Debug [13] Dispatcher: Using Parallel strategy for BestMove_Mate_in_3(5)
01:43:30.061 Debug [13] Dispatcher: Using Parallel strategy for BestMove_Mate_in_3(6)
01:43:30.061 Debug [13] Dispatcher: Using Parallel strategy for BestMove_Mate_in_3(7)
01:43:30.061 Debug [13] Dispatcher: Using Parallel strategy for BestMove_Mate_in_3(8)
01:43:30.061 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence
01:43:30.061 Info  [14] TestWorker: ParallelWorker#2 executing BestMove_Mate_in_3(3)
01:43:30.062 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence(1)
01:43:30.102 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence(2)
01:43:30.102 Info  [16] TestWorker: ParallelWorker#4 executing BestMove_Mate_in_3(5)
01:43:30.102 Info  [14] TestWorker: ParallelWorker#2 executing BestMove_Mate_in_3(4)
01:43:30.102 Info  [15] TestWorker: ParallelWorker#3 executing BestMove_Mate_in_3(6)
01:43:30.115 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence(3)
01:43:30.116 Info  [15] TestWorker: ParallelWorker#3 executing BestMove_Mate_in_3(7)
01:43:30.120 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence(4)
01:43:30.127 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence(5)
01:43:30.140 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence(6)
01:43:30.153 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence(7)
01:43:30.175 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence(8)
01:43:30.182 Debug [13] Dispatcher: Using Direct strategy for BestMove_Quiescence OneTimeTearDown
01:43:30.188 Info  [13] TestWorker: ParallelWorker#1 executing BestMove_Mate_in_3(8)
01:43:30.195 Debug [13] Dispatcher: Using Direct strategy for BestMove_Mate_in_3 OneTimeTearDown
01:43:30.195 Debug [13] Dispatcher: Using Parallel strategy for Tests OneTimeTearDown
01:43:30.195 Info  [13] TestWorker: ParallelWorker#1 executing Tests OneTimeTearDown
01:43:30.195 Debug [13] Dispatcher: Using Direct strategy for TestNamespace OneTimeTearDown
01:43:30.195 Debug [13] Dispatcher: Using Direct strategy for tmnp.dll OneTimeTearDown
01:43:30.251 Debug [12] EventPump: EventPump Terminating
01:43:30.257 Info  [13] WorkShift: Parallel shift ending
01:43:30.257 Debug [13] WorkItemQueue: ParallelQueue.0 pausing
01:43:30.257 Debug [13] WorkItemQueue: ParallelSTAQueue.0 pausing
01:43:30.259 Info  [13] WorkItemQueue: ParallelQueue.0 stopping - 11 WorkItems processed
01:43:30.259 Info  [13] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed
01:43:30.259 Info  [13] WorkItemQueue: NonParallelQueue.0 stopping - 0 WorkItems processed
01:43:30.260 Info  [13] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed
01:43:30.260 Info  [13] TestWorker: ParallelWorker#1 stopping - 3 WorkItems processed.
01:43:30.260 Info  [16] TestWorker: ParallelWorker#4 stopping - 3 WorkItems processed.
01:43:30.260 Info  [14] TestWorker: ParallelWorker#2 stopping - 2 WorkItems processed.
01:43:30.260 Info  [15] TestWorker: ParallelWorker#3 stopping - 3 WorkItems processed.
01:43:30.260 Info  [17] TestWorker: ParallelSTAWorker stopping - 0 WorkItems processed.

</details>

```

**Comment by asendimitrov** [comment] 2021-08-16 15:13
I've also just hit this, I think the issue lies within a mix of NonParallelizable + TestCases

**Comment by stevenaw** [comment] 2023-04-07 22:13
Closing as a duplicate of #3371

**Closed by stevenaw** 2023-04-07 22:13 UTC
Labels: confirm
