### ISSUE TITLE
Make the delegate for TextContext.AddFormatter<TSUPPORTED> generic

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#2245] opened 2017-06-13 08:51 UTC
Since AddFormatter checks the type it'd make the formatter callback simpler.

**Comment by CharliePoole** [comment] 2017-06-13 15:45
Seems like a good idea, but do we need this issue plus #2246 ?

**Comment by appel1** [comment] 2017-06-13 18:12
I think it would be helpful.

**Comment by CharliePoole** [comment] 2017-06-13 18:17
I agree. I'm asking why this is not a duplicate of #2246 ?

**Comment by appel1** [comment] 2017-06-13 18:25
If the delegate was generic you could use it like this instead:
```
TestContext.AddFormatter<SomeType>(value => value.SpecialFormattingMethod());
```

Instead of:
```
TestContext.AddFormatter<SomeType>( value => ((SomeType)value).SpecialFormattingMethod());
```

But not a big deal, just a little thing I thought worth mentioning that could simplify usage.

**Comment by appel1** [comment] 2017-06-13 18:26
Perhaps it would also make it a little bit more obvious that the delegate will only be called with an instance of the specified type as argument.

**Comment by CharliePoole** [comment] 2017-06-13 18:30
We are missing one another. 😄 I understand both issues. Aren't they both part of one issue, with one solution? This issue appears to be at least a partial solution for the problem in #2246.

I see why #2244 is separate, although I'd probably fix it in the same PR as the other two, but #2245 and #2246 seem to be looking at the same problem from two different perspectives.

**Comment by CharliePoole** [comment] 2017-06-13 18:33
@appel1 "Perhaps it would..." What is "it" in that sentence? If it's this (#2245) issue, there's no doubt that it's a very good idea. My doubts were about #2246.

**Comment by appel1** [comment] 2017-06-13 18:37
This one is for the signature of the delegate to make using AddFormatter easier. #2246 is about making it possible to implement the callback to recursively take advantage of the existing formatters, in my current specific case (KeyValuePair) that would be handled by #2244 but we have other classes not part of the framework that could take advantage of that. 

Perhaps I'm just too tired to be able express myself coherently. :)

**Comment by CharliePoole** [comment] 2017-06-13 19:41
@appel1 No, I think it's me not expressing my question clearly.

First... thanks for the explanation... I did understand the details of what you were asking for. I was more on the higher level of whether we should manage these things as separate issues or just unify them and make one fix. Let's just keep them separate now and do a single PR for both of them if that seems appropriate to whomever takes them on.

**Comment by rprouse** [comment] 2018-01-15 00:56
Closing as won't fix because the change will break the existing API. See the discussion in #2509

**Closed by rprouse** 2018-01-15 00:56 UTC
Labels: hacktoberfest, help wanted, is:enhancement, pri:normal
