### ISSUE TITLE
Unable to get property on a test's class when properties are specified on a test within the class.

### ISSUE THREAD

**Issue by DanLomanto** [nunit/nunit#1902] opened 2016-11-14 19:37 UTC
I have a class\test that looks like below, but when I go to read the Properties of the Test via it's context, i'm only given the "Retry" property when I was hoping to see the Category that was specified at the class level as well.  I've figured out that if I remove the Retry property from the test that I'm then able to see the Category from the class decorator. So it appears that the properties are being overwritten by the ones specified at the test level instead of "added" to a list of properties from both the class and test?

    [TestFixture]
    [Category("SmokeTest")]
    public class LoginTests
    {
        [Test]
        [Retry(2)]
        public void UserCanLogIn()
        {
              // Test Guts in here...
        }
    }

c# code to get category - returns null reference error instead of "SmokeTest"
string categoryName = TestContext.Test.Properties.Get("Category").ToString();

**Comment by CharliePoole** [comment] 2016-11-15 01:29
Duplicate of #796

**Closed** 2016-12-01 20:44 UTC
Labels: closed:duplicate
