### ISSUE TITLE
ITestCaseData does not show test with Visual Studio Test Adapter 3.0.7

### ISSUE THREAD

**Issue by immeraufdemhund** [nunit/nunit#1056] opened 2015-11-22 21:07 UTC
Using Visual Studio 2015 community and the Visual Studio Test Adapater 3.0.7. I'm trying to get a single test to show in the test explorer by implementing ITestCaseData but none show up. If I extend TestParameters instead I see the test, but the TestName does not show properly (expected to see what I set the TestName too but found "TestTheTruth(GildedRose.Tests.ItemTestCaseData)") However if i use the fluent TestCaseData it works as expected. For a full scenario of what I was doing you can see my article on c-sharpcorner I"m just trying to get it to work with NUnit 3.0

http://www.c-sharpcorner.com/UploadFile/0f29c1/nunit-test-case-source/

currently my code looks like this

```
[TestFixture]
public class TestAssemblyTests
{
    [Test, TestCaseSource(typeof(ItemTestCaseProvider))]
    public int TestTheTruth()
    {
        true.Should().BeTrue();
        return 1;
    }
}
class ItemTestCaseProvider : IEnumerable<ItemTestCaseData>
{
    public IEnumerator<ItemTestCaseData> GetEnumerator()
    {
        yield return new ItemTestCaseData();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }
}
internal class ItemTestCaseData : TestParameters //ITestCaseData
{
    //public object[] Arguments { get; private set; }

    //public object ExpectedResult { get; private set; }

    //public bool HasExpectedResult { get { return true; } }

    //public IPropertyBag Properties { get; private set; }

    //public RunState RunState { get { return RunState.Runnable; } }

    //public string TestName { get; set; }

    public ItemTestCaseData()
    {
        //Properties = new PropertyBag();
        //ExpectedResult = 1;
        RunState = RunState.Runnable;
        TestName = "ITEMMMSSS";
    }
}
```

**Comment by CharliePoole** [comment] 2015-11-22 21:16
The link doesn't work, so I probably don't have the full picture of what you are trying to do.

What I see in your sample code is that you have a test method without arguments to which you seem to want to provide an argument. Also, it returns a value, which makes it illegal for NUnit unless you tell NUnit what the expected result should be. Can you clarify what's going on?

**Comment by immeraufdemhund** [comment] 2015-11-22 21:56
well... I was happy with that website, now because I hit edit on it so that I could update the code from NUnit 2.6 (saved as draft) it unpublished the article.. *sigh* I told them to finish and re-publish but that could take a few days.

Oh well that aside. I was mainly just playing around with ITestCaseData and the other interfaces related to this. I found a good enough work around (make a ItemBuilder class, and pass that into the TestCaseData then do my magic there for the TestName formatting) What I was hoping to see was that if i implement ITestCaseData that I would see tests. Here is a completed set of working code. 

    [TestFixture]
    public class TestAssemblyTests
    {
        [Test, TestCaseSource(typeof(ItemTestCaseProvider))]
        public int TestTheTruth(Item item)
        {
            var program = new Program();
            program.AddItem(item);
            program.UpdateQuality();
            return item.Quality;
        }
    }
    class ItemTestCaseProvider : IEnumerable<ItemTestCaseData>
    {
        public IEnumerator<ItemTestCaseData> GetEnumerator()
        {
            yield return new ItemTestCaseData(ItemBuilder.AnyItem.WithInitialQuality(1).ToBeSoldIn(1).ShouldByTomorrowHaveQualityOf(0));
            yield return new ItemTestCaseData(ItemBuilder.AnyItem.WithInitialQuality(2).ToBeSoldIn(0).ShouldByTomorrowHaveQualityOf(0));
            yield return new ItemTestCaseData(ItemBuilder.AnyItem.WithInitialQuality(0).ToBeSoldIn(0).ShouldByTomorrowHaveQualityOf(0));
            yield return new ItemTestCaseData(ItemBuilder.AgedBrie.WithInitialQuality(0).ToBeSoldIn(1).ShouldByTomorrowHaveQualityOf(1));
            yield return new ItemTestCaseData(ItemBuilder.AgedBrie.WithInitialQuality(0).ToBeSoldIn(0).ShouldByTomorrowHaveQualityOf(2));
            yield return new ItemTestCaseData(ItemBuilder.AgedBrie.WithInitialQuality(50).ToBeSoldIn(1).ShouldByTomorrowHaveQualityOf(50));
            yield return new ItemTestCaseData(ItemBuilder.AgedBrie.WithInitialQuality(50).ToBeSoldIn(0).ShouldByTomorrowHaveQualityOf(50));
            yield return new ItemTestCaseData(ItemBuilder.Sulfuras.ToBeSoldIn(0).ShouldByTomorrowHaveQualityOf(80));
            yield return new ItemTestCaseData(ItemBuilder.BackstagePass.ToBeSoldIn(11).ShouldByTomorrowHaveQualityOf(1));
            yield return new ItemTestCaseData(ItemBuilder.BackstagePass.ToBeSoldIn(10).ShouldByTomorrowHaveQualityOf(2));
            yield return new ItemTestCaseData(ItemBuilder.BackstagePass.ToBeSoldIn(5).ShouldByTomorrowHaveQualityOf(3));
            yield return new ItemTestCaseData(ItemBuilder.BackstagePass.WithInitialQuality(50).ToBeSoldIn(0).ShouldByTomorrowHaveQualityOf(0));
            yield return new ItemTestCaseData(ItemBuilder.ConjuredItem.WithInitialQuality(2).ToBeSoldIn(1).ShouldByTomorrowHaveQualityOf(0));
            yield return new ItemTestCaseData(ItemBuilder.ConjuredItem.WithInitialQuality(4).ToBeSoldIn(0).ShouldByTomorrowHaveQualityOf(0));
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }

    class ItemBuilder
        {
            public static ItemBuilder AnyItem { get { return new ItemBuilder("Any Item"); } }
            public static ItemBuilder AgedBrie { get { return new ItemBuilder("Aged Brie"); } }
            public static ItemBuilder Sulfuras { get { return new ItemBuilder("Sulfuras, Hand of Ragnaros").WithInitialQuality(80); } }
            public static ItemBuilder BackstagePass { get { return new ItemBuilder("Backstage passes to a TAFKAL80ETC concert"); } }
            public static ItemBuilder ConjuredItem { get { return new ItemBuilder("Conjured Mana Cake"); } }

        public Item Item { get; private set; }
            public int ExpectedQuality { get; private set; }

            private ItemBuilder(string name)
            {
                Item = new Item { Name = name };
            }

            public ItemBuilder ToBeSoldIn(int days)
            {
                Item.SellIn = days;
                return this;
            }
            public ItemBuilder WithInitialQuality(int quality)
            {
                Item.Quality = quality;
                return this;
            }

            internal ItemBuilder ShouldByTomorrowHaveQualityOf(int quality)
            {
                ExpectedQuality = quality;
                return this;
            }
        }

now if i do this I get no tests in the TestExplorer

    internal class ItemTestCaseData : ITestCaseData
    {
        public ItemTestCaseData(ItemBuilder itemBuilder)
        {
            Arguments = new object[] { itemBuilder.Item };
            ExpectedResult = itemBuilder.ExpectedQuality;
            TestName = $"{itemBuilder.Item.Name} with quality {itemBuilder.Item.Quality} to be sold in {itemBuilder.Item.SellIn} days should have quality of {itemBuilder.ExpectedQuality} tomorrow";
        }

        public object[] Arguments { get; private set; }

        public object ExpectedResult { get; private set; }

        public bool HasExpectedResult { get { return true; } }

        public IPropertyBag Properties { get; private set; }

        public RunState RunState { get { return RunState.Runnable; } }

        public string TestName { get; private set; }
    }

if I do this I get tests

    internal class ItemTestCaseData : TestCaseParameters
    {
        public ItemTestCaseData(ItemBuilder itemBuilder)
            : base(new object[] { itemBuilder.Item })
        {
            ExpectedResult = itemBuilder.ExpectedQuality;
            TestName = $"{itemBuilder.Item.Name} with quality {itemBuilder.Item.Quality} to be sold in {itemBuilder.Item.SellIn} days should have quality of {itemBuilder.ExpectedQuality} tomorrow";
        }


Now that i'm typing this out I think this is more of a bug report for the Test Adapter than NUnit.

**Comment by immeraufdemhund** [comment] 2015-11-23 20:27
The link should be working. I just went to the website without logging in and could see the article again

http://www.c-sharpcorner.com/UploadFile/0f29c1/nunit-test-case-source/

**Comment by ericnewton76** [comment] 2015-11-27 16:53
The link is working for me.  I arrived here because after upgrading from Nunit 2.6.4 to Nunit 3.0.0 (via nuget update) the VS test runner isn't finding any tests.

I believe this is a bigger issue than just the ITestCaseData issue

**Comment by rprouse** [comment] 2015-11-27 16:58
@ericnewton76 have you installed the NUnit3 Test Adapter? The original NUnit2 adapter only runs v2 tests and the new NUnit3 adapter only runs v3 tests.

https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d

**Comment by ericnewton76** [comment] 2015-11-27 17:10
I thought I checked for that both through Extension Updates and by general search... I will try that and report back.  If it succeeds we should probably just remove this noise... lol

**Comment by ericnewton76** [comment] 2015-11-27 17:13
As anticipated, it works.  Should I "add this as an issue" and you comment to place it in better search results?  I'm tempted to just wipe all this noise from this particular thread.

**Comment by CharliePoole** [comment] 2015-11-27 18:15
This is an issue. Creating a second issue will only double the noise. :-)

**Comment by CharliePoole** [comment] 2015-11-28 17:42
I'm noting that the original issue filed by @immeraufdemhund is still not resolved. The questions introduced by @ericnewton76 are not related and have been resolved separately.

Please avoid "piling on" to bugs if you don't have exactly the same symptoms in exactly the same circumstances!

**Comment by constructor-igor** [comment] 2015-12-31 11:03
I try to investigate the issue and execute test adapter 3.0.8 with updated sample from http://www.c-sharpcorner.com/uploadfile/0f29c1/nunit-test-case-source/

Updated (fixed compilation error) test placed:
https://github.com/constructor-igor/TechSugar/tree/master/TestingLab/NUnitSamples/NUnit_v3_samples/1056

```
SetUp failed for test fixture NUnit_v3_samples._1056.NUnitIssue1056
An exception was thrown while loading the test.
System.InvalidCastException: Unable to cast object of type 'NUnit_v3_samples._1056.ItemTestCaseData' to type 'NUnit.Framework.Internal.TestCaseParameters'.
   at NUnit.Framework.TestCaseSourceAttribute.<BuildFrom>d__16.MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData)
   at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__48.MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)
```

**Comment by CharliePoole** [comment] 2015-12-31 17:39
@constructor-igor You are looking at NUnit V2 documentation? Isn't this an NUnit 3.0 bug?

**Comment by CharliePoole** [comment] 2015-12-31 17:59
OK, I see the problem. If you look at NUnitTestCaseBuilder.cs, you will notice that it has been changed to require an argument of Type TestCaseParameters. IIRC I did this because all our own calls were actually using that class and because I could see no reason for a user to extend TestCaseData.

Unfortunately, I didn't change the docs, which still say in a few places that you can simply implement ITestCaseData.

The question is now, should we simply change the docs or is it still desirable to allow users to implement the interface themselves?

@immeraufdemhund What do you think of this choice?

@constructor-igor Do you think code changes are needed? Would you like to make them? If it's docs, one of us can simply edit them.

**Comment by immeraufdemhund** [comment] 2015-12-31 18:45
well.. part of me is screaming "ALWAYS DEPEND ON INTERFACES". the other part of me is looking at the difference in my code when it implements ITestCaseData, and extending TestCaseParameter. The code is smaller and more concise when I extend. However the name doesn't really line up with how I was using it. In my scenario I'm adapting my Model (or my data) to be data for my test. And it's more than just a parameter to a test. I can expect a return value or a variety of other things. I suppose from your code it makes sense that it is just a parameter into a test case runner. Since i'm writing tests for my code and not yours I would like to implement ITestCaseData, or extend TestCaseDataBase (or words to that effect). 

As for which... I'm going to pondering on it some.

**Comment by CharliePoole** [comment] 2015-12-31 19:54
Please mix the following notes in with your pondering. :-)

Note that the name is actually plural: TestCaseParameters. It was originally called ParameterSet, which might be a bit more obvious. The notion is that it wraps a number of parameters, one of which is the list of arguments to the method. Other parameters are the name of the test, the expected return value, whether the test should be ignored, etc.

However, I see your point. From the point of view of your method, a parameter is an argument, so one of my "parameters" is the list of "parameters" to your method. I'm open to naming suggestions, of course.

Since my changes originated from the notion that people can simply use TestCaseData, I guess the first question to resolve is this: "In what situations is TestCaseData by itself insufficient for your use?" Can't you just pass all the info needed by your test method through TestCaseData? At any rate, that is what my changes envisioned.

If there are reasons why an extended class is needed, my next question would be why don't you just extend TestCaseData rather than it's base?

For now, I have marked this as a bug, but will change it if we decide it merely needs better docs.

**Comment by immeraufdemhund** [comment] 2016-01-01 05:29
I concede to your point about `TestCaseData` being sufficient. I am so used to needing interfaces to test with that I just assumed that I should implement `ITestCaseData`. However to counter my point is to say that we use interfaces so that we can replace the concrete class with another one as we see fit for any reason. To which we should then ask "Why should I replace ITestCaseData with my own home brew version?", or another related question for the mockists out there "Why would I ever want to mock ITestCaseData?" In my mind there is no valid reason to do either. I'm writing tests for my code. I need to use the tools of the testing framework as is or ADD TO the framework (through attributes and extension methods) but never should I replace the functionality. That would be changing the way NUnit works.

So all that to say I don't need or want to implement `ITestCaseData`. To extend `TestCaseData` or `TestCaseParameters` on the other hand I think is also a wrong  solution because I'm not taking your test case data and extending it to mine. I'm taking my data and adapting it to work in a test. A builder pattern, or a adapter pattern would be a much more reasonable approach.

Now from a generic standpoint I would contend that if your documentation says that I can put a class that directly implements ITestCaseData, and the code allows it then I would want to see it work. I don't like, though, that I can use a class that has Internal in the namespace (specifically talking about `TestCaseParamters`). This leaves me with the feeling of saying I would rather have to return TestCaseData because I should be giving my test concrete test cases. I think the following code reads nice, and speaks well to my point

    class ItemTestCaseDataProvider : IEnumerable<TestCaseData>
    {
        private class ItemTestCaseBuilder
        {
            public static ItemTestCaseBuilder AnyItem
            {
                get
                {
                    return new ItemTestCaseBuilder(new Item { Name = "Any Item" });
                }
            }
            public static ItemTestCaseBuilder AgedBrie
            {
                get
                {
                    return new ItemTestCaseBuilder(new Item { Name = "Aged Brie" });
                }
            }
            private readonly Item _item;

            private ItemTestCaseBuilder(Item item)
            {
                _item = item;
            }
            public ItemTestCaseBuilder WithDaysToBeSold(int remainingDays)
            {
                _item.SellIn = remainingDays;
                return this;
            }
            public ItemTestCaseBuilder WithInitialQuality(int initialQuality)
            {
                _item.Quality = initialQuality;
                return this;
            }

            public TestCaseData ShouldHaveQuality(int expectedQuality)
            {
                var testCaseData = new TestCaseData(_item)
                {
                    ExpectedResult = expectedQuality,
                    HasExpectedResult = true,
                    TestName = $"{_item.Name} with quality {_item.Quality} to be sold in {_item.SellIn} days should have quality of {expectedQuality} tomorrow",
                };

                return testCaseData;
            }
        }
        public IEnumerator<TestCaseData> GetEnumerator()
        {
            yield return ItemTestCaseBuilder.AnyItem.WithDaysToBeSold(1).WithInitialQuality(1).ShouldHaveQuality(0);
            yield return ItemTestCaseBuilder.AnyItem.WithDaysToBeSold(0).WithInitialQuality(2).ShouldHaveQuality(0);
            yield return ItemTestCaseBuilder.AnyItem.WithDaysToBeSold(0).WithInitialQuality(0).ShouldHaveQuality(0);
            yield return ItemTestCaseBuilder.AgedBrie.WithDaysToBeSold(1).WithInitialQuality(0).ShouldHaveQuality(1);
            yield return ItemTestCaseBuilder.AgedBrie.WithDaysToBeSold(1).WithInitialQuality(50).ShouldHaveQuality(50);

        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }

**Comment by CharliePoole** [comment] 2016-01-01 17:01
I think you summarized the issue well. I would add that you can also add to NUnit by making suggestions for changes or even contributing them. :-)

Since TestCaseData already encapsulates (through TestCaseParameters) the **only** test parameters that NUnit understands, it seems like there is only one reason to extend it: to provide additional fluent properties and methods. However, you can't extend it that way for individual args, since a test case potentially uses multiple args. So a separate class makes more sense, as you have done. 

At first glance, it looks like your example will work, provided your test method takes an argument of ItemTestCaseBuilder. However, that seems a bit unnatural to me. Your tests are probably really dealing with Items and the extra infrastructure may be a bit confusing, particularly if some test takes two items or a list of items.

Here's how you might do it for the Item class...

```C#
public class TestItem : Item
{
        public static TestItem AnyItem
        {
            get
            {
                return new TestItem { Name = "Any Item" };
            }
        }

        public static TestItem AgedBrie
        {
            get
            {
                return new TestItem { Name = "Aged Brie" };
            }
        }

        public TestItemTestCaseBuilder WithDaysToBeSold(int remainingDays)
        {
            SellIn = remainingDays;
            return this;
        }

        public TestItem WithInitialQuality(int initialQuality)
        {
            Quality = initialQuality;
            return this;
        }
}
```

This sort of thing would allow you to use the same syntax for a ValueSource and to support multiple items as test args more easily. You could eliminate the extra indirection of ItemTestCaseBuilder.

One small comment on the code... It's not necessary for you to set HasExpectedResult and I'm a bit surprised if it has a public setter. If you should set it without actually setting an ExpectedResult, then the expected value would be null, which might be quite confusing.

**Comment by stevenaw** [comment] 2023-12-16 19:09
I can confirm that this can be reproduced with latest:
- NUnit 4.0.1
- NUnit3TestAdapter 4.5.0
- Visual Studio 17.8.0

I've uploaded the following repro to the issues repo: https://github.com/nunit/nunit.issues/tree/main/Issue1056
The following error is visible in the Test Explorer window:

> Message: 
> Failure building Test
> System.InvalidCastException : Unable to cast object of type 'Issue1056.ItemTestCaseData' to type 'NUnit.Framework.Internal.TestCaseParameters'.
> 
>   Stack Trace: 
> TestCaseSourceAttribute.BuildFrom(IMethodInfo method, Test suite)+MoveNext()
> DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)

It looks like @mikkelbu has found and linked a duplicate issue in https://github.com/nunit/nunit/issues/3803#issuecomment-813094737 and noted the following from the [documentation](https://docs.nunit.org/articles/nunit/writing-tests/TestCaseData.html) :

> The TestCaseData class provides extended test case information for a parameterized test, although any object deriving from TestCaseParameters may be used. Unlike NUnit 2, you cannot implement ITestCaseData, you must derive from TestCaseParameters.

There's a bit more context within #3803 about this so I'm going to close this as a duplicate

**Closed by stevenaw** 2023-12-16 19:09 UTC
Labels: is:bug, pri:normal
