### ISSUE TITLE
Add support for ASP.NET 5 and the new Core CLR

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#575] opened 2015-04-07 18:41 UTC
I tried to create an NUnit test project using Visual Studio 2015 using the ASP.NET 5 class library that uses the Core CLR. It built fine against the full CLR, but failed to compile against the Core CLR.

Web development is probably one of the areas that .NET is most widely used in, so we should be ready for the next version of ASP.NET.

**Update**

At this point, the new portable NUnit framework built using the `nunit-dnx.sln` targets the following frameworks;

- .NET Framework 4.6 (net46)
- ASP.NET Core 5.0 (dnxcore50) and
- Windows Universal 10.0 (uwp.10.0)

This is intended to allow testing of cross-platform ASP.NET 5 applications, Windows 10 Universal apps and .NET Core applications.

For information on installing and using ASP.NET 5 on Windows, see https://docs.asp.net/en/latest/index.html

The nunitlite.runner assembly will allow you to create a new .NET Core Console Application that will self run any unit tests contained within itself.

![image](https://cloud.githubusercontent.com/assets/493828/10590992/cec4430e-7681-11e5-8bdf-78aa423a2afa.png)

**Outstanding Tasks**

- Add the new assemblies to the framework and nunitlite NuGet packages
- Add the ability to build, test and package the new projects to NUnit.proj
- Add a project template to nunit/nunit.templates
- Create a more full featured test runner including running tests from Visual Studio

**Comment by CharliePoole** [comment] 2015-04-07 19:08
Makes sense to me. I added it to the final milestone, but you may want to schedule it sooner.

**Comment by eliprand** [comment] 2015-04-07 20:20
Rob,
I agree. I can maybe offer some assistance in testing. You mentioned having some success building. I was not even able to add a reference to NUnit to a ASP.NET 5 WebAPI project....

**Comment by eliprand** [comment] 2015-04-08 03:01
Rob,
As you may have seen on the Google group, my issue was due to a rogue PostSharp NuGet source. I will dig into NUnit and VS 2015 tomorrow.

**Comment by voloda** [comment] 2015-04-29 19:20
I am interested about this one.

**Comment by CharliePoole** [comment] 2015-04-30 21:57
@voloda Give it a shot then!

**Comment by voloda** [comment] 2015-05-05 22:11
@rob, @eliprand 

I did a bit of research here with following summary:

* Using portability analyzer closest to CoreCLR seems to be current Portable version
* Brute force changes without any actual testing can be seen [here](https://github.com/voloda/nunit/tree/coreclr)
  * This is compilable with VS 2015 RC and CoreCLR only
  * It does not contain any updates to comments etc.
* Few ideas how to continue if this is viable:
  * Extract the reflection into some helper class and perform platform specific code there
  * Since ReflectedType is not supported (I submitted a question regarding this) we can either pass it thru the calling chain or wrap the method info to always provide ReflectedType - for CoreCLR this will simply be set to original Type used for reflection.

Any feedback welcome.

**Comment by rprouse** [comment] 2015-05-06 00:06
@voloda, thanks for doing all that work. I figured that the portable framework would be closest to the CoreCLR. I was hoping that we could modify the the portable framework to also target the CoreCLR. That shouldn't be too hard looking at your fork. As you noted, `ReflectedType` is not supported. Maybe we should push to get that added, it may not be too late and would really simplify our changes. Let me know what you hear back. Can you post a link to where you asked the question so we can track it or add our voice?

The second thing that I see is that many of our queries on the `Type` need to got through `GetTypeInfo()` first. It would be an easy fix if we could use extension methods, but we can't, so your idea of refactoring it out to a helper class is probably a good idea.

I am uninstalling the CTP of VS 2015 tonight and installing the RC, so I will take a closer look at your code when I am done. Diffs are one thing, but I prefer to play in Visual Studio :smile:

**Comment by CharliePoole** [comment] 2015-05-06 00:14
@rprouse Why can't we use extension methods? I thought that was just a compiler thing. Can't we use the same trick we use to support them under .NET 2.0?

**Comment by rprouse** [comment] 2015-05-06 00:31
@CharliePoole, I stand corrected. I thought we had trouble with extension methods under Mono when targeting 2.0. If they work, we can make GetTypeInfo() an extension method on Type if not targeting the Portable framework assuming that GetTypeInfo() is supported in the Portable framework. I would really like to not have to add a CoreCLR framework if we can make the portable framework work.

**Comment by CharliePoole** [comment] 2015-05-06 01:04
I'm with you in extending the portable framework to work under CoreCLR.

For type info, I had actually been assuming we would create extension methods for IsEnum, etc. in teh CoreCLR build rather than the other way around. At least that's the syntax with which we are all familiar.

**Comment by rprouse** [comment] 2015-05-06 01:08
Extension methods for IsEnum and the like would be better, but we can't have extension properties yet can we? I'm pretty tired tonight, I could easily be wrong :smile:

**Comment by CharliePoole** [comment] 2015-05-06 01:23
You're right. How annoying! Of course, that's entirely reasonable since an extension method has to have a _this_ argument.

**Comment by voloda** [comment] 2015-05-06 06:07
[CoreCLR issue](https://github.com/dotnet/coreclr/issues/926)

@rprouse I will try with portable only but there were still few more exceptions regarding localization.

@rprouse, @CharliePoole Extension method are just compilar syntactic sugar but it requires some special attribute being in the code. Workaround is to declare it manually in your codebase but I never felt good about such hack.

**Comment by CharliePoole** [comment] 2015-05-06 06:19
It's shack we already use if you need it and I believe ms designed the hack
in.

**Comment by voloda** [comment] 2015-05-11 20:19
See comments on linked CoreCLR issue... They are not willing to add it,

**Comment by CharliePoole** [comment] 2015-05-11 21:18
@voloda "They are not willing to add it" meaning ReflectedType?

**Comment by voloda** [comment] 2015-05-11 21:19
@CharliePoole Sorry for confusion - yes the ReflectedType

**Comment by CharliePoole** [comment] 2015-05-11 21:48
No problem... these comments are somewhat stateless. :-)

**Comment by davidfowl** [comment] 2015-07-21 16:29
Any progress made here?

**Comment by CharliePoole** [comment] 2015-07-21 16:51
Sorry, no. Our use of milestone 3.0 means we would like to get it into the 3.0 final release but that it's not currently planned in any of the betas. Our plates are pretty full.

Now that I'm back from my long vacation, I'll take another look at what @voloda  has done. My first reaction was that he removed ReflectedType at the expense of a complicating some interfaces and that we might actually be able to do without the info provided by ReflectedType. Experimenting, I found that we would eliminate some very useful patterns if we did that, in particular, the ability to specify tests in a base class for use by a derived class and the ability to create parameterized tests in the base that took their data from the derived class. Still, I'd like to avoid passing the Type we are actually dealing with (ReflectedType) around through multiple layers of methods. I'm thinking that some sort of wrapper around Type and MemberInfo might do the job.

**Comment by voloda** [comment] 2015-08-02 19:25
@CharliePoole I was out as well.

At some point you made a comment whether this cannot be taken from test context. Actually - I believe that some sort of context from which you will be able grab all the information about the actual test class might be pretty useful and IMHO cleaner solution from design perspective.

With my limited knowledge I was not able identify the correct way how to approach this.

**Comment by CharliePoole** [comment] 2015-08-02 23:41
@voloda Regarding context, I can't remember the comment I made. We do have a TestExecutionContext, which contains the current test, which has a Type specified. I'm not sure that's very helpful, however, because the context has to do with the execution of tests and most of our reflection takes place before execution begins.

**Comment by voloda** [comment] 2015-08-03 05:53
@CharliePoole Perhaps you could have a context which will be created based on initial information you have and during execution you will clone from it more and more specific context as you have more and more information available?

**Comment by CharliePoole** [comment] 2015-09-05 06:06
PR #797 has now eliminated the user of MemberInfo.ReflectedType from the framework code, eliminating one obstacle to a CoreCLR build.

**Comment by roji** [comment] 2015-09-22 14:11
+1 to this, having NUnit support CoreCLR is critical for projects wanting to support CoreCLR and already using NUnit...

**Comment by richlander** [comment] 2015-09-28 17:32
Hi folks. We're looking at projects that want to target .NET Core / ASP.NET 5. How can we help?

Me, @jeremymeng and @martinwoodward are interesting in helping.

**Comment by rprouse** [comment] 2015-09-28 19:43
@richlander, perfect timing, I was just getting ready to work on our .NET Core support, but I don't have much experience with it beyond a bit of playing around. We currently have a portable version of the framework, so hopefully that codebase is close to targeting Core. I think the biggest challenge will be porting/writing a test runner. Currently our runners spawn off a separate test processes and communicate with those processes through .NET remoting.

What sort of help can you provide? We are hoping to release the RC of NUnit 3 within a few weeks. Full .NET Core / ASP.NET support can follow, but I think it is important that we understand how we will support it and make sure that none of our architecture has backed us into a corner that will be problematic.

My goal for NUnit is that it is available as a full featured test framework for .NET Core. To begin with, I think that includes,

- A version of the framework that targets .NET Core, either directly, or as a part of our portable library
- A console test runner with most or all of the functionality of our current runner.
- If it is possible, add the ability to run unit tests in Visual Studio by extending our [test adapter](https://github.com/nunit/nunit3-vs-adapter)
- Adding project templates to our [template pack](https://github.com/nunit/nunit.templates)

I've been concentrating on our Xamarin support recently, but I think that is just about ready for an initial release, so this is a good time to switch over.

**Comment by stephenstroud** [comment] 2015-10-01 09:52
:+1:  for NUnit 3 and NUnit3TestAdapter RC. Already developing and really wanted this. Look forward to the release.

**Comment by jeremymeng** [comment] 2015-10-01 23:02
@rprouse, the xunit dnx runner (https://github.com/xunit/dnx.xunit/tree/master/src/xunit.runner.dnx) is probably a good example for command-line and VS integration.

The portable library is a good start.  I've done an experimental port at https://github.com/jeremymeng/nunit/commits/netcore.  I was able to get a portable nunit.framework.netcore project building against the `dotnet` profile but haven't got to tests yet.  You can see what the changes are like from my commits.

A question for the conditional compilation symbols.  Some prefer feature-based, e.g., 
```
#if FEATURE_SERIALIZATION
```
while the other option is
```
#if !NETCF && !SILVERLIGHT && !PORTABLE && !NETCORE
```
I've used both in my changes.  There are already usage similar to latter in NUnit projects.  The feature-based approach looks neat.  However it might become hard to manage for multiple projects when a lot of symbols are introduced.  What are your thoughts?

**Comment by rprouse** [comment] 2015-10-02 03:49
@jeremymeng, thanks for doing all that work. I've been plugging away at it too on the branch issue-575 and got to the point of running the tests, but didn't get it working properly. Your fork showed me how to do a few things differently, so I've taken my branch and restarted a new version with some of your code.

If you get to running tests, you will likely run into problems with many of the GetCustomAttributes calls. In .NET Core, they throw if the given type does not derive from Attribute. NUnit searches for attributes based on interfaces, so I had to write my own extensions for getting attributes.

**Comment by jeremymeng** [comment] 2015-10-02 22:03
@rprouse, very glad to know that you have made huge progress on the porting.  Looking forward to a .Net Core release!  I am working on another OSS project now (which also uses NUnit).  But we will help as much as we can if there are any issues blocking you.

Is the exception you are seeing a null ref?  I've hit a bug on `GetCustomAttributes()` returning unexpected null, which might be related.

**Comment by richlander** [comment] 2015-10-12 17:10
@rprouse Did you make any progress on your port? Or should @jeremymeng continue with his? He may start moving that forward just so that we have a complete port. NUnit is super important to get ported to .NET Core! Many projects rely on it.

**Comment by rprouse** [comment] 2015-10-12 18:22
I have a pr ready porting the framework, but still need to get it into the
main solution, add it to the nuget package and create a test runner. I
could use some help with the later once we get the pr reviewed and merged.

**Comment by rprouse** [comment] 2015-10-13 22:44
@richlander and @jeremymeng. I could use some help getting the console runner using our autorunner to compile and run the tests.

I have added a non-working branch as issue-575-c. As you can see, I don't have much experience with DNX yet and I don't think I have my references right. It compiled with the references I had, but without the AutoRun.Execute, but I can't get it to compile with it. I suspect I am just doing things wrong, but I don't have time to do the reading required right now. I am pushing to get this ready for the next beta this week so that we can add at least minimal support for the final 3.0 release.

**Comment by jeremymeng** [comment] 2015-10-13 23:00
@rprouse I am still engaged in other projects this week. Luckily my teammate @chlowell is able to help out.  He is looking at it now.

**Comment by rprouse** [comment] 2015-10-14 01:52
Thanks @jeremymeng and @chlowell, we are pretty swamped right now, so help is welcome. If we can figure out what I am doing wrong, we should be able to get this in the 3.0 release and I will be able to follow up with Visual Studio templates soon after.

**Comment by rprouse** [comment] 2015-10-14 12:47
@chlowell, I pushed a few changed to the branch issue-575-c this morning. Sorry, I was a bit rushed last night. I have removed the extra dependencies in the project.json for the framework PCL and program.cs in the runner is in the correct form. Everything except the runner compiles. None of the NUnit references are picked up, so AutoRun is not found. I've tried adding them as dependencies in project.json and adding them as project references in Visual Studio.

The second problem I have is that when I try to add dnx451 to the frameworks in project.json, I get tons of errors saying things like System.Object is not defined.

I did notice that none of the NUnit assemblies were pulled into the artifacts\bin directory which leads me to believe I am doing the references wrong. Unfortunately, all the examples on the internet assume a clean solution structure, not trying to shoehorn it into an existing structure like this. 

Plus, I'm sitting on the beach with my laptop in the Caribbean, so my motivation to search isn't what it might be. Poor me :smile:

**Comment by CharliePoole** [comment] 2015-10-14 17:58
I see you have a 575-c branch but your PR, which I reviewed, is on 575-b. Too much sun? :-)

**Comment by jeremymeng** [comment] 2015-10-14 19:35
I believe 575-c is a WIP branch where @rprouse is experimenting with dnx projects.

@rprouse are you trying to reference the PCL projects? The only assembly sharing mechanism in Asp.Net 5 is NuGet.  The dll's from the PCL projects cannot be consumed directly.  We will need to wrap each of the dll as described at https://github.com/aspnet/Home/wiki/Project.json-file.

I have an example for Moq: https://github.com/jeremymeng/moq4/blob/netcore-beta5/UnitTests.NetCore/wrapper/Moq/project.json
/cc @chlowell

**Comment by CharliePoole** [comment] 2015-10-14 19:42
Well, mainly, we need to decide what he wants merged now for the beta 5 and
what is ongoing work. I'm thinking that the widespread but simple changes
in 575-b should get in while they can, before other ongoing work starts
creating conflicts we will have to resolve.

**Comment by chlowell** [comment] 2015-10-14 19:49
@rprouse and @jeremymeng I've just pushed chlowell/nunit@de4679d40f62b59866cff9c22d844e2964e232d4 which wraps the PCLs. That got nunit.dnx.tests running. Thanks @MattGal for the analysis and insight.

**Comment by rprouse** [comment] 2015-10-14 20:19
No, 525-c is code I pushed up for the guys at Microsoft to help with trying
to get the nunitlite runner working.

**Comment by rprouse** [comment] 2015-10-15 11:58
@jeremymeng, @chlowell and @MattGal, thanks for the help and those changes. I would have never figured out the wrapping, but it is pretty simple once you see it. I will pull in those changes, make some additions and create a pull request.

**Comment by MattGal** [comment] 2015-10-15 17:18
Glad to help.  I chatted a bit with @davidfowl to make sure that they're aware that the challenges around wrapping the new style PCL continue to be tricky.  If you happen to forget how this works, you can always reverse engineer how to make wrappers by doing the same scenario with a .NET Desktop Class library referenced from a Desktop-only ASP.NET 5 project (in this scenario, simply adding project references makes the wrappers... then just emulate what you see).  I get this is a workaround, but not terrible once you have it set up.

**Comment by jeremymeng** [comment] 2015-10-19 18:20
@bradwilson commented that the current approach does not support Mono (https://github.com/castleproject/Core/issues/90#issuecomment-149287218).  Brad, what's your recommendation on how to add the support?  In a few ports that @MattGal and I did, we were using the PCL projects that target ASP.Net 5 and windows 10. I think those need to be fixed too.

**Comment by CharliePoole** [comment] 2015-10-19 20:30
@rprouse This issue started out with "I tried to create an NUnit test project using Visual Studio 2015 using the ASP.NET 5 class library that uses the Core CLR."

I guess it's time to add a comment with a more precise statements of what (other?) platforms you plan to support. :)

**Comment by rprouse** [comment] 2015-10-19 21:01
@CharliePoole, I have updated the initial comment for this issue with more information.

**Comment by CharliePoole** [comment] 2015-10-19 21:06
@rprouse So not mono? Initially? Ever? :-)

**Comment by akoeplinger** [comment] 2015-10-19 21:08
Once Mono supports the 4.6 profile it should "just work" :)

**Comment by rprouse** [comment] 2015-10-19 21:10
Our current portable framework supports mono, so I don't think we need to
support it in the DNX portable, but if it is needed, then we will add it.

**Comment by CharliePoole** [comment] 2015-10-19 21:13
That's what I figured. Just wanted to get it into the thread. :-)

**Comment by bradwilson** [comment] 2015-10-20 00:31
You need to use an old-school PCL, not a new one. The new style (the ones that use project.json) only supports .NET 4.6.

We (xUnit.net) use PCL 259 (and in one case PCL 111) to ensure that we can support many things, including DNX. Any System.Runtime-based (meaning, .NET 4.5+) PCL should support DNX just fine.

https://github.com/xunit/xunit/blob/master/src/xunit.extensibility.execution.nuspec

**Comment by bradwilson** [comment] 2015-10-20 00:33
> Our current portable framework supports mono, so I don't think we need to support it in the DNX portable, but if it is needed, then we will add it.

The problem is that, if you want `dnx451` on Linux/OS X, you're using Mono. And if you build the DLL with .NET 4.6 as the target, it won't work.

**Comment by rprouse** [comment] 2015-10-21 21:04
Thanks for your advice @bradwilson. In pull request #915, I have switched out existing framework projects over to profile 259 and merged the previous work we did with the DNX projects into those portable projects.

Thanks for your help :+1:

**Comment by CharliePoole** [comment] 2015-10-24 15:47
@rprouse I was going to push something on this, but I see you have marked it pending. Was that just intended to be "pending for me, while charlie works?" :-)

**Comment by CharliePoole** [comment] 2015-10-24 16:15
So, the main problem with CF is that some of the tests verify that calls on Type work under CF, which simply don't work. That's to do with generics primarily. The key limitation in CF is that you cannot call a number of methods, which work perfectly fine on the desktop, if you are dealing with an open generic type.

The simple fix would be to remove the tests and I may do that. A longer-term fix would be to use extension methods in CF rather than the separately defined utility methods we now use.

**Comment by CharliePoole** [comment] 2015-10-24 16:55
OK... you are not hitting one of the "big" differences but what appears to be a minor one.

It looks as if CF will return private members of a base class if you specify BindingFlags.NonPublic, while the other implementations will not. @oznetmaster can you confirm this is a difference?

Actually, this set of tests is a good start to our understanding how CF reflection differs, something we don't entirely get even now.

**Closed** 2015-10-24 20:32 UTC
Labels: is:feature, pri:normal, status:pending

**Comment by roji** [comment] 2015-10-24 22:06
It's great to see this happening. I'm hoping you guys also plan on providing a DNX command to execute unit tests, like xunit does. Is this being tracked somewhere already?

**Comment by CharliePoole** [comment] 2015-10-24 23:35
Feel free to file an issue!

**Comment by RehanSaeed** [comment] 2015-11-16 17:25
Is there a sample project I can look at?

**Comment by rprouse** [comment] 2015-11-16 17:28
@RehanSaeed take a look at http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/

Source code for that blog post is at https://github.com/rprouse/NUnitDnxTest

**Comment by RehanSaeed** [comment] 2015-11-16 17:41
@rprouse I'm getting the following error using NUnitLite:

```
------ Discover test started ------
------ Test started: Project: Bridge.Framework.Test ------
Starting  Microsoft.Dnx.TestHost [C:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe --appbase "C:\MyProject\Tests\MyProject.Test" Microsoft.Dnx.ApplicationHost --port 49968 Microsoft.Dnx.TestHost --port 52533 --parentProcessId 37296]

Error: Unable to load application or execute command 'Microsoft.Dnx.TestHost'. Available commands: test.
Unable to start Microsoft.Dnx.TestHost
========== Discover test finished: 0 found (0:00:01.0405634) ==========
```

**Comment by rprouse** [comment] 2015-11-16 17:58
@RehanSaeed, It looks like you are trying to run the tests using the Visual Studio Test. That is not supported yet. If you follow my blog post, you need to create a DNX executable and run that from the command line.

**Comment by garora** [comment] 2016-06-28 20:15
@rprouse - is it [Testing .NET Core using NUnit 3](http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/)  valid for .net core 1.0.0. I am planning to port my existing tests [FizzBuzzKata](https://github.com/garora/TDD-Katas/tree/develop/Src/cs/FizzBuzzKata) to .net core.

**Comment by rprouse** [comment] 2016-06-28 20:38
@garora I would recommend looking at [NUnit 3 Tests for .NET Core RC2 and ASP.NET Core RC2](http://www.alteridem.net/2016/06/18/nunit-3-testing-net-core-rc2/) which is the latest. It is currently up to date for RC2 and I think it will work with the RTM. I am in the process of updating `dotnet-test-nunit` to the RTM now. It should be out within the day.

The NUnitLite style you linked to will also work, it just isn't the way it is done in .NET Core :smile:

**Comment by garora** [comment] 2016-06-29 14:12
Thanks for updates! I will wait for latest build of nunit.
