### ISSUE TITLE
Failed test with Timeout attribute fails with AggregateException

### ISSUE THREAD

**Issue by epitavy** [nunit/nunit#3507] opened 2020-03-18 17:57 UTC
Because tests with the Timeout attribute are wrapped in Task, when any exception is thrown, it is wrapped within an AggregateException. Thus, whatever the reason for the failure (AssertionException or any other exception) the failed tests with a timeout always fails with an AggregateException. Is is quite annoying to analyse quickly the errors.
However, when a test succeed, is totaly ok.

**_NUnit version : 3.12 with Rider on MacOS 10.15.3_**

```Tests.Tools.LetterIndex.LowerCase(25)

System.AggregateException : One or more errors occurred. (Rethrown)
  ----> NUnit.Framework.Internal.NUnitException : Rethrown
  ----> NUnit.Framework.AssertionException :   Expected: 25
  But was:  0

   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at NUnit.Framework.Internal.Commands.TimeoutCommand.Execute(TestExecutionContext context)
--NUnitException
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
   at NUnit.Framework.Internal.MethodWrapper.Invoke(Object fixture, Object[] args)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.InvokeTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass2_0.<Execute>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--AssertionException
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
   at Tests.Tools.LetterIndex.LowerCase(Int32 index) in path/to/my/files/test.cs```

**Comment by rprouse** [comment] 2020-05-18 18:08
Adding a confirm label to ensure that it is not an issue with Rider.

**Comment by mikkelbu** [comment] 2020-09-21 19:01
Looking at the stacktrace, I can see that the AssertionException is nested inside an AggregateException, so this could be a duplicate of #3282. Which framework are you targeting? (because I think that this might fail on dotnetcore until 3.13 is released).

EDIT: Does it work if you use the prerelease build of the NUnit framework (from https://www.myget.org/feed/nunit/package/nuget/NUnit) instead of 3.12.0 ?

**Comment by rprouse** [comment] 2021-04-30 16:20
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Closed by rprouse** 2021-04-30 16:20 UTC
Labels: confirm
