### ISSUE TITLE
Engine extensions load old packages

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1427] opened 2016-04-20 06:33 UTC
As reported by @asbjornu in #1323 

I just upgraded `NUnit.ConsoleRunner` from version `3.2.0` to version `3.2.1` and got the following output from `nunit3-console.exe` that I haven't seen before:

```
NUnit Console Runner 3.2.1
Copyright (C) 2016 Charlie Poole

ProjectLoader extension .nunit is already handled by another extension.
```

The workaround was to delete NuGet packages in the packages directory and restore. The engine plugin resolution was probing the old 3.2.0 packages that were left on the system after an upgrade.

I think the solution is that as we are probing for engine extensions we need to look at the directory names, parse out the package name/version and discard directories where there are newer versions.

**Comment by rprouse** [comment] 2016-04-20 06:37
I meant to link  to #1323, I have updated the issue above.

**Comment by asbjornu** [comment] 2016-04-20 07:13
@rprouse Thanks. Just my two cents of input: It might be more robust to not base the version number discovery on the folder name, as that's something NuGet can change on a whim. Extracting it from the `.nupkg` is more tedious, but should be less brittle, should NuGet choose to do anything about the folder layout.

**Comment by rprouse** [comment] 2016-04-20 07:52
@asbjornu that is a good suggestion. Thanks.

**Comment by CharliePoole** [comment] 2016-05-04 01:53
It seems as if this is also a nuget bug. Old packages cannot always be replaced since the old version may used by one project and the new one by another. But the user should have some way to specify whether full replacement is to take place or not.

For our part, we should find all extensions as we now do, but examine them in the end to remove those that are outdated. Currently, an extension point does not define whether it supports multiple extensions at the same time or only one. The distinction is made in the code that actually uses the extension. We may want to add that information to the extension point so it can be used when loading extensions.

If only one copy of an extension is supported, then we should be able to check easily enough to see if multiple extensions are found and issue an error message. It would not matter if the extensions found were multiple versions of the same one or different extensions.

But if multiple extensions are supported at a particular point, then we need a way to uniquely identify each extension. We could parse the nuget package as suggested or simply use the assembly name.

Note that some extension points already implement their own error checking in addition. For example, no two project loader extensions are permitted to specify the same file extension. This would remain unchanged.

**Comment by CharliePoole** [comment] 2016-06-18 19:27
I have a preliminary version of this. It's based on two concepts:

1. One assembly is a duplicate of another if the two AssemblyName.Names are equal. One could test other things, but this seems to be the most practical.

2. Of two duplicates, the better version is the one with the higher AssemblyName.Version.

The second point presents one small problem: we have not been versioning our own extensions internally. Up to now, the are all version 1.0.0.0. In this case, the first one found will be used.

I'm thinking of adding one more check: if the name of the assembly was fully spelled out (no wildcards involved) I'll give that one priority. That would allow a user to make sure a specific version was used.

I'm not inclined to look at the nuget package version or folder name. That will be a bit messy and will only work for nuget packags. Instead, I think we should make sure to version the assemblies in the future.

Thoughts guys?

**Comment by rprouse** [comment] 2016-06-18 23:58
This should work if we increment the version for 3.4. Going forward, these will be moved to a new repo. Once we do tht, maybe we should only release new versions for fixes?

**Comment by CharliePoole** [comment] 2016-06-19 00:13
That makes sense. Right now, I'm facing a problem I hadn't expected, which is that an older extension can't resolve the latest engine api. I'll have to look and see what changes we made since 3.2.1.

**Comment by asbjornu** [comment] 2016-06-20 10:23
@CharliePoole That sounds like a reasonable algorithm. But it would be nice if extensions were properly semantically versioned going forward, no? [GitVersion](https://github.com/GitTools/GitVersion) can help automate that.

**Comment by CharliePoole** [comment] 2016-06-20 23:35
@asbjornu I looked at GitVersion at one point, but everything seemed to be working OK for us without it. I may take another look. Because we have one solution with multiple, separately released, assemblies being produced, we don't want to use an approach that makes blanket changes to all our assemblyinfos.

**Comment by asbjornu** [comment] 2016-06-21 06:59
@CharliePoole This is probably not the right place to discuss GitVersion, but you have a lot of options and configurability in how you want it to version your assemblies. You can use an MSBuild task in place of checked-in `Assembly*Version`, you can use `GitVersion.exe` to patch `AssemblyInfo` files on request and then commit those or use the `.exe` to patch existing `AssemblyInfo` files in a CI build.

What I like the most is using `GitVersionTask` and not having a version number committed to source control at all, so GitVersion is responsible for generating a version number from the git flow and nothing or no one else. That makes a commit produce the same version number across all build environments, no matter if it's a developer's machine or the CI server.

**Closed** 2016-06-21 13:04 UTC
Labels: is:bug, pri:critical

**Comment by CharliePoole** [comment] 2016-06-23 01:50
@asbjornu I'll send you an email about GitVersion...

**Comment by asbjornu** [comment] 2016-06-23 17:29
@CharliePoole: Sure!
