### ISSUE TITLE
Expression-based Has.Property

### ISSUE THREAD

**Issue by outring** [nunit/nunit#473] opened 2015-01-27 09:24 UTC
It would be great if `Has.Property` would have expression-based version (to avoid strings):
```
Assert.That(obj, Has.Property<String>(x => x.Length).EqualTo(5))
```

**Comment by CharliePoole** [comment] 2015-01-27 23:23
It's an interesting idea. Needs some experimentation to see how to make it work before promoting it to an actual enhancement.

**Comment by CharliePoole** [comment] 2015-02-21 05:42
Actually a duplicate of #26

**Closed** 2015-02-21 05:42 UTC
Labels: closed:duplicate, is:idea

**Comment by jeme** [comment] 2015-11-16 10:06
This one would require a bit less effort to add though...

If "Has" was easy extensible that would be a easy trick, for now we have:

HAS....

```
        public static ResolvableConstraintExpression Property<T>(Expression<Func<T, object>> property)
        {
            return new ConstraintExpression().Property(property.GetPropertyInfo().Name);
        }
        
        public static ResolvableConstraintExpression Property<TSource, TProperty>(Expression<Func<TSource, TProperty>> expression)
        {
            return new ConstraintExpression().Property(expression.GetPropertyInfo().Name);
        }


    public static class ReflectionExtensions
    {
        /// <summary/>
        public static PropertyInfo GetPropertyInfo<TSource, TProperty>(this Expression<Func<TSource, TProperty>> propertyLambda)
        {
            Type type = typeof(TSource);

            MemberExpression member = propertyLambda.Body as MemberExpression;
            if (member == null)
            {
                UnaryExpression convert = propertyLambda.Body as UnaryExpression;
                if (convert != null && convert.NodeType == ExpressionType.Convert)
                    member = convert.Operand as MemberExpression;
                if (member == null)
                {
                    throw new ArgumentException(string.Format("Expression '{0}' refers to a method, not a property.", propertyLambda));
                }
            }

            PropertyInfo propInfo = member.Member as PropertyInfo;
            if (propInfo == null)
                throw new ArgumentException(string.Format("Expression '{0}' refers to a field, not a property.", propertyLambda));

            Debug.Assert(propInfo.ReflectedType != null, "propInfo.ReflectedType != null");
            if (type != propInfo.ReflectedType && !type.IsSubclassOf(propInfo.ReflectedType))
                throw new ArgumentException(string.Format("Expresion '{0}' refers to a property that is not from type {1}.", propertyLambda, type));

            return propInfo;
        }

    }
```

**Comment by CharliePoole** [comment] 2015-11-16 15:14
I hadn't thought of making a simple front end to the standard PropertyConstraint. We usually don't put that much logic into our static helpers. This might be a good quick solution until someone comes along who wants to put the time into a deeper solution.
