### ISSUE TITLE
NullReferenceException while loading tests with ValueSource attribute referencing superclass

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1155] opened 2015-12-23 16:39 UTC
Have just upgraded from nUnit 2.5.7 to nUnit 3, and tests with the below structure now throw an exception on loading. The IEnumerable being in the Superclass appears to be the issue. Is this intended? It isn't one of the conditions for ValueSource specified in the docs.

````c#
    [TestFixture]
    public class SubClass : SuperClass
    {
        [Test]
        public void Test([ValueSource(nameof(TestCase))] bool testAnswer)
        {
            Assert.IsTrue(testAnswer);
        }
    }


    public class SuperClass
    {
        protected static IEnumerable<bool> TestCase
        {
            get { yield return true; }
        }
    }
````
````
An exception was thrown while loading the test.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.Builders.ParameterDataSourceProvider.GetDataFor(IParameterInfo parameter)
   at NUnit.Framework.CombiningStrategyAttribute.BuildFrom(IMethodInfo method, Test suite)
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData)
   at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__48.MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)
````

**Comment by CharliePoole** [comment] 2015-12-23 16:59
We use this pattern (data in the base class) extensively in NUnit's own tests. What happens if you replace nameof(TestCase) with "TestCase"?

**Comment by ChrisMaddock** [comment] 2015-12-23 17:03
Hi Charlie,

nameof() vs a string name is no different. I should add I'm running this with nUnit 3.0.1, direct in the console.

**Comment by CharliePoole** [comment] 2015-12-23 17:13
Too bad. i was hoping it was a compiler bug. :-)

**Comment by rprouse** [comment] 2015-12-23 18:08
This is a duplicate of #1109. In that issue, a workaround was given,

```C#
    [TestFixture]
    public class SubClass : SuperClass
    {
        [Test]
        public void Test([ValueSource(typeof(SuperClass), nameof(TestCase))] bool testAnswer)
        {
            Assert.IsTrue(testAnswer);
        }
    }

    public class SuperClass
    {
        protected static IEnumerable<bool> TestCase
        {
            get { yield return true; }
        }
    }
```

**Closed by rprouse** 2015-12-23 18:08 UTC
