### ISSUE TITLE
[OneTimeSetUp] does not run if [TestFixture] does only contain [Theory]-s and no [Test]s

### ISSUE THREAD

**Issue by kostix** [nunit/nunit#809] opened 2015-09-15 17:33 UTC
The problem manifests itself if:

* There's a class marked with `[TestFixture]` which contains:
    * A method marked with `[OneTimeSetUp]`
    * A method marked with `[DatapointSource]`
    * A method marked with `[Theory]` (matching that datapoint source method)
* This text fixture class does *not* contain any method marked as `[Test]`.

In this case, the theory is attempted to be proven by executing its datapoint sources but the method marked with `[OneTimeSetUp]` is not run.

Hence if the method generating datapoints depends on that setup method having been run, it fails.

If I add at least one method marked with `[Test]` to this fixture class, the setup method runs.

An MCVE:

```C#
namespace My.Tests
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Data.SqlClient;
    using NUnit.Framework;

    [TestFixture]
    public class SampleTests
    {
        SqlConnection conn;

        [OneTimeSetUp]
        public void Setup()
        {
            var cs = ConfigurationManager.ConnectionStrings["Test"];
            if (cs == null) {
                throw new InvalidOperationException("No connection string");
            }

            conn = new SqlConnection(cs.ConnectionString);
            conn.Open();
        }

        [OneTimeTearDown]
        public void Teardown()
        {
            conn.Close();
        }

        public struct MyRowData
        {
             // omitted for brewity
        }

        [DatapointSource]
        public IEnumerable<MyRowData> fetchAllRows()
        {
            const string sqlText = @"SELECT * FROM Northwind";

            var stmt = new SqlCommand(sqlText, conn);
            using (stmt) {
                var rd = stmt.ExecuteReader();
                using (rd) {
                    while (rd.Read()) {
                        yield return ParseRowData(rd);
                    }
                }
            }
        }

        //[Test]
        public void DoNothing()
        {
            // Does nothing, intentionally
        }

        [Theory]
        public void Test1(MyRowData entry)
        {
            Assert.That(1, Is.EqualTo(1));
        }
    }
}
```

This code uses `SqlClient` to fetch the data from a sample table and run the theory-testing method on it.

As is, this this code will fail because `fetchAllRows()` needs the setup method to set the database connection up.

If we uncomment the `[Test]` attribute on `DoNothing()`, the setup function will run.

I fathom than NUnit should supposedly treat methods marked with `[Theory]` to also trigger the need to run the functions marked with `[OneTimeSetUp]` before those methods are run.

**Comment by kostix** [comment] 2015-09-15 17:37
I'm running NUnit 3.0.5674.19278 under .NET 4.0 on 32-bit Windows XP SP3.
I think that's NUnit 3.0.0 beta3.

**Comment by CharliePoole** [comment] 2015-09-15 18:17
@rprouse I think this could be related to a bug you just fixed, so I assigned it to you.

**Comment by rprouse** [comment] 2015-09-15 18:44
@CharliePoole, I will look at this next.

**Comment by rprouse** [comment] 2015-09-16 21:54
@kostix, I tested this with a simplified version of your code. I am pretty sure that this shows that the issue is fixed in the current codebase. Can you see anything wrong with my version of the code or with PR #810?

```C#
[TestFixture]
public class SetUpAndTearDownFixtureWithTheories
{
    public int setUpCount = 0;
    public int tearDownCount = 0;

    [OneTimeSetUp]
    public virtual void Init()
    {
        setUpCount++;
    }

    [OneTimeTearDown]
    public virtual void Destroy()
    {
        tearDownCount++;
    }

    public struct Data
    {
        public int Id { get; set; }
    }

    [DatapointSource]
    public IEnumerable<Data> fetchAllRows()
    {
        yield return new Data { Id = 1 };
        yield return new Data { Id = 2 };
        yield return new Data { Id = 3 };
        yield return new Data { Id = 4 };
    }

    [Theory]
    public void TheoryTest(Data entry)
    {
        Assert.Pass("Passed with theory id {0}", entry.Id);
    }
}
```

**Comment by rprouse** [comment] 2015-09-19 18:30
Closing based on PR #810

**Closed by rprouse** 2015-09-19 18:30 UTC
Labels: is:bug, pri:high, status:confirm
