### ISSUE TITLE
specifying solution and --agents is not working with nunit3-console

### ISSUE THREAD

**Issue by pcalin** [nunit/nunit#1389] opened 2016-04-05 02:39 UTC
nunit3-console Test.sln --agents=NUMBER

does not limit number of agents

**Comment by CharliePoole** [comment] 2016-04-05 02:47
Is that your entire command line? The --agents option has no meaning unless you are running assemblies in parallel.

**Comment by pcalin** [comment] 2016-04-05 04:07
So how do I limit the number of agents when I test a solution? 


Sent from my Samsung Galaxy smartphone.-------- Original message --------From: CharliePoole <notifications@github.com> Date: 5/04/2016  10:47  (GMT+08:00) To: nunit/nunit <nunit@noreply.github.com> Cc: Calin <pcalin@yahoo.com> Subject: Re: [nunit/nunit] specifying solution and --agents is not working
  with nunit3-console (#1389) 
Is that your entire command line? The --agents option has no meaning unless you are running assemblies in parallel.

**Comment by pcalin** [comment] 2016-04-05 04:08
But I am running assembles in parallel. 


Sent from my Samsung Galaxy smartphone.-------- Original message --------From: CharliePoole <notifications@github.com> Date: 5/04/2016  10:47  (GMT+08:00) To: nunit/nunit <nunit@noreply.github.com> Cc: Calin <pcalin@yahoo.com> Subject: Re: [nunit/nunit] specifying solution and --agents is not working
  with nunit3-console (#1389) 
Is that your entire command line? The --agents option has no meaning unless you are running assemblies in parallel.

**Comment by CharliePoole** [comment] 2016-04-05 04:30
NUnit runs one assembly at a time when using the default ProcessModel setting (Multiple). In order to run assemblies in parallel, you must specify --process:Parallel. If you do that, __all__ assemblies will run in parallel __unless__ you limit the number of agents.

Are you sure you are running assemblies in parallel? That's not the same thing as having parallel threads executing your tests, under control of the ParallelizableAttribute.

Please supply some more info about what you are doing and especially about what leads you to believe you have multiple assemblies running in parallel.

**Comment by pcalin** [comment] 2016-04-05 05:07
My solution has 50 projects. I see 50 nunit-agents running in parallel. 


Cheers, Călin -------- Original message --------From: CharliePoole <notifications@github.com> Date: 5/04/2016  12:30  (GMT+08:00) To: nunit/nunit <nunit@noreply.github.com> Cc: Calin <pcalin@yahoo.com> Subject: Re: [nunit/nunit] specifying solution and --agents is not working
  with nunit3-console (#1389) 
NUnit runs one assembly at a time when using the default ProcessModel setting (Multiple). In order to run assemblies in parallel, you must specify --process:Parallel. If you do that, all assemblies will run in parallel unless you limit the number of agents.

Are you sure you are running assemblies in parallel? That's not the same thing as having parallel threads executing your tests, under control of the ParallelizableAttribute.

Please supply some more info about what you are doing and especially about what leads you to believe you have multiple assemblies running in parallel.

**Comment by pcalin** [comment] 2016-04-05 05:23
How can I run all tests in my solution using nunit3-console without creating 50 nunit-agents in one hit?

Cheers,
Calin

**Comment by CharliePoole** [comment] 2016-04-05 05:40
The existence of 50 processes doesn't mean your tests are run in parallel. NUnit first loads all the tests. Then it runs them one at s time. The processes exist at the same time but only one at a time actually executes code.

I can see however that you would expect the agent option to do something to limit this. Do you actually see any performance issue beyond the delay in creating all the projects?

**Comment by pcalin** [comment] 2016-04-05 05:50
I see...

Yes. My computer halts to a crawl.
I can however see a few agents (about 4) running at the same time. each taking around 20% cpu which is what lead me to believe they were running in parallel.

Any way to limit the number of agents in the future?

Cheers,
Calin

**Comment by pcalin** [comment] 2016-04-05 05:53
If I specify --process:Separate I get one agent and it takes 3 minutes to run all tests.

If I specify --process:Multiple I get 50 agents and running tests takes about 30 minutes.

Auch.

**Comment by rprouse** [comment] 2016-04-05 14:40
@CharliePoole do you think we should limit the number of agents we start up to the number that we are currently running? In other words, don't start the agent until we are ready to run the tests. I've seen  the same issue as @pcalin at work where an agent gets started per test suite even though only four are running at a time. For us, this is putting memory pressure on the machine causing paging.

**Comment by CharliePoole** [comment] 2016-04-05 15:26
@rprouse @pcalin had a fairly obvious interpretation in what he expected the `--agents` option to do. As a first step we should make it clear in the docs.

But I agree we should do more. The problem is that it's a fundamental architectural issue and not so trivial to change. As you know, we initially load (create) the tests using the same process and domain structure as we intend to run them. That allows persistence of the tests from load-time to run-time and across multiple runs. Currently, this is essential for the gui. It's not really needed by the console, however, so we could create some sort of engine option to use a different model. That is...

1. A batch-like model, where each assembly is first loaded and then run.
2. An interactive model, where all assemblies are loaded first and subsequently run.

My suggestion is that we focus this issue on solving the problem for the console runner, which is where it's being reported anyway.

The rest of this comment aims at the GUI and the problems which need to be solved if we want to prevent the proliferation of agents under the GUI runner. This is probably less of a problem for users, since they can simply load the particular assemblies they are working on.

We already have some experience with a gui model where the tests do not persist between load time and run time. That's with the vs adapter. Under the adapter, discovery (NUnit's test load) takes place in one process and execution takes place in a separate one. Since there is no communication between the processes, which have different lifetimes anyway, the execution actually has to re-discover (re-load, re-create) the tests. Any tests that are generated non-deterministically, as with the Random attribute, are typically created differently the second time! If we want to separate loading from running in the engine itself, we are going to have to solve that problem.

I think we should address this second problem as well, but on a more long-range time-frame, as development of our GUI progresses, as well as in the VS adapter.

**Comment by ChrisMaddock** [comment] 2016-08-10 16:28
@CharliePoole - was this resolved by #1718? :smile:

**Comment by CharliePoole** [comment] 2016-08-10 17:07
Yup! :-)

**Closed** 2016-08-10 17:09 UTC
Labels: enhancement, pri:normal
