### ISSUE TITLE
only first category showing up in visual studio test explorer

### ISSUE THREAD

**Issue by IanMcRV** [nunit/nunit#1495] opened 2016-05-12 15:50 UTC
so if I do:

[Test]
[Category("Cat1")]
[Category("Cat2")]

I'll only see:
Category [Cat1]
in the test explorer

**Comment by rprouse** [comment] 2016-05-12 18:36
Thanks for the report. This is a duplicate of nunit/nunit-vs-adapter#108

**Closed by rprouse** 2016-05-12 18:36 UTC
