### ISSUE TITLE
TimeoutAttribute missing after using dotnet-test-nunit and 3.4.1

### ISSUE THREAD

**Issue by danielwertheim** [nunit/nunit#1658] opened 2016-07-11 19:40 UTC
Upgrading/migrating to `dotnet-test-nunit` and 3.4.1 and then `TimeoutAttribute` was not found anymore.

**Comment by CharliePoole** [comment] 2016-07-11 19:42
Issue moved to [nunit/dotnet-test-nunit #47](https://github.com/nunit/dotnet-test-nunit/issues/47) via [**ZenHub**](https://www.zenhub.com/)

**Comment by danielwertheim** [comment] 2016-07-11 19:47
Sorry, will report there from here on forward.

**Comment by rprouse** [comment] 2016-07-11 19:49
Actually, I am going to reopen this here and close the other issue. It has nothing to do with the runner, it is because .NET Core currently uses the Portable version of the NUnit Framework,

>This is a known issue, Timeout was not included in the PCL (Portable) version of the framework because timing out a test requires threading and threads are not available in most PCL profiles. We are hoping to reintroduce as much of the lost functionality as possible in the next release by converting the PCL version of NUnit to a .NET Standard target.

**Comment by danielwertheim** [comment] 2016-07-11 19:49
Is there a simple way to add this manually for now?

**Comment by CharliePoole** [comment] 2016-07-11 21:09
@rprouse Do you see the resolution of this as being in the portable build or is this about creating a new build?

**Comment by rprouse** [comment] 2016-07-12 00:47
@CharliePoole I see the resolution in adding a `netstandard1.x` build of the framework, probably `netstandard1.3`. .NET Standard is intended to replace portable and now that the tooling is updated on all platforms, it supports all targets that our Portable build targets, but gives us access to more APIs which will allow us to re-enable many features that were dropped from the Portable version of the Framework like Timeout, Platform, File and Directory asserts, etc.

I will enter at least a placeholder issue. I plan to tackle this after we split the repos though.

**Comment by danielwertheim** [comment] 2016-07-12 04:10
@rprouse I'll wait. No worries.

**Comment by ChrisMaddock** [comment] 2017-01-27 10:40
Duplicate of #1638

**Closed by ChrisMaddock** 2017-01-27 10:40 UTC
Labels: is:enhancement, pri:normal
