### ISSUE TITLE
Add command line option to run every test on its own thread

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1488] opened 2016-05-10 22:03 UTC
Removing the fix that I added to run every test on its own thread has broken the ability to forcefully stop many test runs.  In my case, the majority of them.

The removal of the original fix was done to fix issues with tests that needed consistent threads for STA/MTA specific tests, and for tests that needed to run the one time setup on the same thread as the test itself.

I have never had a test suite with either requirement.

It would seem reasonable to have a command line option to put back the thread/test functionality, which allows the absolute forced termination of most tests.

**Comment by CharliePoole** [comment] 2016-05-11 06:50
Although the title specifies timeouts, I believe #1363 deals with this as well.

To the extent possible, NUnit should run tests as it sees fit, with options provided for special user needs. In this case, we would be adding an option to work around a fundamental problem in NUnit itself. We should instead fox the problem.

**Comment by CharliePoole** [comment] 2016-05-11 06:54
Related: I haven't searched (on my phone) but I think we also have an issue asking that we create an attribute causing all tests in a fixture to run on separate threads.

**Comment by oznetmaster** [comment] 2016-05-11 07:06
That would require adding that attribute to every fixture in the test suite, unless it would also work at the assembly level?

**Comment by CharliePoole** [comment] 2016-05-11 07:19
I'm just saying it's related. It's not a solution to the cancellation problem.

**Comment by CharliePoole** [comment] 2016-06-24 18:08
I'd like to close this as won't fix. The problem is that we can't cancel reliably. We have an issue for that. Going back to a thread per test is a backward step even though it's an easy way to resolve that particular problem. I think we need to tackle the harder problem of cancelling without using an extra thread.

@rprouse ? 
@oznetmaster ?

**Comment by rprouse** [comment] 2016-06-24 20:41
I am in favour of closing. I know @oznetmaster has a special case, but the way I think of it, if your test is running too long or hung, you kill the process. A GUI that can cancel individual tests might be nice, but to me it is an edge case that I wouldn't want to compromise the framework for.

**Comment by oznetmaster** [comment] 2016-06-24 20:58
If you kill the process, you lose all the results up to that point.  There needs to be a way to cleanly stop/abort the test run.

I thought the GUI needed this as well?

**Comment by oznetmaster** [comment] 2016-06-24 21:00
I am fine with actually fixing the problem, but running each test on its own thread was a simple fix until a real one can be found.

**Comment by CharliePoole** [comment] 2016-06-24 23:38
Even if we did this, our users would not benefit. Neither the console runner nor nunitlite provide a way to _request_ such a cancellation.

In any case, I'd rather see somebody put time on the actual solution as designed.

**Comment by CharliePoole** [comment] 2016-06-24 23:40
At any rate, I mentioned this because of the work we are doing cleaning up issues that are going nowhere. This shows up as a "New Issue" that has actually been around for a few months.

**Comment by rprouse** [comment] 2016-10-25 12:50
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.

**Closed by rprouse** 2016-10-25 12:50 UTC
Labels: is:idea, review
