### ISSUE TITLE
a few of my tests that are convoluted finish as inconclusive for no apparent reason

### ISSUE THREAD

**Issue by crichmond23** [nunit/nunit#2941] opened 2018-07-21 02:50 UTC
I don't use Assert.Inconclusive anywhere.

I've been writing/rewriting/refactoring a set of tests. I used to rely on hard coded test data. but for these particular tests (I'll call forloop tests) I acquire the test parameters at runtime.

I've had difficulty attempting to populate NUnit test parameters with data collected at runtime. So instead, I made one test that runs through the list of parameters that are acquired at run time (poor man's fix -- and that is a separate topic).

However, now some of those tests complete as if the final result was an Assert.Inconclusive. I've commented the Parallelizable attribute. I've tried running each tests individually. I've even ran a test in debug mode and stepped through each line of code. right when the test resolves, no 'new' success or 'new' failure, just an 'old' (grayed-out) 'test hasn't been run yet'.

I'm befuddled.  Any help that can be provided will be greatly appreciated.

Please let me know if more information is required.

Chris

**Comment by CharliePoole** [comment] 2018-07-21 07:53
The test result includes an enumerated whose default value is Inconclusive. It sounds as if something in the way you run the tests is leaving it at the default value.

**Comment by mikkelbu** [comment] 2018-07-21 14:47
Hi @crichmond23 

Can you provide a minimal code example?

For me it sounds like you datasource do not provide the same data each time. And my understanding of the NUnit Test Adapter in VS is that it first performs a discovering phase were it discovers all the tests and the if you run the tests (not "run all") it will not work if the tests are no longer the same (meaning having the same input) as when they were discovered.

Example
```csharp
using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace ClassLibrary12
{
    [TestFixture]
    public class Class1
    {
        static IEnumerable<DateTime> GetDateTimes()
        {
            yield return DateTime.Now;
        }

        [TestCaseSource(nameof(GetDateTimes))]
        public void MyTest(DateTime now)
        {
            Assert.That(now, Is.GreaterThan(DateTime.MinValue));
        }
    }
}
```
If I build this I get 
![image](https://user-images.githubusercontent.com/1007631/43036530-02d8a96e-8d04-11e8-996e-51ad6e5fab57.png)

And if I then try to run Selected Tests a couple of seconds later in ClassLibrary12 then I get
![image](https://user-images.githubusercontent.com/1007631/43036537-22fb1c0e-8d04-11e8-827e-b016763d9e36.png)

The problem is that the source of the test no longer provide the same data `....16:34:10` (but instead some new data). Hence the testcase cannot be executed. You can also see indication of this in the Output pane in VS under the category Tests (see that it discovers one test, but does not run any tests)

```
[21/07/2018 16:34:10 Informational] ------ Discover test started ------
[21/07/2018 16:34:10 Informational] NUnit Adapter 3.10.0.21: Test discovery starting
[21/07/2018 16:34:11 Informational] NUnit Adapter 3.10.0.21: Test discovery complete
[21/07/2018 16:34:11 Informational] ========== Discover test finished: 1 found (0:00:00.8864955) ==========
[21/07/2018 16:34:28 Informational] ------ Run test started ------
[21/07/2018 16:34:29 Informational] NUnit Adapter 3.10.0.21: Test execution started
[21/07/2018 16:34:29 Informational] Running selected tests in C:\Users\Mikkel\Source\Repos\ClassLibrary12\ClassLibrary12\bin\Debug\ClassLibrary12.dll
[21/07/2018 16:34:29 Informational] NUnit3TestExecutor converted 1 of 1 NUnit test cases
[21/07/2018 16:34:29 Informational] NUnit Adapter 3.10.0.21: Test execution complete
[21/07/2018 16:34:29 Informational] ========== Run test finished: 0 run (0:00:00.8538755) ==========
```

**Comment by crichmond23** [comment] 2018-07-21 23:31
Minimal Code Example:


	...
	
	[TestFixture]
	public class MyForLoopTests
	{
		[Setup]
		public async Task SetUp()
		{
			...
		}
		
		[TearDown]
		public void TearDown()
		{
			...
		}
				
		[Test]
		public async Task CombinedForLoopTest()
		{
			var firstDataList = UtilityClass.GetFirstDataParameters();
			foreach (var firstData in firstDataList)
			{
				try
				{
					await OriginalTest(firstData);
				}
				catch {Exception exc)
				{
				}
			}
		}
		
		// because I couldn't parameterize the data acquired from GetFirstDataParameters
		public async Task OriginalTest(string firstData)
		{
			var secondDataList = UtilityClass.GetSecondDataParameters();
			foreach (var secondData in secondDataList)
			{
				try
				{
					await FunctionalityOriginalTest(firstData, secondData);
				}
				catch (Exception exc)
				{
				}
			}
		}

		// where the magic happens
		public async Task FunctionalityOriginalTest(string firstData, string secondData)
		{
			// perform the test
			...
		}
	}

	...
	
Hopefully you can spot something wrong.

**Comment by crichmond23** [comment] 2018-07-21 23:34
The data is acquired rarely changes, but is different for different environments.
My goal was to avoid using hard coded data when not necessary.

**Comment by CharliePoole** [comment] 2018-07-22 07:33
@crichmond23 Can you confirm @mikkelbu 's assumption that this is a VS adapter problem? How you are running tests is a key bit of info to provide for any issue.

If you are using the adapter, then try running with the console runner to help localize the problem.

**Comment by CharliePoole** [comment] 2018-07-22 14:13
The most common cause of the problem described by @mikkelbu is the use of randomly generated data for some of your arguments. Under VS, that generation is forced to take place twice and the second set of data will not match.

If that's the case, use NUnit TextContext.Random rather than the native implementation. NUnit makes sure to use the same seed for each discovery phase.

**Comment by crichmond23** [comment] 2018-07-22 15:17
The problem might be with the VS adapter.  The thing is that, in the sample code I provided, I don't specify any NUnit test parameters.

But yes, I use the VS NUnit test adapter.  I will try the console runner.

**Comment by crichmond23** [comment] 2018-07-22 15:18
no random values are currently being used.

**Comment by crichmond23** [comment] 2018-07-22 16:16
Also, if you look at my code example, I don't use data parameters for the particular tests.

**Comment by rprouse** [comment] 2020-05-18 19:29
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 19:29 UTC
