### ISSUE TITLE
Testfixture outside assembly is not executed

### ISSUE THREAD

**Issue by MMark4** [nunit/nunit#4109] opened 2022-04-30 18:00 UTC
When I try to utilize the TestFixture annotation to execute code before and after running ALL the tests the OneTimeSetUp and OneTimeTearDown annotations are not being run

Update: Tried with net5.0 and same outcome.

Project:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />

    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit.ConsoleRunner" Version="3.15.0-beta1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NunitXml.TestLogger" Version="3.0.117" />

  </ItemGroup>
</Project>

```

TestFixture class
```
using NUnit.Framework;
using System;

[SetUpFixture]
public class TestSuiteInitializer
{
    [OneTimeSetUp]
    public void RunBeforeAnyTests()
    {
        Console.WriteLine("Running One time setup in TestSuiteInitializer.");
    }

    [OneTimeTearDown]
    public void RunAfterAnyTests()
    {
        Console.WriteLine("Running One time tear down in TestSuiteInitializer.");
    }
}
```

Test Class
```
using NUnit.Framework;
using System.Linq;
using System.Net;
using System.Text.Json;
using System;

namespace TestingFramework.Tests.Api
{
    [Parallelizable(scope: ParallelScope.All)]
    [TestFixture]
    public class ToDoTests
    {
        [SetUp]
        public void Setup()
        {
            Console.WriteLine("Executing setup in class");
        }

        [Test(Description = "Post a To do on user")]
        public void CreateToDoOnUser()
        {
        }

        [Test(Description = "Post a To do without title")]
        public void PostToDoWithoudTitle()
        {
         }
   
        [Test(Description = "Post a To do without status")]
        public void PostToDoWithoutStatus()
        {
        }

        [Test(Description = "Post a To do without User Id")]
        public void PostToDoWithoutUserId()
        {
        }
    }
}

```
Output 
```
[]$ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
Microsoft (R) Test Execution Command Line Tool Version 17.0.0+68bd10d3aee862a9fbb0bac8b3d474bc323024f3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Executing setup in class

Executing setup in class

Executing setup in class

Executing setup in class

Passed!  - Failed:     0, Passed:     4, Skipped:     0, Total:     4, Duration: 15 s - 
```

**Comment by stevenaw** [comment] 2022-05-05 00:45
Thanks for the thorough code snippet and repro @MMark4 
`SetupFixture` will only run the setup/teardown functions for tests within its namespace (or child namespaces). Your setup fixture doesn't have a defined namespace which means it will be in the default global namespace, which may be different from the `TestingFramework.Tests.Api` namespace that your tests are in. It's possible that nunit isn't finding any tests relevant to the namespace of your setup fixture and so the setup/teardown aren't being run.

What happens if you put your setup fixture in the `TestingFramework` or `TestingFramework.Tests` namespace ?

**Comment by mikkelbu** [comment] 2022-05-05 09:26
A `SetupFixture` with no namespace should run for the entire assembly

https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html
> A SetUpFixture outside of any namespace provides SetUp and TearDown for the entire assembly.

@MMark4 You write "outside assembly" in the title. Are the setup in one assembly and the test in another assembly ?

I think the problem is that the Console.WriteLine in the SetUpFixture are not captured, but the methods are run (e.g. if I perform other actions - writing to a shared string, mutate some global state, then I can see the effect)

**Comment by stevenaw** [comment] 2022-05-05 10:35
Thanks for catching that @mikkelbu

**Comment by MMark4** [comment] 2022-05-05 13:01
Hi @mikkelbu , Right now I can answer that is running inside the assembly, for more insight this is the [repository](https://github.com/MMark4/TestingFrameworkTemplate/tree/experimenting) .

@stevenaw when Im back of the office I'll test those variants that you mention and be back with an answer

Thanks for the support!

**Comment by MMark4** [comment] 2022-05-28 20:29
Well sorry for the delay 
![image](https://user-images.githubusercontent.com/17988168/170841780-b1cf2e31-796c-4d4e-ac8e-8ece460f0d5c.png)

Good news, is that @mikkelbu is correct and the code is being executed, checked with debugger and voila!
![image](https://user-images.githubusercontent.com/17988168/170841818-15a7ce2c-3336-4375-804a-6e2cfd15bee6.png)

Still I suppose Console.Writeline not being captured is maybe an issue but a really minor one. I'll leave up to you if its the best to close the issue, or I can update the title and info in the ticket to correctly represent the issue.

Thanks again for the help and sorry for the delay.

**Closed** 2022-08-16 09:12 UTC
Labels: confirm
