### ISSUE TITLE
Test process won't exit if AfterTest method throws

### ISSUE THREAD

**Issue by HansLehnert** [nunit/nunit#4024] opened 2021-12-20 21:11 UTC
If the AfterTest method of a TestActionAttribute throws during execution, the test process will get stuck and never exit. I included a small repro below. I only see this happen on .NET Framework (I'm using 4.7.2), with .NET Core working fine.

I tried running using nunit3-console without passing any argument other than the .dll (`nunit3-console.exe Test.dll`), and from VS test explorer. Had similar results in both cases.

Versions:
- NUnit 3.13.2
- NUnit.ConsoleRunner 3.12
- NUnit3TestAdapter 4.0

```csharp
public class ActionAttribute : TestActionAttribute
{
    public override void BeforeTest(ITest test)
    {
    }

    public override void AfterTest(ITest test)
    {
        throw new Exception("Error during teardown");
    }

    public override ActionTargets Targets => ActionTargets.Default;
}

[TestFixture]
[Action]
public class TestClass
{
    [Test]
    public static void Test1()
    {
        System.Threading.Thread.Sleep(1000);
    }
}
```

**Comment by mikkelbu** [comment] 2021-12-20 21:28
This sounds like a duplicate of #2938

**Comment by stevenaw** [comment] 2022-04-26 03:19
I see similar but different behaviour under the following setup:

- NUnit 3.13.2
- NUnit3TestAdapter 4.0
- Visual Studio 2022 17.1.5

With the above snippet and run under net462, net472, and net6, I see netfx tests pass as expected but it's the net6 one which hangs and never finishes. Commenting out the `Thread.Sleep()` doesn't change this, but commenting out throwing the `Exception` does allow the runner to see the test has finished. This is when they are all run in the same run in the VS test explorer and "Run All". When run _individually_ it's a little different. net462 will complete, but both net472 + net6 seem to hang. 

The same behaviour can also e replicated on the latest versions of each (NUnit 3.13.3 + NUnit3TestAdapter 4.2.1).

While I can't quite explain the difference, it does strike me as a duplicate of #2938 . It's also almost certainly, as described there, an issue with the framework as it is happening in both console runner and the vs test runner.

**Comment by stevenaw** [comment] 2022-04-26 03:21
Charlie has alluded to what's likely the root cause here: https://github.com/nunit/nunit/issues/2938#issuecomment-406877132
I'm going to close this issue as a duplicate, but thanks for having reported it @HansLehnert, it's good to have brought this up on the radar.

**Closed by stevenaw** 2022-04-26 03:21 UTC
Labels: confirm
