### ISSUE TITLE
NUnit fails to match TestCase/TestCaseSource with generic test methods

### ISSUE THREAD

**Issue by damageboy** [nunit/nunit#3499] opened 2020-03-12 06:36 UTC
Hi,
I could not find indication if this sort of this is supposed to be supported and/if how, so I'm opening this issue for what seems almost a trivial case that is not supported by NUnit with respect to generic types. This might not be high on the list of stuff to support, but should at least be explicitly detected and reported, rather than lead to a crash, which is what is happenning now.

I've created a repro project where a few generic constructs clearly fail NUnit:
https://github.com/damageboy/genericnunit

Here's the sort of exception I'm encountering:
```bash
dotnet test
Test run for /tmp/gn/bin/Debug/netcoreapp3.1/gn.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
SetUp failed for test fixture gn.GenericTests
An exception was thrown while loading the test.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NUnit.Framework.Internal.GenericMethodHelper.TryApplyArgType(Type parmType, Type argType)
   at NUnit.Framework.Internal.GenericMethodHelper.TryGetTypeArguments(Object[] argList, Type[]& typeArguments)
   at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature(TestMethod testMethod, TestCaseParameters parms)
   at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(IMethodInfo method, Test parentSuite, TestCaseParameters parms)
   at NUnit.Framework.TestCaseAttribute.BuildFrom(IMethodInfo method, Test suite)+MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
No test is available in /tmp/gn/bin/Debug/netcoreapp3.1/gn.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.

```

What this boild down to is that Nunit is b0rked by even the following construct:

```csharp
[TestCase(new[] { 1 })]
public void GenericArrayShouldWork<T>(T[] data) { }
```

As well as more advanced constructs involving a `TestCaseSource` generating generic array, tuples with generic types, tuples with generic array, or generic classes.

**Comment by mikkelbu** [comment] 2020-03-12 15:47
I just examined this and I would say that it is a duplicate of #3259 (which will be part of the next release). You can get an NUnit build of master from https://www.myget.org/feed/nunit/package/nuget/NUnit.

The correction to #3259 will not solve the case `GenericTestCaseSourceDoesnt`, but here you also supply a sequence of `GenericTypeWrapper<float>` and the test expects a tuple. If I change the signature to `public void GenericTestCaseSourceDoesnt<T>(GenericTypeWrapper<T> input) { }` then this also work.

I'll close this issue as a duplicate, but we will still see additional comments/questions.

**Closed by mikkelbu** 2020-03-12 15:47 UTC
