### ISSUE TITLE
N unit parallel execution browser time out and socket error & one browser is up and running and another one is in active.

### ISSUE THREAD

**Issue by kumarbrandmuscle** [nunit/nunit#2884] opened 2018-06-07 15:12 UTC
Message: BrowserURLACE: OpenQA.Selenium.WebDriverException: no such session
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.17134 x86_64)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClasse.<XPath>b__c(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at BrandmuscleAutomation.Interactions.Clicks.Click(By by) in D:\classlibrary framework\ClassLibraryParallelruns\ClassLibraryParallelruns\Interactions\Clicks.cs:line 18
   at ClassLibraryParallelruns.Common.BrowserURLLaunch.BrowserURLACE(String BrowserPreferred, String RoleType) in D:\classlibrary framework\ClassLibraryParallelruns\ClassLibraryParallelruns\Common\BrowserURLLaunch.cs:line 161

Hi Team,
While running parallel execution I am facing the above error.
One browser is active and another one is inactive.
Tools:
Nunit:3.10.1.0
N unit Adapater:3.10.0

**Comment by CharliePoole** [comment] 2018-06-07 15:15
You need to provide some code to indicate what you are doing. If possible a simplified repro that we can test, if not, a sanitized version of your own test code that shows how you are using the parallel feature.

**Comment by kumarbrandmuscle** [comment] 2018-06-07 15:29
Hi Charlie,
please the attached zip format 

[ClassLibraryParallelruns.zip](https://github.com/nunit/nunit/files/2081075/ClassLibraryParallelruns.zip)

**Comment by CharliePoole** [comment] 2018-06-07 15:35
@kumarbrandmuscle Since you sent the zip, I assume you didn't intend to close this. 😄

**Comment by kumarbrandmuscle** [comment] 2018-06-07 15:36
ohhh.Thanks ..charlie

**Comment by CharliePoole** [comment] 2018-06-07 15:53
Your zip is a pretty complete project and not one anyone can run using pure nunit. I assume that the issue is your Dashboard fixtures?

```C#
    [TestFixture]
    [Parallelizable(ParallelScope.Fixtures)]
    public class ST_TC_6112_Dashboard2 : BrowserURLLaunch
    {
        [Test]
        [Category("CFM_ACE_SMOKE")]
        public void ST_TC_6112_User_Dashboard1()
        {
            log4net.Config.XmlConfigurator.Configure();
            ILog logger = LogManager.GetLogger(typeof(Dashboard_Landing));
            Thread.Sleep(20000);
            BrowserURLLaunch bl1 = new BrowserURLLaunch();
            bl1.BrowserURLACE("Chrome", "CORPORATE1");
            logger.Info("Login with CORPORATE");
            Dashboard_Landing.Dashboard_Landing_User();
            Driver.Quit();

            Thread.Sleep(20000);
        }
    }

    [TestFixture]
    [Parallelizable(ParallelScope.Fixtures)]
    public class ST_TC_6112_Dashboard1 : BrowserURLLaunch
        {
            [Test]
        [Category("CFM_ACE_SMOKE")]
        public void ST_TC_6112_User_Dashboard2()
        {
            Thread.Sleep(20000);
            BrowserURLLaunch bl2 = new BrowserURLLaunch();
            bl2.BrowserURLACE("Chrome", "LME1");
            //logger.Info("Login with LME");
            Dashboard_Landing.Dashboard_Landing_User();
            Driver.Quit();
        }
        }
```

You declare that both fixtures are Parallelizable. Note that this is no more than a __promise__ on your part, it doesn't actually cause them to be parallelizable if they are not. So let's see if they are.

They both inherit from the common class `BrowserURLLaunch`. THis is a fairly complicated class and I didn't analyze it completely. I do see, however, that it sets up a static Driver. That's enough to tell me that your class is not really parallelizable.

For two fixtures to run in parallel, they must not have any state at all unless it is readonly. Static state is, of course, shared state and having non-readonly statics always makes two fixtures unable to be run in parallell. Most folks wanting to run multiple browsers in parallel do so in a onetime setup method in the class. That method can be inherited so long as it doesn't use any shared state.

**Comment by CharliePoole** [comment] 2018-06-07 15:54
Closing this again as not an nunit issue. You can still ask followup questions on the issue and we'll see and answer.

**Closed by CharliePoole** 2018-06-07 15:54 UTC

**Comment by jnm2** [comment] 2018-06-09 21:33
I wonder if we could make a parallelism FAQ visible enough to help folks with this. I remember a few of these issues.

**Comment by CharliePoole** [comment] 2018-06-09 21:45
That makes sense to me.

**Comment by kumarbrandmuscle** [comment] 2018-06-13 10:13
Hi charlie,
I changed the driver as non static as public  IWebDriver Driver;
and webdriver interaction class as non static methods.
and driver is holding null.(Object reference is not set to reference)
Charlie,can you please tell me where i am missing.
Below is my code:
public class Base
    {
        public  IWebDriver Driver;
        
        
        //public void openbrowser()
        //{
        //    //var dir = Path.GetDirectoryName(typeof(Base).Assembly.Location);
        //    //Environment.CurrentDirectory = dir;
        //    //string path = dir;
        //    //Console.WriteLine(path);
        //    //Driver = new ChromeDriver(path + @"\Assets");
        //    //Driver.Manage().Window.Maximize();
        //}
        public  IWebDriver Driverclass()
        {
            if (Driver == null)
            {
                var dir = Path.GetDirectoryName(typeof(Base).Assembly.Location);
                Environment.CurrentDirectory = dir;
                string path = dir;
                Driver = new ChromeDriver(path + @"\Assets");
                Driver.Manage().Window.Maximize();
                return Driver;
            }
            else
            {
                return Driver;
            }
        }

    }
}
======
Interactions class
 public class BasicInteractions:Base
    {
        //private IWebDriver Driver;
        public BasicInteractions(IWebDriver Driver)
        {
            Base bc = new Base();
            this.Driver = bc.Driverclass();
        }

        #region Navigating to the URL
        public void GoToURL(string url)
        {
            //openBrowser();
            
         Driver.Navigate().GoToUrl(url);
        }
        public void Refresh()
        {
            Driver.Navigate().Refresh();
        }
        public void ScrollBy(int scroll)
        {
            IJavaScriptExecutor js = (IJavaScriptExecutor) Driver;
            js.ExecuteScript(" window.scrollBy(0, scroll);");

        }
        public string GetCurrentURL()
        {
            return Driver.Url;
        }

Can you please update me on this.ASAP.

**Comment by jnm2** [comment] 2018-06-13 13:20
@kumarbrandmuscle Edited your post to add [code fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) for syntax highlighting.

**Comment by mikkelbu** [comment] 2018-06-13 13:43
Hi @kumarbrandmuscle 
The code looks a bit odd. Questions/comments:
* Why are `BasicInteractions` accepting a `IWebDriver` in the constructor when you don't use it?
* You don't need to instantiate the base-class (the base-class constructor will be called implicitly, so you could just call `this.Driver = this.Driverclass()`. 
* Where exactly is the NullReferenceException thrown? (as far as I can tell Driver is set in the constructor and not changed afterwards).

**Comment by jnm2** [comment] 2018-06-14 12:10
@kumarbrandmuscle @mikkelbu has some good questions. I'm interested in hearing your answers?
