### ISSUE TITLE
Check for specific version of dotnet core tooling in Cake build

### ISSUE THREAD

**Issue by masaeedu** [nunit/nunit#2472] opened 2017-10-06 15:43 UTC
The Cake build checks whether a `dotnet` binary is available on the path before attempting to build the .NET standard projects, which is useful when you're just trying to test some changes and don't care about cross platform yet.

The problem is that a specific *version* of the `dotnet` tooling is required in order to build the projects (see [this Google groups discussion](https://groups.google.com/forum/#!topic/nunit-developer/QmfY2s9As1E)), and newer versions do not suffice. The `CheckIfDotNetCoreInstalled` bit in `build.cake` should verify the version of `dotnet` available is the correct one, not just that it is present on the PATH.

**Comment by mikkelbu** [comment] 2017-10-06 21:07
Hi @masaeedu I think this is a duplicate of #2111. If you disagree, then please reopen this issue.

**Closed by mikkelbu** 2017-10-06 21:07 UTC
