### ISSUE TITLE
Nunit 3.4.1 is not supporting Appium Page Objects based on Selenium Page objects (Nunit probably cannot get test assemblies)

### ISSUE THREAD

**Issue by szczechu** [nunit/nunit#1826] opened 2016-10-06 08:16 UTC
Visual Studio 2012 Premium Update 5.Net test solution
Nuget Packages installed:

Appium WebDriver 2.0.1.1
Selenium WebDriver v2.53.1 with dependencies
Nunit 3.4.1 with dependencies

Problems:
On Jenkins and Locally (Resharper runs Nunit3 Appium tests)

```
Error : MobileTests.ApplicationTests.ApplicationTests.FlowTest
System.IO.FileNotFoundException : Could not load file or assembly 'file:///C:\Program Files (x86)\Jenkins\workspace\WebDriver.Support.dll' or one of its dependencies. The system cannot find the file specified.
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
at System.Reflection.Assembly.LoadFrom(String assemblyFile)
at OpenQA.Selenium.Appium.PageObjects.ByFactory.From(FindsByAttribute attribute)
at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateDefaultLocatorList(MemberInfo member)
at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateBys(ISearchContext context, MemberInfo member)
at OpenQA.Selenium.Appium.PageObjects.AppiumPageObjectMemberDecorator.Decorate(MemberInfo member, IElementLocator locator)
at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(Object page, IElementLocator locator, IPageObjectMemberDecorator decorator)
at Apriso.Mobile.Framework.Pages.MobileAppPages.GetMobileAppPageTPage in c:\Program Files (x86)\Jenkins\workspace@2\src\Apriso.Mobile.Framework\Pages\MobileAppPages.cs:line 49
at MobileTests.ApplicationTests.ApplicationTests.SetupTest() in c:\Program Files (x86)\Jenkins\workspace@2\tests\MobileTests\ApplicationTests\ApplicationTests.cs:line 33
```

Nunit does not coppy required WebDriver.Support.dll to wokspace.

```
If I provide WebDriver.Support.dll manually, then:
MobileTests.ApplicationTests.ApplicationTests.FlexParts
System.NullReferenceException : Object reference not set to an instance of an object.
at OpenQA.Selenium.Appium.PageObjects.ByFactory.From(FindsByAttribute attribute)
at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateDefaultLocatorList(MemberInfo member)
at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateBys(ISearchContext context, MemberInfo member)
at OpenQA.Selenium.Appium.PageObjects.AppiumPageObjectMemberDecorator.Decorate(MemberInfo member, IElementLocator locator)
at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(Object page, IElementLocator locator, IPageObjectMemberDecorator decorator)
at Apriso.Mobile.Framework.Pages.MobileAppPages.GetMobileAppPageTPage in c:\Program Files (x86)\Jenkins\workspace@2\src\Apriso.Mobile.Framework\Pages\MobileAppPages.cs:line 48
at MobileTests.ApplicationTests.ApplicationTests.SetupTest() in c:\Program Files (x86)\Jenkins\workspace@2\tests\MobileTests\ApplicationTests\ApplicationTests.cs:line 33
```

Pages are created in function:

``` c#
public static TPage GetMobileAppPage() where TPage : new()
{
var page = new TPage();
PageFactory.InitElements(Android.Driver, page, new AppiumPageObjectMemberDecorator());
return page;
}
```

It appears that Nunit 3.4.1 is not supporting AppiumPageObjectMemberDecorator().

Under Nunit 2.6.4 everything is working.

Tests executed locally by resharper or from Windows Batch command:

``` bat
.\packages\NUnit.Runners.3.4.1\tools\nunit3-console.exe --labels all ".\tests\MobileTests\bin\Release\MobileTests.dll" --where "cat == Android" --result="selenium-testresult.xml";format=nunit2 exit %%ERRORLEVEL%%
```

Are throwing above errors.

When test will be runned from test DLL directory, everything is working fine:

``` bat
cd tests\MobileTests\bin\Release ..\..\..\..\packages\NUnit.Runners.3.4.1\tools\nunit3-console.exe --labels all ".\MobileTests.dll" --where "cat == Android" --result="selenium-testresult.xml";format=nunit2 exit %%ERRORLEVEL%%
```

Also Installed Visual Studio extension 'Nunit 3 Test Adapter', and it is throwing error:

```
Result Message: System.IO.FileNotFoundException : Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\WebDriver.Support.dll' or one of its dependencies. The system cannot find the file specified.
```

**Comment by rprouse** [comment] 2016-10-25 03:00
I expect that `WebDriver.Support.dll` is being found, but that it has dependencies that are not found when run from another directory. To be honest, I think this is more a question for Appium. Do they do any static initialization that requires the current directory be set?

**Comment by szczechu** [comment] 2016-11-07 13:48
No static directory have to be set.
I changed Page Object to use only Selenium native methods instead of Appium.
Now I have to copy manually WebDriver.Support.dll into Resharper or Visual Studio (for Nunit 3 Test Adapter). After that tests are running with success.
If Nunit 3 Test Adapter and Resharper have same issue then tis is not an Appium problem.
Same Dll is referenced in test project in Visual Studio, why Nunit3 is not using this dll?

**Comment by rprouse** [comment] 2016-11-07 17:00
@szczechu is the `WebDriver.Support.dll` in your test directory? What errors do you see in the Visual Studio output pane under Tests when running using the Visual Studio Adapter?

**Comment by szczechu** [comment] 2016-11-08 07:59
This DLL is in ..bin\Debug catalog after solution build.
After using native selenium PageObjects NunitTestAdapter is running tests with success.

When creating page:
`        public static TPage GetMobileAppPage<TPage>() where TPage : new()
        {
            var page = new TPage();
            PageFactory.InitElements(Android.Driver, page, new AppiumPageObjectMemberDecorator());
            return page;
        }`
MESSAGE:
System.IO.FileNotFoundException : Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\WebDriver.Support.dll' or one of its dependencies. The system cannot find the file specified.

Changing to selenium WebDriver implementation fixes the problem:
`        public static TPage GetMobileAppPage<TPage>() where TPage : new()
        {
            var page = new TPage();
            PageFactory.InitElements(Android.Driver, page);
            return page;
        }`

For Resharper there needs to be done workaround in OneTimeSetUp method:
`            var sourcePath = TestContext.CurrentContext.TestDirectory;
            var destPath = TestContext.CurrentContext.WorkDirectory;
            // Copy required file required by Nunit3.
            var fileName = "WebDriver.Support.dll";
            var destFile = Path.Combine(destPath, fileName);
            File.Copy(Path.Combine(sourcePath, fileName), destFile, true);`
            
Maybe this is related to Appium and Resharper not working with Nunit3.

For now problem is resolved by above workarounds (and creating page elements using WebDriver, not IMobileElement<AppiumWebElement>).

**Comment by rprouse** [comment] 2016-12-01 20:51
I am going to close this as not our bug. Feel free to reopen if you can show it is an NUnit bug and not one of the other frameworks.

**Closed by rprouse** 2016-12-01 20:51 UTC
Labels: confirm

**Comment by siggerzz** [comment] 2017-03-15 16:21
Has anyone got any closer to figuring out the cause of this? I'm also experiencing the [same issue](https://github.com/appium/appium-dotnet-driver/issues/173)

I've had this issue for days and I not really sure what to do and who to raise the issue with.

Cheers

**Comment by lanzelot1989** [comment] 2017-06-13 09:46
I am also facing this issue with test runners that are able to start tests from Visual Studio, i tried both:
* Resharper Unit Testing and
* NUnit VS Adapter

The problem seems to be this line in ByFactory:
https://github.com/appium/appium-dotnet-driver/blob/master/appium-dotnet-driver/Appium/PageObjects/ByFactory.cs#L32

I think the problem can be generalized and would occur when a loaded DLLs tries to load another DLL.

As an additional info: when using the nunit-console3.exe everything works as expected.
