### ISSUE TITLE
Retry Decorator does not retry test if fail cause is an exception

### ISSUE THREAD

**Issue by randersen** [nunit/nunit#1388] opened 2016-04-04 22:44 UTC
In nunit 3.2...

When a test method has the Retry(int) decorator set and fails because of an uncaught exception (Happens quite often in my API integration tests and is expected) nunit does not retry the test. 

If the fail goes through an nunit assert it retries successfully.

**Comment by CharliePoole** [comment] 2016-04-04 23:00
This is by design. An uncaught exception is considered an error in the test and is reported as an error rather than a failure. Most folks don't notice the difference, but there is one.

If you want the test to fail in case of a particular exception on a particular call, wrap it in Assert.DoesNotThrow().

**Comment by randersen** [comment] 2016-04-04 23:05
Dang, was worried this is just the way it works. It really is difficult to anticipate every single exception that could ever happen in an API call, so i've been treating them failures.  Suppose i will have to make my own decorator, thanks!

**Comment by CharliePoole** [comment] 2016-04-04 23:07
Of course, you could put all the code in the test under Assert.DoesNotThrow, saving the effort of anticipating what might throw an exception. However, then you won't know if the exception comes from some code that you thought should not throw. As a compromise, you could specify where an exception might be thrown without specifying the Type of the exception.

**Comment by randersen** [comment] 2016-04-04 23:09
Good point, I think i can make that work. Thanks!

**Comment by jnm2** [comment] 2017-11-09 17:48
Reopening since @CharliePoole indicated that @LirazShay made a good case ([here](https://github.com/nunit/nunit/issues/2543#issuecomment-343125459)) that this feels like a hack when you'd doing it to a large number of methods.

Another argument in favor of this occurred to me. It would allow the exception to just be reported as a normal exception rather than having a `DoesNotThrow or `Throws.Nothing` constraint message on top, once the retries are exhausted.

**Comment by mitchellmaler** [comment] 2017-12-11 04:22
Would it make sense to allow to specify explicit exception types that I would want tests to be retried along with a retry on any exception.

An example is when using unreliable selenium grid testing where the network/api calls sometimes timeout will throw a WebDriverException. I know those can happen and would like the test to retry only if that exception is received but treat all others as errors.

What I don't want to do is wrap every test method with code just to catch this unexpected exception that could be retried and pass.

**Comment by jnm2** [comment] 2017-12-11 10:47
That sounds useful.

**Comment by nobrayner** [comment] 2019-12-13 05:30
Has there been any progress on this? I am also finding that due to Web Driver instability - i.e. Random crashes - retrying the test will almost always pass successfully.

It has been rather annoying spending the last hour perusing issues, seeing comments that make it seem like something will happen, only to find all the related issues are still open, with nothing done!

**Comment by CharliePoole** [comment] 2019-12-13 06:16
This has been marked as an "idea" for more than two years, since @jnm2 reopened it. If nobody intends to push it forward, it might be kinder to reclose the issue.

**Comment by LirazShay** [comment] 2019-12-15 11:14
I think this issue should be fixed, as I explained here -https://github.com/nunit/nunit/issues/2543#issuecomment-343125459
Many teams use nunit framework for integration tests with UI based frameworks and sometimes test fails due to instability of the external libraries, for example IEDriver for Internet Explorer sometime may crash
At least we can add parameter to ignore exceptions or not

Something like this:
```
[Test, Retry(3, RetryOnException = true)]
public void Login()
{
    step.BasicActions.LoginAndOpenPart15038(_driver);
    Assert.True(false == _driver.Url.Contains("login.html"));
}
```

**Comment by delgesso** [comment] 2020-03-19 00:57
I totally agree with @LirazShay 
I understand the ideological resistance to the idea of the retries, within the logic of micro unit testin
The following list is not even comprehensive, it's all off the top of my head. 
We use nUnit as our runner for very complex UI autotests, that is a mix of:
Server side: several services spinning at the start of every test and stopped at the end of every test, these servers include technologies like WCF, Akka actors, ZeroMQ, NATS queues, then some XML and various insertion of Oracle scripts, then some API tests (some in C# and some in F#), 
Client side: then interacting with a rich UI that has WPF, WinForms, DevExpress components
Sometimes we have to test multi user scenarios, where several clients are started at the same time.
Oh, and we use a third party UI autotest tool, TeamCity agents as our build/deployment agents, and a bunch of scripts that get the artifacts from many GitHub repositories.
Now, this is not a straight case of: input/output validation of micro unit tests.
So, yes, despite how hard we try, some tests have a 1% to 5% flakyness, and Retry would be an amazing way to eliminate the need for investigating false negatives. And the confidence in these tests would increase enormously, as regression test suite, if we stopped seeing "red" results for unknown reasons.
We consider anything under 95% unacceptable anyway, but on the other hand it is not realistic to achieve 100% on UI tests on the architecture I described above.

So what is the suggested workaround if the above suggestions (e.g. [Test, Retry(3, RetryOnException = true)] ) were not deemed viable?
It is for us impossible to predict the whole range of exceptions that may happen, and sometimes it is just a matter of the test timing out (over one of god-knows-which amongst the various hoops that the test had to go through)

**Comment by CharliePoole** [comment] 2020-03-19 01:46
As previously explained, I personally don't have a dog in this fight but I'll make a couple of observations:

1. Characterizing the opinions of those who disagree with you as "ideological" is name-calling. Please stop doing that and stick with the actual arguments, which make up most of your post but are clouded by the initial ad hominem argument.

2 Is there some reason the recommended approach of using `Assert.DoesNotThrow` or a similar call to convert the exception to a failure doesn't work for you?

**Comment by rprouse** [comment] 2020-05-18 18:27
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Closed by rprouse** 2020-05-18 18:27 UTC
Labels: is:idea

**Comment by CharliePoole** [comment] 2023-09-26 19:09
Have you tried just throwing your own AssertionException with your custom exception as the InnerException? AFAIR NUnit will ignore the inner exception but you could use it in your own reporting. And of course Retry would then work.
