### ISSUE TITLE
TestCaseSource of single element array generates test data of that element?

### ISSUE THREAD

**Issue by jeremymeng** [nunit/nunit#1375] opened 2016-03-25 07:55 UTC
May be related to #1327?

The following passed in 2.6.4 but failed in 3.2.0

```csharp
using NUnit.Framework;
using System.Collections.Generic;

namespace NUnitTest
{
    [TestFixture]
    public class Class1Tests
    {
        protected static IEnumerable<object> ValidValues
        {
            get
            {
                yield return new object[] { 10 };
            }
        }

        [Test]
        [TestCaseSource("ValidValues")]
        public void IsValid_should_return_true_for_valid_values(object validValue)
        {
            Assert.AreEqual("System.Object[]", validValue.GetType().ToString());
        }
    }
}
```

Result:
```
1) Failed : NUnitTest.Class1Tests.IsValid_should_return_true_for_valid_values(10)
  Expected string length 15 but was 12. Strings differ at index 7.
  Expected: "System.Object[]"
  But was:  "System.Int32"
  ------------------^
at NUnitTest.Class1Tests.IsValid_should_return_true_for_valid_values(Object validValue) in c:\users\myumyu\documents\visual studio 2015\Projects\NUnitTest\NUnitTest\Class1Tests.cs:line 22
```

**Comment by CharliePoole** [comment] 2016-03-25 15:40
I'm pretty sure this is a duplicate of #1327 and is fixed in PR #1354

**Comment by jeremymeng** [comment] 2016-03-25 19:12
Great! Good to know that it's fixed.

**Comment by CharliePoole** [comment] 2016-03-25 19:38
The fix will be in CTP-9 by the end of this month. I'll try to verify your specific case.

**Comment by rprouse** [comment] 2016-04-07 14:58
Marking as confirm so that we can confirm if it is fixed.

**Comment by rprouse** [comment] 2016-06-23 13:36
No further reports, so closing.

**Closed by rprouse** 2016-06-23 13:36 UTC
Labels: status:confirm
