### ISSUE TITLE
Error downloading Nunit documentation

### ISSUE THREAD

**Issue by AerialBoat95** [nunit/nunit#3069] opened 2018-10-18 07:03 UTC
Everyone is seeing this problem located here

https://stackoverflow.com/questions/52867826/how-do-i-download-the-whole-projects-docs-in-github-as-pdf/52868377?noredirect=1#comment92650612_52868377

You can do it with Github Wikito Converter:

```
npm install -g github-wikito-converter
git clone https://github.com/nunit/docs.wiki.git
gwtc ./docs.wiki
```

**Error**
last step I received this error Unhandled rejection Error: Unknown language: "C#"

**Comment by CharliePoole** [comment] 2018-10-18 07:57
Doesn't appear to be an NUnit problem. Sounds like the program is failing on encountering code requiring c# formatting.

**Comment by rprouse** [comment] 2018-10-18 15:22
I am closing this. C# is a valid language identifier in GitHub's Markdown, so it is an issue with the converter or one of the NPM packages it uses. If you can show that it is an NUnit problem, we can reopen, but it belongs in the docs repository.

**Closed by rprouse** 2018-10-18 15:22 UTC

**Comment by CharliePoole** [comment] 2018-10-18 20:33
It's entirely possible that the NUnit wiki uses some feature that's not supported by the app in question. If we knew what it was, we could decide whether and how to fix it by changing the wiki. Or it might be a feature we consider too important to drop.

It comes down to a question of who is in a better position to figure out what the cause if the problem might be. It seems obvious that would have to be the author of Wikito, which we know nothing about.

Closing the issue is our transparent way of letting you know we are not currently working on it. A post from that author telling us what we would need to do would likely get it reopened.

**Comment by mikkelbu** [comment] 2018-10-19 00:16
@AerialBoat95 I think that you are raising this issue in the wrong place. NUnit just uses the markdown format of github (and several other places), and it seems like the tool you are using does not understand fenced code blocks with "C#" as the language identifier.

If you go to and search for issues with the text "Unknown language" in the github-wikito-converter project, then you'll get https://github.com/yakivmospan/github-wikito-converter/search?q=Unknown+language&type=Issues which shows that the tool also have problems with blocks marked with "text" and "solidity". The author of the tools proposes to replace unknown languages like "```c#" with the default "````" (note that you will loose the syntax highlighting.

He also notes that github-wikito-converter uses marked for the highlighting, see https://github.com/markedjs/marked. But some searching on marked just sends us on to Highlight.js, see https://github.com/highlightjs/highlight.js, and from that it seems that it does not understand the identification "C#", only "cs" and "csharp". I've tried to find out exactly what github (and others) allow, but the best seems to be https://github.com/jmm/gfm-lang-ids/wiki/GitHub-Flavored-Markdown-(GFM)-language-IDs. So it seems that Github and highlight are not in sync. We probably could replace all C# identifier with e.g. csharp on the wiki, but I think that it would be better if highlight.js also could handle the C# identifier.

I don't think that NUnit is the only one having issues. I guess that the following wiki will also give you problems (since they are also using fenced code blocks with C# syntax highlighting)
* https://github.com/dotnet/roslyn/wiki
* https://github.com/dotnet/corefx/wiki
* ...

**Comment by mikkelbu** [comment] 2018-11-03 18:13
Note that highlight.js has been updated to understand `c#`, see highlightjs/highlight.js#1881.
