### ISSUE TITLE
Test adapter sent back results for unknown test

### ISSUE THREAD

**Issue by amado-saladino** [nunit/nunit#3237] opened 2019-05-08 21:56 UTC
**Given** I have json file to read data from
I wrote this method as data source for my test method:

```
private static IEnumerable<TestCaseData> data()
        {
            foreach (var product in DataFactory.GetData("data.json", "products"))   
            {
                yield return new TestCaseData(product["keyword"].ToString(), product["name"].ToString());
            }            
        }
```
and my test method looks like:

```
[TestCaseSource("data"), Property("Description", "It should search for the product")]
        public void SearchProduct(string keyword, string productName)
        { ...
```
**When** My test method runs fine with no problem
**Then** I should get the test results for each iteration in Test Explorer
**But** instead I got a message in console 'Test adapter sent back results for unknown test'... ignoring result for the test'
![image](https://user-images.githubusercontent.com/20227574/57405120-ebd7a480-71dd-11e9-91d9-04960cb1ed98.png)

**Note**: This does not happen when I use static data data source

**Comment by CharliePoole** [comment] 2019-05-09 01:57
In order to function under the VS adapter, your method must be repeatable. In that environment, it will be called twice, once at the time of discovery and once at the time of execution, under two entirely different processes. So it's possible that the problem is in your implementation of your DataFactory.

You can confirm this by running the same tests under the nunit3-console, which doesn't suffer from the same architectural problem and only calls the data source method once.

**Comment by amado-saladino** [comment] 2019-05-09 10:27
I also tried running nunit3-console and got the same. And here is DataFactory class

[DataFactory.zip](https://github.com/nunit/nunit/files/3161584/DataFactory.zip)

**Comment by CharliePoole** [comment] 2019-05-09 11:20
"Test adapter sent back..." message is from Visual Studio, so you can't have got that message from running nunit3-console. What exactly did you get?

**Comment by amado-saladino** [comment] 2019-05-09 14:12
It may have run well.
![image](https://user-images.githubusercontent.com/20227574/57460261-0f99f980-7275-11e9-8626-9148e01b2c25.png)

**Comment by CharliePoole** [comment] 2019-05-09 14:40
Looks like it did although one test failed. In that case, for the VA adapter, make sure your generating code is not leaving the data file open.

**Comment by amado-saladino** [comment] 2019-05-09 14:48
The failure is due to difference in both expected and actual results

**Comment by mikkelbu** [comment] 2021-08-28 11:33
I'm closing this issue as I think that Charlie have already answered it https://github.com/nunit/nunit/issues/3237#issuecomment-490713514, and we cannot do much about changing data in data sources.

**Closed by mikkelbu** 2021-08-28 11:33 UTC
