### ISSUE TITLE
build and build.cmd scripts invoke nuget.exe improperly

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/nunit#778] opened 2015-08-17 17:56 UTC
# ./build nunit.linux.sln
        ./build: line 2: ./tools/nuget.exe: cannot execute binary file: Exec format error
        XBuild Engine Version 12.0
        Mono, Version 4.0.3.0
        Copyright (C) 2005-2013 Various Mono authors
        
        Build started 8/17/2015 8:18:27 PM.

Linux loader in kernel should have capabilites to run .net images like native executables.
https://www.kernel.org/doc/Documentation/binfmt_misc.txt

http://www.mono-project.com/archived/guiderunning_mono_applications/

The presence of this capabilities can be checked from script (zgrep /proc/config.gz, if it is enabled)

If the capability not present, then one should launch program with
mono ... nunit.exe
(but this is bad for gentoo to trust external binaries, so maintainer will wipe this with patch anyway)

At least it is good to check program exit codes in scripts.

**Comment by CharliePoole** [comment] 2015-08-17 18:52
@chris-smith-zocdoc Please take this comment as the description of the issue, rather than the original above. The original gives useful general info but doesn't actually say what the problem is.

When you fixed issue #125, you modified both scripts to include the restore. The primary issue is that you are invoking nuget.exe, a managed program, without the mono prefix. Apparently, the OS we run under on travis implements binfmt to support .NET execution, so the prefix is not needed. Our general policy, in keeping with the mono distribution guidelines is to use the prefix all the time. This is a surprise to me, because I didn't know that nuget.exe is a managed program.

The build script should always use 'mono'.

The build.cmd script could use 'mono' when you are using xbuild but probably doesn't have to.

One added question: Did you consider leaving the build scripts alone and putting the restore into NUnit.proj? This would mean, of course, that we would have to use NUnit.proj for all our batch builds, but we can certainly do that if necessary.

I'm assigning this back to you since you worked on the initial fix. Let me know if it's a duplicate of the other one I assigned.

**Comment by ArsenShnurkov** [comment] 2015-08-17 20:41
"Please comment on #778 regarding what error checking you would like to see in which of our scripts. "

if there is an error, the script should stop. If you throw away the information - this creates various additional risks (of nonupdated packages with malicious code and so on).

It shouln't start building and hope that another error occurs and display the information which you thrown away before.

for bash see http://www.davidpashley.com/articles/writing-robust-shell-scripts/#idm5413512
if [ "$?"-ne 0]; then echo "command failed"; exit 1; fi

**Comment by CharliePoole** [comment] 2015-08-17 20:56
Fair enough. We have been treating these scripts as only used by us at the command line and they only wrapped a single command up to now. But they may be used by other scripts, as you point out.

@chris-smith-zocdoc If you retain the call to nuget in the script, we should check the return code. I think you work on linux, right? If not, you can re-assign it to me.

**Comment by chris-smith-zocdoc** [comment] 2015-08-17 21:55
I won't have time for a couple of days so I assigned it back to you @CharliePoole 

I've tested on linux but I don't primarily work there

**Comment by CharliePoole** [comment] 2015-08-17 23:37
OK. I'll take care of it.

**Closed** 2015-08-18 01:41 UTC
Labels: is:bug, is:build, pri:high
