### ISSUE TITLE
Can I run test within main thread as nunit 2x "/nothread" option

### ISSUE THREAD

**Issue by levimm** [nunit/nunit#1711] opened 2016-07-28 02:30 UTC
Hi Guys,

I was using Nunit 2x console-runner.dll to run the test with parameter "/nothread" so the test is run within the main thread. When I switch to Nunit 3x, I use nunitlite.dll so no new process is used to run the test. But it always create a new thread to run it. I check the newly added SingleThreaded attribute with no success. Is there a way to run the test within main thread now?

Cheers

**Comment by CharliePoole** [comment] 2016-07-28 04:20
No. This option actually had no effect in the last few releases of NUnit 2 and we removed it in NUnit 3.

The single-threaded attribute is defined in the docs: it causes all parts of a fixture (OneTimeSetUp, OneTimeTearDown and every test) to be run on the same thread. But you don't control what that thread is - it's created by NUnit.

What problem are you trying to solve here? Why do you want to run on the main thread?

**Comment by levimm** [comment] 2016-07-28 08:03
Thanks, Charlie. I'm using thread local storage to do some initialization of each thread. I can control the main thread but not the thread created by nunit. Do you have any suggestions for this kind of issue?

**Comment by CharliePoole** [comment] 2016-07-28 15:24
There's no way because nunit needs to control threads in a parallel environment.

Can you explain what kind of initialization you need to do? Maybe we can figure out a way to get NUnit to do it for you.

**Comment by CharliePoole** [comment] 2016-08-07 23:16
Closing this as not a bug. I'll be glad to suggest alternatives if you can provide a bit more info on what kind of initialization you need to do.

**Closed by CharliePoole** 2016-08-07 23:16 UTC
Labels: closed:notabug

**Comment by NecroFilja** [comment] 2020-07-27 09:08
> Closing this as not a bug. I'll be glad to suggest alternatives if you can provide a bit more info on what kind of initialization you need to do.

 @CharliePoole 
Just found this issue when trying to migrate from NUni2 to NUnt3. Our test starting to failing after migration.
We have very specific tests that uses some old COM/ActiveX based component. It requires X86 platform, STA , single thread and we need to create specific ComActivationContext.
We do creation of ComActivationContext and some init in SetUpFixture->OneTimeSetUp as it is expensive. We also have some initialization inside of OneTimeSetUp, SetUp of text fixture. We applied everything that we could through flags of nunit 3 but it still fails. I double checked and all setup/onetimesetup/tests run on the same thread. But this is not enough.
System.InvalidOperationException : DragDrop registration did not succeed.
  ----> System.ComponentModel.Win32Exception : The application called an interface that was marshalled for a different thread

Our command line for nuinit 2 was:
 /noshadow /nothread (and STA through assembly attribute)

For nunit3 command line is even more aggressive and it doesn't help:
--x86 --workers=0 --domain=None --process=Single  (please not that I have rebuild nunit-console under x86 otherwise I could not run both x86 and single)

The only thing that helped me to resolve and run tests is to manually in debug change RunOnMainThread to true (internal flag).
It will be nice if RunOnMainThread  somehow could be configured outside.

**Comment by CharliePoole** [comment] 2020-07-27 14:43
Have you tried the `ApartmentAttribute` to require running the test in the STA?

**Comment by NecroFilja** [comment] 2020-07-27 20:07
yes. we are using assembly level [assembly: Apartment(ApartmentState.STA)]
