### ISSUE TITLE
Getting Exception NUnit.Engine.NUnitEngineException, Exception thrown unloading tests from... after running nunit tests

### ISSUE THREAD

**Issue by ayankumaar** [nunit/nunit#3777] opened 2021-02-25 12:16 UTC
I am running the following command to execute NUnit tests 

**dotnet test --filter "TestCategory=Santity"  "C:\\MyTests\\Workspace\\Mytest\\bin\\x64\\Debug\\net472\\MyTest.exe"**

My project is targeting **.NET 4.7.2**. I have the following packages added in the csproj file

  **PackageReference Include="nunit" Version="3.11.0" 
   PackageReference Include="NUnit3TestAdapter" Version="3.10.0" 
   PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.8.0" 
   PackageReference Include="NUnitLite" Version="3.11.0"** 
   
At the end of the execution, it is throwing the following exception
   
Exception NUnit.Engine.NUnitEngineException, Exception thrown unloading tests from C:\\MyTests\\Workspace\\Mytest\\bin\\x64\\Debug\\net472\\MyTest.exe
Exception encountered unloading AppDomain
   at NUnit.Engine.Services.DomainManager.DomainUnloader.Unload()
   at NUnit.Engine.Runners.TestDomainRunner.UnloadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at NUnit.Engine.Runners.MasterTestRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.MasterTestRunner.Dispose()
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter) in XX:\XXXX\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 314
Innerexception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at NUnit.Engine.Services.DomainManager.DomainUnloader.UnloadOnThread()
   
   **Irrespective of my scripts pass or fail, this exception is thrown. Is there anything that needs to be taken care of to stop this exception ?**

**Comment by rprouse** [comment] 2021-02-25 14:06
We haven't seen this in a long time. This is usually caused by a thread in your code not aborting. Since your test is 4.7.2, you could try running the test using the NUnit Console with the `--inprocess` flag from Visual Studio in the debugger and break on the `CannotUnloadAppDomainException`. You can then inspect the threads window to see which of your threads is still running.

To do this, 

- open the test project properties in VS, 
- go to the debug pane
- switch Launch to Executable
- In the Executable, enter the full path to `nunit3-console.exe`
- For the arguments, `--inprocess  "C:\MyTests\Workspace\Mytest\bin\x64\Debug\net472\MyTest.exe"` (you may also want to add your filter)
- Open the Exception Settings and set it to break on the `CannotUnloadAppDomainException`
- F5 to debug your tests, wait for the exception
- Open the Threads window and go through all the threads inspecting the callstack

> If a thread does not abort, for example because it is executing unmanaged code, or because it is executing a finally block, then after a period of time a CannotUnloadAppDomainException is thrown in the thread that originally called Unload. If the thread that could not be aborted eventually ends, the target domain is not unloaded. Thus, in the .NET Framework version 2.0 domain is not guaranteed to unload, because it might not be possible to terminate executing threads.

See #329

**Comment by ayankumaar** [comment] 2021-02-25 14:15
@rprouse Thank you very much for your reply. We are not using Visual Studio. But, we are using VS Code. Can you tell me how to debug this using VS Code ?

**Comment by rprouse** [comment] 2021-02-25 23:17
You need to add a launch configuration with similar values. I haven't done it, but the instructions are at https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

**Comment by ChrisMaddock** [comment] 2021-03-01 22:57
I think if you upgrade your version of NUnit3TestAdapter, you won't see this as an error anymore. I would recommend looking into the source of the error though as rprouse describes - it's likely that there is some resource in use that's not being disposed of properly.

**Comment by ChrisMaddock** [comment] 2021-03-27 12:42
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂

**Closed by ChrisMaddock** 2021-03-27 12:42 UTC
Labels: is:question
